export const RECETTES_ASSEMBLAGES = [

  /* ── 1. Entremet chocolat noir & passion ─────────────────────────────── */
  {
    id: "entremet-chocolat-passion",
    type: "assemblage",
    nom: "Entremet chocolat noir & passion",
    categorie: "assemblages",
    sous_categorie: "entremet_moule",
    description: "Mousse chocolat noir 64% sur inserts mousseline et gelée passion-abricot, biscuit chocolat, glaçage miroir. Pour 3 entremets ø 20 cm.",
    masse_totale_g: 9610,
    composants: [
      {
        nom: "Biscuit chocolat",
        masse_g: 3203,
        ingredients: [
          { nom: "Sucre semoule",   g: 751,  pct: 23, role: "sucrant"   },
          { nom: "Farine",          g: 609,  pct: 19, role: "structure" },
          { nom: "Levure chimique", g: 42,   pct: 1,  role: "structure" },
          { nom: "Poudre de cacao", g: 100,  pct: 3,  role: "parfum"    },
          { nom: "Huile végétale",  g: 290,  pct: 9,  role: "mg"        },
          { nom: "Œufs entiers",    g: 1000, pct: 32, role: "liant"     },
          { nom: "Lait entier",     g: 411,  pct: 13, role: "eau"       },
        ],
        procede: [
          "Préchauffer le four à 180°C chaleur tournante.",
          "Mélanger les ingrédients secs avec l'huile et les œufs, fouetter 6 min vitesse haute. Ajouter le lait, 2 min vitesse moyenne.",
          "Répartir sur plaques chemisées et cuire 10–15 min. Réserver.",
        ],
      },
      {
        nom: "Mousseline fruit de la passion",
        masse_g: 1376,
        ingredients: [
          { nom: "Gélatine en feuilles",         g: 13,  pct: 1,  role: "gelifiant" },
          { nom: "Purée de fruit de la passion", g: 350, pct: 25, role: "fruit"     },
          { nom: "Crème liquide 35%",            g: 200, pct: 14, role: "mg"        },
          { nom: "Lait entier",                  g: 100, pct: 7,  role: "eau"       },
          { nom: "Poudre de lait écrémé",        g: 35,  pct: 3,  role: "structure" },
          { nom: "Jaunes d'œufs",               g: 108, pct: 8,  role: "liant"     },
          { nom: "Sucre semoule (crème)",        g: 100, pct: 7,  role: "sucrant"   },
          { nom: "Fécule de maïs",               g: 50,  pct: 4,  role: "structure" },
          { nom: "Blancs d'œufs",               g: 160, pct: 12, role: "aeration"  },
          { nom: "Sucre semoule (meringue)",     g: 210, pct: 15, role: "sucrant"   },
          { nom: "Eau",                          g: 50,  pct: 4,  role: "eau"       },
        ],
        procede: [
          "Réhydrater la gélatine.",
          "Porter purée, crème, lait et poudre de lait à ébullition. Verser sur le mélange jaunes-sucre-fécule. Cuire à consistance de crème pâtissière. Incorporer la gélatine. Laisser tiédir.",
          "Cuire sucre + eau à 121°C, verser en filet sur les blancs montés : meringue italienne. Incorporer à la crème tiède.",
          "Couler en moules à insert et surgeler.",
        ],
      },
      {
        nom: "Gelée passion-abricot",
        masse_g: 662,
        ingredients: [
          { nom: "Sucre semoule",                g: 105, pct: 16, role: "sucrant"   },
          { nom: "Pectine NH",                   g: 12,  pct: 2,  role: "gelifiant" },
          { nom: "Purée de fruit de la passion", g: 200, pct: 30, role: "fruit"     },
          { nom: "Purée d'abricot",             g: 250, pct: 38, role: "fruit"     },
          { nom: "Glucose",                      g: 75,  pct: 11, role: "sucrant"   },
          { nom: "Jus de citron",               g: 20,  pct: 3,  role: "acidite"   },
        ],
        procede: [
          "Mélanger sucre et pectine.",
          "Chauffer les purées avec le glucose à 40°C. Incorporer sucre-pectine, porter à ébullition. Hors du feu, ajouter le jus de citron.",
          "Couler en moules à insert et surgeler.",
        ],
      },
      {
        nom: "Mousse chocolat noir 64%",
        masse_g: 3475,
        ingredients: [
          { nom: "Gélatine en feuilles", g: 15,   pct: 0.5, role: "gelifiant" },
          { nom: "Crème liquide 35%",    g: 330,  pct: 9.5, role: "mg"        },
          { nom: "Lait entier",          g: 330,  pct: 9.5, role: "eau"       },
          { nom: "Jaunes d'œufs",       g: 130,  pct: 4,   role: "liant"     },
          { nom: "Sucre semoule",        g: 70,   pct: 2,   role: "sucrant"   },
          { nom: "Couverture noir 64%",  g: 1400, pct: 40,  role: "parfum"    },
          { nom: "Crème montée",         g: 1200, pct: 34.5,role: "aeration"  },
        ],
        procede: [
          "Réhydrater la gélatine.",
          "Porter crème et lait à ébullition. Verser sur jaunes-sucre, cuire à 82°C (crème anglaise). Incorporer la gélatine.",
          "Verser sur le chocolat et émulsionner. Laisser refroidir à 35°C. Incorporer délicatement la crème montée.",
        ],
      },
      {
        nom: "Glaçage chocolat",
        masse_g: 894,
        ingredients: [
          { nom: "Gélatine en feuilles", g: 24,  pct: 3,  role: "gelifiant" },
          { nom: "Eau",                  g: 200, pct: 22, role: "eau"       },
          { nom: "Sucre semoule",        g: 340, pct: 38, role: "sucrant"   },
          { nom: "Poudre de cacao",      g: 150, pct: 17, role: "parfum"    },
          { nom: "Crème liquide 35%",    g: 180, pct: 20, role: "mg"        },
        ],
        procede: [
          "Réhydrater la gélatine.",
          "Porter eau, sucre, cacao et crème à ébullition. Incorporer la gélatine. Chinoiser. Utiliser à 32°C.",
        ],
      },
    ],
    montage: [
      "Chemiser 3 cercles ø 20 cm de rhodoïd.",
      "Pocher une couche de mousse. Déposer un insert mousseline passion. Recouvrir de mousse, déposer un insert gelée. Terminer par une couche de mousse et un disque de biscuit chocolat.",
      "Surgeler. Démouler et glacer à 32°C.",
    ],
    cuisson: { temperature_c: 180, duree_min: 12, mode: "chaleur tournante" },
    temperatures: { service_c: 4, conservation_c: -18 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait", "oeuf", "gluten"],
    tags: ["entremet", "chocolat noir", "passion", "abricot", "mousse", "insert"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Quantités pour 3 entremets ø 20 cm. Les ingrédients sont répartis sur deux colonnes dans la source — reconstruction à vérifier.",
    source_interne: {
      fichier_pdf: "Bachour _ recipes for the professional chef -- Antonio Bachour & Battman -- 1, 2013 -- Battmann -- 9780933477384 -- 8f96a678d66ca9f975c45792c3fb083b -- Anna's Archive.pdf",
      page: 52,
      chef: null,
    },
  },

  /* ── 2. Entremet café & chocolat blanc ───────────────────────────────── */
  {
    id: "entremet-cafe-chocolat-blanc",
    type: "assemblage",
    nom: "Entremet café & chocolat blanc",
    categorie: "assemblages",
    sous_categorie: "entremet_moule",
    description: "Gâteau noisette, mousse chocolat blanc infusée café, croustillant noisette, glaçage blond. Pour 3 entremets ø 20 cm.",
    masse_totale_g: 6342,
    composants: [
      {
        nom: "Gâteau noisette",
        masse_g: 2385,
        ingredients: [
          { nom: "Farine de noisette",       g: 573, pct: 24, role: "parfum"   },
          { nom: "Sucre semoule",            g: 450, pct: 19, role: "sucrant"  },
          { nom: "Œufs entiers",             g: 845, pct: 35, role: "liant"    },
          { nom: "Beurre doux",              g: 225, pct: 9,  role: "mg"       },
          { nom: "Blancs d'œufs",           g: 180, pct: 8,  role: "aeration" },
          { nom: "Sucre semoule (meringue)", g: 112, pct: 5,  role: "sucrant"  },
        ],
        procede: [
          "Préchauffer le four à 180°C.",
          "Mixer farine de noisette, 450g sucre, œufs et beurre jusqu'à masse lisse.",
          "Monter les blancs avec le sucre restant en meringue ferme. Incorporer délicatement.",
          "Répartir dans 3 moules ø 20 cm chemisés. Cuire 15–20 min.",
        ],
      },
      {
        nom: "Croustillant noisette",
        masse_g: 413,
        ingredients: [
          { nom: "Sucre semoule",              g: 150, pct: 36, role: "sucrant"  },
          { nom: "Pectine NH",                 g: 3,   pct: 1,  role: "gelifiant"},
          { nom: "Beurre doux",                g: 125, pct: 30, role: "mg"       },
          { nom: "Glucose",                    g: 50,  pct: 12, role: "sucrant"  },
          { nom: "Eau",                        g: 10,  pct: 2,  role: "eau"      },
          { nom: "Noisettes salées concassées",g: 75,  pct: 19, role: "texture"  },
        ],
        procede: [
          "Préchauffer le four à 180°C.",
          "Porter sucre, pectine, beurre, glucose et eau à ébullition. Incorporer les noisettes.",
          "Étaler sur tapis siliconé et réfrigérer. Cuire 10 min. Laisser refroidir.",
        ],
      },
      {
        nom: "Mousse chocolat blanc café",
        masse_g: 1941,
        ingredients: [
          { nom: "Gélatine en feuilles", g: 16,  pct: 1,  role: "gelifiant" },
          { nom: "Grains de café",       g: 70,  pct: 4,  role: "parfum"    },
          { nom: "Lait entier",          g: 375, pct: 19, role: "eau"       },
          { nom: "Couverture blanc",     g: 735, pct: 38, role: "parfum"    },
          { nom: "Crème montée",         g: 745, pct: 38, role: "aeration"  },
        ],
        procede: [
          "Réhydrater la gélatine.",
          "Porter lait et grains de café à ébullition. Infuser 15 min, chinoiser. Incorporer la gélatine.",
          "Verser sur le chocolat et émulsionner. Laisser refroidir à 35°C. Incorporer la crème montée.",
        ],
      },
      {
        nom: "Glaçage blond",
        masse_g: 1603,
        ingredients: [
          { nom: "Gélatine en feuilles", g: 6,   pct: 0.5, role: "gelifiant" },
          { nom: "Crème liquide 35%",    g: 600, pct: 37,  role: "mg"        },
          { nom: "Couverture blond",     g: 795, pct: 50,  role: "parfum"    },
          { nom: "Eau",                  g: 127, pct: 8,   role: "eau"       },
          { nom: "Huile de colza",       g: 75,  pct: 4.5, role: "mg"        },
        ],
        procede: [
          "Réhydrater la gélatine. Porter crème à ébullition, incorporer la gélatine.",
          "Verser sur le chocolat, émulsionner. Ajouter eau et huile, mixer au plongeant. Utiliser à 32°C.",
        ],
      },
    ],
    montage: [
      "Chemiser 3 cercles ø 20 cm de rhodoïd.",
      "Pocher une couche de mousse. Déposer un disque de gâteau noisette et la couche croustillante.",
      "Étaler une nouvelle couche de mousse et terminer par un disque de gâteau. Surgeler.",
      "Démouler et glacer à 32°C.",
    ],
    cuisson: { temperature_c: 180, duree_min: 18, mode: "chaleur tournante" },
    temperatures: { service_c: 4, conservation_c: -18 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait", "oeuf", "fruits_a_coque"],
    tags: ["entremet", "chocolat blanc", "café", "noisette", "mousse", "glaçage blond", "sans gluten"],
    parfum_principal: "chocolat blanc",
    note_concepteur: "Quantités pour 3 entremets ø 20 cm. Aucune farine de blé dans cette recette — potentiellement sans gluten si ingrédients certifiés.",
    source_interne: {
      fichier_pdf: "Bachour _ recipes for the professional chef -- Antonio Bachour & Battman -- 1, 2013 -- Battmann -- 9780933477384 -- 8f96a678d66ca9f975c45792c3fb083b -- Anna's Archive.pdf",
      page: 54,
      chef: null,
    },
  },

  /* ── 3. Entremet chocolat blanc & fruits rouges ──────────────────────── */
  {
    id: "entremet-chocolat-blanc-fruits-rouges",
    type: "assemblage",
    nom: "Entremet chocolat blanc & fruits rouges",
    categorie: "assemblages",
    sous_categorie: "entremet_moule",
    description: "Biscuit amande, compote fruits rouges, insert feuilletine, mousse chocolat blanc, glaçage miroir blanc. Pour 3 entremets ø 20 cm.",
    masse_totale_g: 6028,
    composants: [
      {
        nom: "Biscuit amande",
        masse_g: 943,
        ingredients: [
          { nom: "Pâte d'amande",   g: 170, pct: 18, role: "parfum"    },
          { nom: "Beurre doux",     g: 170, pct: 18, role: "mg"        },
          { nom: "Sucre semoule",   g: 150, pct: 16, role: "sucrant"   },
          { nom: "Œufs entiers",    g: 165, pct: 18, role: "liant"     },
          { nom: "Farine",          g: 128, pct: 13, role: "structure" },
          { nom: "Levure chimique", g: 5,   pct: 1,  role: "structure" },
          { nom: "Crème sure",      g: 155, pct: 16, role: "eau"       },
        ],
        procede: [
          "Préchauffer le four à 160°C.",
          "Crémer pâte d'amande, beurre et sucre. Ajouter les œufs un à un.",
          "Incorporer farine tamisée et levure, puis la crème sure.",
          "Répartir dans 3 moules ø 15 cm. Cuire 15–20 min.",
        ],
      },
      {
        nom: "Compote fruits rouges",
        masse_g: 473,
        ingredients: [
          { nom: "Purée de fraise", g: 240, pct: 51, role: "fruit"     },
          { nom: "Framboises",      g: 100, pct: 21, role: "fruit"     },
          { nom: "Sucre semoule",   g: 125, pct: 26, role: "sucrant"   },
          { nom: "Pectine NH",      g: 8,   pct: 2,  role: "gelifiant" },
        ],
        procede: [
          "Chauffer purée et framboises à 40°C. Incorporer le mélange sucre-pectine et porter à ébullition.",
          "Couler dans 6 moules ø 15 cm et surgeler.",
        ],
      },
      {
        nom: "Insert croustillant",
        masse_g: 900,
        ingredients: [
          { nom: "Brisures de feuilletine", g: 300, pct: 33, role: "texture" },
          { nom: "Couverture blanc",        g: 400, pct: 45, role: "parfum"  },
          { nom: "Beurre fondu",            g: 200, pct: 22, role: "mg"      },
        ],
        procede: [
          "Mélanger feuilletine, chocolat fondu et beurre.",
          "Répartir dans 6 moules ø 15 cm, presser à 4 mm et réfrigérer jusqu'à prise.",
        ],
      },
      {
        nom: "Mousse chocolat blanc",
        masse_g: 2109,
        ingredients: [
          { nom: "Gélatine en feuilles", g: 24,  pct: 1,  role: "gelifiant" },
          { nom: "Lait entier",          g: 800, pct: 38, role: "eau"       },
          { nom: "Couverture blanc",     g: 810, pct: 38, role: "parfum"    },
          { nom: "Crème montée",         g: 475, pct: 23, role: "aeration"  },
        ],
        procede: [
          "Réhydrater la gélatine. Porter le lait à ébullition, incorporer la gélatine.",
          "Verser lentement sur le chocolat et émulsionner. Laisser refroidir à 35°C.",
          "Incorporer délicatement la crème montée.",
        ],
      },
      {
        nom: "Glaçage chocolat blanc",
        masse_g: 1603,
        ingredients: [
          { nom: "Gélatine en feuilles", g: 6,   pct: 0.5, role: "gelifiant" },
          { nom: "Crème liquide 35%",    g: 600, pct: 37,  role: "mg"        },
          { nom: "Couverture blanc",     g: 795, pct: 50,  role: "parfum"    },
          { nom: "Eau",                  g: 127, pct: 8,   role: "eau"       },
          { nom: "Huile de colza",       g: 75,  pct: 4.5, role: "mg"        },
        ],
        procede: [
          "Réhydrater la gélatine. Porter crème à ébullition, incorporer la gélatine.",
          "Verser sur le chocolat, émulsionner. Ajouter eau et huile, mixer. Utiliser à 32°C.",
        ],
      },
    ],
    montage: [
      "Chemiser 3 cercles ø 20 cm de rhodoïd.",
      "Pocher une couche de mousse. Déposer la compote fruits rouges et une nouvelle couche de mousse.",
      "Ajouter l'insert croustillant, une fine couche de mousse, puis à nouveau compote et croustillant.",
      "Terminer par une couche de mousse et le biscuit amande. Surgeler.",
      "Démouler et glacer à 32°C. Pulvériser du beurre de cacao rouge pour la finition.",
    ],
    cuisson: { temperature_c: 160, duree_min: 18, mode: "chaleur tournante" },
    temperatures: { service_c: 4, conservation_c: -18 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait", "oeuf", "gluten", "fruits_a_coque"],
    tags: ["entremet", "chocolat blanc", "fruits rouges", "fraise", "framboise", "mousse"],
    parfum_principal: "chocolat blanc",
    note_concepteur: "Quantités pour 3 entremets ø 20 cm. Biscuit en moule ø 15 cm, assemblage en moule ø 20 cm.",
    source_interne: {
      fichier_pdf: "Bachour _ recipes for the professional chef -- Antonio Bachour & Battman -- 1, 2013 -- Battmann -- 9780933477384 -- 8f96a678d66ca9f975c45792c3fb083b -- Anna's Archive.pdf",
      page: 56,
      chef: null,
    },
  },

  /* ── 4. Entremet gianduja, noisette & mangue ─────────────────────────── */
  {
    id: "entremet-gianduja-noisette-mangue",
    type: "assemblage",
    nom: "Entremet gianduja, noisette & mangue",
    categorie: "assemblages",
    sous_categorie: "entremet_moule",
    description: "Dacquoise au chocolat amer, mousse gianduja, crémeux mangue, insert streusel noisette, gel mangue et glaçage chocolat. Pour 3 entremets ø 20 cm.",
    masse_totale_g: 4630,
    composants: [
      {
        nom: "Dacquoise amère",
        masse_g: 657,
        ingredients: [
          { nom: "Farine",                          g: 40,  pct: 6,  role: "structure" },
          { nom: "Poudre d'amande",                g: 115, pct: 18, role: "parfum"    },
          { nom: "Sucre glace",                     g: 135, pct: 20, role: "sucrant"   },
          { nom: "Poudre de blanc d'œuf",          g: 7,   pct: 1,  role: "structure" },
          { nom: "Sucre semoule",                   g: 70,  pct: 11, role: "sucrant"   },
          { nom: "Blancs d'œufs",                  g: 190, pct: 29, role: "aeration"  },
          { nom: "Couverture noir extra-amer concassée", g: 100, pct: 15, role: "parfum" },
        ],
        procede: [
          "Préchauffer le four à 190°C.",
          "Tamiser farine, poudre d'amande et sucre glace.",
          "Monter les blancs en ajoutant progressivement le mélange sucre-poudre de blanc, jusqu'à pics mi-fermes.",
          "Incorporer les ingrédients secs puis le chocolat concassé. Étaler dans 3 moules ø 20 cm. Cuire 11–15 min.",
        ],
      },
      {
        nom: "Streusel noisette",
        masse_g: 390,
        ingredients: [
          { nom: "Noisettes",   g: 110, pct: 28, role: "parfum"    },
          { nom: "Farine",      g: 90,  pct: 23, role: "structure" },
          { nom: "Cassonade",   g: 90,  pct: 23, role: "sucrant"   },
          { nom: "Beurre doux", g: 100, pct: 26, role: "mg"        },
        ],
        procede: [
          "Préchauffer le four à 180°C.",
          "Mélanger tous les ingrédients au batteur jusqu'à texture sablée.",
          "Étaler sur plaque et cuire 12 min jusqu'à dorure. Laisser refroidir.",
        ],
      },
      {
        nom: "Crémeux mangue",
        masse_g: 980,
        ingredients: [
          { nom: "Gélatine en feuilles", g: 5,   pct: 0.5,  role: "gelifiant" },
          { nom: "Purée de mangue",      g: 250, pct: 25.5, role: "fruit"     },
          { nom: "Œufs entiers",         g: 250, pct: 25.5, role: "liant"     },
          { nom: "Jaunes d'œufs",       g: 75,  pct: 8,    role: "liant"     },
          { nom: "Sucre semoule",        g: 200, pct: 20,   role: "sucrant"   },
          { nom: "Beurre doux",          g: 200, pct: 20.5, role: "mg"        },
        ],
        procede: [
          "Réhydrater la gélatine.",
          "Porter la purée à frémissement. Verser sur œufs-jaunes-sucre pour tempérer. Cuire à 85°C.",
          "Hors du feu, incorporer la gélatine puis le beurre en morceaux. Émulsionner.",
          "Couler dans 3 moules ø 20 cm et surgeler.",
        ],
      },
      {
        nom: "Insert croustillant noisette",
        masse_g: 441,
        ingredients: [
          { nom: "Praliné noisette",     g: 190, pct: 43, role: "parfum"    },
          { nom: "Couverture lait",      g: 100, pct: 23, role: "parfum"    },
          { nom: "Noisettes torréfiées", g: 50,  pct: 11, role: "texture"   },
          { nom: "Streusel noisette",    g: 100, pct: 22, role: "texture"   },
          { nom: "Fleur de sel",         g: 1,   pct: 1,  role: "exhausteur"},
        ],
        procede: [
          "Mélanger praliné et chocolat fondu. Incorporer noisettes, streusel et fleur de sel.",
          "Répartir dans 3 moules ø 15 cm, presser à 4 mm et surgeler.",
        ],
      },
      {
        nom: "Mousse gianduja",
        masse_g: 1036,
        ingredients: [
          { nom: "Gélatine en feuilles", g: 6,   pct: 1,  role: "gelifiant" },
          { nom: "Gianduja fondu",       g: 375, pct: 36, role: "parfum"    },
          { nom: "Crème liquide chaude", g: 220, pct: 21, role: "mg"        },
          { nom: "Pâte de noisette",     g: 60,  pct: 6,  role: "parfum"    },
          { nom: "Crème montée",         g: 375, pct: 36, role: "aeration"  },
        ],
        procede: [
          "Réhydrater la gélatine.",
          "Émulsionner gianduja et crème chaude. Incorporer pâte de noisette et gélatine dissoute.",
          "Refroidir à 35°C. Incorporer délicatement la crème montée.",
        ],
      },
      {
        nom: "Gel mangue",
        masse_g: 232,
        ingredients: [
          { nom: "Purée de mangue", g: 200, pct: 86, role: "fruit"     },
          { nom: "Sucre semoule",   g: 30,  pct: 13, role: "sucrant"   },
          { nom: "Agar-agar",       g: 2,   pct: 1,  role: "gelifiant" },
        ],
        procede: [
          "Porter tous les ingrédients à ébullition. Réfrigérer 4h jusqu'à prise. Mixer au blender jusqu'à gel lisse.",
        ],
      },
      {
        nom: "Glaçage chocolat",
        masse_g: 894,
        ingredients: [
          { nom: "Gélatine en feuilles", g: 24,  pct: 3,  role: "gelifiant" },
          { nom: "Eau",                  g: 200, pct: 22, role: "eau"       },
          { nom: "Sucre semoule",        g: 340, pct: 38, role: "sucrant"   },
          { nom: "Poudre de cacao",      g: 150, pct: 17, role: "parfum"    },
          { nom: "Crème liquide 35%",    g: 180, pct: 20, role: "mg"        },
        ],
        procede: [
          "Réhydrater la gélatine. Porter eau, sucre, cacao et crème à ébullition. Incorporer la gélatine. Chinoiser. Utiliser à 32°C.",
        ],
      },
    ],
    montage: [
      "Chemiser 3 cercles ø 20 cm de rhodoïd.",
      "Pocher une couche de mousse gianduja. Déposer l'insert crémeux mangue.",
      "Couvrir d'une nouvelle couche de mousse, puis l'insert streusel croustillant.",
      "Pocher une fine couche de mousse et terminer par la dacquoise. Surgeler.",
      "Démouler et glacer à 32°C. Décorer de points de gel mangue.",
    ],
    cuisson: { temperature_c: 185, duree_min: 13, mode: "chaleur tournante" },
    temperatures: { service_c: 4, conservation_c: -18 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait", "oeuf", "gluten", "fruits_a_coque"],
    tags: ["entremet", "gianduja", "noisette", "mangue", "mousse", "dacquoise"],
    parfum_principal: "gianduja",
    note_concepteur: "Quantités pour 3 entremets ø 20 cm. Le streusel noisette est préparé séparément et utilisé dans l'insert croustillant.",
    source_interne: {
      fichier_pdf: "Bachour _ recipes for the professional chef -- Antonio Bachour & Battman -- 1, 2013 -- Battmann -- 9780933477384 -- 8f96a678d66ca9f975c45792c3fb083b -- Anna's Archive.pdf",
      page: 58,
      chef: null,
    },
  },

  /* ── 5. Entremet praliné, citron vert & agrumes ──────────────────────── */
  {
    id: "entremet-praline-citron-agrumes",
    type: "assemblage",
    nom: "Entremet praliné, citron vert & agrumes",
    categorie: "assemblages",
    sous_categorie: "entremet_moule",
    description: "Génoise, insert mousseline citron vert, crumble croustillant aux agrumes, mousse praliné, glaçage miroir blanc. Pour 3 entremets ø 20 cm.",
    masse_totale_g: 9159,
    composants: [
      {
        nom: "Génoise",
        masse_g: 3096,
        ingredients: [
          { nom: "Sucre semoule",   g: 751,  pct: 24, role: "sucrant"   },
          { nom: "Farine",          g: 609,  pct: 20, role: "structure" },
          { nom: "Levure chimique", g: 42,   pct: 1,  role: "structure" },
          { nom: "Œufs entiers",    g: 1000, pct: 32, role: "liant"     },
          { nom: "Huile végétale",  g: 283,  pct: 9,  role: "mg"        },
          { nom: "Lait entier",     g: 411,  pct: 14, role: "eau"       },
        ],
        procede: [
          "Préchauffer le four à 180°C.",
          "Fouetter ingrédients secs + œufs + huile, 6 min vitesse haute. Ajouter lait, 2 min vitesse moyenne.",
          "Répartir dans 3 moules ø 20 cm. Cuire 10–15 min.",
        ],
      },
      {
        nom: "Mousseline citron vert",
        masse_g: 1337,
        ingredients: [
          { nom: "Gélatine en feuilles",    g: 12,  pct: 1,  role: "gelifiant" },
          { nom: "Jus de citron vert",      g: 250, pct: 19, role: "fruit"     },
          { nom: "Jus de citron jaune",     g: 50,  pct: 4,  role: "fruit"     },
          { nom: "Crème liquide 35%",       g: 200, pct: 15, role: "mg"        },
          { nom: "Lait entier",             g: 100, pct: 7,  role: "eau"       },
          { nom: "Poudre de lait écrémé",   g: 35,  pct: 3,  role: "structure" },
          { nom: "Jaunes d'œufs",          g: 120, pct: 9,  role: "liant"     },
          { nom: "Sucre semoule (crème)",   g: 100, pct: 7,  role: "sucrant"   },
          { nom: "Fécule de maïs",          g: 50,  pct: 4,  role: "structure" },
          { nom: "Blancs d'œufs",          g: 160, pct: 12, role: "aeration"  },
          { nom: "Sucre semoule (meringue)",g: 210, pct: 15, role: "sucrant"   },
          { nom: "Eau",                     g: 50,  pct: 4,  role: "eau"       },
        ],
        procede: [
          "Réhydrater la gélatine.",
          "Porter jus, crème, lait et poudre de lait à ébullition. Verser sur jaunes-sucre-fécule. Cuire à consistance, incorporer la gélatine. Laisser tiédir.",
          "Cuire sucre + eau à 121°C, verser sur blancs montés (meringue italienne). Incorporer à la crème citronnée.",
          "Couler en moules à insert et surgeler.",
        ],
      },
      {
        nom: "Crumble croustillant aux agrumes",
        masse_g: 903,
        ingredients: [
          { nom: "Sucre semoule",               g: 150, pct: 17, role: "sucrant"   },
          { nom: "Poudre d'amande",            g: 150, pct: 17, role: "parfum"    },
          { nom: "Beurre doux",                 g: 150, pct: 16, role: "mg"        },
          { nom: "Farine",                      g: 150, pct: 17, role: "structure" },
          { nom: "Couverture blanc (enrobage)", g: 300, pct: 33, role: "parfum"    },
        ],
        procede: [
          "Préchauffer le four à 170°C. Mélanger sucre, amande, beurre et farine en pâte sablée.",
          "Cuire sur plaque jusqu'à coloration. Laisser refroidir.",
          "Mélanger streusel cuit avec le chocolat blanc fondu. Couler en insert à 4 mm et surgeler.",
        ],
      },
      {
        nom: "Mousse praliné",
        masse_g: 2220,
        ingredients: [
          { nom: "Gélatine en feuilles", g: 20,   pct: 1,  role: "gelifiant" },
          { nom: "Crème liquide 35%",    g: 250,  pct: 11, role: "mg"        },
          { nom: "Lait entier",          g: 250,  pct: 11, role: "eau"       },
          { nom: "Jaunes d'œufs",       g: 100,  pct: 5,  role: "liant"     },
          { nom: "Sucre semoule",        g: 50,   pct: 2,  role: "sucrant"   },
          { nom: "Pâte de praliné",      g: 550,  pct: 25, role: "parfum"    },
          { nom: "Crème montée",         g: 1000, pct: 45, role: "aeration"  },
        ],
        procede: [
          "Réhydrater la gélatine.",
          "Porter crème et lait à ébullition. Verser sur jaunes-sucre, cuire à 84°C. Chinoiser, incorporer la gélatine.",
          "Incorporer la pâte de praliné. Refroidir à 35°C puis incorporer la crème montée.",
        ],
      },
      {
        nom: "Glaçage chocolat blanc",
        masse_g: 1603,
        ingredients: [
          { nom: "Gélatine en feuilles", g: 6,   pct: 0.5, role: "gelifiant" },
          { nom: "Crème liquide 35%",    g: 600, pct: 37,  role: "mg"        },
          { nom: "Couverture blanc",     g: 795, pct: 50,  role: "parfum"    },
          { nom: "Eau",                  g: 127, pct: 8,   role: "eau"       },
          { nom: "Huile de colza",       g: 75,  pct: 4.5, role: "mg"        },
        ],
        procede: [
          "Réhydrater la gélatine. Porter crème à ébullition, incorporer la gélatine.",
          "Verser sur le chocolat, émulsionner. Ajouter eau et huile, mixer. Utiliser à 32°C.",
        ],
      },
    ],
    montage: [
      "Chemiser 3 cercles ø 20 cm de rhodoïd.",
      "Pocher une couche de mousse praliné. Déposer l'insert mousseline citron vert.",
      "Couvrir de mousse, ajouter l'insert crumble croustillant.",
      "Pocher une dernière couche de mousse. Terminer par un disque de génoise. Surgeler.",
      "Démouler et glacer à 32°C.",
    ],
    cuisson: { temperature_c: 180, duree_min: 12, mode: "chaleur tournante" },
    temperatures: { service_c: 4, conservation_c: -18 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait", "oeuf", "gluten", "fruits_a_coque"],
    tags: ["entremet", "praliné", "citron vert", "agrumes", "mousse", "glaçage blanc"],
    parfum_principal: "praliné",
    note_concepteur: "Quantités pour 3 entremets ø 20 cm. Le crumble ne comprend pas le sel indiqué dans la source (30g — vraisemblablement une erreur de lecture PDF).",
    source_interne: {
      fichier_pdf: "Bachour _ recipes for the professional chef -- Antonio Bachour & Battman -- 1, 2013 -- Battmann -- 9780933477384 -- 8f96a678d66ca9f975c45792c3fb083b -- Anna's Archive.pdf",
      page: 60,
      chef: null,
    },
  },

  /* ── 6. Entremet blond & fraise ──────────────────────────────────────── */
  {
    id: "entremet-blond-fraise",
    type: "assemblage",
    nom: "Entremet blond & fraise",
    categorie: "assemblages",
    sous_categorie: "entremet_moule",
    description: "Gâteau chocolat, compote fraise, insert croustillant blond, mousse chocolat blond, glaçage blond. Pour 3 entremets ø 20 cm.",
    masse_totale_g: 7022,
    composants: [
      {
        nom: "Gâteau chocolat",
        masse_g: 1587,
        ingredients: [
          { nom: "Farine",                g: 300, pct: 19,  role: "structure" },
          { nom: "Poudre de cacao",        g: 45,  pct: 3,   role: "parfum"    },
          { nom: "Cassonade",             g: 225, pct: 14,  role: "sucrant"   },
          { nom: "Levure chimique",       g: 6,   pct: 0.5, role: "structure" },
          { nom: "Bicarbonate de soude",  g: 6,   pct: 0.5, role: "structure" },
          { nom: "Couverture noir fondu", g: 270, pct: 17,  role: "parfum"    },
          { nom: "Sirop d'érable",       g: 120, pct: 8,   role: "sucrant"   },
          { nom: "Lait entier",           g: 225, pct: 14,  role: "eau"       },
          { nom: "Huile végétale",        g: 225, pct: 14,  role: "mg"        },
          { nom: "Œufs entiers",          g: 165, pct: 10,  role: "liant"     },
        ],
        procede: [
          "Préchauffer le four à 170°C.",
          "Mélanger les ingrédients secs. Dans un autre bol, mélanger chocolat fondu, sirop d'érable, lait, huile et œufs.",
          "Combiner les deux appareils. Étaler sur plaque avec tapis siliconé. Cuire 10–15 min.",
        ],
      },
      {
        nom: "Compote fraise",
        masse_g: 473,
        ingredients: [
          { nom: "Purée de fraise",  g: 240, pct: 51, role: "fruit"     },
          { nom: "Fraises en dés",  g: 100, pct: 21, role: "fruit"     },
          { nom: "Sucre semoule",    g: 125, pct: 26, role: "sucrant"   },
          { nom: "Pectine NH",       g: 8,   pct: 2,  role: "gelifiant" },
        ],
        procede: [
          "Chauffer purée et fraises à 40°C. Incorporer sucre-pectine, porter à ébullition.",
          "Couler dans 6 moules ø 15 cm et surgeler.",
        ],
      },
      {
        nom: "Insert croustillant blond",
        masse_g: 900,
        ingredients: [
          { nom: "Brisures de feuilletine", g: 300, pct: 33, role: "texture" },
          { nom: "Couverture blond",        g: 400, pct: 45, role: "parfum"  },
          { nom: "Beurre fondu",            g: 200, pct: 22, role: "mg"      },
        ],
        procede: [
          "Mélanger feuilletine, chocolat fondu et beurre. Couler dans 6 moules ø 15 cm, presser à 4 mm et surgeler.",
        ],
      },
      {
        nom: "Mousse chocolat blond",
        masse_g: 2457,
        ingredients: [
          { nom: "Gélatine en feuilles", g: 17,  pct: 1,  role: "gelifiant" },
          { nom: "Lait entier",          g: 375, pct: 15, role: "eau"       },
          { nom: "Jaunes d'œufs",       g: 340, pct: 14, role: "liant"     },
          { nom: "Sucre semoule",        g: 50,  pct: 2,  role: "sucrant"   },
          { nom: "Couverture blond",     g: 775, pct: 32, role: "parfum"    },
          { nom: "Crème montée",         g: 900, pct: 36, role: "aeration"  },
        ],
        procede: [
          "Réhydrater la gélatine. Porter le lait à ébullition. Verser sur jaunes-sucre, cuire à 84°C. Chinoiser, incorporer la gélatine.",
          "Verser sur le chocolat et émulsionner. Refroidir à 35°C. Incorporer la crème montée.",
        ],
      },
      {
        nom: "Glaçage chocolat blond",
        masse_g: 1605,
        ingredients: [
          { nom: "Gélatine en feuilles", g: 8,   pct: 0.5, role: "gelifiant" },
          { nom: "Crème liquide 35%",    g: 600, pct: 37,  role: "mg"        },
          { nom: "Couverture blond",     g: 795, pct: 50,  role: "parfum"    },
          { nom: "Eau",                  g: 127, pct: 8,   role: "eau"       },
          { nom: "Huile de colza",       g: 75,  pct: 4.5, role: "mg"        },
        ],
        procede: [
          "Réhydrater la gélatine. Porter crème à ébullition, incorporer la gélatine.",
          "Verser sur le chocolat, émulsionner. Ajouter eau et huile, mixer. Utiliser à 32°C.",
        ],
      },
    ],
    montage: [
      "Chemiser 3 cercles ø 20 cm de rhodoïd.",
      "Pocher une couche de mousse blond. Déposer la compote fraise et une nouvelle couche de mousse.",
      "Ajouter l'insert croustillant blond et une fine couche de mousse.",
      "Terminer par le gâteau chocolat. Surgeler.",
      "Démouler et glacer à 32°C. Décorer de pointillés de gel fraise.",
    ],
    cuisson: { temperature_c: 170, duree_min: 12, mode: "chaleur tournante" },
    temperatures: { service_c: 4, conservation_c: -18 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait", "oeuf", "gluten"],
    tags: ["entremet", "chocolat blond", "fraise", "mousse", "glaçage blond"],
    parfum_principal: "chocolat blond",
    note_concepteur: "Quantités pour 3 entremets ø 20 cm.",
    source_interne: {
      fichier_pdf: "Bachour _ recipes for the professional chef -- Antonio Bachour & Battman -- 1, 2013 -- Battmann -- 9780933477384 -- 8f96a678d66ca9f975c45792c3fb083b -- Anna's Archive.pdf",
      page: 62,
      chef: null,
    },
  },
];
