export const RECETTES_ASSEMBLAGES = [

  /* ── 1. Entremet chocolat noir & passion ─────────────────────────────── */
  {
    id: "entremet-chocolat-passion",
    type: "assemblage",
    nom: "Entremet chocolat noir & passion",
    categorie: "assemblages",
    sous_categorie: "entremet_moule",
    description: "Mousse chocolat noir 64% sur inserts mousseline et gelée passion-abricot, biscuit chocolat, glaçage miroir. Pour 3 entremets ø 20 cm.",
    masse_totale_g: 9610,
    composants: [
      {
        nom: "Biscuit chocolat",
        masse_g: 3203,
        ingredients: [
          { nom: "Sucre semoule",   g: 751,  pct: 23, role: "sucrant"   },
          { nom: "Farine",          g: 609,  pct: 19, role: "structure" },
          { nom: "Levure chimique", g: 42,   pct: 1,  role: "structure" },
          { nom: "Poudre de cacao", g: 100,  pct: 3,  role: "parfum"    },
          { nom: "Huile végétale",  g: 290,  pct: 9,  role: "mg"        },
          { nom: "Œufs entiers",    g: 1000, pct: 32, role: "liant"     },
          { nom: "Lait entier",     g: 411,  pct: 13, role: "eau"       },
        ],
        procede: [
          "Préchauffer le four à 180°C chaleur tournante.",
          "Mélanger les ingrédients secs avec l'huile et les œufs, fouetter 6 min vitesse haute. Ajouter le lait, 2 min vitesse moyenne.",
          "Répartir sur plaques chemisées et cuire 10–15 min. Réserver.",
        ],
      },
      {
        nom: "Mousseline fruit de la passion",
        masse_g: 1376,
        ingredients: [
          { nom: "Gélatine en feuilles",         g: 13,  pct: 1,  role: "gelifiant" },
          { nom: "Purée de fruit de la passion", g: 350, pct: 25, role: "fruit"     },
          { nom: "Crème liquide 35%",            g: 200, pct: 14, role: "mg"        },
          { nom: "Lait entier",                  g: 100, pct: 7,  role: "eau"       },
          { nom: "Poudre de lait écrémé",        g: 35,  pct: 3,  role: "structure" },
          { nom: "Jaunes d'œufs",               g: 108, pct: 8,  role: "liant"     },
          { nom: "Sucre semoule (crème)",        g: 100, pct: 7,  role: "sucrant"   },
          { nom: "Fécule de maïs",               g: 50,  pct: 4,  role: "structure" },
          { nom: "Blancs d'œufs",               g: 160, pct: 12, role: "aeration"  },
          { nom: "Sucre semoule (meringue)",     g: 210, pct: 15, role: "sucrant"   },
          { nom: "Eau",                          g: 50,  pct: 4,  role: "eau"       },
        ],
        procede: [
          "Réhydrater la gélatine.",
          "Porter purée, crème, lait et poudre de lait à ébullition. Verser sur le mélange jaunes-sucre-fécule. Cuire à consistance de crème pâtissière. Incorporer la gélatine. Laisser tiédir.",
          "Cuire sucre + eau à 121°C, verser en filet sur les blancs montés : meringue italienne. Incorporer à la crème tiède.",
          "Couler en moules à insert et surgeler.",
        ],
      },
      {
        nom: "Gelée passion-abricot",
        masse_g: 662,
        ingredients: [
          { nom: "Sucre semoule",                g: 105, pct: 16, role: "sucrant"   },
          { nom: "Pectine NH",                   g: 12,  pct: 2,  role: "gelifiant" },
          { nom: "Purée de fruit de la passion", g: 200, pct: 30, role: "fruit"     },
          { nom: "Purée d'abricot",             g: 250, pct: 38, role: "fruit"     },
          { nom: "Glucose",                      g: 75,  pct: 11, role: "sucrant"   },
          { nom: "Jus de citron",               g: 20,  pct: 3,  role: "acidite"   },
        ],
        procede: [
          "Mélanger sucre et pectine.",
          "Chauffer les purées avec le glucose à 40°C. Incorporer sucre-pectine, porter à ébullition. Hors du feu, ajouter le jus de citron.",
          "Couler en moules à insert et surgeler.",
        ],
      },
      {
        nom: "Mousse chocolat noir 64%",
        masse_g: 3475,
        ingredients: [
          { nom: "Gélatine en feuilles", g: 15,   pct: 0.5, role: "gelifiant" },
          { nom: "Crème liquide 35%",    g: 330,  pct: 9.5, role: "mg"        },
          { nom: "Lait entier",          g: 330,  pct: 9.5, role: "eau"       },
          { nom: "Jaunes d'œufs",       g: 130,  pct: 4,   role: "liant"     },
          { nom: "Sucre semoule",        g: 70,   pct: 2,   role: "sucrant"   },
          { nom: "Couverture noir 64%",  g: 1400, pct: 40,  role: "parfum"    },
          { nom: "Crème montée",         g: 1200, pct: 34.5,role: "aeration"  },
        ],
        procede: [
          "Réhydrater la gélatine.",
          "Porter crème et lait à ébullition. Verser sur jaunes-sucre, cuire à 82°C (crème anglaise). Incorporer la gélatine.",
          "Verser sur le chocolat et émulsionner. Laisser refroidir à 35°C. Incorporer délicatement la crème montée.",
        ],
      },
      {
        nom: "Glaçage chocolat",
        masse_g: 894,
        ingredients: [
          { nom: "Gélatine en feuilles", g: 24,  pct: 3,  role: "gelifiant" },
          { nom: "Eau",                  g: 200, pct: 22, role: "eau"       },
          { nom: "Sucre semoule",        g: 340, pct: 38, role: "sucrant"   },
          { nom: "Poudre de cacao",      g: 150, pct: 17, role: "parfum"    },
          { nom: "Crème liquide 35%",    g: 180, pct: 20, role: "mg"        },
        ],
        procede: [
          "Réhydrater la gélatine.",
          "Porter eau, sucre, cacao et crème à ébullition. Incorporer la gélatine. Chinoiser. Utiliser à 32°C.",
        ],
      },
    ],
    montage: [
      "Chemiser 3 cercles ø 20 cm de rhodoïd.",
      "Pocher une couche de mousse. Déposer un insert mousseline passion. Recouvrir de mousse, déposer un insert gelée. Terminer par une couche de mousse et un disque de biscuit chocolat.",
      "Surgeler. Démouler et glacer à 32°C.",
    ],
    cuisson: { temperature_c: 180, duree_min: 12, mode: "chaleur tournante" },
    temperatures: { service_c: 4, conservation_c: -18 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait", "oeuf", "gluten"],
    tags: ["entremet", "chocolat noir", "passion", "abricot", "mousse", "insert"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Quantités pour 3 entremets ø 20 cm. Les ingrédients sont répartis sur deux colonnes dans la source — reconstruction à vérifier.",
    source_interne: {
      fichier_pdf: "Bachour _ recipes for the professional chef -- Antonio Bachour & Battman -- 1, 2013 -- Battmann -- 9780933477384 -- 8f96a678d66ca9f975c45792c3fb083b -- Anna's Archive.pdf",
      page: 52,
      chef: null,
    },
  },

  /* ── 2. Entremet café & chocolat blanc ───────────────────────────────── */
  {
    id: "entremet-cafe-chocolat-blanc",
    type: "assemblage",
    nom: "Entremet café & chocolat blanc",
    categorie: "assemblages",
    sous_categorie: "entremet_moule",
    description: "Gâteau noisette, mousse chocolat blanc infusée café, croustillant noisette, glaçage blond. Pour 3 entremets ø 20 cm.",
    masse_totale_g: 6342,
    composants: [
      {
        nom: "Gâteau noisette",
        masse_g: 2385,
        ingredients: [
          { nom: "Farine de noisette",       g: 573, pct: 24, role: "parfum"   },
          { nom: "Sucre semoule",            g: 450, pct: 19, role: "sucrant"  },
          { nom: "Œufs entiers",             g: 845, pct: 35, role: "liant"    },
          { nom: "Beurre doux",              g: 225, pct: 9,  role: "mg"       },
          { nom: "Blancs d'œufs",           g: 180, pct: 8,  role: "aeration" },
          { nom: "Sucre semoule (meringue)", g: 112, pct: 5,  role: "sucrant"  },
        ],
        procede: [
          "Préchauffer le four à 180°C.",
          "Mixer farine de noisette, 450g sucre, œufs et beurre jusqu'à masse lisse.",
          "Monter les blancs avec le sucre restant en meringue ferme. Incorporer délicatement.",
          "Répartir dans 3 moules ø 20 cm chemisés. Cuire 15–20 min.",
        ],
      },
      {
        nom: "Croustillant noisette",
        masse_g: 413,
        ingredients: [
          { nom: "Sucre semoule",              g: 150, pct: 36, role: "sucrant"  },
          { nom: "Pectine NH",                 g: 3,   pct: 1,  role: "gelifiant"},
          { nom: "Beurre doux",                g: 125, pct: 30, role: "mg"       },
          { nom: "Glucose",                    g: 50,  pct: 12, role: "sucrant"  },
          { nom: "Eau",                        g: 10,  pct: 2,  role: "eau"      },
          { nom: "Noisettes salées concassées",g: 75,  pct: 19, role: "texture"  },
        ],
        procede: [
          "Préchauffer le four à 180°C.",
          "Porter sucre, pectine, beurre, glucose et eau à ébullition. Incorporer les noisettes.",
          "Étaler sur tapis siliconé et réfrigérer. Cuire 10 min. Laisser refroidir.",
        ],
      },
      {
        nom: "Mousse chocolat blanc café",
        masse_g: 1941,
        ingredients: [
          { nom: "Gélatine en feuilles", g: 16,  pct: 1,  role: "gelifiant" },
          { nom: "Grains de café",       g: 70,  pct: 4,  role: "parfum"    },
          { nom: "Lait entier",          g: 375, pct: 19, role: "eau"       },
          { nom: "Couverture blanc",     g: 735, pct: 38, role: "parfum"    },
          { nom: "Crème montée",         g: 745, pct: 38, role: "aeration"  },
        ],
        procede: [
          "Réhydrater la gélatine.",
          "Porter lait et grains de café à ébullition. Infuser 15 min, chinoiser. Incorporer la gélatine.",
          "Verser sur le chocolat et émulsionner. Laisser refroidir à 35°C. Incorporer la crème montée.",
        ],
      },
      {
        nom: "Glaçage blond",
        masse_g: 1603,
        ingredients: [
          { nom: "Gélatine en feuilles", g: 6,   pct: 0.5, role: "gelifiant" },
          { nom: "Crème liquide 35%",    g: 600, pct: 37,  role: "mg"        },
          { nom: "Couverture blond",     g: 795, pct: 50,  role: "parfum"    },
          { nom: "Eau",                  g: 127, pct: 8,   role: "eau"       },
          { nom: "Huile de colza",       g: 75,  pct: 4.5, role: "mg"        },
        ],
        procede: [
          "Réhydrater la gélatine. Porter crème à ébullition, incorporer la gélatine.",
          "Verser sur le chocolat, émulsionner. Ajouter eau et huile, mixer au plongeant. Utiliser à 32°C.",
        ],
      },
    ],
    montage: [
      "Chemiser 3 cercles ø 20 cm de rhodoïd.",
      "Pocher une couche de mousse. Déposer un disque de gâteau noisette et la couche croustillante.",
      "Étaler une nouvelle couche de mousse et terminer par un disque de gâteau. Surgeler.",
      "Démouler et glacer à 32°C.",
    ],
    cuisson: { temperature_c: 180, duree_min: 18, mode: "chaleur tournante" },
    temperatures: { service_c: 4, conservation_c: -18 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait", "oeuf", "fruits_a_coque"],
    tags: ["entremet", "chocolat blanc", "café", "noisette", "mousse", "glaçage blond", "sans gluten"],
    parfum_principal: "chocolat blanc",
    note_concepteur: "Quantités pour 3 entremets ø 20 cm. Aucune farine de blé dans cette recette — potentiellement sans gluten si ingrédients certifiés.",
    source_interne: {
      fichier_pdf: "Bachour _ recipes for the professional chef -- Antonio Bachour & Battman -- 1, 2013 -- Battmann -- 9780933477384 -- 8f96a678d66ca9f975c45792c3fb083b -- Anna's Archive.pdf",
      page: 54,
      chef: null,
    },
  },

  /* ── 3. Entremet chocolat blanc & fruits rouges ──────────────────────── */
  {
    id: "entremet-chocolat-blanc-fruits-rouges",
    type: "assemblage",
    nom: "Entremet chocolat blanc & fruits rouges",
    categorie: "assemblages",
    sous_categorie: "entremet_moule",
    description: "Biscuit amande, compote fruits rouges, insert feuilletine, mousse chocolat blanc, glaçage miroir blanc. Pour 3 entremets ø 20 cm.",
    masse_totale_g: 6028,
    composants: [
      {
        nom: "Biscuit amande",
        masse_g: 943,
        ingredients: [
          { nom: "Pâte d'amande",   g: 170, pct: 18, role: "parfum"    },
          { nom: "Beurre doux",     g: 170, pct: 18, role: "mg"        },
          { nom: "Sucre semoule",   g: 150, pct: 16, role: "sucrant"   },
          { nom: "Œufs entiers",    g: 165, pct: 18, role: "liant"     },
          { nom: "Farine",          g: 128, pct: 13, role: "structure" },
          { nom: "Levure chimique", g: 5,   pct: 1,  role: "structure" },
          { nom: "Crème sure",      g: 155, pct: 16, role: "eau"       },
        ],
        procede: [
          "Préchauffer le four à 160°C.",
          "Crémer pâte d'amande, beurre et sucre. Ajouter les œufs un à un.",
          "Incorporer farine tamisée et levure, puis la crème sure.",
          "Répartir dans 3 moules ø 15 cm. Cuire 15–20 min.",
        ],
      },
      {
        nom: "Compote fruits rouges",
        masse_g: 473,
        ingredients: [
          { nom: "Purée de fraise", g: 240, pct: 51, role: "fruit"     },
          { nom: "Framboises",      g: 100, pct: 21, role: "fruit"     },
          { nom: "Sucre semoule",   g: 125, pct: 26, role: "sucrant"   },
          { nom: "Pectine NH",      g: 8,   pct: 2,  role: "gelifiant" },
        ],
        procede: [
          "Chauffer purée et framboises à 40°C. Incorporer le mélange sucre-pectine et porter à ébullition.",
          "Couler dans 6 moules ø 15 cm et surgeler.",
        ],
      },
      {
        nom: "Insert croustillant",
        masse_g: 900,
        ingredients: [
          { nom: "Brisures de feuilletine", g: 300, pct: 33, role: "texture" },
          { nom: "Couverture blanc",        g: 400, pct: 45, role: "parfum"  },
          { nom: "Beurre fondu",            g: 200, pct: 22, role: "mg"      },
        ],
        procede: [
          "Mélanger feuilletine, chocolat fondu et beurre.",
          "Répartir dans 6 moules ø 15 cm, presser à 4 mm et réfrigérer jusqu'à prise.",
        ],
      },
      {
        nom: "Mousse chocolat blanc",
        masse_g: 2109,
        ingredients: [
          { nom: "Gélatine en feuilles", g: 24,  pct: 1,  role: "gelifiant" },
          { nom: "Lait entier",          g: 800, pct: 38, role: "eau"       },
          { nom: "Couverture blanc",     g: 810, pct: 38, role: "parfum"    },
          { nom: "Crème montée",         g: 475, pct: 23, role: "aeration"  },
        ],
        procede: [
          "Réhydrater la gélatine. Porter le lait à ébullition, incorporer la gélatine.",
          "Verser lentement sur le chocolat et émulsionner. Laisser refroidir à 35°C.",
          "Incorporer délicatement la crème montée.",
        ],
      },
      {
        nom: "Glaçage chocolat blanc",
        masse_g: 1603,
        ingredients: [
          { nom: "Gélatine en feuilles", g: 6,   pct: 0.5, role: "gelifiant" },
          { nom: "Crème liquide 35%",    g: 600, pct: 37,  role: "mg"        },
          { nom: "Couverture blanc",     g: 795, pct: 50,  role: "parfum"    },
          { nom: "Eau",                  g: 127, pct: 8,   role: "eau"       },
          { nom: "Huile de colza",       g: 75,  pct: 4.5, role: "mg"        },
        ],
        procede: [
          "Réhydrater la gélatine. Porter crème à ébullition, incorporer la gélatine.",
          "Verser sur le chocolat, émulsionner. Ajouter eau et huile, mixer. Utiliser à 32°C.",
        ],
      },
    ],
    montage: [
      "Chemiser 3 cercles ø 20 cm de rhodoïd.",
      "Pocher une couche de mousse. Déposer la compote fruits rouges et une nouvelle couche de mousse.",
      "Ajouter l'insert croustillant, une fine couche de mousse, puis à nouveau compote et croustillant.",
      "Terminer par une couche de mousse et le biscuit amande. Surgeler.",
      "Démouler et glacer à 32°C. Pulvériser du beurre de cacao rouge pour la finition.",
    ],
    cuisson: { temperature_c: 160, duree_min: 18, mode: "chaleur tournante" },
    temperatures: { service_c: 4, conservation_c: -18 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait", "oeuf", "gluten", "fruits_a_coque"],
    tags: ["entremet", "chocolat blanc", "fruits rouges", "fraise", "framboise", "mousse"],
    parfum_principal: "chocolat blanc",
    note_concepteur: "Quantités pour 3 entremets ø 20 cm. Biscuit en moule ø 15 cm, assemblage en moule ø 20 cm.",
    source_interne: {
      fichier_pdf: "Bachour _ recipes for the professional chef -- Antonio Bachour & Battman -- 1, 2013 -- Battmann -- 9780933477384 -- 8f96a678d66ca9f975c45792c3fb083b -- Anna's Archive.pdf",
      page: 56,
      chef: null,
    },
  },

  /* ── 4. Entremet gianduja, noisette & mangue ─────────────────────────── */
  {
    id: "entremet-gianduja-noisette-mangue",
    type: "assemblage",
    nom: "Entremet gianduja, noisette & mangue",
    categorie: "assemblages",
    sous_categorie: "entremet_moule",
    description: "Dacquoise au chocolat amer, mousse gianduja, crémeux mangue, insert streusel noisette, gel mangue et glaçage chocolat. Pour 3 entremets ø 20 cm.",
    masse_totale_g: 4630,
    composants: [
      {
        nom: "Dacquoise amère",
        masse_g: 657,
        ingredients: [
          { nom: "Farine",                          g: 40,  pct: 6,  role: "structure" },
          { nom: "Poudre d'amande",                g: 115, pct: 18, role: "parfum"    },
          { nom: "Sucre glace",                     g: 135, pct: 20, role: "sucrant"   },
          { nom: "Poudre de blanc d'œuf",          g: 7,   pct: 1,  role: "structure" },
          { nom: "Sucre semoule",                   g: 70,  pct: 11, role: "sucrant"   },
          { nom: "Blancs d'œufs",                  g: 190, pct: 29, role: "aeration"  },
          { nom: "Couverture noir extra-amer concassée", g: 100, pct: 15, role: "parfum" },
        ],
        procede: [
          "Préchauffer le four à 190°C.",
          "Tamiser farine, poudre d'amande et sucre glace.",
          "Monter les blancs en ajoutant progressivement le mélange sucre-poudre de blanc, jusqu'à pics mi-fermes.",
          "Incorporer les ingrédients secs puis le chocolat concassé. Étaler dans 3 moules ø 20 cm. Cuire 11–15 min.",
        ],
      },
      {
        nom: "Streusel noisette",
        masse_g: 390,
        ingredients: [
          { nom: "Noisettes",   g: 110, pct: 28, role: "parfum"    },
          { nom: "Farine",      g: 90,  pct: 23, role: "structure" },
          { nom: "Cassonade",   g: 90,  pct: 23, role: "sucrant"   },
          { nom: "Beurre doux", g: 100, pct: 26, role: "mg"        },
        ],
        procede: [
          "Préchauffer le four à 180°C.",
          "Mélanger tous les ingrédients au batteur jusqu'à texture sablée.",
          "Étaler sur plaque et cuire 12 min jusqu'à dorure. Laisser refroidir.",
        ],
      },
      {
        nom: "Crémeux mangue",
        masse_g: 980,
        ingredients: [
          { nom: "Gélatine en feuilles", g: 5,   pct: 0.5,  role: "gelifiant" },
          { nom: "Purée de mangue",      g: 250, pct: 25.5, role: "fruit"     },
          { nom: "Œufs entiers",         g: 250, pct: 25.5, role: "liant"     },
          { nom: "Jaunes d'œufs",       g: 75,  pct: 8,    role: "liant"     },
          { nom: "Sucre semoule",        g: 200, pct: 20,   role: "sucrant"   },
          { nom: "Beurre doux",          g: 200, pct: 20.5, role: "mg"        },
        ],
        procede: [
          "Réhydrater la gélatine.",
          "Porter la purée à frémissement. Verser sur œufs-jaunes-sucre pour tempérer. Cuire à 85°C.",
          "Hors du feu, incorporer la gélatine puis le beurre en morceaux. Émulsionner.",
          "Couler dans 3 moules ø 20 cm et surgeler.",
        ],
      },
      {
        nom: "Insert croustillant noisette",
        masse_g: 441,
        ingredients: [
          { nom: "Praliné noisette",     g: 190, pct: 43, role: "parfum"    },
          { nom: "Couverture lait",      g: 100, pct: 23, role: "parfum"    },
          { nom: "Noisettes torréfiées", g: 50,  pct: 11, role: "texture"   },
          { nom: "Streusel noisette",    g: 100, pct: 22, role: "texture"   },
          { nom: "Fleur de sel",         g: 1,   pct: 1,  role: "exhausteur"},
        ],
        procede: [
          "Mélanger praliné et chocolat fondu. Incorporer noisettes, streusel et fleur de sel.",
          "Répartir dans 3 moules ø 15 cm, presser à 4 mm et surgeler.",
        ],
      },
      {
        nom: "Mousse gianduja",
        masse_g: 1036,
        ingredients: [
          { nom: "Gélatine en feuilles", g: 6,   pct: 1,  role: "gelifiant" },
          { nom: "Gianduja fondu",       g: 375, pct: 36, role: "parfum"    },
          { nom: "Crème liquide chaude", g: 220, pct: 21, role: "mg"        },
          { nom: "Pâte de noisette",     g: 60,  pct: 6,  role: "parfum"    },
          { nom: "Crème montée",         g: 375, pct: 36, role: "aeration"  },
        ],
        procede: [
          "Réhydrater la gélatine.",
          "Émulsionner gianduja et crème chaude. Incorporer pâte de noisette et gélatine dissoute.",
          "Refroidir à 35°C. Incorporer délicatement la crème montée.",
        ],
      },
      {
        nom: "Gel mangue",
        masse_g: 232,
        ingredients: [
          { nom: "Purée de mangue", g: 200, pct: 86, role: "fruit"     },
          { nom: "Sucre semoule",   g: 30,  pct: 13, role: "sucrant"   },
          { nom: "Agar-agar",       g: 2,   pct: 1,  role: "gelifiant" },
        ],
        procede: [
          "Porter tous les ingrédients à ébullition. Réfrigérer 4h jusqu'à prise. Mixer au blender jusqu'à gel lisse.",
        ],
      },
      {
        nom: "Glaçage chocolat",
        masse_g: 894,
        ingredients: [
          { nom: "Gélatine en feuilles", g: 24,  pct: 3,  role: "gelifiant" },
          { nom: "Eau",                  g: 200, pct: 22, role: "eau"       },
          { nom: "Sucre semoule",        g: 340, pct: 38, role: "sucrant"   },
          { nom: "Poudre de cacao",      g: 150, pct: 17, role: "parfum"    },
          { nom: "Crème liquide 35%",    g: 180, pct: 20, role: "mg"        },
        ],
        procede: [
          "Réhydrater la gélatine. Porter eau, sucre, cacao et crème à ébullition. Incorporer la gélatine. Chinoiser. Utiliser à 32°C.",
        ],
      },
    ],
    montage: [
      "Chemiser 3 cercles ø 20 cm de rhodoïd.",
      "Pocher une couche de mousse gianduja. Déposer l'insert crémeux mangue.",
      "Couvrir d'une nouvelle couche de mousse, puis l'insert streusel croustillant.",
      "Pocher une fine couche de mousse et terminer par la dacquoise. Surgeler.",
      "Démouler et glacer à 32°C. Décorer de points de gel mangue.",
    ],
    cuisson: { temperature_c: 185, duree_min: 13, mode: "chaleur tournante" },
    temperatures: { service_c: 4, conservation_c: -18 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait", "oeuf", "gluten", "fruits_a_coque"],
    tags: ["entremet", "gianduja", "noisette", "mangue", "mousse", "dacquoise"],
    parfum_principal: "gianduja",
    note_concepteur: "Quantités pour 3 entremets ø 20 cm. Le streusel noisette est préparé séparément et utilisé dans l'insert croustillant.",
    source_interne: {
      fichier_pdf: "Bachour _ recipes for the professional chef -- Antonio Bachour & Battman -- 1, 2013 -- Battmann -- 9780933477384 -- 8f96a678d66ca9f975c45792c3fb083b -- Anna's Archive.pdf",
      page: 58,
      chef: null,
    },
  },

  /* ── 5. Entremet praliné, citron vert & agrumes ──────────────────────── */
  {
    id: "entremet-praline-citron-agrumes",
    type: "assemblage",
    nom: "Entremet praliné, citron vert & agrumes",
    categorie: "assemblages",
    sous_categorie: "entremet_moule",
    description: "Génoise, insert mousseline citron vert, crumble croustillant aux agrumes, mousse praliné, glaçage miroir blanc. Pour 3 entremets ø 20 cm.",
    masse_totale_g: 9159,
    composants: [
      {
        nom: "Génoise",
        masse_g: 3096,
        ingredients: [
          { nom: "Sucre semoule",   g: 751,  pct: 24, role: "sucrant"   },
          { nom: "Farine",          g: 609,  pct: 20, role: "structure" },
          { nom: "Levure chimique", g: 42,   pct: 1,  role: "structure" },
          { nom: "Œufs entiers",    g: 1000, pct: 32, role: "liant"     },
          { nom: "Huile végétale",  g: 283,  pct: 9,  role: "mg"        },
          { nom: "Lait entier",     g: 411,  pct: 14, role: "eau"       },
        ],
        procede: [
          "Préchauffer le four à 180°C.",
          "Fouetter ingrédients secs + œufs + huile, 6 min vitesse haute. Ajouter lait, 2 min vitesse moyenne.",
          "Répartir dans 3 moules ø 20 cm. Cuire 10–15 min.",
        ],
      },
      {
        nom: "Mousseline citron vert",
        masse_g: 1337,
        ingredients: [
          { nom: "Gélatine en feuilles",    g: 12,  pct: 1,  role: "gelifiant" },
          { nom: "Jus de citron vert",      g: 250, pct: 19, role: "fruit"     },
          { nom: "Jus de citron jaune",     g: 50,  pct: 4,  role: "fruit"     },
          { nom: "Crème liquide 35%",       g: 200, pct: 15, role: "mg"        },
          { nom: "Lait entier",             g: 100, pct: 7,  role: "eau"       },
          { nom: "Poudre de lait écrémé",   g: 35,  pct: 3,  role: "structure" },
          { nom: "Jaunes d'œufs",          g: 120, pct: 9,  role: "liant"     },
          { nom: "Sucre semoule (crème)",   g: 100, pct: 7,  role: "sucrant"   },
          { nom: "Fécule de maïs",          g: 50,  pct: 4,  role: "structure" },
          { nom: "Blancs d'œufs",          g: 160, pct: 12, role: "aeration"  },
          { nom: "Sucre semoule (meringue)",g: 210, pct: 15, role: "sucrant"   },
          { nom: "Eau",                     g: 50,  pct: 4,  role: "eau"       },
        ],
        procede: [
          "Réhydrater la gélatine.",
          "Porter jus, crème, lait et poudre de lait à ébullition. Verser sur jaunes-sucre-fécule. Cuire à consistance, incorporer la gélatine. Laisser tiédir.",
          "Cuire sucre + eau à 121°C, verser sur blancs montés (meringue italienne). Incorporer à la crème citronnée.",
          "Couler en moules à insert et surgeler.",
        ],
      },
      {
        nom: "Crumble croustillant aux agrumes",
        masse_g: 903,
        ingredients: [
          { nom: "Sucre semoule",               g: 150, pct: 17, role: "sucrant"   },
          { nom: "Poudre d'amande",            g: 150, pct: 17, role: "parfum"    },
          { nom: "Beurre doux",                 g: 150, pct: 16, role: "mg"        },
          { nom: "Farine",                      g: 150, pct: 17, role: "structure" },
          { nom: "Couverture blanc (enrobage)", g: 300, pct: 33, role: "parfum"    },
        ],
        procede: [
          "Préchauffer le four à 170°C. Mélanger sucre, amande, beurre et farine en pâte sablée.",
          "Cuire sur plaque jusqu'à coloration. Laisser refroidir.",
          "Mélanger streusel cuit avec le chocolat blanc fondu. Couler en insert à 4 mm et surgeler.",
        ],
      },
      {
        nom: "Mousse praliné",
        masse_g: 2220,
        ingredients: [
          { nom: "Gélatine en feuilles", g: 20,   pct: 1,  role: "gelifiant" },
          { nom: "Crème liquide 35%",    g: 250,  pct: 11, role: "mg"        },
          { nom: "Lait entier",          g: 250,  pct: 11, role: "eau"       },
          { nom: "Jaunes d'œufs",       g: 100,  pct: 5,  role: "liant"     },
          { nom: "Sucre semoule",        g: 50,   pct: 2,  role: "sucrant"   },
          { nom: "Pâte de praliné",      g: 550,  pct: 25, role: "parfum"    },
          { nom: "Crème montée",         g: 1000, pct: 45, role: "aeration"  },
        ],
        procede: [
          "Réhydrater la gélatine.",
          "Porter crème et lait à ébullition. Verser sur jaunes-sucre, cuire à 84°C. Chinoiser, incorporer la gélatine.",
          "Incorporer la pâte de praliné. Refroidir à 35°C puis incorporer la crème montée.",
        ],
      },
      {
        nom: "Glaçage chocolat blanc",
        masse_g: 1603,
        ingredients: [
          { nom: "Gélatine en feuilles", g: 6,   pct: 0.5, role: "gelifiant" },
          { nom: "Crème liquide 35%",    g: 600, pct: 37,  role: "mg"        },
          { nom: "Couverture blanc",     g: 795, pct: 50,  role: "parfum"    },
          { nom: "Eau",                  g: 127, pct: 8,   role: "eau"       },
          { nom: "Huile de colza",       g: 75,  pct: 4.5, role: "mg"        },
        ],
        procede: [
          "Réhydrater la gélatine. Porter crème à ébullition, incorporer la gélatine.",
          "Verser sur le chocolat, émulsionner. Ajouter eau et huile, mixer. Utiliser à 32°C.",
        ],
      },
    ],
    montage: [
      "Chemiser 3 cercles ø 20 cm de rhodoïd.",
      "Pocher une couche de mousse praliné. Déposer l'insert mousseline citron vert.",
      "Couvrir de mousse, ajouter l'insert crumble croustillant.",
      "Pocher une dernière couche de mousse. Terminer par un disque de génoise. Surgeler.",
      "Démouler et glacer à 32°C.",
    ],
    cuisson: { temperature_c: 180, duree_min: 12, mode: "chaleur tournante" },
    temperatures: { service_c: 4, conservation_c: -18 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait", "oeuf", "gluten", "fruits_a_coque"],
    tags: ["entremet", "praliné", "citron vert", "agrumes", "mousse", "glaçage blanc"],
    parfum_principal: "praliné",
    note_concepteur: "Quantités pour 3 entremets ø 20 cm. Le crumble ne comprend pas le sel indiqué dans la source (30g — vraisemblablement une erreur de lecture PDF).",
    source_interne: {
      fichier_pdf: "Bachour _ recipes for the professional chef -- Antonio Bachour & Battman -- 1, 2013 -- Battmann -- 9780933477384 -- 8f96a678d66ca9f975c45792c3fb083b -- Anna's Archive.pdf",
      page: 60,
      chef: null,
    },
  },

  /* ── 6. Entremet blond & fraise ──────────────────────────────────────── */
  {
    id: "entremet-blond-fraise",
    type: "assemblage",
    nom: "Entremet blond & fraise",
    categorie: "assemblages",
    sous_categorie: "entremet_moule",
    description: "Gâteau chocolat, compote fraise, insert croustillant blond, mousse chocolat blond, glaçage blond. Pour 3 entremets ø 20 cm.",
    masse_totale_g: 7022,
    composants: [
      {
        nom: "Gâteau chocolat",
        masse_g: 1587,
        ingredients: [
          { nom: "Farine",                g: 300, pct: 19,  role: "structure" },
          { nom: "Poudre de cacao",        g: 45,  pct: 3,   role: "parfum"    },
          { nom: "Cassonade",             g: 225, pct: 14,  role: "sucrant"   },
          { nom: "Levure chimique",       g: 6,   pct: 0.5, role: "structure" },
          { nom: "Bicarbonate de soude",  g: 6,   pct: 0.5, role: "structure" },
          { nom: "Couverture noir fondu", g: 270, pct: 17,  role: "parfum"    },
          { nom: "Sirop d'érable",       g: 120, pct: 8,   role: "sucrant"   },
          { nom: "Lait entier",           g: 225, pct: 14,  role: "eau"       },
          { nom: "Huile végétale",        g: 225, pct: 14,  role: "mg"        },
          { nom: "Œufs entiers",          g: 165, pct: 10,  role: "liant"     },
        ],
        procede: [
          "Préchauffer le four à 170°C.",
          "Mélanger les ingrédients secs. Dans un autre bol, mélanger chocolat fondu, sirop d'érable, lait, huile et œufs.",
          "Combiner les deux appareils. Étaler sur plaque avec tapis siliconé. Cuire 10–15 min.",
        ],
      },
      {
        nom: "Compote fraise",
        masse_g: 473,
        ingredients: [
          { nom: "Purée de fraise",  g: 240, pct: 51, role: "fruit"     },
          { nom: "Fraises en dés",  g: 100, pct: 21, role: "fruit"     },
          { nom: "Sucre semoule",    g: 125, pct: 26, role: "sucrant"   },
          { nom: "Pectine NH",       g: 8,   pct: 2,  role: "gelifiant" },
        ],
        procede: [
          "Chauffer purée et fraises à 40°C. Incorporer sucre-pectine, porter à ébullition.",
          "Couler dans 6 moules ø 15 cm et surgeler.",
        ],
      },
      {
        nom: "Insert croustillant blond",
        masse_g: 900,
        ingredients: [
          { nom: "Brisures de feuilletine", g: 300, pct: 33, role: "texture" },
          { nom: "Couverture blond",        g: 400, pct: 45, role: "parfum"  },
          { nom: "Beurre fondu",            g: 200, pct: 22, role: "mg"      },
        ],
        procede: [
          "Mélanger feuilletine, chocolat fondu et beurre. Couler dans 6 moules ø 15 cm, presser à 4 mm et surgeler.",
        ],
      },
      {
        nom: "Mousse chocolat blond",
        masse_g: 2457,
        ingredients: [
          { nom: "Gélatine en feuilles", g: 17,  pct: 1,  role: "gelifiant" },
          { nom: "Lait entier",          g: 375, pct: 15, role: "eau"       },
          { nom: "Jaunes d'œufs",       g: 340, pct: 14, role: "liant"     },
          { nom: "Sucre semoule",        g: 50,  pct: 2,  role: "sucrant"   },
          { nom: "Couverture blond",     g: 775, pct: 32, role: "parfum"    },
          { nom: "Crème montée",         g: 900, pct: 36, role: "aeration"  },
        ],
        procede: [
          "Réhydrater la gélatine. Porter le lait à ébullition. Verser sur jaunes-sucre, cuire à 84°C. Chinoiser, incorporer la gélatine.",
          "Verser sur le chocolat et émulsionner. Refroidir à 35°C. Incorporer la crème montée.",
        ],
      },
      {
        nom: "Glaçage chocolat blond",
        masse_g: 1605,
        ingredients: [
          { nom: "Gélatine en feuilles", g: 8,   pct: 0.5, role: "gelifiant" },
          { nom: "Crème liquide 35%",    g: 600, pct: 37,  role: "mg"        },
          { nom: "Couverture blond",     g: 795, pct: 50,  role: "parfum"    },
          { nom: "Eau",                  g: 127, pct: 8,   role: "eau"       },
          { nom: "Huile de colza",       g: 75,  pct: 4.5, role: "mg"        },
        ],
        procede: [
          "Réhydrater la gélatine. Porter crème à ébullition, incorporer la gélatine.",
          "Verser sur le chocolat, émulsionner. Ajouter eau et huile, mixer. Utiliser à 32°C.",
        ],
      },
    ],
    montage: [
      "Chemiser 3 cercles ø 20 cm de rhodoïd.",
      "Pocher une couche de mousse blond. Déposer la compote fraise et une nouvelle couche de mousse.",
      "Ajouter l'insert croustillant blond et une fine couche de mousse.",
      "Terminer par le gâteau chocolat. Surgeler.",
      "Démouler et glacer à 32°C. Décorer de pointillés de gel fraise.",
    ],
    cuisson: { temperature_c: 170, duree_min: 12, mode: "chaleur tournante" },
    temperatures: { service_c: 4, conservation_c: -18 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait", "oeuf", "gluten"],
    tags: ["entremet", "chocolat blond", "fraise", "mousse", "glaçage blond"],
    parfum_principal: "chocolat blond",
    note_concepteur: "Quantités pour 3 entremets ø 20 cm.",
    source_interne: {
      fichier_pdf: "Bachour _ recipes for the professional chef -- Antonio Bachour & Battman -- 1, 2013 -- Battmann -- 9780933477384 -- 8f96a678d66ca9f975c45792c3fb083b -- Anna's Archive.pdf",
      page: 62,
      chef: null,
    },
  },

  /* ── Révolution Pâtisserie — Johanna Le Pape — Créations ────────────────── */

  {
    id: "eclat-cafe-lp",
    nom: "Éclat café, cacao cru & huile d'argan",
    categorie: "assemblages",
    sous_categorie: "entremet",
    type: "assemblage",
    description: "Entremet café et chocolat en 6 couches : pâte sucrée au café, pain de gênes, croustillant chocolat-amandes, crème café, mousse vanille, glaçage chocolat.",
    composants: [
      {
        nom: "Pâte sucrée café",
        masse_g: 160,
        ingredients: [
          { nom: "Farine d'épeautre",   g:  70, pct: 43.8, role: "structure" },
          { nom: "Poudre d'amande",     g:  40, pct: 25.0, role: "parfum"    },
          { nom: "Sucre complet",       g:  30, pct: 18.8, role: "sucrant"   },
          { nom: "Beurre",              g:  15, pct:  9.4, role: "mg"        },
          { nom: "Café soluble",        g:   5, pct:  3.1, role: "parfum"    },
        ],
        procede: ["Mélanger les ingrédients. Étaler à 3 mm. Cuire à 160 °C / 12 min."],
      },
      {
        nom: "Biscuit pain de gênes",
        masse_g: 200,
        ingredients: [
          { nom: "Poudre d'amande",   g: 100, pct: 50.0, role: "parfum"    },
          { nom: "Œufs entiers",      g:  80, pct: 40.0, role: "liant"     },
          { nom: "Sucre complet",     g:  20, pct: 10.0, role: "sucrant"   },
        ],
        procede: ["Monter les œufs et le sucre. Incorporer la poudre d'amande. Cuire à 170 °C / 15 min."],
      },
      {
        nom: "Croustillant chocolat-amandes",
        masse_g: 120,
        ingredients: [
          { nom: "Praliné amande",       g:  60, pct: 50.0, role: "parfum"    },
          { nom: "Chocolat noir 66%",    g:  40, pct: 33.3, role: "parfum"    },
          { nom: "Céréales soufflées",   g:  20, pct: 16.7, role: "structure" },
        ],
        procede: ["Fondre le chocolat. Mélanger avec le praliné et les céréales. Étaler. Figer au froid."],
      },
      {
        nom: "Crème café–chocolat au lait",
        masse_g: 250,
        ingredients: [
          { nom: "Crème de coco",          g: 120, pct: 48.0, role: "mg"     },
          { nom: "Chocolat au lait 40%",   g: 100, pct: 40.0, role: "parfum" },
          { nom: "Café soluble",           g:  15, pct:  6.0, role: "parfum" },
          { nom: "Huile d'argan",          g:  15, pct:  6.0, role: "mg"     },
        ],
        procede: ["Chauffer la crème, infuser le café, verser sur le chocolat. Émulsionner. Réserver."],
      },
      {
        nom: "Mousse vanille",
        masse_g: 250,
        ingredients: [
          { nom: "Crème de coco",    g: 200, pct: 80.0, role: "mg"     },
          { nom: "Chocolat blanc",   g:  40, pct: 16.0, role: "parfum" },
          { nom: "Vanille",          g:  10, pct:  4.0, role: "parfum" },
        ],
        procede: ["Chauffer 100g crème avec la vanille. Verser sur le chocolat. Monter le reste de crème. Incorporer."],
      },
      {
        nom: "Glaçage chocolat",
        masse_g: 150,
        ingredients: [
          { nom: "Chocolat noir 66%", g:  80, pct: 53.3, role: "parfum" },
          { nom: "Crème de coco",     g:  50, pct: 33.3, role: "mg"     },
          { nom: "Miel",              g:  20, pct: 13.3, role: "sucrant" },
        ],
        procede: ["Chauffer la crème et le miel. Verser sur le chocolat. Mixer. Utiliser à 35 °C."],
      },
    ],
    cuisson: { temperature_c: 170, duree_min: 15, mode: "chaleur tournante" },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten", "oeuf", "fruits_a_coque", "lait"],
    tags: ["entremet", "café", "chocolat", "amande", "vanille", "argan", "création"],
    parfum_principal: "café",
    note_concepteur: "Toutes les quantités par composant sont estimées. Vérifier sur source p.230.",
    source_interne: { fichier_pdf: "Révolution-Pâtisserie.-La-bible-de-la-pâtisserie-saine-Johanna-Le-Pape_-Mlanie-Frechon-_-WeLib_organized.pdf", page: 230, chef: "Johanna Le Pape", date_extraction: "2026-05-20" },
  },

  {
    id: "cheesecake-fruits-rouges-lp",
    nom: "Cheesecakes fruits rouges & fleur d'oranger",
    categorie: "assemblages",
    sous_categorie: "entremets_individuels",
    type: "assemblage",
    description: "Cheesecakes individuels : pâte sucrée, compote de fruits rouges, appareil cheesecake citron vert, chantilly fleur d'oranger, spray rouge.",
    composants: [
      {
        nom: "Fond pâte sucrée",
        masse_g: 120,
        ingredients: [
          { nom: "Farine d'épeautre",  g:  55, pct: 45.8, role: "structure" },
          { nom: "Poudre d'amande",    g:  30, pct: 25.0, role: "parfum"    },
          { nom: "Sucre complet",      g:  20, pct: 16.7, role: "sucrant"   },
          { nom: "Beurre",             g:  15, pct: 12.5, role: "mg"        },
        ],
        procede: ["Mélanger. Étaler à 3 mm. Cuire à 160 °C / 12 min."],
      },
      {
        nom: "Compote fruits rouges",
        masse_g: 150,
        ingredients: [
          { nom: "Fruits rouges (mélange)", g: 130, pct: 86.7, role: "parfum"  },
          { nom: "Miel",                    g:  15, pct: 10.0, role: "sucrant" },
          { nom: "Agar-agar",               g: 0.5, pct:  0.3, role: "structure"},
          { nom: "Jus de citron",           g:   5, pct:  3.3, role: "parfum"  },
        ],
        procede: ["Chauffer les fruits avec le miel et le jus. Ajouter l'agar-agar. Couler en insert."],
      },
      {
        nom: "Appareil cheesecake citron vert",
        masse_g: 300,
        ingredients: [
          { nom: "Fromage blanc végétal",    g: 200, pct: 66.7, role: "mg"     },
          { nom: "Crème de coco",            g:  60, pct: 20.0, role: "mg"     },
          { nom: "Jus et zeste de citron vert", g: 25, pct: 8.3, role: "parfum"},
          { nom: "Miel",                     g:  15, pct:  5.0, role: "sucrant"},
        ],
        procede: ["Mélanger tous les ingrédients. Couler dans les cadres ou cercles sur le fond."],
      },
      {
        nom: "Chantilly fleur d'oranger",
        masse_g: 150,
        ingredients: [
          { nom: "Crème de coco",          g: 140, pct: 93.3, role: "mg"     },
          { nom: "Eau de fleur d'oranger", g:  10, pct:  6.7, role: "parfum" },
        ],
        procede: ["Monter la crème de coco froide. Incorporer la fleur d'oranger."],
      },
    ],
    cuisson: { temperature_c: 160, duree_min: 12, mode: "chaleur tournante" },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten", "fruits_a_coque"],
    tags: ["cheesecake", "fruits rouges", "fleur d'oranger", "citron vert", "création"],
    parfum_principal: "fruits rouges",
    note_concepteur: "Quantités par composant estimées. Vérifier sur source p.232.",
    source_interne: { fichier_pdf: "Révolution-Pâtisserie.-La-bible-de-la-pâtisserie-saine-Johanna-Le-Pape_-Mlanie-Frechon-_-WeLib_organized.pdf", page: 232, chef: "Johanna Le Pape", date_extraction: "2026-05-20" },
  },

  {
    id: "fraisier-roses-lp",
    nom: "Fraisier aux pétales de roses",
    categorie: "assemblages",
    sous_categorie: "entremet",
    type: "assemblage",
    description: "Fraisier revisité : pâte sucrée, biscuit moelleux amandes, confiture rose-fraise, crème pâtissière légère vanille, chantilly rose.",
    composants: [
      {
        nom: "Fond pâte sucrée",
        masse_g: 130,
        ingredients: [
          { nom: "Farine d'épeautre",  g:  55, pct: 42.3, role: "structure" },
          { nom: "Poudre d'amande",    g:  35, pct: 26.9, role: "parfum"    },
          { nom: "Sucre complet",      g:  25, pct: 19.2, role: "sucrant"   },
          { nom: "Beurre",             g:  15, pct: 11.5, role: "mg"        },
        ],
        procede: ["Étaler à 3 mm. Cuire à 160 °C / 12 min."],
      },
      {
        nom: "Biscuit moelleux amandes",
        masse_g: 187,
        ingredients: [
          { nom: "Poudre d'amande",  g: 40, pct: 21.4, role: "parfum"    },
          { nom: "Œuf entier",       g: 50, pct: 26.7, role: "liant"     },
          { nom: "Blanc d'œuf",      g: 33, pct: 17.6, role: "aeration"  },
          { nom: "Sucre complet",    g: 30, pct: 16.0, role: "sucrant"   },
          { nom: "Farine d'épeautre",g: 10, pct:  5.3, role: "structure" },
          { nom: "Jaune d'œuf",      g: 18, pct:  9.6, role: "liant"     },
          { nom: "Psyllium",         g:  1, pct:  0.5, role: "liant"     },
        ],
        procede: ["Cuire à 170 °C / 16 min (cf. recette de base p.176)."],
      },
      {
        nom: "Confiture rose-fraise",
        masse_g: 180,
        ingredients: [
          { nom: "Fraises",           g: 150, pct: 83.3, role: "parfum"    },
          { nom: "Miel",              g:  20, pct: 11.1, role: "sucrant"   },
          { nom: "Eau de rose",       g:   8, pct:  4.4, role: "parfum"    },
          { nom: "Agar-agar",         g: 0.5, pct:  0.3, role: "structure" },
        ],
        procede: ["Cuire les fraises avec le miel. Ajouter l'agar-agar. Incorporer l'eau de rose. Refroidir."],
      },
      {
        nom: "Crème pâtissière légère vanille",
        masse_g: 350,
        ingredients: [
          { nom: "Lait végétal",         g: 250, pct: 71.4, role: "eau"       },
          { nom: "Crème de coco",        g:  60, pct: 17.1, role: "mg"        },
          { nom: "Sucre roux",           g:  20, pct:  5.7, role: "sucrant"   },
          { nom: "Fécule d'arrow-root",  g:  15, pct:  4.3, role: "structure" },
          { nom: "Vanille",              g:   5, pct:  1.4, role: "parfum"    },
        ],
        procede: ["Préparer comme la crème pâtissière végétale (p.184). Monter la crème de coco, incorporer."],
      },
    ],
    cuisson: { temperature_c: 170, duree_min: 16, mode: "chaleur tournante" },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten", "oeuf", "fruits_a_coque"],
    tags: ["fraisier", "rose", "fraise", "crème pâtissière", "amande", "création"],
    parfum_principal: "rose",
    note_concepteur: "Quantités par composant estimées. Vérifier sur source p.234.",
    source_interne: { fichier_pdf: "Révolution-Pâtisserie.-La-bible-de-la-pâtisserie-saine-Johanna-Le-Pape_-Mlanie-Frechon-_-WeLib_organized.pdf", page: 234, chef: "Johanna Le Pape", date_extraction: "2026-05-20" },
  },

  {
    id: "tarte-abricot-lavande-lp",
    nom: "Tarte pétale abricot, lavande",
    categorie: "assemblages",
    sous_categorie: "tarte",
    type: "assemblage",
    description: "Tarte abricot-lavande : pâte sucrée, gel lavande, insert abricot-lavande, mousse lait ribot, glaçage abricot.",
    composants: [
      {
        nom: "Fond pâte sucrée",
        masse_g: 130,
        ingredients: [
          { nom: "Farine d'épeautre",  g:  55, pct: 42.3, role: "structure" },
          { nom: "Poudre d'amande",    g:  35, pct: 26.9, role: "parfum"    },
          { nom: "Sucre complet",      g:  25, pct: 19.2, role: "sucrant"   },
          { nom: "Beurre",             g:  15, pct: 11.5, role: "mg"        },
        ],
        procede: ["Étaler à 3 mm. Cuire à 160 °C / 12 min."],
      },
      {
        nom: "Insert abricot-lavande",
        masse_g: 200,
        ingredients: [
          { nom: "Abricots frais",    g: 150, pct: 75.0, role: "parfum"    },
          { nom: "Miel",        g:  30, pct: 15.0, role: "sucrant"   },
          { nom: "Fleurs de lavande séchées", g: 3, pct: 1.5, role: "parfum" },
          { nom: "Agar-agar",   g: 0.5, pct:  0.3, role: "structure" },
          { nom: "Jus de citron",g: 10, pct:  5.0, role: "parfum"   },
        ],
        procede: ["Cuire les abricots avec le miel et la lavande. Ajouter l'agar-agar. Couler en insert. Congeler."],
      },
      {
        nom: "Mousse lait ribot",
        masse_g: 250,
        ingredients: [
          { nom: "Lait ribot (lait fermenté)", g: 180, pct: 72.0, role: "mg"     },
          { nom: "Crème de coco",              g:  60, pct: 24.0, role: "mg"     },
          { nom: "Agar-agar",                  g:   1, pct:  0.4, role: "structure"},
          { nom: "Miel",                       g:   9, pct:  3.6, role: "sucrant"},
        ],
        procede: ["Chauffer 100g de lait avec l'agar-agar et le miel. Mélanger avec le reste. Monter la crème. Incorporer. Verser en moule. Congeler."],
      },
    ],
    cuisson: { temperature_c: 160, duree_min: 12, mode: "chaleur tournante" },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten", "lait", "fruits_a_coque"],
    tags: ["tarte", "abricot", "lavande", "lait ribot", "mousse", "création"],
    parfum_principal: "abricot",
    note_concepteur: "Quantités estimées. Gel lavande séparé non modélisé. Vérifier sur source p.236.",
    source_interne: { fichier_pdf: "Révolution-Pâtisserie.-La-bible-de-la-pâtisserie-saine-Johanna-Le-Pape_-Mlanie-Frechon-_-WeLib_organized.pdf", page: 236, chef: "Johanna Le Pape", date_extraction: "2026-05-20" },
  },

  {
    id: "perle-tahiti-lp",
    nom: "Perle de Tahiti vanille, mangue, gingembre",
    categorie: "assemblages",
    sous_categorie: "entremet",
    type: "assemblage",
    description: "Entremet tropical : pâte sablée coco-citron, biscuit moelleux gingembre, confit mangue-gingembre, crème vanille-coco.",
    composants: [
      {
        nom: "Fond pâte sablée coco-citron",
        masse_g: 150,
        ingredients: [
          { nom: "Farine d'avoine",   g:  60, pct: 40.0, role: "structure" },
          { nom: "Farine de coco",    g:  40, pct: 26.7, role: "structure" },
          { nom: "Beurre",            g:  35, pct: 23.3, role: "mg"        },
          { nom: "Sucre de datte",    g:  10, pct:  6.7, role: "sucrant"   },
          { nom: "Zeste de citron",   g:   5, pct:  3.3, role: "parfum"    },
        ],
        procede: ["Cf. pâte sablée coco-citron p.170. Cuire à 160 °C / 12 min."],
      },
      {
        nom: "Confit mangue-gingembre",
        masse_g: 200,
        ingredients: [
          { nom: "Mangue fraîche",      g: 160, pct: 80.0, role: "parfum"    },
          { nom: "Miel",                g:  25, pct: 12.5, role: "sucrant"   },
          { nom: "Gingembre frais",     g:   5, pct:  2.5, role: "parfum"    },
          { nom: "Agar-agar",           g: 0.5, pct:  0.3, role: "structure" },
          { nom: "Jus de citron vert",  g:  10, pct:  5.0, role: "parfum"   },
        ],
        procede: ["Couper la mangue. Cuire avec le miel, le gingembre et le jus de citron. Ajouter l'agar. Couler en insert."],
      },
      {
        nom: "Crème vanille-coco",
        masse_g: 280,
        ingredients: [
          { nom: "Lait de coco",         g: 200, pct: 71.4, role: "eau"       },
          { nom: "Crème de coco",        g:  60, pct: 21.4, role: "mg"        },
          { nom: "Vanille",              g:   5, pct:  1.8, role: "parfum"    },
          { nom: "Fécule d'arrow-root",  g:  10, pct:  3.6, role: "structure" },
          { nom: "Miel",                 g:   5, pct:  1.8, role: "sucrant"   },
        ],
        procede: ["Chauffer le lait avec la vanille, l'arrow-root et le miel. Monter la crème. Incorporer. Couler."],
      },
    ],
    cuisson: { temperature_c: 160, duree_min: 12, mode: "chaleur tournante" },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten", "fruits_a_coque"],
    tags: ["entremet", "mangue", "vanille", "gingembre", "coco", "tahiti", "création"],
    parfum_principal: "vanille",
    note_concepteur: "Quantités estimées. Biscuit moelleux gingembre non détaillé ici. Vérifier sur source p.238.",
    source_interne: { fichier_pdf: "Révolution-Pâtisserie.-La-bible-de-la-pâtisserie-saine-Johanna-Le-Pape_-Mlanie-Frechon-_-WeLib_organized.pdf", page: 238, chef: "Johanna Le Pape", date_extraction: "2026-05-20" },
  },

  {
    id: "baba-vanille-citron-lp",
    nom: "Baba vanille, citron caviar, thé noir",
    categorie: "assemblages",
    sous_categorie: "baba",
    type: "assemblage",
    description: "Baba imbibé au sirop vanille-citron, confit citron caviar, gelée charbon actif et chantilly thé noir.",
    composants: [
      {
        nom: "Pâte à baba",
        masse_g: 370,
        ingredients: [
          { nom: "Farine de riz",     g: 125, pct: 33.8, role: "structure" },
          { nom: "Œufs entiers",      g: 200, pct: 54.1, role: "liant"     },
          { nom: "Beurre",            g:  11, pct:  3.0, role: "mg"        },
          { nom: "Miel",              g:   5, pct:  1.4, role: "sucrant"   },
          { nom: "Levure boulangère", g:   5, pct:  1.4, role: "levant"    },
          { nom: "Farine de sarrasin",g:   9, pct:  2.4, role: "structure" },
          { nom: "Fécule de maïs",    g:  11, pct:  3.0, role: "structure" },
          { nom: "Sel fin",           g:   1, pct:  0.3, role: "assaisonm" },
          { nom: "Eau",               g:  10, pct:  2.7, role: "eau"       },
        ],
        procede: ["Cf. pâte à baba p.178. Cuire à 180 °C / 10 min individuels."],
      },
      {
        nom: "Sirop vanille-citron",
        masse_g: 250,
        ingredients: [
          { nom: "Eau",          g: 200, pct: 80.0, role: "eau"     },
          { nom: "Miel",         g:  40, pct: 16.0, role: "sucrant" },
          { nom: "Vanille",      g:   5, pct:  2.0, role: "parfum"  },
          { nom: "Jus de citron",g:   5, pct:  2.0, role: "parfum"  },
        ],
        procede: ["Porter à ébullition. Laisser infuser 10 min. Imbiber les babas chauds."],
      },
      {
        nom: "Chantilly thé noir",
        masse_g: 160,
        ingredients: [
          { nom: "Crème de coco",    g: 150, pct: 93.8, role: "mg"     },
          { nom: "Thé noir (infusé)",g:  10, pct:  6.2, role: "parfum" },
        ],
        procede: ["Infuser le thé dans la crème froide 12h. Monter en chantilly."],
      },
    ],
    cuisson: { temperature_c: 180, duree_min: 10, mode: "chaleur tournante" },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["oeuf", "lait"],
    tags: ["baba", "vanille", "citron caviar", "thé noir", "charbon actif", "création"],
    parfum_principal: "vanille",
    note_concepteur: "Confit citron caviar et gelée charbon actif non modélisés (quantités inconnues). Vérifier sur source p.240.",
    source_interne: { fichier_pdf: "Révolution-Pâtisserie.-La-bible-de-la-pâtisserie-saine-Johanna-Le-Pape_-Mlanie-Frechon-_-WeLib_organized.pdf", page: 240, chef: "Johanna Le Pape", date_extraction: "2026-05-20" },
  },

  {
    id: "pavlovas-ananas-lp",
    nom: "Pavlovas ananas, coriandre, mélisse",
    categorie: "assemblages",
    sous_categorie: "pavlova",
    type: "assemblage",
    description: "Pavlovas vegan : meringue aquafaba, insert ananas-coriandre, gelée végétale, chantilly mélisse.",
    composants: [
      {
        nom: "Meringue aquafaba",
        masse_g: 193,
        ingredients: [
          { nom: "Aquafaba",            g: 100, pct: 51.8, role: "aeration"  },
          { nom: "Sucre blond",         g:  70, pct: 36.3, role: "sucrant"   },
          { nom: "Fécule d'arrow-root", g:  20, pct: 10.4, role: "structure" },
          { nom: "Psyllium",            g:   2, pct:  1.0, role: "liant"     },
          { nom: "Agar-agar",           g:   1, pct:  0.5, role: "structure" },
        ],
        procede: ["Monter l'aquafaba en neige ferme. Ajouter le sucre progressivement. Incorporer les poudres. Dresser en nids. Cuire à 90 °C / 2h."],
      },
      {
        nom: "Insert ananas-coriandre",
        masse_g: 180,
        ingredients: [
          { nom: "Ananas frais",     g: 150, pct: 83.3, role: "parfum"    },
          { nom: "Miel",             g:  20, pct: 11.1, role: "sucrant"   },
          { nom: "Coriandre fraîche",g:   5, pct:  2.8, role: "parfum"    },
          { nom: "Agar-agar",        g: 0.5, pct:  0.3, role: "structure" },
          { nom: "Jus de citron",    g:   5, pct:  2.8, role: "parfum"   },
        ],
        procede: ["Couper l'ananas en brunoise. Cuire avec le miel et l'agar. Incorporer la coriandre. Couler."],
      },
      {
        nom: "Chantilly mélisse",
        masse_g: 150,
        ingredients: [
          { nom: "Crème de coco",  g: 145, pct: 96.7, role: "mg"     },
          { nom: "Mélisse fraîche",g:   5, pct:  3.3, role: "parfum" },
        ],
        procede: ["Infuser la mélisse dans la crème froide 12h. Monter en chantilly."],
      },
    ],
    cuisson: { temperature_c: 90, duree_min: 120, mode: "chaleur tournante" },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["pavlova", "aquafaba", "ananas", "coriandre", "mélisse", "vegan", "création"],
    parfum_principal: "ananas",
    note_concepteur: "Quantités meringue confirmées (source p.242). Insert et chantilly estimés.",
    source_interne: { fichier_pdf: "Révolution-Pâtisserie.-La-bible-de-la-pâtisserie-saine-Johanna-Le-Pape_-Mlanie-Frechon-_-WeLib_organized.pdf", page: 242, chef: "Johanna Le Pape", date_extraction: "2026-05-20" },
  },

  {
    id: "babas-agrumes-lp",
    nom: "Babas à l'infusion agrumes et citronnelle",
    categorie: "assemblages",
    sous_categorie: "baba",
    type: "assemblage",
    description: "Babas imbibés d'une infusion d'agrumes et citronnelle, garnis de kumquats confits et crème coco montée.",
    composants: [
      {
        nom: "Pâte à baba",
        masse_g: 370,
        ingredients: [
          { nom: "Farine de riz",     g: 125, pct: 33.8, role: "structure" },
          { nom: "Œufs entiers",      g: 200, pct: 54.1, role: "liant"     },
          { nom: "Beurre",            g:  11, pct:  3.0, role: "mg"        },
          { nom: "Miel",              g:   5, pct:  1.4, role: "sucrant"   },
          { nom: "Levure boulangère", g:   5, pct:  1.4, role: "levant"    },
          { nom: "Sel fin",           g:   1, pct:  0.3, role: "assaisonm" },
        ],
        procede: ["Cf. pâte à baba p.178. Cuire à 180 °C / 10 min."],
      },
      {
        nom: "Infusion agrumes-citronnelle",
        masse_g: 300,
        ingredients: [
          { nom: "Eau",              g: 250, pct: 83.3, role: "eau"     },
          { nom: "Miel",             g:  30, pct: 10.0, role: "sucrant" },
          { nom: "Citronnelle",      g:  10, pct:  3.3, role: "parfum"  },
          { nom: "Zestes d'agrumes", g:  10, pct:  3.3, role: "parfum"  },
        ],
        procede: ["Porter à ébullition. Infuser 15 min. Filtrer. Imbiber les babas chauds."],
      },
      {
        nom: "Crème coco montée",
        masse_g: 150,
        ingredients: [
          { nom: "Crème de coco", g: 145, pct: 96.7, role: "mg"     },
          { nom: "Miel",          g:   5, pct:  3.3, role: "sucrant" },
        ],
        procede: ["Réfrigérer la crème 12h. Monter en chantilly légère."],
      },
    ],
    cuisson: { temperature_c: 180, duree_min: 10, mode: "chaleur tournante" },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["oeuf", "lait"],
    tags: ["baba", "agrumes", "citronnelle", "kumquat", "coco", "création"],
    parfum_principal: "agrumes",
    note_concepteur: "Kumquats confits non modélisés (quantités inconnues). Vérifier sur source p.244.",
    source_interne: { fichier_pdf: "Révolution-Pâtisserie.-La-bible-de-la-pâtisserie-saine-Johanna-Le-Pape_-Mlanie-Frechon-_-WeLib_organized.pdf", page: 244, chef: "Johanna Le Pape", date_extraction: "2026-05-20" },
  },

  {
    id: "velours-chataigne-lp",
    nom: "Velouté châtaigne, poire et vanille",
    categorie: "assemblages",
    sous_categorie: "dessert_assiette",
    type: "assemblage",
    description: "Dessert à l'assiette : velouté de marrons-poire, gavotte aux graines de lin, poire snackée, gelée végétale, chantilly mélisse.",
    composants: [
      {
        nom: "Velouté marrons-poire",
        masse_g: 380,
        ingredients: [
          { nom: "Marrons cuits",     g: 125, pct: 32.9, role: "parfum"  },
          { nom: "Lait d'amande",     g: 125, pct: 32.9, role: "eau"     },
          { nom: "Purée de poire",    g: 125, pct: 32.9, role: "parfum"  },
          { nom: "Vanille",           g:   3, pct:  0.8, role: "parfum"  },
          { nom: "Gingembre frais",   g:   2, pct:  0.5, role: "parfum"  },
        ],
        procede: ["Mixer tous les ingrédients. Chauffer doucement. Servir chaud ou tiède."],
      },
      {
        nom: "Gavotte aux graines de lin",
        masse_g: 80,
        ingredients: [
          { nom: "Farine de riz",     g:  40, pct: 50.0, role: "structure" },
          { nom: "Beurre",            g:  20, pct: 25.0, role: "mg"        },
          { nom: "Graines de lin",    g:  15, pct: 18.8, role: "parfum"    },
          { nom: "Miel",              g:   5, pct:  6.3, role: "sucrant"   },
        ],
        procede: ["Mélanger. Étaler très finement. Cuire à 160 °C / 8 min. Casser en éclats."],
      },
      {
        nom: "Chantilly mélisse",
        masse_g: 150,
        ingredients: [
          { nom: "Crème de coco",  g: 145, pct: 96.7, role: "mg"     },
          { nom: "Mélisse fraîche",g:   5, pct:  3.3, role: "parfum" },
        ],
        procede: ["Infuser la mélisse 12h dans la crème froide. Monter en chantilly."],
      },
    ],
    cuisson: { temperature_c: 160, duree_min: 8, mode: "chaleur tournante" },
    temperatures: { service_c: 6, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["fruits_a_coque", "lait"],
    tags: ["velouté", "châtaigne", "poire", "vanille", "mélisse", "dessert assiette", "création"],
    parfum_principal: "châtaigne",
    note_concepteur: "Quantités velouté confirmées (source p.246). Gavotte et gelée végétale estimées.",
    source_interne: { fichier_pdf: "Révolution-Pâtisserie.-La-bible-de-la-pâtisserie-saine-Johanna-Le-Pape_-Mlanie-Frechon-_-WeLib_organized.pdf", page: 246, chef: "Johanna Le Pape", date_extraction: "2026-05-20" },
  },

  {
    id: "bouillon-framboise-lp",
    nom: "Bouillon framboise, rhubarbe, hibiscus, verveine",
    categorie: "assemblages",
    sous_categorie: "dessert_assiette",
    type: "assemblage",
    description: "Dessert à l'assiette : bouillon rhubarbe-hibiscus-verveine, rhubarbe pochée, chantilly verveine.",
    composants: [
      {
        nom: "Eau de framboise",
        masse_g: 432,
        ingredients: [
          { nom: "Framboises",    g: 400, pct: 92.6, role: "parfum"  },
          { nom: "Sucre complet", g:  30, pct:  6.9, role: "sucrant" },
          { nom: "Cannelle en poudre",      g:   2, pct:  0.5, role: "parfum"  },
        ],
        procede: ["Mixer les framboises avec le sucre et la cannelle. Filtrer au chinois pour obtenir l'eau de framboise."],
      },
      {
        nom: "Bouillon hibiscus-verveine",
        masse_g: 310,
        ingredients: [
          { nom: "Eau de framboise",   g: 200, pct: 64.5, role: "eau"    },
          { nom: "Lait de coco",       g: 100, pct: 32.3, role: "mg"     },
          { nom: "Fleurs d'hibiscus",  g:   5, pct:  1.6, role: "parfum" },
          { nom: "Verveine séchée",    g:   5, pct:  1.6, role: "parfum" },
        ],
        procede: ["Chauffer le bouillon framboise avec le lait de coco. Infuser hibiscus et verveine 10 min. Filtrer."],
      },
      {
        nom: "Chantilly verveine",
        masse_g: 150,
        ingredients: [
          { nom: "Crème de coco",   g: 145, pct: 96.7, role: "mg"     },
          { nom: "Verveine séchée", g:   5, pct:  3.3, role: "parfum" },
        ],
        procede: ["Infuser la verveine dans la crème froide 12h. Monter en chantilly."],
      },
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson" },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["bouillon", "framboise", "rhubarbe", "hibiscus", "verveine", "vegan", "dessert assiette", "création"],
    parfum_principal: "framboise",
    note_concepteur: "Quantités eau de framboise et bouillon confirmées (source p.248). Rhubarbe pochée non modélisée.",
    source_interne: { fichier_pdf: "Révolution-Pâtisserie.-La-bible-de-la-pâtisserie-saine-Johanna-Le-Pape_-Mlanie-Frechon-_-WeLib_organized.pdf", page: 248, chef: "Johanna Le Pape", date_extraction: "2026-05-20" },
  },

  {
    id: "bouillon-coco-galanga-lp",
    nom: "Bouillon coco galanga",
    categorie: "assemblages",
    sous_categorie: "dessert_assiette",
    type: "assemblage",
    description: "Dessert à l'assiette inspiration thaïe : bouillon coco-galanga épicé, brunoise ananas, ravioles tapioca-riz, huile de coriandre.",
    composants: [
      {
        nom: "Bouillon coco-galanga",
        masse_g: 342,
        ingredients: [
          { nom: "Lait de coco",           g: 200, pct: 58.5, role: "mg"     },
          { nom: "Eau",                    g: 100, pct: 29.2, role: "eau"    },
          { nom: "Miel",                   g:  40, pct: 11.7, role: "sucrant"},
          { nom: "Galanga",                g:   0, pct:  0.0, role: "parfum" },
          { nom: "Citronnelle",            g:   0, pct:  0.0, role: "parfum" },
          { nom: "Basilic thaï",           g:   0, pct:  0.0, role: "parfum" },
          { nom: "Coriandre fraîche",      g:   0, pct:  0.0, role: "parfum" },
          { nom: "Zeste de combava",       g:   0, pct:  0.0, role: "parfum" },
        ],
        procede: ["Chauffer le lait de coco et l'eau avec le miel. Infuser galanga, citronnelle, basilic thaï, coriandre et combava 15 min. Filtrer. Ajuster piment selon goût."],
      },
      {
        nom: "Ravioles tapioca-riz",
        masse_g: 200,
        ingredients: [
          { nom: "Tapioca",         g:  75, pct: 37.5, role: "structure" },
          { nom: "Farine de riz",   g:  75, pct: 37.5, role: "structure" },
          { nom: "Farine T65",      g:  50, pct: 25.0, role: "structure" },
        ],
        procede: ["Mélanger les farines avec de l'eau et un peu d'huile jusqu'à pâte souple. Étaler très finement. Garnir d'ananas et plier en ravioles. Cuire à l'eau bouillante 3-4 min."],
      },
      {
        nom: "Huile de coriandre",
        masse_g: 50,
        ingredients: [
          { nom: "Huile neutre",       g:  45, pct: 90.0, role: "mg"     },
          { nom: "Coriandre fraîche",  g:   5, pct: 10.0, role: "parfum" },
        ],
        procede: ["Mixer la coriandre avec l'huile. Filtrer. Réserver."],
      },
    ],
    cuisson: { temperature_c: null, duree_min: 4, mode: "feu moyen" },
    temperatures: { service_c: 6, conservation_c: 4 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten"],
    tags: ["bouillon", "coco", "galanga", "thaï", "raviole", "tapioca", "coriandre", "vegan", "création"],
    parfum_principal: "coco",
    note_concepteur: "Quantités aromates du bouillon non précisées dans la source — inclus avec g: 0. Brunoise ananas non modélisée. Vérifier sur source p.250.",
    source_interne: { fichier_pdf: "Révolution-Pâtisserie.-La-bible-de-la-pâtisserie-saine-Johanna-Le-Pape_-Mlanie-Frechon-_-WeLib_organized.pdf", page: 250, chef: "Johanna Le Pape", date_extraction: "2026-05-20" },
  },
];
