const _SRC_LP = "Révolution-Pâtisserie.-La-bible-de-la-pâtisserie-saine-Johanna-Le-Pape_-Mlanie-Frechon-_-WeLib_organized.pdf";
const _CHEF_LP = "Johanna Le Pape";
const _DATE_LP = "2026-05-20";

export const RECETTES_BISCUITS = [
  {
    id: "biscuit-joconde-01",
    nom: "Biscuit Joconde",
    categorie: "biscuits",
    sous_categorie: "biscuit_leger",
    description: "Biscuit léger aux amandes, fin et souple, support classique d'entremets. Cuit en feuille.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Poudre d'amande",  g: 250, pct: 25, role: "parfum"    },
      { nom: "Sucre glace",      g: 250, pct: 25, role: "sucrant"   },
      { nom: "Œufs entiers",     g: 300, pct: 30, role: "liant"     },
      { nom: "Farine T45",       g:  50, pct:  5, role: "structure" },
      { nom: "Blancs d'œufs",   g: 120, pct: 12, role: "aeration"  },
      { nom: "Sucre semoule",    g:  30, pct:  3, role: "sucrant"   },
    ],
    procede: [
      "Monter les œufs entiers avec la poudre d'amande et le sucre glace au batteur jusqu'au ruban.",
      "Incorporer la farine tamisée à la maryse.",
      "Monter les blancs en neige souple, serrer avec le sucre semoule.",
      "Incorporer délicatement la meringue à l'appareil amande en deux fois.",
      "Étaler 700 g sur plaque 40×60 chemisée. Cuire immédiatement.",
      "Four à 230 °C chaleur tournante, 5–6 min. Le biscuit doit rester souple.",
      "Retourner sur papier sulfurisé à la sortie du four, décoller le papier de cuisson.",
    ],
    cuisson: { temperature_c: 230, duree_min: 6, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf", "fruits_a_coque"],
    tags: ["amande", "entremets", "support", "leger"],
    parfum_principal: "amande",
    note_concepteur: "Ne pas trop cuire : un biscuit trop sec se craquelera au roulage. Le retournement à chaud est essentiel pour le décoller proprement.",
    source_interne: {
      fichier_pdf: null,
      page: null,
      nom_original: "Biscuit de test — recette générique",
      chef: null,
      date_extraction: "2026-05-18",
    },
  },

  {
    id: "dacquoise-noisette-01",
    nom: "Dacquoise noisette",
    categorie: "biscuits",
    sous_categorie: "biscuit_meringue",
    description: "Biscuit meringué à la noisette, croustillant en surface et moelleux à cœur. Sans gluten.",
    masse_totale_g: 800,
    ingredients: [
      { nom: "Blancs d'œufs",       g: 300, pct: 37.5, role: "aeration"  },
      { nom: "Sucre glace",          g: 200, pct: 25,   role: "sucrant"   },
      { nom: "Poudre de noisette",   g: 280, pct: 35,   role: "parfum"    },
      { nom: "Fécule de maïs",       g:  20, pct:  2.5, role: "structure" },
    ],
    procede: [
      "Torréfier la poudre de noisette 10 min à 150 °C, refroidir.",
      "Monter les blancs en neige souple. Incorporer le sucre glace tamisé en 3 fois pour obtenir une meringue ferme.",
      "Mélanger poudre de noisette et fécule. Incorporer à la meringue par mouvements enveloppants.",
      "Dresser à la poche en disques ou étaler en feuille à 5 mm.",
      "Saupoudrer légèrement de sucre glace.",
      "Cuire à 170 °C chaleur tournante, 18 min. La surface doit résister légèrement à la pression.",
      "Refroidir sur grille avant de décoller.",
    ],
    cuisson: { temperature_c: 170, duree_min: 18, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["oeuf", "fruits_a_coque"],
    tags: ["noisette", "meringue", "sans gluten", "entremets", "support"],
    parfum_principal: "noisette",
    note_concepteur: "La torréfaction de la poudre de noisette est indispensable pour développer les arômes. La dacquoise se conserve très bien congelée.",
    source_interne: {
      fichier_pdf: null,
      page: null,
      nom_original: "Biscuit de test — recette générique",
      chef: null,
      date_extraction: "2026-05-18",
    },
  },

  {
    id: "financier-amande-01",
    nom: "Financier amande",
    categorie: "biscuits",
    sous_categorie: "petit_gateau",
    description: "Petit gâteau moelleux au beurre noisette et à la poudre d'amande. Bords caramélisés, cœur fondant.",
    masse_totale_g: 500,
    ingredients: [
      { nom: "Beurre noisette",  g: 175, pct: 35, role: "mg"        },
      { nom: "Poudre d'amande", g: 110, pct: 22, role: "parfum"    },
      { nom: "Sucre glace",      g: 125, pct: 25, role: "sucrant"   },
      { nom: "Farine T55",       g:  40, pct:  8, role: "structure" },
      { nom: "Blancs d'œufs",   g:  50, pct: 10, role: "liant"     },
    ],
    procede: [
      "Cuire le beurre à feu moyen jusqu'à coloration noisette et odeur de noix torréfiées. Passer au chinois, refroidir à 40 °C.",
      "Tamiser ensemble poudre d'amande, sucre glace et farine.",
      "Incorporer les blancs d'œufs liquides (non montés) au mélange sec.",
      "Ajouter le beurre noisette tiède en filet. Mélanger jusqu'à pâte lisse.",
      "Laisser reposer 30 min au réfrigérateur (optionnel, améliore la tenue).",
      "Remplir des moules à financier beurrés aux ¾.",
      "Cuire à 200 °C chaleur tournante, 8 min (moules mini). Démouler tiède.",
    ],
    cuisson: { temperature_c: 200, duree_min: 8, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf", "lactose", "fruits_a_coque"],
    tags: ["amande", "beurre noisette", "moelleux", "petit gateau"],
    parfum_principal: "amande",
    note_concepteur: "La clé est la qualité du beurre noisette : il doit être ambré mais non brûlé. Un beurre noisette trop pâle manque d'arôme.",
    source_interne: {
      fichier_pdf: null,
      page: null,
      nom_original: "Biscuit de test — recette générique",
      chef: null,
      date_extraction: "2026-05-18",
    },
  },

  {
    id: "biscuit-entremets-chocolat",
    nom: "Biscuit entremets chocolat",
    categorie: "biscuits",
    sous_categorie: "biscuit_entremets",
    description: "Biscuit chocolat moelleux cuit en cadre, structure légère et homogène. Adapté à la découpe en couches pour montages.",
    masse_totale_g: 502,
    ingredients: [
      { nom: "Œuf entier",               g: 125,  pct: 25,  role: "liant"     },
      { nom: "Farine T45",               g: 60,   pct: 12,  role: "structure" },
      { nom: "Levure chimique",          g: 2.5,  pct: 0.5, role: "structure" },
      { nom: "Sucre semoule",            g: 74,   pct: 15,  role: "sucrant"   },
      { nom: "Sucre inverti",            g: 12,   pct: 2,   role: "sucrant"   },
      { nom: "Huile de pépins de raisin",g: 76,   pct: 15,  role: "mg"        },
      { nom: "Sel",                      g: 1,    pct: 0.5, role: "exhausteur"},
      { nom: "Chocolat 58%",             g: 151,  pct: 30,  role: "parfum"    },
    ],
    procede: [
      "Fondre le chocolat et l'huile à 45°C.",
      "Ajouter le mélange œufs, sucre semoule, sucre inverti et sel.",
      "Terminer avec la farine et la levure chimique tamisées.",
      "Verser dans un cadre de 20×20 cm. Cuire 10-12 min à 170°C en four ventilé.",
    ],
    cuisson: { temperature_c: 170, duree_min: 11, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf"],
    tags: ["biscuit", "chocolat", "entremets", "moelleux", "cadre"],
    parfum_principal: "chocolat",
    note_concepteur: "Pour plus de moelleux, privilégier une cuisson et un refroidissement rapide. La farine T45 peut être remplacée par un mix sans gluten (riz complet 40% / fécule de pomme de terre 30% / amidon de maïs 30%).",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 46,
      chef: null,
    },
  },

  {
    id: "mi-cuit-chocolat",
    nom: "Mi-cuit chocolat",
    categorie: "biscuits",
    sous_categorie: "mi_cuit",
    description: "Gâteau individuel au cœur coulant, à servir immédiatement à la sortie du four. Meringue incorporée pour une texture aérée.",
    masse_totale_g: 255,
    ingredients: [
      { nom: "Beurre doux",              g: 25,   pct: 10, role: "mg"        },
      { nom: "Blanc d'œuf pasteurisé",  g: 75,   pct: 29, role: "aeration"  },
      { nom: "Jaune d'œuf pasteurisé",  g: 18,   pct: 7,  role: "liant"     },
      { nom: "Sucre semoule",            g: 20,   pct: 8,  role: "sucrant"   },
      { nom: "Amidon de maïs",           g: 12.5, pct: 5,  role: "structure" },
      { nom: "Chocolat 58%",             g: 105,  pct: 41, role: "parfum"    },
    ],
    procede: [
      "Dans une cuve de batteur, monter les blancs en neige en incorporant progressivement le sucre.",
      "Fondre le chocolat et le beurre à 50°C, ajouter les jaunes d'œufs et l'amidon de maïs.",
      "Incorporer délicatement la meringue à l'appareil chocolat.",
      "Mettre en poche, garnir des cercles ou moules chemisés de papier sulfurisé.",
      "Cuire environ 5-6 min à 185°C. Démouler après quelques minutes, servir aussitôt.",
    ],
    cuisson: { temperature_c: 185, duree_min: 6, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["mi-cuit", "coulant", "chocolat", "dessert chaud", "pièce individuelle"],
    parfum_principal: "chocolat",
    note_concepteur: "Pour un cœur bien coulant, laisser reposer à 4°C avant cuisson. La cuisson doit être ajustée en fonction du four et de la taille du mi-cuit.",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 47,
      chef: null,
    },
  },

  {
    id: "biscuit-pate-a-choux-chocolat",
    nom: "Biscuit pâte à choux chocolat",
    categorie: "biscuits",
    sous_categorie: "biscuit_pate_a_choux",
    description: "Biscuit moelleux et flexible sur base pâte à choux, aéré à la meringue. Idéal pour bûches roulées et décors.",
    masse_totale_g: 743,
    ingredients: [
      { nom: "Beurre doux",               g: 60,  pct: 8,  role: "mg"        },
      { nom: "Lait UHT entier",            g: 67,  pct: 9,  role: "eau"       },
      { nom: "Sucre inverti",              g: 37,  pct: 5,  role: "sucrant"   },
      { nom: "Farine T45",                 g: 75,  pct: 10, role: "structure" },
      { nom: "Œuf entier",                 g: 75,  pct: 10, role: "liant"     },
      { nom: "Jaune d'œuf pasteurisé",    g: 127, pct: 17, role: "liant"     },
      { nom: "Sucre semoule",              g: 90,  pct: 12, role: "sucrant"   },
      { nom: "Blanc d'œuf pasteurisé",    g: 187, pct: 25, role: "aeration"  },
      { nom: "Poudre de cacao",            g: 25,  pct: 4,  role: "parfum"    },
    ],
    procede: [
      "Dans une casserole, faire bouillir le lait, le beurre et le sucre inverti.",
      "Hors du feu, ajouter la poudre de cacao et la farine tamisée, mélanger jusqu'à pâte lisse.",
      "Laisser refroidir à 45-50°C, puis ajouter progressivement les œufs entiers.",
      "Dans une cuve, monter les blancs à vitesse moyenne en serrant avec le sucre semoule (meringue ferme mais pas trop).",
      "Dans une autre cuve, monter les jaunes au ruban.",
      "Incorporer délicatement la meringue à l'appareil puis les jaunes montés.",
      "Étaler sur plaque avec tapis siliconé. Cuire 10-12 min à 170°C.",
      "Faire glisser sur grille dès la sortie du four. Retourner et retirer délicatement le tapis.",
    ],
    cuisson: { temperature_c: 170, duree_min: 11, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf", "gluten"],
    tags: ["biscuit", "pâte à choux", "chocolat", "roulé", "décoration", "flexible"],
    parfum_principal: "chocolat",
    note_concepteur: "Ce biscuit très moelleux et flexible est idéal en décoration ou pour réaliser des bûches roulées. La farine T45 peut être remplacée par un mix sans gluten (riz complet 40% / fécule de pomme de terre 30% / amidon de maïs 30%).",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 48,
      chef: null,
    },
  },
  {
    id: "biscuit-micro-ondes-noisette",
    nom: "Biscuit micro-ondes noisette",
    categorie: "biscuits",
    sous_categorie: "biscuit_leger",
    description: "Biscuit aéré cuit en 60 secondes au micro-ondes. Texture mousseuse et légère, parfum noisette et chocolat au lait.",
    masse_totale_g: 766,
    ingredients: [
      { nom: "Noisettes en poudre", g: 120, pct: 16, role: "parfum"    },
      { nom: "Blancs d'œufs",      g: 250, pct: 33, role: "aeration"  },
      { nom: "Jaunes d'œufs",      g: 160, pct: 21, role: "liant"     },
      { nom: "Sucre semoule",       g: 140, pct: 18, role: "sucrant"   },
      { nom: "Farine T45",          g: 38,  pct: 5,  role: "structure" },
      { nom: "Couverture lait",     g: 58,  pct: 7,  role: "parfum"    },
    ],
    procede: [
      "Fondre la couverture au lait. Réserver à 30°C.",
      "Mélanger jaunes, sucre, farine et noisettes en poudre. Ajouter la couverture fondue.",
      "Monter les blancs en neige souple.",
      "Incorporer délicatement les blancs à l'appareil.",
      "Verser dans des cups en papier ou silicone.",
      "Cuire au micro-ondes 60 secondes à pleine puissance (600–800 W).",
      "Retourner immédiatement, laisser refroidir avant de démouler.",
    ],
    cuisson: { temperature_c: null, duree_min: 1, mode: "micro-ondes" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["oeuf", "lait", "gluten", "fruits_a_coque"],
    tags: ["biscuit", "micro-ondes", "noisette", "chocolat au lait", "aéré", "rapide"],
    parfum_principal: "noisette",
    note_concepteur: "La cuisson varie selon la puissance du micro-ondes (600–800 W recommandé). Utiliser des cups en papier ou silicone.",
    source_interne: {
      fichier_pdf: "Bachour Simply Beautiful.pdf",
      page: 114,
      chef: null,
    },
  },
  {
    id: "biscuit-micro-ondes-pistache",
    nom: "Biscuit micro-ondes pistache",
    categorie: "biscuits",
    sous_categorie: "biscuit_leger",
    description: "Biscuit ultra-léger cuit au micro-ondes. Goût pistache prononcé, sans farine ni matière grasse laitière.",
    masse_totale_g: 460,
    ingredients: [
      { nom: "Pâte de pistache",  g: 220, pct: 48, role: "parfum"    },
      { nom: "Blancs d'œufs",    g: 180, pct: 39, role: "aeration"  },
      { nom: "Poudre d'amande",  g: 60,  pct: 13, role: "structure" },
    ],
    procede: [
      "Mélanger la pâte de pistache et la poudre d'amande jusqu'à homogénéité.",
      "Monter les blancs en neige souple.",
      "Incorporer délicatement les blancs à l'appareil pistache.",
      "Verser dans des cups en silicone ou papier.",
      "Cuire au micro-ondes 60 secondes à pleine puissance.",
      "Retourner immédiatement, laisser refroidir avant de démouler.",
    ],
    cuisson: { temperature_c: null, duree_min: 1, mode: "micro-ondes" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["oeuf", "fruits_a_coque"],
    tags: ["biscuit", "micro-ondes", "pistache", "aéré", "rapide", "sans gluten", "sans lactose"],
    parfum_principal: "pistache",
    note_concepteur: "Sans farine ni matière grasse laitière. Texture spongieuse et délicate.",
    source_interne: {
      fichier_pdf: "Bachour Simply Beautiful.pdf",
      page: 116,
      chef: null,
    },
  },

  /* ── Révolution Pâtisserie — Johanna Le Pape ────────────────────────────── */

  {
    id: "biscuit-roule-lp",
    nom: "Biscuit roulé",
    categorie: "biscuits",
    sous_categorie: "biscuit_leger",
    description: "Biscuit roulé léger aux farines d'épeautre et fécule d'arrow-root, aéré par des blancs montés. Pour une plaque de 30 × 40 cm.",
    masse_totale_g: 575,
    ingredients: [
      { nom: "Blancs d'œufs",       g: 165, pct: 28.7, role: "aeration"  },
      { nom: "Œufs entiers",        g: 150, pct: 26.1, role: "liant"     },
      { nom: "Jaunes d'œufs",       g:  90, pct: 15.7, role: "liant"     },
      { nom: "Sucre complet",       g:  60, pct: 10.4, role: "sucrant"   },
      { nom: "Farine d'épeautre",   g:  60, pct: 10.4, role: "structure" },
      { nom: "Fécule d'arrow-root", g:  50, pct:  8.7, role: "structure" },
    ],
    procede: [
      "Tamiser la farine et la fécule.",
      "Monter les œufs entiers avec les jaunes et le sucre jusqu'à obtention d'une texture mousseuse.",
      "Monter en parallèle les blancs.",
      "Incorporer délicatement les blancs au mélange précédent.",
      "Terminer avec les poudres en pluie.",
      "Étaler sur une plaque de 30 × 40 cm avec un tapis en silicone.",
      "Cuire à 180 °C pendant 8 minutes.",
    ],
    cuisson: { temperature_c: 180, duree_min: 8, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten", "oeuf"],
    tags: ["biscuit roulé", "épeautre", "arrow-root", "entremets", "base"],
    parfum_principal: null,
    note_concepteur: "Quantité d'œufs (5 blancs + 5 jaunes + 3 œufs entiers) estimée depuis lecture visuelle — à vérifier sur source p.174. Alternative végétale : 130g yaourt végétal + 10g lait végétal + 4g vinaigre de cidre + 10g huile de coco.",
    source_interne: { fichier_pdf: _SRC_LP, page: 174, chef: _CHEF_LP, date_extraction: _DATE_LP },
  },

  {
    id: "biscuit-moelleux-amandes-lp",
    nom: "Biscuit moelleux amandes",
    categorie: "biscuits",
    sous_categorie: "biscuit_leger",
    description: "Biscuit moelleux pour cercle de 18 cm, à base de poudre d'amande, farine d'épeautre et psyllium. Aéré par un blanc monté.",
    masse_totale_g: 187,
    ingredients: [
      { nom: "Œuf entier",          g: 50, pct: 26.7, role: "liant"     },
      { nom: "Poudre d'amande",     g: 40, pct: 21.4, role: "parfum"    },
      { nom: "Blanc d'œuf",         g: 33, pct: 17.6, role: "aeration"  },
      { nom: "Sucre complet",       g: 30, pct: 16.0, role: "sucrant"   },
      { nom: "Jaune d'œuf",         g: 18, pct:  9.6, role: "liant"     },
      { nom: "Farine d'épeautre",   g: 10, pct:  5.3, role: "structure" },
      { nom: "Huile neutre",        g:  5, pct:  2.7, role: "mg"        },
      { nom: "Psyllium",            g:  1, pct:  0.5, role: "liant"     },
    ],
    procede: [
      "Préchauffer le four à chaleur tournante à 160 °C.",
      "Graisser un cercle ou un moule de 18 cm avec l'huile neutre.",
      "Mélanger l'œuf et le jaune avec le sucre à l'aide d'un fouet.",
      "Ajouter la poudre d'amande, la farine d'épeautre et le psyllium.",
      "Monter le blanc et serrer (texture mousse à raser). L'incorporer avec une maryse.",
      "Verser l'appareil dans le cercle.",
      "Cuire à 170 °C pendant 16 minutes.",
      "Laisser refroidir avant de retirer le cercle.",
    ],
    cuisson: { temperature_c: 170, duree_min: 16, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf", "fruits_a_coque"],
    tags: ["biscuit moelleux", "amande", "épeautre", "psyllium", "entremets", "base"],
    parfum_principal: "amande",
    note_concepteur: "Alternative farine sans gluten : remplacer par 10g de farine d'amande ou 5g de farine de pois chiches.",
    source_interne: { fichier_pdf: _SRC_LP, page: 176, chef: _CHEF_LP, date_extraction: _DATE_LP },
  },

  {
    id: "crepes-lp",
    nom: "Crêpes",
    categorie: "biscuits",
    sous_categorie: "crepe",
    description: "Crêpes légères sans gluten de blé, farine de riz et fécule d'arrow-root. Cuisson à la poêle.",
    masse_totale_g: 366,
    ingredients: [
      { nom: "Lait végétal",        g: 210, pct: 57.4, role: "eau"       },
      { nom: "Farine de riz",       g:  70, pct: 19.1, role: "structure" },
      { nom: "Œuf entier",          g:  50, pct: 13.7, role: "liant"     },
      { nom: "Fécule d'arrow-root", g:  30, pct:  8.2, role: "structure" },
      { nom: "Sel fin",             g:   3, pct:  0.8, role: "assaisonm" },
      { nom: "Sucre complet",       g:   3, pct:  0.8, role: "sucrant"   },
    ],
    procede: [
      "Tamiser la farine et la fécule dans un saladier.",
      "Ajouter l'œuf, le sel et le sucre, puis incorporer le lait végétal en fouettant.",
      "Laisser reposer 30 minutes au réfrigérateur.",
      "Cuire à la poêle antiadhésive légèrement huilée.",
    ],
    cuisson: { temperature_c: null, duree_min: 1, mode: "poêle" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["oeuf"],
    tags: ["crêpe", "riz", "arrow-root", "sans gluten", "petit déjeuner"],
    parfum_principal: null,
    note_concepteur: null,
    source_interne: { fichier_pdf: _SRC_LP, page: 194, chef: _CHEF_LP, date_extraction: _DATE_LP },
  },

  {
    id: "gaufres-lp",
    nom: "Gaufres",
    categorie: "biscuits",
    sous_categorie: "gaufre",
    description: "Gaufres dorées à base de farine d'avoine, bière blonde et huile de coco. Légères grâce au blanc monté.",
    masse_totale_g: 434,
    ingredients: [
      { nom: "Lait végétal",      g: 150, pct: 34.6, role: "eau"       },
      { nom: "Farine d'avoine",   g: 125, pct: 28.8, role: "structure" },
      { nom: "Bière blonde",      g:  50, pct: 11.5, role: "eau"       },
      { nom: "Sucre blond",       g:  40, pct:  9.2, role: "sucrant"   },
      { nom: "Blanc d'œuf",       g:  33, pct:  7.6, role: "aeration"  },
      { nom: "Jaune d'œuf",       g:  18, pct:  4.1, role: "liant"     },
      { nom: "Huile de coco",     g:  15, pct:  3.5, role: "mg"        },
      { nom: "Vanille en poudre", g:   2, pct:  0.5, role: "parfum"    },
      { nom: "Sel fin",           g:   1, pct:  0.2, role: "assaisonm" },
    ],
    procede: [
      "Mélanger la farine, le sel, le sucre et la vanille.",
      "Ajouter le lait végétal, la bière blonde, le jaune d'œuf et l'huile de coco fondue.",
      "Monter le blanc en neige souple et l'incorporer délicatement.",
      "Cuire dans un gaufrier préchauffé et légèrement huilé.",
    ],
    cuisson: { temperature_c: null, duree_min: 4, mode: "gaufrier" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf"],
    tags: ["gaufre", "avoine", "bière blonde", "coco", "petit déjeuner"],
    parfum_principal: "vanille",
    note_concepteur: null,
    source_interne: { fichier_pdf: _SRC_LP, page: 196, chef: _CHEF_LP, date_extraction: _DATE_LP },
  },

  {
    id: "pancakes-lp",
    nom: "Pancakes",
    categorie: "biscuits",
    sous_categorie: "pancake",
    description: "Pancakes moelleux aux farines d'épeautre et riz, lait de coco et psyllium.",
    masse_totale_g: 292,
    ingredients: [
      { nom: "Lait de coco",         g: 125, pct: 42.8, role: "eau"       },
      { nom: "Farine d'épeautre",    g:  40, pct: 13.7, role: "structure" },
      { nom: "Farine de riz",        g:  40, pct: 13.7, role: "structure" },
      { nom: "Œuf entier",           g:  50, pct: 17.1, role: "liant"     },
      { nom: "Sucre complet",        g:  30, pct: 10.3, role: "sucrant"   },
      { nom: "Psyllium",             g:   3, pct:  1.0, role: "liant"     },
      { nom: "Bicarbonate de soude", g:   2, pct:  0.7, role: "levant"    },
      { nom: "Vanille en poudre",    g:   2, pct:  0.7, role: "parfum"    },
    ],
    procede: [
      "Mélanger les farines, le psyllium, le bicarbonate, le sucre et la vanille.",
      "Ajouter l'œuf et le lait de coco. Fouetter jusqu'à pâte lisse.",
      "Laisser reposer 10 minutes.",
      "Cuire à la poêle légèrement huilée, environ 2 minutes par face.",
    ],
    cuisson: { temperature_c: null, duree_min: 4, mode: "poêle" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf"],
    tags: ["pancake", "épeautre", "riz", "coco", "psyllium", "petit déjeuner"],
    parfum_principal: "vanille",
    note_concepteur: null,
    source_interne: { fichier_pdf: _SRC_LP, page: 198, chef: _CHEF_LP, date_extraction: _DATE_LP },
  },

  {
    id: "babka-chocolat-lp",
    nom: "Babka chocolat",
    categorie: "biscuits",
    sous_categorie: "viennoiserie",
    type: "assemblage",
    description: "Babka briochée à la farine T80, sans beurre, enroulée d'une garniture chocolat noir, sucre de coco et psyllium.",
    composants: [
      {
        nom: "Pâte à babka",
        masse_g: 733,
        ingredients: [
          { nom: "Farine T80",        g: 400, pct: 54.6, role: "structure" },
          { nom: "Lait végétal",      g: 150, pct: 20.5, role: "eau"       },
          { nom: "Miel",              g:  80, pct: 10.9, role: "sucrant"   },
          { nom: "Huile neutre",      g:  80, pct: 10.9, role: "mg"        },
          { nom: "Levure boulangère", g:  14, pct:  1.9, role: "levant"    },
          { nom: "Sel fin",           g:   9, pct:  1.2, role: "assaisonm" },
        ],
        procede: [
          "Mélanger la levure avec le lait végétal tiède et le miel.",
          "Ajouter la farine, l'huile et le sel. Pétrir jusqu'à pâte lisse et élastique.",
          "Laisser lever 1 heure à température ambiante.",
          "Étaler en rectangle.",
        ],
      },
      {
        nom: "Intérieur chocolat",
        masse_g: 143,
        ingredients: [
          { nom: "Chocolat noir 70%", g: 100, pct: 70.0, role: "parfum"  },
          { nom: "Sucre de coco",     g:  40, pct: 28.0, role: "sucrant" },
          { nom: "Psyllium",          g:   3, pct:  2.0, role: "liant"   },
        ],
        procede: [
          "Fondre le chocolat au bain-marie.",
          "Mélanger avec le sucre de coco et le psyllium.",
          "Étaler sur la pâte étalée.",
          "Rouler et tordre la pâte pour former le babka. Placer dans un moule à cake.",
          "Laisser lever 30 minutes.",
          "Cuire à 180 °C pendant 25 à 30 minutes.",
        ],
      },
    ],
    cuisson: { temperature_c: 180, duree_min: 28, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten"],
    tags: ["babka", "brioche", "chocolat", "levée", "T80", "sans beurre"],
    parfum_principal: "chocolat",
    note_concepteur: "Quantité de chocolat pour l'intérieur (100g) et psyllium (3g) estimés — à vérifier sur source p.200.",
    source_interne: { fichier_pdf: _SRC_LP, page: 200, chef: _CHEF_LP, date_extraction: _DATE_LP },
  },

  {
    id: "cake-citron-lp",
    nom: "Cake citron",
    categorie: "biscuits",
    sous_categorie: "cake",
    description: "Cake citron moelleux à la courgette râpée, farine d'épeautre, arrow-root et pavot. Glaçage au miel et zeste de citron.",
    masse_totale_g: 422,
    ingredients: [
      { nom: "Lait végétal",          g: 100, pct: 23.7, role: "eau"       },
      { nom: "Jus et zeste de citron", g:  80, pct: 19.0, role: "parfum"   },
      { nom: "Farine d'épeautre",     g:  70, pct: 16.6, role: "structure" },
      { nom: "Sucre de datte",        g:  60, pct: 14.2, role: "sucrant"   },
      { nom: "Œuf entier",            g:  50, pct: 11.8, role: "liant"     },
      { nom: "Courgette râpée",       g:  40, pct:  9.5, role: "eau"       },
      { nom: "Graines de pavot",      g:  10, pct:  2.4, role: "parfum"    },
      { nom: "Fécule d'arrow-root",   g:  10, pct:  2.4, role: "structure" },
      { nom: "Bicarbonate de soude",  g:   1, pct:  0.2, role: "levant"    },
      { nom: "Fleur de sel",          g:   1, pct:  0.2, role: "assaisonm" },
    ],
    procede: [
      "Mélanger la farine avec la courgette broyée en petits morceaux et les sucres.",
      "Ajouter le lait végétal, l'œuf, le bicarbonate, le jus du citron et la fleur de sel.",
      "Graisser le moule et verser l'appareil.",
      "Cuire au four à 160 °C pendant 45 minutes.",
      "Glaçage citron : mélanger miel et zeste de citron et napper à la sortie du four.",
    ],
    cuisson: { temperature_c: 160, duree_min: 45, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten", "oeuf"],
    tags: ["cake", "citron", "courgette", "épeautre", "pavot", "moelleux"],
    parfum_principal: "citron",
    note_concepteur: "Quantités lait végétal et arrow-root estimées depuis lecture visuelle — vérifier sur source p.202. Arrow-root et lait pourraient figurer dans le glaçage.",
    source_interne: { fichier_pdf: _SRC_LP, page: 202, chef: _CHEF_LP, date_extraction: _DATE_LP },
  },

  {
    id: "banana-bread-lp",
    nom: "Banana bread",
    categorie: "biscuits",
    sous_categorie: "cake",
    description: "Banana bread sans gluten de blé, aux farines de riz et de banane verte, purée de banane et huile de pépins. Naturellement sucré.",
    masse_totale_g: 370,
    ingredients: [
      { nom: "Purée de banane",            g: 160, pct: 43.2, role: "eau"       },
      { nom: "Huile de pépins de raisin",  g:  60, pct: 16.2, role: "mg"        },
      { nom: "Œuf entier",                 g:  50, pct: 13.5, role: "liant"     },
      { nom: "Farine de riz complet",      g:  40, pct: 10.8, role: "structure" },
      { nom: "Farine de banane verte",     g:  40, pct: 10.8, role: "structure" },
      { nom: "Sucre complet",              g:  10, pct:  2.7, role: "sucrant"   },
      { nom: "Jus de citron",              g:   5, pct:  1.4, role: "parfum"    },
      { nom: "Bicarbonate de soude",       g:   5, pct:  1.4, role: "levant"    },
    ],
    procede: [
      "Peler et couper une banane dans sa longueur puis en 2. La disposer au fond du moule graissé et l'arroser de sirop de yacon (décor).",
      "Mélanger la purée de banane avec l'huile et l'œuf. Ajouter les sucres et les farines tamisées.",
      "Mélanger le bicarbonate avec le jus de citron et l'ajouter à l'appareil.",
      "Cuire au four à 160 °C pendant 45 minutes.",
    ],
    cuisson: { temperature_c: 160, duree_min: 45, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: true },
    a_verifier: false,
    allergenes: ["oeuf"],
    tags: ["banana bread", "banane", "riz", "sans gluten", "ig bas", "moelleux"],
    parfum_principal: "banane",
    note_concepteur: "Alternative végétale : remplacer l'œuf par 30g de fécule de maïs + 20g d'huile + 10g de purée de banane.",
    source_interne: { fichier_pdf: _SRC_LP, page: 204, chef: _CHEF_LP, date_extraction: _DATE_LP },
  },

  {
    id: "carrot-cake-lp",
    nom: "Carrot cake",
    categorie: "biscuits",
    sous_categorie: "cake",
    description: "Carrot cake aux carottes râpées, poudre d'amande, farine T110 et épices. Sans produits laitiers. Glaçage aux épices.",
    masse_totale_g: 441,
    ingredients: [
      { nom: "Carottes râpées",            g: 150, pct: 34.0, role: "eau"       },
      { nom: "Farine T110",                g:  75, pct: 17.0, role: "structure" },
      { nom: "Poudre d'amande",            g:  65, pct: 14.7, role: "parfum"    },
      { nom: "Huile de pépins de raisin",  g:  45, pct: 10.2, role: "mg"        },
      { nom: "Œuf entier",                 g:  50, pct: 11.3, role: "liant"     },
      { nom: "Sucre de coco",              g:  40, pct:  9.1, role: "sucrant"   },
      { nom: "Noix de pécan concassées",   g:  12, pct:  2.7, role: "parfum"    },
      { nom: "Gingembre frais",            g:   1, pct:  0.2, role: "parfum"    },
      { nom: "Cannelle en poudre",         g:   1, pct:  0.2, role: "parfum"    },
      { nom: "Fleur de sel",               g:   1, pct:  0.2, role: "assaisonm" },
      { nom: "Bicarbonate de soude",       g:   1, pct:  0.2, role: "levant"    },
    ],
    procede: [
      "Mélanger tous les ingrédients.",
      "Verser dans un moule préalablement graissé.",
      "Cuire au four à 160 °C pendant 45 minutes.",
      "Glaçage aux épices : mélanger 100g lait végétal + 10g arrow-root + 10g miel + 7g huile d'olive + zeste ½ citron. Napper après refroidissement.",
    ],
    cuisson: { temperature_c: 160, duree_min: 45, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf", "fruits_a_coque"],
    tags: ["carrot cake", "carotte", "amande", "épices", "T110", "sans lactose"],
    parfum_principal: "cannelle",
    note_concepteur: "Alternative sans gluten : 50g farine de riz + 75g farine de souchet + 40g lait végétal. Glaçage non inclus dans la masse totale.",
    source_interne: { fichier_pdf: _SRC_LP, page: 206, chef: _CHEF_LP, date_extraction: _DATE_LP },
  },

  {
    id: "cake-marbre-lp",
    nom: "Cake marbré",
    categorie: "biscuits",
    sous_categorie: "cake",
    description: "Cake marbré vanille-chocolat à la farine d'épeautre, poudre de noisette et psyllium. Marbrure obtenue par striage.",
    masse_totale_g: 345,
    ingredients: [
      { nom: "Blancs d'œufs",            g:  66, pct: 19.1, role: "aeration"  },
      { nom: "Lait végétal",             g:  60, pct: 17.4, role: "eau"       },
      { nom: "Farine d'épeautre",        g:  55, pct: 15.9, role: "structure" },
      { nom: "Poudre de noisette",       g:  50, pct: 14.5, role: "parfum"    },
      { nom: "Huile de pépins de raisin",g:  40, pct: 11.6, role: "mg"        },
      { nom: "Sucre de datte",           g:  40, pct: 11.6, role: "sucrant"   },
      { nom: "Jaune d'œuf",              g:  18, pct:  5.2, role: "liant"     },
      { nom: "Cacao en poudre",          g:  10, pct:  2.9, role: "parfum"    },
      { nom: "Psyllium",                 g:   4, pct:  1.2, role: "liant"     },
      { nom: "Sel fin",                  g:   1, pct:  0.3, role: "assaisonm" },
      { nom: "Bicarbonate de soude",     g:   1, pct:  0.3, role: "levant"    },
    ],
    procede: [
      "Monter les blancs d'œufs.",
      "Mélanger le sucre avec la poudre de noisette, le psyllium, le jaune et le sel.",
      "Tamiser la farine d'épeautre avec le bicarbonate et l'ajouter à l'appareil.",
      "Ajouter le lait végétal et l'huile. Incorporer délicatement les blancs montés.",
      "Séparer en 2 parts égales. Incorporer le cacao dans l'une.",
      "Dans un moule graissé, alterner les deux pâtes 3 fois et strier avec une spatule.",
      "Cuire à 170 °C pendant 25 minutes.",
    ],
    cuisson: { temperature_c: 170, duree_min: 25, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf", "fruits_a_coque"],
    tags: ["cake marbré", "chocolat", "noisette", "épeautre", "psyllium"],
    parfum_principal: "chocolat",
    note_concepteur: "Alternative farine : remplacer par 50g de farine de riz complet + 20g de fécule d'arrow-root.",
    source_interne: { fichier_pdf: _SRC_LP, page: 208, chef: _CHEF_LP, date_extraction: _DATE_LP },
  },

  {
    id: "brownie-lp",
    nom: "Brownie",
    categorie: "biscuits",
    sous_categorie: "brownie",
    description: "Brownie vegan sans œuf ni beurre, à base de chocolat 66%, compote de pommes et fécule de maïs. Dense et fondant.",
    masse_totale_g: 382,
    ingredients: [
      { nom: "Sucre complet",            g:  60, pct: 15.7, role: "sucrant"   },
      { nom: "Noix de pécan concassées", g:  50, pct: 13.1, role: "parfum"    },
      { nom: "Compote de pommes",        g:  50, pct: 13.1, role: "eau"       },
      { nom: "Fécule de maïs",           g:  50, pct: 13.1, role: "structure" },
      { nom: "Chocolat noir 66%",        g:  70, pct: 18.3, role: "parfum"    },
      { nom: "Poudre d'amande",          g:  40, pct: 10.5, role: "parfum"    },
      { nom: "Lait végétal",             g:  30, pct:  7.9, role: "eau"       },
      { nom: "Farine de riz complet",    g:  15, pct:  3.9, role: "structure" },
      { nom: "Jus de citron",            g:   8, pct:  2.1, role: "parfum"    },
      { nom: "Cacao en poudre",          g:   7, pct:  1.8, role: "parfum"    },
      { nom: "Fleur de sel",             g:   1, pct:  0.3, role: "assaisonm" },
      { nom: "Bicarbonate de soude",     g:   1, pct:  0.3, role: "levant"    },
    ],
    procede: [
      "Faire fondre le chocolat.",
      "Porter le lait à frémissement et verser sur le chocolat en 3 fois en fouettant.",
      "Ajouter la compote puis le sucre. Tamiser la farine, la fécule et le cacao. Incorporer avec la poudre d'amande et les noix de pécan.",
      "Verser dans un moule graissé. Cuire à 160 °C pendant 20 minutes.",
    ],
    cuisson: { temperature_c: 160, duree_min: 20, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["fruits_a_coque"],
    tags: ["brownie", "chocolat", "vegan", "sans oeuf", "compote", "pécan"],
    parfum_principal: "chocolat",
    note_concepteur: "Alternative sucre : remplacer par 30g de sucre de coco ou 30g de sirop de yacon.",
    source_interne: { fichier_pdf: _SRC_LP, page: 210, chef: _CHEF_LP, date_extraction: _DATE_LP },
  },

  {
    id: "madeleines-lp",
    nom: "Madeleines",
    categorie: "biscuits",
    sous_categorie: "petit_gateau",
    description: "Madeleines moelleuses à la farine T80, miel et beurre. Choc thermique froid–chaud pour la bosse.",
    masse_totale_g: 175,
    ingredients: [
      { nom: "Œuf entier",           g:  50, pct: 28.6, role: "liant"     },
      { nom: "Farine T80",           g:  50, pct: 28.6, role: "structure" },
      { nom: "Beurre",               g:  30, pct: 17.1, role: "mg"        },
      { nom: "Miel",                 g:  14, pct:  8.0, role: "sucrant"   },
      { nom: "Sucre blond",          g:  10, pct:  5.7, role: "sucrant"   },
      { nom: "Sucre complet",        g:  10, pct:  5.7, role: "sucrant"   },
      { nom: "Lait végétal",         g:  10, pct:  5.7, role: "eau"       },
      { nom: "Bicarbonate de soude", g:   1, pct:  0.6, role: "levant"    },
    ],
    procede: [
      "Mélanger l'œuf avec les sucres et le miel.",
      "Ajouter la farine tamisée avec le bicarbonate, puis le beurre fondu tiède et le lait végétal.",
      "Réfrigérer la pâte 30 minutes minimum.",
      "Remplir les moules à madeleines graissés aux ¾.",
      "Cuire à 190 °C pendant 10 minutes.",
    ],
    cuisson: { temperature_c: 190, duree_min: 10, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf", "lait"],
    tags: ["madeleine", "miel", "beurre", "T80", "petit gâteau"],
    parfum_principal: "miel",
    note_concepteur: null,
    source_interne: { fichier_pdf: _SRC_LP, page: 212, chef: _CHEF_LP, date_extraction: _DATE_LP },
  },

  {
    id: "financiers-lp",
    nom: "Financiers",
    categorie: "biscuits",
    sous_categorie: "petit_gateau",
    description: "Financiers sains à la poudre et éclats d'amande, graines de pavot et miel. Peu de beurre, texture légère.",
    masse_totale_g: 173,
    ingredients: [
      { nom: "Éclats d'amande",      g:  40, pct: 23.1, role: "parfum"    },
      { nom: "Poudre d'amande",      g:  35, pct: 20.2, role: "parfum"    },
      { nom: "Blanc d'œuf",          g:  33, pct: 19.1, role: "liant"     },
      { nom: "Sucre complet",        g:  15, pct:  8.7, role: "sucrant"   },
      { nom: "Miel",                 g:  15, pct:  8.7, role: "sucrant"   },
      { nom: "Farine de riz",        g:  15, pct:  8.7, role: "structure" },
      { nom: "Graines de pavot",     g:  10, pct:  5.8, role: "parfum"    },
      { nom: "Beurre",               g:  10, pct:  5.8, role: "mg"        },
    ],
    procede: [
      "Fondre le beurre.",
      "Mélanger la poudre d'amande, les éclats d'amande, la farine de riz, le sucre, le pavot et le miel.",
      "Incorporer le blanc d'œuf puis le beurre fondu tiède.",
      "Répartir dans des moules à financier graissés.",
      "Cuire à 160 °C pendant 12 minutes.",
    ],
    cuisson: { temperature_c: 160, duree_min: 12, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf", "fruits_a_coque"],
    tags: ["financier", "amande", "pavot", "miel", "sans gluten"],
    parfum_principal: "amande",
    note_concepteur: null,
    source_interne: { fichier_pdf: _SRC_LP, page: 214, chef: _CHEF_LP, date_extraction: _DATE_LP },
  },

  {
    id: "cookies-lp",
    nom: "Cookies",
    categorie: "biscuits",
    sous_categorie: "cookie",
    description: "Cookies croustillants à la farine d'épeautre, purée de noisette, miel et éclats de chocolat. Tenus par le psyllium.",
    masse_totale_g: 368,
    ingredients: [
      { nom: "Farine d'épeautre",   g: 125, pct: 34.0, role: "structure" },
      { nom: "Huile neutre",        g:  50, pct: 13.6, role: "mg"        },
      { nom: "Œuf entier",          g:  50, pct: 13.6, role: "liant"     },
      { nom: "Éclats de chocolat",  g:  40, pct: 10.9, role: "parfum"    },
      { nom: "Purée de noisette",   g:  40, pct: 10.9, role: "mg"        },
      { nom: "Sucre complet",       g:  30, pct:  8.2, role: "sucrant"   },
      { nom: "Miel",                g:  30, pct:  8.2, role: "sucrant"   },
      { nom: "Psyllium",            g:   3, pct:  0.8, role: "liant"     },
    ],
    procede: [
      "Mélanger l'huile, la purée de noisette, le miel et le sucre.",
      "Ajouter l'œuf puis la farine et le psyllium tamisés.",
      "Incorporer les éclats de chocolat.",
      "Façonner des boules et les aplatir légèrement sur plaque.",
      "Cuire à 180 °C pendant 12 minutes.",
    ],
    cuisson: { temperature_c: 180, duree_min: 12, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf", "fruits_a_coque"],
    tags: ["cookie", "épeautre", "noisette", "chocolat", "miel", "psyllium"],
    parfum_principal: "chocolat",
    note_concepteur: null,
    source_interne: { fichier_pdf: _SRC_LP, page: 216, chef: _CHEF_LP, date_extraction: _DATE_LP },
  },

  {
    id: "energy-balls-lp",
    nom: "Energy balls",
    categorie: "biscuits",
    sous_categorie: "confiserie",
    description: "Boules énergétiques crues aux abricots secs, dattes, coco, farine de châtaigne, amandes et canneberges. Sans cuisson.",
    masse_totale_g: 527,
    ingredients: [
      { nom: "Abricots secs",        g: 160, pct: 30.4, role: "sucrant"   },
      { nom: "Noix de coco poudre",  g: 100, pct: 19.0, role: "structure" },
      { nom: "Dattes",               g:  70, pct: 13.3, role: "sucrant"   },
      { nom: "Farine de châtaigne",  g:  60, pct: 11.4, role: "structure" },
      { nom: "Banane séchée",        g:  50, pct:  9.5, role: "sucrant"   },
      { nom: "Amandes entières",     g:  45, pct:  8.5, role: "parfum"    },
      { nom: "Canneberges séchées",  g:  35, pct:  6.6, role: "parfum"    },
      { nom: "Graines de lin",       g:   7, pct:  1.3, role: "structure" },
    ],
    procede: [
      "Mixer les abricots secs et les dattes pour obtenir une pâte collante.",
      "Mélanger avec tous les autres ingrédients.",
      "Former des boules d'environ 20g.",
      "Rouler dans la noix de coco poudre si désiré.",
      "Conserver au réfrigérateur.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["fruits_a_coque"],
    tags: ["energy ball", "cru", "sans cuisson", "dattes", "abricot", "coco", "snack"],
    parfum_principal: "abricot",
    note_concepteur: null,
    source_interne: { fichier_pdf: _SRC_LP, page: 222, chef: _CHEF_LP, date_extraction: _DATE_LP },
  },

  {
    id: "bountys-healthy-lp",
    nom: "Bountys healthy",
    categorie: "biscuits",
    sous_categorie: "confiserie",
    type: "assemblage",
    description: "Version saine des Bounty : intérieur noix de coco–lait de coco enrobé de chocolat noir 66%.",
    composants: [
      {
        nom: "Intérieur coco",
        masse_g: 270,
        ingredients: [
          { nom: "Lait de coco",  g: 150, pct: 55.6, role: "eau"       },
          { nom: "Coco râpée",    g: 100, pct: 37.0, role: "structure" },
          { nom: "Miel",          g:  10, pct:  3.7, role: "sucrant"   },
          { nom: "Huile de coco", g:  10, pct:  3.7, role: "mg"        },
        ],
        procede: [
          "Mélanger la coco râpée avec le lait de coco, le miel et l'huile de coco.",
          "Former des rectangles ou boules. Congeler 30 minutes pour raffermir.",
        ],
      },
      {
        nom: "Enrobage chocolat",
        masse_g: 170,
        ingredients: [
          { nom: "Chocolat noir 66%",           g: 150, pct: 88.2, role: "parfum" },
          { nom: "Huile de pépins de raisin",   g:  20, pct: 11.8, role: "mg"     },
        ],
        procede: [
          "Fondre le chocolat avec l'huile au bain-marie.",
          "Tremper les intérieurs congelés dans le chocolat.",
          "Laisser figer au réfrigérateur.",
        ],
      },
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson" },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["bounty", "coco", "chocolat", "sans cuisson", "confiserie", "vegan"],
    parfum_principal: "chocolat",
    note_concepteur: null,
    source_interne: { fichier_pdf: _SRC_LP, page: 224, chef: _CHEF_LP, date_extraction: _DATE_LP },
  },

  {
    id: "snickers-healthy-lp",
    nom: "Snickers healthy",
    categorie: "biscuits",
    sous_categorie: "confiserie",
    type: "assemblage",
    description: "Version saine des Snickers : shortbread riz–sarrasin, caramel de dattes Medjool et pâte de cacahuète, enrobage chocolat noir.",
    composants: [
      {
        nom: "Shortbread",
        masse_g: 134,
        ingredients: [
          { nom: "Farine de riz",        g:  80, pct: 59.7, role: "structure" },
          { nom: "Eau",                  g:  15, pct: 11.2, role: "eau"       },
          { nom: "Compote de pomme",     g:  10, pct:  7.5, role: "eau"       },
          { nom: "Huile de coco",        g: 11.5, pct: 8.6, role: "mg"        },
          { nom: "Farine de sarrasin",   g:   9, pct:  6.7, role: "structure" },
          { nom: "Sucre complet",        g:   7.5, pct: 5.6, role: "sucrant"  },
          { nom: "Bicarbonate de soude", g:   1, pct:  0.7, role: "levant"    },
        ],
        procede: [
          "Mélanger tous les ingrédients jusqu'à pâte homogène.",
          "Étaler en rectangle à 5 mm d'épaisseur.",
          "Cuire à 170 °C pendant 20 minutes. Laisser refroidir.",
        ],
      },
      {
        nom: "Caramel de dattes",
        masse_g: 136,
        ingredients: [
          { nom: "Dattes Medjool",    g:  80, pct: 58.8, role: "sucrant"   },
          { nom: "Pâte de cacahuète", g:  40, pct: 29.4, role: "parfum"    },
          { nom: "Eau",               g:  15, pct: 11.0, role: "eau"       },
          { nom: "Fleur de sel",      g:   1, pct:  0.7, role: "assaisonm" },
        ],
        procede: [
          "Mixer les dattes dénoyautées avec l'eau jusqu'à consistance crémeuse.",
          "Incorporer la pâte de cacahuète et la fleur de sel. Mixer à nouveau.",
          "Étaler sur le shortbread refroidi.",
        ],
      },
      {
        nom: "Enrobage chocolat",
        masse_g: 160,
        ingredients: [
          { nom: "Chocolat noir 66%", g: 150, pct: 93.8, role: "parfum" },
          { nom: "Huile neutre",      g:  10, pct:  6.3, role: "mg"     },
        ],
        procede: [
          "Fondre le chocolat avec l'huile.",
          "Tremper les barres shortbread–caramel dans le chocolat fondu.",
          "Laisser figer au réfrigérateur.",
        ],
      },
    ],
    cuisson: { temperature_c: 170, duree_min: 20, mode: "chaleur tournante" },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["arachide"],
    tags: ["snickers", "dattes", "cacahuète", "chocolat", "confiserie", "sans gluten", "vegan"],
    parfum_principal: "chocolat",
    note_concepteur: "Arachide = allergène EU distinct des fruits à coque.",
    source_interne: { fichier_pdf: _SRC_LP, page: 226, chef: _CHEF_LP, date_extraction: _DATE_LP },
  },
];
