export const RECETTES_BISCUITS = [
  {
    id: "biscuit-joconde-01",
    nom: "Biscuit Joconde",
    categorie: "biscuits",
    sous_categorie: "biscuit_leger",
    description: "Biscuit léger aux amandes, fin et souple, support classique d'entremets. Cuit en feuille.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Poudre d'amande",  g: 250, pct: 25, role: "parfum"    },
      { nom: "Sucre glace",      g: 250, pct: 25, role: "sucrant"   },
      { nom: "Œufs entiers",     g: 300, pct: 30, role: "liant"     },
      { nom: "Farine T45",       g:  50, pct:  5, role: "structure" },
      { nom: "Blancs d'œufs",   g: 120, pct: 12, role: "aeration"  },
      { nom: "Sucre semoule",    g:  30, pct:  3, role: "sucrant"   },
    ],
    procede: [
      "Monter les œufs entiers avec la poudre d'amande et le sucre glace au batteur jusqu'au ruban.",
      "Incorporer la farine tamisée à la maryse.",
      "Monter les blancs en neige souple, serrer avec le sucre semoule.",
      "Incorporer délicatement la meringue à l'appareil amande en deux fois.",
      "Étaler 700 g sur plaque 40×60 chemisée. Cuire immédiatement.",
      "Four à 230 °C chaleur tournante, 5–6 min. Le biscuit doit rester souple.",
      "Retourner sur papier sulfurisé à la sortie du four, décoller le papier de cuisson.",
    ],
    cuisson: { temperature_c: 230, duree_min: 6, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf", "fruits_a_coque"],
    tags: ["amande", "entremets", "support", "leger"],
    parfum_principal: "amande",
    note_concepteur: "Ne pas trop cuire : un biscuit trop sec se craquelera au roulage. Le retournement à chaud est essentiel pour le décoller proprement.",
    source_interne: {
      fichier_pdf: null,
      page: null,
      nom_original: "Biscuit de test — recette générique",
      chef: null,
      date_extraction: "2026-05-18",
    },
  },

  {
    id: "dacquoise-noisette-01",
    nom: "Dacquoise noisette",
    categorie: "biscuits",
    sous_categorie: "biscuit_meringue",
    description: "Biscuit meringué à la noisette, croustillant en surface et moelleux à cœur. Sans gluten.",
    masse_totale_g: 800,
    ingredients: [
      { nom: "Blancs d'œufs",       g: 300, pct: 37.5, role: "aeration"  },
      { nom: "Sucre glace",          g: 200, pct: 25,   role: "sucrant"   },
      { nom: "Poudre de noisette",   g: 280, pct: 35,   role: "parfum"    },
      { nom: "Fécule de maïs",       g:  20, pct:  2.5, role: "structure" },
    ],
    procede: [
      "Torréfier la poudre de noisette 10 min à 150 °C, refroidir.",
      "Monter les blancs en neige souple. Incorporer le sucre glace tamisé en 3 fois pour obtenir une meringue ferme.",
      "Mélanger poudre de noisette et fécule. Incorporer à la meringue par mouvements enveloppants.",
      "Dresser à la poche en disques ou étaler en feuille à 5 mm.",
      "Saupoudrer légèrement de sucre glace.",
      "Cuire à 170 °C chaleur tournante, 18 min. La surface doit résister légèrement à la pression.",
      "Refroidir sur grille avant de décoller.",
    ],
    cuisson: { temperature_c: 170, duree_min: 18, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["oeuf", "fruits_a_coque"],
    tags: ["noisette", "meringue", "sans gluten", "entremets", "support"],
    parfum_principal: "noisette",
    note_concepteur: "La torréfaction de la poudre de noisette est indispensable pour développer les arômes. La dacquoise se conserve très bien congelée.",
    source_interne: {
      fichier_pdf: null,
      page: null,
      nom_original: "Biscuit de test — recette générique",
      chef: null,
      date_extraction: "2026-05-18",
    },
  },

  {
    id: "financier-amande-01",
    nom: "Financier amande",
    categorie: "biscuits",
    sous_categorie: "petit_gateau",
    description: "Petit gâteau moelleux au beurre noisette et à la poudre d'amande. Bords caramélisés, cœur fondant.",
    masse_totale_g: 500,
    ingredients: [
      { nom: "Beurre noisette",  g: 175, pct: 35, role: "mg"        },
      { nom: "Poudre d'amande", g: 110, pct: 22, role: "parfum"    },
      { nom: "Sucre glace",      g: 125, pct: 25, role: "sucrant"   },
      { nom: "Farine T55",       g:  40, pct:  8, role: "structure" },
      { nom: "Blancs d'œufs",   g:  50, pct: 10, role: "liant"     },
    ],
    procede: [
      "Cuire le beurre à feu moyen jusqu'à coloration noisette et odeur de noix torréfiées. Passer au chinois, refroidir à 40 °C.",
      "Tamiser ensemble poudre d'amande, sucre glace et farine.",
      "Incorporer les blancs d'œufs liquides (non montés) au mélange sec.",
      "Ajouter le beurre noisette tiède en filet. Mélanger jusqu'à pâte lisse.",
      "Laisser reposer 30 min au réfrigérateur (optionnel, améliore la tenue).",
      "Remplir des moules à financier beurrés aux ¾.",
      "Cuire à 200 °C chaleur tournante, 8 min (moules mini). Démouler tiède.",
    ],
    cuisson: { temperature_c: 200, duree_min: 8, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf", "lactose", "fruits_a_coque"],
    tags: ["amande", "beurre noisette", "moelleux", "petit gateau"],
    parfum_principal: "amande",
    note_concepteur: "La clé est la qualité du beurre noisette : il doit être ambré mais non brûlé. Un beurre noisette trop pâle manque d'arôme.",
    source_interne: {
      fichier_pdf: null,
      page: null,
      nom_original: "Biscuit de test — recette générique",
      chef: null,
      date_extraction: "2026-05-18",
    },
  },
];
