export const RECETTES_BISCUITS = [
  {
    id: "biscuit-joconde-01",
    nom: "Biscuit Joconde",
    categorie: "biscuits",
    sous_categorie: "biscuit_leger",
    description: "Biscuit léger aux amandes, fin et souple, support classique d'entremets. Cuit en feuille.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Poudre d'amande",  g: 250, pct: 25, role: "parfum"    },
      { nom: "Sucre glace",      g: 250, pct: 25, role: "sucrant"   },
      { nom: "Œufs entiers",     g: 300, pct: 30, role: "liant"     },
      { nom: "Farine T45",       g:  50, pct:  5, role: "structure" },
      { nom: "Blancs d'œufs",   g: 120, pct: 12, role: "aeration"  },
      { nom: "Sucre semoule",    g:  30, pct:  3, role: "sucrant"   },
    ],
    procede: [
      "Monter les œufs entiers avec la poudre d'amande et le sucre glace au batteur jusqu'au ruban.",
      "Incorporer la farine tamisée à la maryse.",
      "Monter les blancs en neige souple, serrer avec le sucre semoule.",
      "Incorporer délicatement la meringue à l'appareil amande en deux fois.",
      "Étaler 700 g sur plaque 40×60 chemisée. Cuire immédiatement.",
      "Four à 230 °C chaleur tournante, 5–6 min. Le biscuit doit rester souple.",
      "Retourner sur papier sulfurisé à la sortie du four, décoller le papier de cuisson.",
    ],
    cuisson: { temperature_c: 230, duree_min: 6, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf", "fruits_a_coque"],
    tags: ["amande", "entremets", "support", "leger"],
    parfum_principal: "amande",
    note_concepteur: "Ne pas trop cuire : un biscuit trop sec se craquelera au roulage. Le retournement à chaud est essentiel pour le décoller proprement.",
    source_interne: {
      fichier_pdf: null,
      page: null,
      nom_original: "Biscuit de test — recette générique",
      chef: null,
      date_extraction: "2026-05-18",
    },
  },

  {
    id: "dacquoise-noisette-01",
    nom: "Dacquoise noisette",
    categorie: "biscuits",
    sous_categorie: "biscuit_meringue",
    description: "Biscuit meringué à la noisette, croustillant en surface et moelleux à cœur. Sans gluten.",
    masse_totale_g: 800,
    ingredients: [
      { nom: "Blancs d'œufs",       g: 300, pct: 37.5, role: "aeration"  },
      { nom: "Sucre glace",          g: 200, pct: 25,   role: "sucrant"   },
      { nom: "Poudre de noisette",   g: 280, pct: 35,   role: "parfum"    },
      { nom: "Fécule de maïs",       g:  20, pct:  2.5, role: "structure" },
    ],
    procede: [
      "Torréfier la poudre de noisette 10 min à 150 °C, refroidir.",
      "Monter les blancs en neige souple. Incorporer le sucre glace tamisé en 3 fois pour obtenir une meringue ferme.",
      "Mélanger poudre de noisette et fécule. Incorporer à la meringue par mouvements enveloppants.",
      "Dresser à la poche en disques ou étaler en feuille à 5 mm.",
      "Saupoudrer légèrement de sucre glace.",
      "Cuire à 170 °C chaleur tournante, 18 min. La surface doit résister légèrement à la pression.",
      "Refroidir sur grille avant de décoller.",
    ],
    cuisson: { temperature_c: 170, duree_min: 18, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["oeuf", "fruits_a_coque"],
    tags: ["noisette", "meringue", "sans gluten", "entremets", "support"],
    parfum_principal: "noisette",
    note_concepteur: "La torréfaction de la poudre de noisette est indispensable pour développer les arômes. La dacquoise se conserve très bien congelée.",
    source_interne: {
      fichier_pdf: null,
      page: null,
      nom_original: "Biscuit de test — recette générique",
      chef: null,
      date_extraction: "2026-05-18",
    },
  },

  {
    id: "financier-amande-01",
    nom: "Financier amande",
    categorie: "biscuits",
    sous_categorie: "petit_gateau",
    description: "Petit gâteau moelleux au beurre noisette et à la poudre d'amande. Bords caramélisés, cœur fondant.",
    masse_totale_g: 500,
    ingredients: [
      { nom: "Beurre noisette",  g: 175, pct: 35, role: "mg"        },
      { nom: "Poudre d'amande", g: 110, pct: 22, role: "parfum"    },
      { nom: "Sucre glace",      g: 125, pct: 25, role: "sucrant"   },
      { nom: "Farine T55",       g:  40, pct:  8, role: "structure" },
      { nom: "Blancs d'œufs",   g:  50, pct: 10, role: "liant"     },
    ],
    procede: [
      "Cuire le beurre à feu moyen jusqu'à coloration noisette et odeur de noix torréfiées. Passer au chinois, refroidir à 40 °C.",
      "Tamiser ensemble poudre d'amande, sucre glace et farine.",
      "Incorporer les blancs d'œufs liquides (non montés) au mélange sec.",
      "Ajouter le beurre noisette tiède en filet. Mélanger jusqu'à pâte lisse.",
      "Laisser reposer 30 min au réfrigérateur (optionnel, améliore la tenue).",
      "Remplir des moules à financier beurrés aux ¾.",
      "Cuire à 200 °C chaleur tournante, 8 min (moules mini). Démouler tiède.",
    ],
    cuisson: { temperature_c: 200, duree_min: 8, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf", "lactose", "fruits_a_coque"],
    tags: ["amande", "beurre noisette", "moelleux", "petit gateau"],
    parfum_principal: "amande",
    note_concepteur: "La clé est la qualité du beurre noisette : il doit être ambré mais non brûlé. Un beurre noisette trop pâle manque d'arôme.",
    source_interne: {
      fichier_pdf: null,
      page: null,
      nom_original: "Biscuit de test — recette générique",
      chef: null,
      date_extraction: "2026-05-18",
    },
  },

  {
    id: "biscuit-entremets-chocolat",
    nom: "Biscuit entremets chocolat",
    categorie: "biscuits",
    sous_categorie: "biscuit_entremets",
    description: "Biscuit chocolat moelleux cuit en cadre, structure légère et homogène. Adapté à la découpe en couches pour montages.",
    masse_totale_g: 502,
    ingredients: [
      { nom: "Œuf entier",               g: 125,  pct: 25,  role: "liant"     },
      { nom: "Farine T45",               g: 60,   pct: 12,  role: "structure" },
      { nom: "Levure chimique",          g: 2.5,  pct: 0.5, role: "structure" },
      { nom: "Sucre semoule",            g: 74,   pct: 15,  role: "sucrant"   },
      { nom: "Sucre inverti",            g: 12,   pct: 2,   role: "sucrant"   },
      { nom: "Huile de pépins de raisin",g: 76,   pct: 15,  role: "mg"        },
      { nom: "Sel",                      g: 1,    pct: 0.5, role: "exhausteur"},
      { nom: "Chocolat 58%",             g: 151,  pct: 30,  role: "parfum"    },
    ],
    procede: [
      "Fondre le chocolat et l'huile à 45°C.",
      "Ajouter le mélange œufs, sucre semoule, sucre inverti et sel.",
      "Terminer avec la farine et la levure chimique tamisées.",
      "Verser dans un cadre de 20×20 cm. Cuire 10-12 min à 170°C en four ventilé.",
    ],
    cuisson: { temperature_c: 170, duree_min: 11, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf"],
    tags: ["biscuit", "chocolat", "entremets", "moelleux", "cadre"],
    parfum_principal: "chocolat",
    note_concepteur: "Pour plus de moelleux, privilégier une cuisson et un refroidissement rapide. La farine T45 peut être remplacée par un mix sans gluten (riz complet 40% / fécule de pomme de terre 30% / amidon de maïs 30%).",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 46,
      chef: null,
    },
  },

  {
    id: "mi-cuit-chocolat",
    nom: "Mi-cuit chocolat",
    categorie: "biscuits",
    sous_categorie: "mi_cuit",
    description: "Gâteau individuel au cœur coulant, à servir immédiatement à la sortie du four. Meringue incorporée pour une texture aérée.",
    masse_totale_g: 255,
    ingredients: [
      { nom: "Beurre doux",              g: 25,   pct: 10, role: "mg"        },
      { nom: "Blanc d'œuf pasteurisé",  g: 75,   pct: 29, role: "aeration"  },
      { nom: "Jaune d'œuf pasteurisé",  g: 18,   pct: 7,  role: "liant"     },
      { nom: "Sucre semoule",            g: 20,   pct: 8,  role: "sucrant"   },
      { nom: "Amidon de maïs",           g: 12.5, pct: 5,  role: "structure" },
      { nom: "Chocolat 58%",             g: 105,  pct: 41, role: "parfum"    },
    ],
    procede: [
      "Dans une cuve de batteur, monter les blancs en neige en incorporant progressivement le sucre.",
      "Fondre le chocolat et le beurre à 50°C, ajouter les jaunes d'œufs et l'amidon de maïs.",
      "Incorporer délicatement la meringue à l'appareil chocolat.",
      "Mettre en poche, garnir des cercles ou moules chemisés de papier sulfurisé.",
      "Cuire environ 5-6 min à 185°C. Démouler après quelques minutes, servir aussitôt.",
    ],
    cuisson: { temperature_c: 185, duree_min: 6, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["mi-cuit", "coulant", "chocolat", "dessert chaud", "pièce individuelle"],
    parfum_principal: "chocolat",
    note_concepteur: "Pour un cœur bien coulant, laisser reposer à 4°C avant cuisson. La cuisson doit être ajustée en fonction du four et de la taille du mi-cuit.",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 47,
      chef: null,
    },
  },

  {
    id: "biscuit-pate-a-choux-chocolat",
    nom: "Biscuit pâte à choux chocolat",
    categorie: "biscuits",
    sous_categorie: "biscuit_pate_a_choux",
    description: "Biscuit moelleux et flexible sur base pâte à choux, aéré à la meringue. Idéal pour bûches roulées et décors.",
    masse_totale_g: 743,
    ingredients: [
      { nom: "Beurre doux",               g: 60,  pct: 8,  role: "mg"        },
      { nom: "Lait UHT entier",            g: 67,  pct: 9,  role: "eau"       },
      { nom: "Sucre inverti",              g: 37,  pct: 5,  role: "sucrant"   },
      { nom: "Farine T45",                 g: 75,  pct: 10, role: "structure" },
      { nom: "Œuf entier",                 g: 75,  pct: 10, role: "liant"     },
      { nom: "Jaune d'œuf pasteurisé",    g: 127, pct: 17, role: "liant"     },
      { nom: "Sucre semoule",              g: 90,  pct: 12, role: "sucrant"   },
      { nom: "Blanc d'œuf pasteurisé",    g: 187, pct: 25, role: "aeration"  },
      { nom: "Poudre de cacao",            g: 25,  pct: 4,  role: "parfum"    },
    ],
    procede: [
      "Dans une casserole, faire bouillir le lait, le beurre et le sucre inverti.",
      "Hors du feu, ajouter la poudre de cacao et la farine tamisée, mélanger jusqu'à pâte lisse.",
      "Laisser refroidir à 45-50°C, puis ajouter progressivement les œufs entiers.",
      "Dans une cuve, monter les blancs à vitesse moyenne en serrant avec le sucre semoule (meringue ferme mais pas trop).",
      "Dans une autre cuve, monter les jaunes au ruban.",
      "Incorporer délicatement la meringue à l'appareil puis les jaunes montés.",
      "Étaler sur plaque avec tapis siliconé. Cuire 10-12 min à 170°C.",
      "Faire glisser sur grille dès la sortie du four. Retourner et retirer délicatement le tapis.",
    ],
    cuisson: { temperature_c: 170, duree_min: 11, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf", "gluten"],
    tags: ["biscuit", "pâte à choux", "chocolat", "roulé", "décoration", "flexible"],
    parfum_principal: "chocolat",
    note_concepteur: "Ce biscuit très moelleux et flexible est idéal en décoration ou pour réaliser des bûches roulées. La farine T45 peut être remplacée par un mix sans gluten (riz complet 40% / fécule de pomme de terre 30% / amidon de maïs 30%).",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 48,
      chef: null,
    },
  },
];
