export const RECETTES_BOISSONS = [
  {
    id: "chocolat-chaud-noir",
    nom: "Chocolat chaud",
    categorie: "boissons",
    sous_categorie: "chocolat_chaud",
    description: "Chocolat chaud émulsionné, texture lisse et brillante. Simple et puissant, à servir à 65°C.",
    masse_totale_g: 1237,
    ingredients: [
      { nom: "Lait UHT entier",   g: 1000, pct: 81,   role: "eau"       },
      { nom: "Amidon de maïs",    g: 7,    pct: 0.5,  role: "structure" },
      { nom: "Chocolat noir 67%", g: 230,  pct: 18.5, role: "parfum"    },
    ],
    procede: [
      "Dans une casserole, mélanger le lait et l'amidon.",
      "Porter à ébullition.",
      "Verser sur le chocolat, émulsionner au mixeur plongeant.",
      "Réchauffer si nécessaire à 65°C. Servir aussitôt ou stocker en chocolatière.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 65, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["chocolat chaud", "boisson", "chocolat noir", "service"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Pour une texture plus onctueuse : ajouter de l'amidon de maïs (0,5%), de la gomme de caroube ou de guar (0,1%).",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 56,
      chef: null,
    },
  },

  // === Import extraction-2026-08-12 (9 recettes) ===
  {
    id: "chocolat-chaud1",
    nom: "Chocolat chaud1",
    categorie: "boissons",
    sous_categorie: "chocolat_chaud",
    description: "Chocolat chaud1 — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Couverture Ashanti", g: 173.8, pct: 17.4, role: "parfum" },
      { nom: "Lait", g: 826.2, pct: 82.6, role: "eau" },
    ],
    procede: [
      "Faire bouillir le lait ,",
      "Incorporer la couverture puis laisser bouillir pendant 5 mn.",
      "Mixer à la girafe.",
      "Débarasser dans des seaux de 5kg.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait"],
    tags: ["chocolat chaud", "Chocolat chaud mad bar"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Chocolat chaud 1.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "milk-shake-framboise",
    nom: "Milk-shake framboise",
    categorie: "boissons",
    sous_categorie: "boisson",
    description: "Milk-shake framboise — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Lait", g: 206.8, pct: 20.7, role: "eau" },
      { nom: "Crème", g: 206.8, pct: 20.7, role: "eau" },
      { nom: "Purée de framboise", g: 486.6, pct: 48.7, role: "eau" },
      { nom: "Gourmandise framboise", g: 9.7, pct: 1.0, role: "parfum" },
      { nom: "sucre", g: 90.0, pct: 9.0, role: "sucrant" },
    ],
    procede: [
      "Mixer le tout.",
      "Servir très frais.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait"],
    tags: ["boisson", "framboise", "Dessert à l'assiette 1000F framboise fromage blanc"],
    parfum_principal: "framboise",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Milk shake framboise.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "jus-ananas-rhum-blanc",
    nom: "Jus Ananas rhum blanc",
    categorie: "boissons",
    sous_categorie: "jus",
    description: "Jus Ananas rhum blanc — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Jus ananas Caraibos", g: 803.9, pct: 80.4, role: "eau" },
      { nom: "Rhum blanc", g: 196.1, pct: 19.6, role: "parfum" },
    ],
    procede: [
      "Mélanger les deux ingrédients.",
      "Mettre en pipettes.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["jus", "Babacolada"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Jus ananas rhum blanc.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "jus-fraise-rhum",
    nom: "Jus fraise rhum",
    categorie: "boissons",
    sous_categorie: "jus",
    description: "Jus fraise rhum — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Jus caraïbos fraise", g: 396.8, pct: 39.7, role: "eau" },
      { nom: "Rhum blanc", g: 396.8, pct: 39.7, role: "parfum" },
      { nom: "Gourmandise fraise", g: 206.3, pct: 20.6, role: "parfum" },
    ],
    procede: [
      "Mélanger le tout ensemble.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["jus", "fraise", "Pipette à baba fraise"],
    parfum_principal: "fraise",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Jus fraise rhum.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "jus-orange-jasmin",
    nom: "Jus orange-jasmin",
    categorie: "boissons",
    sous_categorie: "jus",
    description: "Jus orange-jasmin — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Jus d'orange", g: 666.4, pct: 66.6, role: "eau" },
      { nom: "Arôme jasmin", g: 0.3, pct: 0.0, role: "parfum" },
      { nom: "Sirop à 30°", g: 333.2, pct: 33.3, role: "sucrant" },
    ],
    procede: [
      "Mélanger le jus d'orange, le sirop à 30° et l'arôme jasmin",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["jus", "Carré fruits orange jasmin"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Jus orange-jasmin.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "jus-passion-vanille",
    nom: "Jus passion vanille",
    categorie: "boissons",
    sous_categorie: "jus",
    description: "Jus passion vanille — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Purée passion", g: 617.3, pct: 61.7, role: "eau" },
      { nom: "Sirop à 30°", g: 370.4, pct: 37.0, role: "sucrant" },
      { nom: "Vanille gousse", g: 12.4, pct: 1.2, role: "parfum" },
    ],
    procede: [
      "Infuser la vanille dans le sirop à 30° pendant 10 minutes.",
      "Ajouter la purée de passion.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["jus", "vanille", "Carré fruits passion pistache"],
    parfum_principal: "vanille",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Jus vanille passion.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "mousse-chocolat-framboise-cocktail",
    nom: "Mousse chocolat framboise cocktail",
    categorie: "boissons",
    sous_categorie: "boisson",
    description: "Mousse chocolat framboise cocktail — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Chocolat ashanti", g: 249.1, pct: 24.9, role: "parfum" },
      { nom: "Gélatine", g: 3.7, pct: 0.4, role: "gelifiant" },
      { nom: "Crème", g: 373.6, pct: 37.4, role: "eau" },
      { nom: "Purée de framboise", g: 211.7, pct: 21.2, role: "eau" },
      { nom: "Lait", g: 161.9, pct: 16.2, role: "eau" },
    ],
    procede: [
      "Tremper la gélatine pendant 20min dans l'eau froide.",
      "Faire chauffer le lait + la purée de framboise.",
      "Ajouter la gélatine (égoutter) puis verser sur la couverture.",
      "Faire une ganache.",
      "Verser celle-ci à 42-43°C sur la crème fouettée.",
      "Surgeler.",
      "Verre bodega: 0,080gr",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait"],
    tags: ["boisson", "framboise", "Verres cocktail"],
    parfum_principal: "framboise",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Mousse chocolat framboise cocktail.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "mousse-framboisine-cocktail",
    nom: "Mousse framboisine cocktail",
    categorie: "boissons",
    sous_categorie: "boisson",
    description: "Mousse framboisine cocktail — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Poudre d'amande", g: 192.3, pct: 19.2, role: "structure" },
      { nom: "Sucre cristal 1", g: 192.3, pct: 19.2, role: "sucrant" },
      { nom: "Farine 45", g: 51.3, pct: 5.1, role: "structure" },
      { nom: "Blanc d'œuf", g: 307.7, pct: 30.8, role: "aeration" },
      { nom: "Sucre cristal 2", g: 256.4, pct: 25.6, role: "sucrant" },
    ],
    procede: [
      "Tamiser la poudre d'amande ,le sucre 1 et la farine.",
      "Monter les blancs et incorporer le sucre2 en 2 fois.",
      "Ajouter les poudres sur les blancs et mélanger délicatement.",
      "Cadres 38x58 à 0,650gr",
      "3 biscuits par cadre",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["fruits_a_coque", "gluten", "oeuf"],
    tags: ["boisson", "amande", "Framboisine"],
    parfum_principal: "amande",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Mousse framboisine cocktail.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "jus-de-fraise",
    nom: "Jus de fraise",
    categorie: "boissons",
    sous_categorie: "jus",
    description: "Jus de fraise — recette importée, à vérifier.",
    masse_totale_g: 220,
    ingredients: [
      { nom: "fraise", g: 200.0, pct: 90.9, role: "parfum" },
      { nom: "sucre glace", g: 20.0, pct: 9.1, role: "sucrant" },
    ],
    procede: [
      "Bouillir l’eau, le sucre, laisser refroidir et ajouter la fleur d’oranger, réserver au frais",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["jus", "fraise"],
    parfum_principal: "fraise",
    note_concepteur: "",
    source_interne: { fichier: "Tarte rhubarbe.docx", import: "extraction-2026-08-12" },
  },
];
