const _SRC_LN1  = "Chocolats et сonfiserie de l ecole Lenotre T1.pdf";
const _CHEF_LN1 = "François Legras & Stéphane Glacier";

const _SRC_LN2  = "Chocolats et сonfiserie de l ecole Lenotre T2.pdf";
const _CHEF_LN2 = "François Legras & Stéphane Glacier";

export const RECETTES_BONBONS = [

  /* ── École Lenôtre T1 — Confiseries chocolat ────────────────────────── */

  {
    id: "cote-dor-ln1",
    nom: "Le Côte-d'or — fondant cassis-cerise",
    categorie: "bonbons",
    sous_categorie: "bonbon_moule",
    description: "Bonbon moulé : coques chocolat noir garnies d'un fondant cassis-crème de cassis, avec cerises à l'alcool au fond. Croûte à l'air 10 heures, enrobage noir 66 %.",
    masse_totale_g: 750,
    ingredients: [
      { nom: "Fondant au cassis",          g: 500, pct: 67, role: "sucrant" },
      { nom: "Grains de cassis à l'alcool",g: 180, pct: 24, role: "fruit"   },
      { nom: "Crème de cassis",            g:  70, pct:  9, role: "parfum"  },
    ],
    procede: [
      "Faire chauffer le fondant au cassis et la crème de cassis à 32 °C.",
      "Déposer éventuellement quelques grains de cassis dans le fond des coques en chocolat noir.",
      "Couler le fondant jusqu'aux 3/4 des coques. Laisser croûter 10 heures à l'air.",
      "Enrober de couverture noir 66 %. Déposer une plaquette de chocolat coloré découpée.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson — fondant 32 °C" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["bonbon", "cassis", "fondant", "moulé", "liqueur", "confiserie"],
    parfum_principal: "cassis",
    note_concepteur: "Le fondant au cassis doit être tempéré à 32 °C max pour ne pas recristalliser brutalement. La formation d'une croûte (10 heures à l'air) avant obturation est indispensable pour éviter que le chocolat d'enrobage ne dissolve le fondant.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 75, chef: _CHEF_LN1 },
  },

  {
    id: "martinique-ln1",
    nom: "Le Martinique — nougat tendre & ganache rhum",
    categorie: "bonbons",
    sous_categorie: "bonbon_cadre",
    description: "Bonbon deux couches : nougat tendre miel-ananas (3 mm) surmonté d'une ganache chocolat au rhum agricole (6 mm). Cadre guitare 22,5 × 22,5 mm, enrobé noir 66 %.",
    masse_totale_g: 1895,
    ingredients: [
      { nom: "Chocolat ganache 50 %",       g: 500, pct: 27, role: "parfum"  },
      { nom: "Miel",                         g: 300, pct: 16, role: "sucrant" },
      { nom: "Crème liquide 35 % (ganache)", g: 250, pct: 13, role: "mg"      },
      { nom: "Couverture lait 36 %",         g: 250, pct: 13, role: "parfum"  },
      { nom: "Crème fleurette (nougat)",     g: 200, pct: 11, role: "mg"      },
      { nom: "Ananas confits hachés séchés", g: 160, pct:  8, role: "fruit"   },
      { nom: "Rhum agricole 45°",            g:  80, pct:  4, role: "parfum"  },
      { nom: "Amandes effilées",             g:  80, pct:  4, role: "parfum"  },
      { nom: "Glucose",                      g:  75, pct:  4, role: "sucrant" },
    ],
    procede: [
      "Nougat : cuire miel, crème fleurette et glucose à 130 °C. Ajouter amandes et ananas hachés séchés. Étaler immédiatement en cadre 3 mm. Refroidir.",
      "Ganache : faire bouillir la crème. Verser sur les couvertures finement hachées. Refroidir à 35 °C. Ajouter le rhum.",
      "Disposer un cadre 6 mm sur le nougat froid. Y couler la ganache. Laisser cristalliser 10 heures.",
      "Chablonner les deux faces. Dès cristallisation, détailler à la guitare 22,5 × 22,5 mm.",
      "Enrober couverture noir 66 %. Décorer de 3 traits de fourchette.",
    ],
    cuisson: { temperature_c: 130, duree_min: null, mode: "casserole — nougat 130 °C + cadre confiserie" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "fruits_a_coque_amande"],
    tags: ["bonbon", "nougat tendre", "rhum", "ananas", "cadre guitare", "deux couches", "confiserie"],
    parfum_principal: "chocolat noir",
    note_concepteur: "L'ananas confit doit être haché puis séché avant incorporation au nougat — l'humidité résiduelle ramollirait la texture. Le rhum agricole (45°) s'incorpore à la ganache à 35 °C uniquement, jamais sur le feu.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 77, chef: _CHEF_LN1 },
  },

  {
    id: "buchette-agrumes-ln1",
    nom: "La Bûchette aux agrumes",
    categorie: "bonbons",
    sous_categorie: "bonbon_praline",
    description: "Bûchette praliné noisette-couverture lait parfumée citron et orange confits. Dressée en cylindres (douille n°8), saupoudrée de pralinettes, pistolet à 32 °C, détaillée à 3 cm. Enrobée noir 66 %.",
    masse_totale_g: 1510,
    ingredients: [
      { nom: "Praliné noisette",          g: 1000, pct: 66, role: "parfum"  },
      { nom: "Couverture lait 36 %",      g:  400, pct: 27, role: "parfum"  },
      { nom: "Pralinettes",               g:   50, pct:  3, role: "texture" },
      { nom: "Arôme naturel citron",      g:   20, pct:  2, role: "parfum"  },
      { nom: "Zeste citron confit haché", g:   20, pct:  1, role: "parfum"  },
      { nom: "Zeste orange confit haché", g:   20, pct:  1, role: "parfum"  },
    ],
    procede: [
      "Mélanger le praliné noisette et la couverture lait fondue. Ajouter l'arôme citron et les zestes confits hachés.",
      "Chauffer à 45 °C, tabler sur marbre à 30 °C.",
      "À la poche et douille unie n°8, dresser des cylindres sur papier cuisson. Parsemer de pralinettes.",
      "Pulvériser au pistolet (appareil couverture 66 %) à 32 °C pour l'aspect velours. Laisser cristalliser 5 heures.",
      "Détailler en bûchettes de 3 cm. Enrober de couverture noir 66 %.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson — tablage + pistolet" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "fruits_a_coque_noisette"],
    tags: ["bûchette", "praliné", "noisette", "agrumes", "citron", "orange", "confiserie", "pistolet"],
    parfum_principal: "noisette",
    note_concepteur: "Les zestes confits doivent être finement hachés (< 3 mm) pour ne pas perturber l'homogénéité du dressage à la poche. La phase de tablage à 30 °C est indispensable pour que le praliné soit à point avant dressage.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 79, chef: _CHEF_LN1 },
  },

  {
    id: "cerises-kirsch-ln1",
    nom: "Les Cerises au kirsch",
    categorie: "bonbons",
    sous_categorie: "bonbon_moule",
    description: "Bonbon moulé classique : griotte à l'alcool dans une coque chocolat noir, garnie de fondant pâtissier au kirsch. Obturation double, démoulage 24 heures pour brillant parfait.",
    masse_totale_g: 1550,
    ingredients: [
      { nom: "Griottes à l'alcool (égouttées)", g: 1000, pct: 64, role: "fruit"   },
      { nom: "Fondant pâtissier",               g:  500, pct: 33, role: "sucrant" },
      { nom: "Kirsch à 60°",                    g:   50, pct:  3, role: "parfum"  },
    ],
    procede: [
      "Chemiser les moules polycarbonate de couverture noir 66 % tempérée. Ébarber, laisser cristalliser.",
      "Déposer une griotte bien égouttée dans chaque alvéole.",
      "Détendre le fondant avec le kirsch. Tempérer sans dépasser 31 °C. Garnir les moules à 2 mm du bord.",
      "Laisser croûter 10 heures à l'air. Obturer une première fois au pistolet à chocolat. Cristalliser, ébarber.",
      "Obturer une seconde fois à la couverture noir 66 %. Laisser cristalliser. Démouler 24 heures après pour beau brillant.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson — moulage chocolat" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["cerise", "kirsch", "bonbon moulé", "fondant", "polycarbonate", "confiserie", "liqueur"],
    parfum_principal: "cerise",
    note_concepteur: "Les griottes doivent être parfaitement égouttées — l'alcool résiduel dissoudrait le fondant. Le fondant ne doit pas dépasser 31 °C lors du tempérage pour éviter la liquéfaction prématurée. L'obturation double garantit l'étanchéité sans que le kirsch ne migre dans la coque.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 80, chef: _CHEF_LN1 },
  },

  {
    id: "mendiant-ln1",
    nom: "Le Mendiant",
    categorie: "bonbons",
    sous_categorie: "mendiant",
    description: "Disque de couverture noir 66 % garni avant cristallisation d'une pistache, une noisette, un cube d'orange confite et un cube d'ananas confit. Moulé en Flexipan® 2 cm.",
    masse_totale_g: 700,
    ingredients: [
      { nom: "Couverture noir 66 %",      g: 200, pct: 29, role: "parfum"  },
      { nom: "Orange confite (cubes)",    g: 150, pct: 21, role: "fruit"   },
      { nom: "Ananas confit (cubes)",     g: 150, pct: 21, role: "fruit"   },
      { nom: "Pistaches vernies",         g: 100, pct: 14, role: "parfum"  },
      { nom: "Noisettes caramélisées",    g: 100, pct: 15, role: "parfum"  },
    ],
    procede: [
      "Tempérer la couverture noir 66 %. Garnir le fond des moules Flexipan® ronds (Ø 2 cm) ou polycarbonate.",
      "Avant cristallisation, disposer sur chaque disque : 1 pistache vernie, 1 noisette caramélisée, 1 cube d'orange et 1 cube d'ananas.",
      "Laisser cristalliser 2 heures. Démouler délicatement.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson — moulage tempérage" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "fruits_a_coque_noisette", "fruits_a_coque_pistache"],
    tags: ["mendiant", "chocolat noir", "pistache", "noisette", "orange confite", "ananas confit", "confiserie"],
    parfum_principal: null,
    note_concepteur: "Les pistaches sont vernies à la gomme arabique (recette p. 51) avant utilisation pour préserver leur couleur et éviter le verdissement. L'ordre de disposition sur le disque suit la tradition mendiant : les 4 fruits représentent les 4 ordres mendiants.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 81, chef: _CHEF_LN1 },
  },

  {
    id: "chardon-grand-marnier-ln1",
    nom: "Le Chardon Grand Marnier",
    categorie: "bonbons",
    sous_categorie: "bonbon_praline",
    description: "Pâte d'amandes orange enrobant une perle de liqueur Grand Marnier, roulée en boule puis trempée couverture noir 66 % et roulée sur crible pour l'aspect « chardon ». Technique Lenôtre.",
    masse_totale_g: 1175,
    ingredients: [
      { nom: "Pâte d'amandes (60 %)",          g: 1000, pct: 85, role: "parfum"  },
      { nom: "Perles de liqueur Grand Marnier", g:  150, pct: 13, role: "parfum"  },
      { nom: "Arôme naturel orange",            g:   20, pct:  2, role: "parfum"  },
      { nom: "Colorant alimentaire orange",     g:    5, pct:  0, role: "parfum"  },
    ],
    procede: [
      "Parfumer la pâte d'amandes avec l'arôme orange. Colorer en orange pastel.",
      "Abaisser à 4 mm. Détailler des carrés de 30 mm à la guitare.",
      "Enrober chaque perle de liqueur Grand Marnier d'un carré de pâte d'amandes. Bouler correctement.",
      "Enrober de couverture noir 66 % tempérée.",
      "Rouler aussitôt sur crible ou grille d'enrobeuse pour obtenir l'aspect chardon irrégulier.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson — assemblage" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "fruits_a_coque_amande"],
    tags: ["chardon", "Grand Marnier", "pâte d'amandes", "liqueur", "bonbon", "confiserie"],
    parfum_principal: "orange",
    note_concepteur: "Les perles de liqueur Grand Marnier sont coulées en coffret amidon (recette tome 2 p. 104). Le boulage doit être parfait pour éviter que la liqueur ne percole à travers la pâte d'amandes pendant la cristallisation. Le passage sur crible doit être immédiat après trempage.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 82, chef: _CHEF_LN1 },
  },

  {
    id: "quatre-freres-ln1",
    nom: "Les Quatre frères",
    categorie: "bonbons",
    sous_categorie: "rocher",
    description: "Quatre noisettes caramélisées assemblées en pyramide, collées au chocolat noir, montées sur pastille, pistolet velours à 32 °C, enrobées noir 66 %. Confiserie de prestige Lenôtre.",
    masse_totale_g: 1090,
    ingredients: [
      { nom: "Noisettes grillées",    g: 600, pct: 56, role: "parfum"  },
      { nom: "Sucre semoule",         g: 220, pct: 20, role: "sucrant" },
      { nom: "Couverture noir 66 %",  g: 200, pct: 18, role: "parfum"  },
      { nom: "Eau",                   g:  70, pct:  6, role: "eau"     },
    ],
    procede: [
      "Cuire le sucre, l'eau et la vanille grattée à 115 °C. Y ajouter les noisettes.",
      "Sablage, puis caramélisation sur feu doux. Séparer les noisettes sur feuille Exopat®. Refroidir.",
      "Assembler 4 noisettes en pyramide, collées avec un point de couverture noir 66 % tempérée.",
      "Réaliser des pastilles (chablon rond Ø 2,5 cm) de couverture noir. Coller les pyramides sur les pastilles.",
      "Pulvériser au pistolet (appareil noir) à 32 °C pour protéger de l'humidité.",
      "Enrober de couverture noir 66 % tempérée.",
    ],
    cuisson: { temperature_c: 115, duree_min: null, mode: "casserole — sirop 115 °C puis caramélisation" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "fruits_a_coque_noisette"],
    tags: ["rocher", "noisettes", "pyramide", "caramel", "confiserie", "pistolet", "prestige"],
    parfum_principal: "noisette",
    note_concepteur: "1 gousse de vanille (non incluse). La phase pistolet avant enrobage final protège les pyramides de l'humidité — sans elle, les noisettes caramélisées deviendraient collantes. L'enrobage final doit se faire à la fourchette pour préserver la forme pyramidale.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 83, chef: _CHEF_LN1 },
  },

  {
    id: "othelo-ln1",
    nom: "L'Othelo",
    categorie: "bonbons",
    sous_categorie: "bonbon_praline",
    description: "Bonbon duja-moka dressé à la douille cannelée en forme ovale, couronné d'une amande chocolatée. Base trempée dans la couverture noir 66 % en ne couvrant pas l'amande. Finition nette et contrastée.",
    masse_totale_g: 560,
    ingredients: [
      { nom: "Duja noisettes-amandes", g: 250, pct: 45, role: "parfum"  },
      { nom: "Couverture lait 36 %",   g: 250, pct: 45, role: "parfum"  },
      { nom: "Amandes chocolatées",    g:  50, pct:  9, role: "parfum"  },
      { nom: "Pâte moka",              g:  10, pct:  1, role: "parfum"  },
    ],
    procede: [
      "Chauffer le duja, la couverture lait 36 % et la pâte moka à 40 °C. Tabler sur marbre à 30 °C.",
      "À la poche avec douille cannelée, dresser des bonbons ovales sur papier cuisson.",
      "Poser une amande chocolatée sur chacun. Laisser cristalliser 10 heures.",
      "Tremper la base dans la couverture noir 66 % tempérée — ne pas couvrir l'amande.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson — tablage" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "fruits_a_coque_noisette", "fruits_a_coque_amande"],
    tags: ["duja", "café", "moka", "bonbon praline", "amande chocolatée", "confiserie", "ovale"],
    parfum_principal: "café",
    note_concepteur: "Le tablage à 30 °C est critique pour le duja — trop chaud et la pâte coule, trop froid et le dressage est impossible. La pâte moka (10 g seulement) parfume subtilement sans dominer. Le trempage de la base uniquement crée le contraste visuel caractéristique de l'Othelo.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 84, chef: _CHEF_LN1 },
  },

  {
    id: "aphrodite-ln1",
    nom: "L'Aphrodite",
    categorie: "bonbons",
    sous_categorie: "rocher",
    description: "Rocher confiserie : amandes bâtonnets caramélisées, pistaches vertes et raisins cognac enrobés de couverture noir 66 %. Dressé en forme irrégulière à la cuillère ou en moule Flexipan®.",
    masse_totale_g: 1050,
    ingredients: [
      { nom: "Amandes bâtonnets caramélisées", g: 500, pct: 47, role: "parfum"  },
      { nom: "Couverture noir 66 %",           g: 350, pct: 33, role: "parfum"  },
      { nom: "Pistaches vertes",               g: 100, pct: 10, role: "parfum"  },
      { nom: "Raisins blonds macérés au cognac",g: 100, pct: 10, role: "fruit"   },
    ],
    procede: [
      "Tempérer les amandes bâtonnets caramélisées à 30 °C. Égoutter soigneusement les raisins.",
      "Ajouter pistaches, raisins égouttés et couverture noir 66 % à point. Bien mélanger.",
      "Dresser en forme de rocher à la cuillère sur feuille guitare ou dans des moules Flexipan® pour plus de régularité.",
      "Laisser cristalliser complètement avant de démouler ou décrocher.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson — tablage" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "fruits_a_coque_amande", "fruits_a_coque_pistache"],
    tags: ["rocher", "amandes", "pistaches", "cognac", "raisins", "chocolat noir", "confiserie"],
    parfum_principal: "amande",
    note_concepteur: "Les raisins macérés au cognac doivent être parfaitement égouttés — l'alcool résiduel empêcherait la cristallisation du chocolat. Tempérer les amandes caramélisées séparément avant de les incorporer au chocolat pour éviter une montée en température brutale.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 85, chef: _CHEF_LN1 },
  },


  /* ── École Lenôtre T2 — Batch 1 : ganaches tablettes & cadre ────────── */

  {
    id: "tablette-noix-coco-ln2",
    nom: "La Tablette noix de coco",
    categorie: "bonbons",
    sous_categorie: "bonbon_moule",
    description: "Tablette moulée : ganache chocolat ivoire au lait de coco et Malibu, coulée dans des moules à tablettes chemisés ivoire. Cristallisation 5 h à l'air, obturation ivoire, démoulage 24 h.",
    masse_totale_g: 1020,
    ingredients: [
      { nom: "Couverture ivoire",   g: 600, pct: 59, role: "parfum"  },
      { nom: "Lait de coco",        g: 280, pct: 27, role: "mg"      },
      { nom: "Lait concentré",      g: 120, pct: 12, role: "mg"      },
      { nom: "Malibu",              g:  20, pct:  2, role: "parfum"  },
    ],
    procede: [
      "Faire bouillir le lait concentré et le lait de coco.",
      "Verser sur la couverture ivoire finement hachée. Ajouter la vanille grattée et le Malibu.",
      "Laisser refroidir la ganache à 28 °C.",
      "Chemiser des moules à tablettes de couverture ivoire tempérée.",
      "Couler la ganache dans les moules chemisés. Laisser cristalliser 5 heures à l'air.",
      "Obturer avec de la couverture ivoire. Laisser cristalliser 24 heures avant de démouler.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson — ganache 28 °C, moulage" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["tablette", "coco", "ivoire", "Malibu", "ganache moulée", "confiserie"],
    parfum_principal: "coco",
    note_concepteur: "Vanille : 2 gousses (non incluses dans la masse). La ganache doit être refroidie à 28 °C avant coulage — plus chaude, elle ferait fondre le chemisage ivoire. Cristallisation obligatoire 5 h à l'air avant obturation pour éviter que le chocolat de couverture ne dissolution la ganache encore tendre.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 13, chef: _CHEF_LN2 },
  },

  {
    id: "moka-ln2",
    nom: "Le Moka",
    categorie: "bonbons",
    sous_categorie: "bonbon_cadre",
    description: "Ganache café intense : crème concentrée, lait, sucre inverti et pâte moka sur couverture noir 66 %, montée au beurre. Cadre 12 mm, guitare 40 × 40 mm, enrobée noir 66 % avec feuille sérigraphiée or.",
    masse_totale_g: 995,
    ingredients: [
      { nom: "Couverture noir 66 %", g: 500, pct: 50, role: "parfum"  },
      { nom: "Crème concentrée",     g: 250, pct: 25, role: "mg"      },
      { nom: "Beurre",               g: 100, pct: 10, role: "mg"      },
      { nom: "Lait",                 g:  80, pct:  8, role: "eau"     },
      { nom: "Sucre inverti",        g:  50, pct:  5, role: "sucrant" },
      { nom: "Pâte moka",            g:  15, pct:  2, role: "parfum"  },
    ],
    procede: [
      "Faire bouillir la crème concentrée, le lait, le sucre inverti et la pâte moka.",
      "Verser sur la couverture noir 66 % finement hachée. Laisser refroidir à 30 °C.",
      "Ajouter le beurre en pommade.",
      "Chablonner une feuille de papier cuisson de couverture noir 66 % à point. Poser un cadre de 12 mm. Laisser cristalliser.",
      "Couler la ganache dans le cadre. Cristalliser 10 heures.",
      "Décadrer et chablonner le dessus. Dès cristallisation du chablonnage, détailler à la guitare 40 × 40 mm.",
      "Enrober de couverture noir 66 %. Appliquer une feuille de décor sérigraphiée or.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson — ganache 30 °C, cadre guitare" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["moka", "café", "ganache cadre", "guitare", "pâte moka", "bonbon chocolat"],
    parfum_principal: "café",
    note_concepteur: "La pâte moka (recette p. 50, T1) est le cœur aromatique de ce bonbon — ne pas la remplacer par de l'extrait de café. Le cadre 12 mm produit un bonbon épais (plus généreux qu'un cadre standard 8 mm) : le dosage beurre/crème est calibré pour cette épaisseur.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 17, chef: _CHEF_LN2 },
  },

  {
    id: "panache-ln2",
    nom: "Le Panaché",
    categorie: "bonbons",
    sous_categorie: "bonbon_cadre",
    description: "Ganache deux chocolats aux bananes flambées au rhum et pailleté feuilletine. Cadre 12 mm, guitare 70 × 30 mm, enrobée noir 66 % avec décor chocolat strié.",
    masse_totale_g: 1130,
    ingredients: [
      { nom: "Couverture lait 36 %",    g: 300, pct: 27, role: "parfum"  },
      { nom: "Couverture noir 66 %",    g: 300, pct: 27, role: "parfum"  },
      { nom: "Lait concentré",          g: 350, pct: 31, role: "mg"      },
      { nom: "Bananes flambées au rhum",g: 100, pct:  8, role: "fruit"   },
      { nom: "Pailleté feuilletine",    g:  80, pct:  7, role: "texture" },
    ],
    procede: [
      "Bananes flambées : poêler 100 g de chair de banane avec 20 g de sucre inverti et 20 g de beurre. Caraméliser légèrement, flamber avec 20 g de rhum brun 45°. Refroidir.",
      "Porter le lait concentré à ébullition, le laisser refroidir à 60 °C.",
      "Verser sur les deux couvertures finement hachées. Ajouter les bananes flambées et le pailleté feuilletine. Laisser refroidir à 30 °C.",
      "Chablonner une feuille de papier cuisson de couverture noir 66 % à point. Poser un cadre 12 mm. Laisser cristalliser.",
      "Couler la ganache dans le cadre. Cristalliser 10 heures.",
      "Décadrer et chablonner le dessus. Détailler à la guitare 70 × 30 mm.",
      "Enrober couverture noir 66 %. Décorer d'une plaquette de chocolat strié.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson — bananes flambées + ganache 30 °C" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait", "gluten"],
    tags: ["panaché", "banane", "rhum", "feuilletine", "deux chocolats", "cadre guitare", "bonbon"],
    parfum_principal: "banane",
    note_concepteur: "Les bananes flambées (100 g dans la liste principale) nécessitent en amont : 100 g banane + 20 g sucre inverti + 20 g rhum 45° + 20 g beurre, non comptés dans la masse totale de la ganache. La feuilletine apporte le croustillant mais absorbe l'humidité : la ganache doit être coulée dans les 30 minutes après ajout.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 19, chef: _CHEF_LN2 },
  },

  {
    id: "barbade-ln2",
    nom: "Le Barbade",
    categorie: "bonbons",
    sous_categorie: "bonbon_moule",
    description: "Bonbon moulé tablette : base cuite jus d'orange/citron/sucre/gingembre à 104 °C, montée au beurre de cacao et couverture noir 70 %. Coulé à la poche en moule tablette chemisé noir 66 %, obturation 10 heures.",
    masse_totale_g: 875,
    ingredients: [
      { nom: "Sucre semoule",            g: 250, pct: 28, role: "sucrant" },
      { nom: "Jus d'orange",             g: 200, pct: 23, role: "fruit"   },
      { nom: "Beurre de cacao",          g: 100, pct: 11, role: "mg"      },
      { nom: "Couverture noir 70 %",     g: 150, pct: 17, role: "parfum"  },
      { nom: "Beurre",                   g:  80, pct:  9, role: "mg"      },
      { nom: "Glucose",                  g:  30, pct:  3, role: "sucrant" },
      { nom: "Jus de citron",            g:  50, pct:  6, role: "fruit"   },
      { nom: "Arôme naturel citron",     g:   5, pct:  1, role: "parfum"  },
      { nom: "Gingembre frais râpé",     g:  10, pct:  1, role: "parfum"  },
    ],
    procede: [
      "Cuire les jus d'orange et de citron avec le sucre, le glucose et le gingembre à 104 °C.",
      "Laisser refroidir à 40 °C. Ajouter le beurre de cacao fondu, la couverture noir 70 % fondue et l'arôme citron.",
      "Laisser refroidir à 35 °C. Ajouter le beurre en pommade.",
      "Chemiser des moules à tablettes de couverture noir 66 %.",
      "Garnir à la poche les moules chemisés. Laisser cristalliser 10 heures.",
      "Obturer avec couverture noir 66 %. Cristalliser 10 heures. Démouler.",
    ],
    cuisson: { temperature_c: 104, duree_min: null, mode: "casserole — jus/sucre 104 °C, moulage tablette" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait"],
    tags: ["barbade", "orange", "citron", "gingembre", "tablette moulée", "beurre de cacao", "bonbon"],
    parfum_principal: "orange",
    note_concepteur: "La liste d'ingrédients du livre présente deux entrées sucre semoule (250 g + 75 g) dont la seconde n'apparaît pas dans le procédé — probablement une erreur de scan : seuls les 250 g ont été retenus (a_verifier). La cuisson des jus à 104 °C concentre les arômes et construit la structure ; la couverture 70 % apporte l'amertume.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 23, chef: _CHEF_LN2 },
  },

  {
    id: "ganache-framboise-ln2",
    nom: "Ganache framboise",
    categorie: "bonbons",
    sous_categorie: "bonbon_cadre",
    description: "Ganache framboise intense sur base lait UHT et couverture noir 66 %. Cadre 8 mm, guitare 1,5 × 3,5 cm, enrobée noir 66 % avec plaquette chocolat décor.",
    masse_totale_g: 1105,
    ingredients: [
      { nom: "Couverture noir 66 %",      g: 600, pct: 54, role: "parfum"  },
      { nom: "Pulpe de framboise",        g: 180, pct: 16, role: "fruit"   },
      { nom: "Lait UHT",                  g: 230, pct: 21, role: "eau"     },
      { nom: "Beurre",                    g:  45, pct:  4, role: "mg"      },
      { nom: "Crème de framboise 25°",    g:  30, pct:  3, role: "parfum"  },
      { nom: "Sucre inverti",             g:  20, pct:  2, role: "sucrant" },
    ],
    procede: [
      "Porter le lait UHT et le sucre inverti à ébullition.",
      "Verser sur la couverture noir 66 % finement hachée. Ajouter la pulpe de framboise chaude.",
      "Laisser refroidir à 35 °C. Ajouter le beurre en pommade et la crème de framboise.",
      "Chablonner une feuille de papier cuisson de couverture noir 66 % à point. Poser un cadre 8 mm. Laisser cristalliser.",
      "Couler la ganache dans le cadre. Cristalliser 10 heures.",
      "Décadrer et chablonner le dessus. Détailler à la guitare 1,5 × 3,5 cm.",
      "Enrober couverture noir 66 %. Décorer d'une plaquette chocolat décor.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson — ganache 35 °C, cadre guitare" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["framboise", "ganache cadre", "guitare", "lait UHT", "bonbon chocolat"],
    parfum_principal: "framboise",
    note_concepteur: "La pulpe de framboise est ajoutée chaude après le lait pour préserver sa fraîcheur aromatique sans cuisson prolongée. La crème de framboise 25° renforce la note alcoolisée en fin de bouche sans dominer — l'incorporer impérativement à 35 °C, pas sur le feu.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 35, chef: _CHEF_LN2 },
  },

  {
    id: "menthe-fraiche-ln2",
    nom: "La Menthe fraîche",
    categorie: "bonbons",
    sous_categorie: "bonbon_cadre",
    description: "Ganache double infusion menthe fraîche et thé vert sur lait concentré, deux couvertures lait et noir. Cadre 8 mm, guitare 22,5 × 22,5 mm, enrobée noir 66 % avec décor thermoformé.",
    masse_totale_g: 1295,
    ingredients: [
      { nom: "Couverture lait 36 %",  g: 700, pct: 54, role: "parfum"  },
      { nom: "Lait concentré",        g: 300, pct: 23, role: "mg"      },
      { nom: "Menthe fraîche",        g:  60, pct:  5, role: "parfum"  },
      { nom: "Beurre",                g:  70, pct:  5, role: "mg"      },
      { nom: "Couverture noir 66 %",  g: 100, pct:  8, role: "parfum"  },
      { nom: "Thé vert",              g:  45, pct:  3, role: "parfum"  },
      { nom: "Sucre inverti",         g:  10, pct:  1, role: "sucrant" },
      { nom: "Glucose",               g:  10, pct:  1, role: "sucrant" },
    ],
    procede: [
      "Porter à ébullition le lait concentré, le sucre inverti et le glucose.",
      "Ajouter la menthe fraîche et le thé vert. Laisser infuser 5 minutes hors du feu.",
      "Chinoiser, peser 300 g d'infusion (compléter avec du lait si besoin).",
      "Verser sur les deux couvertures finement hachées. Laisser refroidir à 35 °C. Ajouter le beurre en pommade.",
      "Chablonner une feuille de papier cuisson de couverture noir 66 % à point. Poser un cadre 8 mm. Laisser cristalliser.",
      "Couler la ganache dans le cadre. Cristalliser 10 heures.",
      "Décadrer et chablonner le dessus. Détailler à la guitare 22,5 × 22,5 mm.",
      "Enrober couverture noir 66 %. Appliquer une feuille thermoformée jusqu'à cristallisation.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "infusion 5 min, ganache 35 °C, cadre guitare" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["menthe", "thé vert", "infusion", "ganache cadre", "guitare", "thermoformé", "bonbon chocolat"],
    parfum_principal: "menthe",
    note_concepteur: "La menthe fraîche (60 g) et le thé vert (45 g) sont infusés 5 min seulement — au-delà, les tanins du thé amèrent. Peser impérativement 300 g d'infusion après chinoiser pour garantir la consistance d'une tablette à l'autre. Ces deux ingrédients sont non retenus dans la ganache finale mais comptent dans la masse de départ.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 39, chef: _CHEF_LN2 },
  },

  {
    id: "citron-vert-ln2",
    nom: "Le Citron vert",
    categorie: "bonbons",
    sous_categorie: "bonbon_cadre",
    description: "Ganache montée citron vert : crème infusée zeste, jaunes blanchis, jus citron vert cuits à 80 °C, beurre monté au batteur, couverture 55 % à point. Cadre 8 mm, guitare 22 × 27,5 mm.",
    masse_totale_g: 1180,
    ingredients: [
      { nom: "Couverture 55 %",    g: 450, pct: 38, role: "parfum"  },
      { nom: "Beurre",             g: 190, pct: 16, role: "mg"      },
      { nom: "Sucre semoule",      g: 200, pct: 17, role: "sucrant" },
      { nom: "Jus de citron vert", g: 120, pct: 10, role: "fruit"   },
      { nom: "Crème liquide",      g: 120, pct: 10, role: "mg"      },
      { nom: "Jaunes d'œufs",      g: 100, pct:  9, role: "emulsifiant" },
    ],
    procede: [
      "Faire bouillir la crème liquide avec les zestes de 2 citrons (non inclus dans la masse).",
      "Blanchir les jaunes d'œufs avec le sucre. Verser la crème infusée. Ajouter le jus de citron vert.",
      "Cuire l'appareil à 80 °C (comme une crème anglaise).",
      "Laisser refroidir à 30 °C. Ajouter le beurre en pommade. Monter au batteur.",
      "Incorporer la couverture 55 % tempérée à point (non fondue).",
      "Chablonner une feuille de papier cuisson de couverture noir 66 %. Poser un cadre 8 mm. Laisser cristalliser.",
      "Abaisser la ganache dans le cadre. Lisser à la règle. Cristalliser 10 heures.",
      "Décadrer et chablonner. Détailler à la guitare 22 × 27,5 mm. Enrober noir 66 %. Déposer plaquette décor.",
    ],
    cuisson: { temperature_c: 80, duree_min: null, mode: "casserole — crème anglaise 80 °C + cadre guitare" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeufs"],
    tags: ["citron vert", "ganache montée", "crème anglaise", "cadre guitare", "bonbon chocolat"],
    parfum_principal: "citron",
    note_concepteur: "Zeste de 2 citrons (non inclus dans la masse). Ce bonbon est techniquement une ganache cuite à la crème anglaise, pas une ganache classique — la cuisson à 80 °C pasteurise les jaunes et donne une texture plus crémeuse. La couverture 55 % est incorporée à point (pas fondue) pour préserver le craquant à la cristallisation.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 41, chef: _CHEF_LN2 },
  },

  {
    id: "miel-chataignier-ln2",
    nom: "Ganache miel de châtaignier",
    categorie: "bonbons",
    sous_categorie: "bonbon_cadre",
    description: "Ganache lait montée au batteur : crème, miel de châtaignier et couverture lait 36 %. Cadre 8 mm, guitare 22,5 × 22,5 mm, enrobée couverture lait avec feuille sérigraphiée marbrée.",
    masse_totale_g: 940,
    ingredients: [
      { nom: "Couverture lait 36 %",      g: 420, pct: 45, role: "parfum"  },
      { nom: "Crème liquide",             g: 350, pct: 37, role: "mg"      },
      { nom: "Miel de châtaignier",       g: 100, pct: 11, role: "sucrant" },
      { nom: "Beurre",                    g:  70, pct:  7, role: "mg"      },
    ],
    procede: [
      "Faire bouillir la crème liquide. Ajouter le miel de châtaignier.",
      "Verser sur la couverture lait 36 % hachée. Laisser refroidir à 35 °C.",
      "Ajouter le beurre en pommade. Monter au batteur jusqu'à légèreté.",
      "Chablonner une feuille de papier cuisson de couverture noir 66 % à point. Poser un cadre 8 mm. Laisser cristalliser.",
      "Couler la ganache montée dans le cadre. Lisser. Cristalliser 10 heures.",
      "Décadrer et chablonner le dessus. Détailler à la guitare 22,5 × 22,5 mm.",
      "Enrober couverture lait 36 %. Appliquer feuille sérigraphiée marbrée chocolat blanc/lait/noir.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson — ganache montée 35 °C, cadre guitare" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait"],
    tags: ["miel", "châtaignier", "ganache montée", "couverture lait", "cadre guitare", "bonbon chocolat"],
    parfum_principal: "miel",
    note_concepteur: "Le livre présente une incohérence : 150 g de crème (version française) vs 350 g (version anglaise). La version 350 g a été retenue — le ratio crème/chocolat 0,83 est cohérent pour une ganache montée au batteur. Le miel de châtaignier apporte une amertume végétale qui contraste avec la douceur du chocolat au lait.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 43, chef: _CHEF_LN2 },
  },

  /* ── École Lenôtre T2 — Batch 2 : ganaches cadre aromats ────────────── */

  {
    id: "gingembre-ln2",
    nom: "Le Gingembre",
    categorie: "bonbons",
    sous_categorie: "bonbon_cadre",
    description: "Ganache infusion thé de Ceylan et gingembre frais sur deux couvertures, avec gingembre confit broyé incorporé. Cadre 8 mm, guitare 15 × 35 mm, enrobée noir 66 % avec 4 traits de fourchette.",
    masse_totale_g: 1080,
    ingredients: [
      { nom: "Couverture noir 66 %",    g: 300, pct: 28, role: "parfum"  },
      { nom: "Crème liquide",           g: 320, pct: 30, role: "mg"      },
      { nom: "Couverture lait 36 %",    g:  80, pct:  7, role: "parfum"  },
      { nom: "Beurre pommade",          g:  65, pct:  6, role: "mg"      },
      { nom: "Thé de Ceylan",           g:  20, pct:  2, role: "parfum"  },
      { nom: "Gingembre confit broyé",  g:  15, pct:  1, role: "parfum"  },
      { nom: "Gingembre frais râpé",    g: 280, pct: 26, role: "parfum"  },
    ],
    procede: [
      "Faire bouillir la crème liquide avec le gingembre frais râpé. Ajouter le thé de Ceylan à ébullition, infuser 3 minutes hors du feu.",
      "Chinoiser et peser 320 g d'infusion (compléter avec de la crème si besoin).",
      "Verser l'infusion chaude sur les deux couvertures hachées. Laisser refroidir à 35 °C.",
      "Ajouter le beurre pommade et le gingembre confit broyé.",
      "Chablonner une feuille de papier cuisson de couverture noir 66 % à point. Poser un cadre 8 mm. Laisser cristalliser.",
      "Couler la ganache dans le cadre. Cristalliser 10 heures.",
      "Décadrer et chablonner le dessus. Détailler à la guitare 15 × 35 mm.",
      "Enrober couverture noir 66 %. Décorer de 4 traits de fourchette.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "infusion 3 min, ganache 35 °C, cadre guitare" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["gingembre", "thé de Ceylan", "infusion", "ganache cadre", "guitare", "bonbon chocolat"],
    parfum_principal: "gingembre",
    note_concepteur: "Le gingembre frais (1,5 g dans la liste originale du livre — le « 280 g » est la masse totale de crème infusée, pas de gingembre brut) parfume la crème lors de l'infusion ; le gingembre confit broyé apporte une note sucrée-épicée résiduelle à la texture. Infusion thé 3 min maximum pour éviter l'astringence.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 53, chef: _CHEF_LN2 },
  },

  {
    id: "quatre-epices-ln2",
    nom: "Le Quatre-épices",
    categorie: "bonbons",
    sous_categorie: "bonbon_cadre",
    description: "Ganache infusion quatre-épices (gingembre, cardamome, vanille, cannelle) sur chocolat ganache 50 %. Cadre 8 mm, guitare 22,5 × 30 mm, enrobée noir 66 % avec saupoudrage grué de cacao.",
    masse_totale_g: 1100,
    ingredients: [
      { nom: "Chocolat ganache 50 %", g: 650, pct: 59, role: "parfum"  },
      { nom: "Crème liquide",         g: 450, pct: 41, role: "mg"      },
      { nom: "Quatre-épices",         g:   6, pct:  0, role: "parfum"  },
    ],
    procede: [
      "Porter la crème liquide à ébullition avec les quatre-épices en poudre. Laisser infuser.",
      "Chinoiser et verser sur le chocolat finement haché. Laisser refroidir à 30 °C.",
      "Chablonner une feuille de papier cuisson de couverture noir 66 % à point. Poser un cadre 8 mm. Laisser cristalliser.",
      "Couler la ganache dans le cadre. Cristalliser 10 heures.",
      "Décadrer et chablonner le dessus. Détailler à la guitare 22,5 × 30 mm.",
      "Enrober couverture noir 66 %. Parsemer de grué de cacao.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "infusion, ganache 30 °C, cadre guitare" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["quatre-épices", "épices", "gingembre", "cardamome", "cannelle", "grué", "ganache cadre", "bonbon chocolat"],
    parfum_principal: "épices",
    note_concepteur: "Le « chocolat ganache 50 % » est une couverture spécifique type Callebaut 50 % (fond plus vite et est moins amer que le 66 %) — peut être remplacé par couverture 58 %. Le grué de cacao en finition apporte une amertume et un craquant qui contrastent avec le fondu épicé de la ganache.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 54, chef: _CHEF_LN2 },
  },

  {
    id: "barbarie-ln2",
    nom: "Le Barbarie",
    categorie: "bonbons",
    sous_categorie: "bonbon_cadre",
    description: "Ganache figues séchées macérées 24 h dans la crème, purée de figue et miel toutes fleurs sur deux couvertures. Cadre 12 mm, guitare 22,5 × 30 mm, enrobée noir 66 % avec goutte chocolat safrané.",
    masse_totale_g: 1360,
    ingredients: [
      { nom: "Couverture lait 36 %",    g: 450, pct: 33, role: "parfum"  },
      { nom: "Purée de figue",          g: 360, pct: 26, role: "fruit"   },
      { nom: "Beurre",                  g: 200, pct: 15, role: "mg"      },
      { nom: "Chocolat ganache 50 %",   g: 200, pct: 15, role: "parfum"  },
      { nom: "Figues sèches",           g: 300, pct: 22, role: "fruit"   },
      { nom: "Crème liquide",           g: 160, pct: 12, role: "mg"      },
      { nom: "Miel toutes fleurs",      g:  50, pct:  4, role: "sucrant" },
    ],
    procede: [
      "Hacher très finement les figues sèches. Les faire macérer 24 heures dans la crème liquide.",
      "Porter à ébullition la crème (avec les figues), le miel et la purée de figue.",
      "Verser sur les deux couvertures hachées. Laisser refroidir à 35 °C. Ajouter le beurre en pommade.",
      "Chablonner une feuille de papier cuisson de couverture noir 66 % à point. Poser un cadre 12 mm. Laisser cristalliser.",
      "Couler la ganache dans le cadre. Cristalliser 10 heures.",
      "Décadrer et chablonner le dessus. Détailler à la guitare 22,5 × 30 mm.",
      "Sur feuille guitar, dresser de petites gouttes de couverture noir, parsemer de pistils de safran. Cristalliser.",
      "Enrober les intérieurs de couverture noir 66 %. Déposer une goutte chocolat safrané sur chaque bonbon.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "macération 24 h + ganache 35 °C, cadre guitare" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait"],
    tags: ["figue", "safran", "macération", "ganache cadre", "miel", "deux chocolats", "bonbon chocolat"],
    parfum_principal: "figue",
    note_concepteur: "Les figues macèrent 24 h dans la crème — elles s'hydrident et fondent à la cuisson. La masse_totale inclut les figues (300 g) + la crème de macération (160 g) comptées séparément car les pct ont été calculés sur l'ensemble (a_verifier). Les pistils de safran sont en Q.S. (non comptés). Cadre 12 mm pour une ganache plus généreuse.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 57, chef: _CHEF_LN2 },
  },

  {
    id: "licorie-ln2",
    nom: "Le Licorie",
    categorie: "bonbons",
    sous_categorie: "bonbon_cadre",
    description: "Ganache réglisse : sucre-glucose-crème cuit à 105 °C avec café lyophilisé et beurre salé, couvertures noir et lait, suc de réglisse et arômes. Cadre 8 mm, guitare 35 × 15 mm, enrobée noir 66 % avec plaquette décor.",
    masse_totale_g: 1368,
    ingredients: [
      { nom: "Couverture lait 36 %",      g: 230, pct: 17, role: "parfum"  },
      { nom: "Couverture noir 66 %",      g: 280, pct: 20, role: "parfum"  },
      { nom: "Crème liquide",             g: 300, pct: 22, role: "mg"      },
      { nom: "Beurre salé",               g: 250, pct: 18, role: "mg"      },
      { nom: "Sucre",                     g: 100, pct:  7, role: "sucrant" },
      { nom: "Glucose",                   g:  80, pct:  6, role: "sucrant" },
      { nom: "Café lyophilisé",           g:  10, pct:  1, role: "parfum"  },
      { nom: "Suc de réglisse",           g:  15, pct:  1, role: "parfum"  },
      { nom: "Arôme naturel réglisse",    g:   2, pct:  0, role: "parfum"  },
      { nom: "Arôme naturel anis",        g:   1, pct:  0, role: "parfum"  },
    ],
    procede: [
      "Faire cuire le sucre, le glucose et la crème à 105 °C.",
      "Verser sur les deux couvertures mi-fondues. Ajouter le beurre salé tempéré, le café, le suc de réglisse et les arômes.",
      "Chablonner une feuille de papier cuisson de couverture noir 66 % à point. Poser un cadre 8 mm. Laisser cristalliser.",
      "Couler la ganache dans le cadre. Cristalliser 10 heures.",
      "Décadrer et chablonner le dessus. Détailler à la guitare 35 × 15 mm.",
      "Enrober couverture noir 66 %. Déposer une plaquette chocolat décor.",
    ],
    cuisson: { temperature_c: 105, duree_min: null, mode: "casserole — sucre/crème 105 °C, cadre guitare" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["réglisse", "anis", "café", "beurre salé", "ganache cadre", "guitare", "bonbon chocolat"],
    parfum_principal: "réglisse",
    note_concepteur: "6 gouttes arôme réglisse + 3 gouttes arôme anis (non inclus dans la masse totale). La combinaison beurre salé + café lyophilisé est la signature de ce bonbon : le sel rehausse la réglisse. Cuisson crème/sucre à 105 °C uniquement (vs 118-121 °C pour un caramel) pour une ganache fluide plutôt que figée.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 59, chef: _CHEF_LN2 },
  },

  {
    id: "anis-ln2",
    nom: "L'Anis",
    categorie: "bonbons",
    sous_categorie: "bonbon_cadre",
    description: "Ganache anis grec (Ouzo) et Marie Brizard sur sucre-glucose-crème cuit à 106 °C, couverture lait et cacao pâte, beurre de cacao. Cadre 8 mm, triangle 22,5 mm de côté, enrobée noir 66 %.",
    masse_totale_g: 1175,
    ingredients: [
      { nom: "Couverture lait 36 %",  g: 460, pct: 39, role: "parfum"  },
      { nom: "Beurre",                g: 220, pct: 19, role: "mg"      },
      { nom: "Crème liquide",         g: 250, pct: 21, role: "mg"      },
      { nom: "Cacao pur pâte",        g:  80, pct:  7, role: "parfum"  },
      { nom: "Sucre",                 g: 150, pct: 13, role: "sucrant" },
      { nom: "Glucose",               g: 100, pct:  9, role: "sucrant" },
      { nom: "Beurre de cacao",       g:  50, pct:  4, role: "mg"      },
      { nom: "Ouzo",                  g:  35, pct:  3, role: "parfum"  },
      { nom: "Marie Brizard",         g:  10, pct:  1, role: "parfum"  },
    ],
    procede: [
      "Faire cuire le sucre, le glucose et la crème à 106 °C.",
      "Laisser refroidir à 40 °C. Ajouter le chocolat lait fondu, le beurre de cacao fondu, l'Ouzo et la Marie Brizard.",
      "Laisser refroidir à 35 °C. Ajouter le beurre en pommade.",
      "Chablonner une feuille de papier cuisson de couverture noir 66 % à point. Poser un cadre 8 mm. Laisser cristalliser.",
      "Couler la ganache dans le cadre. Cristalliser 10 heures.",
      "Décadrer et chablonner le dessus. Détailler à la guitare en triangles de 22,5 mm de côté.",
      "Enrober couverture noir 66 %.",
    ],
    cuisson: { temperature_c: 106, duree_min: null, mode: "casserole — sucre/crème 106 °C, cadre guitare triangles" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait"],
    tags: ["anis", "Ouzo", "Marie Brizard", "beurre de cacao", "ganache cadre", "triangle", "bonbon chocolat"],
    parfum_principal: "anis",
    note_concepteur: "La somme des pct dépasse 100 % car plusieurs ingrédients ont été arrondis (a_verifier). L'Ouzo (anis grec sec) + Marie Brizard (anis doux sucré) créent un profil anisé complexe. Le cacao pur pâte (80 g) alourdit la ganache et équilibre la douceur de la couverture lait. Format triangle atypique en confiserie Lenôtre.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 61, chef: _CHEF_LN2 },
  },

  /* ── École Lenôtre T2 — Batch 3 : pralinés, gianduja, compositions ───── */

  {
    id: "bouchee-gianduja-pistache-ln2",
    nom: "La Bouchée gianduja pistache",
    categorie: "bonbons",
    sous_categorie: "bonbon_cadre",
    description: "Deux couches cadre : gianduja pistache (beurre de cacao, pâte pistache, duja, huile soja, vanille — 3 mm) puis ganache amère (crème, vanille, glucose, cacao pâte, couverture 71 % — 5 mm). Guitare 6 × 3 cm, trempé noir 66 %, triangle décor.",
    masse_totale_g: 1610,
    ingredients: [
      { nom: "Duja noisette-amande",      g: 600, pct: 37, role: "parfum"  },
      { nom: "Couverture noir 71 %",      g: 250, pct: 16, role: "parfum"  },
      { nom: "Beurre de cacao",           g: 240, pct: 15, role: "mg"      },
      { nom: "Crème liquide",             g: 300, pct: 19, role: "mg"      },
      { nom: "Pâte de pistache",          g:  80, pct:  5, role: "parfum"  },
      { nom: "Cacao pur pâte",            g:  50, pct:  3, role: "parfum"  },
      { nom: "Glucose",                   g:  50, pct:  3, role: "sucrant" },
      { nom: "Huile de soja",             g:  30, pct:  2, role: "mg"      },
      { nom: "Beurre",                    g:  15, pct:  1, role: "mg"      },
    ],
    procede: [
      "Gianduja pistache : chauffer le beurre de cacao (140 g), la pâte de pistache et l'huile de soja à 40 °C. Ajouter le duja. Tabler à 30 °C.",
      "Chablonner une feuille de papier cuisson de couverture noir 66 % à point. Poser un cadre 3 mm. Laisser cristalliser.",
      "Abaisser le gianduja pistache dans le cadre. Lisser. Cristalliser 1 heure.",
      "Ganache amère : faire bouillir la crème avec la vanille grattée et le glucose. Verser sur le cacao pâte et la couverture 71 % hachée. Laisser refroidir à 35 °C. Ajouter le beurre en pommade.",
      "Disposer un second cadre 5 mm sur le gianduja cristallisé. Y couler la ganache amère. Lisser. Cristalliser 10 heures.",
      "Décadrer et chablonner avec couverture noir 66 %. Détailler à la guitare 6 × 3 cm.",
      "Tremper dans couverture noir 66 %. Appliquer un triangle de chocolat décor.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "tablage 30-32 °C + gianduja + cadre guitare deux couches" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "fruits_a_coque_noisette", "fruits_a_coque_amande", "fruits_a_coque_pistache"],
    tags: ["gianduja", "pistache", "ganache amère", "duja", "deux couches", "guitare", "bonbon chocolat"],
    parfum_principal: "pistache",
    note_concepteur: "Le gianduja pistache est tabulé à 30 °C (non 32 °C) car la pâte de pistache apporte de l'humidité qui abaisse légèrement le point de travail. La couche gianduja (3 mm) est délibérément plus fine que la ganache (5 mm) pour que l'amertume de la couverture 71 % domine en bouche.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 21, chef: _CHEF_LN2 },
  },

  {
    id: "pistachier-ln2",
    nom: "Le Pistachier",
    categorie: "bonbons",
    sous_categorie: "bonbon_cadre",
    description: "Deux couches cadre : gianduja nougatine (duja amande-noisette, beurre cacao, couverture lait, nougatine pilée — 6 mm) et ganache pistache (crème, pâte pistache, couverture ivoire, beurre — 6 mm). Guitare 17 × 30 mm, noir 66 %, décor 2 pistaches vernies.",
    masse_totale_g: 1110,
    ingredients: [
      { nom: "Duja amande-noisette",   g: 500, pct: 45, role: "parfum"  },
      { nom: "Couverture ivoire",      g: 600, pct: 54, role: "parfum"  },
      { nom: "Pâte de pistache",       g:  35, pct:  3, role: "parfum"  },
      { nom: "Crème liquide",          g: 150, pct: 14, role: "mg"      },
      { nom: "Nougatine pilée",        g: 150, pct: 14, role: "texture" },
      { nom: "Beurre de cacao",        g:  75, pct:  7, role: "mg"      },
      { nom: "Couverture lait 36 %",   g: 100, pct:  9, role: "parfum"  },
      { nom: "Beurre",                 g:  35, pct:  3, role: "mg"      },
    ],
    procede: [
      "Gianduja nougatine : faire fondre le beurre de cacao et la couverture lait à 45 °C. Mélanger au duja. Chauffer à 40 °C. Tabler à 30 °C. Incorporer la nougatine pilée.",
      "Chablonner une feuille de cuisson de couverture noir 66 %. Poser un cadre 6 mm. Laisser cristalliser. Couler le gianduja. Lisser. Cristalliser 1 heure.",
      "Ganache pistache : faire bouillir la crème avec la pâte de pistache. Verser sur la couverture ivoire finement hachée. Mélanger. Refroidir à 30 °C. Ajouter le beurre en pommade.",
      "Disposer un cadre 6 mm sur le gianduja cristallisé. Couler la ganache. Lisser. Cristalliser 10 heures.",
      "Décadrer et chablonner. Détailler à la guitare 17 × 30 mm.",
      "Enrober couverture noir 66 %. Décorer de 2 pistaches vernies en diagonale.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "tablage 30 °C + gianduja + cadre guitare deux couches" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "fruits_a_coque_noisette", "fruits_a_coque_amande", "fruits_a_coque_pistache"],
    tags: ["pistachier", "gianduja", "nougatine", "pistache", "deux couches", "guitare", "bonbon chocolat"],
    parfum_principal: "pistache",
    note_concepteur: "La nougatine pilée (150 g) apporte le croustillant caractéristique — elle doit être incorporée au gianduja après tablage, juste avant coulage, sinon elle ramollit au contact de l'humidité. Les pistaches vernies à la gomme arabique maintiennent leur couleur verte au contact du chocolat.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 91, chef: _CHEF_LN2 },
  },

  {
    id: "sesame-ln2",
    nom: "Le Sésame",
    categorie: "bonbons",
    sous_categorie: "bonbon_cadre",
    description: "Praliné noisette mélangé à pâte de sésame, beurre de cacao et couverture lait. Cadre 8 mm, guitare 22,5 × 22,5 mm, enrobée noir 66 % avec 4 traits de fourchette.",
    masse_totale_g: 1150,
    ingredients: [
      { nom: "Pâte de sésame",          g: 560, pct: 49, role: "parfum"  },
      { nom: "Praliné noisette",         g: 440, pct: 38, role: "parfum"  },
      { nom: "Beurre de cacao",          g: 150, pct: 13, role: "mg"      },
      { nom: "Couverture lait 36 %",     g: 150, pct: 13, role: "parfum"  },
    ],
    procede: [
      "Mélanger le praliné noisette et la pâte de sésame.",
      "Ajouter le beurre de cacao fondu et la couverture lait fondue. Chauffer l'ensemble à 45 °C.",
      "Tabler à 30 °C.",
      "Chablonner une feuille de cuisson de couverture noir 66 % à point. Poser un cadre 8 mm. Laisser cristalliser.",
      "Abaisser la masse pralinée dans le cadre. Lisser à la règle. Cristalliser 5 heures.",
      "Décadrer et chablonner le dessus. Détailler à la guitare 22,5 × 22,5 mm.",
      "Enrober couverture noir 66 %. Décorer de 4 traits de fourchette. Parsemer de graines de sésame grillées.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "tablage 30 °C, cadre guitare" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait", "fruits_a_coque_noisette", "sesame"],
    tags: ["sésame", "praliné noisette", "pâte de sésame", "cadre guitare", "bonbon chocolat"],
    parfum_principal: "sésame",
    note_concepteur: "Q.S. graines de sésame entières légèrement grillées en décor (non comptées). La somme des pct dépasse 100 % car la masse totale des 4 ingrédients est 1300 g (a_verifier). La pâte de sésame (tahini ou pâte spécifique confiserie) apporte une amertume grillée qui prolonge le praliné noisette.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 97, chef: _CHEF_LN2 },
  },

  {
    id: "valencia-cafe-ln2",
    nom: "Le Valencia café",
    categorie: "bonbons",
    sous_categorie: "bonbon_praline",
    description: "Praliné amande travaillé avec beurre de cacao, couverture lait et pâte moka. Cadre 8 mm, guitare 22,5 × 22,5 mm, enrobée noir 66 % avec rayures couverture lait et marque fourchette.",
    masse_totale_g: 1285,
    ingredients: [
      { nom: "Praliné amande",        g: 1000, pct: 78, role: "parfum"  },
      { nom: "Couverture lait 36 %",  g:  160, pct: 12, role: "parfum"  },
      { nom: "Beurre de cacao",       g:  100, pct:  8, role: "mg"      },
      { nom: "Pâte moka",             g:   25, pct:  2, role: "parfum"  },
    ],
    procede: [
      "Faire fondre la couverture lait 36 % et le beurre de cacao à 45 °C.",
      "Ajouter le praliné amande et la pâte moka. Bien mélanger.",
      "Tabler à 30 °C.",
      "Chablonner une feuille de cuisson de couverture noir 66 % à point. Poser un cadre 8 mm. Laisser cristalliser.",
      "Abaisser la masse pralinée dans le cadre. Lisser à la règle. Cristalliser 5 heures.",
      "Décadrer et chablonner le dessus. Détailler à la guitare 22,5 × 22,5 mm.",
      "Enrober couverture noir 66 %. Rayer avec un cornet de couverture lait 36 %. Marquer à la fourchette.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "tablage 30 °C, cadre guitare" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "fruits_a_coque_amande"],
    tags: ["praliné amande", "café", "moka", "cadre guitare", "bonbon chocolat"],
    parfum_principal: "café",
    note_concepteur: "La pâte moka (recette p. 50, T1) est essentielle — elle parfume avec intensité sur un volume réduit (25 g pour 1 kg de praliné). Le tablage à 30 °C est critique : le praliné doit cristalliser suffisamment pour tenir en cadre sans s'étaler. Finition rayures + fourchette : technique classique Lenôtre de différentiation visuelle.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 93, chef: _CHEF_LN2 },
  },

  {
    id: "zebre-ln2",
    nom: "Le Zébré",
    categorie: "bonbons",
    sous_categorie: "bonbon_cadre",
    description: "Sept couches alternées de gianduja clair, fondant et pistache (cadres 3 mm × 7). Structure zébrée visible à la coupe. Guitare 15 × 37,5 mm, partiellement enrobée noir 66 %.",
    masse_totale_g: 2340,
    ingredients: [
      { nom: "Duja noisette-amande",   g: 2310, pct: 99, role: "parfum"  },
      { nom: "Beurre de cacao",        g: 335,  pct:  0, role: "mg"      },
      { nom: "Couverture lait 36 %",   g:  65,  pct:  0, role: "parfum"  },
      { nom: "Cacao pur pâte",         g:  85,  pct:  0, role: "parfum"  },
      { nom: "Pâte de pistache",       g:  40,  pct:  0, role: "parfum"  },
      { nom: "Huile de soja",          g:  15,  pct:  0, role: "mg"      },
    ],
    procede: [
      "Gianduja clair : fondre beurre de cacao (200 g) + couverture lait (65 g). Ajouter au duja (1340 g). Chauffer à 45 °C. Tabler à 30 °C.",
      "Gianduja fondant : fondre beurre de cacao (65 g) + cacao pâte (85 g). Ajouter au duja (670 g). Chauffer à 45 °C. Tabler à 32 °C.",
      "Gianduja pistache : fondre beurre de cacao (70 g). Ajouter au duja (300 g). Chauffer à 40 °C. Tabler à 30 °C. Incorporer pâte pistache détendue à l'huile de soja.",
      "Chablonner feuille de cuisson avec couverture à point. Poser cadre 3 mm. Cristalliser.",
      "Alterner les couches (cadre 3 mm × 1 chablonnage pour chaque) dans l'ordre : clair, fondant, clair, pistache, clair, fondant, clair. Cristalliser 30 min entre chaque couche.",
      "Après les 7 couches, cristalliser 5 heures. Décadrer et chablonner. Cristalliser.",
      "Détailler à la guitare 15 × 37,5 mm. Enrober partiellement de couverture noir 66 %.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "tablage 30-32 °C × 3 gianduja, cadre multicouche" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait", "fruits_a_coque_noisette", "fruits_a_coque_amande", "fruits_a_coque_pistache"],
    tags: ["gianduja", "zébré", "multicouche", "pistache", "duja", "guitare", "bonbon chocolat"],
    parfum_principal: null,
    note_concepteur: "Les quantités pour les 3 gianduja totalisent plus que la masse_totale listée : les pct sont indicatifs (a_verifier). Le gianduja fondant est tabulé à 32 °C (vs 30 °C) car le cacao pâte le durcit davantage. Chaque couche doit cristalliser 30 min avant la suivante — c'est la condition pour un zébrage net à la coupe.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 93, chef: _CHEF_LN2 },
  },

  {
    id: "chocolat-blanc-cerise-ln2",
    nom: "Chocolat blanc/cerise",
    categorie: "bonbons",
    sous_categorie: "bonbon_moule",
    description: "Bonbon moulé petits cœurs (Philippe Bertrand) : ganache Blanc Satin avec sorbitol, pâte d'amande, jus de griottine et demi-griottine au centre. Enrobage Blanc Satin.",
    masse_totale_g: 650,
    ingredients: [
      { nom: "Blanc Satin (couverture ivoire)", g: 260, pct: 40, role: "parfum"  },
      { nom: "Crème UHT",                       g: 340, pct: 52, role: "mg"      },
      { nom: "Pâte d'amande 66 %",              g:  25, pct:  4, role: "parfum"  },
      { nom: "Jus de griottine",                g:  25, pct:  4, role: "fruit"   },
      { nom: "Sorbitol liquide",                g:  10, pct:  2, role: "humectant"},
    ],
    procede: [
      "Faire bouillir la crème, le sorbitol et la pâte d'amande.",
      "Verser sur le Blanc Satin. Ajouter le jus de griottine. Laisser refroidir à 28 °C.",
      "Chemiser des moules petits cœurs de Blanc Satin tempéré.",
      "Déposer une demi-griottine au centre de chaque alvéole. Couler la ganache.",
      "Laisser cristalliser. Obturer avec Blanc Satin. Démouler après 24 heures.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson — ganache 28 °C, moulage petits cœurs" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "fruits_a_coque_amande"],
    tags: ["chocolat blanc", "cerise", "griottine", "cœur", "moulé", "pâte d'amande", "sorbitol", "bonbon"],
    parfum_principal: "cerise",
    note_concepteur: "Recette pour 2 plaques, moules cerises (colis n°14). La demi-griottine doit être parfaitement égouttée — l'alcool résiduel empêcherait la cristallisation. Le sorbitol prévient la dessiccation de la ganache ivoire, particulièrement sensible. « Blanc Satin » est une couverture ivoire Barry Callebaut.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 87, chef: _CHEF_LN2 },
  },

  {
    id: "caramel-fraise-ln2",
    nom: "Caramel fraise",
    categorie: "bonbons",
    sous_categorie: "bonbon_moule",
    description: "Bonbon moulé petits cœurs (Philippe Bertrand) : caramel blond à la pulpe de fraise et glucose, monté à la couverture lactée Elysée Lenôtre et beurre de cacao. Texture fondante.",
    masse_totale_g: 450,
    ingredients: [
      { nom: "Couverture lactée Elysée Lenôtre", g: 125, pct: 28, role: "parfum"  },
      { nom: "Pulpe de fraise",                  g: 200, pct: 44, role: "fruit"   },
      { nom: "Sucre semoule",                    g: 100, pct: 22, role: "sucrant" },
      { nom: "Beurre de cacao",                  g:  15, pct:  3, role: "mg"      },
      { nom: "Beurre frais",                     g:  25, pct:  6, role: "mg"      },
      { nom: "Glucose",                          g:  50, pct: 11, role: "sucrant" },
    ],
    procede: [
      "Faire un caramel blond avec le sucre semoule à sec.",
      "Décuire avec la pulpe de fraise, le glucose et le beurre frais.",
      "Laisser refroidir à 50 °C. Ajouter la couverture lactée Elysée Lenôtre, puis le beurre de cacao.",
      "Mélanger soigneusement.",
      "Chemiser des moules petits cœurs de couverture lait tempérée.",
      "Garnir à la poche les moules chemisés. Cristalliser. Obturer. Démouler.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "caramel à sec + décuisson, moulage petits cœurs" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["caramel fraise", "fraise", "caramel", "bonbon moulé", "cœur", "couverture lait", "bonbon"],
    parfum_principal: "fraise",
    note_concepteur: "Recette pour 4 plaques, moules petits cœurs (colis n°4). La couverture « Elysée Lenôtre » est une couverture lactée propriétaire Barry Callebaut/Lenôtre — remplacer par couverture lait 36 % standard. L'ajout de la couverture à 50 °C uniquement (pas en dessous) est crucial pour une émulsion stable.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 87, chef: _CHEF_LN2 },
  },

];
