const _SRC_LN1  = "Chocolats et сonfiserie de l ecole Lenotre T1.pdf";
const _CHEF_LN1 = "François Legras & Stéphane Glacier";

export const RECETTES_BONBONS = [

  /* ── École Lenôtre T1 — Confiseries chocolat ────────────────────────── */

  {
    id: "cote-dor-ln1",
    nom: "Le Côte-d'or — fondant cassis-cerise",
    categorie: "bonbons",
    sous_categorie: "bonbon_moule",
    description: "Bonbon moulé : coques chocolat noir garnies d'un fondant cassis-crème de cassis, avec cerises à l'alcool au fond. Croûte à l'air 10 heures, enrobage noir 66 %.",
    masse_totale_g: 750,
    ingredients: [
      { nom: "Fondant au cassis",          g: 500, pct: 67, role: "sucrant" },
      { nom: "Grains de cassis à l'alcool",g: 180, pct: 24, role: "fruit"   },
      { nom: "Crème de cassis",            g:  70, pct:  9, role: "parfum"  },
    ],
    procede: [
      "Faire chauffer le fondant au cassis et la crème de cassis à 32 °C.",
      "Déposer éventuellement quelques grains de cassis dans le fond des coques en chocolat noir.",
      "Couler le fondant jusqu'aux 3/4 des coques. Laisser croûter 10 heures à l'air.",
      "Enrober de couverture noir 66 %. Déposer une plaquette de chocolat coloré découpée.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson — fondant 32 °C" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["bonbon", "cassis", "fondant", "moulé", "liqueur", "confiserie"],
    parfum_principal: "cassis",
    note_concepteur: "Le fondant au cassis doit être tempéré à 32 °C max pour ne pas recristalliser brutalement. La formation d'une croûte (10 heures à l'air) avant obturation est indispensable pour éviter que le chocolat d'enrobage ne dissolve le fondant.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 75, chef: _CHEF_LN1 },
  },

  {
    id: "martinique-ln1",
    nom: "Le Martinique — nougat tendre & ganache rhum",
    categorie: "bonbons",
    sous_categorie: "bonbon_cadre",
    description: "Bonbon deux couches : nougat tendre miel-ananas (3 mm) surmonté d'une ganache chocolat au rhum agricole (6 mm). Cadre guitare 22,5 × 22,5 mm, enrobé noir 66 %.",
    masse_totale_g: 1895,
    ingredients: [
      { nom: "Chocolat ganache 50 %",       g: 500, pct: 27, role: "parfum"  },
      { nom: "Miel",                         g: 300, pct: 16, role: "sucrant" },
      { nom: "Crème liquide 35 % (ganache)", g: 250, pct: 13, role: "mg"      },
      { nom: "Couverture lait 36 %",         g: 250, pct: 13, role: "parfum"  },
      { nom: "Crème fleurette (nougat)",     g: 200, pct: 11, role: "mg"      },
      { nom: "Ananas confits hachés séchés", g: 160, pct:  8, role: "fruit"   },
      { nom: "Rhum agricole 45°",            g:  80, pct:  4, role: "parfum"  },
      { nom: "Amandes effilées",             g:  80, pct:  4, role: "parfum"  },
      { nom: "Glucose",                      g:  75, pct:  4, role: "sucrant" },
    ],
    procede: [
      "Nougat : cuire miel, crème fleurette et glucose à 130 °C. Ajouter amandes et ananas hachés séchés. Étaler immédiatement en cadre 3 mm. Refroidir.",
      "Ganache : faire bouillir la crème. Verser sur les couvertures finement hachées. Refroidir à 35 °C. Ajouter le rhum.",
      "Disposer un cadre 6 mm sur le nougat froid. Y couler la ganache. Laisser cristalliser 10 heures.",
      "Chablonner les deux faces. Dès cristallisation, détailler à la guitare 22,5 × 22,5 mm.",
      "Enrober couverture noir 66 %. Décorer de 3 traits de fourchette.",
    ],
    cuisson: { temperature_c: 130, duree_min: null, mode: "casserole — nougat 130 °C + cadre confiserie" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "fruits_a_coque_amande"],
    tags: ["bonbon", "nougat tendre", "rhum", "ananas", "cadre guitare", "deux couches", "confiserie"],
    parfum_principal: "chocolat noir",
    note_concepteur: "L'ananas confit doit être haché puis séché avant incorporation au nougat — l'humidité résiduelle ramollirait la texture. Le rhum agricole (45°) s'incorpore à la ganache à 35 °C uniquement, jamais sur le feu.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 77, chef: _CHEF_LN1 },
  },

  {
    id: "buchette-agrumes-ln1",
    nom: "La Bûchette aux agrumes",
    categorie: "bonbons",
    sous_categorie: "bonbon_praline",
    description: "Bûchette praliné noisette-couverture lait parfumée citron et orange confits. Dressée en cylindres (douille n°8), saupoudrée de pralinettes, pistolet à 32 °C, détaillée à 3 cm. Enrobée noir 66 %.",
    masse_totale_g: 1510,
    ingredients: [
      { nom: "Praliné noisette",          g: 1000, pct: 66, role: "parfum"  },
      { nom: "Couverture lait 36 %",      g:  400, pct: 27, role: "parfum"  },
      { nom: "Pralinettes",               g:   50, pct:  3, role: "texture" },
      { nom: "Arôme naturel citron",      g:   20, pct:  2, role: "parfum"  },
      { nom: "Zeste citron confit haché", g:   20, pct:  1, role: "parfum"  },
      { nom: "Zeste orange confit haché", g:   20, pct:  1, role: "parfum"  },
    ],
    procede: [
      "Mélanger le praliné noisette et la couverture lait fondue. Ajouter l'arôme citron et les zestes confits hachés.",
      "Chauffer à 45 °C, tabler sur marbre à 30 °C.",
      "À la poche et douille unie n°8, dresser des cylindres sur papier cuisson. Parsemer de pralinettes.",
      "Pulvériser au pistolet (appareil couverture 66 %) à 32 °C pour l'aspect velours. Laisser cristalliser 5 heures.",
      "Détailler en bûchettes de 3 cm. Enrober de couverture noir 66 %.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson — tablage + pistolet" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "fruits_a_coque_noisette"],
    tags: ["bûchette", "praliné", "noisette", "agrumes", "citron", "orange", "confiserie", "pistolet"],
    parfum_principal: "noisette",
    note_concepteur: "Les zestes confits doivent être finement hachés (< 3 mm) pour ne pas perturber l'homogénéité du dressage à la poche. La phase de tablage à 30 °C est indispensable pour que le praliné soit à point avant dressage.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 79, chef: _CHEF_LN1 },
  },

  {
    id: "cerises-kirsch-ln1",
    nom: "Les Cerises au kirsch",
    categorie: "bonbons",
    sous_categorie: "bonbon_moule",
    description: "Bonbon moulé classique : griotte à l'alcool dans une coque chocolat noir, garnie de fondant pâtissier au kirsch. Obturation double, démoulage 24 heures pour brillant parfait.",
    masse_totale_g: 1550,
    ingredients: [
      { nom: "Griottes à l'alcool (égouttées)", g: 1000, pct: 64, role: "fruit"   },
      { nom: "Fondant pâtissier",               g:  500, pct: 33, role: "sucrant" },
      { nom: "Kirsch à 60°",                    g:   50, pct:  3, role: "parfum"  },
    ],
    procede: [
      "Chemiser les moules polycarbonate de couverture noir 66 % tempérée. Ébarber, laisser cristalliser.",
      "Déposer une griotte bien égouttée dans chaque alvéole.",
      "Détendre le fondant avec le kirsch. Tempérer sans dépasser 31 °C. Garnir les moules à 2 mm du bord.",
      "Laisser croûter 10 heures à l'air. Obturer une première fois au pistolet à chocolat. Cristalliser, ébarber.",
      "Obturer une seconde fois à la couverture noir 66 %. Laisser cristalliser. Démouler 24 heures après pour beau brillant.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson — moulage chocolat" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["cerise", "kirsch", "bonbon moulé", "fondant", "polycarbonate", "confiserie", "liqueur"],
    parfum_principal: "cerise",
    note_concepteur: "Les griottes doivent être parfaitement égouttées — l'alcool résiduel dissoudrait le fondant. Le fondant ne doit pas dépasser 31 °C lors du tempérage pour éviter la liquéfaction prématurée. L'obturation double garantit l'étanchéité sans que le kirsch ne migre dans la coque.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 80, chef: _CHEF_LN1 },
  },

  {
    id: "mendiant-ln1",
    nom: "Le Mendiant",
    categorie: "bonbons",
    sous_categorie: "mendiant",
    description: "Disque de couverture noir 66 % garni avant cristallisation d'une pistache, une noisette, un cube d'orange confite et un cube d'ananas confit. Moulé en Flexipan® 2 cm.",
    masse_totale_g: 700,
    ingredients: [
      { nom: "Couverture noir 66 %",      g: 200, pct: 29, role: "parfum"  },
      { nom: "Orange confite (cubes)",    g: 150, pct: 21, role: "fruit"   },
      { nom: "Ananas confit (cubes)",     g: 150, pct: 21, role: "fruit"   },
      { nom: "Pistaches vernies",         g: 100, pct: 14, role: "parfum"  },
      { nom: "Noisettes caramélisées",    g: 100, pct: 15, role: "parfum"  },
    ],
    procede: [
      "Tempérer la couverture noir 66 %. Garnir le fond des moules Flexipan® ronds (Ø 2 cm) ou polycarbonate.",
      "Avant cristallisation, disposer sur chaque disque : 1 pistache vernie, 1 noisette caramélisée, 1 cube d'orange et 1 cube d'ananas.",
      "Laisser cristalliser 2 heures. Démouler délicatement.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson — moulage tempérage" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "fruits_a_coque_noisette", "fruits_a_coque_pistache"],
    tags: ["mendiant", "chocolat noir", "pistache", "noisette", "orange confite", "ananas confit", "confiserie"],
    parfum_principal: null,
    note_concepteur: "Les pistaches sont vernies à la gomme arabique (recette p. 51) avant utilisation pour préserver leur couleur et éviter le verdissement. L'ordre de disposition sur le disque suit la tradition mendiant : les 4 fruits représentent les 4 ordres mendiants.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 81, chef: _CHEF_LN1 },
  },

  {
    id: "chardon-grand-marnier-ln1",
    nom: "Le Chardon Grand Marnier",
    categorie: "bonbons",
    sous_categorie: "bonbon_praline",
    description: "Pâte d'amandes orange enrobant une perle de liqueur Grand Marnier, roulée en boule puis trempée couverture noir 66 % et roulée sur crible pour l'aspect « chardon ». Technique Lenôtre.",
    masse_totale_g: 1175,
    ingredients: [
      { nom: "Pâte d'amandes (60 %)",          g: 1000, pct: 85, role: "parfum"  },
      { nom: "Perles de liqueur Grand Marnier", g:  150, pct: 13, role: "parfum"  },
      { nom: "Arôme naturel orange",            g:   20, pct:  2, role: "parfum"  },
      { nom: "Colorant alimentaire orange",     g:    5, pct:  0, role: "parfum"  },
    ],
    procede: [
      "Parfumer la pâte d'amandes avec l'arôme orange. Colorer en orange pastel.",
      "Abaisser à 4 mm. Détailler des carrés de 30 mm à la guitare.",
      "Enrober chaque perle de liqueur Grand Marnier d'un carré de pâte d'amandes. Bouler correctement.",
      "Enrober de couverture noir 66 % tempérée.",
      "Rouler aussitôt sur crible ou grille d'enrobeuse pour obtenir l'aspect chardon irrégulier.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson — assemblage" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "fruits_a_coque_amande"],
    tags: ["chardon", "Grand Marnier", "pâte d'amandes", "liqueur", "bonbon", "confiserie"],
    parfum_principal: "orange",
    note_concepteur: "Les perles de liqueur Grand Marnier sont coulées en coffret amidon (recette tome 2 p. 104). Le boulage doit être parfait pour éviter que la liqueur ne percole à travers la pâte d'amandes pendant la cristallisation. Le passage sur crible doit être immédiat après trempage.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 82, chef: _CHEF_LN1 },
  },

  {
    id: "quatre-freres-ln1",
    nom: "Les Quatre frères",
    categorie: "bonbons",
    sous_categorie: "rocher",
    description: "Quatre noisettes caramélisées assemblées en pyramide, collées au chocolat noir, montées sur pastille, pistolet velours à 32 °C, enrobées noir 66 %. Confiserie de prestige Lenôtre.",
    masse_totale_g: 1090,
    ingredients: [
      { nom: "Noisettes grillées",    g: 600, pct: 56, role: "parfum"  },
      { nom: "Sucre semoule",         g: 220, pct: 20, role: "sucrant" },
      { nom: "Couverture noir 66 %",  g: 200, pct: 18, role: "parfum"  },
      { nom: "Eau",                   g:  70, pct:  6, role: "eau"     },
    ],
    procede: [
      "Cuire le sucre, l'eau et la vanille grattée à 115 °C. Y ajouter les noisettes.",
      "Sablage, puis caramélisation sur feu doux. Séparer les noisettes sur feuille Exopat®. Refroidir.",
      "Assembler 4 noisettes en pyramide, collées avec un point de couverture noir 66 % tempérée.",
      "Réaliser des pastilles (chablon rond Ø 2,5 cm) de couverture noir. Coller les pyramides sur les pastilles.",
      "Pulvériser au pistolet (appareil noir) à 32 °C pour protéger de l'humidité.",
      "Enrober de couverture noir 66 % tempérée.",
    ],
    cuisson: { temperature_c: 115, duree_min: null, mode: "casserole — sirop 115 °C puis caramélisation" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "fruits_a_coque_noisette"],
    tags: ["rocher", "noisettes", "pyramide", "caramel", "confiserie", "pistolet", "prestige"],
    parfum_principal: "noisette",
    note_concepteur: "1 gousse de vanille (non incluse). La phase pistolet avant enrobage final protège les pyramides de l'humidité — sans elle, les noisettes caramélisées deviendraient collantes. L'enrobage final doit se faire à la fourchette pour préserver la forme pyramidale.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 83, chef: _CHEF_LN1 },
  },

  {
    id: "othelo-ln1",
    nom: "L'Othelo",
    categorie: "bonbons",
    sous_categorie: "bonbon_praline",
    description: "Bonbon duja-moka dressé à la douille cannelée en forme ovale, couronné d'une amande chocolatée. Base trempée dans la couverture noir 66 % en ne couvrant pas l'amande. Finition nette et contrastée.",
    masse_totale_g: 560,
    ingredients: [
      { nom: "Duja noisettes-amandes", g: 250, pct: 45, role: "parfum"  },
      { nom: "Couverture lait 36 %",   g: 250, pct: 45, role: "parfum"  },
      { nom: "Amandes chocolatées",    g:  50, pct:  9, role: "parfum"  },
      { nom: "Pâte moka",              g:  10, pct:  1, role: "parfum"  },
    ],
    procede: [
      "Chauffer le duja, la couverture lait 36 % et la pâte moka à 40 °C. Tabler sur marbre à 30 °C.",
      "À la poche avec douille cannelée, dresser des bonbons ovales sur papier cuisson.",
      "Poser une amande chocolatée sur chacun. Laisser cristalliser 10 heures.",
      "Tremper la base dans la couverture noir 66 % tempérée — ne pas couvrir l'amande.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson — tablage" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "fruits_a_coque_noisette", "fruits_a_coque_amande"],
    tags: ["duja", "café", "moka", "bonbon praline", "amande chocolatée", "confiserie", "ovale"],
    parfum_principal: "café",
    note_concepteur: "Le tablage à 30 °C est critique pour le duja — trop chaud et la pâte coule, trop froid et le dressage est impossible. La pâte moka (10 g seulement) parfume subtilement sans dominer. Le trempage de la base uniquement crée le contraste visuel caractéristique de l'Othelo.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 84, chef: _CHEF_LN1 },
  },

  {
    id: "aphrodite-ln1",
    nom: "L'Aphrodite",
    categorie: "bonbons",
    sous_categorie: "rocher",
    description: "Rocher confiserie : amandes bâtonnets caramélisées, pistaches vertes et raisins cognac enrobés de couverture noir 66 %. Dressé en forme irrégulière à la cuillère ou en moule Flexipan®.",
    masse_totale_g: 1050,
    ingredients: [
      { nom: "Amandes bâtonnets caramélisées", g: 500, pct: 47, role: "parfum"  },
      { nom: "Couverture noir 66 %",           g: 350, pct: 33, role: "parfum"  },
      { nom: "Pistaches vertes",               g: 100, pct: 10, role: "parfum"  },
      { nom: "Raisins blonds macérés au cognac",g: 100, pct: 10, role: "fruit"   },
    ],
    procede: [
      "Tempérer les amandes bâtonnets caramélisées à 30 °C. Égoutter soigneusement les raisins.",
      "Ajouter pistaches, raisins égouttés et couverture noir 66 % à point. Bien mélanger.",
      "Dresser en forme de rocher à la cuillère sur feuille guitare ou dans des moules Flexipan® pour plus de régularité.",
      "Laisser cristalliser complètement avant de démouler ou décrocher.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson — tablage" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "fruits_a_coque_amande", "fruits_a_coque_pistache"],
    tags: ["rocher", "amandes", "pistaches", "cognac", "raisins", "chocolat noir", "confiserie"],
    parfum_principal: "amande",
    note_concepteur: "Les raisins macérés au cognac doivent être parfaitement égouttés — l'alcool résiduel empêcherait la cristallisation du chocolat. Tempérer les amandes caramélisées séparément avant de les incorporer au chocolat pour éviter une montée en température brutale.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 85, chef: _CHEF_LN1 },
  },

];
