const _SRC_KB = "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf";
const _CHEF_KB = "Karim Bourgi";

export const RECETTES_CARAMELS = [

  /* ── Karim Bourgi — Caramels ─────────────────────────────────────────── */

  {
    id: "caramel-semi-liquide-kb",
    nom: "Caramel semi-liquide vanille",
    categorie: "caramels",
    sous_categorie: "caramel_sauce",
    description: "Caramel cuit à 105°C, déglacé crème-lait vanillé, monté au beurre. Texture nappante qui reste coulante à froid. Durée de conservation 14 jours.",
    masse_totale_g: 266,
    ingredients: [
      { nom: "Sucre semoule",         g: 45, pct: 17, role: "sucrant"  },
      { nom: "Sirop de glucose",      g: 48, pct: 18, role: "sucrant"  },
      { nom: "Crème liquide 35%",     g: 93, pct: 35, role: "mg"       },
      { nom: "Lait 3.2%",             g: 23, pct:  9, role: "eau"      },
      { nom: "Sirop de glucose (2)",  g: 23, pct:  9, role: "sucrant"  },
      { nom: "Sel",                   g:  1, pct:  0, role: "assaisonm"},
      { nom: "Beurre 82%",            g: 33, pct: 12, role: "mg"       },
    ],
    procede: [
      "Mélanger la crème, le lait, le glucose (2) et la vanille grattée dans une casserole. Chauffer jusqu'à dissolution du glucose. Réserver au chaud à couvert.",
      "Dans une autre casserole, caraméliser à sec le sucre et le glucose (1) à 185°C sans remuer. Surveiller la couleur (caramel ambré clair).",
      "Hors du feu, verser la crème chaude en deux fois en remuant vigoureusement au fouet — attention aux projections.",
      "Remettre sur le feu, cuire à 105°C.",
      "Hors du feu, chinoiser dans un récipient et laisser refroidir à 70°C.",
      "Incorporer le beurre coupé en cubes au mixeur plongeant jusqu'à émulsion lisse.",
      "Couvrir au contact. Laisser refroidir à température ambiante. Conserver jusqu'à 14 jours au réfrigérateur.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["caramel", "vanille", "sauce", "garnissage", "tartlette"],
    parfum_principal: "caramel",
    note_concepteur: "Vanille : 1 gousse (non incluse dans la masse totale). Cuire le premier glucose avec le sucre jusqu'à 185°C — température critique pour la note ambrée. Un caramel trop court manque de profondeur.",
    source_interne: { fichier_pdf: _SRC_KB, page: 63, chef: _CHEF_KB },
  },

  {
    id: "caramel-mou-kb",
    nom: "Caramel mou à la vanille",
    categorie: "caramels",
    sous_categorie: "caramel_mou",
    description: "Caramel mou texture fondante, stabilisé à la gélatine et à l'acide citrique pour éviter la recristallisation. Idéal en garniture de cookie ou fond de tarte.",
    masse_totale_g: 280,
    ingredients: [
      { nom: "Sirop de glucose",       g:  40, pct: 14, role: "sucrant"  },
      { nom: "Sucre semoule",          g:  40, pct: 14, role: "sucrant"  },
      { nom: "Crème liquide 35%",      g: 113, pct: 40, role: "mg"       },
      { nom: "Eau",                    g:  17, pct:  6, role: "eau"      },
      { nom: "Beurre 82%",             g:  35, pct: 13, role: "mg"       },
      { nom: "Sel",                    g:   1, pct:  0, role: "assaisonm"},
      { nom: "Masse gélatine 200 bloom", g: 10, pct:  4, role: "gelifiant"},
      { nom: "Lait concentré sucré",   g:  23, pct:  8, role: "sucrant"  },
      { nom: "Solution acide citrique", g: 0.7, pct: 0, role: "stabilisant"},
    ],
    procede: [
      "Chauffer la crème, le lait concentré sucré, le beurre, le sel et les graines de vanille à 90°C. Réserver à couvert.",
      "Dans une autre casserole, porter l'eau, le sucre et le glucose à ébullition puis cuire à 185–187°C en remuant.",
      "Hors du feu, incorporer la moitié de la crème chaude en remuant, remettre le feu puis verser le reste.",
      "Recuire à 105°C en remuant.",
      "Hors du feu, ajouter la solution d'acide citrique et la masse gélatine. Mélanger.",
      "Chinoiser dans un récipient. Mixer au plongeant jusqu'à texture lisse.",
      "Couvrir au contact. Laisser stabiliser à température ambiante minimum 6h, idéalement une nuit.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["caramel mou", "vanille", "cookie", "garnissage", "tarte"],
    parfum_principal: "caramel",
    note_concepteur: "Solution acide citrique : acide citrique + eau 1:1. Vanille : 1/2 gousse (non incluse dans la masse totale). La masse gélatine se prépare : 1g gélatine + 6g eau froide.",
    source_interne: { fichier_pdf: _SRC_KB, page: 70, chef: _CHEF_KB },
  },

  /* ── Karim Bourgi — Pralinés ─────────────────────────────────────────── */

  {
    id: "praline-pistache-amande-kb",
    nom: "Praliné pistache-amande",
    categorie: "caramels",
    sous_categorie: "praline",
    description: "Praliné artisanal aux pistaches Antep et amandes entières, caramelisé à sec. Texture pâte onctueuse. Pistaches Antep légèrement citronnées.",
    masse_totale_g: 502,
    ingredients: [
      { nom: "Pistaches Antep",    g: 210, pct: 42, role: "parfum"  },
      { nom: "Amandes entières",   g:  90, pct: 18, role: "parfum"  },
      { nom: "Sucre semoule",      g: 200, pct: 40, role: "sucrant" },
      { nom: "Sel",                g:   2, pct:  0, role: "assaisonm"},
    ],
    procede: [
      "Étaler les pistaches et les amandes sur un tapis silicone ou papier cuisson. Saupoudrer de sel.",
      "Dans une casserole, faire fondre le sucre à sec à feu moyen sans remuer — agiter la casserole pour un caramel uniforme.",
      "Dès coloration ambrée, verser le caramel directement sur les fruits à coque. Laisser refroidir complètement à température ambiante.",
      "Casser le caramel en morceaux et mixer au robot jusqu'à pâte lisse et homogène. Ajouter un filet d'huile neutre si nécessaire.",
      "Conserver en boîte hermétique à température ambiante.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["fruits_a_coque"],
    tags: ["praliné", "pistache", "amande", "Antep", "pâte", "garniture"],
    parfum_principal: "pistache",
    note_concepteur: "Les pistaches Antep (Gaziantep, Turquie) ont un profil légèrement citronné distinctif. Utiliser avec ou sans leurs peaux pour des nuances de couleur différentes.",
    source_interne: { fichier_pdf: _SRC_KB, page: 26, chef: _CHEF_KB },
  },

  {
    id: "praline-noisette-amande-kb",
    nom: "Praliné noisette-amande",
    categorie: "caramels",
    sous_categorie: "praline",
    description: "Praliné classique noisette-amande à part égale, caramelisé au glucose pour une texture plus souple. Note de vanille sèche.",
    masse_totale_g: 360,
    ingredients: [
      { nom: "Noisettes torréfiées",   g: 126, pct: 35, role: "parfum"  },
      { nom: "Amandes torréfiées",     g: 126, pct: 35, role: "parfum"  },
      { nom: "Sucre semoule",          g:  66, pct: 18, role: "sucrant" },
      { nom: "Sirop de glucose",       g:  40, pct: 11, role: "sucrant" },
      { nom: "Sel",                    g:   2, pct:  1, role: "assaisonm"},
    ],
    procede: [
      "Torréfier les noisettes et amandes à 140°C, 25–30 min. Laisser refroidir. Ne pas retirer la peau.",
      "Cuire le sucre et le glucose dans une casserole jusqu'à coloration ambrée (180–185°C) sans remuer.",
      "Verser le caramel sur un tapis silicone et étaler uniformément. Poser la gousse de vanille sèche pour parfumer. Laisser refroidir complètement.",
      "Mixer le caramel refroidi avec les fruits à coque torréfiés et le sel jusqu'à obtenir une pâte lisse.",
      "Mettre en poche à douille et conserver à température ambiante jusqu'à utilisation.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["fruits_a_coque"],
    tags: ["praliné", "noisette", "amande", "cookie", "garniture"],
    parfum_principal: "noisette",
    note_concepteur: "1 gousse de vanille sèche posée sur le caramel non incluse dans la masse totale. Le glucose empêche la recristallisation et donne une texture plus souple qu'un praliné tout-sucre.",
    source_interne: { fichier_pdf: _SRC_KB, page: 72, chef: _CHEF_KB },
  },

  {
    id: "praline-chocolat-lait-pecan-kb",
    nom: "Praliné pécan cadré au chocolat lait",
    categorie: "caramels",
    sous_categorie: "praline_cade",
    description: "Praliné pécan Valrhona 50% mis en cadre avec chocolat lait et beurre de cacao. Texture entre confiserie et praliné — se détaille en cubes pour insert ou décor.",
    masse_totale_g: 623,
    ingredients: [
      { nom: "Chocolat lait Valrhona Jivara 40%", g: 115, pct: 18, role: "parfum"  },
      { nom: "Praliné pécan Valrhona 50%",        g: 463, pct: 74, role: "parfum"  },
      { nom: "Beurre de cacao",                   g:  45, pct:  8, role: "mg"      },
    ],
    procede: [
      "Fondre le chocolat et le beurre de cacao à 35°C.",
      "Incorporer le praliné pécan et mélanger jusqu'à homogénéité.",
      "Réchauffer le mélange à 45°C, puis tempérer sur marbre à 25°C en travaillant avec une spatule.",
      "Couler dans le cadre, lisser à l'offset. Cristalliser à 15°C pendant 12h (ou au réfrigérateur).",
      "Détailler en cubes de 2.5×2.5 cm. Conserver au réfrigérateur.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson" },
    temperatures: { service_c: 15, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "fruits_a_coque"],
    tags: ["praliné", "pécan", "cadre", "insert", "chocolat lait", "cube"],
    parfum_principal: "pécan",
    note_concepteur: "Le tempérage sur marbre est essentiel pour obtenir une cristallisation nette sans bloom. À défaut de marbre, passer brièvement au froid après coulage.",
    source_interne: { fichier_pdf: _SRC_KB, page: 165, chef: _CHEF_KB },
  },

  {
    id: "tartinade-chocolat-noisette-kb",
    nom: "Tartinade chocolat-noisette",
    categorie: "caramels",
    sous_categorie: "pate_de_fruits_a_coque",
    description: "Tartinade artisanale 3 ingrédients : noisettes torréfiées mixées avec sucre glace et chocolat noir fondu. Simple et intense, sans additif.",
    masse_totale_g: 150,
    ingredients: [
      { nom: "Noisettes torréfiées",  g: 50, pct: 33, role: "parfum"  },
      { nom: "Sucre glace",           g: 50, pct: 33, role: "sucrant" },
      { nom: "Chocolat Caraïbe 66%",  g: 50, pct: 33, role: "parfum"  },
    ],
    procede: [
      "Torréfier les noisettes au four à 150°C, 15 min. Laisser refroidir.",
      "Mixer les noisettes refroidies et le sucre glace au robot jusqu'à pâte onctueuse.",
      "Fondre le chocolat à 45°C. Incorporer à la pâte de noisette et mixer jusqu'à texture homogène.",
      "Conserver en boîte hermétique au réfrigérateur jusqu'à 7 jours.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["fruits_a_coque"],
    tags: ["tartinade", "noisette", "chocolat noir", "babka", "garnissage", "simple"],
    parfum_principal: "noisette",
    note_concepteur: "Recette volontairement épurée — aucun lait, aucune huile ajoutée. La torréfaction des noisettes est indispensable pour développer les arômes.",
    source_interne: { fichier_pdf: _SRC_KB, page: 52, chef: _CHEF_KB },
  },

  /* ── Eddie Benghanem — Le Grand Cours de Pâtisserie ─────────────────── */

  {
    id: "caramels-beurre-sale-eb",
    nom: "Caramels au beurre salé",
    categorie: "caramels",
    sous_categorie: "caramel_confiseur",
    description: "Caramels tendres au beurre demi-sel : sucre+glucose caramélisé à 165°C, déglacé à la crème vanillée, recuit à 130°C. Découpés en carrés après 6h de refroidissement.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Sucre semoule",       g: 415, pct: 42, role: "sucrant"  },
      { nom: "Sirop de glucose",    g:  69, pct:  7, role: "sucrant"  },
      { nom: "Crème liquide 35%",   g: 220, pct: 22, role: "mg"       },
      { nom: "Fleur de sel",        g:   4, pct:  0, role: "assaisonm"},
      { nom: "Beurre demi-sel",     g: 264, pct: 26, role: "mg"       },
    ],
    procede: [
      "Porter à ébullition la crème avec la fleur de sel et les gousses de vanille. Réserver chaud.",
      "Cuire sucre et glucose dans une casserole jusqu'à caramel foncé (165°C).",
      "Hors du feu, décuire avec la crème chaude en versant doucement. Mélanger.",
      "Remettre sur le feu et cuire jusqu'à 130°C sans cesser de remuer.",
      "Ajouter le beurre hors du feu. Mélanger.",
      "Verser dans un cadre 34×8 cm sur tapis silicone. Refroidir 6h à température ambiante.",
      "Couper en carrés ou rectangles. Emballer dans des papiers à bonbons.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole — caramel 165°C puis 130°C" },
    temperatures: { service_c: 18, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["caramel", "beurre salé", "confiserie", "bonbon", "cadre"],
    parfum_principal: "caramel",
    note_concepteur: "2 gousses de vanille Bourbon (non incluses). La cuisson à 130°C après déglaçage détermine la fermeté — plus la température est haute, plus le caramel sera ferme. Conserver au frais emballer.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 522,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "praline-noisettes-eb",
    nom: "Praliné aux noisettes",
    categorie: "caramels",
    sous_categorie: "praline",
    description: "Praliné noisettes maison : sirop à 125°C sur noisettes grillées, sablage, caramélisation, refroidissement puis mixage. Texture entre granuleuse et lisse selon mixage. Pour 1kg.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Noisettes entières (avec peau)", g: 350, pct: 35, role: "parfum" },
      { nom: "Sucre semoule",                  g: 500, pct: 50, role: "sucrant"},
      { nom: "Eau",                            g: 200, pct: 20, role: "eau"    },
      { nom: "Sel",                            g:   1, pct:  0, role: "assaisonm"},
    ],
    procede: [
      "Préchauffer le four à 180°C. Griller les noisettes 8–10 min sur plaque.",
      "Cuire eau + sucre + sel dans une casserole jusqu'à 125°C.",
      "Verser les noisettes grillées dans le sirop. Sablage : remuer sans arrêt jusqu'à pellicule de sucre autour des noisettes.",
      "Poursuivre la caramélisation à feu moyen sans cesser de remuer.",
      "Quand le caramel devient foncé et qu'une fumée se dégage, débarrasser sur papier cuisson. Refroidir.",
      "Mixer grossièrement puis jusqu'à pâte lisse et homogène.",
      "Conserver en récipient hermétique au sec.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole — sirop 125°C puis caramélisation" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["fruits_a_coque"],
    tags: ["praliné", "noisette", "maison", "pâte", "confiserie", "entremets"],
    parfum_principal: "noisette",
    note_concepteur: "Plus le praliné est torréfié, plus l'arôme se développe et moins il est sucré. Mixer jusqu'à texture granuleuse pour praliné, ou lisse pour pâte de praliné. Les deux conservent au sec à température ambiante.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 528,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "praline-amandes-eb",
    nom: "Praliné aux amandes",
    categorie: "caramels",
    sous_categorie: "praline",
    description: "Praliné amandes maison : même technique que le praliné noisettes (sablage + caramélisation + mixage). Goût plus doux et légèrement amer. Pour Paris-Brest, crèmes au beurre.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Amandes entières brutes", g: 350, pct: 35, role: "parfum" },
      { nom: "Sucre semoule",           g: 500, pct: 50, role: "sucrant"},
      { nom: "Eau",                     g: 200, pct: 20, role: "eau"    },
      { nom: "Sel",                     g:   1, pct:  0, role: "assaisonm"},
    ],
    procede: [
      "Torréfier les amandes 8–10 min à 180°C.",
      "Cuire eau + sucre + sel à 125°C. Verser les amandes.",
      "Sablage : remuer sans arrêt. Poursuivre jusqu'à caramel foncé.",
      "Débarrasser sur papier cuisson. Refroidir. Mixer jusqu'à pâte.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole — 125°C puis caramélisation" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["fruits_a_coque"],
    tags: ["praliné", "amande", "maison", "pâte", "Paris-Brest", "confiserie"],
    parfum_principal: "amande",
    note_concepteur: "Même technique que le praliné noisettes. L'amande donne une pâte plus claire et moins aromatique que la noisette mais plus polyvalente pour les desserts délicats.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 529,
      chef: "Eddie Benghanem",
    },
  },
];