const _SRC_KB  = "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf";
const _CHEF_KB = "Karim Bourgi";

const _SRC_LN1  = "Chocolats et сonfiserie de l ecole Lenotre T1.pdf";
const _CHEF_LN1 = "François Legras & Stéphane Glacier";

const _SRC_LN2  = "Chocolats et сonfiserie de l ecole Lenotre T2.pdf";
const _CHEF_LN2 = "François Legras & Stéphane Glacier";

export const RECETTES_CARAMELS = [

  /* ── Karim Bourgi — Caramels ─────────────────────────────────────────── */

  {
    id: "caramel-semi-liquide-kb",
    nom: "Caramel semi-liquide vanille",
    categorie: "caramels",
    sous_categorie: "caramel_sauce",
    description: "Caramel cuit à 105°C, déglacé crème-lait vanillé, monté au beurre. Texture nappante qui reste coulante à froid. Durée de conservation 14 jours.",
    masse_totale_g: 266,
    ingredients: [
      { nom: "Sucre semoule",         g: 45, pct: 17, role: "sucrant"  },
      { nom: "Sirop de glucose",      g: 48, pct: 18, role: "sucrant"  },
      { nom: "Crème liquide 35%",     g: 93, pct: 35, role: "mg"       },
      { nom: "Lait 3.2%",             g: 23, pct:  9, role: "eau"      },
      { nom: "Sirop de glucose (2)",  g: 23, pct:  9, role: "sucrant"  },
      { nom: "Sel",                   g:  1, pct:  0, role: "assaisonm"},
      { nom: "Beurre 82%",            g: 33, pct: 12, role: "mg"       },
    ],
    procede: [
      "Mélanger la crème, le lait, le glucose (2) et la vanille grattée dans une casserole. Chauffer jusqu'à dissolution du glucose. Réserver au chaud à couvert.",
      "Dans une autre casserole, caraméliser à sec le sucre et le glucose (1) à 185°C sans remuer. Surveiller la couleur (caramel ambré clair).",
      "Hors du feu, verser la crème chaude en deux fois en remuant vigoureusement au fouet — attention aux projections.",
      "Remettre sur le feu, cuire à 105°C.",
      "Hors du feu, chinoiser dans un récipient et laisser refroidir à 70°C.",
      "Incorporer le beurre coupé en cubes au mixeur plongeant jusqu'à émulsion lisse.",
      "Couvrir au contact. Laisser refroidir à température ambiante. Conserver jusqu'à 14 jours au réfrigérateur.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["caramel", "vanille", "sauce", "garnissage", "tartlette"],
    parfum_principal: "caramel",
    note_concepteur: "Vanille : 1 gousse (non incluse dans la masse totale). Cuire le premier glucose avec le sucre jusqu'à 185°C — température critique pour la note ambrée. Un caramel trop court manque de profondeur.",
    source_interne: { fichier_pdf: _SRC_KB, page: 63, chef: _CHEF_KB },
  },

  {
    id: "caramel-mou-kb",
    nom: "Caramel mou à la vanille",
    categorie: "caramels",
    sous_categorie: "caramel_mou",
    description: "Caramel mou texture fondante, stabilisé à la gélatine et à l'acide citrique pour éviter la recristallisation. Idéal en garniture de cookie ou fond de tarte.",
    masse_totale_g: 280,
    ingredients: [
      { nom: "Sirop de glucose",       g:  40, pct: 14, role: "sucrant"  },
      { nom: "Sucre semoule",          g:  40, pct: 14, role: "sucrant"  },
      { nom: "Crème liquide 35%",      g: 113, pct: 40, role: "mg"       },
      { nom: "Eau",                    g:  17, pct:  6, role: "eau"      },
      { nom: "Beurre 82%",             g:  35, pct: 13, role: "mg"       },
      { nom: "Sel",                    g:   1, pct:  0, role: "assaisonm"},
      { nom: "Masse gélatine 200 bloom", g: 10, pct:  4, role: "gelifiant"},
      { nom: "Lait concentré sucré",   g:  23, pct:  8, role: "sucrant"  },
      { nom: "Solution acide citrique", g: 0.7, pct: 0, role: "stabilisant"},
    ],
    procede: [
      "Chauffer la crème, le lait concentré sucré, le beurre, le sel et les graines de vanille à 90°C. Réserver à couvert.",
      "Dans une autre casserole, porter l'eau, le sucre et le glucose à ébullition puis cuire à 185–187°C en remuant.",
      "Hors du feu, incorporer la moitié de la crème chaude en remuant, remettre le feu puis verser le reste.",
      "Recuire à 105°C en remuant.",
      "Hors du feu, ajouter la solution d'acide citrique et la masse gélatine. Mélanger.",
      "Chinoiser dans un récipient. Mixer au plongeant jusqu'à texture lisse.",
      "Couvrir au contact. Laisser stabiliser à température ambiante minimum 6h, idéalement une nuit.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["caramel mou", "vanille", "cookie", "garnissage", "tarte"],
    parfum_principal: "caramel",
    note_concepteur: "Solution acide citrique : acide citrique + eau 1:1. Vanille : 1/2 gousse (non incluse dans la masse totale). La masse gélatine se prépare : 1g gélatine + 6g eau froide.",
    source_interne: { fichier_pdf: _SRC_KB, page: 70, chef: _CHEF_KB },
  },

  /* ── Karim Bourgi — Pralinés ─────────────────────────────────────────── */

  {
    id: "praline-pistache-amande-kb",
    nom: "Praliné pistache-amande",
    categorie: "caramels",
    sous_categorie: "praline",
    description: "Praliné artisanal aux pistaches Antep et amandes entières, caramelisé à sec. Texture pâte onctueuse. Pistaches Antep légèrement citronnées.",
    masse_totale_g: 502,
    ingredients: [
      { nom: "Pistaches Antep",    g: 210, pct: 42, role: "parfum"  },
      { nom: "Amandes entières",   g:  90, pct: 18, role: "parfum"  },
      { nom: "Sucre semoule",      g: 200, pct: 40, role: "sucrant" },
      { nom: "Sel",                g:   2, pct:  0, role: "assaisonm"},
    ],
    procede: [
      "Étaler les pistaches et les amandes sur un tapis silicone ou papier cuisson. Saupoudrer de sel.",
      "Dans une casserole, faire fondre le sucre à sec à feu moyen sans remuer — agiter la casserole pour un caramel uniforme.",
      "Dès coloration ambrée, verser le caramel directement sur les fruits à coque. Laisser refroidir complètement à température ambiante.",
      "Casser le caramel en morceaux et mixer au robot jusqu'à pâte lisse et homogène. Ajouter un filet d'huile neutre si nécessaire.",
      "Conserver en boîte hermétique à température ambiante.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["fruits_a_coque"],
    tags: ["praliné", "pistache", "amande", "Antep", "pâte", "garniture"],
    parfum_principal: "pistache",
    note_concepteur: "Les pistaches Antep (Gaziantep, Turquie) ont un profil légèrement citronné distinctif. Utiliser avec ou sans leurs peaux pour des nuances de couleur différentes.",
    source_interne: { fichier_pdf: _SRC_KB, page: 26, chef: _CHEF_KB },
  },

  {
    id: "praline-noisette-amande-kb",
    nom: "Praliné noisette-amande",
    categorie: "caramels",
    sous_categorie: "praline",
    description: "Praliné classique noisette-amande à part égale, caramelisé au glucose pour une texture plus souple. Note de vanille sèche.",
    masse_totale_g: 360,
    ingredients: [
      { nom: "Noisettes torréfiées",   g: 126, pct: 35, role: "parfum"  },
      { nom: "Amandes torréfiées",     g: 126, pct: 35, role: "parfum"  },
      { nom: "Sucre semoule",          g:  66, pct: 18, role: "sucrant" },
      { nom: "Sirop de glucose",       g:  40, pct: 11, role: "sucrant" },
      { nom: "Sel",                    g:   2, pct:  1, role: "assaisonm"},
    ],
    procede: [
      "Torréfier les noisettes et amandes à 140°C, 25–30 min. Laisser refroidir. Ne pas retirer la peau.",
      "Cuire le sucre et le glucose dans une casserole jusqu'à coloration ambrée (180–185°C) sans remuer.",
      "Verser le caramel sur un tapis silicone et étaler uniformément. Poser la gousse de vanille sèche pour parfumer. Laisser refroidir complètement.",
      "Mixer le caramel refroidi avec les fruits à coque torréfiés et le sel jusqu'à obtenir une pâte lisse.",
      "Mettre en poche à douille et conserver à température ambiante jusqu'à utilisation.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["fruits_a_coque"],
    tags: ["praliné", "noisette", "amande", "cookie", "garniture"],
    parfum_principal: "noisette",
    note_concepteur: "1 gousse de vanille sèche posée sur le caramel non incluse dans la masse totale. Le glucose empêche la recristallisation et donne une texture plus souple qu'un praliné tout-sucre.",
    source_interne: { fichier_pdf: _SRC_KB, page: 72, chef: _CHEF_KB },
  },

  {
    id: "praline-chocolat-lait-pecan-kb",
    nom: "Praliné pécan cadré au chocolat lait",
    categorie: "caramels",
    sous_categorie: "praline_cade",
    description: "Praliné pécan Valrhona 50% mis en cadre avec chocolat lait et beurre de cacao. Texture entre confiserie et praliné — se détaille en cubes pour insert ou décor.",
    masse_totale_g: 623,
    ingredients: [
      { nom: "Chocolat lait Valrhona Jivara 40%", g: 115, pct: 18, role: "parfum"  },
      { nom: "Praliné pécan Valrhona 50%",        g: 463, pct: 74, role: "parfum"  },
      { nom: "Beurre de cacao",                   g:  45, pct:  8, role: "mg"      },
    ],
    procede: [
      "Fondre le chocolat et le beurre de cacao à 35°C.",
      "Incorporer le praliné pécan et mélanger jusqu'à homogénéité.",
      "Réchauffer le mélange à 45°C, puis tempérer sur marbre à 25°C en travaillant avec une spatule.",
      "Couler dans le cadre, lisser à l'offset. Cristalliser à 15°C pendant 12h (ou au réfrigérateur).",
      "Détailler en cubes de 2.5×2.5 cm. Conserver au réfrigérateur.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson" },
    temperatures: { service_c: 15, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "fruits_a_coque"],
    tags: ["praliné", "pécan", "cadre", "insert", "chocolat lait", "cube"],
    parfum_principal: "pécan",
    note_concepteur: "Le tempérage sur marbre est essentiel pour obtenir une cristallisation nette sans bloom. À défaut de marbre, passer brièvement au froid après coulage.",
    source_interne: { fichier_pdf: _SRC_KB, page: 165, chef: _CHEF_KB },
  },

  {
    id: "tartinade-chocolat-noisette-kb",
    nom: "Tartinade chocolat-noisette",
    categorie: "caramels",
    sous_categorie: "pate_de_fruits_a_coque",
    description: "Tartinade artisanale 3 ingrédients : noisettes torréfiées mixées avec sucre glace et chocolat noir fondu. Simple et intense, sans additif.",
    masse_totale_g: 150,
    ingredients: [
      { nom: "Noisettes torréfiées",  g: 50, pct: 33, role: "parfum"  },
      { nom: "Sucre glace",           g: 50, pct: 33, role: "sucrant" },
      { nom: "Chocolat Caraïbe 66%",  g: 50, pct: 33, role: "parfum"  },
    ],
    procede: [
      "Torréfier les noisettes au four à 150°C, 15 min. Laisser refroidir.",
      "Mixer les noisettes refroidies et le sucre glace au robot jusqu'à pâte onctueuse.",
      "Fondre le chocolat à 45°C. Incorporer à la pâte de noisette et mixer jusqu'à texture homogène.",
      "Conserver en boîte hermétique au réfrigérateur jusqu'à 7 jours.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["fruits_a_coque"],
    tags: ["tartinade", "noisette", "chocolat noir", "babka", "garnissage", "simple"],
    parfum_principal: "noisette",
    note_concepteur: "Recette volontairement épurée — aucun lait, aucune huile ajoutée. La torréfaction des noisettes est indispensable pour développer les arômes.",
    source_interne: { fichier_pdf: _SRC_KB, page: 52, chef: _CHEF_KB },
  },

  /* ── Eddie Benghanem — Le Grand Cours de Pâtisserie ─────────────────── */

  {
    id: "caramels-beurre-sale-eb",
    nom: "Caramels au beurre salé",
    categorie: "caramels",
    sous_categorie: "caramel_confiseur",
    description: "Caramels tendres au beurre demi-sel : sucre+glucose caramélisé à 165°C, déglacé à la crème vanillée, recuit à 130°C. Découpés en carrés après 6h de refroidissement.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Sucre semoule",       g: 415, pct: 42, role: "sucrant"  },
      { nom: "Sirop de glucose",    g:  69, pct:  7, role: "sucrant"  },
      { nom: "Crème liquide 35%",   g: 220, pct: 22, role: "mg"       },
      { nom: "Fleur de sel",        g:   4, pct:  0, role: "assaisonm"},
      { nom: "Beurre demi-sel",     g: 264, pct: 26, role: "mg"       },
    ],
    procede: [
      "Porter à ébullition la crème avec la fleur de sel et les gousses de vanille. Réserver chaud.",
      "Cuire sucre et glucose dans une casserole jusqu'à caramel foncé (165°C).",
      "Hors du feu, décuire avec la crème chaude en versant doucement. Mélanger.",
      "Remettre sur le feu et cuire jusqu'à 130°C sans cesser de remuer.",
      "Ajouter le beurre hors du feu. Mélanger.",
      "Verser dans un cadre 34×8 cm sur tapis silicone. Refroidir 6h à température ambiante.",
      "Couper en carrés ou rectangles. Emballer dans des papiers à bonbons.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole — caramel 165°C puis 130°C" },
    temperatures: { service_c: 18, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["caramel", "beurre salé", "confiserie", "bonbon", "cadre"],
    parfum_principal: "caramel",
    note_concepteur: "2 gousses de vanille Bourbon (non incluses). La cuisson à 130°C après déglaçage détermine la fermeté — plus la température est haute, plus le caramel sera ferme. Conserver au frais emballer.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 522,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "praline-noisettes-eb",
    nom: "Praliné aux noisettes",
    categorie: "caramels",
    sous_categorie: "praline",
    description: "Praliné noisettes maison : sirop à 125°C sur noisettes grillées, sablage, caramélisation, refroidissement puis mixage. Texture entre granuleuse et lisse selon mixage. Pour 1kg.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Noisettes entières (avec peau)", g: 350, pct: 35, role: "parfum" },
      { nom: "Sucre semoule",                  g: 500, pct: 50, role: "sucrant"},
      { nom: "Eau",                            g: 200, pct: 20, role: "eau"    },
      { nom: "Sel",                            g:   1, pct:  0, role: "assaisonm"},
    ],
    procede: [
      "Préchauffer le four à 180°C. Griller les noisettes 8–10 min sur plaque.",
      "Cuire eau + sucre + sel dans une casserole jusqu'à 125°C.",
      "Verser les noisettes grillées dans le sirop. Sablage : remuer sans arrêt jusqu'à pellicule de sucre autour des noisettes.",
      "Poursuivre la caramélisation à feu moyen sans cesser de remuer.",
      "Quand le caramel devient foncé et qu'une fumée se dégage, débarrasser sur papier cuisson. Refroidir.",
      "Mixer grossièrement puis jusqu'à pâte lisse et homogène.",
      "Conserver en récipient hermétique au sec.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole — sirop 125°C puis caramélisation" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["fruits_a_coque"],
    tags: ["praliné", "noisette", "maison", "pâte", "confiserie", "entremets"],
    parfum_principal: "noisette",
    note_concepteur: "Plus le praliné est torréfié, plus l'arôme se développe et moins il est sucré. Mixer jusqu'à texture granuleuse pour praliné, ou lisse pour pâte de praliné. Les deux conservent au sec à température ambiante.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 528,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "praline-amandes-eb",
    nom: "Praliné aux amandes",
    categorie: "caramels",
    sous_categorie: "praline",
    description: "Praliné amandes maison : même technique que le praliné noisettes (sablage + caramélisation + mixage). Goût plus doux et légèrement amer. Pour Paris-Brest, crèmes au beurre.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Amandes entières brutes", g: 350, pct: 35, role: "parfum" },
      { nom: "Sucre semoule",           g: 500, pct: 50, role: "sucrant"},
      { nom: "Eau",                     g: 200, pct: 20, role: "eau"    },
      { nom: "Sel",                     g:   1, pct:  0, role: "assaisonm"},
    ],
    procede: [
      "Torréfier les amandes 8–10 min à 180°C.",
      "Cuire eau + sucre + sel à 125°C. Verser les amandes.",
      "Sablage : remuer sans arrêt. Poursuivre jusqu'à caramel foncé.",
      "Débarrasser sur papier cuisson. Refroidir. Mixer jusqu'à pâte.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole — 125°C puis caramélisation" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["fruits_a_coque"],
    tags: ["praliné", "amande", "maison", "pâte", "Paris-Brest", "confiserie"],
    parfum_principal: "amande",
    note_concepteur: "Même technique que le praliné noisettes. L'amande donne une pâte plus claire et moins aromatique que la noisette mais plus polyvalente pour les desserts délicats.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 529,
      chef: "Eddie Benghanem",
    },
  },

  /* ── École Lenôtre T1 — Pralinés & fruits secs caramélisés ──────────── */

  {
    id: "praline-amandes-ln1",
    nom: "Praliné aux amandes",
    categorie: "caramels",
    sous_categorie: "praline",
    description: "Praliné professionnel 53 % amandes : sirop à 120 °C, sablage, caramélisation progressive. Passé 4 fois à la broyeuse à cylindres pour une texture soyeuse. Base de nombreuses confiseries Lenôtre.",
    masse_totale_g: 2250,
    ingredients: [
      { nom: "Amandes pelées grillées", g: 1200, pct: 53, role: "parfum"  },
      { nom: "Sucre cristal",           g:  800, pct: 36, role: "sucrant" },
      { nom: "Eau",                     g:  250, pct: 11, role: "eau"     },
    ],
    procede: [
      "Faire légèrement griller les amandes pelées dans un four à 150 °C.",
      "Faire cuire le sucre et l'eau à 120 °C.",
      "Y ajouter les amandes. Hors du feu, remuer vivement pour faire cristalliser le sucre autour des amandes (sablage).",
      "Remettre sur le feu et caraméliser à volonté — plus les fruits sont caramélisés, plus le goût sera prononcé.",
      "Laisser refroidir sur plaque. Éventuellement poser 2 gousses de vanille sèches pour parfumer.",
      "Broyer au mixeur le plus fin possible.",
      "Passer 4 fois à la broyeuse à cylindres en réglant les rouleaux de plus en plus fin. Homogénéiser au batteur avec feuille.",
    ],
    cuisson: { temperature_c: 120, duree_min: null, mode: "casserole — sirop 120 °C puis caramélisation" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["fruits_a_coque_amande"],
    tags: ["praliné", "amandes", "confiserie", "pâte", "chocolat", "sablage"],
    parfum_principal: "amande",
    note_concepteur: "2 gousses de vanille facultatives (non incluses dans la masse). Le ratio 53 % fruits correspond au praliné 50 % de la tradition Lenôtre. L'intensité du caramel est réglable : légèrement caramélisé pour un goût doux, plus poussé pour un praliné corsé.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 47, chef: _CHEF_LN1 },
  },

  {
    id: "praline-noisettes-ln1",
    nom: "Praliné aux noisettes",
    categorie: "caramels",
    sous_categorie: "praline",
    description: "Praliné professionnel 53 % noisettes : même technique sirop 120 °C + sablage + broyeuse cylindres que le praliné amandes. Arôme plus profond et persistant en bouche.",
    masse_totale_g: 2250,
    ingredients: [
      { nom: "Noisettes pelées grillées", g: 1200, pct: 53, role: "parfum"  },
      { nom: "Sucre cristal",             g:  800, pct: 36, role: "sucrant" },
      { nom: "Eau",                       g:  250, pct: 11, role: "eau"     },
    ],
    procede: [
      "Faire légèrement griller les noisettes pelées dans un four à 150 °C.",
      "Faire cuire le sucre et l'eau à 120 °C.",
      "Y ajouter les noisettes. Hors du feu, remuer vivement pour faire cristalliser le sucre (sablage).",
      "Remettre sur le feu et caraméliser à volonté.",
      "Laisser refroidir sur plaque. Éventuellement poser 2 gousses de vanille sèches.",
      "Broyer au mixeur, puis passer 4 fois à la broyeuse à cylindres en réglant de plus en plus fin.",
      "Homogénéiser au batteur avec feuille.",
    ],
    cuisson: { temperature_c: 120, duree_min: null, mode: "casserole — sirop 120 °C puis caramélisation" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["fruits_a_coque_noisette"],
    tags: ["praliné", "noisettes", "confiserie", "pâte", "chocolat", "sablage"],
    parfum_principal: "noisette",
    note_concepteur: "Même procédé que le praliné amandes — remplacer les amandes pelées par la même quantité de noisettes pelées grillées. La noisette prolonge l'arôme en bouche là où l'amande donne la force du goût initial.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 48, chef: _CHEF_LN1 },
  },

  {
    id: "praline-amande-noisette-ln1",
    nom: "Praliné amande-noisette",
    categorie: "caramels",
    sous_categorie: "praline",
    description: "Praliné mixte 50/50 amandes-noisettes : équilibre entre la force de l'amande et la persistance aromatique de la noisette. Praliné de référence en chocolaterie Lenôtre.",
    masse_totale_g: 2250,
    ingredients: [
      { nom: "Amandes pelées grillées",   g:  600, pct: 27, role: "parfum"  },
      { nom: "Noisettes pelées grillées", g:  600, pct: 27, role: "parfum"  },
      { nom: "Sucre cristal",             g:  800, pct: 35, role: "sucrant" },
      { nom: "Eau",                       g:  250, pct: 11, role: "eau"     },
    ],
    procede: [
      "Faire légèrement griller amandes et noisettes séparément dans un four à 150 °C.",
      "Faire cuire le sucre et l'eau à 120 °C.",
      "Y ajouter les fruits à coque mélangés. Hors du feu, sablage : remuer vivement jusqu'à cristallisation du sucre.",
      "Remettre sur le feu et caraméliser à cœur.",
      "Laisser refroidir sur plaque. Broyer au mixeur.",
      "Passer 4 fois à la broyeuse à cylindres, réglage de plus en plus fin. Homogénéiser au batteur.",
    ],
    cuisson: { temperature_c: 120, duree_min: null, mode: "casserole — sirop 120 °C puis caramélisation" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["fruits_a_coque_amande", "fruits_a_coque_noisette"],
    tags: ["praliné", "amandes", "noisettes", "mixte", "chocolaterie", "confiserie"],
    parfum_principal: "noisette",
    note_concepteur: "Ce type de praliné est fréquemment utilisé en chocolaterie : les amandes donnent la force du goût en attaque, les noisettes assurent la persistance en bouche. Proportion 50/50 validée par Lenôtre comme équilibre optimal.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 48, chef: _CHEF_LN1 },
  },

  {
    id: "amandes-caramelisees-ln1",
    nom: "Amandes caramélisées",
    categorie: "caramels",
    sous_categorie: "amandes_caramelisees",
    description: "Petites amandes entières sablées au sirop vanillé 115 °C puis caramélisées à cœur sur feu doux. Enrobage craquant et brillant. Base pour amandes chocolatées, Quatre frères, mendiant.",
    masse_totale_g: 1150,
    ingredients: [
      { nom: "Amandes brutes (petites, Provence)", g: 800, pct: 70, role: "parfum"  },
      { nom: "Sucre cristal",                      g: 260, pct: 22, role: "sucrant" },
      { nom: "Eau",                                g:  90, pct:  8, role: "eau"     },
    ],
    procede: [
      "Faire légèrement griller les amandes brutes à 150 °C sans faire craquer la peau.",
      "Faire cuire le sucre, l'eau et la vanille grattée à 115 °C.",
      "Y verser les amandes. Remuer et faire sablage : cristallisation du sucre autour des amandes.",
      "Caraméliser à cœur sur feu doux en remuant régulièrement jusqu'à beau caramel ambré.",
      "Débarrasser sur feuille Exopat® ou plaque huilée en veillant à séparer les amandes. Laisser refroidir.",
    ],
    cuisson: { temperature_c: 115, duree_min: null, mode: "casserole — sirop 115 °C puis caramélisation" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["fruits_a_coque_amande"],
    tags: ["amandes caramélisées", "sablage", "confiserie", "décor", "pralinettes", "mendiant"],
    parfum_principal: "amande",
    note_concepteur: "1 gousse de vanille facultative (non incluse dans la masse). Amandes de Provence recommandées pour leur taille régulière. La technique sablage→caramélisation est indispensable : le sablage assure l'adhérence du sucre, la caramélisation donne le craquant.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 50, chef: _CHEF_LN1 },
  },

  {
    id: "amandes-batonnets-caramelisees-ln1",
    nom: "Amandes bâtonnets caramélisées",
    categorie: "caramels",
    sous_categorie: "amandes_caramelisees",
    description: "Bâtonnets d'amandes sablés au sucre de canne et caramélisés à cœur. Format bâtonnet pour décor de bonbons et enrobage. Même technique que les amandes entières.",
    masse_totale_g: 575,
    ingredients: [
      { nom: "Amandes en bâtonnets", g: 400, pct: 70, role: "parfum"  },
      { nom: "Sucre de canne",       g: 125, pct: 22, role: "sucrant" },
      { nom: "Eau",                  g:  50, pct:  8, role: "eau"     },
    ],
    procede: [
      "Faire légèrement griller les bâtonnets d'amandes dans un four à 150 °C.",
      "Faire cuire le sucre de canne et l'eau à 115 °C. Y verser les bâtonnets.",
      "Remuer et faire sablage : cristallisation du sucre autour des bâtonnets.",
      "Caraméliser à cœur sur feu doux en remuant régulièrement.",
      "Débarrasser sur feuille Exopat®. Séparer les bâtonnets avant refroidissement complet.",
    ],
    cuisson: { temperature_c: 115, duree_min: null, mode: "casserole — sirop 115 °C puis caramélisation" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["fruits_a_coque_amande"],
    tags: ["amandes caramélisées", "bâtonnets", "décor", "confiserie", "sablage"],
    parfum_principal: "amande",
    note_concepteur: "Le sucre de canne blanc (plus raffiné que le sucre de betterave) donne un meilleur brillant et une absence d'impuretés pour le travail du sucre confiserie. Séparer rapidement les bâtonnets à la sortie du feu pour éviter les collages.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 51, chef: _CHEF_LN1 },
  },

  {
    id: "pralinettes-ln1",
    nom: "Pralinettes",
    categorie: "caramels",
    sous_categorie: "amandes_caramelisees",
    description: "Amandes hachées sablées et caramélisées. Utilisées comme décor craquant sur bonbons (bûchette agrumes), pralinés feuilletés. Format haché = surface irrégulière et craquante.",
    masse_totale_g: 1020,
    ingredients: [
      { nom: "Amandes hachées", g: 500, pct: 49, role: "parfum"  },
      { nom: "Sucre semoule",   g: 400, pct: 39, role: "sucrant" },
      { nom: "Eau",             g: 120, pct: 12, role: "eau"     },
    ],
    procede: [
      "Faire légèrement griller les amandes hachées dans un four à 150 °C.",
      "Faire cuire le sucre et l'eau à 115 °C. Y verser les amandes hachées.",
      "Remuer et faire sablage : cristallisation du sucre.",
      "Caraméliser à cœur sur feu doux en remuant régulièrement.",
      "Débarrasser sur feuille Exopat®. Laisser refroidir. Conserver au sec en boîte hermétique.",
    ],
    cuisson: { temperature_c: 115, duree_min: null, mode: "casserole — sirop 115 °C puis caramélisation" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["fruits_a_coque_amande"],
    tags: ["pralinettes", "amandes hachées", "décor", "craquant", "confiserie", "bûchette"],
    parfum_principal: "amande",
    note_concepteur: "Les pralinettes sont le format haché des amandes caramélisées. Utilisées telles quelles comme décor de surface (bûchettes agrumes, bonbons pralinés) ou concassées plus finement comme insert craquant. Se conservent 3 semaines au sec.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 52, chef: _CHEF_LN1 },
  },

  {
    id: "nougatine-ln1",
    nom: "Nougatine",
    categorie: "caramels",
    sous_categorie: "nougatine",
    description: "Nougatine classique confiserie : sucre-glucose-nougat sec cuit à 170 °C, beurre et amandes hachées blondes incorporés hors du feu. Souple à chaud, craquante à froid. Base de décors, socles et inserts.",
    masse_totale_g: 1425,
    ingredients: [
      { nom: "Sucre cristal",      g: 500, pct: 35, role: "sucrant" },
      { nom: "Amandes hachées",    g: 400, pct: 28, role: "parfum"  },
      { nom: "Glucose",            g: 400, pct: 28, role: "sucrant" },
      { nom: "Eau",                g:  50, pct:  4, role: "eau"     },
      { nom: "Nougat sec",         g:  45, pct:  3, role: "liant"   },
      { nom: "Beurre salé 3 %",    g:  30, pct:  2, role: "mg"      },
    ],
    procede: [
      "Faire griller les amandes hachées sur plaque au four jusqu'à blond clair.",
      "Faire cuire le sucre, l'eau, le glucose et le nougat sec à 170 °C.",
      "Hors du feu, ajouter le beurre puis les amandes blondes. Mélanger rapidement.",
      "Verser sur feuille Exopat® ou plaque huilée. Laisser refroidir puis détailler selon les besoins.",
      "Maintenir au four à 130 °C entre les utilisations pour la garder souple au façonnage.",
    ],
    cuisson: { temperature_c: 170, duree_min: null, mode: "casserole — caramel 170 °C" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "fruits_a_coque_amande"],
    tags: ["nougatine", "confiserie", "décor", "croustillant", "amandes", "sucre cuit"],
    parfum_principal: "caramel",
    note_concepteur: "Le nougat sec (stabilisant sucre confiserie) retarde la recristallisation et améliore la souplesse au façonnage. Peut être remplacé par une pointe de crème de tartre. La nougatine durcit rapidement — travailler vite hors du four.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 49, chef: _CHEF_LN1 },
  },

  /* ── École Lenôtre T2 — Batch 5 : caramels confiserie ───────────────── */

  {
    id: "caramel-vanille-ln2",
    nom: "Caramel vanille",
    categorie: "caramels",
    sous_categorie: "caramel_confiserie",
    description: "Caramel mou confiserie : sucre-glucose cuit à 145 °C, décuit au beurre salé, miel de lavande et crème vanillée. Recuit à 121 °C. Cadre inox 1 cm, découpé 3 × 3 cm, emballé individuellement.",
    masse_totale_g: 1300,
    ingredients: [
      { nom: "Sucre semoule",   g: 375, pct: 29, role: "sucrant" },
      { nom: "Glucose",         g: 300, pct: 23, role: "sucrant" },
      { nom: "Crème liquide",   g: 500, pct: 38, role: "mg"      },
      { nom: "Beurre salé",     g:  50, pct:  4, role: "mg"      },
      { nom: "Miel de lavande", g:  50, pct:  4, role: "sucrant" },
      { nom: "Eau",             g:  75, pct:  6, role: "eau"     },
    ],
    procede: [
      "Cuire le sucre, le glucose et l'eau à 145 °C.",
      "Faire bouillir la crème avec les gousses de vanille (Q.S.). Tenir au chaud.",
      "Décuire le sucre avec le beurre salé, puis le miel de lavande, puis la crème bouillante en 2-3 fois (ne pas descendre sous 110 °C).",
      "Remuer vivement. Faire recuire à 121 °C.",
      "Couler dans un cadre inox 1 cm sur feuille Exopat®. Laisser refroidir.",
      "Marquer avec découpoir à caramel. Couper en carrés 3 × 3 cm. Emballer individuellement.",
    ],
    cuisson: { temperature_c: 145, duree_min: null, mode: "casserole — sucre/glucose 145 °C puis recuit 121 °C" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["caramel", "vanille", "miel lavande", "beurre salé", "confiserie", "emballé", "cadre"],
    parfum_principal: "caramel",
    note_concepteur: "Vanille : 3 gousses (non incluses dans la masse). La verser en 2-3 fois pour éviter un choc thermique qui baisserait la température sous 110 °C — en dessous, le sucre se recristallise au lieu de caraméliser. Le recuit à 121 °C donne la texture ferme-fondante caractéristique du caramel confiserie (plus ferme que le caramel sauce).",
    source_interne: { fichier_pdf: _SRC_LN2, page: 99, chef: _CHEF_LN2 },
  },

  {
    id: "caramel-chocolat-ln2",
    nom: "Caramel chocolat",
    categorie: "caramels",
    sous_categorie: "caramel_confiserie",
    description: "Caramel chocolat noir : sucre-glucose cuit à 145 °C, décuit beurre-crème vanille/bicarbonate/sel, cacao pâte incorporé. Recuit à 118 °C. Cadre 1 cm, carrés 3 × 3 cm emballés.",
    masse_totale_g: 1740,
    ingredients: [
      { nom: "Sucre semoule",   g: 650, pct: 37, role: "sucrant" },
      { nom: "Crème liquide",   g: 400, pct: 23, role: "mg"      },
      { nom: "Cacao pur pâte",  g: 200, pct: 11, role: "parfum"  },
      { nom: "Beurre",          g: 275, pct: 16, role: "mg"      },
      { nom: "Glucose cristal", g:  65, pct:  4, role: "sucrant" },
      { nom: "Eau",             g: 150, pct:  9, role: "eau"     },
      { nom: "Bicarbonate de soude", g: 1, pct: 0, role: "liant" },
      { nom: "Sel fin",         g:   1, pct:  0, role: "assaisonm"},
    ],
    procede: [
      "Cuire le sucre, le glucose et l'eau à 145 °C.",
      "Faire bouillir la crème avec la vanille (Q.S.), le bicarbonate et le sel. Tenir au chaud.",
      "Décuire le sucre avec le beurre, puis la crème bouillante en 2-3 fois.",
      "Incorporer le cacao pur pâte. Faire recuire à 118 °C.",
      "Couler dans un cadre 1 cm sur feuille Exopat®. Laisser refroidir.",
      "Marquer au découpoir. Couper en carrés 3 × 3 cm. Emballer individuellement.",
    ],
    cuisson: { temperature_c: 145, duree_min: null, mode: "casserole — sucre/glucose 145 °C puis recuit 118 °C" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["caramel", "chocolat", "cacao pâte", "bicarbonate", "confiserie", "cadre", "emballé"],
    parfum_principal: "chocolat",
    note_concepteur: "Vanille : 1 gousse (non incluse). Le bicarbonate (1 g) dans la crème crée une légère effervescence au contact du caramel acide — il assouplit la texture et fonce légèrement la couleur. Recuit à 118 °C (vs 121 °C pour le caramel vanille) : le cacao pâte apporte de la matière sèche qui épaissit la masse.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 100, chef: _CHEF_LN2 },
  },

  {
    id: "caramel-gingembre-citron-orange-ln2",
    nom: "Caramel gingembre/citron/orange",
    categorie: "caramels",
    sous_categorie: "caramel_confiserie",
    description: "Caramel agrumes-épices : sucre-glucose-eau à 145 °C, crème infusée zestes citron vert, orange et gingembre confit, jus d'agrumes. Beurre de cacao incorporé. Recuit à 118 °C, cadre 1 cm, carrés 3 × 3 cm.",
    masse_totale_g: 410,
    ingredients: [
      { nom: "Crème liquide",         g: 100, pct: 24, role: "mg"      },
      { nom: "Sucre",                 g:  75, pct: 18, role: "sucrant" },
      { nom: "Jus de citron vert",    g:  45, pct: 11, role: "fruit"   },
      { nom: "Jus d'orange",          g:  45, pct: 11, role: "fruit"   },
      { nom: "Beurre",                g:  10, pct:  2, role: "mg"      },
      { nom: "Beurre de cacao",       g:  10, pct:  2, role: "mg"      },
      { nom: "Glucose",               g:  35, pct:  8, role: "sucrant" },
      { nom: "Gingembre confit haché",g:  35, pct:  8, role: "parfum"  },
      { nom: "Eau",                   g:  20, pct:  5, role: "eau"     },
      { nom: "Sucre inverti",         g:  10, pct:  2, role: "sucrant" },
    ],
    procede: [
      "Cuire le sucre, le glucose et l'eau à 145 °C.",
      "Faire bouillir la crème avec les zestes de 3 citrons verts, 3 oranges (Q.S.) et le gingembre confit. Tenir au chaud.",
      "Décuire le sucre avec le beurre, le sucre inverti, puis la crème bouillante et les jus chauds en 2-3 fois (ne pas descendre sous 110 °C).",
      "Remuer vivement. Faire recuire à 118 °C. Ajouter le beurre de cacao.",
      "Couler dans un cadre inox 1 cm sur feuille Exopat®. Laisser refroidir.",
      "Couper en carrés 3 × 3 cm. Emballer individuellement.",
    ],
    cuisson: { temperature_c: 145, duree_min: null, mode: "casserole — sucre/glucose 145 °C puis recuit 118 °C" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait"],
    tags: ["caramel", "gingembre", "citron vert", "orange", "agrumes", "confiserie", "cadre"],
    parfum_principal: "agrumes",
    note_concepteur: "Zestes de 3 citrons verts + 3 oranges (Q.S., non comptés dans la masse totale). La masse_totale est faible (recette de base du livre) — multiplier par 3 ou 4 pour une production pratique. Les jus d'agrumes s'ajoutent chauds avec la crème pour éviter un trop grand choc thermique.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 101, chef: _CHEF_LN2 },
  },

  {
    id: "caramel-pistache-ln2",
    nom: "Caramel pistache",
    categorie: "caramels",
    sous_categorie: "caramel_confiserie",
    description: "Caramel pistache : sucre-glucose cuit à 148 °C, décuit beurre salé, miel de sapin et crème. Beurre de cacao et pâte de pistache incorporés. Recuit à 121 °C, coulé en moule Flexipan®, emballé.",
    masse_totale_g: 815,
    ingredients: [
      { nom: "Sucre semoule",   g: 275, pct: 34, role: "sucrant" },
      { nom: "Crème liquide",   g: 250, pct: 31, role: "mg"      },
      { nom: "Glucose",         g: 150, pct: 18, role: "sucrant" },
      { nom: "Beurre de cacao", g:  40, pct:  5, role: "mg"      },
      { nom: "Pâte de pistache",g:  60, pct:  7, role: "parfum"  },
      { nom: "Beurre salé",     g:  15, pct:  2, role: "mg"      },
      { nom: "Miel de sapin",   g:  25, pct:  3, role: "sucrant" },
      { nom: "Eau",             g:  40, pct:  5, role: "eau"     },
    ],
    procede: [
      "Cuire le sucre, le glucose et l'eau à 148 °C.",
      "Faire bouillir la crème jusqu'à ébullition.",
      "Décuire le sucre avec le beurre salé, le miel de sapin, puis la crème bouillante en 2-3 fois.",
      "Remuer vivement. Faire recuire à 121 °C.",
      "Incorporer le beurre de cacao et la pâte de pistache.",
      "Couler dans des moules Flexipan® souples. Laisser refroidir. Démouler.",
      "Emballer chaque caramel individuellement.",
    ],
    cuisson: { temperature_c: 148, duree_min: null, mode: "casserole — sucre/glucose 148 °C puis recuit 121 °C" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "fruits_a_coque_pistache"],
    tags: ["caramel", "pistache", "miel de sapin", "beurre de cacao", "Flexipan", "confiserie"],
    parfum_principal: "pistache",
    note_concepteur: "Le miel de sapin (goût résineux distinct du miel de lavande ou fleurs) apporte une note boisée qui complexifie le caramel pistache. La pâte de pistache s'incorpore hors du feu à 121 °C — au-delà elle sèche et coagule. Coulé en Flexipan® (format individuel) vs cadre guitare pour les autres caramels T2.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 102, chef: _CHEF_LN2 },
  },

];