const _SRC_LN1  = "Chocolats et сonfiserie de l ecole Lenotre T1.pdf";
const _CHEF_LN1 = "François Legras & Stéphane Glacier";

const _SRC_LN2  = "Chocolats et сonfiserie de l ecole Lenotre T2.pdf";
const _CHEF_LN2 = "François Legras & Stéphane Glacier";

export const RECETTES_CONFISERIES = [

  /* ── École Lenôtre T1 — Confiseries sucrées ─────────────────────────── */

  {
    id: "sucettes-ln1",
    nom: "Sucettes",
    categorie: "confiseries",
    sous_categorie: "sucre_cuit",
    description: "Sucre cuit à 148 °C coloré et aromatisé. Déclinable en sucettes moulées, coulées, médaillons ou avec fruits secs. Base universelle de la confiserie sucrée au sucre.",
    masse_totale_g: 1800,
    ingredients: [
      { nom: "Sucre cristal", g: 1000, pct: 56, role: "sucrant" },
      { nom: "Eau",           g:  400, pct: 22, role: "eau"     },
      { nom: "Glucose",       g:  400, pct: 22, role: "sucrant" },
    ],
    procede: [
      "Dans un poêlon en cuivre, cuire eau, sucre et glucose.",
      "À 148 °C, ajouter colorant et arôme naturel au choix. Laisser reposer quelques minutes pour faire disparaître les bulles.",
      "Sucettes moulées : couler dans les moules, insérer le bâton avant cristallisation.",
      "Sucettes coulées : verser sur Exopat® huilé, former des disques, insérer les bâtons.",
    ],
    cuisson: { temperature_c: 148, duree_min: null, mode: "poêlon cuivre — 148 °C" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["sucette", "sucre cuit", "confiserie", "bonbon", "arôme"],
    parfum_principal: null,
    note_concepteur: "Colorant et arôme en Q.S. selon la saveur voulue. Laisser impérativement reposer après l'ajout des arômes pour éliminer les bulles — sinon les sucettes seront opaques et fragiles. Se conserve au sec hermétique : le sucre cuit est très hygroscopique.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 89, chef: _CHEF_LN1 },
  },

  {
    id: "drops-miel-ln1",
    nom: "Drops au miel",
    categorie: "confiseries",
    sous_categorie: "sucre_cuit",
    description: "Bonbons cylindriques à base de miel et sucre cuit à 165 °C, légèrement satinés. Texture entre dur et demi-dur. Roulés dans le boulier et détaillés.",
    masse_totale_g: 1231,
    ingredients: [
      { nom: "Miel",            g: 500, pct: 41, role: "sucrant"  },
      { nom: "Sucre cristal",   g: 400, pct: 32, role: "sucrant"  },
      { nom: "Eau",             g: 180, pct: 15, role: "eau"      },
      { nom: "Nougat sec",      g:  30, pct:  2, role: "liant"    },
      { nom: "Glucose",         g: 120, pct: 10, role: "sucrant"  },
      { nom: "Crème de tartre", g:   1, pct:  0, role: "acidite"  },
    ],
    procede: [
      "Dans un poêlon en cuivre, cuire sucre, eau, glucose et crème de tartre.",
      "En parallèle dans une autre casserole, cuire le miel et le nougat sec à 130 °C.",
      "Quand le sucre atteint 152 °C, réunir les deux cuissons. Poursuivre à 165 °C.",
      "Verser sur feuille Exopat®. Refroidir en satinant légèrement.",
      "Former des boudins de 1 cm de diamètre et 20 cm de long. Placer dans le boulier, détailler.",
      "Laisser refroidir complètement. Stocker au sec.",
    ],
    cuisson: { temperature_c: 165, duree_min: null, mode: "poêlon cuivre — miel 130 °C + sucre 152 °C → 165 °C" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["drops", "miel", "bonbon dur", "sucre cuit", "confiserie", "boulier"],
    parfum_principal: "miel",
    note_concepteur: "La double cuisson (miel 130 °C + sucre 152 °C réunis → 165 °C) est caractéristique des drops — elle garantit la fusion homogène des deux sucres. Le nougat sec est mentionné au procédé mais absent de la liste originale : utiliser 25-30 g comme stabilisant.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 91, chef: _CHEF_LN1 },
  },

  {
    id: "pastilles-menthe-ln1",
    nom: "Pastilles de tour à la menthe",
    categorie: "confiseries",
    sous_categorie: "sucre_cuit",
    description: "Pastilles rondes sucre-glucose-nougat sec à 152 °C, parfumées à l'huile essentielle de menthe et colorées en vert. Coulées en moule Flexipan®. Texture dure et fondante.",
    masse_totale_g: 1630,
    ingredients: [
      { nom: "Sucre cristal", g: 1000, pct: 61, role: "sucrant" },
      { nom: "Eau",           g:  300, pct: 19, role: "eau"     },
      { nom: "Glucose",       g:  300, pct: 18, role: "sucrant" },
      { nom: "Nougat sec",    g:   30, pct:  2, role: "liant"   },
    ],
    procede: [
      "Cuire eau, sucre, glucose et nougat sec à 152 °C dans un poêlon en cuivre.",
      "Hors du feu, ajouter 12 gouttes d'huile essentielle de menthe et le colorant vert.",
      "Laisser les bulles disparaître quelques minutes.",
      "Couler à l'entonnoir dans des moules Flexipan® en forme de petites pastilles.",
      "Laisser refroidir. Démouler. Stocker au sec.",
    ],
    cuisson: { temperature_c: 152, duree_min: null, mode: "poêlon cuivre — 152 °C" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["pastille", "menthe", "sucre cuit", "confiserie", "Flexipan", "huile essentielle"],
    parfum_principal: "menthe",
    note_concepteur: "Huile essentielle de menthe : 12 gouttes (non incluses dans la masse). L'huile essentielle s'ajoute strictement hors du feu — au-delà de 80 °C les arômes volatils s'évaporent instantanément. Le nougat sec prévient la recristallisation du sucre en pastilles.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 92, chef: _CHEF_LN1 },
  },

  {
    id: "bonbons-effervescents-ln1",
    nom: "Bonbons effervescents",
    categorie: "confiseries",
    sous_categorie: "effervescent",
    description: "Bonbons sucre cuit à 145 °C avec acide tartrique et bicarbonate de soude incorporés à chaud. L'effervescence se produit au contact de la salive. Deux méthodes : machine à drops ou boulier.",
    masse_totale_g: 1790,
    ingredients: [
      { nom: "Sucre cristal",         g: 1000, pct: 56, role: "sucrant" },
      { nom: "Glucose",               g:  430, pct: 24, role: "sucrant" },
      { nom: "Eau",                   g:  330, pct: 18, role: "eau"     },
      { nom: "Acide tartrique",       g:   15, pct:  1, role: "acidite" },
      { nom: "Bicarbonate de soude",  g:   15, pct:  1, role: "liant"   },
    ],
    procede: [
      "Cuire eau, sucre, glucose et nougat sec à 145 °C. Ajouter colorant et arôme (Q.S.).",
      "Verser sur feuille Exopat®. Tamiser l'acide tartrique et le bicarbonate sur le sucre chaud.",
      "Refroidir en repliant régulièrement, puis satiner.",
      "Méthode 1 : abaisser à 1 cm, passer à la machine à drops. Méthode 2 : boudins 1 cm × 20 cm dans le boulier.",
      "Laisser refroidir. Stocker au sec — l'humidité active l'effervescence prématurément.",
    ],
    cuisson: { temperature_c: 145, duree_min: null, mode: "poêlon cuivre — 145 °C" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["effervescent", "bonbon", "sucre cuit", "acide tartrique", "pétillant", "confiserie"],
    parfum_principal: null,
    note_concepteur: "Le couple acide tartrique + bicarbonate de soude crée CO₂ au contact de la salive (réaction acide-base). Les deux poudres doivent être tamisées séparément et simultanément sur le sucre chaud — mélangées à l'avance, elles réagiraient. Conservation hermétique indispensable.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 93, chef: _CHEF_LN1 },
  },

  {
    id: "berlingots-ln1",
    nom: "Berlingots",
    categorie: "confiseries",
    sous_categorie: "sucre_cuit",
    description: "Bonbons traditionnels français bicolores ou tricolores : sucre de canne tiré et satiné, centre sur-satiné blanc et opaque, rayures torsadées. Découpés en quarts de tour aux ciseaux.",
    masse_totale_g: 1701,
    ingredients: [
      { nom: "Sucre de canne blanc", g: 1000, pct: 59, role: "sucrant" },
      { nom: "Eau",                  g:  400, pct: 23, role: "eau"     },
      { nom: "Glucose",              g:  300, pct: 18, role: "sucrant" },
      { nom: "Acide tartrique",      g:    1, pct:  0, role: "acidite" },
    ],
    procede: [
      "Cuire eau, sucre et glucose à 120 °C. Ajouter l'acide tartrique, puis cuire à 155 °C.",
      "Verser en plusieurs masses sur Exopat®. Aromatiser et colorer chaque masse différemment. Satiner sous lampe à sucre.",
      "Sur-satiner une masse (centre du berlingot) jusqu'à blanchiment complet — elle devient opaque.",
      "Former un boudin central de 5 cm avec le sucre sur-satiné. L'envelopper d'un ruban de 2-3 sucres colorés.",
      "Allonger le boudin à 1 cm de diamètre en le tournant sur lui-même pour torsader les rayures.",
      "Découper en berlingots en faisant 1/4 de tour à chaque coup de ciseaux. Laisser refroidir. Stocker au sec.",
    ],
    cuisson: { temperature_c: 155, duree_min: null, mode: "poêlon cuivre — 155 °C" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["berlingot", "sucre tiré", "satiné", "confiserie", "bicolore", "torsadé", "traditionnel"],
    parfum_principal: null,
    note_concepteur: "Le sucre de canne blanc est plus pur que le sucre de betterave — il donne un brillant supérieur et des couleurs plus pures. Le sur-satinage du centre (tourner jusqu'à opacité) est le geste clé : c'est lui qui crée le contraste visuel caractéristique. Travailler impérativement sous lampe à sucre.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 96, chef: _CHEF_LN1 },
  },

  {
    id: "praline-feuillette-cafe-ln1",
    nom: "Praliné feuilleté café",
    categorie: "confiseries",
    sous_categorie: "sucre_cuit",
    description: "Confiserie sucre de canne tiré fourré au praliné amandes-café, feuilleté comme une pâte viennoise et découpé à 5 cm. Rayures torsadées multicolores. Technique sucrerie haute confiserie.",
    masse_totale_g: 2774,
    ingredients: [
      { nom: "Sucre de canne blanc",  g: 1300, pct: 47, role: "sucrant" },
      { nom: "Praliné aux amandes",   g:  700, pct: 25, role: "parfum"  },
      { nom: "Eau",                   g:  500, pct: 18, role: "eau"     },
      { nom: "Glucose",               g:  260, pct:  9, role: "sucrant" },
      { nom: "Extrait de café",       g:   10, pct:  1, role: "parfum"  },
      { nom: "Crème de tartre",       g:    4, pct:  0, role: "acidite" },
    ],
    procede: [
      "Cuire eau, sucre, glucose et crème de tartre à 161 °C. Diviser en 4 masses sur Exopat®.",
      "La masse principale (2/3) reste blanche. Colorer les 3 autres différemment. Satiner toutes sous lampe à sucre.",
      "Chauffer le praliné amandes avec l'extrait de café à 45 °C. Réserver sur le bord de la lampe.",
      "Abaisser la masse blanche en rectangle. Étaler le praliné café en laissant 1 cm de bord et une bande centrale vide.",
      "Plier en tour double (comme un feuilletage). Former un rouleau régulier.",
      "Envelopper le rouleau d'un ruban des sucres colorés. Allonger à 1 cm en tournant pour torsader.",
      "Couper des pralinés feuilletés de 5 cm aux ciseaux. Refroidir. Stocker au sec.",
    ],
    cuisson: { temperature_c: 161, duree_min: null, mode: "poêlon cuivre — 161 °C + feuilletage sucre" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["fruits_a_coque_amande"],
    tags: ["praliné feuilleté", "café", "sucre tiré", "confiserie", "feuilletage", "amandes"],
    parfum_principal: "café",
    note_concepteur: "La technique de feuilletage du sucre (tour double) est directement inspirée de la pâte feuilletée — elle crée des couches alternées praliné/sucre visible à la coupe. La crème de tartre prévient la recristallisation du sucre lors du tirage.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 99, chef: _CHEF_LN1 },
  },

  {
    id: "gomme-citron-ln1",
    nom: "Gomme citron",
    categorie: "confiseries",
    sous_categorie: "gomme",
    description: "Pâte de gomme arabique et agar-agar parfumée au citron et acide citrique. Coulée en coffrets à amidon, étuvée 24 h, roulée dans le sucre cristal. Texture ferme et translucide.",
    masse_totale_g: 1605,
    ingredients: [
      { nom: "Sucre cristal",  g:  650, pct: 40, role: "sucrant"  },
      { nom: "Eau",            g:  600, pct: 37, role: "eau"      },
      { nom: "Glucose",        g:  200, pct: 12, role: "sucrant"  },
      { nom: "Gomme arabique", g:  100, pct:  6, role: "gelifiant"},
      { nom: "Agar-agar",      g:   25, pct:  2, role: "gelifiant"},
      { nom: "Arôme citron",   g:   10, pct:  1, role: "parfum"   },
      { nom: "Acide citrique", g:   10, pct:  1, role: "acidite"  },
      { nom: "Eau (acide)",    g:   10, pct:  1, role: "eau"      },
    ],
    procede: [
      "Tremper agar-agar et gomme arabique dans les 600 g d'eau à 35 °C pendant 10-12 min. Faire bouillir 3-4 min.",
      "Ajouter le sucre. Cuire à 104 °C.",
      "Ajouter le glucose. Laisser refroidir à 90 °C.",
      "Dissoudre l'acide citrique dans les 10 g d'eau. Incorporer avec l'arôme citron.",
      "Couler à l'entonnoir à piston dans coffrets à amidon marqués à l'empreinte. Étuver 24 heures.",
      "Sortir de l'amidon, brosser. Humidifier à la vapeur. Rouler dans le sucre cristal.",
    ],
    cuisson: { temperature_c: 104, duree_min: null, mode: "casserole — 104 °C + étuve 24 h" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["gomme", "citron", "pâte de gomme", "confiserie", "coffret amidon", "agar-agar"],
    parfum_principal: "citron",
    note_concepteur: "La gomme arabique assure l'élasticité et la fermeté caractéristiques des vraies pâtes de gomme ; l'agar-agar accélère la prise. L'étuve à 35-40 °C pendant 24 h forme la croûte de sucre naturellement sur la surface. Ne jamais humidifier avant d'avoir brossé.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 102, chef: _CHEF_LN1 },
  },

  {
    id: "gomme-fraise-ln1",
    nom: "Gomme fraise",
    categorie: "confiseries",
    sous_categorie: "gomme",
    description: "Pâte de gomme arabique-agar-agar à la pulpe de fraise fraîche. Coulée en coffrets à amidon, étuvée 24 h. Texture plus souple que la gomme citron, saveur fruitée naturelle.",
    masse_totale_g: 1581,
    ingredients: [
      { nom: "Sucre cristal",    g:  500, pct: 32, role: "sucrant"  },
      { nom: "Eau",              g:  400, pct: 25, role: "eau"      },
      { nom: "Pulpe de fraise",  g:  400, pct: 25, role: "fruit"    },
      { nom: "Glucose",          g:  200, pct: 13, role: "sucrant"  },
      { nom: "Gomme arabique",   g:   50, pct:  3, role: "gelifiant"},
      { nom: "Agar-agar",        g:   16, pct:  1, role: "gelifiant"},
      { nom: "Eau (acide)",      g:   10, pct:  1, role: "eau"      },
      { nom: "Acide citrique",   g:    5, pct:  0, role: "acidite"  },
    ],
    procede: [
      "Tremper agar-agar et gomme arabique dans les 400 g d'eau à 35 °C pendant 10 min. Faire bouillir 3-4 min.",
      "Ajouter le sucre et la pulpe de fraise. Cuire à 105 °C.",
      "Ajouter le glucose. Laisser refroidir à 90 °C.",
      "Dissoudre l'acide citrique dans les 10 g d'eau. Incorporer à 90 °C.",
      "Couler à l'entonnoir à piston dans coffrets à amidon marqués. Étuver 24 heures.",
      "Sortir, brosser, humidifier à la vapeur, rouler dans le sucre cristal.",
    ],
    cuisson: { temperature_c: 105, duree_min: null, mode: "casserole — 105 °C + étuve 24 h" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["gomme", "fraise", "pâte de gomme", "confiserie", "pulpe", "agar-agar"],
    parfum_principal: "fraise",
    note_concepteur: "La pulpe de fraise fraîche remplace partiellement l'eau — la pectine naturelle de la fraise contribue à la prise. La cuisson à 105 °C (vs 104 °C pour gomme citron) compense l'eau supplémentaire apportée par la pulpe. Moins de gomme arabique que la version citron car la pulpe apporte de la structure.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 103, chef: _CHEF_LN1 },
  },

  {
    id: "gomme-eucalyptus-ln1",
    nom: "Gomme eucalyptus",
    categorie: "confiseries",
    sous_categorie: "gomme",
    description: "Gomme arabique pure dissoute au bain-marie, sucrée, étuvée 8 h à 60 °C, parfumée à l'eau de fleur d'oranger et à l'essence d'eucalyptus. Technique sans cuisson haute. Texture légère et transparente.",
    masse_totale_g: 785,
    ingredients: [
      { nom: "Gomme arabique en morceaux", g: 235, pct: 30, role: "gelifiant"},
      { nom: "Eau",                        g: 300, pct: 38, role: "eau"      },
      { nom: "Sucre cristal",              g: 210, pct: 27, role: "sucrant"  },
      { nom: "Glucose",                    g:  30, pct:  4, role: "sucrant"  },
      { nom: "Eau de fleur d'oranger",     g:  10, pct:  1, role: "parfum"   },
    ],
    procede: [
      "Faire dissoudre la gomme arabique en morceaux dans l'eau au bain-marie.",
      "Ajouter le sucre et le glucose. Homogénéiser.",
      "Maintenir à l'étuve à 60 °C pendant 8 heures pour dissoudre complètement la gomme.",
      "Le lendemain, retirer l'écume et les impuretés à la surface.",
      "Ajouter l'eau de fleur d'oranger et les 5 gouttes d'essence d'eucalyptus. Mélanger.",
      "Couler à l'entonnoir en coffrets à amidon. Étuver 24 h. Brosser, humidifier, rouler dans le sucre cristal.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "bain-marie + étuve 60 °C (8 h)" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["gomme", "eucalyptus", "fleur d'oranger", "pâte de gomme", "bain-marie", "confiserie"],
    parfum_principal: "eucalyptus",
    note_concepteur: "5 gouttes d'essence d'eucalyptus (non incluses dans la masse). Cette technique à basse température préserve les arômes délicats de l'eucalyptus qui seraient détruits par une cuisson haute. La gomme arabique en morceaux se dissout plus facilement que la poudre et donne une pâte plus limpide.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 104, chef: _CHEF_LN1 },
  },

  {
    id: "reglisse-ln1",
    nom: "Réglisse",
    categorie: "confiseries",
    sous_categorie: "reglisse",
    description: "Pâte de réglisse noire : sucre-glucose cuit à 135 °C, gomme arabique, gélatine et suc de réglisse incorporés, recuit à 120 °C. Coulée en coffrets à amidon, étuvée 24 h. Texture élastique et intense.",
    masse_totale_g: 1145,
    ingredients: [
      { nom: "Gomme arabique",     g: 300, pct: 26, role: "gelifiant"},
      { nom: "Sucre cristal",      g: 300, pct: 27, role: "sucrant"  },
      { nom: "Eau (cuisson)",      g: 200, pct: 17, role: "eau"      },
      { nom: "Gélatine en feuille",g: 120, pct: 10, role: "gelifiant"},
      { nom: "Eau (gélatine)",     g:  80, pct:  7, role: "eau"      },
      { nom: "Glucose",            g:  60, pct:  5, role: "sucrant"  },
      { nom: "Suc de réglisse",    g:  60, pct:  5, role: "parfum"   },
      { nom: "Colorant noir",      g:  25, pct:  3, role: "parfum"   },
    ],
    procede: [
      "Ramollir la gélatine dans les 80 g d'eau froide.",
      "Cuire sucre cristal, glucose et eau (200 g) à 135 °C.",
      "Ajouter la gomme arabique, la gélatine essorée et le suc de réglisse.",
      "Recuire à 120 °C. Ajouter l'essence de menthe ou d'anis (4 gouttes) et le colorant noir.",
      "Couler à l'entonnoir à piston dans coffrets à amidon marqués. Étuver 24 heures.",
      "Sortir, brosser, humidifier à la vapeur, rouler dans le sucre cristal.",
    ],
    cuisson: { temperature_c: 135, duree_min: null, mode: "casserole — 135 °C puis 120 °C + étuve 24 h" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["réglisse", "suc de réglisse", "pâte de gomme", "gélatine", "confiserie", "noir"],
    parfum_principal: "réglisse",
    note_concepteur: "4 gouttes essence de menthe ou d'anis (non incluses dans la masse). La double cuisson (135 °C puis 120 °C après ajout gomme-gélatine-suc) permet de fondre les agents gélifiants sans les dénaturer. Le colorant noir intense est nécessaire — le suc de réglisse seul donne une teinte brun foncé insuffisante.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 105, chef: _CHEF_LN1 },
  },

  /* ── École Lenôtre T2 — Batch 4 : pralines, nougats, liqueurs, marrons ─ */

  {
    id: "praline-montespan-ln2",
    nom: "Praline de Montespan",
    categorie: "confiseries",
    sous_categorie: "praline_amande",
    description: "Amandes grillées enrobées en 6 passes de sirop cuit à 116 °C avec cacao pâte, vanille et colorant rouge. Gommées à la gomme arabique, étuvées une nuit à 40 °C.",
    masse_totale_g: 1680,
    ingredients: [
      { nom: "Sucre cristal",     g: 1000, pct: 60, role: "sucrant" },
      { nom: "Amandes brutes grillées", g: 500, pct: 30, role: "parfum"  },
      { nom: "Eau",               g:  350, pct: 21, role: "eau"     },
      { nom: "Glucose",           g:  200, pct: 12, role: "sucrant" },
      { nom: "Cacao pâte",        g:  125, pct:  7, role: "parfum"  },
    ],
    procede: [
      "Griller les amandes au four à 170 °C jusqu'à couleur blonde à cœur. Réserver.",
      "Faire un sirop avec l'eau, le sucre et le glucose. Diviser en 6 parts égales (environ 200 g chacune).",
      "Disposer les amandes chaudes dans une bassine en cuivre. Verser la 1re part de sirop cuit à 116 °C.",
      "Mélanger à la spatule pour faire masser et sabler — chaque amande doit être enrobée de sucre.",
      "Passer sur crible pour éliminer l'excédent de sucre.",
      "Répéter 5 fois en ajoutant à chaque passe 25 g de cacao pâte, de la vanille liquide (Q.S.) et du colorant rouge (Q.S.).",
      "Enrober de gomme arabique (recette p. 30, T2). Étuver une nuit à 40 °C.",
      "Laisser refroidir. Conserver au sec.",
    ],
    cuisson: { temperature_c: 116, duree_min: null, mode: "sirop 116 °C × 6 passes + étuve 40 °C" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["fruits_a_coque_amande"],
    tags: ["praline", "amande", "caramélisée", "rouge", "cacao", "sablage", "confiserie", "Montespan"],
    parfum_principal: "amande",
    note_concepteur: "Vanille liquide (5 g) et colorant rouge alimentaire : Q.S. (non comptés dans la masse totale). La praline de Montespan se distingue de la praline rouge par l'ajout de cacao pâte à chaque passe (vs uniquement arômes pour la praline rouge). L'étuve une nuit à 40 °C est indispensable pour fixer la gomme arabique.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 31, chef: _CHEF_LN2 },
  },

  {
    id: "praline-rouge-ln2",
    nom: "Praline rouge",
    categorie: "confiseries",
    sous_categorie: "praline_amande",
    description: "Amandes blanches en 6 passes de sirop à 116 °C avec vanille, eau de fleur d'oranger et colorant rouge intense. Gommées, étuvées nuit. Confiserie lyonnaise traditionnelle.",
    masse_totale_g: 1085,
    ingredients: [
      { nom: "Sucre cristal",      g: 500, pct: 46, role: "sucrant" },
      { nom: "Amandes blanches",   g: 250, pct: 23, role: "parfum"  },
      { nom: "Eau",                g: 175, pct: 16, role: "eau"     },
      { nom: "Glucose",            g: 100, pct:  9, role: "sucrant" },
      { nom: "Nougat sec",         g:  30, pct:  3, role: "liant"   },
      { nom: "Eau de fleur d'oranger", g: 10, pct: 1, role: "parfum"  },
      { nom: "Extrait vanille naturelle", g: 5, pct: 0, role: "parfum" },
      { nom: "Colorant rouge",     g:  10, pct:  1, role: "parfum"  },
    ],
    procede: [
      "Griller les amandes au four à 170 °C jusqu'à couleur blonde à cœur. Réserver.",
      "Faire un sirop avec l'eau, le sucre et le glucose. Diviser en 6 parts égales.",
      "Disposer les amandes chaudes dans une bassine en cuivre. Verser la 1re part cuite à 116 °C.",
      "Mélanger pour faire masser et sabler.",
      "Passer sur crible pour éliminer l'excédent. Renouveler 5 fois : la 1re fois ajouter toute la vanille, l'eau de fleur d'oranger et du colorant rouge ; les fois suivantes ajouter un peu plus de colorant.",
      "Enrober de gomme arabique. Étuver une nuit à 40 °C. Laisser refroidir. Conserver au sec.",
    ],
    cuisson: { temperature_c: 116, duree_min: null, mode: "sirop 116 °C × 6 passes + étuve 40 °C" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["fruits_a_coque_amande"],
    tags: ["praline", "rouge", "amande blanche", "fleur d'oranger", "sablage", "confiserie", "Lyon"],
    parfum_principal: "amande",
    note_concepteur: "La vraie praline lyonnaise utilise des amandes blanches (émondées) contrairement à la Montespan (amandes brutes). L'eau de fleur d'oranger (10 g) s'ajoute uniquement lors de la 1re passe aromatique pour diffuser son parfum sur le sucre chaud. Les passes suivantes intensifient uniquement la couleur rouge.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 33, chef: _CHEF_LN2 },
  },

  {
    id: "nougat-pur-miel-ln2",
    nom: "Le Nougat pur miel",
    categorie: "confiseries",
    sous_categorie: "nougat",
    description: "Nougat tendre sans cuisson sucre : miel de châtaignier cuit à 135 °C versé sur blancs montés. Fruits secs torréfiés et pistaches incorporés à la feuille. Étalé entre feuilles azyme, découpé 24 heures.",
    masse_totale_g: 990,
    ingredients: [
      { nom: "Miel de châtaignier",     g: 600, pct: 61, role: "sucrant" },
      { nom: "Amandes blanches",        g: 180, pct: 18, role: "parfum"  },
      { nom: "Amandes hachées grillées",g:  70, pct:  7, role: "parfum"  },
      { nom: "Blancs d'œufs frais",     g:  60, pct:  6, role: "emulsifiant"},
      { nom: "Pistaches mondées",       g:  90, pct:  9, role: "parfum"  },
      { nom: "Noisettes",               g:  80, pct:  8, role: "parfum"  },
    ],
    procede: [
      "Torréfier au four les amandes et noisettes jusqu'à couleur blonde à cœur. Réserver.",
      "Monter les blancs d'œufs en neige ferme.",
      "Cuire le miel de châtaignier à 135 °C. Verser doucement sur les blancs montés en filet.",
      "Ajouter les fruits secs torréfiés et les pistaches mondées avec la feuille du batteur (pas le fouet) pour ne pas écraser.",
      "Bien mélanger. Étaler immédiatement entre 2 feuilles azyme dans un cadre.",
      "Laisser refroidir 24 heures. Découper à la taille désirée. Envelopper dans du papier cellophane.",
    ],
    cuisson: { temperature_c: 135, duree_min: null, mode: "casserole — miel 135 °C" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["oeufs", "fruits_a_coque_amande", "fruits_a_coque_noisette", "fruits_a_coque_pistache"],
    tags: ["nougat", "miel", "châtaignier", "blanc d'œuf", "fruits secs", "azyme", "confiserie"],
    parfum_principal: "miel",
    note_concepteur: "Le miel pur (sans sucre cuit associé) donne un nougat plus souple et plus brun. La feuille du batteur (pas le fouet) évite d'écraser les fruits secs — c'est une technique de confiserie professionnelle. Les pistaches mondées sont ajoutées crues pour conserver leur couleur verte.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 45, chef: _CHEF_LN2 },
  },

  {
    id: "nougat-blanc-ln2",
    nom: "Le Nougat blanc",
    categorie: "confiseries",
    sous_categorie: "nougat",
    description: "Nougat blanc classique : sucre/glucose cuit à 150 °C + miel lavande à 130 °C sur meringue italienne. Noisettes, amandes, pistaches et beurre de cacao incorporés. Cadre inox 1,2 cm entre feuilles azyme.",
    masse_totale_g: 2330,
    ingredients: [
      { nom: "Sucre cristal",        g: 830, pct: 36, role: "sucrant" },
      { nom: "Miel de lavande",      g: 500, pct: 21, role: "sucrant" },
      { nom: "Amandes brutes",       g: 350, pct: 15, role: "parfum"  },
      { nom: "Noisettes",            g: 250, pct: 11, role: "parfum"  },
      { nom: "Eau",                  g: 250, pct: 11, role: "eau"     },
      { nom: "Glucose",              g: 180, pct:  8, role: "sucrant" },
      { nom: "Pistaches",            g: 120, pct:  5, role: "parfum"  },
      { nom: "Blancs d'œufs",        g: 100, pct:  4, role: "emulsifiant"},
      { nom: "Beurre de cacao",      g:  60, pct:  3, role: "mg"      },
      { nom: "Sucre (meringue)",     g:  40, pct:  2, role: "sucrant" },
    ],
    procede: [
      "Torréfier noisettes et amandes au four, blondes à cœur.",
      "Cuire eau, sucre et glucose à 150 °C. En parallèle, cuire le miel à 130 °C (démarrer miel quand sucre est à 120 °C pour terminer simultanément).",
      "Monter les blancs avec les 40 g de sucre. Verser le miel à 130 °C sur les blancs. Remuer vif. Verser immédiatement le sucre cuit à 150 °C. Dessécher quelques minutes.",
      "Ajouter les fruits secs tièdes, les pistaches puis le beurre de cacao avec la feuille du batteur.",
      "Débarrasser immédiatement dans un cadre inox 1,2 cm entre 2 feuilles azyme ou film alimentaire.",
      "Laisser refroidir. Le lendemain, découper à la taille désirée.",
    ],
    cuisson: { temperature_c: 150, duree_min: null, mode: "sucre/glucose 150 °C + miel 130 °C simultanés" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["oeufs", "fruits_a_coque_amande", "fruits_a_coque_noisette", "fruits_a_coque_pistache"],
    tags: ["nougat blanc", "miel lavande", "fruits secs", "meringue italienne", "azyme", "confiserie"],
    parfum_principal: "miel",
    note_concepteur: "La double cuisson simultanée (sucre 150 °C + miel 130 °C) est une technique maîtrise absolue — elles doivent finir en même temps pour verser dans l'ordre correct. Le beurre de cacao (60 g) en fin de procédé lubrifie la masse et facilite la découpe sans coller.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 46, chef: _CHEF_LN2 },
  },

  {
    id: "nougat-pistache-ln2",
    nom: "Le Nougat pistache",
    categorie: "confiseries",
    sous_categorie: "nougat",
    description: "Nougat aux pistaches : sucre/glucose cuit à 160 °C + miel lavande à 135 °C sur meringue italienne, avec amandes, noisettes, pâte de pistache et beurre de cacao. Cadre inox 1,2 cm, feuilles azyme.",
    masse_totale_g: 1295,
    ingredients: [
      { nom: "Sucre",              g: 420, pct: 32, role: "sucrant" },
      { nom: "Miel de lavande",    g: 250, pct: 19, role: "sucrant" },
      { nom: "Pistaches",          g: 150, pct: 12, role: "parfum"  },
      { nom: "Amandes blanches",   g: 180, pct: 14, role: "parfum"  },
      { nom: "Eau",                g: 125, pct: 10, role: "eau"     },
      { nom: "Noisettes",          g: 125, pct: 10, role: "parfum"  },
      { nom: "Glucose",            g:  90, pct:  7, role: "sucrant" },
      { nom: "Blancs d'œufs",      g:  50, pct:  4, role: "emulsifiant"},
      { nom: "Pâte de pistache",   g:  20, pct:  2, role: "parfum"  },
      { nom: "Beurre de cacao",    g:  25, pct:  2, role: "mg"      },
      { nom: "Sucre (meringue)",   g:  20, pct:  2, role: "sucrant" },
    ],
    procede: [
      "Griller noisettes et amandes au four, blondes à cœur.",
      "Cuire eau, sucre et glucose à 160 °C. En parallèle cuire le miel à 135 °C.",
      "Monter les blancs avec les 20 g de sucre. Verser le miel sur les blancs. Verser immédiatement le sucre cuit.",
      "Ajouter les fruits secs tièdes, les pistaches, la pâte de pistache et le beurre de cacao avec la feuille du batteur.",
      "Débarrasser dans un cadre inox 1,2 cm entre 2 feuilles azyme. Laisser refroidir. Découper le lendemain.",
    ],
    cuisson: { temperature_c: 160, duree_min: null, mode: "sucre/glucose 160 °C + miel 135 °C simultanés" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["oeufs", "fruits_a_coque_amande", "fruits_a_coque_noisette", "fruits_a_coque_pistache"],
    tags: ["nougat", "pistache", "miel lavande", "meringue italienne", "azyme", "confiserie"],
    parfum_principal: "pistache",
    note_concepteur: "La pâte de pistache (20 g) renforce la couleur verte et le parfum sans apporter de morceaux. Ce nougat cuit plus haut (160 °C vs 150 °C pour le blanc) pour une texture plus ferme qui supporte les pistaches entières. La double cuisson simultanée s'applique identiquement au nougat blanc.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 49, chef: _CHEF_LN2 },
  },

  {
    id: "nougat-dur-coriandre-ln2",
    nom: "Nougat dur au coriandre",
    categorie: "confiseries",
    sous_categorie: "nougat_dur",
    description: "Nougat dur (sans blancs d'œufs) : amandes et pistaches enrobées de sucre/glucose/miel cuit à 165 °C avec coriandre en poudre. Coulé sur marbre huilé, cassé en morceaux.",
    masse_totale_g: 1205,
    ingredients: [
      { nom: "Amandes brutes",   g: 550, pct: 46, role: "parfum"  },
      { nom: "Sucre",            g: 300, pct: 25, role: "sucrant" },
      { nom: "Pistaches",        g: 150, pct: 12, role: "parfum"  },
      { nom: "Glucose",          g: 130, pct: 11, role: "sucrant" },
      { nom: "Miel",             g: 100, pct:  8, role: "sucrant" },
      { nom: "Coriandre en poudre", g: 5, pct: 0, role: "parfum"  },
    ],
    procede: [
      "Griller les amandes brutes au four, blondes à cœur.",
      "Cuire le sucre, le glucose et le miel à 165 °C jusqu'à couleur caramel.",
      "Ajouter les amandes grillées, les pistaches et la coriandre en poudre. Mélanger.",
      "Verser immédiatement sur un marbre légèrement huilé ou feuille Exopat®.",
      "Étaler. Laisser refroidir. Casser en gros morceaux.",
      "Filmer et conserver au sec.",
    ],
    cuisson: { temperature_c: 165, duree_min: null, mode: "casserole — sucre/glucose/miel 165 °C" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["fruits_a_coque_amande", "fruits_a_coque_pistache"],
    tags: ["nougat dur", "coriandre", "amande", "pistache", "caramel", "confiserie"],
    parfum_principal: "amande",
    note_concepteur: "Ce nougat dur (sans albumen) est plus proche d'une nougatine que d'un nougat tendre. La coriandre en poudre (5 g) est l'élément distinctif — subtile en intensité, elle apporte une note agrumée et épicée inattendue. Le 165 °C est critique : en dessous, le caramel reste collant ; au-dessus, il devient amer.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 51, chef: _CHEF_LN2 },
  },

  {
    id: "bonbon-pate-amande-orange-ln2",
    nom: "Bonbon pâte d'amande chocolat/orange",
    categorie: "confiseries",
    sous_categorie: "pate_amande_chocolat",
    description: "Disque de pâte d'amande 66 % mixée avec écorce d'orange confite et couverture Louvre à 40 °C, découpé en bouton d'or. Enrobé partiellement de couverture Louvre avec écorces d'orange déposées.",
    masse_totale_g: 200,
    ingredients: [
      { nom: "Pâte d'amande 66 %",         g: 150, pct: 75, role: "parfum"  },
      { nom: "Couverture Louvre",           g:  50, pct: 25, role: "parfum"  },
      { nom: "Écorce d'orange confite",     g:  50, pct: 25, role: "fruit"   },
    ],
    procede: [
      "Mixer la pâte d'amande avec les écorces d'orange confites.",
      "Ajouter la couverture Louvre fondue à 40 °C. Bien mélanger.",
      "Abaisser à 0,6 cm d'épaisseur entre deux feuilles de cuisson Exopat®.",
      "Détailler en forme de bouton d'or. Déposer un morceau d'écorce d'orange sur chaque pièce.",
      "Enrober partiellement de couverture Louvre tempérée.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson — enrobage partiel 32 °C" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait", "fruits_a_coque_amande"],
    tags: ["pâte d'amande", "orange", "confite", "bonbon", "couverture Louvre", "confiserie"],
    parfum_principal: "orange",
    note_concepteur: "La « couverture Louvre » est une couverture chocolat lait propriétaire Barry Callebaut (pour l'école Lenôtre) — remplacer par couverture lait 36 % standard. La somme des pct dépasse 100 % (a_verifier) car les écorces sont comptées dans la pâte et séparément. Forme bouton d'or = emporte-pièce festonné.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 47, chef: _CHEF_LN2 },
  },

  {
    id: "bonbon-pate-amande-cafe-ln2",
    nom: "Bonbon pâte d'amande chocolat/café",
    categorie: "confiseries",
    sous_categorie: "pate_amande_chocolat",
    description: "Disque pâte d'amande/chocolat surmonté d'une meringue confiseur café (blancs pochés 60 °C, sucre, gélatine). Glacé à 30-35 °C au dessus, enrobé partiellement couverture Louvre.",
    masse_totale_g: 730,
    ingredients: [
      { nom: "Blancs d'œufs",               g: 180, pct: 25, role: "emulsifiant"},
      { nom: "Sucre semoule",               g: 310, pct: 42, role: "sucrant" },
      { nom: "Pâte d'amande 66 %",          g: 150, pct: 21, role: "parfum"  },
      { nom: "Couverture Louvre",           g:  50, pct:  7, role: "parfum"  },
      { nom: "Sucre glace",                 g:  90, pct: 12, role: "sucrant" },
      { nom: "Extrait naturel café",        g:  20, pct:  3, role: "parfum"  },
      { nom: "Écorce d'orange confite",     g:  50, pct:  7, role: "fruit"   },
      { nom: "Gélatine feuille",            g:   5, pct:  1, role: "gelifiant"},
      { nom: "Jus de citron",               g:   2, pct:  0, role: "acidite" },
    ],
    procede: [
      "Pâte d'amande chocolat/café : mixer la pâte d'amande avec les écorces d'orange confites. Ajouter la couverture Louvre à 40 °C.",
      "Meringue confiseur café : pocher à 60 °C les blancs d'œufs, le sucre semoule et l'extrait de café. Refroidir à 40 °C au batteur avec le fouet.",
      "Ajouter le sucre glace, le jus de citron et la gélatine réhydratée.",
      "Détailler la pâte d'amande/chocolat en ronds.",
      "Déposer la meringue confiseur sur chaque rond. Glacer le dessus à 30-35 °C.",
      "Enrober partiellement de couverture Louvre tempérée.",
    ],
    cuisson: { temperature_c: 60, duree_min: null, mode: "pocher 60 °C + enrobage partiel" },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["oeufs", "lait", "fruits_a_coque_amande"],
    tags: ["pâte d'amande", "café", "meringue confiseur", "gélatine", "confiserie", "couverture Louvre"],
    parfum_principal: "café",
    note_concepteur: "La « meringue confiseur » est une meringue pochée à 60 °C (pasteurisée) stabilisée à la gélatine — technique confiserie professionnelle différente de la meringue suisse ou italienne. L'extrait de café s'incorpore dans les blancs chauds pour une diffusion aromatique optimale. Somme pct > 100 % (a_verifier).",
    source_interne: { fichier_pdf: _SRC_LN2, page: 47, chef: _CHEF_LN2 },
  },

  {
    id: "marrons-glaces-ln2",
    nom: "Marrons glacés",
    categorie: "confiseries",
    sous_categorie: "fruit_confit",
    description: "Marrons au sirop égouttés puis glacés au fondant pâtissier dilué au sirop de marron (48-50 °C / 81 % Brix). Passés au four à 180 °C jusqu'au perlage du glaçage. Technique classique confiserie.",
    masse_totale_g: 2200,
    ingredients: [
      { nom: "Fondant pâtissier", g: 1000, pct: 45, role: "sucrant" },
      { nom: "Marrons au sirop",  g:  800, pct: 36, role: "fruit"   },
      { nom: "Sirop de marron ou sirop 60 %", g: 400, pct: 18, role: "sucrant" },
    ],
    procede: [
      "Égoutter les marrons sur grille pendant 1 heure.",
      "Préchauffer le four à 40 °C. Y passer les marrons environ 15 minutes pour les réchauffer.",
      "Réaliser le glaçage : chauffer le sirop de marron et le fondant pâtissier à 48-50 °C (81 % Brix).",
      "Tremper les marrons dans le glaçage. Les poser sur une grille avec une plaque aluminium dessous.",
      "Enfourner à 180 °C jusqu'à l'apparition du perlage du glaçage sur la plaque ou la grille.",
      "Sortir immédiatement. Laisser refroidir et croûter.",
    ],
    cuisson: { temperature_c: 180, duree_min: null, mode: "four 180 °C jusqu'au perlage du glaçage" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["marron glacé", "fondant", "glaçage", "fruit confit", "confiserie", "châtaigne"],
    parfum_principal: "marron",
    note_concepteur: "Rester devant le four pendant le glaçage — le perlage apparaît en quelques secondes et si le four est trop chaud ou le temps de chauffe trop long, le glaçage masse. Si le marron colle une fois refroidi, le temps de four était insuffisant. La température de glaçage (48-50 °C / 81 % Brix) est critique pour la cristallisation fine.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 89, chef: _CHEF_LN2 },
  },

  {
    id: "toffee-ln2",
    nom: "Toffee",
    categorie: "confiseries",
    sous_categorie: "caramel_lait",
    description: "Toffee anglais : sucre-glucose cuit à 190 °C, décuit avec beurre salé puis lait concentré vanillé. Recuit à 122 °C, coulé en moule Flexipan®. Texture fondante très caramérisée.",
    masse_totale_g: 1555,
    ingredients: [
      { nom: "Lait concentré",    g: 655, pct: 42, role: "mg"      },
      { nom: "Sucre",             g: 550, pct: 35, role: "sucrant" },
      { nom: "Glucose",           g: 250, pct: 16, role: "sucrant" },
      { nom: "Beurre salé",       g: 125, pct:  8, role: "mg"      },
      { nom: "Nougat sec",        g:  25, pct:  2, role: "liant"   },
    ],
    procede: [
      "Cuire le sucre et le glucose à 190 °C.",
      "Chauffer le lait concentré avec les gousses de vanille (Q.S.) et le nougat sec jusqu'à ébullition.",
      "Décuire le sucre avec le beurre salé, puis verser le lait concentré bouillant en 2-3 fois (ne pas descendre sous 114 °C).",
      "Remuer vivement à la spatule. Faire recuire à 122 °C.",
      "Couler dans un entonnoir à piston préchauffé au four à 80 °C, puis couler dans des moules Flexipan®.",
      "Laisser refroidir avant de démouler. Conserver en boîte hermétique.",
    ],
    cuisson: { temperature_c: 190, duree_min: null, mode: "casserole — sucre/glucose 190 °C puis recuit 122 °C" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["toffee", "caramel", "lait concentré", "beurre salé", "confiserie", "anglais"],
    parfum_principal: "caramel",
    note_concepteur: "Vanille : 3 gousses (non incluses dans la masse). La cuisson initiale à 190 °C (très haute pour un caramel) donne la note grillée intense caractéristique du toffee anglais. Ne jamais descendre sous 114 °C lors de la décuisson avec le lait — un choc thermique trop fort ferait masser le sucre. L'entonnoir préchauffé prévient la solidification prématurée.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 101, chef: _CHEF_LN2 },
  },

  {
    id: "liqueur-irlandaise-ln2",
    nom: "Liqueur irlandaise",
    categorie: "confiseries",
    sous_categorie: "liqueur_sucre",
    description: "Liqueur irlandaise : infusion café-whisky, sirop cuit à 117 °C, cristallisation contrôlée en coffret amidon. Enrobée de couverture 64 % ou candissée. Procédé liqueur coulée en amidon.",
    masse_totale_g: 2050,
    ingredients: [
      { nom: "Sucre",           g: 1000, pct: 49, role: "sucrant" },
      { nom: "Eau/infusion café",g: 1200, pct: 59, role: "eau"    },
      { nom: "Whisky 40°",      g:  500, pct: 24, role: "parfum"  },
      { nom: "Café moulu",      g:  350, pct: 17, role: "parfum"  },
    ],
    procede: [
      "Faire une infusion avec 1200 g d'eau et 350 g de café moulu. Chinoiser. Peser 1200 g d'infusion.",
      "Cuire l'infusion et le sucre à 117 °C. Débarrasser dans un cul-de-poule.",
      "Verser le whisky. Mélanger. Remettre dans le poêlon puis transvaser de nouveau dans le cul-de-poule. Répéter 3 fois.",
      "Couler à l'entonnoir à piston dans un coffret d'amidon chaud préalablement marqué à l'empreinte.",
      "Tamiser de l'amidon chaud sur le dessus des liqueurs. Cristalliser 3 heures.",
      "Couvrir et retourner le coffret. Cristalliser 10 heures. Prélever délicatement, brosser doucement.",
      "Finition : enrober de couverture 64 % ou candisser. Emballer en papier aluminium coloré.",
    ],
    cuisson: { temperature_c: 117, duree_min: null, mode: "casserole — sirop 117 °C + coffret amidon" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["liqueur", "whisky", "café", "coulée amidon", "confiserie", "irlandaise"],
    parfum_principal: "café",
    note_concepteur: "Le transfert 3 fois poêlon→cul-de-poule contrôle la cristallisation pour obtenir une croûte fine mais solide. Le coffret d'amidon doit être chaud (30-35 °C) sinon la cristallisation est trop rapide. La somme des pct dépasse 100 % (a_verifier) car l'eau de l'infusion contient aussi le café — comptage distinct.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 106, chef: _CHEF_LN2 },
  },

  {
    id: "liqueur-framboise-ln2",
    nom: "Liqueur framboise",
    categorie: "confiseries",
    sous_categorie: "liqueur_sucre",
    description: "Liqueur framboise : sirop sucre cuit à 116 °C + eau-de-vie framboise 60°. Cristallisation en coffret amidon, enrobée couverture ou candissée.",
    masse_totale_g: 1600,
    ingredients: [
      { nom: "Sucre cristal",           g: 1000, pct: 63, role: "sucrant" },
      { nom: "Eau",                     g:  400, pct: 25, role: "eau"     },
      { nom: "Eau-de-vie de framboise 60°", g: 200, pct: 13, role: "parfum" },
    ],
    procede: [
      "Cuire l'eau et le sucre à 116 °C. Débarrasser dans un cul-de-poule.",
      "Verser l'eau-de-vie de framboise. Mélanger. Remettre dans le poêlon puis reverser. Répéter 3 fois.",
      "Couler à l'entonnoir dans le coffret d'amidon chaud marqué à l'empreinte.",
      "Tamiser de l'amidon chaud. Cristalliser 3 heures. Retourner et cristalliser 10 heures.",
      "Prélever, brosser. Enrober de couverture ou candisser. Emballer.",
    ],
    cuisson: { temperature_c: 116, duree_min: null, mode: "casserole — sirop 116 °C + coffret amidon" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["liqueur", "framboise", "eau-de-vie", "coulée amidon", "confiserie"],
    parfum_principal: "framboise",
    note_concepteur: "Variante avec eau-de-vie framboise 40° : utiliser 300 g au lieu de 200 g pour le même titre alcoolique final (principe de base : 50 g de sucre par degré d'alcool, p. 105). La technique de transfert 3× est identique à la liqueur irlandaise.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 107, chef: _CHEF_LN2 },
  },

];
