const _SRC_LN1  = "Chocolats et сonfiserie de l ecole Lenotre T1.pdf";
const _CHEF_LN1 = "François Legras & Stéphane Glacier";

export const RECETTES_CONFISERIES = [

  /* ── École Lenôtre T1 — Confiseries sucrées ─────────────────────────── */

  {
    id: "sucettes-ln1",
    nom: "Sucettes",
    categorie: "confiseries",
    sous_categorie: "sucre_cuit",
    description: "Sucre cuit à 148 °C coloré et aromatisé. Déclinable en sucettes moulées, coulées, médaillons ou avec fruits secs. Base universelle de la confiserie sucrée au sucre.",
    masse_totale_g: 1800,
    ingredients: [
      { nom: "Sucre cristal", g: 1000, pct: 56, role: "sucrant" },
      { nom: "Eau",           g:  400, pct: 22, role: "eau"     },
      { nom: "Glucose",       g:  400, pct: 22, role: "sucrant" },
    ],
    procede: [
      "Dans un poêlon en cuivre, cuire eau, sucre et glucose.",
      "À 148 °C, ajouter colorant et arôme naturel au choix. Laisser reposer quelques minutes pour faire disparaître les bulles.",
      "Sucettes moulées : couler dans les moules, insérer le bâton avant cristallisation.",
      "Sucettes coulées : verser sur Exopat® huilé, former des disques, insérer les bâtons.",
    ],
    cuisson: { temperature_c: 148, duree_min: null, mode: "poêlon cuivre — 148 °C" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["sucette", "sucre cuit", "confiserie", "bonbon", "arôme"],
    parfum_principal: null,
    note_concepteur: "Colorant et arôme en Q.S. selon la saveur voulue. Laisser impérativement reposer après l'ajout des arômes pour éliminer les bulles — sinon les sucettes seront opaques et fragiles. Se conserve au sec hermétique : le sucre cuit est très hygroscopique.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 89, chef: _CHEF_LN1 },
  },

  {
    id: "drops-miel-ln1",
    nom: "Drops au miel",
    categorie: "confiseries",
    sous_categorie: "sucre_cuit",
    description: "Bonbons cylindriques à base de miel et sucre cuit à 165 °C, légèrement satinés. Texture entre dur et demi-dur. Roulés dans le boulier et détaillés.",
    masse_totale_g: 1231,
    ingredients: [
      { nom: "Miel",            g: 500, pct: 41, role: "sucrant"  },
      { nom: "Sucre cristal",   g: 400, pct: 32, role: "sucrant"  },
      { nom: "Eau",             g: 180, pct: 15, role: "eau"      },
      { nom: "Nougat sec",      g:  30, pct:  2, role: "liant"    },
      { nom: "Glucose",         g: 120, pct: 10, role: "sucrant"  },
      { nom: "Crème de tartre", g:   1, pct:  0, role: "acidite"  },
    ],
    procede: [
      "Dans un poêlon en cuivre, cuire sucre, eau, glucose et crème de tartre.",
      "En parallèle dans une autre casserole, cuire le miel et le nougat sec à 130 °C.",
      "Quand le sucre atteint 152 °C, réunir les deux cuissons. Poursuivre à 165 °C.",
      "Verser sur feuille Exopat®. Refroidir en satinant légèrement.",
      "Former des boudins de 1 cm de diamètre et 20 cm de long. Placer dans le boulier, détailler.",
      "Laisser refroidir complètement. Stocker au sec.",
    ],
    cuisson: { temperature_c: 165, duree_min: null, mode: "poêlon cuivre — miel 130 °C + sucre 152 °C → 165 °C" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["drops", "miel", "bonbon dur", "sucre cuit", "confiserie", "boulier"],
    parfum_principal: "miel",
    note_concepteur: "La double cuisson (miel 130 °C + sucre 152 °C réunis → 165 °C) est caractéristique des drops — elle garantit la fusion homogène des deux sucres. Le nougat sec est mentionné au procédé mais absent de la liste originale : utiliser 25-30 g comme stabilisant.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 91, chef: _CHEF_LN1 },
  },

  {
    id: "pastilles-menthe-ln1",
    nom: "Pastilles de tour à la menthe",
    categorie: "confiseries",
    sous_categorie: "sucre_cuit",
    description: "Pastilles rondes sucre-glucose-nougat sec à 152 °C, parfumées à l'huile essentielle de menthe et colorées en vert. Coulées en moule Flexipan®. Texture dure et fondante.",
    masse_totale_g: 1630,
    ingredients: [
      { nom: "Sucre cristal", g: 1000, pct: 61, role: "sucrant" },
      { nom: "Eau",           g:  300, pct: 19, role: "eau"     },
      { nom: "Glucose",       g:  300, pct: 18, role: "sucrant" },
      { nom: "Nougat sec",    g:   30, pct:  2, role: "liant"   },
    ],
    procede: [
      "Cuire eau, sucre, glucose et nougat sec à 152 °C dans un poêlon en cuivre.",
      "Hors du feu, ajouter 12 gouttes d'huile essentielle de menthe et le colorant vert.",
      "Laisser les bulles disparaître quelques minutes.",
      "Couler à l'entonnoir dans des moules Flexipan® en forme de petites pastilles.",
      "Laisser refroidir. Démouler. Stocker au sec.",
    ],
    cuisson: { temperature_c: 152, duree_min: null, mode: "poêlon cuivre — 152 °C" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["pastille", "menthe", "sucre cuit", "confiserie", "Flexipan", "huile essentielle"],
    parfum_principal: "menthe",
    note_concepteur: "Huile essentielle de menthe : 12 gouttes (non incluses dans la masse). L'huile essentielle s'ajoute strictement hors du feu — au-delà de 80 °C les arômes volatils s'évaporent instantanément. Le nougat sec prévient la recristallisation du sucre en pastilles.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 92, chef: _CHEF_LN1 },
  },

  {
    id: "bonbons-effervescents-ln1",
    nom: "Bonbons effervescents",
    categorie: "confiseries",
    sous_categorie: "effervescent",
    description: "Bonbons sucre cuit à 145 °C avec acide tartrique et bicarbonate de soude incorporés à chaud. L'effervescence se produit au contact de la salive. Deux méthodes : machine à drops ou boulier.",
    masse_totale_g: 1790,
    ingredients: [
      { nom: "Sucre cristal",         g: 1000, pct: 56, role: "sucrant" },
      { nom: "Glucose",               g:  430, pct: 24, role: "sucrant" },
      { nom: "Eau",                   g:  330, pct: 18, role: "eau"     },
      { nom: "Acide tartrique",       g:   15, pct:  1, role: "acidite" },
      { nom: "Bicarbonate de soude",  g:   15, pct:  1, role: "liant"   },
    ],
    procede: [
      "Cuire eau, sucre, glucose et nougat sec à 145 °C. Ajouter colorant et arôme (Q.S.).",
      "Verser sur feuille Exopat®. Tamiser l'acide tartrique et le bicarbonate sur le sucre chaud.",
      "Refroidir en repliant régulièrement, puis satiner.",
      "Méthode 1 : abaisser à 1 cm, passer à la machine à drops. Méthode 2 : boudins 1 cm × 20 cm dans le boulier.",
      "Laisser refroidir. Stocker au sec — l'humidité active l'effervescence prématurément.",
    ],
    cuisson: { temperature_c: 145, duree_min: null, mode: "poêlon cuivre — 145 °C" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["effervescent", "bonbon", "sucre cuit", "acide tartrique", "pétillant", "confiserie"],
    parfum_principal: null,
    note_concepteur: "Le couple acide tartrique + bicarbonate de soude crée CO₂ au contact de la salive (réaction acide-base). Les deux poudres doivent être tamisées séparément et simultanément sur le sucre chaud — mélangées à l'avance, elles réagiraient. Conservation hermétique indispensable.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 93, chef: _CHEF_LN1 },
  },

  {
    id: "berlingots-ln1",
    nom: "Berlingots",
    categorie: "confiseries",
    sous_categorie: "sucre_cuit",
    description: "Bonbons traditionnels français bicolores ou tricolores : sucre de canne tiré et satiné, centre sur-satiné blanc et opaque, rayures torsadées. Découpés en quarts de tour aux ciseaux.",
    masse_totale_g: 1701,
    ingredients: [
      { nom: "Sucre de canne blanc", g: 1000, pct: 59, role: "sucrant" },
      { nom: "Eau",                  g:  400, pct: 23, role: "eau"     },
      { nom: "Glucose",              g:  300, pct: 18, role: "sucrant" },
      { nom: "Acide tartrique",      g:    1, pct:  0, role: "acidite" },
    ],
    procede: [
      "Cuire eau, sucre et glucose à 120 °C. Ajouter l'acide tartrique, puis cuire à 155 °C.",
      "Verser en plusieurs masses sur Exopat®. Aromatiser et colorer chaque masse différemment. Satiner sous lampe à sucre.",
      "Sur-satiner une masse (centre du berlingot) jusqu'à blanchiment complet — elle devient opaque.",
      "Former un boudin central de 5 cm avec le sucre sur-satiné. L'envelopper d'un ruban de 2-3 sucres colorés.",
      "Allonger le boudin à 1 cm de diamètre en le tournant sur lui-même pour torsader les rayures.",
      "Découper en berlingots en faisant 1/4 de tour à chaque coup de ciseaux. Laisser refroidir. Stocker au sec.",
    ],
    cuisson: { temperature_c: 155, duree_min: null, mode: "poêlon cuivre — 155 °C" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["berlingot", "sucre tiré", "satiné", "confiserie", "bicolore", "torsadé", "traditionnel"],
    parfum_principal: null,
    note_concepteur: "Le sucre de canne blanc est plus pur que le sucre de betterave — il donne un brillant supérieur et des couleurs plus pures. Le sur-satinage du centre (tourner jusqu'à opacité) est le geste clé : c'est lui qui crée le contraste visuel caractéristique. Travailler impérativement sous lampe à sucre.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 96, chef: _CHEF_LN1 },
  },

  {
    id: "praline-feuillette-cafe-ln1",
    nom: "Praliné feuilleté café",
    categorie: "confiseries",
    sous_categorie: "sucre_cuit",
    description: "Confiserie sucre de canne tiré fourré au praliné amandes-café, feuilleté comme une pâte viennoise et découpé à 5 cm. Rayures torsadées multicolores. Technique sucrerie haute confiserie.",
    masse_totale_g: 2774,
    ingredients: [
      { nom: "Sucre de canne blanc",  g: 1300, pct: 47, role: "sucrant" },
      { nom: "Praliné aux amandes",   g:  700, pct: 25, role: "parfum"  },
      { nom: "Eau",                   g:  500, pct: 18, role: "eau"     },
      { nom: "Glucose",               g:  260, pct:  9, role: "sucrant" },
      { nom: "Extrait de café",       g:   10, pct:  1, role: "parfum"  },
      { nom: "Crème de tartre",       g:    4, pct:  0, role: "acidite" },
    ],
    procede: [
      "Cuire eau, sucre, glucose et crème de tartre à 161 °C. Diviser en 4 masses sur Exopat®.",
      "La masse principale (2/3) reste blanche. Colorer les 3 autres différemment. Satiner toutes sous lampe à sucre.",
      "Chauffer le praliné amandes avec l'extrait de café à 45 °C. Réserver sur le bord de la lampe.",
      "Abaisser la masse blanche en rectangle. Étaler le praliné café en laissant 1 cm de bord et une bande centrale vide.",
      "Plier en tour double (comme un feuilletage). Former un rouleau régulier.",
      "Envelopper le rouleau d'un ruban des sucres colorés. Allonger à 1 cm en tournant pour torsader.",
      "Couper des pralinés feuilletés de 5 cm aux ciseaux. Refroidir. Stocker au sec.",
    ],
    cuisson: { temperature_c: 161, duree_min: null, mode: "poêlon cuivre — 161 °C + feuilletage sucre" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["fruits_a_coque_amande"],
    tags: ["praliné feuilleté", "café", "sucre tiré", "confiserie", "feuilletage", "amandes"],
    parfum_principal: "café",
    note_concepteur: "La technique de feuilletage du sucre (tour double) est directement inspirée de la pâte feuilletée — elle crée des couches alternées praliné/sucre visible à la coupe. La crème de tartre prévient la recristallisation du sucre lors du tirage.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 99, chef: _CHEF_LN1 },
  },

  {
    id: "gomme-citron-ln1",
    nom: "Gomme citron",
    categorie: "confiseries",
    sous_categorie: "gomme",
    description: "Pâte de gomme arabique et agar-agar parfumée au citron et acide citrique. Coulée en coffrets à amidon, étuvée 24 h, roulée dans le sucre cristal. Texture ferme et translucide.",
    masse_totale_g: 1605,
    ingredients: [
      { nom: "Sucre cristal",  g:  650, pct: 40, role: "sucrant"  },
      { nom: "Eau",            g:  600, pct: 37, role: "eau"      },
      { nom: "Glucose",        g:  200, pct: 12, role: "sucrant"  },
      { nom: "Gomme arabique", g:  100, pct:  6, role: "gelifiant"},
      { nom: "Agar-agar",      g:   25, pct:  2, role: "gelifiant"},
      { nom: "Arôme citron",   g:   10, pct:  1, role: "parfum"   },
      { nom: "Acide citrique", g:   10, pct:  1, role: "acidite"  },
      { nom: "Eau (acide)",    g:   10, pct:  1, role: "eau"      },
    ],
    procede: [
      "Tremper agar-agar et gomme arabique dans les 600 g d'eau à 35 °C pendant 10-12 min. Faire bouillir 3-4 min.",
      "Ajouter le sucre. Cuire à 104 °C.",
      "Ajouter le glucose. Laisser refroidir à 90 °C.",
      "Dissoudre l'acide citrique dans les 10 g d'eau. Incorporer avec l'arôme citron.",
      "Couler à l'entonnoir à piston dans coffrets à amidon marqués à l'empreinte. Étuver 24 heures.",
      "Sortir de l'amidon, brosser. Humidifier à la vapeur. Rouler dans le sucre cristal.",
    ],
    cuisson: { temperature_c: 104, duree_min: null, mode: "casserole — 104 °C + étuve 24 h" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["gomme", "citron", "pâte de gomme", "confiserie", "coffret amidon", "agar-agar"],
    parfum_principal: "citron",
    note_concepteur: "La gomme arabique assure l'élasticité et la fermeté caractéristiques des vraies pâtes de gomme ; l'agar-agar accélère la prise. L'étuve à 35-40 °C pendant 24 h forme la croûte de sucre naturellement sur la surface. Ne jamais humidifier avant d'avoir brossé.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 102, chef: _CHEF_LN1 },
  },

  {
    id: "gomme-fraise-ln1",
    nom: "Gomme fraise",
    categorie: "confiseries",
    sous_categorie: "gomme",
    description: "Pâte de gomme arabique-agar-agar à la pulpe de fraise fraîche. Coulée en coffrets à amidon, étuvée 24 h. Texture plus souple que la gomme citron, saveur fruitée naturelle.",
    masse_totale_g: 1581,
    ingredients: [
      { nom: "Sucre cristal",    g:  500, pct: 32, role: "sucrant"  },
      { nom: "Eau",              g:  400, pct: 25, role: "eau"      },
      { nom: "Pulpe de fraise",  g:  400, pct: 25, role: "fruit"    },
      { nom: "Glucose",          g:  200, pct: 13, role: "sucrant"  },
      { nom: "Gomme arabique",   g:   50, pct:  3, role: "gelifiant"},
      { nom: "Agar-agar",        g:   16, pct:  1, role: "gelifiant"},
      { nom: "Eau (acide)",      g:   10, pct:  1, role: "eau"      },
      { nom: "Acide citrique",   g:    5, pct:  0, role: "acidite"  },
    ],
    procede: [
      "Tremper agar-agar et gomme arabique dans les 400 g d'eau à 35 °C pendant 10 min. Faire bouillir 3-4 min.",
      "Ajouter le sucre et la pulpe de fraise. Cuire à 105 °C.",
      "Ajouter le glucose. Laisser refroidir à 90 °C.",
      "Dissoudre l'acide citrique dans les 10 g d'eau. Incorporer à 90 °C.",
      "Couler à l'entonnoir à piston dans coffrets à amidon marqués. Étuver 24 heures.",
      "Sortir, brosser, humidifier à la vapeur, rouler dans le sucre cristal.",
    ],
    cuisson: { temperature_c: 105, duree_min: null, mode: "casserole — 105 °C + étuve 24 h" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["gomme", "fraise", "pâte de gomme", "confiserie", "pulpe", "agar-agar"],
    parfum_principal: "fraise",
    note_concepteur: "La pulpe de fraise fraîche remplace partiellement l'eau — la pectine naturelle de la fraise contribue à la prise. La cuisson à 105 °C (vs 104 °C pour gomme citron) compense l'eau supplémentaire apportée par la pulpe. Moins de gomme arabique que la version citron car la pulpe apporte de la structure.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 103, chef: _CHEF_LN1 },
  },

  {
    id: "gomme-eucalyptus-ln1",
    nom: "Gomme eucalyptus",
    categorie: "confiseries",
    sous_categorie: "gomme",
    description: "Gomme arabique pure dissoute au bain-marie, sucrée, étuvée 8 h à 60 °C, parfumée à l'eau de fleur d'oranger et à l'essence d'eucalyptus. Technique sans cuisson haute. Texture légère et transparente.",
    masse_totale_g: 785,
    ingredients: [
      { nom: "Gomme arabique en morceaux", g: 235, pct: 30, role: "gelifiant"},
      { nom: "Eau",                        g: 300, pct: 38, role: "eau"      },
      { nom: "Sucre cristal",              g: 210, pct: 27, role: "sucrant"  },
      { nom: "Glucose",                    g:  30, pct:  4, role: "sucrant"  },
      { nom: "Eau de fleur d'oranger",     g:  10, pct:  1, role: "parfum"   },
    ],
    procede: [
      "Faire dissoudre la gomme arabique en morceaux dans l'eau au bain-marie.",
      "Ajouter le sucre et le glucose. Homogénéiser.",
      "Maintenir à l'étuve à 60 °C pendant 8 heures pour dissoudre complètement la gomme.",
      "Le lendemain, retirer l'écume et les impuretés à la surface.",
      "Ajouter l'eau de fleur d'oranger et les 5 gouttes d'essence d'eucalyptus. Mélanger.",
      "Couler à l'entonnoir en coffrets à amidon. Étuver 24 h. Brosser, humidifier, rouler dans le sucre cristal.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "bain-marie + étuve 60 °C (8 h)" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["gomme", "eucalyptus", "fleur d'oranger", "pâte de gomme", "bain-marie", "confiserie"],
    parfum_principal: "eucalyptus",
    note_concepteur: "5 gouttes d'essence d'eucalyptus (non incluses dans la masse). Cette technique à basse température préserve les arômes délicats de l'eucalyptus qui seraient détruits par une cuisson haute. La gomme arabique en morceaux se dissout plus facilement que la poudre et donne une pâte plus limpide.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 104, chef: _CHEF_LN1 },
  },

  {
    id: "reglisse-ln1",
    nom: "Réglisse",
    categorie: "confiseries",
    sous_categorie: "reglisse",
    description: "Pâte de réglisse noire : sucre-glucose cuit à 135 °C, gomme arabique, gélatine et suc de réglisse incorporés, recuit à 120 °C. Coulée en coffrets à amidon, étuvée 24 h. Texture élastique et intense.",
    masse_totale_g: 1145,
    ingredients: [
      { nom: "Gomme arabique",     g: 300, pct: 26, role: "gelifiant"},
      { nom: "Sucre cristal",      g: 300, pct: 27, role: "sucrant"  },
      { nom: "Eau (cuisson)",      g: 200, pct: 17, role: "eau"      },
      { nom: "Gélatine en feuille",g: 120, pct: 10, role: "gelifiant"},
      { nom: "Eau (gélatine)",     g:  80, pct:  7, role: "eau"      },
      { nom: "Glucose",            g:  60, pct:  5, role: "sucrant"  },
      { nom: "Suc de réglisse",    g:  60, pct:  5, role: "parfum"   },
      { nom: "Colorant noir",      g:  25, pct:  3, role: "parfum"   },
    ],
    procede: [
      "Ramollir la gélatine dans les 80 g d'eau froide.",
      "Cuire sucre cristal, glucose et eau (200 g) à 135 °C.",
      "Ajouter la gomme arabique, la gélatine essorée et le suc de réglisse.",
      "Recuire à 120 °C. Ajouter l'essence de menthe ou d'anis (4 gouttes) et le colorant noir.",
      "Couler à l'entonnoir à piston dans coffrets à amidon marqués. Étuver 24 heures.",
      "Sortir, brosser, humidifier à la vapeur, rouler dans le sucre cristal.",
    ],
    cuisson: { temperature_c: 135, duree_min: null, mode: "casserole — 135 °C puis 120 °C + étuve 24 h" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["réglisse", "suc de réglisse", "pâte de gomme", "gélatine", "confiserie", "noir"],
    parfum_principal: "réglisse",
    note_concepteur: "4 gouttes essence de menthe ou d'anis (non incluses dans la masse). La double cuisson (135 °C puis 120 °C après ajout gomme-gélatine-suc) permet de fondre les agents gélifiants sans les dénaturer. Le colorant noir intense est nécessaire — le suc de réglisse seul donne une teinte brun foncé insuffisante.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 105, chef: _CHEF_LN1 },
  },

];
