const _SRC_KB  = "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf";
const _CHEF_KB = "Karim Bourgi";

const _SRC_LN1  = "Chocolats et сonfiserie de l ecole Lenotre T1.pdf";
const _CHEF_LN1 = "François Legras & Stéphane Glacier";

export const RECETTES_CONFITS = [

  /* ── Karim Bourgi ────────────────────────────────────────────────────── */

  {
    id: "confit-pamplemousse-rose-kb",
    nom: "Confit pamplemousse rose",
    categorie: "confits",
    sous_categorie: "confit_agrumes",
    description: "Confit de purée de pamplemousse rose à la pectine NH. Texture gel souple, acidité franche et légère amertume. Utilisé en couche intercalaire dans les travel cakes.",
    masse_totale_g: 600,
    ingredients: [
      { nom: "Purée pamplemousse rose", g: 440, pct: 74, role: "fruit"    },
      { nom: "Sirop de glucose",        g:  75, pct: 12, role: "sucrant"  },
      { nom: "Sucre semoule",           g:  75, pct: 12, role: "sucrant"  },
      { nom: "Pectine NH",              g:  10, pct:  2, role: "gelifiant"},
    ],
    procede: [
      "Chauffer la purée et le glucose à 40°C.",
      "Mélanger le sucre et la pectine NH ensemble pour éviter les grumeaux.",
      "Verser en pluie le mélange sucre-pectine sur la purée chaude en fouettant constamment.",
      "Porter à ébullition.",
      "Transférer dans un bol propre, filmer au contact et réserver jusqu'au montage.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["confit", "pamplemousse", "agrumes", "travel cake", "intercalaire"],
    parfum_principal: "pamplemousse",
    note_concepteur: "Le glucose réduit la cristallisation du sucre et améliore la souplesse du confit à la découpe. Peut se préparer la veille et se conserver au réfrigérateur.",
    source_interne: { fichier_pdf: _SRC_KB, page: 41, chef: _CHEF_KB },
  },

  {
    id: "confit-framboise-kb",
    nom: "Confit framboise",
    categorie: "confits",
    sous_categorie: "confit_fruits_rouges",
    description: "Confit de framboise à la pectine NH, acidulé au citron. Texture gel souple, couche fine pour bûche roulée. L'acidité du citron active la pectine.",
    masse_totale_g: 250,
    ingredients: [
      { nom: "Purée de framboise",  g: 160, pct: 64, role: "fruit"    },
      { nom: "Sirop de glucose",    g:  27, pct: 11, role: "sucrant"  },
      { nom: "Sucre semoule (1)",   g:  33, pct: 13, role: "sucrant"  },
      { nom: "Pectine NH",          g: 3.3, pct:  1, role: "gelifiant"},
      { nom: "Sucre semoule (2)",   g:  10, pct:  4, role: "sucrant"  },
      { nom: "Jus de citron",       g:  17, pct:  7, role: "acidite"  },
    ],
    procede: [
      "Chauffer la purée de framboise avec le glucose et le sucre (1) à 40°C.",
      "Mélanger la pectine NH avec le sucre (2).",
      "Incorporer le mélange pectine-sucre (2) en pluie dans la purée tiède en fouettant. Porter à ébullition en continuant à remuer.",
      "Hors du feu, ajouter le jus de citron et mélanger.",
      "Transférer dans un bol propre, filmer au contact et réfrigérer jusqu'au montage.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["confit", "framboise", "fruits rouges", "bûche roulée", "couche"],
    parfum_principal: "framboise",
    note_concepteur: "Le jus de citron est ajouté hors du feu — le chauffer risquerait de dégrader les arômes et de modifier la prise de la pectine.",
    source_interne: { fichier_pdf: _SRC_KB, page: 135, chef: _CHEF_KB },
  },

  {
    id: "gel-fruit-passion-kb",
    nom: "Gel fruit de la passion",
    categorie: "confits",
    sous_categorie: "gel_fruits",
    description: "Gel passion-glaçage neutre, coulé en demi-sphères et surgelé. Très concentré en fruit de la passion, brillant et translucide. Insert signature pour tartelettes.",
    masse_totale_g: 312,
    ingredients: [
      { nom: "Purée fruit de la passion", g: 100, pct: 32, role: "fruit"    },
      { nom: "Glaçage neutre",            g: 200, pct: 64, role: "gelifiant"},
      { nom: "Sucre semoule",             g:  10, pct:  3, role: "sucrant"  },
      { nom: "Pectine NH",                g:   2, pct:  1, role: "gelifiant"},
    ],
    procede: [
      "Mélanger le glaçage neutre et la purée dans une casserole. Chauffer à 30°C.",
      "Mélanger la pectine NH avec le sucre.",
      "Verser en pluie le mélange pectine-sucre dans la purée tiède en fouettant.",
      "Porter à ébullition, maintenir 5–10 secondes.",
      "Couler immédiatement dans des moules Pomponette silicone d=3.5 cm (ou demi-sphères même diamètre).",
      "Surgeler au moins 3h.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole" },
    temperatures: { service_c: null, conservation_c: -18 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["gel", "fruit de la passion", "insert", "tartelette", "demi-sphère", "surgelé"],
    parfum_principal: "fruit de la passion",
    note_concepteur: "Le glaçage neutre (Absolu Cristal Valrhona ou fait maison) assure la brillance et la tenue du gel. À utiliser congelé : trempé dans le glaçage neutre chaud puis déposé au centre de la tartelette.",
    source_interne: { fichier_pdf: _SRC_KB, page: 156, chef: _CHEF_KB },
  },

  /* ── Eddie Benghanem — Le Grand Cours de Pâtisserie ─────────────────── */

  {
    id: "confit-fruits-rouges-eb",
    nom: "Confit de fruits rouges",
    categorie: "confits",
    sous_categorie: "confit_fruits_rouges",
    description: "Confit framboises+fraises à la pectine NH : acidulé et fruité. Polyvalent pour tartes, entremets, macarons, garnissage. Se conserve au réfrigérateur.",
    masse_totale_g: 380,
    ingredients: [
      { nom: "Purée de framboises", g: 200, pct: 53, role: "fruit"    },
      { nom: "Purée de fraises",    g: 100, pct: 26, role: "fruit"    },
      { nom: "Jus de citron jaune", g:  10, pct:  3, role: "acidite"  },
      { nom: "Sucre inverti",       g:  20, pct:  5, role: "sucrant"  },
      { nom: "Sucre semoule",       g:  50, pct: 13, role: "sucrant"  },
      { nom: "Pectine NH",          g:   8, pct:  2, role: "gelifiant"},
    ],
    procede: [
      "Chauffer la pulpe, le jus de citron et le sucre inverti dans une casserole jusqu'à 45°C.",
      "Mélanger sucre semoule et pectine NH ensemble.",
      "Verser dans la casserole en fouettant. Porter à ébullition.",
      "Réserver.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["confit", "framboises", "fraises", "fruits rouges", "garniture", "macaron"],
    parfum_principal: "framboise",
    note_concepteur: "La pectine NH peut être remplacée par un sucre spécial confiture. Polyvalent : tartes, garnissage de macarons, Opéra, entremets. Ce confit est la base de nombreuses variantes chez Benghanem.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 510,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "confit-cassis-mures-eb",
    nom: "Confit de fruits (cassis-mûres)",
    categorie: "confits",
    sous_categorie: "confit_fruits_rouges",
    description: "Confit cassis+mûres à la pectine NH. Intense et légèrement acidulé. Utilisé en garniture de tartes et entremets.",
    masse_totale_g: 388,
    ingredients: [
      { nom: "Cassis",              g: 200, pct: 52, role: "fruit"    },
      { nom: "Mûres",               g: 100, pct: 26, role: "fruit"    },
      { nom: "Jus de citron jaune", g:  10, pct:  3, role: "acidite"  },
      { nom: "Sucre inverti",       g:  20, pct:  5, role: "sucrant"  },
      { nom: "Sucre semoule",       g:  50, pct: 13, role: "sucrant"  },
      { nom: "Pectine NH",          g:   8, pct:  2, role: "gelifiant"},
    ],
    procede: [
      "Chauffer les fruits, le jus de citron et le sucre inverti à 45°C.",
      "Mélanger sucre + pectine. Verser dans la casserole. Porter à ébullition.",
      "Réserver.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["confit", "cassis", "mûres", "garniture"],
    parfum_principal: "cassis",
    note_concepteur: "Même technique que confit fruits rouges. Le mélange cassis-mûres est plus acidulé et tannique. Pour gâteaux chocolat-fruits rouges.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 510,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "confit-ananas-eb",
    nom: "Confit d'ananas au gingembre",
    categorie: "confits",
    sous_categorie: "confit_fruits",
    description: "Confit d'ananas frais au gingembre, xanthane et vanille, cuit au four à 120°C. Texture confite et caramélisée. Pour tartes exotiques, savarins, verrines.",
    masse_totale_g: 447,
    ingredients: [
      { nom: "Ananas frais",         g: 400, pct: 90, role: "fruit"   },
      { nom: "Sucre semoule",        g:  15, pct:  3, role: "sucrant" },
      { nom: "Gingembre frais",      g:  20, pct:  4, role: "parfum"  },
      { nom: "Gomme de xanthane",    g:   1, pct:  0, role: "liant"   },
      { nom: "Zeste citron vert",    g:   5, pct:  1, role: "parfum"  },
    ],
    procede: [
      "Éplucher l'ananas et couper en dés.",
      "Mélanger tous les ingrédients avec le zeste de citron vert et la gousse de vanille grattée.",
      "Étaler dans un plat couvert. Enfourner à 120°C, 40 min.",
    ],
    cuisson: { temperature_c: 120, duree_min: 40, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["confit", "ananas", "gingembre", "exotique", "savarin", "tarte"],
    parfum_principal: "ananas",
    note_concepteur: "1 gousse de vanille (non incluse). La xanthane est un épaississant naturel — alternative : laisser sans et égoutter davantage. Peut être utilisé chaud (savarin) ou froid (verrine).",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 510,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "guimauve-eb",
    nom: "Guimauve aromatisée (sans blanc d'œuf)",
    categorie: "confits",
    sous_categorie: "guimauve",
    description: "Guimauve gélatine sans blanc d'œuf : sirop sucre+eau+sucre inverti cuit à 110°C, fouetté avec gélatine. Légère, aérienne, aromatisée avec extrait ou arôme. Coulée en cadre 34×34 cm.",
    masse_totale_g: 500,
    ingredients: [
      { nom: "Gélatine feuilles",   g:   8, pct:  2, role: "gelifiant"},
      { nom: "Sucre semoule",       g: 230, pct: 46, role: "sucrant"  },
      { nom: "Eau",                 g:  72, pct: 14, role: "eau"      },
      { nom: "Sucre inverti",       g: 170, pct: 34, role: "sucrant"  },
      { nom: "Arôme alimentaire",   g:  10, pct:  2, role: "parfum"   },
    ],
    procede: [
      "Hydrater la gélatine dans l'eau froide.",
      "Cuire sucre semoule + eau + 70g de sucre inverti à 110°C.",
      "Verser le sucre inverti restant (100g) dans le robot. Verser le sirop chaud dessus. Fouetter 3 min.",
      "Ajouter la gélatine essorée. Continuer à fouetter jusqu'à guimauve tiède.",
      "Ajouter l'arôme. Fouetter encore quelques secondes.",
      "Couler dans le cadre huilé. Laisser reposer 24h à température ambiante.",
      "Démouler, couper en carrés ou bandes. Enrober de sucre cristal (300g sucre + 5g acide citrique + 2g arôme).",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole — sirop 110°C" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["guimauve", "confiserie", "bonbon", "arôme", "sucre"],
    parfum_principal: null,
    note_concepteur: "Ces guimauves peuvent être enrobées de chocolat tempéré (nounours de l'enfance). Conserver au sec dans une boîte hermétique avec un déshydratant. L'arôme peut être remplacé par une huile essentielle alimentaire.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 516,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "nougat-eb",
    nom: "Nougat blanc amandes-pistaches",
    categorie: "confits",
    sous_categorie: "nougat",
    description: "Nougat de Montélimar blanc : blanc d'œuf moussé + miel cuit à 130°C + sirop de sucre à 145°C. Incorporer amandes et pistaches grillées. Repos 24h avant découpe.",
    masse_totale_g: 535,
    ingredients: [
      { nom: "Blanc d'œuf",      g:  30, pct:  6, role: "aeration" },
      { nom: "Sucre semoule (blanc)",g: 18, pct: 3, role: "sucrant"},
      { nom: "Miel",             g: 250, pct: 47, role: "sucrant"  },
      { nom: "Amandes entières", g: 200, pct: 37, role: "parfum"   },
      { nom: "Pistaches mondées",g:  65, pct: 12, role: "parfum"   },
      { nom: "Sucre (sirop)",    g: 200, pct: 37, role: "sucrant"  },
      { nom: "Sirop de glucose", g: 100, pct: 19, role: "sucrant"  },
      { nom: "Eau",              g:  70, pct: 13, role: "eau"      },
    ],
    procede: [
      "Torréfier amandes et pistaches au four à 150°C.",
      "Fouetter le blanc d'œuf avec 18g de sucre dans le robot à petite vitesse jusqu'à mousser (pas trop monté).",
      "Cuire le miel à 130°C dans une casserole.",
      "Cuire le sucre + glucose + eau à 145°C dans une autre casserole.",
      "Verser le miel chaud sur les blancs mousseux en fouettant.",
      "Ajouter le sirop cuit. Fouetter 10–15 min à petite vitesse.",
      "Incorporer amandes et pistaches grillées à la maryse.",
      "Verser dans le cadre sur tapis silicone. Reposer 24h à température ambiante.",
      "Couper en carrés. Emballer dans du papier cristal.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole — miel 130°C + sirop 145°C" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["oeuf", "fruits_a_coque"],
    tags: ["nougat", "amandes", "pistaches", "confiserie", "miel", "Montélimar"],
    parfum_principal: "miel",
    note_concepteur: "Décrocher le nougat du cadre à l'aide d'un pistolet thermique (décollage à chaud). Emballer immédiatement dans du papier cristal pour éviter l'humidification. Conservation à l'abri de l'humidité.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 518,
      chef: "Eddie Benghanem",
    },
  },

  /* ── École Lenôtre T1 — Pâtes de fruits ─────────────────────────────── */

  {
    id: "pate-fruits-figue-ln1",
    nom: "Pâte de fruits figue-cannelle",
    categorie: "confits",
    sous_categorie: "pate_fruits",
    description: "Pâte de fruits figue et jus de poire à la pectine jaune, parfumée à la cannelle. Cuite à 107 °C (76 % Brix), coulée en cadre guitare, roulée dans le sucre roux. Texture ferme et fondante.",
    masse_totale_g: 7080,
    ingredients: [
      { nom: "Jus de poire",         g: 2500, pct: 36, role: "fruit"    },
      { nom: "Pulpe de figue",       g: 1000, pct: 14, role: "fruit"    },
      { nom: "Sucre cristal n°2",    g: 2500, pct: 36, role: "sucrant"  },
      { nom: "Glucose",              g:  600, pct:  8, role: "sucrant"  },
      { nom: "Sucre cristal n°1",    g:  300, pct:  4, role: "sucrant"  },
      { nom: "Pectine jaune",        g:   85, pct:  1, role: "gelifiant"},
      { nom: "Acide tartrique",      g:   50, pct:  1, role: "acidite"  },
      { nom: "Cannelle en poudre",   g:   15, pct:  0, role: "parfum"   },
      { nom: "Eau",                  g:   30, pct:  0, role: "eau"      },
    ],
    procede: [
      "Dans une bassine en cuivre, faire bouillir la pulpe de figue, le jus de poire et la cannelle.",
      "Mélanger la pectine jaune avec les 300 g de sucre (n°1). Verser au fouet dans la pulpe bouillante. Rebouillir.",
      "Ajouter la deuxième partie de sucre et le glucose en mélangeant régulièrement.",
      "Cuire à 76 % Brix au réfractomètre ou 107 °C au thermomètre.",
      "Hors du feu, dissoudre l'acide tartrique dans l'eau et incorporer à la pâte chaude.",
      "Chemiser de papier le fond d'un cadre 36 × 36 cm. Couler 2,7 kg de masse. Laisser refroidir.",
      "Décadrer, retirer la feuille de papier. Humecter les deux faces et saupoudrer de sucre roux.",
      "Découper à la guitare en carrés de 2,5 × 2,5 mm. Rouler dans le sucre roux.",
    ],
    cuisson: { temperature_c: 107, duree_min: null, mode: "bassine cuivre — 76 % Brix" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["pâte de fruits", "confiserie", "figue", "poire", "cannelle", "pectine", "cadre guitare"],
    parfum_principal: "figue",
    note_concepteur: "Recette production : 7,08 kg de masse cuite donne ~2,7 kg de pâte de fruits finie (perte à la cuisson par évaporation). La pectine jaune se mélange au sucre n°1 avant incorporation pour éviter les grumeaux. L'acide tartrique, activateur de prise, ne s'incorpore qu'en fin de cuisson hors du feu.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 64, chef: _CHEF_LN1 },
  },

  {
    id: "pate-fruits-passion-cassis-ln1",
    nom: "Pâte de fruits passion-cassis",
    categorie: "confits",
    sous_categorie: "pate_fruits",
    description: "Pâte de fruits fruit de la Passion et cassis sur jus de poire. Intensément acidulée et parfumée. Coulée en coffrets à amidon (format individuel arrondi) ou en cadre guitare.",
    masse_totale_g: 8118,
    ingredients: [
      { nom: "Sucre cristal n°2",              g: 3500, pct: 43, role: "sucrant"  },
      { nom: "Jus de poire",                   g: 1600, pct: 20, role: "fruit"    },
      { nom: "Glucose",                         g: 1000, pct: 12, role: "sucrant"  },
      { nom: "Pulpe de cassis",                 g:  800, pct: 10, role: "fruit"    },
      { nom: "Pulpe de fruit de la Passion",    g:  800, pct: 10, role: "fruit"    },
      { nom: "Sucre cristal n°1",               g:  300, pct:  4, role: "sucrant"  },
      { nom: "Pectine jaune",                   g:   85, pct:  1, role: "gelifiant"},
      { nom: "Acide tartrique",                 g:   23, pct:  0, role: "acidite"  },
      { nom: "Eau",                             g:   10, pct:  0, role: "eau"      },
    ],
    procede: [
      "Dans une bassine en cuivre, faire bouillir les pulpes de cassis, de fruit de la Passion et le jus de poire.",
      "Mélanger la pectine jaune avec les 300 g de sucre (n°1). Verser au fouet dans les pulpes bouillantes. Rebouillir.",
      "Ajouter la deuxième partie de sucre et le glucose. Cuire à 76 % Brix (107 °C).",
      "Hors du feu, dissoudre l'acide tartrique dans l'eau et incorporer.",
      "Couler dans des coffrets à amidon préalablement marqués à l'empreinte. Laisser refroidir.",
      "Retirer de l'amidon, brosser. Glacer au pistolet (voir recette glaçage pâtes de fruits) ou rouler dans le sucre cristal.",
    ],
    cuisson: { temperature_c: 107, duree_min: null, mode: "bassine cuivre — 76 % Brix" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["pâte de fruits", "confiserie", "passion", "cassis", "pectine", "coffret amidon"],
    parfum_principal: "fruit de la Passion",
    note_concepteur: "Recette production (~8 kg masse, ~2,7 kg par cadre). Le jus de poire allonge et adoucit l'acidité des deux pulpes sans masquer les arômes. La technique coffrets à amidon donne des formats individuels arrondis ; la technique cadre-guitare donne des carrés réguliers.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 70, chef: _CHEF_LN1 },
  },

  {
    id: "pate-fruits-framboise-ln1",
    nom: "Pâte de fruits framboise",
    categorie: "confits",
    sous_categorie: "pate_fruits",
    description: "Pâte de fruits framboise pure à la pectine jaune. Coulée en cadre guitare 36 × 36 cm, découpée à 2,5 × 2,5 mm et roulée dans le sucre cristal. Goût très concentré.",
    masse_totale_g: 6903,
    ingredients: [
      { nom: "Sucre cristal n°2",  g: 3000, pct: 44, role: "sucrant"  },
      { nom: "Pulpe de framboise", g: 2800, pct: 41, role: "fruit"    },
      { nom: "Glucose",            g:  700, pct: 10, role: "sucrant"  },
      { nom: "Sucre cristal n°1",  g:  300, pct:  4, role: "sucrant"  },
      { nom: "Pectine jaune",      g:   70, pct:  1, role: "gelifiant"},
      { nom: "Acide tartrique",    g:   23, pct:  0, role: "acidite"  },
      { nom: "Eau",                g:   10, pct:  0, role: "eau"      },
    ],
    procede: [
      "Dans une bassine en cuivre, faire bouillir la pulpe de framboise.",
      "Mélanger la pectine jaune avec les 300 g de sucre (n°1). Verser au fouet dans la pulpe bouillante. Rebouillir.",
      "Ajouter la deuxième partie de sucre et le glucose. Cuire à 75 % Brix au réfractomètre (106-107 °C).",
      "Hors du feu, dissoudre l'acide tartrique dans l'eau et incorporer.",
      "Chemiser de papier un cadre 36 × 36 cm. Couler 2,7 kg de masse. Laisser refroidir.",
      "Décadrer, retirer la feuille. Humecter les deux faces et saupoudrer de sucre cristal.",
      "Découper à la guitare en carrés de 2,5 × 2,5 mm. Rouler dans le sucre cristal.",
    ],
    cuisson: { temperature_c: 107, duree_min: null, mode: "bassine cuivre — 75 % Brix" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["pâte de fruits", "confiserie", "framboise", "fruits rouges", "pectine", "cadre guitare"],
    parfum_principal: "framboise",
    note_concepteur: "La framboise a naturellement plus de pectine que d'autres fruits, d'où la cuisson à 75 % Brix (légèrement moins que les autres). La gélatinisation se fait à l'acide tartrique en fin de cuisson : ne jamais incorporer en cours de cuisson.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 72, chef: _CHEF_LN1 },
  },

  {
    id: "pate-fruits-citron-vert-ln1",
    nom: "Pâte de fruits citron vert",
    categorie: "confits",
    sous_categorie: "pate_fruits",
    description: "Pâte de fruits citron vert sur fond de poire mixée, parfumée aux sucres zestés. Cuisson poussée à 109 °C (78 % Brix). Format Flexipan® individuel, roulé dans le sucre cristal.",
    masse_totale_g: 1078,
    ingredients: [
      { nom: "Jus de citrons verts",                 g: 400, pct: 37, role: "fruit"    },
      { nom: "Sucre cristal n°2",                    g: 400, pct: 37, role: "sucrant"  },
      { nom: "Poires mixées",                        g: 100, pct: 10, role: "fruit"    },
      { nom: "Glucose",                              g: 100, pct:  9, role: "sucrant"  },
      { nom: "Sucre cristal n°1",                    g:  40, pct:  4, role: "sucrant"  },
      { nom: "Sucre zesté (3 morceaux, zeste citron vert)", g: 15, pct: 1, role: "parfum" },
      { nom: "Pectine jaune",                        g:  10, pct:  1, role: "gelifiant"},
      { nom: "Acide tartrique",                      g:  10, pct:  1, role: "acidite"  },
      { nom: "Eau",                                  g:   3, pct:  0, role: "eau"      },
    ],
    procede: [
      "Dans une bassine en cuivre, faire bouillir le jus de citrons verts avec les poires mixées et les sucres zestés.",
      "Mélanger la pectine jaune avec les 40 g de sucre (n°1). Verser au fouet dans le jus bouillant. Rebouillir.",
      "Ajouter la deuxième partie de sucre et le glucose. Cuire à 78 % Brix (109 °C).",
      "Hors du feu, dissoudre l'acide tartrique dans l'eau et incorporer.",
      "À l'aide d'un entonnoir à piston préchauffé à 80 °C, couler dans des moules Flexipan®. Laisser refroidir.",
      "Démouler. Humecter les surfaces et rouler dans le sucre cristal.",
    ],
    cuisson: { temperature_c: 109, duree_min: null, mode: "bassine cuivre — 78 % Brix" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["pâte de fruits", "confiserie", "citron vert", "agrumes", "flexipan", "pectine"],
    parfum_principal: "citron vert",
    note_concepteur: "La poire mixée adoucit l'acidité vive du citron vert et apporte du pectocellulose naturel. Les sucres frottés sur le zeste (technique de zestage sec) concentrent les huiles essentielles dans le sucre. Cuisson plus poussée (109 °C) pour compenser l'acidité élevée du citron qui retarde la prise.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 73, chef: _CHEF_LN1 },
  },

  {
    id: "pate-fruits-mangue-abricot-ln1",
    nom: "Pâte de fruits mangue-abricot",
    categorie: "confits",
    sous_categorie: "pate_fruits",
    description: "Pâte de fruits mangue et abricot à la pectine jaune. Coulée en cadre guitare, roulée dans le sucre cristal. Équilibre sucre-acidité typique des fruits exotiques Lenôtre.",
    masse_totale_g: 6808,
    ingredients: [
      { nom: "Sucre cristal n°2",  g: 3000, pct: 44, role: "sucrant"  },
      { nom: "Pulpe de mangue",    g: 1500, pct: 23, role: "fruit"    },
      { nom: "Pulpe d'abricot",    g: 1200, pct: 18, role: "fruit"    },
      { nom: "Glucose",            g:  700, pct: 10, role: "sucrant"  },
      { nom: "Sucre cristal n°1",  g:  300, pct:  4, role: "sucrant"  },
      { nom: "Pectine jaune",      g:   75, pct:  1, role: "gelifiant"},
      { nom: "Acide tartrique",    g:   23, pct:  0, role: "acidite"  },
      { nom: "Eau",                g:   10, pct:  0, role: "eau"      },
    ],
    procede: [
      "Dans une bassine en cuivre, faire bouillir les pulpes de mangue et d'abricot.",
      "Mélanger la pectine jaune avec les 300 g de sucre (n°1). Verser au fouet aux pulpes bouillantes. Rebouillir.",
      "Ajouter la deuxième partie de sucre et le glucose en mélangeant régulièrement.",
      "Cuire à 76 % Brix au réfractomètre (107 °C au thermomètre).",
      "Hors du feu, dissoudre l'acide tartrique dans l'eau et incorporer.",
      "Chemiser de papier un cadre 36 × 36 cm. Couler 2,7 kg de masse. Laisser refroidir.",
      "Décadrer, retirer la feuille. Humecter les deux faces et saupoudrer de sucre cristal.",
      "Découper à la guitare en carrés de 2,5 × 2,5 mm. Rouler dans le sucre cristal.",
    ],
    cuisson: { temperature_c: 107, duree_min: null, mode: "bassine cuivre — 76 % Brix" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["pâte de fruits", "confiserie", "mangue", "abricot", "exotique", "pectine", "cadre guitare"],
    parfum_principal: "mangue",
    note_concepteur: "Recette production (~6,8 kg masse, ~2,7 kg par cadre). La mangue apporte le sucre naturel et l'arôme exotique ; l'abricot apporte la pectine naturelle et l'acidité. Rapport pulpes 55/45 favorable à la mangue.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 75, chef: _CHEF_LN1 },
  },

];