const _SRC_LN2  = "Chocolats et сonfiserie de l ecole Lenotre T2.pdf";
const _CHEF_LN2 = "François Legras & Stéphane Glacier";

export const RECETTES_CONFITURES = [

  /* ── École Lenôtre T2 — Confitures & gelées ─────────────────────────── */

  {
    id: "confiture-abricots-ln2",
    nom: "Confiture d'abricots",
    categorie: "confitures",
    sous_categorie: "confiture_fruit",
    description: "Abricots confits 3 jours en sirop progressif (125 °C → cuisson finale 115 °C avec amandes amères). Acide tartrique ajouté en fin de cuisson. Prise en pots retournés.",
    masse_totale_g: 2353,
    ingredients: [
      { nom: "Abricots frais",       g: 1000, pct: 43, role: "fruit"   },
      { nom: "Sucre cristal",        g: 1000, pct: 43, role: "sucrant" },
      { nom: "Eau",                  g:  350, pct: 15, role: "eau"     },
      { nom: "Amandes blanches amères", g: 5, pct:  0, role: "parfum"  },
      { nom: "Acide tartrique",      g:   3, pct:  0, role: "acidite" },
    ],
    procede: [
      "Jour 1 : cuire le sucre et l'eau à 125 °C dans une bassine en cuivre. Verser sur les abricots. Laisser reposer 24 heures.",
      "Jour 2 : égoutter les fruits. Porter le sirop à ébullition et reverser sur les fruits. Laisser reposer 24 heures.",
      "Jour 3 : cuire le tout à 115 °C avec les 5 amandes blanches amères. Ajouter l'acide tartrique en fin de cuisson.",
      "Verser immédiatement en pots de verre. Fermer avec couvercle, retourner le pot. Vide d'air à la prise.",
    ],
    cuisson: { temperature_c: 115, duree_min: null, mode: "bassine cuivre — 3 jours, cuisson finale 115 °C" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["fruits_a_coque_amande"],
    tags: ["confiture", "abricot", "confisage progressif", "amande amère", "acide tartrique"],
    parfum_principal: "abricot",
    note_concepteur: "Le confisage 3 jours (progression du sirop) imprègne les abricots progressivement sans les déformer — c'est la technique confiserie haute gamme. Les 5 amandes amères (non comptées dans la masse) apportent la note d'amande caractéristique de la confiture d'abricots artisanale. L'acide tartrique en fin stabilise la couleur et la pectine.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 63, chef: _CHEF_LN2 },
  },

  {
    id: "confiture-fraise-cannelle-ln2",
    nom: "Confiture fraise/cannelle",
    categorie: "confitures",
    sous_categorie: "confiture_fruit",
    description: "Fraises entières cuites doucement avec sucre et bâtons de cannelle dans une bassine en cuivre jusqu'à 115 °C / 72 % Brix. Acide tartrique en fin. Prise en pots retournés.",
    masse_totale_g: 1803,
    ingredients: [
      { nom: "Fraises fraîches",  g: 1000, pct: 55, role: "fruit"   },
      { nom: "Sucre cristal",     g:  800, pct: 44, role: "sucrant" },
      { nom: "Bâtons de cannelle",g:    4, pct:  0, role: "parfum"  },
      { nom: "Acide tartrique",   g:    3, pct:  0, role: "acidite" },
    ],
    procede: [
      "Laver les fraises, les équeuter.",
      "Cuire les fraises entières dans une bassine en cuivre avec le sucre et les bâtons de cannelle, à feu doux — pour extraire jus et pectine naturelle.",
      "Remuer délicatement. Écumer les impuretés et la mousse.",
      "Cuire jusqu'à 115 °C ou 72 % Brix. Ajouter l'acide tartrique.",
      "Verser immédiatement en pots. Fermer, retourner. Laisser refroidir.",
    ],
    cuisson: { temperature_c: 115, duree_min: null, mode: "bassine cuivre — feu doux, 115 °C / 72 % Brix" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["confiture", "fraise", "cannelle", "bassine cuivre", "pectine naturelle"],
    parfum_principal: "fraise",
    note_concepteur: "La cuisson à feu doux des fraises entières est intentionnelle : elle préserve la couleur rouge et les morceaux. La pectine naturelle de la fraise suffit à faire prendre sans ajout d'épaississant. Les 4 bâtons de cannelle parfument subtilement — ne pas les écraser ni les moudre.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 64, chef: _CHEF_LN2 },
  },

  {
    id: "confiture-rhubarbe-cassis-ln2",
    nom: "Confiture rhubarbe/cassis",
    categorie: "confitures",
    sous_categorie: "confiture_fruit",
    description: "Rhubarbe en tronçons et grains de cassis cuits ensemble avec sucre et pectine ajoutée. Cuisson à 116 °C / 73 % Brix. Acide tartrique en fin. Prise en pots retournés.",
    masse_totale_g: 2632,
    ingredients: [
      { nom: "Rhubarbe",       g: 1000, pct: 38, role: "fruit"   },
      { nom: "Sucre",          g: 1300, pct: 49, role: "sucrant" },
      { nom: "Grains de cassis",g: 300, pct: 11, role: "fruit"   },
      { nom: "Pectine",        g:   30, pct:  1, role: "gelifiant"},
      { nom: "Acide tartrique",g:    2, pct:  0, role: "acidite" },
    ],
    procede: [
      "Laver et éplucher la rhubarbe. Couper en tronçons. Laver les grains de cassis.",
      "Mélanger le sucre et la pectine ensemble.",
      "Dans une bassine en cuivre, porter à ébullition la rhubarbe et le cassis. Ajouter le mélange sucre/pectine.",
      "Écumer. Cuire à 116 °C ou 73 % Brix. Ajouter l'acide tartrique en fin de cuisson.",
      "Verser en pots. Fermer, retourner. Laisser refroidir.",
    ],
    cuisson: { temperature_c: 116, duree_min: null, mode: "bassine cuivre — 116 °C / 73 % Brix" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["confiture", "rhubarbe", "cassis", "pectine", "acidité"],
    parfum_principal: "cassis",
    note_concepteur: "La pectine est mélangée avec le sucre avant incorporation (jamais seule dans le liquide) pour éviter les grumeaux. La rhubarbe est peu pectinée — l'ajout de pectine est indispensable pour la prise. Le cassis apporte couleur violette et note fruitée acidulée qui contre-balance l'acidité végétale de la rhubarbe.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 65, chef: _CHEF_LN2 },
  },

  {
    id: "confiture-tomate-citron-vert-ln2",
    nom: "Confiture tomate/citron vert",
    categorie: "confitures",
    sous_categorie: "confiture_legume",
    description: "Confiture tomate verte (ou rouge) pelée et épépinée avec zeste et jus de citron vert. Sucre et pectine. Cuisson à 117 °C / 74 % Brix. Saveur insolite et sucrée-acidulée.",
    masse_totale_g: 1909,
    ingredients: [
      { nom: "Tomate verte épépinée mondée", g: 800, pct: 42, role: "fruit"   },
      { nom: "Sucre cristal",               g: 1000, pct: 52, role: "sucrant" },
      { nom: "Jus de citron vert",          g:  80, pct:  4, role: "fruit"   },
      { nom: "Pectine",                     g:  25, pct:  1, role: "gelifiant"},
      { nom: "Acide tartrique",             g:   4, pct:  0, role: "acidite" },
    ],
    procede: [
      "Cuire la pulpe de tomate avec le zeste de 3 citrons verts (Q.S.) et le jus de citron vert dans une bassine en cuivre.",
      "Ajouter le sucre mélangé à la pectine.",
      "Porter à ébullition. Écumer.",
      "Cuire à 117 °C ou 74 % Brix. Ajouter l'acide tartrique en fin.",
      "Verser en pots. Fermer, retourner. Laisser refroidir.",
    ],
    cuisson: { temperature_c: 117, duree_min: null, mode: "bassine cuivre — 117 °C / 74 % Brix" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["confiture", "tomate", "citron vert", "insolite", "confiture légume"],
    parfum_principal: "citron",
    note_concepteur: "Zeste de 3 citrons verts (Q.S., non comptés). La tomate verte (non mûre, plus ferme) est préférée pour sa texture et son acidité naturelle. La tomate rouge peut être utilisée mais donne une confiture plus sucrée et moins acidulée. Cette confiture est un accord exotique Lenôtre — la tomate confite au citron vert surprend en dégustation.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 65, chef: _CHEF_LN2 },
  },

  {
    id: "gelee-groseille-ln2",
    nom: "Gelée de groseille",
    categorie: "confitures",
    sous_categorie: "gelee_fruit",
    description: "Gelée de groseille : jus extrait par cuisson douce (1800 g groseilles → 1000 g jus), sucre cristal, cuisson à 117 °C / 75 % Brix. Acide citrique en fin. Translucide et rubis.",
    masse_totale_g: 2010,
    ingredients: [
      { nom: "Groseilles entières",  g: 1800, pct: 89, role: "fruit"   },
      { nom: "Sucre cristal",        g: 1000, pct: 50, role: "sucrant" },
      { nom: "Acide citrique",       g:   10, pct:  0, role: "acidite" },
    ],
    procede: [
      "Cuire les groseilles à feu doux dans une bassine en cuivre pour extraire le jus et libérer la pectine naturelle.",
      "Presser les fruits et extraire 1000 g de jus.",
      "Porter le jus à ébullition. Ajouter le sucre cristal. Porter de nouveau à ébullition.",
      "Écumer les impuretés et la mousse.",
      "Cuire à 117 °C ou 75 % Brix. Ajouter l'acide citrique.",
      "Verser à la louche en pots. Fermer, retourner. Laisser refroidir.",
    ],
    cuisson: { temperature_c: 117, duree_min: null, mode: "bassine cuivre — jus extrait → 117 °C / 75 % Brix" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["gelée", "groseille", "pectine naturelle", "rubis", "confiture"],
    parfum_principal: "groseille",
    note_concepteur: "La pectine naturelle des groseilles est très élevée — aucun ajout nécessaire. Ne jamais presser trop fort lors de l'extraction pour éviter de passer la pulpe (qui trouble la gelée). La cuisson à 75 % Brix (plus haute que les confitures) est nécessaire pour une gelée qui tient ferme à température ambiante.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 67, chef: _CHEF_LN2 },
  },

  {
    id: "gelee-pomme-ln2",
    nom: "Gelée de pomme",
    categorie: "confitures",
    sous_categorie: "gelee_fruit",
    description: "Gelée de pomme : pommes cuites en marmelade, égouttées légèrement (1800 g pommes → 1000 g jus), sucre cristal, cuisson à 116 °C / 73 % Brix. Gelée pâle et translucide.",
    masse_totale_g: 2800,
    ingredients: [
      { nom: "Pommes Granny Smith",  g: 1800, pct: 64, role: "fruit"   },
      { nom: "Sucre cristal",        g: 1000, pct: 36, role: "sucrant" },
    ],
    procede: [
      "Cuire les pommes à feu doux jusqu'à ce qu'elles tombent en marmelade.",
      "Égoutter en pressant légèrement dans un tamis fin. Récupérer 1000 g de jus.",
      "Porter le jus à ébullition dans une bassine en cuivre. Ajouter le sucre cristal. Porter de nouveau à ébullition.",
      "Écumer les impuretés et la mousse.",
      "Cuire à 116 °C ou 73 % Brix.",
      "Verser en pots. Fermer, retourner. Laisser refroidir.",
    ],
    cuisson: { temperature_c: 116, duree_min: null, mode: "bassine cuivre — 116 °C / 73 % Brix" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["gelée", "pomme", "Granny Smith", "pectine naturelle", "confiture"],
    parfum_principal: "pomme",
    note_concepteur: "Les pommes Granny Smith sont préférées (chair ferme, acidité naturelle, haute teneur en pectine) mais toute pomme à chair ferme fonctionne. La pression légère sur le tamis est intentionnelle — une pression forte trouble le jus. La gelée de pomme est aussi utilisée comme base de nappage neutre en pâtisserie.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 68, chef: _CHEF_LN2 },
  },

  {
    id: "confiture-poire-banane-ln2",
    nom: "Confiture poire/banane",
    categorie: "confitures",
    sous_categorie: "confiture_fruit",
    description: "Poires fraîches confites dans un sirop 115 °C avec banane mûre écrasée. Recuites à 115 °C / 72 % Brix. Acide tartrique en fin. Alliance poire-banane fondante et sucrée.",
    masse_totale_g: 1435,
    ingredients: [
      { nom: "Poires fraîches",   g: 1000, pct: 70, role: "fruit"   },
      { nom: "Sucre cristal",     g: 1000, pct: 70, role: "sucrant" },
      { nom: "Eau",               g:  350, pct: 24, role: "eau"     },
      { nom: "Bananes mûres",     g:   80, pct:  6, role: "fruit"   },
      { nom: "Acide tartrique",   g:    5, pct:  0, role: "acidite" },
    ],
    procede: [
      "Laver les poires, les équeuter.",
      "Cuire l'eau et le sucre à 115 °C. Verser sur les fruits dans une bassine en cuivre.",
      "Écumer les impuretés et la mousse.",
      "Faire recuire à 115 °C ou 72 % Brix. Ajouter l'acide tartrique.",
      "Verser en pots. Fermer, retourner. Laisser refroidir.",
    ],
    cuisson: { temperature_c: 115, duree_min: null, mode: "bassine cuivre — sirop 115 °C + recuit 115 °C / 72 % Brix" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["confiture", "poire", "banane", "confisage sirop", "confiture exotique"],
    parfum_principal: "poire",
    note_concepteur: "La masse_totale liste les sucres (1000 g sucre + 350 g eau) et les fruits (1000 g poires + 80 g bananes) séparément mais la confiture finale représente environ 1435 g. La somme des pct dépasse 100 % (a_verifier). La banane mûre s'écrase à la cuisson et parfume discrètement sans dominer.",
    source_interne: { fichier_pdf: _SRC_LN2, page: 68, chef: _CHEF_LN2 },
  },

];
