export const RECETTES_CREMES = [
  {
    id: "cremeux-chocolat-noir",
    nom: "Crémeux chocolat noir",
    categorie: "cremes",
    sous_categorie: "cremeux_chocolat",
    description: "Crémeux onctueux sur base crème anglaise, émulsionné au chocolat noir. Texture fondante et brillante, idéal en insert ou couche d'entremets.",
    masse_totale_g: 345,
    ingredients: [
      { nom: "Crème liquide 35%",       g: 105,  pct: 30,   role: "mg"        },
      { nom: "Lait UHT entier",          g: 105,  pct: 31,   role: "eau"       },
      { nom: "Jaune d'œuf pasteurisé",  g: 40,   pct: 12,   role: "liant"     },
      { nom: "Chocolat noir 67%",        g: 95,   pct: 27,   role: "parfum"    },
    ],
    procede: [
      "Réaliser une crème anglaise avec le lait, la crème et les jaunes d'œufs.",
      "Cuire à 82°C, stopper la cuisson, filtrer et verser sur le chocolat.",
      "Émulsionner au mixeur plongeant sans incorporer d'air.",
      "Couler directement dans les fonds de tartes ou filmer au contact.",
      "Refroidir rapidement à 4°C. Laisser cristalliser 12h minimum avant de pocher.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["crémeux", "chocolat noir", "entremets", "pocher", "base anglaise"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Veiller à réaliser une cuisson juste de la crème anglaise et à peser après cuisson avant d'émulsionner avec le chocolat. Pour une texture optimale à pocher, laisser cristalliser 12h à 4°C.",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 22,
      chef: null,
    },
  },

  {
    id: "cremeux-ultrafondant-noir",
    nom: "Crémeux ultra-fondant chocolat",
    categorie: "cremes",
    sous_categorie: "cremeux_chocolat",
    description: "Crémeux construit à froid sur émulsion lait-chocolat avec gélatine légère. Texture ultra-fondante — ne pas trop travailler avant emploi.",
    masse_totale_g: 464,
    ingredients: [
      { nom: "Crème liquide 35%",  g: 200,  pct: 43,   role: "mg"        },
      { nom: "Lait UHT entier",     g: 100,  pct: 22,   role: "eau"       },
      { nom: "Gélatine 200 bloom",  g: 2,    pct: 0.5,  role: "gelifiant" },
      { nom: "Eau gélatine",        g: 12,   pct: 2.5,  role: "eau"       },
      { nom: "Chocolat 58%",        g: 150,  pct: 32,   role: "parfum"    },
    ],
    procede: [
      "Hydrater la gélatine dans 6× son poids en eau froide (quantités déjà indiquées).",
      "Porter le lait à ébullition, ajouter la masse gélatine et laisser fondre.",
      "Verser sur le chocolat fondu, émulsionner au mixeur plongeant.",
      "Ajouter la crème froide, mixer à nouveau.",
      "Stocker minimum 12h à 4°C avant utilisation.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 10, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["crémeux", "ultra-fondant", "chocolat", "entremets"],
    parfum_principal: "chocolat",
    note_concepteur: "Ce crémeux est ultra fondant : éviter de trop le travailler avant utilisation au risque de le rendre trop liquide.",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 24,
      chef: null,
    },
  },

  {
    id: "creme-patissiere-vanille-01",
    nom: "Crème pâtissière vanille",
    categorie: "cremes",
    sous_categorie: "creme_cuite",
    description: "Crème de base, onctueuse et parfumée à la vanille. Polyvalente : garnissage, fond de tarte, base mousseline.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Lait entier",        g: 600, pct: 60, role: "eau"       },
      { nom: "Sucre semoule",      g: 150, pct: 15, role: "sucrant"   },
      { nom: "Jaunes d'œufs",      g: 120, pct: 12, role: "liant"     },
      { nom: "Amidon de maïs",     g:  60, pct:  6, role: "structure" },
      { nom: "Beurre doux",        g:  60, pct:  6, role: "mg"        },
      { nom: "Vanille (gousse)",   g:  10, pct:  1, role: "parfum"    },
    ],
    procede: [
      "Fendre et gratter la gousse de vanille. Infuser dans le lait chaud 15 min à couvert. Retirer la gousse.",
      "Blanchir les jaunes avec le sucre et l'amidon. Ne pas trop travailler.",
      "Porter le lait vanillé à ébullition. Verser un tiers sur l'appareil jaunes en fouettant.",
      "Reverser dans la casserole. Cuire à feu moyen en fouettant vivement jusqu'à la première ébullition.",
      "Maintenir l'ébullition 1 min pour désactiver l'amylase.",
      "Hors du feu, incorporer le beurre froid en dés en fouettant.",
      "Débarrasser sur plaque filmée au contact. Refroidir rapidement à 4°C.",
    ],
    cuisson: { temperature_c: 100, duree_min: 1, mode: "casserole — ébullition" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["oeuf", "lait"],
    tags: ["vanille", "base", "garnissage", "tarte", "mousseline"],
    parfum_principal: "vanille",
    note_concepteur: "L'ébullition maintenue 1 min est indispensable pour éliminer l'amylase bactérienne et obtenir une crème stable. Un film plastique au contact évite la formation d'une peau.",
    source_interne: {
      fichier_pdf: null,
      page: null,
      chef: null,
    },
  },

  {
    id: "creme-patissiere-chocolat",
    nom: "Crème pâtissière chocolat",
    categorie: "cremes",
    sous_categorie: "creme_patissiere",
    description: "Crème pâtissière au chocolat noir, réalisée par ajout du chocolat hors feu après cuisson. Riche et onctueuse, idéale pour garnissages et compositions.",
    masse_totale_g: 1665,
    ingredients: [
      { nom: "Lait UHT entier",          g: 1000, pct: 60, role: "eau"       },
      { nom: "Sucre semoule",            g: 155,  pct: 9,  role: "sucrant"   },
      { nom: "Jaune d'œuf pasteurisé",  g: 108,  pct: 7,  role: "liant"     },
      { nom: "Amidon de maïs",           g: 80,   pct: 5,  role: "structure" },
      { nom: "Chocolat noir 67%",        g: 322,  pct: 19, role: "parfum"    },
    ],
    procede: [
      "Porter le lait à ébullition.",
      "Verser sur le mélange jaunes d'œufs, sucre semoule et amidon.",
      "Reverser dans la casserole. Cuire 3 min à partir de l'ébullition en fouettant.",
      "Hors du feu, ajouter le chocolat et émulsionner au mixeur plongeant.",
      "Refroidir rapidement à 4°C.",
    ],
    cuisson: { temperature_c: 100, duree_min: 3, mode: "casserole — ébullition" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["crème pâtissière", "chocolat noir", "garnissage", "base"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Il est possible de congeler cette recette : pour une texture stable, remplacer la moitié de l'amidon de maïs par de la farine de blé. Pour une version allégée, ajouter 20g de gélatine 200 bloom (hydratée 6× son poids en eau) par kg de crème puis incorporer une quantité égale de crème fouettée.",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 26,
      chef: null,
    },
  },

  /* ── Bachour PLATED ───────────────────────────────────────────────────── */

  {
    id: "cremeux-vanille-fouette",
    nom: "Crémeux vanille fouetté",
    categorie: "cremes",
    sous_categorie: "cremeux_monte",
    description: "Crémeux vanille réalisé à chaud, réfrigéré 12h puis monté en chantilly. Texture légère et aérée, tenue au pochage.",
    masse_totale_g: 1236,
    ingredients: [
      { nom: "Gélatine en feuilles", g: 8,    pct: 1,  role: "gelifiant" },
      { nom: "Crème liquide 35%",    g: 1000, pct: 80, role: "mg"        },
      { nom: "Sucre semoule",        g: 228,  pct: 19, role: "sucrant"   },
    ],
    procede: [
      "Réhydrater la gélatine.",
      "Porter crème, sucre et gousses de vanille grattées à frémissement. Incorporer la gélatine.",
      "Chinoiser et réfrigérer au minimum 12h.",
      "Monter au batteur jusqu'à texture chantilly ferme. Pocher immédiatement.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 6, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["crémeux", "vanille", "fouetté", "monté", "pocher", "dessert à l'assiette"],
    parfum_principal: "vanille",
    note_concepteur: "Ajouter 2 gousses de vanille fendues et grattées à la crème. Sortir du réfrigérateur 15 min avant de monter pour éviter que la crème ne graisse.",
    source_interne: {
      fichier_pdf: "Bachour _ recipes for the professional chef -- Antonio Bachour & Battman -- 1, 2013 -- Battmann -- 9780933477384 -- 8f96a678d66ca9f975c45792c3fb083b -- Anna's Archive.pdf",
      page: 66,
      chef: null,
    },
  },

  {
    id: "crema-catalana",
    nom: "Crema Catalana",
    categorie: "cremes",
    sous_categorie: "creme_cuite",
    description: "Crème cuite vapeur à la vanille, servie dans des ramequins individuels. Texture ferme et soyeuse, caramélisée au service.",
    masse_totale_g: 1618,
    ingredients: [
      { nom: "Crème liquide 35%", g: 793, pct: 49, role: "mg"      },
      { nom: "Lait entier",       g: 255, pct: 16, role: "eau"     },
      { nom: "Sucre semoule",     g: 300, pct: 18, role: "sucrant" },
      { nom: "Jaunes d'œufs",    g: 270, pct: 17, role: "liant"   },
    ],
    procede: [
      "Porter crème, lait et gousse de vanille grattée à frémissement. Laisser infuser 10 min.",
      "Mélanger jaunes et sucre sans blanchir. Verser le liquide chaud pour tempérer.",
      "Chinoiser et couler dans 24 ramequins.",
      "Cuire en four vapeur combi à 100°C, ventilation haute, 35–45 min.",
      "Réfrigérer jusqu'au service. Saupoudrer de sucre et caraméliser au chalumeau.",
    ],
    cuisson: { temperature_c: 100, duree_min: 40, mode: "bain-marie vapeur" },
    temperatures: { service_c: 6, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait", "oeuf"],
    tags: ["crema catalana", "crème brûlée", "vanille", "ramequin", "dessert à l'assiette"],
    parfum_principal: "vanille",
    note_concepteur: "Le sucre (1,5 cup ≈ 300g) converti depuis l'unité volume — à vérifier. Ajouter une gousse de vanille fendue à la crème.",
    source_interne: {
      fichier_pdf: "Bachour _ recipes for the professional chef -- Antonio Bachour & Battman -- 1, 2013 -- Battmann -- 9780933477384 -- 8f96a678d66ca9f975c45792c3fb083b -- Anna's Archive.pdf",
      page: 68,
      chef: null,
    },
  },

  {
    id: "cremeux-chocolat-noir-64",
    nom: "Crémeux chocolat noir 64%",
    categorie: "cremes",
    sous_categorie: "cremeux_chocolat",
    description: "Crémeux sur base crème anglaise, coulé en moules individuels et réfrigéré. Texture dense et fondante, idéal pour les assiettes.",
    masse_totale_g: 1810,
    ingredients: [
      { nom: "Crème liquide 35%", g: 500, pct: 28, role: "mg"      },
      { nom: "Lait entier",       g: 500, pct: 27, role: "eau"     },
      { nom: "Jaunes d'œufs",    g: 200, pct: 11, role: "liant"   },
      { nom: "Sucre semoule",     g: 100, pct: 6,  role: "sucrant" },
      { nom: "Couverture noir 64%", g: 510, pct: 28, role: "parfum" },
    ],
    procede: [
      "Porter crème et lait à ébullition. Verser sur le mélange jaunes-sucre pour tempérer.",
      "Remettre en casserole et cuire à 82–84°C (crème anglaise). Chinoiser.",
      "Verser sur le chocolat et émulsionner au mixeur plongeant.",
      "Couler dans des moules individuels. Réfrigérer une nuit.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 6, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["crémeux", "chocolat noir", "assiette", "moule individuel"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Recette calibrée pour 24 portions individuelles. La proportion crème/lait égale donne un crémeux plus fluide qu'avec crème seule — bien adaptée au pochage à l'assiette.",
    source_interne: {
      fichier_pdf: "Bachour _ recipes for the professional chef -- Antonio Bachour & Battman -- 1, 2013 -- Battmann -- 9780933477384 -- 8f96a678d66ca9f975c45792c3fb083b -- Anna's Archive.pdf",
      page: 78,
      chef: null,
    },
  },

  {
    id: "panna-cotta-coco",
    nom: "Panna cotta coco",
    categorie: "cremes",
    sous_categorie: "panna_cotta",
    description: "Panna cotta coco-lait concentré, texture onctueuse et fondante. Coulée en bols de service, prise en 6h.",
    masse_totale_g: 1269,
    ingredients: [
      { nom: "Gélatine en feuilles",  g: 10,  pct: 1,  role: "gelifiant" },
      { nom: "Lait entier",           g: 226, pct: 18, role: "eau"       },
      { nom: "Crème liquide 35%",     g: 340, pct: 27, role: "mg"        },
      { nom: "Lait de coco",          g: 396, pct: 31, role: "eau"       },
      { nom: "Lait concentré sucré",  g: 297, pct: 23, role: "sucrant"   },
    ],
    procede: [
      "Réhydrater la gélatine.",
      "Porter lait, crème et lait de coco à ébullition. Incorporer la gélatine.",
      "Hors du feu, incorporer le lait concentré sucré et mélanger.",
      "Couler dans des bols de service. Réfrigérer 6h minimum jusqu'à prise.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 6, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["panna cotta", "coco", "dessert à l'assiette", "verrine"],
    parfum_principal: "coco",
    note_concepteur: "Le lait concentré sucré apporte onctuosité et sucre en une seule étape. Ne pas faire bouillir après ajout du concentré pour éviter toute modification de texture.",
    source_interne: {
      fichier_pdf: "Bachour _ recipes for the professional chef -- Antonio Bachour & Battman -- 1, 2013 -- Battmann -- 9780933477384 -- 8f96a678d66ca9f975c45792c3fb083b -- Anna's Archive.pdf",
      page: 100,
      chef: null,
    },
  },

  {
    id: "panna-cotta-yaourt-grec",
    nom: "Panna cotta yaourt grec",
    categorie: "cremes",
    sous_categorie: "panna_cotta",
    description: "Panna cotta à base de crème et yaourt grec. Texture légèrement acidulée, coulée directement en bols de service.",
    masse_totale_g: 1490,
    ingredients: [
      { nom: "Gélatine en feuilles", g: 10,  pct: 1,  role: "gelifiant" },
      { nom: "Crème liquide 35%",    g: 480, pct: 32, role: "mg"        },
      { nom: "Sucre semoule",        g: 200, pct: 13, role: "sucrant"   },
      { nom: "Yaourt grec",          g: 800, pct: 54, role: "eau"       },
    ],
    procede: [
      "Réhydrater la gélatine.",
      "Porter crème et sucre à frémissement. Incorporer la gélatine.",
      "Hors du feu, incorporer le yaourt grec et mélanger.",
      "Chinoiser et couler dans des bols. Réfrigérer 8h minimum.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 6, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait"],
    tags: ["panna cotta", "yaourt grec", "acidulé", "dessert à l'assiette"],
    parfum_principal: "yaourt",
    note_concepteur: "Quantités converties depuis des tasses (cups) — à vérifier. 2 cups crème ≈ 480g, 3⅓ cups yaourt ≈ 800g.",
    source_interne: {
      fichier_pdf: "Bachour _ recipes for the professional chef -- Antonio Bachour & Battman -- 1, 2013 -- Battmann -- 9780933477384 -- 8f96a678d66ca9f975c45792c3fb083b -- Anna's Archive.pdf",
      page: 102,
      chef: null,
    },
  },

  {
    id: "panna-cotta-lychee",
    nom: "Panna cotta litchi",
    categorie: "cremes",
    sous_categorie: "panna_cotta",
    description: "Panna cotta au litchi, parfumée et délicate. Forte proportion de purée pour une texture légère et aromatique.",
    masse_totale_g: 2260,
    ingredients: [
      { nom: "Gélatine en feuilles", g: 20,   pct: 1,  role: "gelifiant" },
      { nom: "Crème liquide 35%",    g: 840,  pct: 37, role: "mg"        },
      { nom: "Sucre semoule",        g: 200,  pct: 9,  role: "sucrant"   },
      { nom: "Purée de litchi",      g: 1200, pct: 53, role: "fruit"     },
    ],
    procede: [
      "Réhydrater la gélatine.",
      "Porter crème et sucre à frémissement. Incorporer la gélatine.",
      "Chinoiser. Ajouter la purée de litchi et mélanger.",
      "Couler dans des ramequins de 120g. Réfrigérer 6h minimum.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 6, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait"],
    tags: ["panna cotta", "litchi", "dessert à l'assiette", "fruits exotiques"],
    parfum_principal: "litchi",
    note_concepteur: "Quantités converties depuis des tasses — à vérifier. 3,5 cups crème ≈ 840g, 1 cup sucre ≈ 200g, 5 cups purée ≈ 1200g. La forte proportion de purée donne une texture très légère.",
    source_interne: {
      fichier_pdf: "Bachour _ recipes for the professional chef -- Antonio Bachour & Battman -- 1, 2013 -- Battmann -- 9780933477384 -- 8f96a678d66ca9f975c45792c3fb083b -- Anna's Archive.pdf",
      page: 104,
      chef: null,
    },
  },

  /* ── Révolution Pâtisserie — Johanna Le Pape ────────────────────────────── */

  {
    id: "creme-anglaise-lp",
    nom: "Crème anglaise",
    categorie: "cremes",
    sous_categorie: "creme_anglaise",
    description: "Crème anglaise allégée au lait végétal, sucrée au miel. Sans sucre raffiné, sans produits laitiers.",
    masse_totale_g: 180,
    ingredients: [
      { nom: "Lait végétal",  g: 150, pct: 83.3, role: "eau"    },
      { nom: "Miel",          g:  10, pct:  5.6, role: "sucrant" },
      { nom: "Jaune d'œuf",  g:  18, pct: 10.0, role: "liant"  },
      { nom: "Vanille",       g:   2, pct:  1.1, role: "parfum" },
    ],
    procede: [
      "Chauffer le lait végétal avec la vanille et le miel.",
      "Blanchir légèrement le jaune.",
      "Verser le lait chaud sur le jaune en fouettant.",
      "Remettre sur feu doux en remuant jusqu'à 82 °C (nappe la cuillère).",
      "Passer au chinois. Refroidir rapidement.",
    ],
    cuisson: { temperature_c: null, duree_min: 5, mode: "feu doux" },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["oeuf"],
    tags: ["crème anglaise", "lait végétal", "miel", "sans lactose", "sauce"],
    parfum_principal: "vanille",
    note_concepteur: null,
    source_interne: { fichier_pdf: "Révolution-Pâtisserie.-La-bible-de-la-pâtisserie-saine-Johanna-Le-Pape_-Mlanie-Frechon-_-WeLib_organized.pdf", page: 182, chef: "Johanna Le Pape", date_extraction: "2026-05-20" },
  },

  {
    id: "creme-patissiere-lp",
    nom: "Crème pâtissière végétale",
    categorie: "cremes",
    sous_categorie: "creme_patissiere",
    description: "Crème pâtissière 100 % végétale sans œuf : lait végétal, huile de coco, arrow-root et curcuma pour la couleur jaune.",
    masse_totale_g: 287,
    ingredients: [
      { nom: "Lait végétal",        g: 250, pct: 87.1, role: "eau"       },
      { nom: "Sucre roux",          g:  15, pct:  5.2, role: "sucrant"   },
      { nom: "Huile de coco",       g:  10, pct:  3.5, role: "mg"        },
      { nom: "Fécule d'arrow-root", g:  10, pct:  3.5, role: "structure" },
      { nom: "Vanille",             g:   2, pct:  0.7, role: "parfum"    },
      { nom: "Curcuma en poudre",   g: 0.2, pct:  0.1, role: "colorant"  },
    ],
    procede: [
      "Chauffer le lait végétal avec la vanille et le sucre.",
      "Délayer l'arrow-root dans un peu de lait froid.",
      "Verser le lait chaud sur le mélange arrow-root en fouettant.",
      "Remettre sur feu moyen en fouettant jusqu'à épaississement.",
      "Hors du feu, incorporer l'huile de coco et le curcuma.",
      "Filmer au contact, refroidir rapidement.",
    ],
    cuisson: { temperature_c: null, duree_min: 5, mode: "feu moyen" },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["crème pâtissière", "végétale", "arrow-root", "curcuma", "sans oeuf", "vegan"],
    parfum_principal: "vanille",
    note_concepteur: "Le curcuma donne la couleur jaune sans modifier le goût à cette dose. Sans oeuf ni farine : convient aux allergies.",
    source_interne: { fichier_pdf: "Révolution-Pâtisserie.-La-bible-de-la-pâtisserie-saine-Johanna-Le-Pape_-Mlanie-Frechon-_-WeLib_organized.pdf", page: 184, chef: "Johanna Le Pape", date_extraction: "2026-05-20" },
  },

  {
    id: "cremeux-citron-lp",
    nom: "Crémeux citron",
    categorie: "cremes",
    sous_categorie: "cremeux_fruit",
    description: "Crémeux citron sans beurre laitier, émulsionné au beurre de cacao. Texture fondante, acidité franche.",
    masse_totale_g: 322,
    ingredients: [
      { nom: "Purée de citron",     g: 120, pct: 37.3, role: "parfum"    },
      { nom: "Eau",                 g: 100, pct: 31.1, role: "eau"       },
      { nom: "Beurre de cacao",     g:  40, pct: 12.4, role: "mg"        },
      { nom: "Miel",                g:  40, pct: 12.4, role: "sucrant"   },
      { nom: "Fécule d'arrow-root", g:  15, pct:  4.7, role: "structure" },
      { nom: "Zeste de citron",     g:   5, pct:  1.6, role: "parfum"    },
      { nom: "Agar-agar",           g: 0.2, pct:  0.1, role: "structure" },
    ],
    procede: [
      "Mélanger le jus de citron, l'eau, le miel et l'arrow-root à froid.",
      "Chauffer à feu moyen en fouettant jusqu'à épaississement.",
      "Hors du feu, incorporer le beurre de cacao et les zestes.",
      "Verser dans les inserts ou moules. Refroidir.",
    ],
    cuisson: { temperature_c: null, duree_min: 5, mode: "feu moyen" },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["crémeux", "citron", "beurre de cacao", "arrow-root", "vegan", "insert"],
    parfum_principal: "citron",
    note_concepteur: "Présence d'agar-agar estimée depuis contexte — à vérifier sur source p.186.",
    source_interne: { fichier_pdf: "Révolution-Pâtisserie.-La-bible-de-la-pâtisserie-saine-Johanna-Le-Pape_-Mlanie-Frechon-_-WeLib_organized.pdf", page: 186, chef: "Johanna Le Pape", date_extraction: "2026-05-20" },
  },

  {
    id: "creme-caramel-lp",
    nom: "Crème caramel",
    categorie: "cremes",
    sous_categorie: "creme_dessert",
    description: "Crème vanille légèrement caramélisée au sirop de yacon, gélifiée à l'agar-agar. Vegan, sans sucre raffiné.",
    masse_totale_g: 146,
    ingredients: [
      { nom: "Lait végétal",      g: 125, pct: 85.6, role: "eau"       },
      { nom: "Sirop de yacon",    g:  19, pct: 13.0, role: "sucrant"   },
      { nom: "Vanille",           g:   2, pct:  1.4, role: "parfum"    },
      { nom: "Agar-agar",         g: 0.2, pct:  0.1, role: "structure" },
    ],
    procede: [
      "Dans une casserole, chauffer 15g de sirop de yacon jusqu'à caramel léger.",
      "Verser dans le fond du moule.",
      "Chauffer le lait végétal avec la vanille, 4g de sirop de yacon et l'agar-agar jusqu'à frémissement.",
      "Couler sur le caramel. Réfrigérer au moins 2 heures avant de démouler.",
    ],
    cuisson: { temperature_c: null, duree_min: 10, mode: "feu moyen" },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: true },
    a_verifier: true,
    allergenes: [],
    tags: ["crème caramel", "yacon", "agar-agar", "vegan", "ig bas", "sans sucre"],
    parfum_principal: "vanille",
    note_concepteur: "Quantités yacon (15g caramel + 4g crème) estimées depuis lecture visuelle — à vérifier sur source p.218.",
    source_interne: { fichier_pdf: "Révolution-Pâtisserie.-La-bible-de-la-pâtisserie-saine-Johanna-Le-Pape_-Mlanie-Frechon-_-WeLib_organized.pdf", page: 218, chef: "Johanna Le Pape", date_extraction: "2026-05-20" },
  },

  /* ── Karim Bourgi ────────────────────────────────────────────────────── */

  {
    id: "chantilly-vanille-mascarpone-kb",
    nom: "Chantilly vanille-mascarpone",
    categorie: "cremes",
    sous_categorie: "chantilly",
    description: "Chantilly stabilisée gélatine-mascarpone, infusée à la vanille. Cristallisation 12h, montée souple. Texture légère avec tenue prolongée. Utilisée en dôme de tartelettes.",
    masse_totale_g: 466,
    ingredients: [
      { nom: "Crème liquide 35% (1)", g: 200, pct: 43, role: "mg"       },
      { nom: "Crème liquide 35% (2)", g: 200, pct: 43, role: "mg"       },
      { nom: "Masse gélatine 200 bloom", g: 13, pct: 3, role: "gelifiant"},
      { nom: "Sucre semoule",          g:  13, pct:  3, role: "sucrant"  },
      { nom: "Mascarpone",             g:  40, pct:  8, role: "liant"    },
    ],
    procede: [
      "Porter la crème (1) et le sucre à 80°C. Hors du feu, ajouter la masse gélatine et les graines de vanille avec la gousse. Fouetter jusqu'à dissolution. Couvrir, infuser 30 min.",
      "Placer le mascarpone dans un pichet. Chinoiser la crème chaude sur le mascarpone. Mixer au plongeant jusqu'à texture lisse.",
      "Ajouter la crème froide (2), remixer.",
      "Filmer au contact. Réfrigérer 12h.",
      "Monter au batteur jusqu'à pics souples. Pocher immédiatement.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["chantilly", "vanille", "mascarpone", "gélatine", "tartelette", "dôme"],
    parfum_principal: "vanille",
    note_concepteur: "Vanille : 1/5 de gousse (non incluse dans la masse totale). La masse gélatine se prépare : 1g gélatine + 6g eau. Le mascarpone apporte une onctuosité et une tenue supérieures à une chantilly simple.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 59,
      chef: "Karim Bourgi",
    },
  },

  {
    id: "chantilly-chocolat-blanc-fleur-oranger-kb",
    nom: "Chantilly chocolat blanc-fleur d'oranger",
    categorie: "cremes",
    sous_categorie: "chantilly",
    description: "Chantilly stabilisée au chocolat blanc, parfumée à l'eau de fleur d'oranger. Forte proportion de crème (77%) pour légèreté. Stabilisation 12h avant montage. Garniture de tartelettes pistache.",
    masse_totale_g: 970,
    ingredients: [
      { nom: "Crème liquide 35%",        g: 750, pct: 77, role: "mg"       },
      { nom: "Masse gélatine 200 bloom", g:  35, pct:  4, role: "gelifiant" },
      { nom: "Chocolat blanc 30%",       g: 150, pct: 15, role: "liant"    },
      { nom: "Eau de fleur d'oranger",   g:  35, pct:  4, role: "parfum"   },
    ],
    procede: [
      "Porter 250g de crème à 80°C. Verser sur la masse gélatine et le chocolat blanc dans un pichet. Mixer au plongeant.",
      "Ajouter le reste de crème froide et l'eau de fleur d'oranger. Remixer.",
      "Filmer au contact. Réfrigérer 12h.",
      "Monter au batteur jusqu'à pics souples. Ne pas trop serrer.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["chantilly", "chocolat blanc", "fleur d'oranger", "tartelette", "dôme", "pistache"],
    parfum_principal: "fleur d'oranger",
    note_concepteur: "La masse gélatine : ~5g gélatine + 30g eau. Le chocolat blanc stabilise la chantilly sans alourdir la texture. La fleur d'oranger s'ajoute froide pour conserver ses arômes.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 25,
      chef: "Karim Bourgi",
    },
  },

  {
    id: "cremeux-chocolat-anglaise-kb",
    nom: "Crémeux chocolat (base anglaise)",
    categorie: "cremes",
    sous_categorie: "cremeux_chocolat",
    description: "Crémeux chocolat noir sur base crème anglaise classique. Très fort ratio chocolat (27%). Cristallisé 12h, texture dense et brillante, pochage à la poche.",
    masse_totale_g: 1375,
    ingredients: [
      { nom: "Lait 2.5%",                g: 500, pct: 36, role: "eau"    },
      { nom: "Crème liquide 35%",         g: 500, pct: 36, role: "mg"    },
      { nom: "Jaunes d'œufs",            g: 200, pct: 15, role: "liant"  },
      { nom: "Sucre semoule",             g: 100, pct:  7, role: "sucrant"},
      { nom: "Chocolat Araguani 72%",     g: 375, pct: 27, role: "parfum" },
    ],
    procede: [
      "Porter le lait et la crème à ébullition. Verser sur le mélange jaunes-sucre en fouettant pour tempérer.",
      "Reverser en casserole. Cuire à feu doux à 83°C en remuant constamment. Chinoiser.",
      "Fondre le chocolat à 45°C. Verser la crème anglaise chaude progressivement sur le chocolat.",
      "Mixer au plongeant 2 min pour parfaire l'émulsion.",
      "Filmer au contact. Cristalliser 12h au réfrigérateur.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole — anglaise 83°C" },
    temperatures: { service_c: 8, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait", "oeuf"],
    tags: ["crémeux", "chocolat noir", "Araguani", "anglaise", "éclair", "garnissage"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Les pourcentages sont calculés sur le total brut (1675g) mais la réduction à la cuisson donne ~1375g final — les pcts sont indicatifs. Le ratio lait:crème 1:1 donne un crémeux plus fluide, bien adapté au garnissage d'éclairs.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 82,
      chef: "Karim Bourgi",
    },
  },

  {
    id: "cremeux-vanille-opalys-kb",
    nom: "Crémeux vanille intensif (Opalys)",
    categorie: "cremes",
    sous_categorie: "cremeux_chocolat",
    description: "Crémeux vanille sur crème anglaise émulsionné au chocolat blanc Opalys 33%, gélifié léger. Coulé sur le biscuit sacher en insert pour l'Entremet Racine. Texture soyeuse et fondante.",
    masse_totale_g: 315,
    ingredients: [
      { nom: "Lait 3.2%",                     g: 110, pct: 35, role: "eau"    },
      { nom: "Crème liquide 35%",              g:  45, pct: 14, role: "mg"    },
      { nom: "Jaunes d'œufs",                 g:  35, pct: 11, role: "liant"  },
      { nom: "Sucre semoule",                  g:   3, pct:  1, role: "sucrant"},
      { nom: "Masse gélatine 200 bloom",       g:  15, pct:  5, role: "gelifiant"},
      { nom: "Chocolat blanc Opalys 33%",      g: 140, pct: 44, role: "parfum" },
    ],
    procede: [
      "Mélanger le lait, la crème et la vanille dans une casserole. Porter à ébullition.",
      "Battre les jaunes et le sucre. Verser le liquide chaud pour tempérer. Remettre en casserole, cuire à 83–85°C en fouettant.",
      "Hors du feu, chinoiser la crème anglaise dans un pichet. Ajouter la masse gélatine, remuer.",
      "Verser sur le chocolat blanc. Mixer au plongeant jusqu'à émulsion lisse.",
      "Couler directement dans les cercles sur le biscuit sacher (150g par cercle d=16 cm). Surgeler.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole — anglaise 83°C" },
    temperatures: { service_c: 4, conservation_c: -18 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["crémeux", "vanille", "chocolat blanc", "Opalys", "insert", "entremets"],
    parfum_principal: "vanille",
    note_concepteur: "Vanille : 1 gousse (non incluse dans la masse). La masse gélatine : ~2g gélatine + 13g eau. L'Opalys 33% (chocolat blanc Valrhona) donne une note vanillée naturelle intense.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 93,
      chef: "Karim Bourgi",
    },
  },

  {
    id: "cremeux-exotique-passion-kb",
    nom: "Crémeux exotique passion-mangue-yuzu",
    categorie: "cremes",
    sous_categorie: "cremeux_fruit",
    description: "Crémeux sur appareil cuit 4 purées exotiques (passion, calamansi, mangue, yuzu) et jaunes, émulsionné au chocolat blanc Opalys. Acidité vive, texture soyeuse.",
    masse_totale_g: 302,
    ingredients: [
      { nom: "Crème liquide 35%",          g: 40, pct: 13, role: "mg"     },
      { nom: "Purée fruit de la passion",  g: 27, pct:  9, role: "fruit"  },
      { nom: "Purée de calamansi",         g: 27, pct:  9, role: "fruit"  },
      { nom: "Purée de mangue",            g: 27, pct:  9, role: "fruit"  },
      { nom: "Purée de yuzu",              g: 14, pct:  5, role: "fruit"  },
      { nom: "Jaunes d'œufs",             g: 27, pct:  9, role: "liant"  },
      { nom: "Chocolat blanc Opalys 33%",  g: 133, pct: 44, role: "parfum"},
      { nom: "Beurre de cacao",            g:  7, pct:  2, role: "mg"     },
    ],
    procede: [
      "Mélanger la crème, les 4 purées de fruits et les jaunes d'œufs dans une casserole.",
      "Cuire à feu moyen à épaississement en fouettant constamment.",
      "Fondre le chocolat blanc et le beurre de cacao ensemble.",
      "Verser la crème cuite chaude sur le mélange chocolat-beurre de cacao. Mixer au plongeant sans incorporer d'air.",
      "Filmer au contact. Réfrigérer 3–4h.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole — cuisson jusqu'à épaississement" },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["crémeux", "passion", "mangue", "yuzu", "calamansi", "exotique", "tartelette"],
    parfum_principal: "fruit de la passion",
    note_concepteur: "Le beurre de cacao remplace le beurre laitier classique — texture plus fine et moins riche. Appliquer directement dans la tartelette sans attendre que la texture fige complètement.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 157,
      chef: "Karim Bourgi",
    },
  },

  {
    id: "cremeux-pistache-sans-oeuf-kb",
    nom: "Crémeux pistache fouetté (sans œuf)",
    categorie: "cremes",
    sous_categorie: "cremeux_monte",
    description: "Crémeux au praliné pistache Valrhona, sans œuf. Base lait-gélatine émulsionnée au praliné, allongée à la crème froide. Fouetté après stabilisation pour texture légère et pochable.",
    masse_totale_g: 613,
    ingredients: [
      { nom: "Lait 3.2%",                    g:  50, pct:  8, role: "eau"     },
      { nom: "Masse gélatine 200 bloom",      g:  18, pct:  3, role: "gelifiant"},
      { nom: "Praliné pistache Valrhona",     g: 365, pct: 60, role: "parfum"  },
      { nom: "Crème liquide 35%",             g: 180, pct: 29, role: "mg"      },
    ],
    procede: [
      "Chauffer le lait et la masse gélatine à 80°C en remuant jusqu'à dissolution.",
      "Verser progressivement le lait gélifié sur le praliné pistache. Mélanger — la préparation va d'abord se séparer avant de devenir lisse et élastique.",
      "Ajouter la crème froide en filet. Mixer au plongeant pour parfaire l'émulsion.",
      "Filmer au contact. Réfrigérer 12h.",
      "Fouetter au batteur jusqu'à texture légère et pochable.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 6, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "fruits_a_coque"],
    tags: ["crémeux", "pistache", "sans oeuf", "fouetté", "travel cake", "pochage"],
    parfum_principal: "pistache",
    note_concepteur: "La masse gélatine : ~2.5g gélatine + 15g eau ≈ 18g. À la cuisson, le mélange lait-praliné va se séparer temporairement — continuer à mélanger, c'est normal. La crème froide rattrape l'émulsion.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 42,
      chef: "Karim Bourgi",
    },
  },

  /* ── Eddie Benghanem — Le Grand Cours de Pâtisserie ─────────────────── */

  {
    id: "creme-anglaise-eb",
    nom: "Crème anglaise",
    categorie: "cremes",
    sous_categorie: "creme_anglaise",
    description: "Crème anglaise classique : lait+crème+vanille, cuite à 82°C avec jaunes et sucre. Texture nappante. Base de nombreuses crèmes (chiboust, diplomate, mousseline, bavarois).",
    masse_totale_g: 500,
    ingredients: [
      { nom: "Lait entier",       g: 170, pct: 34, role: "eau"    },
      { nom: "Crème liquide 35%", g: 200, pct: 40, role: "mg"     },
      { nom: "Sucre semoule",     g:  80, pct: 16, role: "sucrant"},
      { nom: "Jaunes d'œufs",    g: 100, pct: 20, role: "liant"  },
    ],
    procede: [
      "Porter à ébullition le lait, la crème, la gousse de vanille fendue et grattée avec la moitié du sucre.",
      "Fouetter les jaunes avec le sucre restant jusqu'à blanchiment.",
      "Verser la moitié du liquide bouillant sur les jaunes. Mélanger. Reverser dans la casserole.",
      "Cuire à feu moyen jusqu'à 82°C sans cesser de remuer avec une spatule.",
      "Filtrer à travers une passoire fine. Filmer au contact. Réfrigérer.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole — anglaise 82°C" },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["crème anglaise", "sauce", "base", "vanille", "bavarois", "île flottante"],
    parfum_principal: "vanille",
    note_concepteur: "Vanille : 1 gousse non incluse dans la masse. Si la crème est trop cuite, mixez-la à nouveau. La crème nappant la cuillère est le signe d'une cuisson correcte. Base de bavarois, chiboust, mousse.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 352,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "creme-patissiere-eb",
    nom: "Crème pâtissière",
    categorie: "cremes",
    sous_categorie: "creme_patissiere",
    description: "Crème pâtissière de base Benghanem : 25cl lait, jaunes-sucre-poudre flan, beurre hors feu. Simple et rapide. Base de choux, éclairs, millefeuille, tarte aux fruits.",
    masse_totale_g: 500,
    ingredients: [
      { nom: "Lait entier",    g: 250, pct: 50, role: "eau"      },
      { nom: "Jaunes d'œufs", g:  60, pct: 12, role: "liant"    },
      { nom: "Sucre semoule",  g:  60, pct: 12, role: "sucrant"  },
      { nom: "Poudre à flan",  g:  25, pct:  5, role: "structure"},
      { nom: "Beurre",         g:  25, pct:  5, role: "mg"       },
    ],
    procede: [
      "Porter à ébullition le lait avec la moitié du sucre dans une casserole.",
      "Fouetter les jaunes et le sucre restant dans un cul-de-poule. Incorporer la poudre à flan.",
      "Verser un tiers du lait bouillant sur le mélange jaunes. Mélanger au fouet.",
      "Reverser dans la casserole et cuire à feu moyen sans cesser de remuer.",
      "Dès que la crème épaissit, retirer du feu. Ajouter le beurre. Mélanger.",
      "Débarrasser dans un plat, filmer au contact, réfrigérer minimum 1h.",
    ],
    cuisson: { temperature_c: 100, duree_min: 3, mode: "casserole" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["crème pâtissière", "base", "choux", "éclair", "millefeuille", "tarte"],
    parfum_principal: "vanille",
    note_concepteur: "Refroidir rapidement la crème. La fécule de maïs peut remplacer la poudre à flan. Peut servir à garnir des choux : remplir une poche, percer le fond du chou.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 358,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "creme-patissiere-chocolat-eb",
    nom: "Crème pâtissière au chocolat",
    categorie: "cremes",
    sous_categorie: "creme_patissiere",
    description: "Variante chocolat de la crème pâtissière : lait+crème, jaunes-sucre-poudre flan, chocolat noir 64% et cacao hors feu. Pour garnissage choux, éclairs, mille-feuilles chocolat.",
    masse_totale_g: 450,
    ingredients: [
      { nom: "Lait entier",        g: 200, pct: 44, role: "eau"      },
      { nom: "Crème liquide 35%",  g:  50, pct: 11, role: "mg"       },
      { nom: "Sucre semoule",      g:  30, pct:  7, role: "sucrant"  },
      { nom: "Jaunes d'œufs",     g:  60, pct: 13, role: "liant"    },
      { nom: "Poudre à flan",      g:  15, pct:  3, role: "structure"},
      { nom: "Chocolat noir 64%",  g:  90, pct: 20, role: "parfum"   },
      { nom: "Cacao en poudre",    g:   5, pct:  1, role: "parfum"   },
    ],
    procede: [
      "Porter lait et crème à ébullition avec la moitié du sucre.",
      "Fouetter les jaunes et le sucre restant. Incorporer la poudre à flan.",
      "Verser 1/3 du liquide chaud sur les jaunes, reverser dans la casserole.",
      "Cuire 2 min à feu moyen en fouettant.",
      "Hors du feu, ajouter le chocolat haché et le cacao. Mixer au plongeant.",
      "Verser dans un plat, filmer au contact. Réserver 2h au froid.",
    ],
    cuisson: { temperature_c: 100, duree_min: 2, mode: "casserole" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["crème pâtissière", "chocolat", "choux chocolat", "éclair", "garnissage"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Ajout du cacao en poudre en plus du chocolat fondu : double intensité chocolatée. Mixer au plongeant pour obtenir une texture parfaitement lisse.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 359,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "creme-chiboust-eb",
    nom: "Crème chiboust",
    categorie: "cremes",
    sous_categorie: "creme_chiboust",
    description: "Crème chiboust : crème pâtissière allégée à la gélatine et meringue italienne. Légère, aérée, utiliser aussitôt. Pour Saint-Honoré, tarte Tatin chiboust. Se caramélise au chalumeau.",
    masse_totale_g: 600,
    ingredients: [
      { nom: "Lait entier",    g: 250, pct: 42, role: "eau"      },
      { nom: "Œufs entiers",  g: 125, pct: 21, role: "liant"    },
      { nom: "Sucre semoule",  g: 120, pct: 20, role: "sucrant"  },
      { nom: "Poudre à flan",  g:  25, pct:  4, role: "structure"},
      { nom: "Gélatine feuilles",g: 2, pct:  0, role: "gelifiant"},
    ],
    procede: [
      "Séparer blancs et jaunes.",
      "Réaliser une crème pâtissière avec les jaunes, 20g de sucre, la poudre à flan et le lait.",
      "Tremper les feuilles de gélatine dans l'eau froide. Les incorporer à la crème pâtissière chaude. Mixer.",
      "Monter les blancs en neige avec le sucre restant (100g).",
      "Incorporer un peu de blancs montés à la crème pour faire un pré-mélange.",
      "Puis incorporer le reste délicatement à la maryse. Utiliser aussitôt.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole — crème pâtissière" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["chiboust", "Saint-Honoré", "légère", "gélatine", "meringue", "chalumeau"],
    parfum_principal: "vanille",
    note_concepteur: "Le lait peut être remplacé par la même quantité de jus de fruit de la Passion par exemple. Pocher sur des sablés bretons et caraméliser comme une crème brûlée. Utiliser aussitôt — ne supporte pas le stockage monté.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 364,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "creme-diplomate-eb",
    nom: "Crème diplomate",
    categorie: "cremes",
    sous_categorie: "creme_diplomate",
    description: "Crème pâtissière gélifiée + crème fouettée. Texture légère et ferme, tient au pochage. Garnissage de tartes aux fruits, choux, millefeuille. Peut être légèrement alcoolisée.",
    masse_totale_g: 500,
    ingredients: [
      { nom: "Lait entier",    g: 250, pct: 50, role: "eau"      },
      { nom: "Sucre semoule",  g:  50, pct: 10, role: "sucrant"  },
      { nom: "Jaunes d'œufs", g:  50, pct: 10, role: "liant"    },
      { nom: "Poudre à flan",  g:  20, pct:  4, role: "structure"},
      { nom: "Beurre",         g:  25, pct:  5, role: "mg"       },
      { nom: "Gélatine feuilles",g: 5, pct:  1, role: "gelifiant"},
      { nom: "Crème liquide 35%",g: 150, pct: 30, role: "aeration"},
    ],
    procede: [
      "Réhydrater la gélatine 10 min dans l'eau froide.",
      "Réaliser une crème pâtissière : lait + moitié sucre à ébullition, jaunes + sucre restant + poudre à flan.",
      "Cuire jusqu'à épaississement. Hors du feu : beurre + gélatine essorée. Mélanger.",
      "Verser dans un plat, filmer au contact, réfrigérer 1h30.",
      "Monter la crème liquide froide en chantilly.",
      "Fouetter la crème pâtissière refroidie pour la lisser. Incorporer délicatement la chantilly.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole — crème pâtissière" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["crème diplomate", "légère", "tarte", "choux", "millefeuille", "alcoolisable"],
    parfum_principal: "vanille",
    note_concepteur: "La gélatine assure la tenue une fois incorporée à la chantilly. La crème peut être légèrement alcoolisée. Garnit les tartes aux fruits frais, les mille-feuilles, les choux.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 372,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "creme-mousseline-eb",
    nom: "Crème mousseline nature",
    categorie: "cremes",
    sous_categorie: "creme_mousseline",
    description: "Crème mousseline : crème pâtissière + beurre pommade monté jusqu'à texture mousseuse. Ferme une fois refroidie. Pour fraisier, Paris-Brest. Peut être parfumée.",
    masse_totale_g: 500,
    ingredients: [
      { nom: "Lait entier",    g: 250, pct: 50, role: "eau"      },
      { nom: "Sucre semoule",  g:  60, pct: 12, role: "sucrant"  },
      { nom: "Jaunes d'œufs", g:  75, pct: 15, role: "liant"    },
      { nom: "Poudre à flan",  g:  25, pct:  5, role: "structure"},
      { nom: "Beurre (CP)",    g:  25, pct:  5, role: "mg"       },
      { nom: "Beurre pommade", g: 140, pct: 28, role: "mg"       },
    ],
    procede: [
      "Réaliser une crème pâtissière à la vanille : lait + moitié sucre à ébullition, jaunes + sucre + poudre à flan, cuire jusqu'à épaississement. Ajouter les 25g de beurre. Filmer, refroidir.",
      "Fouetter la crème pâtissière refroidie au batteur pour la lisser.",
      "Travailler les 140g de beurre pommade à la spatule pour l'assouplir.",
      "Ajouter progressivement le beurre dans la crème en fouettant à vitesse moyenne jusqu'à texture mousseuse et légère.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole — crème pâtissière" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["mousseline", "fraisier", "Paris-Brest", "beurre", "pochage"],
    parfum_principal: "vanille",
    note_concepteur: "Vanille : 1 gousse (non incluse). Monter à vitesse moyenne. Comme elle contient du beurre, elle est bien ferme une fois refroidie. Utiliser pour fraisier ou succès noisette.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 378,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "creme-mousseline-pralinee-eb",
    nom: "Crème mousseline pralinée",
    categorie: "cremes",
    sous_categorie: "creme_mousseline",
    description: "Crème mousseline riche au praliné noisette. Pour Paris-Brest. Proportions de la tarte tropézienne / brioche : 50cl lait, 6 jaunes, 330g beurre final.",
    masse_totale_g: 1060,
    ingredients: [
      { nom: "Lait entier",        g: 500, pct: 47, role: "eau"      },
      { nom: "Sucre semoule",      g: 120, pct: 11, role: "sucrant"  },
      { nom: "Jaunes d'œufs",     g: 150, pct: 14, role: "liant"    },
      { nom: "Poudre à flan",      g:  50, pct:  5, role: "structure"},
      { nom: "Beurre (CP)",        g:  50, pct:  5, role: "mg"       },
      { nom: "Beurre pommade",     g: 280, pct: 26, role: "mg"       },
      { nom: "Praliné noisettes",  g: 150, pct: 14, role: "parfum"   },
    ],
    procede: [
      "Crème pâtissière : lait + moitié sucre à ébullition + gousses vanille. Jaunes + sucre restant + poudre à flan. Cuire. Ajouter 50g beurre. Filmer, refroidir.",
      "Fouetter la crème pâtissière refroidie dans le robot.",
      "Ajouter progressivement le beurre pommade en fouettant.",
      "Incorporer le praliné noisettes. Fouetter jusqu'à texture mousseuse.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole — crème pâtissière" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf", "fruits_a_coque"],
    tags: ["mousseline", "praliné", "noisette", "Paris-Brest", "Succès"],
    parfum_principal: "noisette",
    note_concepteur: "Vanille : 2 gousses (non incluses). Proportions basées sur la recette du fraisier/tropézienne Benghanem (50cl lait, 6 jaunes, 330g beurre total). Utiliser pour Paris-Brest classique avec éclats de noisettes.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 379,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "creme-au-beurre-eb",
    nom: "Crème au beurre (anglaise + meringue italienne)",
    categorie: "cremes",
    sous_categorie: "creme_au_beurre",
    description: "Crème au beurre complète : crème anglaise 82°C + beurre pommade fouetté, puis meringue italienne incorporée. Légère et aérienne. Pour moka, Opéra, Merveilleuse.",
    masse_totale_g: 800,
    ingredients: [
      { nom: "Lait entier",         g:  67, pct:  8, role: "eau"    },
      { nom: "Sucre semoule (CA)",  g:  67, pct:  8, role: "sucrant"},
      { nom: "Jaunes d'œufs",      g:  54, pct:  7, role: "liant"  },
      { nom: "Beurre pommade",      g: 410, pct: 51, role: "mg"     },
      { nom: "Eau (MI)",            g:  40, pct:  5, role: "eau"    },
      { nom: "Sucre semoule (MI)",  g: 130, pct: 16, role: "sucrant"},
      { nom: "Blancs d'œufs",      g:  70, pct:  9, role: "aeration"},
    ],
    procede: [
      "Crème anglaise : porter lait + moitié sucre à ébullition. Fouetter jaunes + sucre restant. Reverser dans casserole, cuire à 82°C. Refroidir au robot.",
      "Ajouter progressivement le beurre pommade en fouettant jusqu'à crème homogène.",
      "Meringue italienne : eau + sucre à 118°C. Monter les blancs en parallèle. Verser sirop cuit sur les blancs. Fouetter jusqu'à refroidissement.",
      "Incorporer délicatement la meringue italienne dans la crème au beurre foisonnée.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole — crème anglaise 82°C" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["crème au beurre", "moka", "Opéra", "Merveilleuse", "légère"],
    parfum_principal: null,
    note_concepteur: "Une crème au beurre bien montée est très légère et agréable en goût. Monter à vitesse moyenne. Peut être parfumée au café, au praliné ou autre extrait. La meringue italienne aérée allège la texture.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 388,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "creme-brulee-eb",
    nom: "Crème brûlée",
    categorie: "cremes",
    sous_categorie: "creme_brulee",
    description: "Crème brûlée classique à la vanille : forte proportion crème (35cl), cuisson douce à 100°C 40 min. Infusion 10 min. Caramelisée à la cassonade au chalumeau avant service.",
    masse_totale_g: 610,
    ingredients: [
      { nom: "Lait entier",       g: 125, pct: 20, role: "eau"    },
      { nom: "Crème liquide 35%", g: 350, pct: 57, role: "mg"     },
      { nom: "Sucre semoule",     g:  75, pct: 12, role: "sucrant"},
      { nom: "Jaunes d'œufs",    g:  95, pct: 16, role: "liant"  },
    ],
    procede: [
      "Préchauffer le four à 100°C.",
      "Porter à ébullition le lait, la crème et les gousses de vanille fendues et grattées. Laisser infuser 10 min.",
      "Fouetter les jaunes avec le sucre dans un cul-de-poule.",
      "Verser le lait vanillé froid sur les jaunes. Mélanger.",
      "Remplir les ramequins de 8 cm. Cuire 40 min.",
      "Refroidir à température ambiante. Saupoudrer de cassonade. Caraméliser au chalumeau.",
    ],
    cuisson: { temperature_c: 100, duree_min: 40, mode: "four traditionnel — sans bain-marie" },
    temperatures: { service_c: 6, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["crème brûlée", "vanille", "chalumeau", "cassonade", "ramequin"],
    parfum_principal: "vanille",
    note_concepteur: "2 gousses de vanille (non incluses). Ne pas chercher à ne faire mousser les jaunes et le sucre. La crème est tremblotante en sortie du four — elle se fige en refroidissant.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 396,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "panna-cotta-classique-eb",
    nom: "Panna cotta classique vanille",
    categorie: "cremes",
    sous_categorie: "panna_cotta",
    description: "Panna cotta pure crème : 50cl crème + 50g sucre + vanille + gélatine. Texture ferme et onctueuse. La plus classique des panna cottas. Utiliser sans tarder après la prise.",
    masse_totale_g: 510,
    ingredients: [
      { nom: "Crème liquide 35%", g: 500, pct: 98, role: "mg"       },
      { nom: "Sucre semoule",     g:  50, pct: 10, role: "sucrant"  },
      { nom: "Gélatine feuilles", g:   4, pct:  1, role: "gelifiant"},
    ],
    procede: [
      "Hydrater la gélatine 20 min dans l'eau froide.",
      "Porter la crème, le sucre et la gousse de vanille fendue et grattée à ébullition.",
      "Ajouter la gélatine essorée. Mélanger au fouet ou mixer au plongeant.",
      "Filtrer et verser dans les verrines ou moules.",
      "Réfrigérer minimum 3h jusqu'à prise.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole" },
    temperatures: { service_c: 6, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["panna cotta", "vanille", "crème", "verrine", "classique"],
    parfum_principal: "vanille",
    note_concepteur: "1 gousse de vanille (non incluse). La proportion gélatine/crème donne une texture ferme mais fondante. Peut être démoulée si réalisée en moule silicone.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 408,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "panna-cotta-cremeuse-vanille-eb",
    nom: "Panna cotta crémeuse vanille (au chocolat blanc)",
    categorie: "cremes",
    sous_categorie: "panna_cotta",
    description: "Panna cotta crémeuse stabilisée au chocolat blanc : lait+crème+vanille+chocolat blanc+mascarpone. Texture très onctueuse, peut être foisonnée au batteur pour obtenir une mousse. Polyvalente.",
    masse_totale_g: 530,
    ingredients: [
      { nom: "Crème liquide 35%", g: 150, pct: 28, role: "mg"       },
      { nom: "Lait entier",       g: 150, pct: 28, role: "eau"      },
      { nom: "Chocolat blanc",    g: 125, pct: 24, role: "liant"    },
      { nom: "Mascarpone",        g:  50, pct:  9, role: "liant"    },
      { nom: "Gélatine feuilles", g:   6, pct:  1, role: "gelifiant"},
    ],
    procede: [
      "Hydrater la gélatine 20 min dans l'eau froide.",
      "Porter à ébullition la crème et les gousses de vanille fendues et grattées.",
      "Filtrer le liquide sur le chocolat blanc haché. Ajouter la gélatine essorée.",
      "Incorporer le mascarpone. Mixer au plongeant.",
      "Filmer et réfrigérer minimum 3h.",
      "Pour foisonner : monter au batteur avant utilisation pour obtenir une panna cotta mousseuse.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole" },
    temperatures: { service_c: 6, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["panna cotta", "crémeuse", "chocolat blanc", "mascarpone", "foisonnable", "mousse"],
    parfum_principal: "vanille",
    note_concepteur: "1–2 gousses de vanille (non incluses). Le chocolat blanc est un agent texturant : son goût est relativement neutre et permet des crèmes aux fruits. Peut être foisonnée = mousse de panna cotta. Versatile pour entremets.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 408,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "panna-cotta-coco-eb",
    nom: "Panna cotta crémeuse à la coco",
    categorie: "cremes",
    sous_categorie: "panna_cotta",
    description: "Variante coco de la panna cotta crémeuse : purée de coco remplace le lait. Riche, exotique, texture onctueuse. Peut être foisonnée. Pour verrines, entremets, esquimaux.",
    masse_totale_g: 406,
    ingredients: [
      { nom: "Crème liquide 35%", g:  75, pct: 18, role: "mg"       },
      { nom: "Purée de noix de coco", g: 150, pct: 37, role: "parfum"},
      { nom: "Chocolat blanc",    g: 125, pct: 31, role: "liant"    },
      { nom: "Mascarpone",        g:  50, pct: 12, role: "liant"    },
      { nom: "Gélatine feuilles", g:   6, pct:  1, role: "gelifiant"},
    ],
    procede: [
      "Hydrater la gélatine 20 min dans l'eau froide.",
      "Chauffer la crème et la verser sur le chocolat blanc avec la gélatine essorée.",
      "Incorporer le mascarpone et la purée de coco. Mixer au plongeant.",
      "Filmer au contact. Réfrigérer minimum 3h.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole" },
    temperatures: { service_c: 6, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["panna cotta", "coco", "exotique", "verrine", "mousse coco"],
    parfum_principal: "coco",
    note_concepteur: "La purée de coco remplace entièrement le lait — résultat plus riche que si on fait moitié-moitié. Peut être foisonnée en mousse de panna cotta coco.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 409,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "panna-cotta-cafe-eb",
    nom: "Panna cotta crémeuse au café",
    categorie: "cremes",
    sous_categorie: "panna_cotta",
    description: "Panna cotta crémeuse infusée au café double (moulu + soluble), stabilisée au chocolat blond Dulcey et mascarpone. Arôme intense. Pour tartes au café, verrines, entremets.",
    masse_totale_g: 423,
    ingredients: [
      { nom: "Lait entier",         g: 150, pct: 35, role: "eau"    },
      { nom: "Crème liquide 35%",   g: 150, pct: 35, role: "mg"     },
      { nom: "Chocolat blond Dulcey",g: 125, pct: 30, role: "liant" },
      { nom: "Mascarpone",          g:  50, pct: 12, role: "liant"  },
      { nom: "Café moulu",          g:   7, pct:  2, role: "parfum" },
      { nom: "Café soluble",        g:   1, pct:  0, role: "parfum" },
      { nom: "Gélatine feuilles",   g:   6, pct:  1, role: "gelifiant"},
    ],
    procede: [
      "Hydrater la gélatine dans l'eau froide.",
      "Porter lait et crème à ébullition. Ajouter le café moulu et le café soluble. Laisser infuser.",
      "Filtrer. Ajouter la gélatine essorée. Verser sur le chocolat blond haché.",
      "Incorporer le mascarpone. Mixer. Filmer. Réfrigérer 24h.",
      "Monter au batteur le jour même si utilisation foisonnée.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole" },
    temperatures: { service_c: 6, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["panna cotta", "café", "Dulcey", "mascarpone", "verrine", "tarte café"],
    parfum_principal: "café",
    note_concepteur: "L'association café moulu + soluble donne une profondeur aromatique maximale. Le chocolat blond Dulcey apporte une note caramel biscuitée qui complète le café. Stabilisation 24h recommandée.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 409,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "creme-citron-eb",
    nom: "Crème au citron",
    categorie: "cremes",
    sous_categorie: "cremeux_fruit",
    description: "Crème citron Benghanem : lait + sucre + œufs + jus citron jaune+vert + zestes, cuit au bain-marie à 82°C, puis chocolat blanc + beurre de cacao. Texture fondante, acidité franche.",
    masse_totale_g: 400,
    ingredients: [
      { nom: "Lait entier",             g:  80, pct: 20, role: "eau"    },
      { nom: "Sucre semoule",           g:  50, pct: 13, role: "sucrant"},
      { nom: "Œufs entiers",           g: 150, pct: 38, role: "liant"  },
      { nom: "Jus de citron jaune",     g:  65, pct: 16, role: "parfum" },
      { nom: "Jus de citron vert",      g:  40, pct: 10, role: "parfum" },
      { nom: "Chocolat blanc 35%",      g: 130, pct: 33, role: "liant"  },
      { nom: "Beurre de cacao",         g:  10, pct:  3, role: "mg"     },
    ],
    procede: [
      "Hydrater la gélatine 10 min dans l'eau froide.",
      "Verser dans un cul-de-poule : lait, sucre, œufs battus, jus et zestes des deux citrons.",
      "Mixer 2 min au plongeant.",
      "Cuire au bain-marie sans cesser de remuer jusqu'à 82°C et épaississement.",
      "Ajouter la gélatine essorée, le chocolat blanc et le beurre de cacao. Mixer 2 min.",
      "Filmer au contact. Réfrigérer jusqu'à refroidissement.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "bain-marie — 82°C" },
    temperatures: { service_c: 6, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["crème citron", "curd", "tarte citron", "acidulé", "tartelette"],
    parfum_principal: "citron",
    note_concepteur: "7g gélatine feuilles (3.5 feuilles) — non incluse dans masse totale. Zestes de 2 citrons verts et jaunes en plus du jus. Mélanger les jus : verts, jaunes et yuzu pour varier. Pocher sur sablé breton pour une tarte citron.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 424,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "creme-marrons-eb",
    nom: "Crème aux marrons pour Mont-blanc",
    categorie: "cremes",
    sous_categorie: "creme_marrons",
    description: "Crème marrons ultra-simple 3 ingrédients : crème de marrons + pâte de marrons + crème liquide. À dresser directement à la douille à vermicelles. Base du Mont-blanc.",
    masse_totale_g: 460,
    ingredients: [
      { nom: "Crème de marrons", g: 200, pct: 43, role: "parfum"  },
      { nom: "Pâte de marrons",  g: 200, pct: 43, role: "parfum"  },
      { nom: "Crème liquide 35%",g:  60, pct: 13, role: "mg"      },
    ],
    procede: [
      "Mélanger les 3 ingrédients.",
      "Mettre dans une poche à douille à vermicelles pour le Mont-blanc.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["marrons", "Mont-blanc", "crème de marrons", "pâte de marrons", "vermicelles"],
    parfum_principal: "marron",
    note_concepteur: "Recette de base — certaines versions ajoutent de l'alcool (whisky, cognac). La douille à vermicelles (ou spaghetti) est indispensable pour l'effet Mont-blanc.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 434,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "chantilly-eb",
    nom: "Chantilly au mascarpone",
    categorie: "cremes",
    sous_categorie: "chantilly",
    description: "Chantilly enrichie au mascarpone : plus stable et onctueuse qu'une chantilly pure crème. Montée au batteur. Pour merveilleuses, gâteaux, décorations. Peut être parfumée.",
    masse_totale_g: 400,
    ingredients: [
      { nom: "Mascarpone froid",  g: 150, pct: 38, role: "liant"  },
      { nom: "Crème liquide 35%", g: 225, pct: 56, role: "mg"     },
      { nom: "Sucre semoule",     g:  30, pct:  8, role: "sucrant"},
    ],
    procede: [
      "Mélanger le mascarpone froid, la crème liquide froide et le sucre dans un bol.",
      "Monter au robot pâtissier muni du fouet jusqu'à texture chantilly ferme.",
      "Utiliser aussitôt ou réfrigérer.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson" },
    temperatures: { service_c: 6, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["chantilly", "mascarpone", "stable", "décor", "merveilleuse", "vacherin"],
    parfum_principal: "vanille",
    note_concepteur: "Le mascarpone apporte de la stabilité et de l'onctuosité. Les trois ingrédients doivent être froids pour un foisonnement optimal. Peut être parfumée (orgeat, framboise, café, extrait de vanille).",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 446,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "creme-amandes-eb",
    nom: "Crème d'amandes",
    categorie: "cremes",
    sous_categorie: "creme_amandes",
    description: "Crème d'amandes classique 100/100/100 (beurre/sucre/amandes) + 2 œufs. Cuite dans la tarte (bourdaloue, amandine, dartois). Peut accueillir des fruits avant cuisson.",
    masse_totale_g: 400,
    ingredients: [
      { nom: "Beurre",            g: 100, pct: 25, role: "mg"     },
      { nom: "Sucre semoule",     g: 100, pct: 25, role: "sucrant"},
      { nom: "Poudre d'amandes",  g: 100, pct: 25, role: "parfum" },
      { nom: "Œufs entiers",     g: 100, pct: 25, role: "liant"  },
    ],
    procede: [
      "Mélanger le beurre et le sucre. Fouetter légèrement.",
      "Incorporer la poudre d'amandes.",
      "Terminer en ajoutant les œufs. Mélanger bien au fouet.",
      "Mettre dans une poche à douille. Réfrigérer jusqu'à utilisation.",
    ],
    cuisson: { temperature_c: 165, duree_min: 20, mode: "chaleur tournante — dans la tarte" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf", "fruits_a_coque"],
    tags: ["crème d'amandes", "amandine", "bourdaloue", "tarte", "garnissage cuit", "frangipane"],
    parfum_principal: "amande",
    note_concepteur: "Ratio 1/1/1/1 (poids égal) — très facile à multiplier. Ne pas foisonner la crème pour qu'elle reste moelleuse et ne déborde pas à la cuisson. Base de la frangipane (mélangée à crème pâtissière).",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 470,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "creme-frangipane-eb",
    nom: "Crème frangipane",
    categorie: "cremes",
    sous_categorie: "creme_frangipane",
    description: "Crème frangipane = crème pâtissière + crème d'amandes. Moelleuse, humide, parfaite pour la galette des rois et le dartois. Ne pas foisonner pour éviter le débordement.",
    masse_totale_g: 800,
    ingredients: [
      { nom: "Lait entier",       g: 125, pct: 16, role: "eau"      },
      { nom: "Sucre semoule (CP)",g:  30, pct:  4, role: "sucrant"  },
      { nom: "Jaunes d'œufs",    g:  75, pct:  9, role: "liant"    },
      { nom: "Fécule de maïs",    g:  12, pct:  2, role: "structure"},
      { nom: "Beurre (CP)",       g:  12, pct:  2, role: "mg"       },
      { nom: "Beurre (CA)",       g: 150, pct: 19, role: "mg"       },
      { nom: "Sucre semoule (CA)",g: 150, pct: 19, role: "sucrant"  },
      { nom: "Poudre d'amandes",  g: 150, pct: 19, role: "parfum"   },
      { nom: "Œufs entiers",     g:  75, pct:  9, role: "liant"    },
    ],
    procede: [
      "Crème pâtissière : chauffer lait + moitié sucre. Fouetter jaunes + sucre restant + fécule. Cuire jusqu'à épaississement. Ajouter beurre. Filmer, réfrigérer 1h30.",
      "Crème d'amandes : mélanger beurre + sucre, ajouter amandes, puis œufs.",
      "Fouetter la crème pâtissière refroidie. Incorporer la crème d'amandes. Mélanger.",
      "Mettre en poche. Réfrigérer.",
    ],
    cuisson: { temperature_c: 180, duree_min: 30, mode: "chaleur tournante — dans la galette" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "lait", "oeuf", "fruits_a_coque"],
    tags: ["frangipane", "galette des rois", "dartois", "croissants amandes", "garniture"],
    parfum_principal: "amande",
    note_concepteur: "Ne pas foisonner pour éviter que la crème gonfle et déborde à la cuisson. La frangipane = 1 CP + 1 CA mélangées (poids approximativement égaux dans cette recette).",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 476,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "creme-patissiere-cafe-eb",
    nom: "Crème pâtissière au café",
    categorie: "cremes",
    sous_categorie: "creme_cuite",
    description: "Crème pâtissière parfumée Nescafé + infusion de café fort. Terminée au beurre. Base pour entremets café, opéras, garnissages.",
    masse_totale_g: 600,
    ingredients: [
      { nom: "Lait entier",       g: 300, pct: 50,   role: "eau"       },
      { nom: "Sucre semoule",     g:  60, pct: 10,   role: "sucrant"   },
      { nom: "Œufs entiers",     g: 100, pct: 16.7, role: "liant"     },
      { nom: "Poudre à flan",     g:  30, pct:  5,   role: "structure" },
      { nom: "Beurre",            g:  40, pct:  6.7, role: "mg"        },
      { nom: "Café fort infusé",  g: 100, pct: 16.7, role: "parfum"    },
      { nom: "Nescafé",           g:  10, pct:  1.7, role: "parfum"    },
    ],
    procede: [
      "Porter lait + Nescafé + moitié du sucre à ébullition.",
      "Blanchir œufs + reste sucre. Ajouter poudre à flan, mélanger.",
      "Verser ⅓ du lait chaud, fouetter. Reverser dans casserole, cuire 2 min à feu moyen.",
      "Hors du feu : ajouter beurre + infusion de café fort. Bien mélanger.",
      "Verser en plat creux. Filmer au contact. Réfrigérer.",
    ],
    cuisson: { temperature_c: null, duree_min: 2, mode: "feu moyen" },
    temperatures: { service_c: 6, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["crème pâtissière", "café", "garnissage", "base"],
    parfum_principal: "café",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 359,
      chef: "Eddie Benghanem",
    },
  },

  /* ── Ganaches à entremets ───────────────────────────────────────────────── */

  {
    id: "ganache-chocolat-noir-eb",
    nom: "Ganache chocolat noir (entremets)",
    categorie: "cremes",
    sous_categorie: "ganache",
    description: "Ganache émulsionnée crème + sucre inverti + chocolat noir 64%. Texture fondante. Enrobage, couche de tarte, fourrage.",
    masse_totale_g: 605,
    ingredients: [
      { nom: "Crème liquide 35%",  g: 300, pct: 49.6, role: "mg"     },
      { nom: "Sucre inverti",      g:  45, pct:  7.4, role: "sucrant"},
      { nom: "Chocolat noir 64%",  g: 260, pct: 43,   role: "parfum" },
    ],
    procede: [
      "Porter crème + sucre inverti à ébullition.",
      "Verser sur le chocolat finement haché. Émulsionner au mixeur plongeant.",
      "Filmer au contact. Utiliser à 35–40°C ou réserver au frais.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 18, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["ganache", "chocolat noir", "entremets", "tarte", "fourrage"],
    parfum_principal: "chocolat noir",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 400,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "ganache-chocolat-blanc-eb",
    nom: "Ganache chocolat blanc (entremets)",
    categorie: "cremes",
    sous_categorie: "ganache",
    description: "Ganache crème + sucre inverti + chocolat blanc 35%. Texture souple et légère. Tarte, entremets, fourrage. Repos 24 h.",
    masse_totale_g: 925,
    ingredients: [
      { nom: "Crème liquide 35%",  g: 300, pct: 32.4, role: "mg"     },
      { nom: "Sucre inverti",      g:  50, pct:  5.4, role: "sucrant"},
      { nom: "Chocolat blanc 35%", g: 575, pct: 62.2, role: "parfum" },
    ],
    procede: [
      "Porter crème + sucre inverti à ébullition.",
      "Verser en 3 fois sur le chocolat blanc haché. Émulsionner délicatement.",
      "Mixer. Filmer au contact. Repos 24 h au réfrigérateur.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 18, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["ganache", "chocolat blanc", "entremets", "repos 24h"],
    parfum_principal: "chocolat blanc",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 400,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "ganache-montee-noir-eb",
    nom: "Ganache montée chocolat noir Manjari",
    categorie: "cremes",
    sous_categorie: "ganache",
    description: "Ganache montée Manjari 64% Valrhona. Crème chaude sur chocolat + crème froide ajoutée, repos 24 h, montée au fouet. Texture aérée et mousseuse.",
    masse_totale_g: 925,
    ingredients: [
      { nom: "Crème liquide 35%",  g: 675, pct: 72.9, role: "mg"     },
      { nom: "Sucre inverti",      g:  25, pct:  2.7, role: "sucrant"},
      { nom: "Glucose",            g:  25, pct:  2.7, role: "sucrant"},
      { nom: "Chocolat noir 64%",  g: 200, pct: 21.6, role: "parfum" },
    ],
    procede: [
      "Porter 22.5 cl crème + sucre inverti + glucose à ébullition.",
      "Verser en 3 fois sur le chocolat haché. Émulsionner. Mixer.",
      "Ajouter les 45 cl de crème froide. Mixer à nouveau. Filmer au contact.",
      "Repos 24 h au réfrigérateur.",
      "Le jour J : monter au fouet à vitesse moyenne jusqu'à texture mousseuse.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 6, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["ganache montée", "chocolat noir", "Manjari", "entremets", "repos 24h"],
    parfum_principal: "chocolat noir",
    note_concepteur: "22.5 cl crème chaude pour l'émulsion + 45 cl crème froide ajoutées après. Bien mixer avant d'ajouter la crème froide. La ganache est liquide à froid — elle se monte le lendemain.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 400,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "ganache-montee-lait-eb",
    nom: "Ganache montée chocolat au lait Jivara",
    categorie: "cremes",
    sous_categorie: "ganache",
    description: "Ganache montée Jivara 40% Valrhona. Crème bouillante sur chocolat, repos 24 h, montée au fouet. Plus douce et aérée que la version noir.",
    masse_totale_g: 1020,
    ingredients: [
      { nom: "Crème liquide 35%",  g: 600, pct: 58.8, role: "mg"     },
      { nom: "Chocolat lait 35%",  g: 420, pct: 41.2, role: "parfum" },
    ],
    procede: [
      "Porter la crème à ébullition.",
      "Verser en 3 fois sur le chocolat haché. Émulsionner.",
      "Filmer au contact. Repos 24 h au réfrigérateur.",
      "Le jour J : monter au fouet à vitesse moyenne jusqu'à texture mousseuse.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 6, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["ganache montée", "chocolat au lait", "Jivara", "entremets", "repos 24h"],
    parfum_principal: "chocolat au lait",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 400,
      chef: "Eddie Benghanem",
    },
  },

  /* ── Mousse aux marrons ─────────────────────────────────────────────────── */

  {
    id: "mousse-marrons-eb",
    nom: "Mousse aux marrons",
    categorie: "cremes",
    sous_categorie: "mousse",
    description: "Mousse légère aux marrons : sabayon 80°C + gélatine + crème de/pâte de marrons + whisky + crème fouettée. Base Mont-blanc, entremets d'automne.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Crème de marrons",    g: 185, pct: 18.5, role: "parfum"    },
      { nom: "Pâte de marrons",     g: 185, pct: 18.5, role: "parfum"    },
      { nom: "Crème liquide 35%",   g: 550, pct: 55,   role: "mg"        },
      { nom: "Jaunes d'œufs",      g:  55, pct:  5.5, role: "liant"     },
      { nom: "Sirop à 30°B",        g:  90, pct:  9,   role: "sucrant"   },
      { nom: "Gélatine 200 bloom",  g:  15, pct:  1.5, role: "gelifiant" },
      { nom: "Whisky",              g:  12, pct:  1.2, role: "parfum"    },
    ],
    procede: [
      "Hydrater la gélatine dans l'eau froide.",
      "Mixer crème de marrons + pâte de marrons + whisky.",
      "Chauffer sirop à 30°B + jaunes au bain-marie jusqu'à 80°C sans cesser de fouetter. Monter en sabayon jusqu'à refroidissement.",
      "Faire fondre la gélatine essorée ; l'incorporer à une petite partie du sabayon puis au reste.",
      "Monter la crème en crème fouettée. Incorporer l'appareil marrons au sabayon, puis la crème fouettée.",
      "Utiliser aussitôt ou réfrigérer 2 h.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "bain-marie — 80°C" },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["mousse", "marrons", "Mont-blanc", "automne", "sabayon"],
    parfum_principal: "marrons",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 436,
      chef: "Eddie Benghanem",
    },
  },

  /* ── Bavarois ───────────────────────────────────────────────────────────── */

  {
    id: "bavarois-base-eb",
    nom: "Crème bavaroise de base",
    categorie: "cremes",
    sous_categorie: "mousse",
    description: "Crème bavaroise classique : crème anglaise + gélatine + crème fouettée. Base universelle déclinable en toutes saveurs (fruits, chocolat, café…). Texture légère.",
    masse_totale_g: 530,
    ingredients: [
      { nom: "Lait entier",         g: 125, pct: 23.6, role: "eau"       },
      { nom: "Crème liquide 35%",   g: 325, pct: 61.3, role: "mg"        },
      { nom: "Jaunes d'œufs",      g:  55, pct: 10.4, role: "liant"     },
      { nom: "Sucre semoule",       g:  26, pct:  4.9, role: "sucrant"   },
      { nom: "Gélatine 200 bloom",  g:   5, pct:  0.9, role: "gelifiant" },
    ],
    procede: [
      "Hydrater la gélatine 10 min dans l'eau froide.",
      "Porter lait + 12.5 cl crème + moitié du sucre à ébullition.",
      "Fouetter jaunes + reste sucre. Verser moitié lait bouillant, mélanger ; reverser dans casserole. Cuire à 82°C.",
      "Ajouter gélatine essorée hors feu. Filtrer. Refroidir rapidement sur glaçons.",
      "Monter les 20 cl de crème restante en crème mousseuse. Incorporer délicatement à la maryse.",
      "Couler en verrines. Réfrigérer 2 h.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "anglaise 82°C" },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["bavarois", "crème bavaroise", "entremets", "base", "gélatine"],
    parfum_principal: "vanille",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 450,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "bavarois-framboise-eb",
    nom: "Bavarois à la framboise",
    categorie: "cremes",
    sous_categorie: "mousse",
    description: "Bavarois framboise : base crème anglaise lait+pulpe framboises + gélatine + crème fouettée. Pour entremets ou verrines. 1 kg.",
    masse_totale_g: 1060,
    ingredients: [
      { nom: "Lait entier",          g: 190, pct: 17.9, role: "eau"       },
      { nom: "Purée de framboises",  g: 320, pct: 30.2, role: "parfum"    },
      { nom: "Jaunes d'œufs",       g: 108, pct: 10.2, role: "liant"     },
      { nom: "Sucre semoule",        g: 130, pct: 12.3, role: "sucrant"   },
      { nom: "Crème liquide 35%",    g: 300, pct: 28.3, role: "mg"        },
      { nom: "Gélatine 200 bloom",   g:  10, pct:  0.9, role: "gelifiant" },
    ],
    procede: [
      "Hydrater la gélatine 10 min dans l'eau froide.",
      "Chauffer lait + pulpe framboises dans une casserole.",
      "Mélanger sucre + jaunes. Verser un peu de lait chaud, mélanger, reverser, cuire à 82°C.",
      "Ajouter gélatine essorée hors feu.",
      "Monter la crème en crème fouettée (bec d'oiseau). Pré-mélange puis incorporer délicatement à la maryse.",
      "Couler en verrines. Réfrigérer 2 h.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "anglaise 82°C" },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["bavarois", "framboise", "entremets", "verrine"],
    parfum_principal: "framboise",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 452,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "bavarois-chocolat-lait-eb",
    nom: "Bavarois au chocolat au lait",
    categorie: "cremes",
    sous_categorie: "mousse",
    description: "Bavarois bi-chocolat (lait 35% + noir 64%) sur base crème anglaise, crème fouettée incorporée à 40°C. Texture mousseuse et soyeuse — pas de gélatine.",
    masse_totale_g: 600,
    ingredients: [
      { nom: "Lait entier",         g: 105, pct: 17.5, role: "eau"     },
      { nom: "Crème liquide 35%",   g: 330, pct: 55,   role: "mg"      },
      { nom: "Jaunes d'œufs",      g:  36, pct:  6,   role: "liant"   },
      { nom: "Sucre semoule",       g:  35, pct:  5.8, role: "sucrant" },
      { nom: "Chocolat lait 35%",   g:  90, pct: 15,   role: "parfum"  },
      { nom: "Chocolat noir 64%",   g: 135, pct: 22.5, role: "parfum"  },
    ],
    procede: [
      "Porter lait + 10.5 cl crème à ébullition. Blanchir jaunes + sucre.",
      "Verser moitié liquide sur jaunes, mélanger, reverser, cuire à 82°C.",
      "Verser la crème anglaise chaude sur les deux chocolats hachés. Émulsionner.",
      "Monter les 22.5 cl de crème restante en crème mousseuse.",
      "Lorsque l'appareil au chocolat est à 40°C, l'incorporer délicatement à la crème fouettée.",
      "Couler en verrines. Décorer de copeaux de chocolat noir. Réfrigérer 3 h.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "anglaise 82°C" },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["bavarois", "chocolat au lait", "chocolat noir", "entremets", "verrine"],
    parfum_principal: "chocolat au lait",
    note_concepteur: "Pas de gélatine — la tenue vient de la structure chocolat + crème fouettée. Bien respecter la température de 40°C avant incorporation de la crème fouettée.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 454,
      chef: "Eddie Benghanem",
    },
  },

  /* ── Mousses légères (meringue italienne + crème fouettée) ───────────────── */

  {
    id: "mousse-fruits-bois-eb",
    nom: "Mousse aux fruits des bois",
    categorie: "cremes",
    sous_categorie: "mousse",
    description: "Mousse framboises-fraises-cassis : gélatine sur purées, meringue italienne 118°C + crème fouettée. Entremets ou verrines. 600 g.",
    masse_totale_g: 660,
    ingredients: [
      { nom: "Purée de framboises",  g: 120, pct: 18.2, role: "parfum"    },
      { nom: "Purée de fraises",     g: 120, pct: 18.2, role: "parfum"    },
      { nom: "Purée de cassis",      g:  90, pct: 13.6, role: "parfum"    },
      { nom: "Gélatine 200 bloom",   g:   4, pct:  0.6, role: "gelifiant" },
      { nom: "Blancs d'œufs",       g:  30, pct:  4.5, role: "liant"     },
      { nom: "Sucre semoule",        g:  50, pct:  7.6, role: "sucrant"   },
      { nom: "Glucose",              g:  25, pct:  3.8, role: "sucrant"   },
      { nom: "Eau",                  g:  20, pct:  3,   role: "eau"       },
      { nom: "Crème liquide 35%",    g: 200, pct: 30.3, role: "mg"        },
    ],
    procede: [
      "Hydrater la gélatine dans l'eau froide.",
      "Chauffer ⅓ des purées. Ajouter gélatine essorée hors feu. Incorporer au reste des purées.",
      "Meringue italienne : cuire eau + sucre + glucose à 118°C ; verser sur blancs en neige au robot fouet.",
      "Monter la crème froide en crème fouettée.",
      "Incorporer délicatement la crème fouettée dans la meringue italienne, puis les purées gélatinées.",
      "Couler en verrines. Réfrigérer 3 h. Décorer de fruits frais.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "meringue italienne 118°C" },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["mousse", "fruits des bois", "framboise", "cassis", "meringue italienne"],
    parfum_principal: "fruits des bois",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 456,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "mousse-exotique-eb",
    nom: "Mousse aux fruits exotiques",
    categorie: "cremes",
    sous_categorie: "mousse",
    description: "Mousse passion-mangue-banane : meringue italienne + crème fouettée + purées gélatinées. Entremets tropical, verrines ou insert.",
    masse_totale_g: 650,
    ingredients: [
      { nom: "Purée de fruits de la Passion", g: 120, pct: 18.5, role: "parfum"    },
      { nom: "Purée de mangue",    g: 120, pct: 18.5, role: "parfum"    },
      { nom: "Purée de banane",    g:  90, pct: 13.8, role: "parfum"    },
      { nom: "Gélatine 200 bloom", g:   4, pct:  0.6, role: "gelifiant" },
      { nom: "Blancs d'œufs",     g:  30, pct:  4.6, role: "liant"     },
      { nom: "Sucre semoule",      g:  50, pct:  7.7, role: "sucrant"   },
      { nom: "Glucose",            g:  20, pct:  3.1, role: "sucrant"   },
      { nom: "Eau",                g:  20, pct:  3.1, role: "eau"       },
      { nom: "Crème liquide 35%",  g: 200, pct: 30.8, role: "mg"        },
    ],
    procede: [
      "Hydrater la gélatine dans l'eau froide.",
      "Chauffer ⅓ des purées ; ajouter gélatine essorée hors feu. Incorporer au reste des purées.",
      "Meringue italienne : cuire eau + sucre + glucose à 118°C ; verser sur blancs au robot fouet.",
      "Monter la crème froide en crème fouettée.",
      "Lorsque la meringue italienne est froide et ferme : incorporer crème fouettée puis purées-gélatine.",
      "Utiliser aussitôt.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "meringue italienne 118°C" },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["mousse", "exotique", "passion", "mangue", "banane", "meringue italienne"],
    parfum_principal: "fruits exotiques",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 458,
      chef: "Eddie Benghanem",
    },
  },

  /* ── Sabayon au chocolat ────────────────────────────────────────────────── */

  {
    id: "sabayon-chocolat-eb",
    nom: "Sabayon au chocolat au lait",
    categorie: "cremes",
    sous_categorie: "mousse",
    description: "Sabayon chocolat lait : pâte à bombe (jaunes + sucre cuit 82°C au bain-marie) montée, chocolat fondu à 45°C et crème fouettée incorporés. Verrine ou insert.",
    masse_totale_g: 590,
    ingredients: [
      { nom: "Jaunes d'œufs",    g:  55, pct:  9.3, role: "liant"   },
      { nom: "Œufs entiers",    g:  25, pct:  4.2, role: "liant"   },
      { nom: "Sucre semoule",   g:  45, pct:  7.6, role: "sucrant" },
      { nom: "Eau",             g:  30, pct:  5.1, role: "eau"     },
      { nom: "Crème liquide 35%",g: 200, pct: 33.9, role: "mg"    },
      { nom: "Chocolat lait 35%",g: 230, pct: 39,   role: "parfum" },
    ],
    procede: [
      "Fouetter jaunes + demi-œuf + sucre + eau dans un bol sur bain-marie. Cuire à 82°C.",
      "Mettre au robot fouet : monter jusqu'à refroidissement (volume doublé, mousseux).",
      "Fondre le chocolat au bain-marie à 45°C.",
      "Monter la crème en texture mousseuse. Prélever une partie et mélanger avec le chocolat.",
      "Ajouter ce mélange à la pâte à bombe. Incorporer délicatement le reste de crème fouettée.",
      "Couler en verrine. Réfrigérer.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "bain-marie 82°C" },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["sabayon", "chocolat au lait", "mousse", "verrine", "pâte à bombe"],
    parfum_principal: "chocolat au lait",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 468,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "creme-a-lorange-eb",
    nom: "Crème à l'orange",
    categorie: "cremes",
    sous_categorie: "cremeux_fruit",
    description: "Crème orange-passion : jus d'orange + pulpe passion + œufs cuits au bain-marie à 82°C, finis au chocolat blanc + beurre de cacao. Texture fondante, arôme d'orange intense.",
    masse_totale_g: 500,
    ingredients: [
      { nom: "Pulpe de fruit de la Passion", g: 75, pct: 15, role: "parfum" },
      { nom: "Jus d'orange",          g: 110, pct: 22, role: "parfum" },
      { nom: "Œufs entiers",         g: 180, pct: 36, role: "liant"  },
      { nom: "Sucre semoule",         g:  45, pct:  9, role: "sucrant"},
      { nom: "Chocolat blanc",        g: 130, pct: 26, role: "liant"  },
      { nom: "Beurre de cacao",       g:   8, pct:  2, role: "mg"     },
    ],
    procede: [
      "Hydrater la gélatine dans l'eau froide.",
      "Cuire au bain-marie : jus d'orange, pulpe passion, œufs, sucre et zestes des oranges jusqu'à 82°C en remuant.",
      "Hors du feu, ajouter la gélatine essorée, le beurre de cacao et le chocolat blanc.",
      "Mixer 2 min au plongeant.",
      "Verser dans un plat. Filmer au contact. Réfrigérer.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "bain-marie — 82°C" },
    temperatures: { service_c: 6, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["crème orange", "passion", "curd", "tarte orange", "exotique"],
    parfum_principal: "orange",
    note_concepteur: "6g gélatine feuilles + zestes de 3 oranges (non incluses dans masse totale). La pulpe de passion équilibre l'orange par une pointe d'acidité tropicale. Pocher sur sablé breton pour une tarte à l'orange.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 440,
      chef: "Eddie Benghanem",
    },
  },
];
