export const RECETTES_CREMES = [
  {
    id: "cremeux-framboise-01",
    nom: "Crémeux framboise",
    categorie: "cremes",
    sous_categorie: "cremeux_fruit",
    description: "Crémeux onctueux à base de purée de framboise, monté au beurre. Acidulé et brillant, idéal en insert ou en couche d'entremets.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Purée de framboise",  g: 380, pct: 38,  role: "fruit"     },
      { nom: "Crème liquide 35%",   g: 200, pct: 20,  role: "mg"        },
      { nom: "Jaunes d'œufs",       g: 160, pct: 16,  role: "liant"     },
      { nom: "Sucre semoule",        g: 120, pct: 12,  role: "sucrant"   },
      { nom: "Beurre doux",          g: 100, pct: 10,  role: "mg"        },
      { nom: "Gélatine (poudre 200B)", g: 20, pct: 2,  role: "gelifiant" },
      { nom: "Eau de réhydratation", g:  20, pct:  2,  role: "eau"       },
    ],
    procede: [
      "Réhydrater la gélatine dans l'eau froide, laisser gonfler 10 min.",
      "Chauffer la purée de framboise et la crème jusqu'à frémissement.",
      "Blanchir les jaunes avec le sucre. Verser le liquide chaud en filet sur les jaunes en fouettant.",
      "Reverser dans la casserole. Cuire à 82–84 °C en remuant sans arrêt (nappe).",
      "Retirer du feu. Incorporer la gélatine essorée, dissoudre.",
      "Refroidir à 40 °C. Incorporer le beurre froid en dés au mixeur plongeant, émulsionner 2 min.",
      "Couler immédiatement dans les inserts ou cadres. Bloquer au froid (–18 °C) ou réfrigérer 4 h minimum.",
    ],
    cuisson: { temperature_c: 84, duree_min: null, mode: "casserole — nappe" },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["oeuf", "lactose"],
    tags: ["framboise", "insert", "cremeux", "entremets", "acidule"],
    parfum_principal: "framboise",
    note_concepteur: "La cuisson à 82–84 °C est impérative pour pasteuriser les jaunes sans coaguler. Le mixage au beurre froid crée une émulsion qui donne le brillant caractéristique.",
    source_interne: {
      fichier_pdf: null,
      page: null,
      nom_original: "Recette de test — recette générique",
      chef: null,
      date_extraction: "2026-05-18",
    },
  },

  {
    id: "creme-patissiere-vanille-01",
    nom: "Crème pâtissière vanille",
    categorie: "cremes",
    sous_categorie: "creme_cuite",
    description: "Crème de base, onctueuse et parfumée à la vanille. Polyvalente : garnissage, fond de tarte, base mousseline.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Lait entier",          g: 600, pct: 60, role: "eau"       },
      { nom: "Sucre semoule",        g: 150, pct: 15, role: "sucrant"   },
      { nom: "Jaunes d'œufs",        g: 120, pct: 12, role: "liant"     },
      { nom: "Amidon de maïs",       g:  60, pct:  6, role: "structure" },
      { nom: "Beurre doux",          g:  60, pct:  6, role: "mg"        },
      { nom: "Vanille (gousse)",      g:  10, pct:  1, role: "parfum"    },
    ],
    procede: [
      "Fendre et gratter la gousse de vanille. Infuser dans le lait chaud 15 min à couvert. Retirer la gousse.",
      "Blanchir les jaunes avec le sucre et l'amidon. Ne pas trop travailler.",
      "Porter le lait vanillé à ébullition. Verser un tiers sur l'appareil jaunes en fouettant.",
      "Reverser dans la casserole. Cuire à feu moyen en fouettant vivement jusqu'à la première ébullition.",
      "Maintenir l'ébullition 1 min pour désactiver l'amylase.",
      "Hors du feu, incorporer le beurre froid en dés en fouettant.",
      "Débarrasser sur plaque filmée au contact. Refroidir rapidement à 4 °C.",
    ],
    cuisson: { temperature_c: 100, duree_min: 1, mode: "casserole — ébullition" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["oeuf", "lactose"],
    tags: ["vanille", "base", "garnissage", "tarte", "mousseline"],
    parfum_principal: "vanille",
    note_concepteur: "L'ébullition maintenue 1 min est indispensable pour éliminer l'amylase bactérienne et obtenir une crème stable. Un film plastique au contact évite la formation d'une peau.",
    source_interne: {
      fichier_pdf: null,
      page: null,
      nom_original: "Recette de test — recette générique",
      chef: null,
      date_extraction: "2026-05-18",
    },
  },
];
