export const RECETTES_CREMES = [
  {
    id: "cremeux-chocolat-noir",
    nom: "Crémeux chocolat noir",
    categorie: "cremes",
    sous_categorie: "cremeux_chocolat",
    description: "Crémeux onctueux sur base crème anglaise, émulsionné au chocolat noir. Texture fondante et brillante, idéal en insert ou couche d'entremets.",
    masse_totale_g: 345,
    ingredients: [
      { nom: "Crème liquide 35%",       g: 105,  pct: 30,   role: "mg"        },
      { nom: "Lait UHT entier",          g: 105,  pct: 31,   role: "eau"       },
      { nom: "Jaune d'œuf pasteurisé",  g: 40,   pct: 12,   role: "liant"     },
      { nom: "Chocolat noir 67%",        g: 95,   pct: 27,   role: "parfum"    },
    ],
    procede: [
      "Réaliser une crème anglaise avec le lait, la crème et les jaunes d'œufs.",
      "Cuire à 82°C, stopper la cuisson, filtrer et verser sur le chocolat.",
      "Émulsionner au mixeur plongeant sans incorporer d'air.",
      "Couler directement dans les fonds de tartes ou filmer au contact.",
      "Refroidir rapidement à 4°C. Laisser cristalliser 12h minimum avant de pocher.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["crémeux", "chocolat noir", "entremets", "pocher", "base anglaise"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Veiller à réaliser une cuisson juste de la crème anglaise et à peser après cuisson avant d'émulsionner avec le chocolat. Pour une texture optimale à pocher, laisser cristalliser 12h à 4°C.",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 22,
      chef: null,
    },
  },

  {
    id: "cremeux-ultrafondant-noir",
    nom: "Crémeux ultra-fondant chocolat",
    categorie: "cremes",
    sous_categorie: "cremeux_chocolat",
    description: "Crémeux construit à froid sur émulsion lait-chocolat avec gélatine légère. Texture ultra-fondante — ne pas trop travailler avant emploi.",
    masse_totale_g: 464,
    ingredients: [
      { nom: "Crème liquide 35%",  g: 200,  pct: 43,   role: "mg"        },
      { nom: "Lait UHT entier",     g: 100,  pct: 22,   role: "eau"       },
      { nom: "Gélatine 200 bloom",  g: 2,    pct: 0.5,  role: "gelifiant" },
      { nom: "Eau gélatine",        g: 12,   pct: 2.5,  role: "eau"       },
      { nom: "Chocolat 58%",        g: 150,  pct: 32,   role: "parfum"    },
    ],
    procede: [
      "Hydrater la gélatine dans 6× son poids en eau froide (quantités déjà indiquées).",
      "Porter le lait à ébullition, ajouter la masse gélatine et laisser fondre.",
      "Verser sur le chocolat fondu, émulsionner au mixeur plongeant.",
      "Ajouter la crème froide, mixer à nouveau.",
      "Stocker minimum 12h à 4°C avant utilisation.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 10, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["crémeux", "ultra-fondant", "chocolat", "entremets"],
    parfum_principal: "chocolat",
    note_concepteur: "Ce crémeux est ultra fondant : éviter de trop le travailler avant utilisation au risque de le rendre trop liquide.",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 24,
      chef: null,
    },
  },

  {
    id: "creme-patissiere-vanille-01",
    nom: "Crème pâtissière vanille",
    categorie: "cremes",
    sous_categorie: "creme_cuite",
    description: "Crème de base, onctueuse et parfumée à la vanille. Polyvalente : garnissage, fond de tarte, base mousseline.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Lait entier",        g: 600, pct: 60, role: "eau"       },
      { nom: "Sucre semoule",      g: 150, pct: 15, role: "sucrant"   },
      { nom: "Jaunes d'œufs",      g: 120, pct: 12, role: "liant"     },
      { nom: "Amidon de maïs",     g:  60, pct:  6, role: "structure" },
      { nom: "Beurre doux",        g:  60, pct:  6, role: "mg"        },
      { nom: "Vanille (gousse)",   g:  10, pct:  1, role: "parfum"    },
    ],
    procede: [
      "Fendre et gratter la gousse de vanille. Infuser dans le lait chaud 15 min à couvert. Retirer la gousse.",
      "Blanchir les jaunes avec le sucre et l'amidon. Ne pas trop travailler.",
      "Porter le lait vanillé à ébullition. Verser un tiers sur l'appareil jaunes en fouettant.",
      "Reverser dans la casserole. Cuire à feu moyen en fouettant vivement jusqu'à la première ébullition.",
      "Maintenir l'ébullition 1 min pour désactiver l'amylase.",
      "Hors du feu, incorporer le beurre froid en dés en fouettant.",
      "Débarrasser sur plaque filmée au contact. Refroidir rapidement à 4°C.",
    ],
    cuisson: { temperature_c: 100, duree_min: 1, mode: "casserole — ébullition" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["oeuf", "lait"],
    tags: ["vanille", "base", "garnissage", "tarte", "mousseline"],
    parfum_principal: "vanille",
    note_concepteur: "L'ébullition maintenue 1 min est indispensable pour éliminer l'amylase bactérienne et obtenir une crème stable. Un film plastique au contact évite la formation d'une peau.",
    source_interne: {
      fichier_pdf: null,
      page: null,
      chef: null,
    },
  },
];
