export const RECETTES_CROUSTILLANTS = [
  {
    id: "croustillant-praline-feuilletine-01",
    nom: "Croustillant praliné feuilletine",
    categorie: "croustillants",
    sous_categorie: "croustillant_praline",
    description: "Insert croustillant classique à base de praliné noisette, chocolat au lait et feuilletine. Fond croquant d'entremets.",
    masse_totale_g: 500,
    ingredients: [
      { nom: "Praliné noisette 60%",  g: 275, pct: 55, role: "parfum"    },
      { nom: "Chocolat au lait 40%",  g:  60, pct: 12, role: "emulsion"  },
      { nom: "Feuilletine (paillettes)", g: 150, pct: 30, role: "texture" },
      { nom: "Beurre de cacao",        g:  15, pct:  3, role: "mg"        },
    ],
    procede: [
      "Fondre le chocolat au lait et le beurre de cacao ensemble à 45 °C.",
      "Incorporer le praliné noisette à température ambiante. Mélanger jusqu'à pâte homogène.",
      "Ajouter la feuilletine en une fois. Mélanger délicatement à la spatule pour ne pas écraser les paillettes.",
      "Étaler immédiatement à 4–5 mm entre deux feuilles de papier cuisson.",
      "Bloquer au froid (–18 °C) 15 min ou réfrigérer 30 min avant détaillage.",
      "Détailler aux dimensions souhaitées. Conserver au froid jusqu'au montage.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["lactose", "fruits_a_coque", "gluten"],
    tags: ["praline", "noisette", "feuilletine", "croustillant", "insert", "fond"],
    parfum_principal: "noisette",
    note_concepteur: "La feuilletine doit être incorporée en dernier et sans excès de mélange pour conserver son croustillant. Un croustillant trop travaillé devient mou après congélation.",
    source_interne: {
      fichier_pdf: null,
      page: null,
      nom_original: "Recette de test — recette générique",
      chef: null,
      date_extraction: "2026-05-18",
    },
  },
];
