export const RECETTES_CROUSTILLANTS = [
  {
    id: "croustillant-praline-feuilletine-01",
    nom: "Croustillant praliné feuilletine",
    categorie: "croustillants",
    sous_categorie: "croustillant_praline",
    description: "Insert croustillant classique à base de praliné noisette, chocolat au lait et feuilletine. Fond croquant d'entremets.",
    masse_totale_g: 500,
    ingredients: [
      { nom: "Praliné noisette 60%",  g: 275, pct: 55, role: "parfum"    },
      { nom: "Chocolat au lait 40%",  g:  60, pct: 12, role: "emulsion"  },
      { nom: "Feuilletine (paillettes)", g: 150, pct: 30, role: "texture" },
      { nom: "Beurre de cacao",        g:  15, pct:  3, role: "mg"        },
    ],
    procede: [
      "Fondre le chocolat au lait et le beurre de cacao ensemble à 45 °C.",
      "Incorporer le praliné noisette à température ambiante. Mélanger jusqu'à pâte homogène.",
      "Ajouter la feuilletine en une fois. Mélanger délicatement à la spatule pour ne pas écraser les paillettes.",
      "Étaler immédiatement à 4–5 mm entre deux feuilles de papier cuisson.",
      "Bloquer au froid (–18 °C) 15 min ou réfrigérer 30 min avant détaillage.",
      "Détailler aux dimensions souhaitées. Conserver au froid jusqu'au montage.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["lactose", "fruits_a_coque", "gluten"],
    tags: ["praline", "noisette", "feuilletine", "croustillant", "insert", "fond"],
    parfum_principal: "noisette",
    note_concepteur: "La feuilletine doit être incorporée en dernier et sans excès de mélange pour conserver son croustillant. Un croustillant trop travaillé devient mou après congélation.",
    source_interne: {
      fichier_pdf: null,
      page: null,
      nom_original: "Recette de test — recette générique",
      chef: null,
      date_extraction: "2026-05-18",
    },
  },

  /* ── Karim Bourgi ────────────────────────────────────────────────────── */

  {
    id: "streusel-pistache-kb",
    nom: "Streusel pistache",
    categorie: "croustillants",
    sous_categorie: "streusel",
    description: "Streusel sableux à la poudre de pistache Antep, 4 ingrédients à part égale. Cuit à basse température pour préserver la couleur verte. Utilisé en croustillant ou décor émietté.",
    masse_totale_g: 360,
    ingredients: [
      { nom: "Sucre de canne roux",    g: 90, pct: 25, role: "sucrant"   },
      { nom: "Farine",                 g: 90, pct: 25, role: "structure" },
      { nom: "Poudre de pistache Antep", g: 90, pct: 25, role: "parfum" },
      { nom: "Beurre sec 84%",         g: 90, pct: 25, role: "mg"       },
    ],
    procede: [
      "Mélanger le sucre, la farine et la poudre de pistache au batteur avec la feuille.",
      "Ajouter le beurre froid coupé en cubes. Mélanger jusqu'à texture sableuse — la pâte va s'agglomérer.",
      "Étaler sur une plaque avec un tapis perforé. Congeler quelques minutes.",
      "Cuire à 125°C, 25 min. Laisser refroidir à température ambiante.",
    ],
    cuisson: { temperature_c: 125, duree_min: 25, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "lait", "fruits_a_coque"],
    tags: ["streusel", "pistache", "croustillant", "travel cake", "décor"],
    parfum_principal: "pistache",
    note_concepteur: "Cuisson basse (125°C) intentionnelle pour préserver la couleur verte de la pistache. Un streusel classique à 170°C brunira excessivement.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 40,
      chef: "Karim Bourgi",
    },
  },

  {
    id: "streusel-cacao-kb",
    nom: "Streusel cacao-amande",
    categorie: "croustillants",
    sous_categorie: "streusel",
    description: "Streusel à base de pépites de cacao broyées et poudre d'amande. Intense, amer et croustillant. Utilisé comme décor d'éclair ou en couche dans un croustillant.",
    masse_totale_g: 328,
    ingredients: [
      { nom: "Sucre brun",              g:  82, pct: 25, role: "sucrant"   },
      { nom: "Farine",                  g:  82, pct: 25, role: "structure" },
      { nom: "Poudre d'amande torréfiée", g: 40, pct: 12, role: "parfum"  },
      { nom: "Pépites de cacao",        g:  40, pct: 12, role: "parfum"   },
      { nom: "Beurre 82%",              g:  82, pct: 25, role: "mg"       },
      { nom: "Sel",                     g: 1.5, pct:  1, role: "assaisonm"},
    ],
    procede: [
      "Mixer au robot le sucre, la poudre d'amande et les pépites de cacao jusqu'à poudre fine.",
      "Transférer dans la cuve du batteur. Ajouter le beurre froid en cubes, la farine et le sel.",
      "Mélanger à la feuille jusqu'à texture sableuse-grumeleuse.",
      "Étaler sur une plaque silicone. Surgeler 10–15 min.",
      "Cuire à 140°C, 18–20 min. Laisser refroidir.",
    ],
    cuisson: { temperature_c: 140, duree_min: 19, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "lait", "fruits_a_coque"],
    tags: ["streusel", "cacao", "amande", "éclair", "décor", "croustillant"],
    parfum_principal: "cacao",
    note_concepteur: "Les pépites de cacao apportent amertume et croquant caractéristiques. Mixer les pépites avant d'incorporer assure une distribution homogène et évite les morceaux trop gros.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 84,
      chef: "Karim Bourgi",
    },
  },

  {
    id: "croustillant-pistache-kb",
    nom: "Croustillant pistache",
    categorie: "croustillants",
    sous_categorie: "croustillant_praline",
    description: "Couche croustillante à base de praliné pistache, streusel pistache et chocolat blanc. Découpée en rectangles pour l'assemblage des travel cakes. Texture dense et croquante.",
    masse_totale_g: 701,
    ingredients: [
      { nom: "Chocolat blanc Opalys 33%", g: 105, pct: 15, role: "liant"   },
      { nom: "Beurre clarifié",           g:  63, pct:  9, role: "mg"      },
      { nom: "Praliné pistache",          g: 210, pct: 30, role: "parfum"  },
      { nom: "Streusel pistache cuit",    g: 320, pct: 46, role: "texture" },
      { nom: "Sel",                       g:   3, pct:  0, role: "assaisonm"},
    ],
    procede: [
      "Fondre le chocolat blanc.",
      "Incorporer le beurre clarifié et le praliné pistache. Mélanger à la spatule.",
      "Ajouter le streusel pistache cuit et refroidi, le sel. Mélanger délicatement pour conserver les morceaux.",
      "Étaler dans un cadre 30×30 cm posé sur tapis silicone. Parsemer de pistaches concassées. Surgeler.",
      "Détailler des rectangles 5×14 cm dès la sortie du congélateur.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson" },
    temperatures: { service_c: null, conservation_c: -18 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "gluten", "fruits_a_coque"],
    tags: ["croustillant", "pistache", "travel cake", "insert", "rectangle"],
    parfum_principal: "pistache",
    note_concepteur: "Le beurre clarifié (sans lactose) favorise une texture plus nette que le beurre entier. Le streusel doit être incorporé en dernier et sans excès de mélange pour conserver le croquant.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 44,
      chef: "Karim Bourgi",
    },
  },

  {
    id: "base-croustillante-cacao-kb",
    nom: "Base croustillante cacao-praliné",
    categorie: "croustillants",
    sous_categorie: "croustillant_praline",
    description: "Base d'entremets au praliné amande-noisette, chocolat lait et pépites de cacao. Disques cuits surgelés, posés sur le dessus de l'entremet avant glaçage.",
    masse_totale_g: 225,
    ingredients: [
      { nom: "Chocolat lait Jivara 40%",         g:  55, pct: 24, role: "liant"   },
      { nom: "Praliné amande-noisette 50% Valrhona", g: 130, pct: 58, role: "parfum"},
      { nom: "Céréales croustillantes (blé soufflé)", g: 20, pct: 9, role: "texture"},
      { nom: "Pépites de cacao",                 g:  20, pct:  9, role: "parfum"  },
    ],
    procede: [
      "Broyer les pépites de cacao au robot jusqu'à poudre. Mélanger avec le praliné et les céréales croustillantes dans un bol.",
      "Fondre le chocolat et verser sur le mélange. Mélanger à la spatule jusqu'à homogénéité.",
      "Répartir dans des cercles d=16 cm posés sur tapis silicone. Lisser à l'offset. Surgeler.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson" },
    temperatures: { service_c: null, conservation_c: -18 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "gluten", "fruits_a_coque"],
    tags: ["croustillant", "praliné", "cacao", "entremet", "base", "insert"],
    parfum_principal: "praliné",
    note_concepteur: "Cette base se pose côté biscuit vers le haut lors du montage — elle devient la semelle de l'entremet Racine. À conserver surgelée jusqu'au moment du glaçage.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 94,
      chef: "Karim Bourgi",
    },
  },

  {
    id: "croustillant-chocolat-cacao-kb",
    nom: "Croustillant chocolat-cacao pressé",
    categorie: "croustillants",
    sous_categorie: "croustillant_chocolat",
    description: "Couche croustillante pressée : streusel cacao, feuilletine et pépites de cacao liés au chocolat noir. Découpée en bandes et insérée dans l'éclair avant garnissage.",
    masse_totale_g: 339,
    ingredients: [
      { nom: "Pépites de cacao",          g:  38, pct: 12, role: "parfum"  },
      { nom: "Sel",                       g:   1, pct:  0, role: "assaisonm"},
      { nom: "Streusel cacao cuit",       g: 140, pct: 41, role: "texture" },
      { nom: "Feuilletine (paillettes wafer)", g: 50, pct: 15, role: "texture"},
      { nom: "Chocolat Araguani 72%",     g: 110, pct: 32, role: "liant"   },
    ],
    procede: [
      "Fondre le chocolat à 45°C.",
      "Mélanger les pépites de cacao, le sel, le streusel cuit et la feuilletine dans un bol.",
      "Verser le chocolat fondu. Mélanger jusqu'à enrobage complet.",
      "Étaler dans un cadre 35×25 cm sur tapis silicone à l'offset. Surgeler.",
      "Détailler des bandes 8×1 cm (ajuster à la longueur des éclairs).",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson" },
    temperatures: { service_c: null, conservation_c: -18 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "lait", "fruits_a_coque"],
    tags: ["croustillant", "chocolat", "cacao", "feuilletine", "éclair", "insert"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Les bandes sont insérées dans l'éclair par le côté (découpe avec aiguille) avant le garnissage crémeux par le fond. La feuilletine reste croquante même après surgélation.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 85,
      chef: "Karim Bourgi",
    },
  },
];
