export const RECETTES_DECORS = [
  {
    id: "enrobage-gourmand-noir",
    nom: "Enrobage gourmand chocolat noir",
    categorie: "decors",
    sous_categorie: "enrobage",
    description: "Enrobage chocolat croustillant aux fruits secs, pour napper glaces et bûches congelées. Application à 40-45°C sur produit congelé.",
    masse_totale_g: 775,
    ingredients: [
      { nom: "Chocolat noir 67%",       g: 500, pct: 64, role: "parfum"  },
      { nom: "Beurre de cacao",         g: 150, pct: 19, role: "mg"      },
      { nom: "Huile pépins de raisin",  g: 50,  pct: 7,  role: "mg"      },
      { nom: "Fruits secs torréfiés",   g: 75,  pct: 10, role: "texture" },
    ],
    procede: [
      "Fondre la couverture avec le beurre de cacao au bain-marie à 45°C.",
      "Ajouter l'huile de pépins de raisin et les fruits secs torréfiés de votre choix (amande, noisette, noix, sésame, grué de cacao…).",
      "Utiliser entre 40-45°C sur produit congelé.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: 15 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["fruits_a_coque"],
    tags: ["enrobage", "chocolat noir", "fruits secs", "décor", "glace", "bûche"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Ajuster la quantité d'huile pour un enrobage plus ou moins fin.",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 62,
      chef: null,
    },
  },

  {
    id: "pulverisation-noir",
    nom: "Pulvérisation velours chocolat noir",
    categorie: "decors",
    sous_categorie: "pulverisation",
    description: "Préparation pour effet velours au pistolet à chocolat. Pulvériser à 45°C sur entremets surgelés pour un fini mat et velouté.",
    masse_totale_g: 400,
    ingredients: [
      { nom: "Chocolat noir 67%",      g: 200, pct: 50, role: "parfum" },
      { nom: "Beurre de cacao",        g: 150, pct: 37, role: "mg"     },
      { nom: "Huile pépins de raisin", g: 50,  pct: 13, role: "mg"     },
    ],
    procede: [
      "Fondre la couverture avec le beurre de cacao au bain-marie à 45°C.",
      "Ajouter l'huile de pépins de raisin.",
      "Pour un effet velours, pulvériser à 45°C sur produits congelés.",
      "Pour donner du brillant sur moulages, pré-cristalliser avant de pulvériser en suivant les courbes de tempérage dédiées.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: 15 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["velours", "pulvérisation", "chocolat noir", "décor", "finition", "pistolet"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Ajouter de l'huile de pépins de raisin donne de la souplesse à la pulvérisation et évite qu'elle ne se fissure sur les entremets lors de la décongélation.",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 64,
      chef: null,
    },
  },

  {
    id: "chocolat-plastique-noir",
    nom: "Chocolat plastique noir",
    categorie: "decors",
    sous_categorie: "chocolat_plastique",
    description: "Pâte à modeler au chocolat, utilisable à température ambiante. Idéale pour décors sculptés et modelés à la main.",
    masse_totale_g: 335,
    ingredients: [
      { nom: "Chocolat noir 67%",     g: 200, pct: 60, role: "parfum"  },
      { nom: "Sirop de glucose DE40", g: 135, pct: 40, role: "sucrant" },
    ],
    procede: [
      "Fondre séparément le chocolat et le glucose à 40-42°C.",
      "Émulsionner ensemble à la spatule silicone.",
      "Verser sur film alimentaire, couvrir hermétiquement.",
      "Laisser cristalliser minimum 12h à 15-20°C avant d'utiliser.",
      "Utiliser par petites quantités en travaillant à la main. Réchauffer très légèrement au micro-ondes si nécessaire.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 20, conservation_c: 15 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["chocolat plastique", "décoration", "modelage", "chocolat noir", "sculpter"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Laisser cristalliser minimum 12h avant utilisation.",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 65,
      chef: null,
    },
  },

  /* ── Révolution Pâtisserie — Johanna Le Pape ────────────────────────────── */

  {
    id: "meringues-vegan-lp",
    nom: "Meringues vegan",
    categorie: "decors",
    sous_categorie: "meringue",
    description: "Meringues 100 % végétales à base d'aquafaba (jus de pois chiche), arrow-root, psyllium et agar-agar. Texture croustillante.",
    masse_totale_g: 196,
    ingredients: [
      { nom: "Aquafaba",            g: 100, pct: 51.0, role: "aeration"  },
      { nom: "Sucre blond",         g:  70, pct: 35.7, role: "sucrant"   },
      { nom: "Fécule d'arrow-root", g:  20, pct: 10.2, role: "structure" },
      { nom: "Psyllium",            g:   5, pct:  2.6, role: "liant"     },
      { nom: "Agar-agar",           g:   1, pct:  0.5, role: "structure" },
    ],
    procede: [
      "Monter l'aquafaba en neige ferme au batteur.",
      "Ajouter le sucre blond progressivement en continuant de battre.",
      "Incorporer délicatement l'arrow-root, le psyllium et l'agar-agar tamisés.",
      "Dresser à la poche sur plaque recouverte de papier sulfurisé.",
      "Cuire à 90 °C pendant 2 heures. Laisser sécher dans le four éteint.",
    ],
    cuisson: { temperature_c: 90, duree_min: 120, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 15 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["meringue", "aquafaba", "vegan", "sans oeuf", "sans gluten", "décor"],
    parfum_principal: null,
    note_concepteur: "Aquafaba = jus de cuisson des pois chiches en conserve non salée. La conservation 15°C en boîte hermétique préserve le croustillant.",
    source_interne: { fichier_pdf: "Révolution-Pâtisserie.-La-bible-de-la-pâtisserie-saine-Johanna-Le-Pape_-Mlanie-Frechon-_-WeLib_organized.pdf", page: 180, chef: "Johanna Le Pape", date_extraction: "2026-05-20" },
  },
];
