export const RECETTES_DECORS = [
  {
    id: "enrobage-gourmand-noir",
    nom: "Enrobage gourmand chocolat noir",
    categorie: "decors",
    sous_categorie: "enrobage",
    description: "Enrobage chocolat croustillant aux fruits secs, pour napper glaces et bûches congelées. Application à 40-45°C sur produit congelé.",
    masse_totale_g: 775,
    ingredients: [
      { nom: "Chocolat noir 67%",       g: 500, pct: 64, role: "parfum"  },
      { nom: "Beurre de cacao",         g: 150, pct: 19, role: "mg"      },
      { nom: "Huile pépins de raisin",  g: 50,  pct: 7,  role: "mg"      },
      { nom: "Fruits secs torréfiés",   g: 75,  pct: 10, role: "texture" },
    ],
    procede: [
      "Fondre la couverture avec le beurre de cacao au bain-marie à 45°C.",
      "Ajouter l'huile de pépins de raisin et les fruits secs torréfiés de votre choix (amande, noisette, noix, sésame, grué de cacao…).",
      "Utiliser entre 40-45°C sur produit congelé.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: 15 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["fruits_a_coque"],
    tags: ["enrobage", "chocolat noir", "fruits secs", "décor", "glace", "bûche"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Ajuster la quantité d'huile pour un enrobage plus ou moins fin.",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 62,
      chef: null,
    },
  },

  {
    id: "pulverisation-noir",
    nom: "Pulvérisation velours chocolat noir",
    categorie: "decors",
    sous_categorie: "pulverisation",
    description: "Préparation pour effet velours au pistolet à chocolat. Pulvériser à 45°C sur entremets surgelés pour un fini mat et velouté.",
    masse_totale_g: 400,
    ingredients: [
      { nom: "Chocolat noir 67%",      g: 200, pct: 50, role: "parfum" },
      { nom: "Beurre de cacao",        g: 150, pct: 37, role: "mg"     },
      { nom: "Huile pépins de raisin", g: 50,  pct: 13, role: "mg"     },
    ],
    procede: [
      "Fondre la couverture avec le beurre de cacao au bain-marie à 45°C.",
      "Ajouter l'huile de pépins de raisin.",
      "Pour un effet velours, pulvériser à 45°C sur produits congelés.",
      "Pour donner du brillant sur moulages, pré-cristalliser avant de pulvériser en suivant les courbes de tempérage dédiées.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: 15 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["velours", "pulvérisation", "chocolat noir", "décor", "finition", "pistolet"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Ajouter de l'huile de pépins de raisin donne de la souplesse à la pulvérisation et évite qu'elle ne se fissure sur les entremets lors de la décongélation.",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 64,
      chef: null,
    },
  },

  {
    id: "chocolat-plastique-noir",
    nom: "Chocolat plastique noir",
    categorie: "decors",
    sous_categorie: "chocolat_plastique",
    description: "Pâte à modeler au chocolat, utilisable à température ambiante. Idéale pour décors sculptés et modelés à la main.",
    masse_totale_g: 335,
    ingredients: [
      { nom: "Chocolat noir 67%",     g: 200, pct: 60, role: "parfum"  },
      { nom: "Sirop de glucose DE40", g: 135, pct: 40, role: "sucrant" },
    ],
    procede: [
      "Fondre séparément le chocolat et le glucose à 40-42°C.",
      "Émulsionner ensemble à la spatule silicone.",
      "Verser sur film alimentaire, couvrir hermétiquement.",
      "Laisser cristalliser minimum 12h à 15-20°C avant d'utiliser.",
      "Utiliser par petites quantités en travaillant à la main. Réchauffer très légèrement au micro-ondes si nécessaire.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 20, conservation_c: 15 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["chocolat plastique", "décoration", "modelage", "chocolat noir", "sculpter"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Laisser cristalliser minimum 12h avant utilisation.",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 65,
      chef: null,
    },
  },

  /* ── Révolution Pâtisserie — Johanna Le Pape ────────────────────────────── */

  {
    id: "meringues-vegan-lp",
    nom: "Meringues vegan",
    categorie: "decors",
    sous_categorie: "meringue",
    description: "Meringues 100 % végétales à base d'aquafaba (jus de pois chiche), arrow-root, psyllium et agar-agar. Texture croustillante.",
    masse_totale_g: 196,
    ingredients: [
      { nom: "Aquafaba",            g: 100, pct: 51.0, role: "aeration"  },
      { nom: "Sucre blond",         g:  70, pct: 35.7, role: "sucrant"   },
      { nom: "Fécule d'arrow-root", g:  20, pct: 10.2, role: "structure" },
      { nom: "Psyllium",            g:   5, pct:  2.6, role: "liant"     },
      { nom: "Agar-agar",           g:   1, pct:  0.5, role: "structure" },
    ],
    procede: [
      "Monter l'aquafaba en neige ferme au batteur.",
      "Ajouter le sucre blond progressivement en continuant de battre.",
      "Incorporer délicatement l'arrow-root, le psyllium et l'agar-agar tamisés.",
      "Dresser à la poche sur plaque recouverte de papier sulfurisé.",
      "Cuire à 90 °C pendant 2 heures. Laisser sécher dans le four éteint.",
    ],
    cuisson: { temperature_c: 90, duree_min: 120, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 15 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["meringue", "aquafaba", "vegan", "sans oeuf", "sans gluten", "décor"],
    parfum_principal: null,
    note_concepteur: "Aquafaba = jus de cuisson des pois chiches en conserve non salée. La conservation 15°C en boîte hermétique préserve le croustillant.",
    source_interne: { fichier_pdf: "Révolution-Pâtisserie.-La-bible-de-la-pâtisserie-saine-Johanna-Le-Pape_-Mlanie-Frechon-_-WeLib_organized.pdf", page: 180, chef: "Johanna Le Pape", date_extraction: "2026-05-20" },
  },

  // === Import extraction-2026-08-12 (46 recettes) ===
  {
    id: "nappage-a-pulveriser",
    nom: "Nappage à pulvériser",
    categorie: "decors",
    sous_categorie: "pulverisation",
    description: "Nappage à pulvériser — recette importée, à vérifier.",
    masse_totale_g: 660,
    ingredients: [
      { nom: "nappage absolu", g: 600.0, pct: 90.9, role: "parfum" },
      { nom: "eau", g: 60.0, pct: 9.1, role: "eau" },
    ],
    procede: [
      "Faire chauffer le nappage et l’eau, ajouter le scintillant et pulvériser.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["pulverisation"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Bûche tiramisu.docx", import: "extraction-2026-08-12" },
  },
  {
    id: "cristalline",
    nom: "CRISTALLINE",
    categorie: "decors",
    sous_categorie: "pastillage",
    description: "CRISTALLINE — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "EAU", g: 285.7, pct: 28.6, role: "eau" },
      { nom: "SUCRE SEMOULE", g: 714.3, pct: 71.4, role: "sucrant" },
    ],
    procede: [
      "0",
      "FAIRE BOUILLIR SUCRE ET EAU",
      "COULER, PARSEMER DE SUCRE ET LAISSER REPOSER 48H SANS TOUCHER",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["pastillage"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "CRISTALLINE.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "chocolat-rose",
    nom: "Chocolat  rose",
    categorie: "decors",
    sous_categorie: "coloration",
    description: "Chocolat  rose — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Couverture ivoire", g: 999.5, pct: 99.9, role: "parfum" },
      { nom: "Colorant liposoluble rouge", g: 0.5, pct: 0.1, role: "colorant" },
    ],
    procede: [
      "Faire la couverture ivoire.",
      "Fondre également le beurre de cacao puis ajouter le colorant, bien dissoudre.",
      "Reverser dans la couverture ivoire.",
      "Mélanger puis mettre au point avant utilisation.",
      "Melt a white chocolate",
      "Melt too a cocoa butter, and add a coloring, mix",
      "Pour on white chocolate.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten"],
    tags: ["coloration", "chocolat blanc", "La pink"],
    parfum_principal: "chocolat blanc",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Chocolat  Rose.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "chocolat-au-cafe",
    nom: "Chocolat au café",
    categorie: "decors",
    sous_categorie: "coloration",
    description: "Chocolat au café — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Couverture Ivoire", g: 781.2, pct: 78.1, role: "parfum" },
      { nom: "Café soluble Fauchon", g: 11.7, pct: 1.2, role: "parfum" },
      { nom: "Eau", g: 11.7, pct: 1.2, role: "eau" },
      { nom: "Beurre de cacao", g: 195.3, pct: 19.5, role: "mg" },
    ],
    procede: [
      "Dissoudre le café avec l'eau bouillante, laisser refroidir.",
      "Ajouter le mélange froid au chocolat blanc fondu, bien mélanger.",
      "En dernier le beurre de cacao fondu.",
      "Mettre la couverture au point avant utilisation.",
      "Dissolve a coffee with the water boiling, to cool.",
      "When the mixture is cold add a chocolate melted. Mix.",
      "And a last, add a cocoa butter melted.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten"],
    tags: ["coloration", "chocolat blanc", "Eclair café liégois"],
    parfum_principal: "chocolat blanc",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Chocolat au café.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "chocolat-blanc-de-blanc",
    nom: "Chocolat blanc de blanc",
    categorie: "decors",
    sous_categorie: "coloration",
    description: "Chocolat blanc de blanc — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Couverture ivoire", g: 870.8, pct: 87.1, role: "parfum" },
      { nom: "Beurre de cacao", g: 87.1, pct: 8.7, role: "mg" },
      { nom: "Oxyde de titane", g: 42.1, pct: 4.2, role: "colorant" },
    ],
    procede: [
      "Faire fondre la couverture puis ajouter le beurre de cacao fondu puis l'oxyde",
      "de titane.",
      "Mixer.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["coloration", "chocolat blanc", "Plaque Carremenchoc"],
    parfum_principal: "chocolat blanc",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Chocolat blanc de blanc.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "chocolat-mangue",
    nom: "Chocolat mangue",
    categorie: "decors",
    sous_categorie: "coloration",
    description: "Chocolat mangue — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Chocolat ivoire", g: 996.7, pct: 99.7, role: "parfum" },
      { nom: "Colorant jaune lipo", g: 3.2, pct: 0.3, role: "liant" },
      { nom: "Colorant rouge lipo", g: 0.2, pct: 0.0, role: "colorant" },
    ],
    procede: [
      "Mixer les colorants dans la couverture ivoire.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["oeuf"],
    tags: ["coloration", "chocolat blanc", "1000F vanille mangue"],
    parfum_principal: "chocolat blanc",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Chocolat mangue.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "chocolat-orange-1",
    nom: "Chocolat orange 1",
    categorie: "decors",
    sous_categorie: "coloration",
    description: "Chocolat orange 1 — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Couverture Ivoire", g: 993.6, pct: 99.4, role: "parfum" },
      { nom: "Colorant liposoluble orange", g: 6.4, pct: 0.6, role: "colorant" },
    ],
    procede: [
      "Fondre la couverture ivoire.",
      "Prélever une petite partie pour dissoudre le colorant liposoluble.",
      "Mélanger l'ensemble puis mettre au point.",
      "Melt a white chocolate.",
      "Take a small quantity for mix a coloring.",
      "Mix all together.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten"],
    tags: ["coloration", "chocolat blanc", "Sphère orange"],
    parfum_principal: "chocolat blanc",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Chocolat orange 1.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "chocolat-plastique-blanc",
    nom: "Chocolat plastique blanc",
    categorie: "decors",
    sous_categorie: "chocolat_plastique",
    description: "Chocolat plastique blanc — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Beurre de cacao", g: 217.4, pct: 21.7, role: "mg" },
      { nom: "Glucose", g: 260.9, pct: 26.1, role: "sucrant" },
      { nom: "Sucre glace", g: 521.7, pct: 52.2, role: "sucrant" },
    ],
    procede: [
      "Faire fondre le beurre de cacao.",
      "Mélanger au glucose et incorporer le sucre glace.",
      "Bien malaxer.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["chocolat plastique", "Fleur saint valentin"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Chocolat plastique blanc.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "chocolat-plastique-fushia",
    nom: "Chocolat plastique fushia",
    categorie: "decors",
    sous_categorie: "chocolat_plastique",
    description: "Chocolat plastique fushia — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Beurre de cacao", g: 563.9, pct: 56.4, role: "mg" },
      { nom: "Sucre glace", g: 417.3, pct: 41.7, role: "sucrant" },
      { nom: "Colorant fushia", g: 18.8, pct: 1.9, role: "colorant" },
    ],
    procede: [
      "Mixer le beurre de cacao froid",
      "Mettre le sucre glace petit à petit",
      "Finir par le colorant",
      "Bien mixer",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["chocolat plastique", "Buche ruban (gâteau du 31)"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Chocolat plastique fushia.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "chocolat-rouge-1",
    nom: "Chocolat rouge 1",
    categorie: "decors",
    sous_categorie: "coloration",
    description: "Chocolat rouge 1 — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Couverture Ivoire", g: 875.0, pct: 87.5, role: "parfum" },
      { nom: "Beurre de cacao", g: 122.5, pct: 12.3, role: "mg" },
      { nom: "Colorant liposoluble rouge", g: 2.4, pct: 0.2, role: "colorant" },
    ],
    procede: [
      "Faire fondre le beurre de cacao puis dissoudre le colorant.",
      "Fondre également la couverture ivoire puis réunir les deux.",
      "Millefeuille :  Détailler des pastilles de 2cm et 1,5 cm de diamètre",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten"],
    tags: ["coloration", "chocolat blanc", "Millefeuille vanille fraises des bois"],
    parfum_principal: "chocolat blanc",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Chocolat rouge 1.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "chocolat-rouge",
    nom: "Chocolat rouge",
    categorie: "decors",
    sous_categorie: "coloration",
    description: "Chocolat rouge — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Couverture Ivoire", g: 830.0, pct: 83.0, role: "parfum" },
      { nom: "Beurre de cacao", g: 166.0, pct: 16.6, role: "mg" },
      { nom: "Colorant liposoluble rouge", g: 4.0, pct: 0.4, role: "colorant" },
    ],
    procede: [
      "Faire fondre le beurre de cacao puis dissoudre le colorant.",
      "Fondre également la couverture ivoire puis réunir les deux.",
      "Millefeuille :  Détailler des pastilles de 2cm et 1,5 cm de diamètre",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten"],
    tags: ["coloration", "chocolat blanc", "Embout de bûche", "Millefeuille vanille framboise"],
    parfum_principal: "chocolat blanc",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Chocolat rouge.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "chocolat-vert-1",
    nom: "Chocolat Vert 1",
    categorie: "decors",
    sous_categorie: "coloration",
    description: "Chocolat Vert 1 — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Couverture Ivoire", g: 998.3, pct: 99.8, role: "parfum" },
      { nom: "Colorant vert liposoluble", g: 1.7, pct: 0.2, role: "colorant" },
    ],
    procede: [
      "Fondre la couverture et ajouter le colorant liposoluble;",
      "mixer",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten"],
    tags: ["coloration", "chocolat blanc", "Eclair dragée rose"],
    parfum_principal: "chocolat blanc",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Chocolat vert 1.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "chocolat-vert-2",
    nom: "Chocolat Vert 2",
    categorie: "decors",
    sous_categorie: "coloration",
    description: "Chocolat Vert 2 — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Couverture Ivoire", g: 961.4, pct: 96.1, role: "parfum" },
      { nom: "Colorant vert liposoluble", g: 4.8, pct: 0.5, role: "colorant" },
      { nom: "Colorant jaune liposoluble", g: 24.2, pct: 2.4, role: "liant" },
      { nom: "Dioxyde de titane", g: 9.7, pct: 1.0, role: "colorant" },
    ],
    procede: [
      "Fondre la couverture et ajouter les colorants liposolubles et le dioxyde de titane.",
      "Mixer et mettre au point.",
      "Etaler à épaisseur 2 mm.",
      "Détailler des carrés de 2,2 x 2,2 cm.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten", "oeuf"],
    tags: ["coloration", "chocolat blanc", "Logo vert carré framboise 2"],
    parfum_principal: "chocolat blanc",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Chocolat vert 2.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "chocolat-vert",
    nom: "Chocolat vert",
    categorie: "decors",
    sous_categorie: "coloration",
    description: "Chocolat vert — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Couverture Ivoire", g: 995.0, pct: 99.5, role: "parfum" },
      { nom: "Colorant liposoluble vert", g: 5.0, pct: 0.5, role: "colorant" },
    ],
    procede: [
      "Fondre la couverture ivoire puis ajouter le colorant vert.",
      "Mettre le chocolat vert au point avant de l'étaler à une épaisseur de 2mm.",
      "Détailler des rectangle de 8,5 x 7 cm pour les bûches et 5 x 4 cm pour les bûchettes",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten"],
    tags: ["coloration", "chocolat blanc", "Bûche Carrémangue"],
    parfum_principal: "chocolat blanc",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Chocolat vert.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "coco-rouge",
    nom: "Coco rouge",
    categorie: "decors",
    sous_categorie: "coloration",
    description: "Coco rouge — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Noix de coco rapée", g: 992.1, pct: 99.2, role: "parfum" },
      { nom: "Colorant liposoluble rouge", g: 7.9, pct: 0.8, role: "colorant" },
    ],
    procede: [
      "Torréfié la noix de coco, refroidir puis mixer légèrement.",
      "Ajouter le colorant poudre.",
      "Bien mélanger.",
      "Roast a coconut, to cool.",
      "Crush lightly.",
      "Add a red coloring.",
      "Mix",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["fruits_a_coque", "gluten"],
    tags: ["coloration", "coco", "Millecoeur framboise"],
    parfum_principal: "coco",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Coco rouge.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "colorant-fushia",
    nom: "Colorant fushia",
    categorie: "decors",
    sous_categorie: "coloration",
    description: "Colorant fushia — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Eau", g: 833.3, pct: 83.3, role: "eau" },
      { nom: "Colorant rouge violet", g: 166.7, pct: 16.7, role: "colorant" },
    ],
    procede: [
      "mélanger les deux ingrédients",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["coloration", "Chocolat plastique fushia"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Colorant fushia.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "couverture-jaune-1",
    nom: "Couverture jaune 1",
    categorie: "decors",
    sous_categorie: "coloration",
    description: "Couverture jaune 1 — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Colorant jaune lipo", g: 0.8, pct: 0.1, role: "liant" },
      { nom: "Couverture ivoire", g: 999.2, pct: 99.9, role: "parfum" },
    ],
    procede: [
      "Fondre la couverture, prélever une petite partie pour dissoudre le colorant.",
      "Tout remélanger",
      "Mettre au point puis étaler sur le transfert.",
      "Melt a white chocolate, deduct a small quantity for dissolve the coloring.",
      "Mix all together",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["oeuf"],
    tags: ["coloration", "chocolat blanc", "Eclair abricot"],
    parfum_principal: "chocolat blanc",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Couverture jaune 1.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "couverture-jaune-2",
    nom: "Couverture jaune 2",
    categorie: "decors",
    sous_categorie: "coloration",
    description: "Couverture jaune 2 — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Colorant jaune lipo", g: 5.0, pct: 0.5, role: "liant" },
      { nom: "Couverture ivoire", g: 995.0, pct: 99.5, role: "parfum" },
    ],
    procede: [
      "Fondre la couverture, prélever une petite partie pour dissoudre le colorant.",
      "Tout remélanger",
      "Mettre au point puis étaler sur le transfert.",
      "Melt a white chocolate, deduct a small quantity for dissolve the coloring.",
      "Mix all together",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["oeuf"],
    tags: ["coloration", "chocolat blanc", "Eclair pamplemousse"],
    parfum_principal: "chocolat blanc",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Couverture jaune 2.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "couverture-jaune-3",
    nom: "Couverture jaune 3",
    categorie: "decors",
    sous_categorie: "coloration",
    description: "Couverture jaune 3 — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Colorant jaune lipo", g: 3.2, pct: 0.3, role: "liant" },
      { nom: "Couverture ivoire", g: 996.7, pct: 99.7, role: "parfum" },
      { nom: "Colorant rouge lipo", g: 0.2, pct: 0.0, role: "colorant" },
    ],
    procede: [
      "Fondre la couverture, prélever une petite partie pour dissoudre les colorants.",
      "Tout remélanger",
      "Mettre au point puis étaler sur papier guitare et détailler des pastilles.",
      "Melt a white chocolate, deduct a small quantity for dissolve the coloring.",
      "Mix all together",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["oeuf"],
    tags: ["coloration", "chocolat blanc", "Millfeuille vanille mangue"],
    parfum_principal: "chocolat blanc",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Couverture jaune 3.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "gum-paste",
    nom: "GUM PASTE",
    categorie: "decors",
    sous_categorie: "pastillage",
    description: "GUM PASTE — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "SUCRE GLACE AMYLASE", g: 602.6, pct: 60.3, role: "sucrant" },
      { nom: "SUCRE SEMOULE", g: 167.4, pct: 16.7, role: "sucrant" },
      { nom: "EAU", g: 33.5, pct: 3.3, role: "eau" },
      { nom: "GLUCOSE", g: 67.0, pct: 6.7, role: "sucrant" },
      { nom: "VEGETALINE", g: 67.0, pct: 6.7, role: "parfum" },
      { nom: "GELATINE POISSON", g: 9.0, pct: 0.9, role: "gelifiant" },
      { nom: "EAU", g: 45.2, pct: 4.5, role: "eau" },
      { nom: "CITRON", g: 8.4, pct: 0.8, role: "acidite" },
    ],
    procede: [
      "0",
      "MELANGER GELATINE ET EAU 20MIN AVANT",
      "CUIRE SUCRE SEMOULE, EAU ET GLUCOSE A 112°C",
      "TAMISER LE SUCRE GLACE AMYLASE",
      "FAIRE FONDRE LA VEGETALINE ET AJOUTER LA GELATINE, CITRON, FAIRE FONDRE",
      "VERSER SUCRE SUR SUCRE GLACE ET MELANGER A LA FEUILLE",
      "PUIS AJOUTER MELANGE GELATINE ET VEGETALINE FONDU",
      "DEBARRASSER SUR PLAQUE DANS CADRE ET RECOUVRIR D'UNE FEUILLE SULFU",
      "0",
      "0",
      "0",
    ],
    cuisson: { temperature_c: 112, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["pastillage", "citron"],
    parfum_principal: "citron",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "GUM PASTE.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "pastillage",
    nom: "Pastillage",
    categorie: "decors",
    sous_categorie: "pastillage",
    description: "Pastillage — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Sucre glace", g: 813.7, pct: 81.4, role: "sucrant" },
      { nom: "Fécule de PDT", g: 81.4, pct: 8.1, role: "structure" },
      { nom: "Jus de citron", g: 9.8, pct: 1.0, role: "acidite" },
      { nom: "Eau", g: 65.1, pct: 6.5, role: "eau" },
      { nom: "Gélatine feuille", g: 8.1, pct: 0.8, role: "gelifiant" },
      { nom: "colorant rouge Mac", g: 22.0, pct: 2.2, role: "colorant" },
    ],
    procede: [
      "Faire tremper la gelatine dans l'eau froide pendnat au moins 20 min.",
      "Tamiser le sucre glace et la fécule de PDT ensemble.",
      "Faire bouillier l'eau  et le jus de citron.",
      "Incorporer la gélatine dans l'eau et le jus de citron.",
      "Mélanger le tout puis incorporer le colorant.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["pastillage", "citron"],
    parfum_principal: "citron",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Pastillage.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "pastillage-rose",
    nom: "Pastillage rose",
    categorie: "decors",
    sous_categorie: "pastillage",
    description: "Pastillage rose — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Pastillage", g: 997.3, pct: 99.7, role: "parfum" },
      { nom: "Colorant rouge PCB", g: 2.7, pct: 0.3, role: "colorant" },
    ],
    procede: [
      "Mélanger le colarant avec le pastillage.",
      "Fleurs Côté fleuri : étaler à 2mm",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["pastillage", "Côté fleuri et Côté jardin"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Pastillage rose.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "pastillage-rouge",
    nom: "Pastillage rouge",
    categorie: "decors",
    sous_categorie: "pastillage",
    description: "Pastillage rouge — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Pastillage", g: 988.8, pct: 98.9, role: "parfum" },
      { nom: "Colorant rouge PCB", g: 11.2, pct: 1.1, role: "colorant" },
    ],
    procede: [
      "Mélanger le colarant avec le pastillage.",
      "Fleurs Côté fleuri : étaler à 2mm",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["pastillage", "Côté fleuri"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Pastillage rouge.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "pastillage-a-chaud",
    nom: "PASTILLAGE à chaud",
    categorie: "decors",
    sous_categorie: "pastillage",
    description: "PASTILLAGE à chaud — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Gélatine feuille", g: 10.5, pct: 1.1, role: "gelifiant" },
      { nom: "Eau", g: 68.4, pct: 6.8, role: "eau" },
      { nom: "Vinaigre", g: 26.3, pct: 2.6, role: "acidite" },
      { nom: "Sucre glace", g: 263.2, pct: 26.3, role: "sucrant" },
      { nom: "Fécule", g: 105.3, pct: 10.5, role: "structure" },
      { nom: "Sucre glace", g: 526.3, pct: 52.6, role: "sucrant" },
    ],
    procede: [
      "0",
      "Faire tremper la gélatine dans l'eau au minimum 20min avant utilisation.",
      "Egoutter. Dans une grande casserole, chauffer le vinaigre et ajouter la gélatine.",
      "Ajouter le premier sucre glace tamisé dans la casserole de la gélatine et mélanger.",
      "Au mélangeur, mettre le deuxième sucre glace et la fécule le tout tamisés.",
      "Verser le mélange de la casserole sur les poudres et mélanger à la feuille.",
      "Retirer le pastillage, filmer et stocker au réfrigérateur.",
      "0",
      "0",
      "0",
      "0",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["pastillage"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Pastillage à chaud.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "pepites-or",
    nom: "Pépites Or",
    categorie: "decors",
    sous_categorie: "coloration",
    description: "Pépites Or — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Eclat de sucre pétillant", g: 995.0, pct: 99.5, role: "sucrant" },
      { nom: "Poudre or", g: 5.0, pct: 0.5, role: "parfum" },
    ],
    procede: [
      "Mettre les pépites de chocolat au surgélateur 5 minutes sur plaque Une fois les pépites froide incorporr la poudre or et les pépites dans un cul de poule Mélanger le tout avec des gants Stocker en boîtes de macarons",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["coloration", "Eclair chocolat fauchon Caroline chocolat fauchon"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Pépites or.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "petale-de-rose-cristalise",
    nom: "Pétale de rose cristalisé",
    categorie: "decors",
    sous_categorie: "decor_sucre",
    description: "Pétale de rose cristalisé — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Pétale de rose ( Un )", g: 993.1, pct: 99.3, role: "parfum" },
      { nom: "Sucre semoule", g: 2.0, pct: 0.2, role: "sucrant" },
      { nom: "Blanc d'œuf", g: 5.0, pct: 0.5, role: "aeration" },
    ],
    procede: [
      "Prendre 1 pétale de rose ( fraiche ), l'enduire de blancs d'œufs au pinceau.",
      "Saupoudrer de sucre semoule.",
      "Disposer sur plaque en étuve pendant 24h.",
      "1 rose commander chez charair permait de fair 34 petales de rose cristalisé ( 1choux/1petale )",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["oeuf"],
    tags: ["decor sucre", "Choux fraise framboise rose et vanille"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Pétale de rose cristalisé.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "sucre-jaune",
    nom: "Sucre Jaune",
    categorie: "decors",
    sous_categorie: "sucre_decor",
    description: "Sucre Jaune — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Sucre semoule", g: 996.9, pct: 99.7, role: "sucrant" },
      { nom: "Colorant liposoluble jaune", g: 3.0, pct: 0.3, role: "liant" },
      { nom: "Colorant liposoluble rouge", g: 0.1, pct: 0.0, role: "colorant" },
    ],
    procede: [
      "Mélanger les trois ingrédients.",
      "1 un = 1g",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten", "oeuf"],
    tags: ["sucre decor", "Guimauve mangue Jasmin"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Sucre Jaune.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "sucre-orange",
    nom: "Sucre Orange",
    categorie: "decors",
    sous_categorie: "sucre_decor",
    description: "Sucre Orange — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Sucre semoule", g: 997.0, pct: 99.7, role: "sucrant" },
      { nom: "Colorant liposoluble orange", g: 3.0, pct: 0.3, role: "colorant" },
    ],
    procede: [
      "Mélanger les deux ingrédients",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten"],
    tags: ["sucre decor", "Guimauve mandarine"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Sucre Orange.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "sucre-candi",
    nom: "Sucre Candi",
    categorie: "decors",
    sous_categorie: "coloration",
    description: "Sucre Candi — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Eau", g: 285.7, pct: 28.6, role: "eau" },
      { nom: "Sucre semoule", g: 714.3, pct: 71.4, role: "sucrant" },
    ],
    procede: [
      "Donner un bouillon.",
      "Débarasser, laisser refroidir avant d'incruster les pièces à candir.",
      "Faire des boules de diamétre voulu en végétaline",
      "Une fois refroidies, les piquer avec un curdent",
      "Les recouvrir légèrement de sucre cristal",
      "Ensuite, les plonger dans le candi",
      "Laisser reposer 24h",
      "Débarrasser les boules de végétaline; les mettre à l'étuve",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["coloration", "Buche ruban"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Sucre candi.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "sucre-decor-pour-choux",
    nom: "Sucre décor pour choux",
    categorie: "decors",
    sous_categorie: "sucre_decor",
    description: "Sucre décor pour choux — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "sucre", g: 626.0, pct: 62.6, role: "sucrant" },
      { nom: "eau", g: 250.0, pct: 25.0, role: "eau" },
      { nom: "glucose", g: 62.0, pct: 6.2, role: "sucrant" },
      { nom: "nougasec", g: 62.0, pct: 6.2, role: "parfum" },
    ],
    procede: [
      "Mélanger le nougat sec avec une petite quantité de sucre.",
      "Faire bouillir l'eau et le sucre, ajouter le glucose à ébullition.",
      "Cuire à 70°C suivant la couleur",
      "Laisser reposer le sucre 10 minutes avant utilisation;",
    ],
    cuisson: { temperature_c: 70, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sucre decor", "Croquembouche classique et fleuri"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Sucre décor pour choux.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "sucre-pistache",
    nom: "Sucre Pistache",
    categorie: "decors",
    sous_categorie: "sucre_decor",
    description: "Sucre Pistache — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Sucre semoule", g: 999.0, pct: 99.9, role: "sucrant" },
      { nom: "Colorant liposoluble vert", g: 1.0, pct: 0.1, role: "colorant" },
    ],
    procede: [
      "Mélanger les deux ingrédients",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten"],
    tags: ["sucre decor", "pistache", "Guimauve pistache"],
    parfum_principal: "pistache",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Sucre pistache.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "sucre-vert",
    nom: "Sucre vert",
    categorie: "decors",
    sous_categorie: "sucre_decor",
    description: "Sucre vert — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Sucre semoule", g: 980.4, pct: 98.0, role: "sucrant" },
      { nom: "Colorant liposoluble vert", g: 19.6, pct: 2.0, role: "colorant" },
    ],
    procede: [
      "Mélanger les deux ingrédients.",
      "Conserver à l'abri de l'humidité.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten"],
    tags: ["sucre decor", "Macarons citron menthe fraiche"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Sucre vert.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "preparation-argent",
    nom: "Préparation Argent",
    categorie: "decors",
    sous_categorie: "coloration",
    description: "Préparation Argent — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Poudre argent PCB", g: 222.2, pct: 22.2, role: "parfum" },
      { nom: "Kirsch", g: 777.8, pct: 77.8, role: "parfum" },
    ],
    procede: [
      "140 g = 50 macarons",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["coloration"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Préparation Argent.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "preparation-or",
    nom: "Préparation Or",
    categorie: "decors",
    sous_categorie: "coloration",
    description: "Préparation Or — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Poudre or PCB", g: 222.2, pct: 22.2, role: "parfum" },
      { nom: "Kirsch", g: 777.8, pct: 77.8, role: "parfum" },
    ],
    procede: [
      "140 g = 50 macarons",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["coloration"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Préparation Or.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "preparation-rose",
    nom: "Préparation Rose",
    categorie: "decors",
    sous_categorie: "coloration",
    description: "Préparation Rose — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Poudre Rose PCB", g: 222.2, pct: 22.2, role: "parfum" },
      { nom: "Kirsch", g: 777.8, pct: 77.8, role: "parfum" },
    ],
    procede: [
      "140 g = 50 macarons",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["coloration"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Préparation Rose.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "sucre-fraise-basilic",
    nom: "Sucre fraise basilic",
    categorie: "decors",
    sous_categorie: "sucre_decor",
    description: "Sucre fraise basilic — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Sucre semoule", g: 991.1, pct: 99.1, role: "sucrant" },
      { nom: "Colorant liposoluble rouge", g: 4.0, pct: 0.4, role: "colorant" },
      { nom: "Gourmandise", g: 5.0, pct: 0.5, role: "parfum" },
    ],
    procede: [
      "Mélanger les deux ingrédients.",
      "1un = 1g",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten"],
    tags: ["sucre decor", "fraise", "Guimauve fraise basilic"],
    parfum_principal: "fraise",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Sucre fraise basilic.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "sucre-framboise",
    nom: "Sucre framboise",
    categorie: "decors",
    sous_categorie: "sucre_decor",
    description: "Sucre framboise — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Sucre", g: 986.8, pct: 98.7, role: "sucrant" },
      { nom: "Colorant liposoluble rouge", g: 13.2, pct: 1.3, role: "colorant" },
    ],
    procede: [
      "Mélanger les deux ingrédients.",
      "Parsemer sur les guimauves framboises.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten"],
    tags: ["sucre decor", "framboise", "Charlotte orange framboise"],
    parfum_principal: "framboise",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Sucre framboise.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "enrobage-chocolat-rouge",
    nom: "Enrobage chocolat rouge",
    categorie: "decors",
    sous_categorie: "coloration",
    description: "Enrobage chocolat rouge — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Couverture ivoire", g: 744.0, pct: 74.4, role: "parfum" },
      { nom: "Beurre de cacao", g: 248.1, pct: 24.8, role: "mg" },
      { nom: "Colorange rouge liposoluble PCB", g: 8.0, pct: 0.8, role: "parfum" },
    ],
    procede: [
      "Faire fondre le beurre de cacao et la couverture ivoire puis mélanger les deux.",
      "Délayer le colorant avec un petit peu de chocolat.",
      "Puis ajouter le reste.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten"],
    tags: ["coloration", "chocolat blanc", "Boulier chocolat framboise"],
    parfum_principal: "chocolat blanc",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Enrobage chocolat rouge.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "veloutage-blanc-blanc",
    nom: "Veloutage blanc blanc",
    categorie: "decors",
    sous_categorie: "pulverisation",
    description: "Veloutage blanc blanc — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Couverture Ivoire", g: 414.4, pct: 41.4, role: "parfum" },
      { nom: "Beurre de cacao", g: 537.5, pct: 53.8, role: "mg" },
      { nom: "Dioxyde de titane", g: 48.0, pct: 4.8, role: "colorant" },
    ],
    procede: [
      "Fondre la couverture ivoire et le beurre de cacao.",
      "Prélever un peu du mélange pour dissoudre petit à petit l'oxyde de titane.",
      "Chinoiser et remélanger au reste de la couverture.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["pulverisation", "chocolat blanc", "Bûche Marron myrtille", "Entremet vanille-caramel"],
    parfum_principal: "chocolat blanc",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Veloutage blanc blanc.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "veloutage-gris",
    nom: "Veloutage gris",
    categorie: "decors",
    sous_categorie: "pulverisation",
    description: "Veloutage gris — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Couverture Ivoire", g: 412.7, pct: 41.3, role: "parfum" },
      { nom: "Beurre de cacao", g: 535.7, pct: 53.6, role: "mg" },
      { nom: "Dioxyde de titane", g: 47.6, pct: 4.8, role: "colorant" },
      { nom: "Colorant noir charbon", g: 4.0, pct: 0.4, role: "colorant" },
    ],
    procede: [
      "Fondre la couverture ivoire et le beurre de cacao.",
      "Prélever un peu du mélange pour dissoudre petit à petit l'oxyde de titane et le colorant noir.",
      "Chinoiser et remélanger au reste de la couverture.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["pulverisation", "chocolat blanc", "Mima"],
    parfum_principal: "chocolat blanc",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Veloutage gris.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "veloutage-lait",
    nom: "Veloutage lait",
    categorie: "decors",
    sous_categorie: "pulverisation",
    description: "Veloutage lait — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Couverture Jivara", g: 500.0, pct: 50.0, role: "parfum" },
      { nom: "Beurre de cacao", g: 500.0, pct: 50.0, role: "mg" },
    ],
    procede: [
      "Faire fondre la couverture et le beurre de cacao.",
      "Mixer avant chaque utilisation.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["pulverisation", "chocolat lait", "entremet chocolat caramel", "Bonheur assiette 1", "Verrine poire marron"],
    parfum_principal: "chocolat lait",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Veloutage lait.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "veloutage-noir",
    nom: "Veloutage noir",
    categorie: "decors",
    sous_categorie: "pulverisation",
    description: "Veloutage noir — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Couverture Caraque 56%", g: 705.9, pct: 70.6, role: "parfum" },
      { nom: "Beurre de cacao", g: 294.1, pct: 29.4, role: "mg" },
    ],
    procede: [
      "Faire fondre la couverture et le beurre de cacao.",
      "Mixer et chinoiser avant chaque utilisation.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["pulverisation", "Bûche carrémenchoc", "La black", "Dessert à l'assiette bizot mousse chocolat", "Carachoc"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Veloutage noir..xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "veloutage-orange",
    nom: "Veloutage orange",
    categorie: "decors",
    sous_categorie: "pulverisation",
    description: "Veloutage orange — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Couverture Ivoire", g: 905.4, pct: 90.5, role: "parfum" },
      { nom: "Colorant liposoluble orange", g: 14.1, pct: 1.4, role: "colorant" },
      { nom: "Beurre de cacao", g: 80.5, pct: 8.0, role: "mg" },
    ],
    procede: [
      "Fondre la couverture ivoire et le beurre de cacao.",
      "Prélever une petite partie de la couverture pour dissoudre le colorant liposoluble.",
      "Remélanger à la couverture et ajouter le beurre de cacao.",
      "Melt a white chocolate and a cocoa butter.",
      "Take a small quantity of chocolate for mix a coloring.",
      "Mix all together and add a cocoa butter.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten"],
    tags: ["pulverisation", "chocolat blanc", "Sphère orange"],
    parfum_principal: "chocolat blanc",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Veloutage orange.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "chocolat-a-pulveriser-rose-1",
    nom: "Chocolat à pulvériser rose 1",
    categorie: "decors",
    sous_categorie: "pulverisation",
    description: "Chocolat à pulvériser rose 1 — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Couverture ivoire", g: 713.3, pct: 71.3, role: "parfum" },
      { nom: "Beurre de cacao", g: 285.7, pct: 28.6, role: "mg" },
      { nom: "Colorant liposoluble rouge", g: 1.0, pct: 0.1, role: "colorant" },
    ],
    procede: [
      "Fondre la couverture ivoire, ajouter le beurre de cacao fondu.",
      "Prélever une petite partie pour dissoudre le colorant.",
      "Tout remélanger ensemble.",
      "Melt a chocolate and cocoa butter.",
      "Dissolve a coloring with a small quantity of cocoa butter.",
      "Mix all together.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten"],
    tags: ["pulverisation", "chocolat blanc", "Duo 2008"],
    parfum_principal: "chocolat blanc",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Veloutage rose 1.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "chocolat-a-pulveriser-rose",
    nom: "Chocolat à pulvériser rose",
    categorie: "decors",
    sous_categorie: "pulverisation",
    description: "Chocolat à pulvériser rose — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Couverture ivoire", g: 712.6, pct: 71.3, role: "parfum" },
      { nom: "Beurre de cacao", g: 285.4, pct: 28.5, role: "mg" },
      { nom: "Colorant liposoluble rouge", g: 2.0, pct: 0.2, role: "colorant" },
    ],
    procede: [
      "Fondre la couverture ivoire, ajouter le beurre de cacao fondu.",
      "Prélever une petite partie pour dissoudre le colorant.",
      "Tout remélanger ensemble.",
      "Melt a chocolate and cocoa butter.",
      "Dissolve a coloring with a small quantity of cocoa butter.",
      "Mix all together.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten"],
    tags: ["pulverisation", "chocolat blanc", "La pink."],
    parfum_principal: "chocolat blanc",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Veloutage rose.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "veloutage-vert",
    nom: "Veloutage vert",
    categorie: "decors",
    sous_categorie: "pulverisation",
    description: "Veloutage vert — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Couverture Ivoire", g: 348.5, pct: 34.8, role: "parfum" },
      { nom: "Beurre de cacao", g: 602.8, pct: 60.3, role: "mg" },
      { nom: "Colorant liposoluble vert", g: 15.1, pct: 1.5, role: "colorant" },
      { nom: "Veloutage blanc de blanc", g: 33.6, pct: 3.4, role: "parfum" },
    ],
    procede: [
      "Fondre ensemble la couverture ivoire et le beurre de cacao.",
      "Détendre petit à petit les colorants avant de les ajouter au reste.",
      "Mixer pour parfaire le mélange.",
      "ATTENTION POIDS DU COLORANT !!!",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten", "oeuf"],
    tags: ["pulverisation", "chocolat blanc", "Côté jardin"],
    parfum_principal: "chocolat blanc",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Veloutage vert.xlsx", import: "extraction-2026-08-12" },
  },
];
