export const RECETTES_GANACHES = [
  {
    id: "ganache-montee-noir",
    nom: "Ganache montée chocolat noir",
    categorie: "ganaches",
    sous_categorie: "ganache_montee",
    description: "Ganache émulsionnée à froid puis montée en chantilly chocolatée. Texture aérée, tenue optimale au pochage.",
    masse_totale_g: 509,
    ingredients: [
      { nom: "Crème liquide 35% n°1",  g: 130, pct: 26, role: "mg"      },
      { nom: "Lait UHT entier",         g: 60,  pct: 12, role: "eau"     },
      { nom: "Sucre inverti",           g: 12,  pct: 2,  role: "sucrant" },
      { nom: "Sirop de glucose DE60",   g: 12,  pct: 2,  role: "sucrant" },
      { nom: "Chocolat noir 67%",       g: 95,  pct: 19, role: "parfum"  },
      { nom: "Crème liquide 35% n°2",  g: 200, pct: 39, role: "mg"      },
    ],
    procede: [
      "Porter le lait, le sucre inverti et la crème n°1 à ébullition.",
      "Verser sur le chocolat fondu, émulsionner au mixeur plongeant.",
      "Ajouter la crème froide n°2, mixer à nouveau.",
      "Filmer au contact, refroidir rapidement à 4°C.",
      "Laisser cristalliser 12h minimum, idéalement 24h avant de monter.",
      "Monter au batteur à vitesse moyenne jusqu'à texture chantilly. Pocher immédiatement.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 10, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["ganache", "chocolat noir", "pocher", "entremets", "montée", "chantilly"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Pour une texture lisse et légère, monter lentement sans trop serrer et utiliser aussitôt. La recette est équilibrée pour minimiser le sucre ajouté tout en assurant tenue et saveur.",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 36,
      chef: null,
    },
  },

  {
    id: "ganache-patissiere-noir",
    nom: "Ganache pâtissière chocolat noir",
    categorie: "ganaches",
    sous_categorie: "ganache_patissiere",
    description: "Ganache crémeuse à base de crème et lait entier, texture souple et élastique. Idéale pour pocher ou garnir.",
    masse_totale_g: 600,
    ingredients: [
      { nom: "Crème liquide 35%",        g: 140, pct: 23, role: "mg"      },
      { nom: "Lait UHT entier",           g: 140, pct: 23, role: "eau"     },
      { nom: "Sucre inverti",             g: 60,  pct: 10, role: "sucrant" },
      { nom: "Sirop de glucose DE 38/40", g: 30,  pct: 5,  role: "sucrant" },
      { nom: "Chocolat noir 67%",         g: 230, pct: 39, role: "parfum"  },
    ],
    procede: [
      "Porter à ébullition la crème, le lait entier, le sucre inverti et le glucose.",
      "Verser en 3 fois sur le chocolat fondu.",
      "Parfaire l'émulsion au mixeur plongeant sans incorporer d'air.",
      "Filmer au contact. Conserver à 4°C.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 10, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["ganache", "chocolat noir", "pocher", "entremets", "pâtissière"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Pour une texture bien souple et élastique, réaliser soigneusement l'émulsion sans incorporer d'air.",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 40,
      chef: null,
    },
  },

  {
    id: "ganache-confiseur-noir",
    nom: "Ganache confiseur chocolat noir",
    categorie: "ganaches",
    sous_categorie: "ganache_confiseur",
    description: "Ganache dense à haute teneur en chocolat pour la confiserie. Cristallisation longue, texture ferme et fondante, destinée aux bonbons et au cadrage.",
    masse_totale_g: 1450,
    ingredients: [
      { nom: "Lait UHT entier",         g: 272,  pct: 19, role: "eau"     },
      { nom: "Sucre inverti",           g: 79,   pct: 5,  role: "sucrant" },
      { nom: "Beurre doux",             g: 157,  pct: 11, role: "mg"      },
      { nom: "Sirop de glucose DE60",   g: 157,  pct: 11, role: "sucrant" },
      { nom: "Chocolat noir 67%",       g: 785,  pct: 54, role: "parfum"  },
    ],
    procede: [
      "Fondre la couverture et le beurre à 33°C.",
      "Dissoudre le sucre inverti et le glucose dans le lait chauffé à environ 45°C.",
      "Une fois ce mélange redescendu à 33°C, le verser en 3 fois sur le chocolat.",
      "Parfaire l'émulsion au mixeur plongeant puis cadrer immédiatement sur plaque chablonnée.",
      "Laisser cristalliser 24h à 15°C et 70% HR.",
      "Chablonner le dessus, détailler et enrober rapidement.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["ganache", "confiseur", "chocolat noir", "bonbon", "cadre", "confiserie"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Veiller à bien respecter les températures : faire bouillir le liquide n'est pas nécessaire et risque de modifier l'équilibre de la recette.",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 42,
      chef: null,
    },
  },
  {
    id: "ganache-flexi",
    nom: "Ganache flexible chocolat noir",
    categorie: "ganaches",
    sous_categorie: "ganache_flexible",
    description: "Ganache souple au chocolat noir maintenue flexible par la combinaison gélatine et agar-agar. Idéale en insert ou garniture de desserts à l'assiette.",
    masse_totale_g: 501,
    ingredients: [
      { nom: "Gélatine en poudre 200 bloom", g: 4,   pct: 1,    role: "gelifiant" },
      { nom: "Crème liquide 35%",            g: 300, pct: 60,   role: "mg"        },
      { nom: "Sucre inverti",                g: 35,  pct: 7,    role: "sucrant"   },
      { nom: "Sirop de glucose DE60",        g: 35,  pct: 7,    role: "sucrant"   },
      { nom: "Agar-agar",                    g: 2,   pct: 0.5,  role: "gelifiant" },
      { nom: "Couverture noir 64%",          g: 125, pct: 24.5, role: "parfum"    },
    ],
    procede: [
      "Hydrater la gélatine dans un peu d'eau froide.",
      "Porter la crème, le sucre inverti et le glucose à ébullition avec l'agar-agar.",
      "Hors du feu, ajouter la gélatine essorée, dissoudre.",
      "Verser en trois fois sur la couverture hachée, émulsionner au mixeur plongeant.",
      "Couler immédiatement dans le moule ou le cadre. Réfrigérer jusqu'à prise complète.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait"],
    tags: ["ganache", "flexible", "insert", "chocolat noir", "dessert à l'assiette"],
    parfum_principal: "chocolat noir",
    note_concepteur: null,
    source_interne: {
      fichier_pdf: "Bachour Simply Beautiful.pdf",
      page: 86,
      chef: null,
    },
  },
  {
    id: "ganache-montee-blond",
    nom: "Ganache montée chocolat blond",
    categorie: "ganaches",
    sous_categorie: "ganache_montee",
    description: "Ganache montée à base de couverture blonde, légère et lactée, aux notes de caramel biscuité.",
    masse_totale_g: 895,
    ingredients: [
      { nom: "Crème liquide 35% n°1",   g: 250, pct: 28, role: "mg"      },
      { nom: "Sucre inverti",           g: 25,  pct: 3,  role: "sucrant" },
      { nom: "Sirop de glucose DE60",   g: 25,  pct: 3,  role: "sucrant" },
      { nom: "Couverture blond",        g: 220, pct: 25, role: "parfum"  },
      { nom: "Crème liquide 35% n°2",  g: 375, pct: 41, role: "mg"      },
    ],
    procede: [
      "Porter la crème n°1, le sucre inverti et le glucose à ébullition.",
      "Verser en trois fois sur la couverture blonde hachée, émulsionner au mixeur plongeant.",
      "Ajouter la crème froide n°2, mixer à nouveau.",
      "Filmer au contact, réfrigérer 12h minimum.",
      "Monter au batteur à vitesse moyenne jusqu'à texture mousseuse et pochable.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 10, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait"],
    tags: ["ganache", "montée", "chocolat blond", "caramel", "pocher", "entremets"],
    parfum_principal: "chocolat blond",
    note_concepteur: null,
    source_interne: {
      fichier_pdf: "Bachour Simply Beautiful.pdf",
      page: 88,
      chef: null,
    },
  },
];
