export const RECETTES_GANACHES = [
  {
    id: "ganache-montee-noir",
    nom: "Ganache montée chocolat noir",
    categorie: "ganaches",
    sous_categorie: "ganache_montee",
    description: "Ganache émulsionnée à froid puis montée en chantilly chocolatée. Texture aérée, tenue optimale au pochage.",
    masse_totale_g: 509,
    ingredients: [
      { nom: "Crème liquide 35% n°1",  g: 130, pct: 26, role: "mg"      },
      { nom: "Lait UHT entier",         g: 60,  pct: 12, role: "eau"     },
      { nom: "Sucre inverti",           g: 12,  pct: 2,  role: "sucrant" },
      { nom: "Sirop de glucose DE60",   g: 12,  pct: 2,  role: "sucrant" },
      { nom: "Chocolat noir 67%",       g: 95,  pct: 19, role: "parfum"  },
      { nom: "Crème liquide 35% n°2",  g: 200, pct: 39, role: "mg"      },
    ],
    procede: [
      "Porter le lait, le sucre inverti et la crème n°1 à ébullition.",
      "Verser sur le chocolat fondu, émulsionner au mixeur plongeant.",
      "Ajouter la crème froide n°2, mixer à nouveau.",
      "Filmer au contact, refroidir rapidement à 4°C.",
      "Laisser cristalliser 12h minimum, idéalement 24h avant de monter.",
      "Monter au batteur à vitesse moyenne jusqu'à texture chantilly. Pocher immédiatement.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 10, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["ganache", "chocolat noir", "pocher", "entremets", "montée", "chantilly"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Pour une texture lisse et légère, monter lentement sans trop serrer et utiliser aussitôt. La recette est équilibrée pour minimiser le sucre ajouté tout en assurant tenue et saveur.",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 36,
      chef: null,
    },
  },

  {
    id: "ganache-patissiere-noir",
    nom: "Ganache pâtissière chocolat noir",
    categorie: "ganaches",
    sous_categorie: "ganache_patissiere",
    description: "Ganache crémeuse à base de crème et lait entier, texture souple et élastique. Idéale pour pocher ou garnir.",
    masse_totale_g: 600,
    ingredients: [
      { nom: "Crème liquide 35%",        g: 140, pct: 23, role: "mg"      },
      { nom: "Lait UHT entier",           g: 140, pct: 23, role: "eau"     },
      { nom: "Sucre inverti",             g: 60,  pct: 10, role: "sucrant" },
      { nom: "Sirop de glucose DE 38/40", g: 30,  pct: 5,  role: "sucrant" },
      { nom: "Chocolat noir 67%",         g: 230, pct: 39, role: "parfum"  },
    ],
    procede: [
      "Porter à ébullition la crème, le lait entier, le sucre inverti et le glucose.",
      "Verser en 3 fois sur le chocolat fondu.",
      "Parfaire l'émulsion au mixeur plongeant sans incorporer d'air.",
      "Filmer au contact. Conserver à 4°C.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 10, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["ganache", "chocolat noir", "pocher", "entremets", "pâtissière"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Pour une texture bien souple et élastique, réaliser soigneusement l'émulsion sans incorporer d'air.",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 40,
      chef: null,
    },
  },

  {
    id: "ganache-confiseur-noir",
    nom: "Ganache confiseur chocolat noir",
    categorie: "ganaches",
    sous_categorie: "ganache_confiseur",
    description: "Ganache dense à haute teneur en chocolat pour la confiserie. Cristallisation longue, texture ferme et fondante, destinée aux bonbons et au cadrage.",
    masse_totale_g: 1450,
    ingredients: [
      { nom: "Lait UHT entier",         g: 272,  pct: 19, role: "eau"     },
      { nom: "Sucre inverti",           g: 79,   pct: 5,  role: "sucrant" },
      { nom: "Beurre doux",             g: 157,  pct: 11, role: "mg"      },
      { nom: "Sirop de glucose DE60",   g: 157,  pct: 11, role: "sucrant" },
      { nom: "Chocolat noir 67%",       g: 785,  pct: 54, role: "parfum"  },
    ],
    procede: [
      "Fondre la couverture et le beurre à 33°C.",
      "Dissoudre le sucre inverti et le glucose dans le lait chauffé à environ 45°C.",
      "Une fois ce mélange redescendu à 33°C, le verser en 3 fois sur le chocolat.",
      "Parfaire l'émulsion au mixeur plongeant puis cadrer immédiatement sur plaque chablonnée.",
      "Laisser cristalliser 24h à 15°C et 70% HR.",
      "Chablonner le dessus, détailler et enrober rapidement.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["ganache", "confiseur", "chocolat noir", "bonbon", "cadre", "confiserie"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Veiller à bien respecter les températures : faire bouillir le liquide n'est pas nécessaire et risque de modifier l'équilibre de la recette.",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 42,
      chef: null,
    },
  },
  {
    id: "ganache-flexi",
    nom: "Ganache flexible chocolat noir",
    categorie: "ganaches",
    sous_categorie: "ganache_flexible",
    description: "Ganache souple au chocolat noir maintenue flexible par la combinaison gélatine et agar-agar. Idéale en insert ou garniture de desserts à l'assiette.",
    masse_totale_g: 501,
    ingredients: [
      { nom: "Gélatine en poudre 200 bloom", g: 4,   pct: 1,    role: "gelifiant" },
      { nom: "Crème liquide 35%",            g: 300, pct: 60,   role: "mg"        },
      { nom: "Sucre inverti",                g: 35,  pct: 7,    role: "sucrant"   },
      { nom: "Sirop de glucose DE60",        g: 35,  pct: 7,    role: "sucrant"   },
      { nom: "Agar-agar",                    g: 2,   pct: 0.5,  role: "gelifiant" },
      { nom: "Couverture noir 64%",          g: 125, pct: 24.5, role: "parfum"    },
    ],
    procede: [
      "Hydrater la gélatine dans un peu d'eau froide.",
      "Porter la crème, le sucre inverti et le glucose à ébullition avec l'agar-agar.",
      "Hors du feu, ajouter la gélatine essorée, dissoudre.",
      "Verser en trois fois sur la couverture hachée, émulsionner au mixeur plongeant.",
      "Couler immédiatement dans le moule ou le cadre. Réfrigérer jusqu'à prise complète.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait"],
    tags: ["ganache", "flexible", "insert", "chocolat noir", "dessert à l'assiette"],
    parfum_principal: "chocolat noir",
    note_concepteur: null,
    source_interne: {
      fichier_pdf: "Bachour Simply Beautiful.pdf",
      page: 86,
      chef: null,
    },
  },
  {
    id: "ganache-montee-blond",
    nom: "Ganache montée chocolat blond",
    categorie: "ganaches",
    sous_categorie: "ganache_montee",
    description: "Ganache montée à base de couverture blonde, légère et lactée, aux notes de caramel biscuité.",
    masse_totale_g: 895,
    ingredients: [
      { nom: "Crème liquide 35% n°1",   g: 250, pct: 28, role: "mg"      },
      { nom: "Sucre inverti",           g: 25,  pct: 3,  role: "sucrant" },
      { nom: "Sirop de glucose DE60",   g: 25,  pct: 3,  role: "sucrant" },
      { nom: "Couverture blond",        g: 220, pct: 25, role: "parfum"  },
      { nom: "Crème liquide 35% n°2",  g: 375, pct: 41, role: "mg"      },
    ],
    procede: [
      "Porter la crème n°1, le sucre inverti et le glucose à ébullition.",
      "Verser en trois fois sur la couverture blonde hachée, émulsionner au mixeur plongeant.",
      "Ajouter la crème froide n°2, mixer à nouveau.",
      "Filmer au contact, réfrigérer 12h minimum.",
      "Monter au batteur à vitesse moyenne jusqu'à texture mousseuse et pochable.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 10, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait"],
    tags: ["ganache", "montée", "chocolat blond", "caramel", "pocher", "entremets"],
    parfum_principal: "chocolat blond",
    note_concepteur: null,
    source_interne: {
      fichier_pdf: "Bachour Simply Beautiful.pdf",
      page: 88,
      chef: null,
    },
  },

  /* ── Karim Bourgi ────────────────────────────────────────────────────── */

  {
    id: "ganache-montee-noisette-kb",
    nom: "Ganache montée noisette",
    categorie: "ganaches",
    sous_categorie: "ganache_montee",
    description: "Ganache montée à la pâte de noisette et beurre de cacao. Cristallisée 12h, montée en texture semi-liquide légère. Pochée en dôme sur tartelette ou coulée en moule.",
    masse_totale_g: 822,
    ingredients: [
      { nom: "Crème liquide 35% (1)",  g: 255, pct: 31, role: "mg"      },
      { nom: "Sirop de glucose",       g:  25, pct:  3, role: "sucrant" },
      { nom: "Sucre inverti",          g:  25, pct:  3, role: "sucrant" },
      { nom: "Pâte de noisette 100%",  g: 130, pct: 16, role: "parfum"  },
      { nom: "Beurre de cacao",        g:  47, pct:  6, role: "mg"      },
      { nom: "Crème liquide 35% (2)",  g: 340, pct: 41, role: "mg"      },
    ],
    procede: [
      "Porter la crème (1), le glucose et le sucre inverti à 80°C.",
      "Fondre le beurre de cacao à 45°C, mélanger avec la pâte de noisette.",
      "Verser la crème chaude progressivement sur le mélange beurre-noisette. Mélanger à la spatule puis ajouter la crème froide (2). Mixer au plongeant.",
      "Filmer au contact. Réfrigérer 12h pour cristalliser.",
      "Monter au fouet jusqu'à texture aérée mais encore semi-liquide.",
      "Couler dans des moules Pavoflex PX4334S (d=7.4 cm, h=1.5 cm) et surgeler, ou pocher immédiatement.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 8, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "fruits_a_coque"],
    tags: ["ganache montée", "noisette", "dôme", "tartelette", "pochage"],
    parfum_principal: "noisette",
    note_concepteur: "Monter à texture 'semi-liquide aérée' — ne pas serrer comme une chantilly. La ganache montée trop ferme ne garde pas sa texture légère après décongélation.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 16,
      chef: "Karim Bourgi",
    },
  },

  {
    id: "ganache-gianduja-noisette-kb",
    nom: "Ganache gianduja-noisette",
    categorie: "ganaches",
    sous_categorie: "ganache_cremeux",
    description: "Ganache coulante au gianduja lait Valrhona 36% et pâte de noisette. Texture fondante et riche. Garnissage de fond de tartelette, se fige à température ambiante en 6h.",
    masse_totale_g: 507,
    ingredients: [
      { nom: "Crème liquide 35%",       g: 135, pct: 27, role: "mg"      },
      { nom: "Lait 3.2%",               g:  93, pct: 18, role: "eau"     },
      { nom: "Sel",                     g:   1, pct:  0, role: "assaisonm"},
      { nom: "Gianduja lait Valrhona 36%", g: 185, pct: 37, role: "parfum"},
      { nom: "Pâte de noisette 100%",   g:  93, pct: 18, role: "parfum"  },
    ],
    procede: [
      "Fondre le gianduja à 45°C. Incorporer la pâte de noisette et mélanger.",
      "Porter la crème, le lait et le sel à 80°C.",
      "Verser progressivement les liquides chauds sur le mélange gianduja-noisette. Mélanger à la spatule puis mixer au plongeant pour parfaire l'émulsion.",
      "Filmer au contact. Laisser reposer 6h à température ambiante avant utilisation.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 18, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "fruits_a_coque"],
    tags: ["ganache", "gianduja", "noisette", "tartelette", "garnissage", "coulant"],
    parfum_principal: "gianduja",
    note_concepteur: "Le gianduja Valrhona 36% (chocolat lait noisette) donne une ganache plus onctueuse qu'un chocolat ordinaire. À conserver à température ambiante pour la texture optimale.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 17,
      chef: "Karim Bourgi",
    },
  },

  {
    id: "namelaka-praline-pistache-kb",
    nom: "Namelaka praliné pistache",
    categorie: "ganaches",
    sous_categorie: "namelaka",
    description: "Namelaka au praliné pistache Valrhona : texture entre ganache et crémeux, très onctueuse et pochable après 8h de stabilisation. Garnissage de tartelettes pistache.",
    masse_totale_g: 320,
    ingredients: [
      { nom: "Lait 2.5%",                    g:  62, pct: 19, role: "eau"     },
      { nom: "Sirop de glucose",              g:   3, pct:  1, role: "sucrant" },
      { nom: "Masse gélatine 200 bloom",      g:   8, pct:  3, role: "gelifiant"},
      { nom: "Praliné pistache Valrhona",     g:  95, pct: 30, role: "parfum"  },
      { nom: "Beurre de cacao",               g:  27, pct:  9, role: "mg"      },
      { nom: "Crème liquide 35%",             g: 125, pct: 39, role: "mg"      },
    ],
    procede: [
      "Fondre le beurre de cacao à 45°C. Mélanger avec le praliné pistache dans un pichet.",
      "Chauffer le lait avec le glucose à 80°C. Ajouter la masse gélatine, remuer jusqu'à dissolution.",
      "Verser progressivement le lait gélifié sur le mélange praliné-beurre de cacao. Mélanger.",
      "Ajouter la crème froide. Mixer au plongeant pour parfaire l'émulsion.",
      "Réfrigérer minimum 8h avant de pocher.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 8, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "fruits_a_coque"],
    tags: ["namelaka", "pistache", "praliné", "tartelette", "pochage", "garnissage"],
    parfum_principal: "pistache",
    note_concepteur: "La masse gélatine se prépare : 1g gélatine 200 bloom + 6g eau froide. La namelaka doit être stabilisée minimum 8h — la gélatine est indispensable pour la tenue au pochage.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 27,
      chef: "Karim Bourgi",
    },
  },

  {
    id: "ganache-montee-pistache-kb",
    nom: "Ganache montée pistache",
    categorie: "ganaches",
    sous_categorie: "ganache_montee",
    description: "Ganache montée au chocolat blanc Opalys et pâte de pistache pure. Forte proportion de crème froide (50%) pour légèreté maximale. Utilisée en roulé ou dôme de finition.",
    masse_totale_g: 584,
    ingredients: [
      { nom: "Crème liquide 35% (1)",        g: 100, pct: 17, role: "mg"      },
      { nom: "Sirop de glucose",              g:  12, pct:  2, role: "sucrant" },
      { nom: "Sucre inverti",                 g:  12, pct:  2, role: "sucrant" },
      { nom: "Chocolat blanc Opalys 33%",     g: 115, pct: 20, role: "parfum"  },
      { nom: "Pâte de pistache pure Sosa",    g:  55, pct:  9, role: "parfum"  },
      { nom: "Crème liquide 35% (2)",         g: 290, pct: 50, role: "mg"      },
    ],
    procede: [
      "Fondre le chocolat blanc à 40°C.",
      "Chauffer la crème (1), le glucose et le sucre inverti à 80°C.",
      "Verser la crème chaude sur le chocolat fondu. Ajouter la crème froide (2) et la pâte de pistache. Mixer au plongeant.",
      "Filmer au contact. Réfrigérer 12h.",
      "Monter au fouet jusqu'à texture légère mais encore semi-liquide. Utiliser aussitôt.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 8, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "fruits_a_coque"],
    tags: ["ganache montée", "pistache", "chocolat blanc", "bûche roulée", "dôme"],
    parfum_principal: "pistache",
    note_concepteur: "Ne pas trop monter — texture 'semi-liquide aérée' pour conserver le brillant à la coupe. La pâte de pistache pure Sosa donne une couleur vert intense sans colorant.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 134,
      chef: "Karim Bourgi",
    },
  },

  {
    id: "ganache-caramel-chocolat-kb",
    nom: "Ganache caramel-chocolat lait (Tanariva)",
    categorie: "ganaches",
    sous_categorie: "ganache_caramel",
    description: "Ganache sur caramel à sec déglacé crème-glucose, émulsionnée au chocolat lait Tanariva 33%. Texture fondante et tendre. Pochée en tube sur biscuit pour travel cakes.",
    masse_totale_g: 828,
    ingredients: [
      { nom: "Sucre semoule",              g: 173, pct: 21, role: "sucrant"  },
      { nom: "Crème liquide 35%",          g: 340, pct: 41, role: "mg"      },
      { nom: "Sirop de glucose",           g:  23, pct:  3, role: "sucrant"  },
      { nom: "Beurre clarifié",            g:  63, pct:  8, role: "mg"      },
      { nom: "Chocolat lait Tanariva 33%", g: 227, pct: 27, role: "parfum"  },
      { nom: "Fleur de sel",               g:   2, pct:  0, role: "assaisonm"},
    ],
    procede: [
      "Chauffer la crème, le glucose et la fleur de sel à 80°C. Réserver à couvert.",
      "Caraméliser le sucre par ajouts successifs dans une casserole à feu moyen (ajouter la portion suivante seulement quand la précédente est fondue).",
      "Quand tout le sucre est fondu et ambré, incorporer le beurre clarifié fondu en filet. Mélanger.",
      "Ajouter la crème chaude et mélanger. Laisser redescendre à 75–80°C.",
      "Verser progressivement sur le chocolat fondu. Mixer au plongeant immédiatement.",
      "Transférer dans un contenant. Filmer au contact. Cristalliser 12h au réfrigérateur.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 12, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["ganache", "caramel", "chocolat lait", "Tanariva", "travel cake", "tube"],
    parfum_principal: "caramel",
    note_concepteur: "La technique du caramel par ajouts successifs garantit une fonte uniforme sans risque de brûlure. Mixer immédiatement après ajout du chocolat pour une émulsion parfaite.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 109,
      chef: "Karim Bourgi",
    },
  },

  {
    id: "ganache-caramel-bahibe-kb",
    nom: "Ganache caramel-Bahibe crémeuse",
    categorie: "ganaches",
    sous_categorie: "ganache_caramel",
    description: "Ganache sur caramel à sec déglacé, émulsionnée au chocolat lait Bahibe 46% (intense). Texture crémeuse, pochée en tube sur financier. Légèrement plus intense que la Tanariva.",
    masse_totale_g: 758,
    ingredients: [
      { nom: "Sucre semoule",              g: 165, pct: 22, role: "sucrant"  },
      { nom: "Beurre clarifié",            g:  60, pct:  8, role: "mg"      },
      { nom: "Crème liquide 35%",          g: 325, pct: 43, role: "mg"      },
      { nom: "Sirop de glucose",           g:  23, pct:  3, role: "sucrant"  },
      { nom: "Chocolat lait Bahibe 46%",   g: 183, pct: 24, role: "parfum"  },
      { nom: "Fleur de sel",               g:   2, pct:  0, role: "assaisonm"},
    ],
    procede: [
      "Chauffer la crème avec le glucose et la fleur de sel à 80°C. Réserver.",
      "Faire fondre le sucre par ajouts successifs dans une casserole à feu moyen jusqu'à caramel ambré.",
      "Incorporer le beurre clarifié fondu en filet, mélanger. Ajouter la crème chaude. Laisser redescendre à 75–80°C.",
      "Verser progressivement sur le chocolat fondu. Mixer au plongeant immédiatement pour parfaire l'émulsion.",
      "Transférer dans un contenant peu profond. Filmer au contact. Cristalliser 12h.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 12, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["ganache", "caramel", "chocolat lait", "Bahibe", "travel cake", "financier"],
    parfum_principal: "caramel",
    note_concepteur: "Bahibe 46% est plus intense et moins sucré que la Tanariva 33% — la ganache a plus de caractère et moins de douceur. Même technique caramel par ajouts successifs.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 163,
      chef: "Karim Bourgi",
    },
  },

  {
    id: "ganache-banane-molle-kb",
    nom: "Ganache banane molle",
    categorie: "ganaches",
    sous_categorie: "ganache_fruits",
    description: "Ganache express 2 ingrédients : purée de banane chauffée directement versée sur chocolat lait fondu. Sans crème ajoutée. Texture fondante, à utiliser aussitôt.",
    masse_totale_g: 200,
    ingredients: [
      { nom: "Banane (mixée)",             g: 110, pct: 55, role: "fruit"  },
      { nom: "Chocolat lait Tanariva 33%", g:  90, pct: 45, role: "parfum" },
    ],
    procede: [
      "Mixer la banane au blender et chauffer la purée à 70°C dans une casserole.",
      "Fondre le chocolat au micro-ondes.",
      "Verser la purée chaude sur le chocolat fondu. Mixer au plongeant sans incorporer d'air.",
      "Utiliser immédiatement pour garnir les tartelettes.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["ganache", "banane", "chocolat lait", "tartelette", "express", "garnissage"],
    parfum_principal: "banane",
    note_concepteur: "Recette volontairement simple — l'eau naturelle de la banane suffit à émulsionner avec le chocolat lait. À utiliser aussitôt avant que la ganache ne se fige.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 65,
      chef: "Karim Bourgi",
    },
  },

  /* ── Eddie Benghanem — Le Grand Cours de Pâtisserie ─────────────────── */

  {
    id: "ganache-entremets-noir-eb",
    nom: "Ganache entremets chocolat noir",
    categorie: "ganaches",
    sous_categorie: "ganache_entremets",
    description: "Ganache entremets chocolat noir 64% : crème+sucre inverti bouillis versés en 3 fois sur le chocolat. Simple, brillante. Pour garnissage de tartes, verrines, gâteaux.",
    masse_totale_g: 600,
    ingredients: [
      { nom: "Crème liquide 35%",  g: 300, pct: 50, role: "mg"     },
      { nom: "Sucre inverti",      g:  45, pct:  8, role: "sucrant"},
      { nom: "Chocolat noir 64%",  g: 260, pct: 43, role: "parfum" },
    ],
    procede: [
      "Porter à ébullition la crème et le sucre inverti.",
      "Verser en 3 fois sur le chocolat finement haché.",
      "Entre chaque ajout, mélanger délicatement à la maryse du centre vers l'extérieur.",
      "Mixer au plongeant sans incorporer d'air.",
      "Filmer au contact et réserver.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 18, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["ganache", "chocolat noir", "entremets", "tarte", "garnissage"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Bien respecter les températures et mixer la ganache pour parfaire l'émulsion. La ganache est liquide en sortie de réalisation — elle se fige en refroidissant.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 400,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "ganache-entremets-blanc-eb",
    nom: "Ganache entremets chocolat blanc",
    categorie: "ganaches",
    sous_categorie: "ganache_entremets",
    description: "Ganache entremets chocolat blanc : crème+sucre inverti sur chocolat blanc (forte proportion). Légère, lactée et sucrée. Pour tartes blanches, verrines.",
    masse_totale_g: 900,
    ingredients: [
      { nom: "Crème liquide 35%",  g: 300, pct: 33, role: "mg"     },
      { nom: "Sucre inverti",      g:  50, pct:  6, role: "sucrant"},
      { nom: "Chocolat blanc 35%", g: 575, pct: 64, role: "parfum" },
    ],
    procede: [
      "Porter à ébullition la crème et le sucre inverti.",
      "Fondre le chocolat blanc finement haché au bain-marie.",
      "Verser la crème bouillante sur le chocolat en 3 fois. Mélanger entre chaque ajout.",
      "Mixer. Filmer au contact. Réserver.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 18, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["ganache", "chocolat blanc", "entremets", "tarte", "garnissage"],
    parfum_principal: "chocolat blanc",
    note_concepteur: "La forte proportion de chocolat blanc (64%) donne une ganache ferme à froid. Peut être parfumée (framboise, citron) en ajoutant une pulpe après émulsification.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 400,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "ganache-montee-noir-manjari-eb",
    nom: "Ganache montée chocolat noir Manjari",
    categorie: "ganaches",
    sous_categorie: "ganache_montee",
    description: "Ganache montée chocolat noir Manjari (35% cacao) sur base crème+glucose+sucre inverti. Cristallisation 24h, montée le lendemain. Pour entremets, décors pochés.",
    masse_totale_g: 900,
    ingredients: [
      { nom: "Crème liquide 35%",           g: 675, pct: 75, role: "mg"     },
      { nom: "Sucre inverti",               g:  25, pct:  3, role: "sucrant"},
      { nom: "Sirop de glucose",            g:  25, pct:  3, role: "sucrant"},
      { nom: "Chocolat noir Manjari 64%",   g: 200, pct: 22, role: "parfum" },
    ],
    procede: [
      "Porter à ébullition 22.5cl de crème avec le sucre inverti et le glucose.",
      "Verser sur le chocolat haché en 3 fois. Mélanger pour obtenir une ganache lisse et brillante.",
      "Ajouter le reste de crème liquide froide lorsque la ganache est à 40°C. Incorporer à la maryse.",
      "Filmer au contact. Réserver 24h au frais.",
      "Monter au robot avec le fouet à vitesse moyenne jusqu'à consistance mousseuse.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 10, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["ganache montée", "Manjari", "chocolat noir", "entremets", "pocher"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Le Manjari Valrhona est un chocolat noir fruité (notes de framboises). La crème froide est ajoutée après l'émulsion principale pour une texture plus légère. Stabilisation 24h obligatoire.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 400,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "ganache-bonbons-noir-eb",
    nom: "Ganache bonbons chocolat noir",
    categorie: "ganaches",
    sous_categorie: "ganache_confiseur",
    description: "Ganache confiseur chocolat noir 70% Guanaja pour bonbons moulés ou cadrés. Crème+sucre inverti, beurre incorporé en fin. Cristallisation 24–48h en cadre Inox.",
    masse_totale_g: 1200,
    ingredients: [
      { nom: "Crème liquide 35%",  g: 250, pct: 21, role: "mg"     },
      { nom: "Sucre inverti",      g:  45, pct:  4, role: "sucrant"},
      { nom: "Chocolat 70% Guanaja",g: 335, pct: 28, role: "parfum"},
      { nom: "Beurre mou",         g:  75, pct:  6, role: "mg"     },
    ],
    procede: [
      "Porter à ébullition crème et sucre inverti.",
      "Verser en 3 fois sur le chocolat finement haché. Mélanger du centre vers l'extérieur.",
      "Incorporer le beurre mou coupé en petits morceaux.",
      "Mixer au plongeant sans incorporer d'air.",
      "Verser dans un cadre à ganache 8×27 cm. Cristalliser 24–48h au frais.",
      "Couper, tremper dans la couverture tempérée.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["ganache", "bonbons", "confiserie", "Guanaja", "cadre", "cristallisation"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Le Guanaja Valrhona à 70% est intense et légèrement amer — ganache de caractère. Pour bonbons moulés (demi-sphères) ou cadrés. Le beurre apporte fondant et brillance après découpe.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 538,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "ganache-bonbons-vanille-eb",
    nom: "Ganache bonbons vanille (chocolat blanc Ivoire)",
    categorie: "ganaches",
    sous_categorie: "ganache_confiseur",
    description: "Ganache bonbons chocolat blanc Ivoire infusée à la vanille Bourbon. Crème+sucre inverti+vanille, forte proportion chocolat blanc. Pour bonbons moulés ou trempés.",
    masse_totale_g: 1040,
    ingredients: [
      { nom: "Crème liquide 35%",   g: 250, pct: 24, role: "mg"     },
      { nom: "Sucre inverti",       g:  65, pct:  6, role: "sucrant"},
      { nom: "Chocolat blanc Ivoire",g: 670, pct: 64, role: "parfum"},
      { nom: "Beurre mou",          g: 110, pct: 11, role: "mg"     },
    ],
    procede: [
      "Porter à ébullition la crème, le sucre inverti et les gousses de vanille fendues et grattées.",
      "Hacher finement le chocolat. Retirer les gousses de vanille.",
      "Verser la crème chaude sur le chocolat en 3 fois. Mélanger pour obtenir une émulsion brillante.",
      "Incorporer le beurre mou. Mixer au plongeant.",
      "Verser dans un cadre. Cristalliser 24–48h au frais.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 18, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["ganache", "vanille", "chocolat blanc", "bonbons", "Ivoire", "confiserie"],
    parfum_principal: "vanille",
    note_concepteur: "2 gousses de vanille Bourbon (non incluses). L'Ivoire Valrhona est le chocolat blanc de référence pour les ganaches — texture stable et saveur lactée nette. Forte proportion de beurre pour le fondant.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 539,
      chef: "Eddie Benghanem",
    },
  },
];
