export const RECETTES_GLACES_SORBETS = [
  {
    id: "glace-chocolat-noir",
    nom: "Crème glacée chocolat noir",
    categorie: "glaces_sorbets",
    sous_categorie: "glace_turbinee",
    description: "Crème glacée au chocolat noir pasteurisée et turbinée. Matières sèches équilibrées pour une texture onctueuse et une saveur intense.",
    masse_totale_g: 1625,
    ingredients: [
      { nom: "Lait UHT entier",       g: 1036, pct: 64,  role: "eau"        },
      { nom: "Crème liquide 35%",     g: 110,  pct: 7,   role: "mg"         },
      { nom: "Poudre de lait 0%",     g: 45,   pct: 3,   role: "structure"  },
      { nom: "Saccharose",            g: 100,  pct: 6,   role: "sucrant"    },
      { nom: "Dextrose",              g: 90,   pct: 5,   role: "sucrant"    },
      { nom: "Sucre inverti",         g: 100,  pct: 6,   role: "sucrant"    },
      { nom: "Stabilisateur à glace", g: 10,   pct: 0.5, role: "structure"  },
      { nom: "Monostéarates",         g: 4,    pct: 0.5, role: "emulsifiant"},
      { nom: "Chocolat noir 67%",     g: 130,  pct: 8,   role: "parfum"     },
    ],
    procede: [
      "Mélanger le lait et la poudre de lait.",
      "À 30°C ajouter les sucres (saccharose, dextrose, sucre inverti).",
      "À 35°C ajouter la crème.",
      "À 45°C ajouter les stabilisateurs, les monostéarates et le chocolat.",
      "Porter à 85°C en remuant constamment (pasteurisation).",
      "Filtrer et mixer. Filmer au contact, refroidir rapidement à 4°C.",
      "Laisser maturer minimum 12h à 4°C, mixer à nouveau puis turbiner.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: -14, conservation_c: -18 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["glace", "turbiner", "chocolat noir", "dessert glacé", "pasteurisation"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Afin de développer les arômes et optimiser la consistance finale, laisser maturer au minimum 6h à 4°C avant de turbiner.",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 52,
      chef: null,
    },
  },
  {
    id: "semifreddo-cerise",
    nom: "Semifreddo cerise",
    categorie: "glaces_sorbets",
    sous_categorie: "semifreddo",
    description: "Semifreddo à la cerise, texture aérée non turbinée. Parfum fruité intense, servi en tranche ou en verrine.",
    masse_totale_g: 1579,
    ingredients: [
      { nom: "Œufs entiers",    g: 220, pct: 14, role: "liant"   },
      { nom: "Sucre semoule",   g: 226, pct: 14, role: "sucrant" },
      { nom: "Purée de cerise", g: 680, pct: 43, role: "fruit"   },
      { nom: "Crème montée",    g: 453, pct: 29, role: "mg"      },
    ],
    procede: [
      "Monter les œufs et le sucre au bain-marie jusqu'à 55°C, puis fouetter hors du feu jusqu'à refroidissement complet (pâte à bombe).",
      "Incorporer la purée de cerise à température ambiante.",
      "Incorporer délicatement la crème montée en deux fois.",
      "Couler en moule ou cadre. Surgeler minimum 4h.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: -6, conservation_c: -18 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["oeuf", "lait"],
    tags: ["semifreddo", "cerise", "glacé", "non turbiné", "dessert à l'assiette"],
    parfum_principal: "cerise",
    note_concepteur: null,
    source_interne: {
      fichier_pdf: "Bachour Simply Beautiful.pdf",
      page: 106,
      chef: null,
    },
  },
  {
    id: "semifreddo-coco",
    nom: "Semifreddo coco",
    categorie: "glaces_sorbets",
    sous_categorie: "semifreddo",
    description: "Semifreddo à la noix de coco et couverture blanche, léger et exotique, relevé d'une pointe de rhum.",
    masse_totale_g: 580,
    ingredients: [
      { nom: "Lait de coco",     g: 200, pct: 35, role: "fruit"  },
      { nom: "Couverture blanc", g: 160, pct: 28, role: "parfum" },
      { nom: "Rhum coco",        g: 20,  pct: 3,  role: "parfum" },
      { nom: "Crème montée",     g: 200, pct: 34, role: "mg"     },
    ],
    procede: [
      "Chauffer le lait de coco, verser sur la couverture blanche hachée, émulsionner.",
      "Ajouter le rhum, laisser refroidir à 30°C.",
      "Incorporer délicatement la crème montée.",
      "Couler en moule. Surgeler minimum 4h.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: -6, conservation_c: -18 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait"],
    tags: ["semifreddo", "coco", "rhum", "glacé", "non turbiné", "exotique"],
    parfum_principal: "coco",
    note_concepteur: null,
    source_interne: {
      fichier_pdf: "Bachour Simply Beautiful.pdf",
      page: 108,
      chef: null,
    },
  },
  {
    id: "semifreddo-praline",
    nom: "Semifreddo praliné",
    categorie: "glaces_sorbets",
    sous_categorie: "semifreddo",
    description: "Semifreddo praliné, aérien et gourmand, à base de meringue et crème montée.",
    masse_totale_g: 776,
    ingredients: [
      { nom: "Crème liquide 35% (base)", g: 96,  pct: 12, role: "mg"      },
      { nom: "Pâte de praliné",          g: 275, pct: 36, role: "parfum"  },
      { nom: "Blancs d'œufs",           g: 70,  pct: 9,  role: "aeration" },
      { nom: "Sucre semoule",            g: 60,  pct: 7,  role: "sucrant"  },
      { nom: "Crème montée",             g: 275, pct: 36, role: "mg"      },
    ],
    procede: [
      "Tiédir légèrement la crème base avec la pâte de praliné, bien mélanger.",
      "Monter les blancs en meringue avec le sucre.",
      "Incorporer la meringue à l'appareil praliné.",
      "Incorporer délicatement la crème montée.",
      "Couler en moule. Surgeler minimum 4h.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: -6, conservation_c: -18 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["oeuf", "lait", "fruits_a_coque"],
    tags: ["semifreddo", "praliné", "glacé", "non turbiné", "meringue"],
    parfum_principal: "praliné",
    note_concepteur: null,
    source_interne: {
      fichier_pdf: "Bachour Simply Beautiful.pdf",
      page: 110,
      chef: null,
    },
  },
];
