export const RECETTES_GLACAGES = [
  {
    id: "glacage-miroir-noir",
    nom: "Glaçage miroir chocolat noir",
    categorie: "glacages",
    sous_categorie: "glacage_miroir",
    description: "Glaçage brillant au chocolat sur base glucose-sucre. Application à 25-30°C sur entremets surgelé.",
    masse_totale_g: 1005,
    ingredients: [
      { nom: "Eau",                        g: 110,  pct: 11,   role: "eau"       },
      { nom: "Sucre cristal",              g: 215,  pct: 21,   role: "sucrant"   },
      { nom: "Sirop de glucose DE40",      g: 215,  pct: 22,   role: "sucrant"   },
      { nom: "Lait concentré non sucré",   g: 145,  pct: 14,   role: "mg"        },
      { nom: "Gélatine 200 bloom",         g: 14.5, pct: 1.5,  role: "gelifiant" },
      { nom: "Eau gélatine",               g: 72.5, pct: 7,    role: "eau"       },
      { nom: "Poudre de cacao",            g: 60,   pct: 6,    role: "parfum"    },
      { nom: "Chocolat 58%",               g: 173,  pct: 17.5, role: "parfum"    },
    ],
    procede: [
      "Hydrater la gélatine dans 5× son poids en eau froide (quantités déjà indiquées).",
      "Réaliser un sirop avec l'eau, le sucre, le glucose et le lait concentré. Cuire à 103°C.",
      "Stopper la cuisson avec la masse gélatine et la poudre de cacao.",
      "Une fois la gélatine totalement fondue, filtrer et verser sur le chocolat.",
      "Mixer sans incorporer d'air.",
      "Utiliser entre 25 et 30°C. Conserver à 4°C.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["glaçage", "miroir", "chocolat noir", "entremets", "finition"],
    parfum_principal: "chocolat noir",
    note_concepteur: "En cas de bulles d'air, filtrer le glaçage à l'aide d'une étamine.",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 60,
      chef: null,
    },
  },

  /* ── Karim Bourgi ────────────────────────────────────────────────────── */

  {
    id: "glacage-neutre-kb",
    nom: "Glaçage neutre à la pectine",
    categorie: "glacages",
    sous_categorie: "glacage_neutre",
    description: "Glaçage neutre transparent à la pectine NH. Brillant intense, texture gel souple. Base polyvalente pour glacer fruits ou dômes, ou incorporée dans d'autres glaçages.",
    masse_totale_g: 306,
    ingredients: [
      { nom: "Eau",               g: 135,  pct: 44, role: "eau"      },
      { nom: "Sucre semoule (1)", g: 114,  pct: 37, role: "sucrant"  },
      { nom: "Sucre semoule (2)", g:  18,  pct:  6, role: "sucrant"  },
      { nom: "Pectine NH",        g:   6,  pct:  2, role: "gelifiant"},
      { nom: "Sirop de glucose",  g:  33,  pct: 11, role: "sucrant"  },
      { nom: "Acide citrique",    g: 0.3,  pct:  0, role: "acidite"  },
    ],
    procede: [
      "Mélanger l'eau, le glucose et le sucre (1) dans une casserole. Chauffer à 30°C.",
      "Mélanger la pectine NH avec le sucre (2) pour éviter les grumeaux.",
      "Verser le mélange pectine-sucre (2) en pluie dans la casserole en fouettant.",
      "Porter à ébullition, laisser mijoter à feu moyen 3 min.",
      "Hors du feu, ajouter l'acide citrique (ou 3g de jus de citron). Mélanger.",
      "Chinoiser dans un contenant propre. Réfrigérer au minimum 6h pour stabiliser.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["glaçage neutre", "pectine NH", "transparent", "brillant", "base"],
    parfum_principal: null,
    note_concepteur: "L'acide citrique active la pectine NH. En l'absence d'acide citrique, utiliser 3g de jus de citron. Ce glaçage entre dans la composition du glaçage praliné et du gel passion.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 11,
      chef: "Karim Bourgi",
    },
  },

  {
    id: "glacage-praline-noisette-kb",
    nom: "Glaçage praliné noisette",
    categorie: "glacages",
    sous_categorie: "glacage_praline",
    description: "Glaçage gourmand au praliné noisette artisanal, crème et glaçage neutre. Appliqué chaud (35°C) sur dômes de ganache montée surgelés. Couleur et texture proches d'une pralinoise.",
    masse_totale_g: 660,
    ingredients: [
      { nom: "Praliné noisette artisanal",  g: 200, pct: 30, role: "parfum"  },
      { nom: "Crème liquide 35%",           g: 100, pct: 15, role: "mg"      },
      { nom: "Glaçage neutre",              g: 300, pct: 46, role: "liant"   },
      { nom: "Eau",                         g:  30, pct:  5, role: "eau"     },
      { nom: "Masse gélatine 200 bloom",    g:  30, pct:  5, role: "gelifiant"},
    ],
    procede: [
      "Faire fondre le glaçage neutre avec l'eau à 80°C.",
      "Chauffer la crème et incorporer la masse gélatine. Mélanger jusqu'à dissolution.",
      "Incorporer le praliné noisette à la crème gélatinée.",
      "Verser le mélange glaçage neutre-eau sur la préparation praliné-crème. Mixer au plongeant jusqu'à texture lisse.",
      "Filmer au contact. Réfrigérer jusqu'à utilisation.",
      "Réchauffer à 35°C et remixer avant d'utiliser.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "fruits_a_coque"],
    tags: ["glaçage", "praliné", "noisette", "tartlette", "dôme", "finition"],
    parfum_principal: "noisette",
    note_concepteur: "La masse gélatine se prépare : 1g gélatine 200 bloom + 6g eau froide. Utiliser entre 35°C et 40°C — trop froid le glaçage fige, trop chaud il coule.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 12,
      chef: "Karim Bourgi",
    },
  },

  {
    id: "glacage-chocolat-eclair-kb",
    nom: "Glaçage chocolat pour éclairs",
    categorie: "glacages",
    sous_categorie: "glacage_chocolat",
    description: "Glaçage chocolat brillant sur base sirop-condensé, incorporant glaçage neutre pour souplesse et tenue. Appliqué par trempage à 25–26°C. Finition nette sans bullage.",
    masse_totale_g: 1207,
    ingredients: [
      { nom: "Eau (1)",                    g: 112, pct:  9, role: "eau"     },
      { nom: "Sucre semoule",              g: 150, pct: 13, role: "sucrant" },
      { nom: "Sirop de glucose",           g: 188, pct: 15, role: "sucrant" },
      { nom: "Lait concentré sucré",       g: 150, pct: 13, role: "mg"     },
      { nom: "Chocolat Caraïbe 66%",       g: 240, pct: 20, role: "parfum" },
      { nom: "Beurre de cacao",            g:  37, pct:  3, role: "mg"     },
      { nom: "Glaçage neutre",             g: 300, pct: 25, role: "liant"  },
      { nom: "Eau (2)",                    g:  30, pct:  2, role: "eau"    },
    ],
    procede: [
      "Porter l'eau (1), le sucre et le glucose à 103°C.",
      "Incorporer le lait concentré sucré au sirop, mélanger.",
      "Verser sur le chocolat fondu et le beurre de cacao. Mélanger à la spatule.",
      "Porter le glaçage neutre avec l'eau (2) à ébullition séparément.",
      "Verser le glaçage neutre sur le mélange chocolat. Mixer au plongeant pour parfaire l'émulsion.",
      "Filmer au contact. Réfrigérer 12h minimum.",
      "Réchauffer à 25–26°C. Remixer avant de tremper les éclairs.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["glaçage", "chocolat", "éclair", "choux", "trempage", "brillant"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Application par trempage : tenir l'éclair par le bas, plonger le dessus dans le glaçage, remonter et ôter l'excédent avec le doigt. Éviter de remixer après réchauffage pour ne pas incorporer d'air.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 83,
      chef: "Karim Bourgi",
    },
  },

  {
    id: "glacage-chocolat-cacao-kb",
    nom: "Glaçage chocolat au cacao (entremets)",
    categorie: "glacages",
    sous_categorie: "glacage_miroir",
    description: "Glaçage chocolat miroir à base de cacao en poudre, glucose et glaçage neutre. Coulé à 27°C sur entremets surgelés. Texture épaisse, tenue parfaite, brillance intense.",
    masse_totale_g: 1210,
    ingredients: [
      { nom: "Crème liquide 35%",       g: 250, pct: 21, role: "mg"      },
      { nom: "Poudre de cacao",         g: 100, pct:  8, role: "parfum"  },
      { nom: "Eau",                     g: 130, pct: 11, role: "eau"     },
      { nom: "Sucre semoule",           g: 350, pct: 29, role: "sucrant" },
      { nom: "Sirop de glucose",        g: 120, pct: 10, role: "sucrant" },
      { nom: "Glaçage neutre",          g: 100, pct:  8, role: "liant"   },
      { nom: "Masse gélatine 200 bloom",g: 160, pct: 13, role: "gelifiant"},
    ],
    procede: [
      "Mélanger la crème et la poudre de cacao dans une casserole. Chauffer à 40°C en fouettant.",
      "Porter l'eau, le sucre et le glucose à 110°C dans une casserole séparée.",
      "Réunir le sirop, le mélange crème-cacao, le glaçage neutre et la masse gélatine dans un pichet. Mixer au plongeant jusqu'à texture homogène.",
      "Filmer au contact. Laisser stabiliser au réfrigérateur.",
      "Utiliser à 27°C.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["glaçage", "chocolat", "cacao", "miroir", "entremets", "coulage"],
    parfum_principal: "cacao",
    note_concepteur: "La masse gélatine (25g gélatine + 150g eau ≈ 175g, ici 160g) assure la tenue. Couler sur entremet surgelé et laisser drainer sur grille avant de transférer au réfrigérateur.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 97,
      chef: "Karim Bourgi",
    },
  },

  {
    id: "glacage-pistache-kb",
    nom: "Glaçage pistache (icing)",
    categorie: "glacages",
    sous_categorie: "glacage_chocolat",
    description: "Glaçage coulant à base de chocolat blanc Opalys, pâte et praliné pistache, huile de pépin de raisin. Appliqué par nappage sur travel cakes surgelés. Couleur verte naturelle.",
    masse_totale_g: 1260,
    ingredients: [
      { nom: "Chocolat blanc Opalys 33%",  g: 800, pct: 63, role: "liant"  },
      { nom: "Huile de pépin de raisin",   g:  60, pct:  5, role: "mg"     },
      { nom: "Pâte de pistache Sosa",      g: 200, pct: 16, role: "parfum" },
      { nom: "Praliné pistache Valrhona",  g: 200, pct: 16, role: "parfum" },
    ],
    procede: [
      "Fondre le chocolat à 45°C.",
      "Incorporer l'huile, la pâte de pistache et le praliné pistache.",
      "Mixer au plongeant jusqu'à texture lisse et homogène.",
      "Utiliser à 35–38°C.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "fruits_a_coque"],
    tags: ["glaçage", "pistache", "travel cake", "nappage", "vert", "coulant"],
    parfum_principal: "pistache",
    note_concepteur: "L'huile de pépin de raisin (neutre en goût) assure la fluidité et évite la fissuration à froid. Ce glaçage ne cristallise pas — il reste souple une fois pris.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 46,
      chef: "Karim Bourgi",
    },
  },

  {
    id: "glacage-miroir-neutre-kb",
    nom: "Glaçage miroir neutre (Absolu Cristal)",
    categorie: "glacages",
    sous_categorie: "glacage_neutre",
    description: "Glaçage miroir transparent ultra-brillant dilué à l'eau. Appliqué chaud sur dômes surgelés. Couvre et scelle les inserts surgelés pour les déposer sur la tartelette.",
    masse_totale_g: 250,
    ingredients: [
      { nom: "Glaçage neutre Valrhona Absolu Cristal", g: 210, pct: 84, role: "liant" },
      { nom: "Eau",                                     g:  40, pct: 16, role: "eau"   },
    ],
    procede: [
      "Mélanger le glaçage neutre et l'eau dans une casserole.",
      "Porter à ébullition.",
      "Chinoiser. Utiliser immédiatement à chaud pour tremper les inserts ou dômes surgelés.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["glaçage miroir", "neutre", "transparent", "brillant", "insert", "trempage"],
    parfum_principal: null,
    note_concepteur: "Le glaçage neutre maison (glacage-neutre-kb) peut remplacer l'Absolu Cristal à quantités équivalentes. Utiliser chaud pour un dépôt fin et transparent.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 138,
      chef: "Karim Bourgi",
    },
  },

  {
    id: "glacage-chocolat-lait-eskimo-kb",
    nom: "Glaçage eskimo chocolat lait",
    categorie: "glacages",
    sous_categorie: "glacage_enrobage",
    description: "Enrobage type eskimo au chocolat lait Bahibe dilué à l'huile. Cristallise rapidement au contact du produit surgelé. Application par trempage ou coulage.",
    masse_totale_g: 880,
    ingredients: [
      { nom: "Chocolat lait Bahibe 46%",  g: 800, pct: 91, role: "liant"  },
      { nom: "Huile de pépin de raisin",  g:  80, pct:  9, role: "mg"     },
    ],
    procede: [
      "Fondre le chocolat à 40°C.",
      "Incorporer l'huile. Mélanger et mixer au plongeant.",
      "Utiliser à 35–38°C.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["enrobage", "chocolat lait", "eskimo", "travel cake", "cristallisation rapide"],
    parfum_principal: "chocolat lait",
    note_concepteur: "L'huile fluidifie l'enrobage et prévient la fissuration à la découpe. À base de Bahibe 46% (chocolat lait intense Valrhona). Application sur travel cakes surgelés.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 167,
      chef: "Karim Bourgi",
    },
  },

  {
    id: "glacage-gomme-arabique-kb",
    nom: "Glaçage gomme arabique (babka)",
    categorie: "glacages",
    sous_categorie: "glacage_nappage",
    description: "Nappage brillant à la gomme arabique, glucose et sucre brun. Appliqué au pinceau sur la babka chaude. Donne un aspect laqué et conserve le moelleux.",
    masse_totale_g: 147,
    ingredients: [
      { nom: "Eau",              g: 56, pct: 38, role: "eau"      },
      { nom: "Sucre brun",       g: 56, pct: 38, role: "sucrant"  },
      { nom: "Sirop de glucose", g: 25, pct: 17, role: "sucrant"  },
      { nom: "Gomme arabique",   g: 10, pct:  7, role: "liant"    },
    ],
    procede: [
      "Mélanger eau, sucre brun, glucose et gomme arabique dans une casserole.",
      "Chauffer à feu moyen en remuant jusqu'à dissolution complète de tous les ingrédients.",
      "Verser dans un pichet, mixer au plongeant jusqu'à texture lisse.",
      "Passer au chinois dans un bol propre. Laisser refroidir.",
      "Appliquer au pinceau sur la babka encore chaude à la sortie du four.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["nappage", "gomme arabique", "babka", "brillant", "laqué", "viennoiserie"],
    parfum_principal: null,
    note_concepteur: "Appliquer impérativement à chaud sur la viennoiserie encore chaude — le nappage pénètre légèrement et scelle la surface sans alourdir.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 53,
      chef: "Karim Bourgi",
    },
  },

  /* ── Eddie Benghanem — Le Grand Cours de Pâtisserie ─────────────────── */

  {
    id: "glacage-blanc-entremets-eb",
    nom: "Glaçage blanc entremets",
    categorie: "glacages",
    sous_categorie: "glacage_blanc",
    description: "Glaçage blanc pour entremets : sirop sucre+glucose+eau cuit à 130°C + crème + chocolat blanc + gélatine + pectine X58. Application à 35°C. Conservation 1 semaine au réfrigérateur.",
    masse_totale_g: 368,
    ingredients: [
      { nom: "Gélatine feuilles",  g:   3, pct:  1, role: "gelifiant"},
      { nom: "Eau (sirop)",        g:  50, pct: 14, role: "eau"      },
      { nom: "Sucre semoule",      g:  65, pct: 18, role: "sucrant"  },
      { nom: "Sirop de glucose",   g:  40, pct: 11, role: "sucrant"  },
      { nom: "Crème liquide",      g:  80, pct: 22, role: "mg"       },
      { nom: "Chocolat blanc 35%", g:  80, pct: 22, role: "parfum"   },
      { nom: "Pectine X58",        g:   1, pct:  0, role: "gelifiant"},
      { nom: "Sucre semoule (pectine)",g: 5, pct: 1, role: "sucrant" },
      { nom: "Eau (pectine)",      g:  25, pct:  7, role: "eau"      },
    ],
    procede: [
      "Hydrater la gélatine dans l'eau froide. Essorez.",
      "Mélanger les 2.5cl d'eau, les 5g de sucre et la pectine. Porter à ébullition.",
      "Cuire crème à ébullition, verser sur chocolat blanc haché → ganache.",
      "Cuire les 5cl d'eau + 60g sucre + glucose à 130°C.",
      "Hors du feu, verser la ganache, la gélatine et le mélange pectine.",
      "Mixer au plongeant. Utiliser à 35–40°C.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole — sirop 130°C" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["glaçage blanc", "entremets", "brillant", "pectine X58"],
    parfum_principal: null,
    note_concepteur: "Ce glaçage s'utilise à 35°C. Se conserve 1 semaine au réfrigérateur. Peut être coloré avec des colorants liposolubles. La pectine X58 est indispensable pour la tenue à la découpe.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 558,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "glacage-fruits-choux-eb",
    nom: "Glaçage aux fruits pour pâte à choux",
    categorie: "glacages",
    sous_categorie: "glacage_fruits",
    description: "Glaçage abricot-mangue à la pectine NH pour pâte à choux. Étalé sur plaque et congelé, découpé puis posé sur les choux. Fruité, brillant, translucide.",
    masse_totale_g: 420,
    ingredients: [
      { nom: "Purée d'abricots",  g: 155, pct: 37, role: "fruit"    },
      { nom: "Purée de mangue",   g: 155, pct: 37, role: "fruit"    },
      { nom: "Sirop de glucose",  g:  35, pct:  8, role: "sucrant"  },
      { nom: "Sucre semoule",     g:  55, pct: 13, role: "sucrant"  },
      { nom: "Pectine NH",        g:   8, pct:  2, role: "gelifiant"},
      { nom: "Jus de citron vert",g:  10, pct:  2, role: "acidite"  },
    ],
    procede: [
      "Chauffer les purées et le glucose à 40°C.",
      "Mélanger sucre et pectine. Verser dans les purées chaudes. Porter à ébullition 2 min.",
      "Hors du feu, ajouter le jus de citron. Mixer.",
      "Couler sur une plaque avec feuille guitare. Surgeler 35 min.",
      "Découper aux dimensions des choux et poser surgelé sur les choux avant service.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole" },
    temperatures: { service_c: null, conservation_c: -18 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["glaçage", "fruits", "abricot", "mangue", "choux", "surgelé", "décor"],
    parfum_principal: "abricot",
    note_concepteur: "Ce glaçage se pose surgelé sur les choux — il décongèle rapidement et adhère parfaitement. Alternative aux fondants classiques pour une note fruitée et translucide. Congeler 35 min minimum avant utilisation.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 558,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "glacage-eau-eb",
    nom: "Glaçage à l'eau (glace royale légère)",
    categorie: "glacages",
    sous_categorie: "glacage_eau",
    description: "Glaçage à l'eau : sucre glace + eau chauffé à 45°C. Fluide, transparent, séchage rapide. Pour pains d'épices, sablés, croissants aux amandes, petits fours.",
    masse_totale_g: 347,
    ingredients: [
      { nom: "Sucre glace", g: 280, pct: 81, role: "sucrant"},
      { nom: "Eau",         g:  70, pct: 20, role: "eau"   },
    ],
    procede: [
      "Mélanger le sucre glace et l'eau.",
      "Chauffer doucement à 45°C dans une casserole.",
      "Utiliser aussitôt pour glacer.",
      "Pour fixer : enfourner les pièces quelques secondes à 220°C.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole — chauffage doux 45°C" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["glaçage eau", "sucre glace", "pain d'épices", "sablé", "simple"],
    parfum_principal: null,
    note_concepteur: "Ce glaçage peut aussi être utilisé pour des croissants aux amandes, des petits fours secs et des sablés. Le chauffage léger à 45°C rend le glaçage fluide et lisse.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 558,
      chef: "Eddie Benghanem",
    },
  },
];
