export const RECETTES_GLACAGES = [
  {
    id: "glacage-miroir-noir",
    nom: "Glaçage miroir chocolat noir",
    categorie: "glacages",
    sous_categorie: "glacage_miroir",
    description: "Glaçage brillant au chocolat sur base glucose-sucre. Application à 25-30°C sur entremets surgelé.",
    masse_totale_g: 1005,
    ingredients: [
      { nom: "Eau",                        g: 110,  pct: 11,   role: "eau"       },
      { nom: "Sucre cristal",              g: 215,  pct: 21,   role: "sucrant"   },
      { nom: "Sirop de glucose DE40",      g: 215,  pct: 22,   role: "sucrant"   },
      { nom: "Lait concentré non sucré",   g: 145,  pct: 14,   role: "mg"        },
      { nom: "Gélatine 200 bloom",         g: 14.5, pct: 1.5,  role: "gelifiant" },
      { nom: "Eau gélatine",               g: 72.5, pct: 7,    role: "eau"       },
      { nom: "Poudre de cacao",            g: 60,   pct: 6,    role: "parfum"    },
      { nom: "Chocolat 58%",               g: 173,  pct: 17.5, role: "parfum"    },
    ],
    procede: [
      "Hydrater la gélatine dans 5× son poids en eau froide (quantités déjà indiquées).",
      "Réaliser un sirop avec l'eau, le sucre, le glucose et le lait concentré. Cuire à 103°C.",
      "Stopper la cuisson avec la masse gélatine et la poudre de cacao.",
      "Une fois la gélatine totalement fondue, filtrer et verser sur le chocolat.",
      "Mixer sans incorporer d'air.",
      "Utiliser entre 25 et 30°C. Conserver à 4°C.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["glaçage", "miroir", "chocolat noir", "entremets", "finition"],
    parfum_principal: "chocolat noir",
    note_concepteur: "En cas de bulles d'air, filtrer le glaçage à l'aide d'une étamine.",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 60,
      chef: null,
    },
  },
];
