export const RECETTES_GLACES_SORBETS = [
  {
    id: "glace-chocolat-noir",
    nom: "Crème glacée chocolat noir",
    categorie: "glaces_sorbets",
    sous_categorie: "glace_turbinee",
    description: "Crème glacée au chocolat noir pasteurisée et turbinée. Matières sèches équilibrées pour une texture onctueuse et une saveur intense.",
    masse_totale_g: 1625,
    ingredients: [
      { nom: "Lait UHT entier",       g: 1036, pct: 64,  role: "eau"        },
      { nom: "Crème liquide 35%",     g: 110,  pct: 7,   role: "mg"         },
      { nom: "Poudre de lait 0%",     g: 45,   pct: 3,   role: "structure"  },
      { nom: "Saccharose",            g: 100,  pct: 6,   role: "sucrant"    },
      { nom: "Dextrose",              g: 90,   pct: 5,   role: "sucrant"    },
      { nom: "Sucre inverti",         g: 100,  pct: 6,   role: "sucrant"    },
      { nom: "Stabilisateur à glace", g: 10,   pct: 0.5, role: "structure"  },
      { nom: "Monostéarates",         g: 4,    pct: 0.5, role: "emulsifiant"},
      { nom: "Chocolat noir 67%",     g: 130,  pct: 8,   role: "parfum"     },
    ],
    procede: [
      "Mélanger le lait et la poudre de lait.",
      "À 30°C ajouter les sucres (saccharose, dextrose, sucre inverti).",
      "À 35°C ajouter la crème.",
      "À 45°C ajouter les stabilisateurs, les monostéarates et le chocolat.",
      "Porter à 85°C en remuant constamment (pasteurisation).",
      "Filtrer et mixer. Filmer au contact, refroidir rapidement à 4°C.",
      "Laisser maturer minimum 12h à 4°C, mixer à nouveau puis turbiner.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: -14, conservation_c: -18 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["glace", "turbiner", "chocolat noir", "dessert glacé", "pasteurisation"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Afin de développer les arômes et optimiser la consistance finale, laisser maturer au minimum 6h à 4°C avant de turbiner.",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 52,
      chef: null,
    },
  },
  {
    id: "semifreddo-cerise",
    nom: "Semifreddo cerise",
    categorie: "glaces_sorbets",
    sous_categorie: "semifreddo",
    description: "Semifreddo à la cerise, texture aérée non turbinée. Parfum fruité intense, servi en tranche ou en verrine.",
    masse_totale_g: 1579,
    ingredients: [
      { nom: "Œufs entiers",    g: 220, pct: 14, role: "liant"   },
      { nom: "Sucre semoule",   g: 226, pct: 14, role: "sucrant" },
      { nom: "Purée de cerise", g: 680, pct: 43, role: "fruit"   },
      { nom: "Crème montée",    g: 453, pct: 29, role: "mg"      },
    ],
    procede: [
      "Monter les œufs et le sucre au bain-marie jusqu'à 55°C, puis fouetter hors du feu jusqu'à refroidissement complet (pâte à bombe).",
      "Incorporer la purée de cerise à température ambiante.",
      "Incorporer délicatement la crème montée en deux fois.",
      "Couler en moule ou cadre. Surgeler minimum 4h.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: -6, conservation_c: -18 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["oeuf", "lait"],
    tags: ["semifreddo", "cerise", "glacé", "non turbiné", "dessert à l'assiette"],
    parfum_principal: "cerise",
    note_concepteur: null,
    source_interne: {
      fichier_pdf: "Bachour Simply Beautiful.pdf",
      page: 106,
      chef: null,
    },
  },
  {
    id: "semifreddo-coco",
    nom: "Semifreddo coco",
    categorie: "glaces_sorbets",
    sous_categorie: "semifreddo",
    description: "Semifreddo à la noix de coco et couverture blanche, léger et exotique, relevé d'une pointe de rhum.",
    masse_totale_g: 580,
    ingredients: [
      { nom: "Lait de coco",     g: 200, pct: 35, role: "fruit"  },
      { nom: "Couverture blanc", g: 160, pct: 28, role: "parfum" },
      { nom: "Rhum coco",        g: 20,  pct: 3,  role: "parfum" },
      { nom: "Crème montée",     g: 200, pct: 34, role: "mg"     },
    ],
    procede: [
      "Chauffer le lait de coco, verser sur la couverture blanche hachée, émulsionner.",
      "Ajouter le rhum, laisser refroidir à 30°C.",
      "Incorporer délicatement la crème montée.",
      "Couler en moule. Surgeler minimum 4h.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: -6, conservation_c: -18 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait"],
    tags: ["semifreddo", "coco", "rhum", "glacé", "non turbiné", "exotique"],
    parfum_principal: "coco",
    note_concepteur: null,
    source_interne: {
      fichier_pdf: "Bachour Simply Beautiful.pdf",
      page: 108,
      chef: null,
    },
  },
  {
    id: "semifreddo-praline",
    nom: "Semifreddo praliné",
    categorie: "glaces_sorbets",
    sous_categorie: "semifreddo",
    description: "Semifreddo praliné, aérien et gourmand, à base de meringue et crème montée.",
    masse_totale_g: 776,
    ingredients: [
      { nom: "Crème liquide 35% (base)", g: 96,  pct: 12, role: "mg"      },
      { nom: "Pâte de praliné",          g: 275, pct: 36, role: "parfum"  },
      { nom: "Blancs d'œufs",           g: 70,  pct: 9,  role: "aeration" },
      { nom: "Sucre semoule",            g: 60,  pct: 7,  role: "sucrant"  },
      { nom: "Crème montée",             g: 275, pct: 36, role: "mg"      },
    ],
    procede: [
      "Tiédir légèrement la crème base avec la pâte de praliné, bien mélanger.",
      "Monter les blancs en meringue avec le sucre.",
      "Incorporer la meringue à l'appareil praliné.",
      "Incorporer délicatement la crème montée.",
      "Couler en moule. Surgeler minimum 4h.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: -6, conservation_c: -18 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["oeuf", "lait", "fruits_a_coque"],
    tags: ["semifreddo", "praliné", "glacé", "non turbiné", "meringue"],
    parfum_principal: "praliné",
    note_concepteur: null,
    source_interne: {
      fichier_pdf: "Bachour Simply Beautiful.pdf",
      page: 110,
      chef: null,
    },
  },

  /* ── Révolution Pâtisserie — Johanna Le Pape ────────────────────────────── */

  {
    id: "glace-cacahuete-lp",
    nom: "Glace cacahuète",
    categorie: "glaces_sorbets",
    sous_categorie: "glace_fruit",
    description: "Glace cacahuète sans produits laitiers : eau, pâte de cacahuète, dattes et miel, géliflée à l'arrow-root. Congeler puis mixer.",
    masse_totale_g: 644,
    ingredients: [
      { nom: "Eau",               g: 500, pct: 77.6, role: "eau"       },
      { nom: "Dattes",            g:  80, pct: 12.4, role: "sucrant"   },
      { nom: "Pâte de cacahuète", g:  50, pct:  7.8, role: "parfum"    },
      { nom: "Miel",              g:  10, pct:  1.6, role: "sucrant"   },
      { nom: "Fécule d'arrow-root",g:  4, pct:  0.6, role: "structure" },
    ],
    procede: [
      "Porter l'eau, la pâte de cacahuète et la fécule d'arrow-root à ébullition.",
      "Verser sur les dattes et le miel. Mixer.",
      "Verser dans des petits moules en silicone. Congeler au moins 2 heures.",
      "Pour servir : démouler et mixer à l'aide d'un blender. Consommer immédiatement.",
    ],
    cuisson: { temperature_c: null, duree_min: 2, mode: "feu + congélateur" },
    temperatures: { service_c: -2, conservation_c: -18 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["arachide"],
    tags: ["glace", "cacahuète", "dattes", "sans lactose", "vegan", "sans barème"],
    parfum_principal: "cacahuète",
    note_concepteur: "Technique popsicle/granité : congélation en moules puis mixage. À consommer immédiatement après le mixage.",
    source_interne: { fichier_pdf: "Révolution-Pâtisserie.-La-bible-de-la-pâtisserie-saine-Johanna-Le-Pape_-Mlanie-Frechon-_-WeLib_organized.pdf", page: 188, chef: "Johanna Le Pape", date_extraction: "2026-05-20" },
  },

  {
    id: "glace-chocolat-lp",
    nom: "Glace chocolat",
    categorie: "glaces_sorbets",
    sous_categorie: "glace_chocolat",
    description: "Glace chocolat sans produits laitiers : crème de coco, lait d'amande, chocolat 64% et miel. Fleur de sel pour la profondeur.",
    masse_totale_g: 325,
    ingredients: [
      { nom: "Crème de coco",     g: 140, pct: 43.1, role: "mg"        },
      { nom: "Chocolat noir 64%", g: 100, pct: 30.8, role: "parfum"    },
      { nom: "Lait d'amande",     g:  70, pct: 21.5, role: "eau"       },
      { nom: "Miel",              g:  10, pct:  3.1, role: "sucrant"   },
      { nom: "Fleur de sel",      g:   4, pct:  1.2, role: "assaisonm" },
      { nom: "Fécule d'arrow-root",g:  1, pct:  0.3, role: "structure" },
    ],
    procede: [
      "Fondre le chocolat.",
      "Chauffer la crème de coco avec le lait d'amande, l'arrow-root et le miel. Porter à ébullition en fouettant.",
      "Verser sur le chocolat et mixer.",
      "Verser dans des petits moules en silicone. Congeler au moins 2 heures.",
      "Pour servir : démouler et mixer. Consommer immédiatement.",
    ],
    cuisson: { temperature_c: null, duree_min: 5, mode: "feu + congélateur" },
    temperatures: { service_c: -2, conservation_c: -18 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["fruits_a_coque"],
    tags: ["glace", "chocolat", "coco", "amande", "fleur de sel", "vegan"],
    parfum_principal: "chocolat",
    note_concepteur: "4g de fleur de sel est la quantité indiquée dans la source — fort dosage intentionnel pour un effet contraste.",
    source_interne: { fichier_pdf: "Révolution-Pâtisserie.-La-bible-de-la-pâtisserie-saine-Johanna-Le-Pape_-Mlanie-Frechon-_-WeLib_organized.pdf", page: 188, chef: "Johanna Le Pape", date_extraction: "2026-05-20" },
  },

  {
    id: "sorbet-abricot-thym-lp",
    nom: "Sorbet abricot thym",
    categorie: "glaces_sorbets",
    sous_categorie: "sorbet_fruit",
    description: "Sorbet abricot au jus de pomme et thym citron séché. Sans sucre raffiné, sans produits laitiers.",
    masse_totale_g: 442,
    ingredients: [
      { nom: "Abricots frais",        g: 300, pct: 67.9, role: "parfum"  },
      { nom: "Jus de pomme",          g: 100, pct: 22.6, role: "eau"     },
      { nom: "Miel",                  g:  40, pct:  9.0, role: "sucrant" },
      { nom: "Thym citron séché",     g:   2, pct:  0.5, role: "parfum"  },
    ],
    procede: [
      "Laver les abricots et retirer les noyaux.",
      "Mixer tous les ingrédients ensemble.",
      "Verser dans des petits moules en silicone. Congeler au moins 2 heures.",
      "Pour servir : démouler et mixer à l'aide d'un blender. Consommer immédiatement.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "congélateur" },
    temperatures: { service_c: -2, conservation_c: -18 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["sorbet", "abricot", "thym citron", "jus de pomme", "vegan", "sans sucre"],
    parfum_principal: "abricot",
    note_concepteur: null,
    source_interne: { fichier_pdf: "Révolution-Pâtisserie.-La-bible-de-la-pâtisserie-saine-Johanna-Le-Pape_-Mlanie-Frechon-_-WeLib_organized.pdf", page: 190, chef: "Johanna Le Pape", date_extraction: "2026-05-20" },
  },

  {
    id: "sorbet-ananas-coco-lp",
    nom: "Sorbet ananas coco",
    categorie: "glaces_sorbets",
    sous_categorie: "sorbet_fruit",
    description: "Sorbet ananas-coco au lait de coco, crème de coco et zeste de citron vert. Vegan et sans sucre ajouté.",
    masse_totale_g: 680,
    ingredients: [
      { nom: "Ananas frais",           g: 500, pct: 73.5, role: "parfum"  },
      { nom: "Lait de coco",           g: 100, pct: 14.7, role: "eau"     },
      { nom: "Crème de coco",          g:  50, pct:  7.4, role: "mg"      },
      { nom: "Jus et zeste de citron vert", g: 30, pct: 4.4, role: "parfum" },
    ],
    procede: [
      "Peler l'ananas et le couper en petits morceaux.",
      "Mixer l'ananas avec le lait de coco, le jus de citron et la crème de coco.",
      "Ajouter les zestes de citron vert.",
      "Verser dans des petits moules en silicone. Congeler au moins 2 heures.",
      "Pour servir : démouler et mixer à l'aide d'un blender. Consommer immédiatement.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "congélateur" },
    temperatures: { service_c: -2, conservation_c: -18 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: [],
    tags: ["sorbet", "ananas", "coco", "citron vert", "vegan", "sans sucre ajouté"],
    parfum_principal: "ananas",
    note_concepteur: null,
    source_interne: { fichier_pdf: "Révolution-Pâtisserie.-La-bible-de-la-pâtisserie-saine-Johanna-Le-Pape_-Mlanie-Frechon-_-WeLib_organized.pdf", page: 190, chef: "Johanna Le Pape", date_extraction: "2026-05-20" },
  },
];
