export const RECETTES_GLACES_SORBETS = [
  {
    id: "glace-chocolat-noir",
    nom: "Crème glacée chocolat noir",
    categorie: "glaces_sorbets",
    sous_categorie: "glace_turbinee",
    description: "Crème glacée au chocolat noir pasteurisée et turbinée. Matières sèches équilibrées pour une texture onctueuse et une saveur intense.",
    masse_totale_g: 1625,
    ingredients: [
      { nom: "Lait UHT entier",       g: 1036, pct: 64,  role: "eau"        },
      { nom: "Crème liquide 35%",     g: 110,  pct: 7,   role: "mg"         },
      { nom: "Poudre de lait 0%",     g: 45,   pct: 3,   role: "structure"  },
      { nom: "Saccharose",            g: 100,  pct: 6,   role: "sucrant"    },
      { nom: "Dextrose",              g: 90,   pct: 5,   role: "sucrant"    },
      { nom: "Sucre inverti",         g: 100,  pct: 6,   role: "sucrant"    },
      { nom: "Stabilisateur à glace", g: 10,   pct: 0.5, role: "structure"  },
      { nom: "Monostéarates",         g: 4,    pct: 0.5, role: "emulsifiant"},
      { nom: "Chocolat noir 67%",     g: 130,  pct: 8,   role: "parfum"     },
    ],
    procede: [
      "Mélanger le lait et la poudre de lait.",
      "À 30°C ajouter les sucres (saccharose, dextrose, sucre inverti).",
      "À 35°C ajouter la crème.",
      "À 45°C ajouter les stabilisateurs, les monostéarates et le chocolat.",
      "Porter à 85°C en remuant constamment (pasteurisation).",
      "Filtrer et mixer. Filmer au contact, refroidir rapidement à 4°C.",
      "Laisser maturer minimum 12h à 4°C, mixer à nouveau puis turbiner.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: -14, conservation_c: -18 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["glace", "turbiner", "chocolat noir", "dessert glacé", "pasteurisation"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Afin de développer les arômes et optimiser la consistance finale, laisser maturer au minimum 6h à 4°C avant de turbiner.",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 52,
      chef: null,
    },
  },
];
