export const RECETTES_MOUSSES = [
  {
    id: "mousse-chocolat-noir-01",
    nom: "Mousse chocolat noir",
    categorie: "mousses",
    sous_categorie: "mousse_chocolat",
    description: "Mousse aérienne au chocolat noir, montée sur base pâte à bombe. Texture soyeuse, intensité cacaotée.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Chocolat noir 70%",    g: 250, pct: 25, role: "parfum"   },
      { nom: "Crème foisonnée 35%",  g: 400, pct: 40, role: "aeration" },
      { nom: "Crème chaude 35%",     g: 150, pct: 15, role: "mg"       },
      { nom: "Jaunes d'œufs",        g:  80, pct:  8, role: "liant"    },
      { nom: "Sucre semoule",        g:  80, pct:  8, role: "sucrant"  },
      { nom: "Eau (sirop)",          g:  40, pct:  4, role: "eau"      },
    ],
    procede: [
      "Fondre le chocolat noir à 50 °C au bain-marie.",
      "Préparer un sirop à 121 °C avec le sucre et l'eau.",
      "Monter les jaunes au batteur. Verser le sirop chaud en filet. Fouetter jusqu'à complet refroidissement (pâte à bombe).",
      "Verser la crème chaude sur le chocolat fondu en trois fois, émulsionner.",
      "Incorporer la pâte à bombe à la ganache chocolat tiède (35 °C) à la maryse.",
      "Incorporer la crème foisonnée mousseuse en deux fois par mouvements enveloppants.",
      "Couler immédiatement dans les cercles ou cadres. Bloquer au froid (–18 °C).",
    ],
    cuisson: { temperature_c: 121, duree_min: null, mode: "sirop cuit — pâte à bombe" },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["oeuf", "lactose"],
    tags: ["chocolat", "noir", "mousse", "entremets", "intense"],
    parfum_principal: "chocolat",
    note_concepteur: "La température de la ganache lors de l'incorporation de la crème foisonnée est critique : trop froide, elle crée des grumeaux ; trop chaude, elle fait fondre la crème. Viser 35 °C.",
    source_interne: {
      fichier_pdf: null,
      page: null,
      nom_original: "Recette de test — recette générique",
      chef: null,
      date_extraction: "2026-05-18",
    },
  },

  {
    id: "mousse-framboise-01",
    nom: "Mousse framboise",
    categorie: "mousses",
    sous_categorie: "mousse_fruit",
    description: "Mousse légère et acidulée à la framboise, montée sur meringue italienne. Couleur naturelle vive, texture fondante.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Purée de framboise",     g: 350, pct: 35,  role: "fruit"     },
      { nom: "Crème foisonnée 35%",    g: 400, pct: 40,  role: "aeration"  },
      { nom: "Blancs d'œufs",          g:  80, pct:  8,  role: "aeration"  },
      { nom: "Sucre semoule (sirop)",  g: 100, pct: 10,  role: "sucrant"   },
      { nom: "Eau (sirop)",            g:  60, pct:  6,  role: "eau"       },
      { nom: "Gélatine (poudre 200B)", g:  10, pct:  1,  role: "gelifiant" },
    ],
    procede: [
      "Réhydrater la gélatine dans 5× son poids en eau froide, laisser gonfler.",
      "Préparer un sirop à 121 °C avec le sucre et l'eau.",
      "Monter les blancs en neige souple. Verser le sirop chaud en filet pour obtenir une meringue italienne. Fouetter jusqu'à refroidissement à 35 °C.",
      "Chauffer une petite partie de la purée (50 g), dissoudre la gélatine essorée. Mélanger au reste de la purée froide.",
      "Foisonner la crème en chantilly mousseuse (pas trop ferme).",
      "Incorporer la purée gélifiée à la meringue à la maryse.",
      "Incorporer la chantilly en deux fois par mouvements enveloppants.",
      "Couler immédiatement dans les moules. Bloquer au froid (–18 °C) ou réfrigérer 4 h.",
    ],
    cuisson: { temperature_c: 121, duree_min: null, mode: "sirop cuit — meringue italienne" },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["oeuf", "lactose"],
    tags: ["framboise", "mousse", "entremets", "fruit", "leger"],
    parfum_principal: "framboise",
    note_concepteur: "La meringue italienne stabilise la mousse et remplace partiellement la gélatine. L'intégration de la purée doit se faire avant que la meringue refroidisse complètement pour faciliter le mélange.",
    source_interne: {
      fichier_pdf: null,
      page: null,
      nom_original: "Recette de test — recette générique",
      chef: null,
      date_extraction: "2026-05-18",
    },
  },
];
