export const RECETTES_MOUSSES = [
  {
    id: "mousse-bavaroise-noir",
    nom: "Mousse bavaroise chocolat noir",
    categorie: "mousses",
    sous_categorie: "mousse_bavaroise",
    description: "Mousse sur base crème anglaise, allégée à la crème fouettée. Texture onctueuse et bien structurée, sans gélatine pour la variante noir.",
    masse_totale_g: 852,
    ingredients: [
      { nom: "Crème liquide 35%",       g: 105,  pct: 12, role: "mg"       },
      { nom: "Lait UHT entier",          g: 105,  pct: 12, role: "eau"      },
      { nom: "Jaune d'œuf pasteurisé",  g: 40,   pct: 5,  role: "liant"    },
      { nom: "Chocolat noir 67%",        g: 270,  pct: 32, role: "parfum"   },
      { nom: "Crème fouettée 35%",       g: 332,  pct: 39, role: "aeration" },
    ],
    procede: [
      "Réaliser une crème anglaise avec le lait, la crème et les jaunes d'œufs. Cuire à 82°C.",
      "Filtrer et verser immédiatement sur le chocolat.",
      "Émulsionner au mixeur plongeant.",
      "Lorsque la base atteint 35°C, incorporer la crème fouettée mousseuse.",
      "Utiliser immédiatement. Conserver à 4°C ou surgeler.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 14, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["mousse", "chocolat noir", "entremets", "crème anglaise", "bavaroise"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Pour une texture homogène, bien respecter la température d'incorporation de la crème fouettée (35°C pour les chocolats noirs).",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 30,
      chef: null,
    },
  },

  {
    id: "mousse-patebombe-noir",
    nom: "Mousse pâte à bombe chocolat noir",
    categorie: "mousses",
    sous_categorie: "mousse_patebombe",
    description: "Mousse aérienne au chocolat noir sur pâte à bombe. Légèreté maximale, sans crème anglaise ni gélatine.",
    masse_totale_g: 910,
    ingredients: [
      { nom: "Jaune d'œuf pasteurisé",  g: 244, pct: 27, role: "liant"    },
      { nom: "Sucre semoule",            g: 158, pct: 17, role: "sucrant"  },
      { nom: "Eau",                      g: 58,  pct: 6,  role: "eau"      },
      { nom: "Chocolat noir 67%",        g: 150, pct: 17, role: "parfum"   },
      { nom: "Crème fouettée 35%",       g: 300, pct: 33, role: "aeration" },
    ],
    procede: [
      "Pocher à 65°C au bain-marie les jaunes, le sucre et l'eau, puis monter au ruban au fouet.",
      "Fondre le chocolat à 55-60°C.",
      "Incorporer environ un tiers de la crème fouettée mousseuse au fouet.",
      "Ajouter la pâte à bombe, puis le reste de crème fouettée.",
      "Parfaire le mélange à la spatule silicone. Utiliser immédiatement.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 14, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait", "oeuf"],
    tags: ["mousse", "chocolat noir", "entremets", "pâte à bombe", "aérien"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Pour une pâte à bombe réussie et un gain de temps, il n'est pas nécessaire de réaliser un sirop de sucre : porter le tout à 65°C avec des jaunes d'œufs pasteurisés.",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 32,
      chef: null,
    },
  },

  {
    id: "mousse-legere-noir",
    nom: "Mousse légère chocolat noir",
    categorie: "mousses",
    sous_categorie: "mousse_legere",
    description: "Mousse express au chocolat noir : base lait gélifié, allégée à la crème fouettée. La plus simple et la plus légère des trois mousses.",
    masse_totale_g: 504,
    ingredients: [
      { nom: "Lait UHT entier",    g: 117,  pct: 23,   role: "eau"       },
      { nom: "Gélatine 200 bloom", g: 1,    pct: 0.5,  role: "gelifiant" },
      { nom: "Eau gélatine",       g: 6,    pct: 1.5,  role: "eau"       },
      { nom: "Chocolat noir 67%",  g: 145,  pct: 28,   role: "parfum"    },
      { nom: "Crème fouettée 35%", g: 235,  pct: 47,   role: "aeration"  },
    ],
    procede: [
      "Hydrater la gélatine dans 6× son poids en eau froide (quantités déjà indiquées).",
      "Porter le lait à ébullition, ajouter la masse gélatine et laisser fondre.",
      "Verser sur le chocolat fondu, émulsionner au mixeur plongeant.",
      "Lorsque la base atteint environ 40°C, incorporer la crème fouettée mousseuse.",
      "Utiliser aussitôt. Surgeler ou conserver à 4°C.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 14, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["mousse", "chocolat noir", "entremets", "légère", "simple"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Pour une texture idéale, monter la crème fouettée à vitesse moyenne sans trop serrer pour un maximum de volume.",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 34,
      chef: null,
    },
  },
];
