export const RECETTES_MOUSSES = [
  {
    id: "mousse-bavaroise-noir",
    nom: "Mousse bavaroise chocolat noir",
    categorie: "mousses",
    sous_categorie: "mousse_bavaroise",
    description: "Mousse sur base crème anglaise, allégée à la crème fouettée. Texture onctueuse et bien structurée, sans gélatine pour la variante noir.",
    masse_totale_g: 852,
    ingredients: [
      { nom: "Crème liquide 35%",       g: 105,  pct: 12, role: "mg"       },
      { nom: "Lait UHT entier",          g: 105,  pct: 12, role: "eau"      },
      { nom: "Jaune d'œuf pasteurisé",  g: 40,   pct: 5,  role: "liant"    },
      { nom: "Chocolat noir 67%",        g: 270,  pct: 32, role: "parfum"   },
      { nom: "Crème fouettée 35%",       g: 332,  pct: 39, role: "aeration" },
    ],
    procede: [
      "Réaliser une crème anglaise avec le lait, la crème et les jaunes d'œufs. Cuire à 82°C.",
      "Filtrer et verser immédiatement sur le chocolat.",
      "Émulsionner au mixeur plongeant.",
      "Lorsque la base atteint 35°C, incorporer la crème fouettée mousseuse.",
      "Utiliser immédiatement. Conserver à 4°C ou surgeler.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 14, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["mousse", "chocolat noir", "entremets", "crème anglaise", "bavaroise"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Pour une texture homogène, bien respecter la température d'incorporation de la crème fouettée (35°C pour les chocolats noirs).",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 30,
      chef: null,
    },
  },

  {
    id: "mousse-patebombe-noir",
    nom: "Mousse pâte à bombe chocolat noir",
    categorie: "mousses",
    sous_categorie: "mousse_patebombe",
    description: "Mousse aérienne au chocolat noir sur pâte à bombe. Légèreté maximale, sans crème anglaise ni gélatine.",
    masse_totale_g: 910,
    ingredients: [
      { nom: "Jaune d'œuf pasteurisé",  g: 244, pct: 27, role: "liant"    },
      { nom: "Sucre semoule",            g: 158, pct: 17, role: "sucrant"  },
      { nom: "Eau",                      g: 58,  pct: 6,  role: "eau"      },
      { nom: "Chocolat noir 67%",        g: 150, pct: 17, role: "parfum"   },
      { nom: "Crème fouettée 35%",       g: 300, pct: 33, role: "aeration" },
    ],
    procede: [
      "Pocher à 65°C au bain-marie les jaunes, le sucre et l'eau, puis monter au ruban au fouet.",
      "Fondre le chocolat à 55-60°C.",
      "Incorporer environ un tiers de la crème fouettée mousseuse au fouet.",
      "Ajouter la pâte à bombe, puis le reste de crème fouettée.",
      "Parfaire le mélange à la spatule silicone. Utiliser immédiatement.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 14, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait", "oeuf"],
    tags: ["mousse", "chocolat noir", "entremets", "pâte à bombe", "aérien"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Pour une pâte à bombe réussie et un gain de temps, il n'est pas nécessaire de réaliser un sirop de sucre : porter le tout à 65°C avec des jaunes d'œufs pasteurisés.",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 32,
      chef: null,
    },
  },

  {
    id: "mousse-legere-noir",
    nom: "Mousse légère chocolat noir",
    categorie: "mousses",
    sous_categorie: "mousse_legere",
    description: "Mousse express au chocolat noir : base lait gélifié, allégée à la crème fouettée. La plus simple et la plus légère des trois mousses.",
    masse_totale_g: 504,
    ingredients: [
      { nom: "Lait UHT entier",    g: 117,  pct: 23,   role: "eau"       },
      { nom: "Gélatine 200 bloom", g: 1,    pct: 0.5,  role: "gelifiant" },
      { nom: "Eau gélatine",       g: 6,    pct: 1.5,  role: "eau"       },
      { nom: "Chocolat noir 67%",  g: 145,  pct: 28,   role: "parfum"    },
      { nom: "Crème fouettée 35%", g: 235,  pct: 47,   role: "aeration"  },
    ],
    procede: [
      "Hydrater la gélatine dans 6× son poids en eau froide (quantités déjà indiquées).",
      "Porter le lait à ébullition, ajouter la masse gélatine et laisser fondre.",
      "Verser sur le chocolat fondu, émulsionner au mixeur plongeant.",
      "Lorsque la base atteint environ 40°C, incorporer la crème fouettée mousseuse.",
      "Utiliser aussitôt. Surgeler ou conserver à 4°C.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 14, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["mousse", "chocolat noir", "entremets", "légère", "simple"],
    parfum_principal: "chocolat noir",
    note_concepteur: "Pour une texture idéale, monter la crème fouettée à vitesse moyenne sans trop serrer pour un maximum de volume.",
    source_interne: {
      fichier_pdf: "210902_WEISS_LE LIVRE DU SAVOIR FAIRE_EXE_BD.pdf",
      page: 34,
      chef: null,
    },
  },

  /* ── Révolution Pâtisserie — Johanna Le Pape ────────────────────────────── */

  {
    id: "mousse-chocolat-fleur-sel-lp",
    nom: "Mousse chocolat fleur de sel",
    categorie: "mousses",
    sous_categorie: "mousse_chocolat",
    description: "Mousse chocolat sans crème laitière : blancs d'œufs (ou aquafaba) montés, lait d'amande et fleur de sel.",
    masse_totale_g: 231,
    ingredients: [
      { nom: "Chocolat noir 64%", g: 100, pct: 43.3, role: "parfum"   },
      { nom: "Blancs d'œufs",    g:  90, pct: 39.0, role: "aeration" },
      { nom: "Lait d'amande",    g:  40, pct: 17.3, role: "eau"      },
      { nom: "Fleur de sel",     g:   1, pct:  0.4, role: "assaisonm"},
    ],
    procede: [
      "Fondre le chocolat avec le lait d'amande au bain-marie. Laisser refroidir à 40 °C.",
      "Monter les blancs (ou l'aquafaba) en neige souple.",
      "Incorporer délicatement les blancs en 3 fois au chocolat.",
      "Ajouter la fleur de sel. Réserver au frais minimum 2 heures.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson" },
    temperatures: { service_c: 4, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["oeuf", "fruits_a_coque"],
    tags: ["mousse", "chocolat", "fleur de sel", "sans crème", "aquafaba"],
    parfum_principal: "chocolat",
    note_concepteur: "Alternative vegan : remplacer les blancs par 90g d'aquafaba. Gingembre frais râpé (1g) mentionné dans la source — non inclus dans la masse totale.",
    source_interne: { fichier_pdf: "Révolution-Pâtisserie.-La-bible-de-la-pâtisserie-saine-Johanna-Le-Pape_-Mlanie-Frechon-_-WeLib_organized.pdf", page: 220, chef: "Johanna Le Pape", date_extraction: "2026-05-20" },
  },

  /* ── Karim Bourgi ────────────────────────────────────────────────────── */

  {
    id: "mousse-chocolat-pepites-cacao-kb",
    nom: "Mousse chocolat-pépites de cacao",
    categorie: "mousses",
    sous_categorie: "mousse_chocolat",
    description: "Mousse chocolat noir à infusion de pépites de cacao dans la crème. Mélange Illanka 63% + Jivara 40% pour complexité aromatique. Légèreté par crème fouettée à soupe peaks.",
    masse_totale_g: 893,
    ingredients: [
      { nom: "Crème liquide 35% (1)",    g: 225, pct: 25, role: "mg"       },
      { nom: "Pépites de cacao",         g:  40, pct:  5, role: "parfum"   },
      { nom: "Sirop de glucose",         g:  37, pct:  4, role: "sucrant"  },
      { nom: "Chocolat Illanka 63%",     g: 230, pct: 26, role: "parfum"   },
      { nom: "Chocolat Jivara 40%",      g:  37, pct:  4, role: "parfum"   },
      { nom: "Crème liquide 35% (2)",    g: 324, pct: 36, role: "aeration" },
    ],
    procede: [
      "Mélanger la crème (1) et les pépites de cacao dans une casserole. Porter presque à ébullition.",
      "Retirer du feu, couvrir et infuser 30 min.",
      "Chinoiser et peser : compléter avec de la crème si nécessaire pour retrouver 225g.",
      "Ajouter le glucose à la crème infusée et chauffer à 60°C.",
      "Fondre les deux chocolats ensemble au micro-ondes.",
      "Verser la crème chaude sur le chocolat. Mixer au plongeant jusqu'à texture lisse. Laisser refroidir à 35°C.",
      "Monter la crème (2) en pics souples au batteur.",
      "Incorporer la crème montée en plusieurs fois au mélange chocolat, en mélangeant délicatement au fouet.",
      "Utiliser immédiatement.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: 14, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait"],
    tags: ["mousse", "chocolat noir", "pépites de cacao", "entremets", "infusion"],
    parfum_principal: "chocolat noir",
    note_concepteur: "L'infusion des pépites de cacao dans la crème apporte une amertume et des arômes de cacao cru qui complètent le chocolat fondu. Ne pas filtrer trop fin pour conserver un peu de matière.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 95,
      chef: "Karim Bourgi",
    },
  },

  /* ── Eddie Benghanem — Le Grand Cours de Pâtisserie ─────────────────── */

  {
    id: "bavarois-base-eb",
    nom: "Bavarois de base",
    categorie: "mousses",
    sous_categorie: "bavarois",
    description: "Bavarois classique : crème anglaise gélifiée + crème fouettée mousseuse. Texture légère, stable au froid. Peut être parfumé avec n'importe quelle pulpe de fruits ou extrait.",
    masse_totale_g: 500,
    ingredients: [
      { nom: "Lait entier",        g: 125, pct: 25, role: "eau"      },
      { nom: "Crème liquide 35% (1)",g: 125, pct: 25, role: "mg"    },
      { nom: "Sucre semoule",      g:  26, pct:  5, role: "sucrant"  },
      { nom: "Jaunes d'œufs",     g:  75, pct: 15, role: "liant"    },
      { nom: "Gélatine feuilles",  g:   5, pct:  1, role: "gelifiant"},
      { nom: "Crème liquide 35% (2)",g: 200, pct: 40, role: "aeration"},
    ],
    procede: [
      "Préparer un récipient creux avec des glaçons.",
      "Réhydrater la gélatine 10 min dans l'eau froide.",
      "Porter le lait, la crème (1) et la moitié du sucre à ébullition.",
      "Fouetter les jaunes et le sucre restant. Verser le liquide chaud. Reverser en casserole. Cuire à 82°C.",
      "Ajouter la gélatine essorée hors du feu. Filtrer. Placer sur les glaçons jusqu'à refroidissement.",
      "Monter la crème (2) en chantilly mousseuse.",
      "Incorporer délicatement la chantilly au mélange crème anglaise-gélatine à la maryse.",
      "Verser dans des verrines. Réfrigérer 2h.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole — anglaise 82°C" },
    temperatures: { service_c: 6, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["bavarois", "crème anglaise", "mousse", "entremets", "base"],
    parfum_principal: "vanille",
    note_concepteur: "Refroidir rapidement la crème anglaise sur glaçons est indispensable avant d'incorporer la chantilly. Décorer au moment de servir avec des brisures de biscuits ou croustillants.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 450,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "bavarois-framboise-eb",
    nom: "Bavarois à la framboise",
    categorie: "mousses",
    sous_categorie: "bavarois",
    description: "Bavarois framboise : crème anglaise lait+pulpe framboises gélifiée + crème fouettée. Texture bec d'oiseau pour la chantilly. Couler dans des verrines avec couche de pulpe fraises.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Lait entier",         g: 190, pct: 19, role: "eau"      },
      { nom: "Sucre semoule",       g: 130, pct: 13, role: "sucrant"  },
      { nom: "Jaunes d'œufs",      g: 150, pct: 15, role: "liant"    },
      { nom: "Pulpe de framboises", g: 320, pct: 32, role: "fruit"    },
      { nom: "Gélatine feuilles",   g:  10, pct:  1, role: "gelifiant"},
      { nom: "Crème liquide 35%",   g: 300, pct: 30, role: "aeration" },
    ],
    procede: [
      "Réhydrater la gélatine dans l'eau froide.",
      "Chauffer le lait et la pulpe. Mélanger jaunes + sucre. Verser lait+pulpe. Cuire à 82°C.",
      "Ajouter la gélatine essorée hors du feu. Laisser refroidir.",
      "Monter la crème froide en texture bec d'oiseau.",
      "Pré-mélanger un peu de chantilly dans la préparation framboise, puis incorporer le reste délicatement à la maryse.",
      "Couler dans des verrines. Ajouter une fine couche de pulpe de fraises. Réfrigérer 2h.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole — 82°C" },
    temperatures: { service_c: 6, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["bavarois", "framboise", "mousse", "fruits rouges", "entremets"],
    parfum_principal: "framboise",
    note_concepteur: "La texture de la chantilly au stade 'bec d'oiseau' (souple, pas trop ferme) garantit un bavarois léger sans grumeaux. La couche de pulpe de fraises mixées en finition apporte fraîcheur et couleur.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 452,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "bavarois-chocolat-lait-eb",
    nom: "Bavarois au chocolat au lait",
    categorie: "mousses",
    sous_categorie: "bavarois",
    description: "Bavarois chocolat lait : crème anglaise émulsionnée sur chocolat lait+noir, crème fouettée incorporée à 40°C du mélange chocolat. Texture dense et fondante. Pour entremets, insert, verrine.",
    masse_totale_g: 600,
    ingredients: [
      { nom: "Lait entier",              g: 105, pct: 18, role: "eau"    },
      { nom: "Crème liquide 35% (1)",    g: 105, pct: 18, role: "mg"     },
      { nom: "Jaunes d'œufs",           g:  50, pct:  8, role: "liant"  },
      { nom: "Sucre semoule",            g:  35, pct:  6, role: "sucrant"},
      { nom: "Chocolat lait 35%",        g:  90, pct: 15, role: "parfum" },
      { nom: "Chocolat noir 64%",        g: 135, pct: 23, role: "parfum" },
      { nom: "Crème liquide 35% (2)",    g: 225, pct: 38, role: "aeration"},
    ],
    procede: [
      "Porter lait et crème (1) à ébullition. Fouetter jaunes et sucre. Cuire à 82°C.",
      "Verser sur les deux chocolats hachés. Mélanger et mixer au plongeant.",
      "Monter la crème (2) en chantilly mousseuse.",
      "Lorsque l'appareil chocolat atteint 40°C, incorporer délicatement la chantilly.",
      "Couler dans des verrines. Réfrigérer 3h.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole — anglaise 82°C" },
    temperatures: { service_c: 6, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["bavarois", "chocolat lait", "chocolat noir", "mousse", "entremets"],
    parfum_principal: "chocolat lait",
    note_concepteur: "Bien respecter la température d'incorporation (40°C) — trop chaud fait fondre la chantilly, trop froid fait gripper le chocolat. L'association chocolat lait+noir équilibre douceur et amertume.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 454,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "mousse-fruits-des-bois-eb",
    nom: "Mousse aux fruits des bois",
    categorie: "mousses",
    sous_categorie: "mousse_fruits",
    description: "Mousse fruits des bois : purées framboises+fraises+cassis gélifiées, allégeées à la meringue italienne + crème fouettée. Texture légère et aérienne. Pour verrine, entremets, insert.",
    masse_totale_g: 600,
    ingredients: [
      { nom: "Gélatine feuilles",   g:   4, pct:  1, role: "gelifiant"},
      { nom: "Purée framboises",    g: 120, pct: 20, role: "fruit"    },
      { nom: "Purée fraises",       g: 120, pct: 20, role: "fruit"    },
      { nom: "Purée cassis",        g:  90, pct: 15, role: "fruit"    },
      { nom: "Blanc d'œuf",        g:  30, pct:  5, role: "aeration" },
      { nom: "Eau",                 g:  20, pct:  3, role: "eau"      },
      { nom: "Sucre semoule",       g:  50, pct:  8, role: "sucrant"  },
      { nom: "Sirop de glucose",    g:  25, pct:  4, role: "sucrant"  },
      { nom: "Crème liquide 35%",   g: 200, pct: 33, role: "aeration" },
    ],
    procede: [
      "Réhydrater la gélatine dans l'eau froide.",
      "Chauffer 1/3 des purées de fruits. Ajouter la gélatine hors du feu, dissoudre. Ajouter les autres purées.",
      "Meringue italienne : cuire eau + sucre + glucose à 118°C. Monter le blanc. Verser le sirop. Fouetter jusqu'à refroidissement.",
      "Monter la crème froide en chantilly.",
      "Incorporer à la maryse : crème fouettée dans la meringue, puis purées-gélatine.",
      "Couler dans des verrines. Réfrigérer 3h. Décorer de fruits frais.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole — sirop 118°C" },
    temperatures: { service_c: 6, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["mousse", "fruits des bois", "framboise", "fraise", "cassis", "léger"],
    parfum_principal: "fruits rouges",
    note_concepteur: "La meringue italienne froide et la crème fouettée froide sont indispensables au succès. Incorporer la crème dans la meringue, pas l'inverse, pour conserver le maximum de légèreté.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 456,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "mousse-exotique-eb",
    nom: "Mousse exotique passion-mangue",
    categorie: "mousses",
    sous_categorie: "mousse_fruits",
    description: "Mousse exotique à la meringue italienne : passion+mangue gélifiées, allégeées à la meringue italienne + crème fouettée. Intense en fruits exotiques. Pour entremets coco-mangue.",
    masse_totale_g: 870,
    ingredients: [
      { nom: "Sucre semoule",              g:  96, pct: 11, role: "sucrant"  },
      { nom: "Sirop de glucose",           g:  38, pct:  4, role: "sucrant"  },
      { nom: "Eau",                        g:  25, pct:  3, role: "eau"      },
      { nom: "Blancs d'œufs",             g:  60, pct:  7, role: "aeration" },
      { nom: "Purée de fruits de la Passion",g: 240, pct: 28, role: "fruit"  },
      { nom: "Purée de mangues",           g: 240, pct: 28, role: "fruit"    },
      { nom: "Gélatine feuilles",          g:  25, pct:  3, role: "gelifiant"},
      { nom: "Crème liquide 35%",          g: 288, pct: 33, role: "aeration" },
    ],
    procede: [
      "Réhydrater la gélatine dans l'eau froide.",
      "Meringue italienne : cuire eau + sucre + glucose à 118°C. Monter les blancs. Verser le sirop. Fouetter jusqu'à refroidissement.",
      "Chauffer une partie des purées, dissoudre la gélatine. Ajouter les purées restantes.",
      "Monter la crème en chantilly.",
      "Incorporer la chantilly à la meringue. Ajouter les purées gélatinées à la maryse.",
      "Couler dans les moules. Réfrigérer minimum 2h.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "casserole — sirop 118°C" },
    temperatures: { service_c: 6, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["mousse", "passion", "mangue", "exotique", "entremets"],
    parfum_principal: "fruit de la passion",
    note_concepteur: "25g gélatine = 12.5 feuilles — ratio élevé pour un entremets moulé. À ajuster à 15g (7.5 feuilles) pour une verrine. La forte proportion de purée donne une mousse très fruitée.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 459,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "mousse-marrons-eb",
    nom: "Mousse aux marrons",
    categorie: "mousses",
    sous_categorie: "mousse_autre",
    description: "Mousse marrons sur sabayon léger : crème+pâte de marrons mixées, sabayon sirop à 80°C, crème fouettée incorporée. Texture aérée et parfumée. Pour Mont-blanc, verrine, insert.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Gélatine feuilles",   g:  15, pct:  2, role: "gelifiant"},
      { nom: "Crème de marrons",    g: 185, pct: 19, role: "parfum"  },
      { nom: "Pâte de marrons",     g: 185, pct: 19, role: "parfum"  },
      { nom: "Whisky",              g:  12, pct:  1, role: "parfum"  },
      { nom: "Sirop à 30°B",        g:  90, pct:  9, role: "sucrant" },
      { nom: "Jaunes d'œufs",      g:  75, pct:  8, role: "liant"   },
      { nom: "Crème liquide 35%",   g: 550, pct: 55, role: "aeration"},
    ],
    procede: [
      "Hydrater la gélatine dans l'eau froide.",
      "Mixer crème de marrons + pâte de marrons + whisky.",
      "Sabayon : chauffer sirop + jaunes au bain-marie jusqu'à 80°C en fouettant. Placer au robot, fouetter jusqu'à refroidissement.",
      "Fondre la gélatine essorée. Incorporer dans un peu de sabayon, puis dans le reste.",
      "Monter la crème en chantilly.",
      "Incorporer l'appareil marrons puis la crème fouettée à la maryse.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "bain-marie — 80°C" },
    temperatures: { service_c: 6, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["lait", "oeuf"],
    tags: ["mousse marrons", "Mont-blanc", "sabayon", "whisky", "entremets"],
    parfum_principal: "marron",
    note_concepteur: "Le whisky est facultatif mais apporte de la profondeur. Le sirop à 30°B est un sirop standard : 300g sucre + 100g eau. La gélatine pre-mélangée dans un peu de sabayon avant incorporation générale évite les grumeaux.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 434,
      chef: "Eddie Benghanem",
    },
  },
];
