// Révolution Pâtisserie — Johanna Le Pape (Flammarion 2023)
const _SRC = "Révolution-Pâtisserie.-La-bible-de-la-pâtisserie-saine-Johanna-Le-Pape_-Mlanie-Frechon-_-WeLib_organized.pdf";
const _CHEF = "Johanna Le Pape";
const _DATE = "2026-05-20";

export const RECETTES_PATES = [

  /* ── Recettes de base ─────────────────────────────────────────────────── */

  {
    id: "pate-sucree-lp",
    nom: "Pâte sucrée",
    categorie: "pates",
    sous_categorie: "pate_sucree",
    description: "Pâte sucrée saine à la farine d'épeautre et farine de riz, allégée en matières grasses. Alternative végétale : remplacer le beurre par 50 g de purée d'amande.",
    masse_totale_g: 256,
    ingredients: [
      { nom: "Farine d'épeautre",     g: 70,  pct: 27.3, role: "structure" },
      { nom: "Farine de riz complet", g: 40,  pct: 15.6, role: "structure" },
      { nom: "Poudre d'amande",       g: 40,  pct: 15.6, role: "parfum"    },
      { nom: "Sucre complet",         g: 40,  pct: 15.6, role: "sucrant"   },
      { nom: "Beurre",                g: 50,  pct: 19.5, role: "mg"        },
      { nom: "Eau",                   g: 15,  pct:  5.9, role: "eau"       },
      { nom: "Fleur de sel",          g:  1,  pct:  0.4, role: "assaisonm" },
    ],
    procede: [
      "Mélanger le sucre avec les farines et la poudre d'amande.",
      "Ajouter l'eau et la fleur de sel, puis terminer avec le beurre pommade.",
      "Étaler à 3 mm entre deux feuilles de papier sulfurisé.",
      "Cuire à 160 °C pendant 12 à 15 minutes.",
    ],
    cuisson: { temperature_c: 160, duree_min: 13, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "lait", "fruits_a_coque"],
    tags: ["pâte sucrée", "épeautre", "riz", "fond de tarte", "base"],
    parfum_principal: "amande",
    note_concepteur: "Pour une version vegan, remplacer le beurre par 50 g de purée d'amande. Pour une version IG bas, remplacer le sucre complet par du sucre de coco ou de l'érythritol.",
    source_interne: { fichier_pdf: _SRC, page: 168, chef: _CHEF, date_extraction: _DATE },
  },

  {
    id: "pate-sablee-lp",
    nom: "Pâte sablée coco-citron",
    categorie: "pates",
    sous_categorie: "pate_sablee",
    description: "Pâte sablée sans gluten à la farine de coco, d'avoine et poudre d'amande, parfumée au zeste de citron. Glaçage coco-citron en option.",
    masse_totale_g: 241,
    ingredients: [
      { nom: "Farine d'avoine",  g: 60, pct: 24.9, role: "structure" },
      { nom: "Farine de coco",   g: 40, pct: 16.6, role: "structure" },
      { nom: "Poudre d'amande",  g: 40, pct: 16.6, role: "parfum"    },
      { nom: "Beurre",           g: 70, pct: 29.0, role: "mg"        },
      { nom: "Sucre de datte",   g: 14, pct:  5.8, role: "sucrant"   },
      { nom: "Eau",              g: 10, pct:  4.1, role: "eau"       },
      { nom: "Fleur de sel",     g:  5, pct:  2.1, role: "assaisonm" },
      { nom: "Zeste de citron",  g:  2, pct:  0.8, role: "parfum"    },
    ],
    procede: [
      "Mélanger à la feuille le beurre et le sucre de datte.",
      "Ajouter au fur et à mesure le sel, les farines, la poudre d'amande et l'eau.",
      "Étaler entre deux feuilles de papier cuisson à 3 mm.",
      "Tailler des bâtonnets de 1 cm × 10 cm. Placer 15 min au congélateur.",
      "Cuire à 160 °C pendant 12 minutes sur tapis Silpain.",
    ],
    cuisson: { temperature_c: 160, duree_min: 12, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: true },
    a_verifier: false,
    allergenes: ["lait", "fruits_a_coque"],
    tags: ["pâte sablée", "coco", "citron", "avoine", "bâtonnets", "base"],
    parfum_principal: "citron",
    note_concepteur: "Alternative farine sans gluten : remplacer l'avoine par de la farine de riz. Alternative végétale : remplacer le beurre par 50 g d'eau + 30 g de compote de pomme.",
    source_interne: { fichier_pdf: _SRC, page: 170, chef: _CHEF, date_extraction: _DATE },
  },

  {
    id: "pate-a-choux-lp",
    nom: "Pâte à choux végétale",
    categorie: "pates",
    sous_categorie: "pate_a_choux",
    description: "Pâte à choux sans beurre ni farine de blé, à base d'huile neutre, farine de riz et farine de maïs. Texture légère et dorée.",
    masse_totale_g: 452,
    ingredients: [
      { nom: "Lait végétal",          g: 100, pct: 22.1, role: "eau"       },
      { nom: "Eau",                   g: 100, pct: 22.1, role: "eau"       },
      { nom: "Huile neutre",          g: 150, pct: 33.2, role: "mg"        },
      { nom: "Farine de riz complet", g:  70, pct: 15.5, role: "structure" },
      { nom: "Farine de maïs",        g:  30, pct:  6.6, role: "structure" },
      { nom: "Sel fin gris",          g:   1, pct:  0.2, role: "assaisonm" },
      { nom: "Sucre complet",         g:   1, pct:  0.2, role: "sucrant"   },
    ],
    procede: [
      "Chauffer le lait, l'eau, l'huile et le sel sans porter à ébullition, pendant 30 secondes.",
      "Hors du feu, ajouter en une fois les farines tamisées.",
      "Mélanger et dessécher la pâte, toujours hors du feu, pendant 30 secondes.",
      "Transvaser dans la cuve du robot et travailler à la feuille até de la refroidir.",
      "Dès qu'elle commence à être tiède, ajouter les œufs battus en filet, progressivement.",
      "On doit obtenir une pâte lisse, brillante et retombant de la feuille en faisant un V.",
      "Pocher sur plaque antiadhésive et cuire à 180 °C pendant 20 à 30 minutes.",
    ],
    cuisson: { temperature_c: 180, duree_min: 25, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["oeuf"],
    tags: ["pâte à choux", "végétal", "sans beurre", "sans gluten", "base"],
    parfum_principal: null,
    note_concepteur: "Les oeufs sont ajoutés progressivement après refroidissement — quantité à ajuster selon la texture (non indiquée précisément dans la source). Masse totale oeufs non incluse.",
    source_interne: { fichier_pdf: _SRC, page: 172, chef: _CHEF, date_extraction: _DATE },
  },

  {
    id: "pate-a-baba-lp",
    nom: "Pâte à baba",
    categorie: "pates",
    sous_categorie: "pate_a_baba",
    description: "Pâte à baba levée aux farines de riz et sarrasin, sans gluten de blé. Texture élastique et dorée, pour babas individuels ou grande pièce.",
    masse_totale_g: 370,
    ingredients: [
      { nom: "Farine de riz",    g: 125, pct: 33.8, role: "structure" },
      { nom: "Fécule de maïs",   g:  11, pct:  3.0, role: "structure" },
      { nom: "Farine de sarrasin",g:  9, pct:  2.4, role: "structure" },
      { nom: "Œufs entiers",     g: 200, pct: 54.1, role: "liant"     },
      { nom: "Beurre",           g:  11, pct:  3.0, role: "mg"        },
      { nom: "Miel",             g:   5, pct:  1.4, role: "sucrant"   },
      { nom: "Levure boulangère",g:   5, pct:  1.4, role: "levant"    },
      { nom: "Sel fin",          g:   1, pct:  0.3, role: "assaisonm" },
      { nom: "Eau",              g:  10, pct:  2.7, role: "eau"       },
    ],
    procede: [
      "Dans le bol du batteur, mélanger à la feuille la levure, l'eau et le miel.",
      "Ajouter les farines, la fécule, le sel, le beurre coupé en dés et les oeufs.",
      "Pétrir en première vitesse jusqu'à ce que la pâte soit lisse, brillante et se décolle du bol.",
      "Graisser légèrement les moules. Peser 35 g par moule individuel.",
      "Mettre à pousser 40 min à 28-30 °C.",
      "Cuire 10 min à 180 °C pour les babas individuels, 30 min pour le grand format.",
      "Démouler.",
    ],
    cuisson: { temperature_c: 180, duree_min: 10, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["oeuf", "lait"],
    tags: ["pâte à baba", "levée", "riz", "sarrasin", "sans blé", "base"],
    parfum_principal: null,
    note_concepteur: "Proportions farines estimées depuis lecture visuelle — à vérifier sur source. Alternative végétale possible avec lait végétal, margarine et méthode adaptée.",
    source_interne: { fichier_pdf: _SRC, page: 178, chef: _CHEF, date_extraction: _DATE },
  },

];
