// Révolution Pâtisserie — Johanna Le Pape (Flammarion 2023)
const _SRC = "Révolution-Pâtisserie.-La-bible-de-la-pâtisserie-saine-Johanna-Le-Pape_-Mlanie-Frechon-_-WeLib_organized.pdf";
const _CHEF = "Johanna Le Pape";
const _DATE = "2026-05-20";

const _SRC_LN1  = "Chocolats et сonfiserie de l ecole Lenotre T1.pdf";
const _CHEF_LN1 = "François Legras & Stéphane Glacier";

const _SRC_EB  = "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf";
const _CHEF_EB = "Eddie Benghanem";
const _DATE_EB = "2026-06-02";

export const RECETTES_PATES = [

  /* ── Recettes de base ─────────────────────────────────────────────────── */

  {
    id: "pate-sucree-lp",
    nom: "Pâte sucrée",
    categorie: "pates",
    sous_categorie: "pate_sucree",
    description: "Pâte sucrée saine à la farine d'épeautre et farine de riz, allégée en matières grasses. Alternative végétale : remplacer le beurre par 50 g de purée d'amande.",
    masse_totale_g: 256,
    ingredients: [
      { nom: "Farine d'épeautre",     g: 70,  pct: 27.3, role: "structure" },
      { nom: "Farine de riz complet", g: 40,  pct: 15.6, role: "structure" },
      { nom: "Poudre d'amande",       g: 40,  pct: 15.6, role: "parfum"    },
      { nom: "Sucre complet",         g: 40,  pct: 15.6, role: "sucrant"   },
      { nom: "Beurre",                g: 50,  pct: 19.5, role: "mg"        },
      { nom: "Eau",                   g: 15,  pct:  5.9, role: "eau"       },
      { nom: "Fleur de sel",          g:  1,  pct:  0.4, role: "assaisonm" },
    ],
    procede: [
      "Mélanger le sucre avec les farines et la poudre d'amande.",
      "Ajouter l'eau et la fleur de sel, puis terminer avec le beurre pommade.",
      "Étaler à 3 mm entre deux feuilles de papier sulfurisé.",
      "Cuire à 160 °C pendant 12 à 15 minutes.",
    ],
    cuisson: { temperature_c: 160, duree_min: 13, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "lait", "fruits_a_coque"],
    tags: ["pâte sucrée", "épeautre", "riz", "fond de tarte", "base"],
    parfum_principal: "amande",
    note_concepteur: "Pour une version vegan, remplacer le beurre par 50 g de purée d'amande. Pour une version IG bas, remplacer le sucre complet par du sucre de coco ou de l'érythritol.",
    source_interne: { fichier_pdf: _SRC, page: 168, chef: _CHEF, date_extraction: _DATE },
  },

  {
    id: "pate-sablee-lp",
    nom: "Pâte sablée coco-citron",
    categorie: "pates",
    sous_categorie: "pate_sablee",
    description: "Pâte sablée sans gluten à la farine de coco, d'avoine et poudre d'amande, parfumée au zeste de citron. Glaçage coco-citron en option.",
    masse_totale_g: 241,
    ingredients: [
      { nom: "Farine d'avoine",  g: 60, pct: 24.9, role: "structure" },
      { nom: "Farine de coco",   g: 40, pct: 16.6, role: "structure" },
      { nom: "Poudre d'amande",  g: 40, pct: 16.6, role: "parfum"    },
      { nom: "Beurre",           g: 70, pct: 29.0, role: "mg"        },
      { nom: "Sucre de datte",   g: 14, pct:  5.8, role: "sucrant"   },
      { nom: "Eau",              g: 10, pct:  4.1, role: "eau"       },
      { nom: "Fleur de sel",     g:  5, pct:  2.1, role: "assaisonm" },
      { nom: "Zeste de citron",  g:  2, pct:  0.8, role: "parfum"    },
    ],
    procede: [
      "Mélanger à la feuille le beurre et le sucre de datte.",
      "Ajouter au fur et à mesure le sel, les farines, la poudre d'amande et l'eau.",
      "Étaler entre deux feuilles de papier cuisson à 3 mm.",
      "Tailler des bâtonnets de 1 cm × 10 cm. Placer 15 min au congélateur.",
      "Cuire à 160 °C pendant 12 minutes sur tapis Silpain.",
    ],
    cuisson: { temperature_c: 160, duree_min: 12, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 15 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: true },
    a_verifier: false,
    allergenes: ["lait", "fruits_a_coque"],
    tags: ["pâte sablée", "coco", "citron", "avoine", "bâtonnets", "base"],
    parfum_principal: "citron",
    note_concepteur: "Alternative farine sans gluten : remplacer l'avoine par de la farine de riz. Alternative végétale : remplacer le beurre par 50 g d'eau + 30 g de compote de pomme.",
    source_interne: { fichier_pdf: _SRC, page: 170, chef: _CHEF, date_extraction: _DATE },
  },

  {
    id: "pate-a-choux-lp",
    nom: "Pâte à choux végétale",
    categorie: "pates",
    sous_categorie: "pate_a_choux",
    description: "Pâte à choux sans beurre ni farine de blé, à base d'huile neutre, farine de riz et farine de maïs. Texture légère et dorée.",
    masse_totale_g: 452,
    ingredients: [
      { nom: "Lait végétal",          g: 100, pct: 22.1, role: "eau"       },
      { nom: "Eau",                   g: 100, pct: 22.1, role: "eau"       },
      { nom: "Huile neutre",          g: 150, pct: 33.2, role: "mg"        },
      { nom: "Farine de riz complet", g:  70, pct: 15.5, role: "structure" },
      { nom: "Farine de maïs",        g:  30, pct:  6.6, role: "structure" },
      { nom: "Sel fin gris",          g:   1, pct:  0.2, role: "assaisonm" },
      { nom: "Sucre complet",         g:   1, pct:  0.2, role: "sucrant"   },
    ],
    procede: [
      "Chauffer le lait, l'eau, l'huile et le sel sans porter à ébullition, pendant 30 secondes.",
      "Hors du feu, ajouter en une fois les farines tamisées.",
      "Mélanger et dessécher la pâte, toujours hors du feu, pendant 30 secondes.",
      "Transvaser dans la cuve du robot et travailler à la feuille até de la refroidir.",
      "Dès qu'elle commence à être tiède, ajouter les œufs battus en filet, progressivement.",
      "On doit obtenir une pâte lisse, brillante et retombant de la feuille en faisant un V.",
      "Pocher sur plaque antiadhésive et cuire à 180 °C pendant 20 à 30 minutes.",
    ],
    cuisson: { temperature_c: 180, duree_min: 25, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["oeuf"],
    tags: ["pâte à choux", "végétal", "sans beurre", "sans gluten", "base"],
    parfum_principal: null,
    note_concepteur: "Les oeufs sont ajoutés progressivement après refroidissement — quantité à ajuster selon la texture (non indiquée précisément dans la source). Masse totale oeufs non incluse.",
    source_interne: { fichier_pdf: _SRC, page: 172, chef: _CHEF, date_extraction: _DATE },
  },

  {
    id: "pate-a-baba-lp",
    nom: "Pâte à baba",
    categorie: "pates",
    sous_categorie: "pate_a_baba",
    description: "Pâte à baba levée aux farines de riz et sarrasin, sans gluten de blé. Texture élastique et dorée, pour babas individuels ou grande pièce.",
    masse_totale_g: 370,
    ingredients: [
      { nom: "Farine de riz",    g: 125, pct: 33.8, role: "structure" },
      { nom: "Fécule de maïs",   g:  11, pct:  3.0, role: "structure" },
      { nom: "Farine de sarrasin",g:  9, pct:  2.4, role: "structure" },
      { nom: "Œufs entiers",     g: 200, pct: 54.1, role: "liant"     },
      { nom: "Beurre",           g:  11, pct:  3.0, role: "mg"        },
      { nom: "Miel",             g:   5, pct:  1.4, role: "sucrant"   },
      { nom: "Levure boulangère",g:   5, pct:  1.4, role: "levant"    },
      { nom: "Sel fin",          g:   1, pct:  0.3, role: "assaisonm" },
      { nom: "Eau",              g:  10, pct:  2.7, role: "eau"       },
    ],
    procede: [
      "Dans le bol du batteur, mélanger à la feuille la levure, l'eau et le miel.",
      "Ajouter les farines, la fécule, le sel, le beurre coupé en dés et les oeufs.",
      "Pétrir en première vitesse jusqu'à ce que la pâte soit lisse, brillante et se décolle du bol.",
      "Graisser légèrement les moules. Peser 35 g par moule individuel.",
      "Mettre à pousser 40 min à 28-30 °C.",
      "Cuire 10 min à 180 °C pour les babas individuels, 30 min pour le grand format.",
      "Démouler.",
    ],
    cuisson: { temperature_c: 180, duree_min: 10, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["oeuf", "lait"],
    tags: ["pâte à baba", "levée", "riz", "sarrasin", "sans blé", "base"],
    parfum_principal: null,
    note_concepteur: "Proportions farines estimées depuis lecture visuelle — à vérifier sur source. Alternative végétale possible avec lait végétal, margarine et méthode adaptée.",
    source_interne: { fichier_pdf: _SRC, page: 178, chef: _CHEF, date_extraction: _DATE },
  },

  /* ── Karim Bourgi ────────────────────────────────────────────────────── */

  {
    id: "pate-sablee-noisette-kb",
    nom: "Pâte sablée noisette",
    categorie: "pates",
    sous_categorie: "pate_sablee",
    description: "Sablée riche à la poudre de noisette, beurre à point (pas de crémage). Technique sablage pour texture friable. Étalée à 2–2.5 mm et cuite en deux temps à 140°C. Pour tartelettes d=8 cm.",
    masse_totale_g: 1113,
    ingredients: [
      { nom: "Farine",               g: 495, pct: 45, role: "structure" },
      { nom: "Sucre glace",          g: 190, pct: 17, role: "sucrant"  },
      { nom: "Poudre de noisette",   g:  65, pct:  6, role: "parfum"  },
      { nom: "Sel",                  g:   3, pct:  0, role: "assaisonm"},
      { nom: "Beurre 82% (froid)",   g: 255, pct: 23, role: "mg"      },
      { nom: "Œufs entiers",         g: 105, pct:  9, role: "liant"   },
    ],
    procede: [
      "Dans le bol du batteur avec la feuille, mélanger farine, sucre glace, poudre de noisette, sel et beurre froid coupé en cubes jusqu'à texture sableuse.",
      "Ajouter les œufs entiers. Mélanger jusqu'à pâte homogène. Finir à la main.",
      "Diviser en 3 parts. Étaler entre deux feuilles guitare à 2–2.5 mm.",
      "Reposer 12h à 3–4°C.",
      "Travailler à 18–21°C sur surface froide. Découper des bandes 24 cm × 2.5 cm. Surgeler.",
      "Beurrer les cercles d=8 cm h=2 cm, surgeler. Foncer avec les bandes, former les fonds.",
      "Cuire les cercles surgelés à 140°C, 20 min. Retirer les cercles. Cuire encore 15 min jusqu'à dorure.",
    ],
    cuisson: { temperature_c: 140, duree_min: 35, mode: "chaleur tournante — perforé" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf", "lait", "fruits_a_coque"],
    tags: ["pâte sablée", "noisette", "tartelette", "croustillant", "fond"],
    parfum_principal: "noisette",
    note_concepteur: "Technique de fonçage par bandes (côtés puis fond séparé) garantit des angles nets. Travailler rapidement sur surface froide pour éviter que la pâte ne ramollisse.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 13,
      chef: "Karim Bourgi",
    },
  },

  {
    id: "pate-sablee-amande-2farines-kb",
    nom: "Pâte sablée amande (2 farines)",
    categorie: "pates",
    sous_categorie: "pate_sablee",
    description: "Sablée professionnelle à double farine (T55 + farine de force 13–15% protéines) pour équilibre tenue/friabilité. Fonçage en bandes, cuisson en 2 temps à 150°C. Pour tartelettes d=7 cm.",
    masse_totale_g: 482,
    ingredients: [
      { nom: "Farine T55",                    g:  55, pct: 11, role: "structure" },
      { nom: "Farine de force (13–15% prot.)", g: 167, pct: 35, role: "structure"},
      { nom: "Beurre 82% (mou)",              g: 110, pct: 23, role: "mg"       },
      { nom: "Sucre glace",                   g:  74, pct: 15, role: "sucrant"  },
      { nom: "Poudre d'amande",               g:  28, pct:  6, role: "parfum"   },
      { nom: "Sel",                           g:   2, pct:  0, role: "assaisonm"},
      { nom: "Œufs entiers",                  g:  46, pct: 10, role: "liant"    },
    ],
    procede: [
      "Placer le beurre mou, le sel, le sucre glace, la poudre d'amande, les œufs et la farine T55 dans le bol du batteur. Mélanger à faible vitesse jusqu'à homogénéité.",
      "Ajouter la farine de force. Arrêter dès incorporation.",
      "Réfrigérer plusieurs heures avant d'étaler.",
      "Étaler en 2 parts à 2 mm entre deux feuilles guitare ou papier sulfurisé.",
      "Reposer minimum 3h à 3–4°C.",
      "Foncer les cercles d=7 cm selon la technique bandes surgelées.",
      "Cuire à 150°C, 15 min. Démouler. Badigeonner d'egg wash au pistolet. Recuire 5 min.",
    ],
    cuisson: { temperature_c: 150, duree_min: 20, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf", "lait", "fruits_a_coque"],
    tags: ["pâte sablée", "amande", "double farine", "tartelette", "fond", "professionnel"],
    parfum_principal: "amande",
    note_concepteur: "La farine de force (13–15% protéines) apporte de l'élasticité et évite les craquelures au fonçage. Le badigeonnage d'egg wash (jaune + crème) après la 1ère cuisson donne le brillant et l'imperméabilité.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 28,
      chef: "Karim Bourgi",
    },
  },

  {
    id: "pate-sablee-avoine-kb",
    nom: "Pâte sablée aux flocons d'avoine",
    categorie: "pates",
    sous_categorie: "pate_sablee",
    description: "Sablée rustique aux flocons d'avoine semi-grillés et sucre brun. Texture plus dense qu'une sablée classique, bords nets. Étalée à 3 mm, moulée en tartlette d=8 cm sans fonçage en bande.",
    masse_totale_g: 500,
    ingredients: [
      { nom: "Farine",               g: 105, pct: 21, role: "structure" },
      { nom: "Flocons d'avoine",     g: 160, pct: 32, role: "structure" },
      { nom: "Sel",                  g:   2, pct:  0, role: "assaisonm" },
      { nom: "Sucre brun foncé",     g:  85, pct: 17, role: "sucrant"  },
      { nom: "Levure chimique",      g: 1.5, pct:  0, role: "levant"   },
      { nom: "Beurre 82% (froid)",   g: 125, pct: 25, role: "mg"       },
      { nom: "Blancs d'œufs",       g:  21, pct:  4, role: "liant"    },
    ],
    procede: [
      "Mixer au robot flocons, sel, sucre et levure. Ne pas trop réduire — conserver quelques petits morceaux d'avoine.",
      "Ajouter le beurre froid en cubes. Mélanger jusqu'à texture sableuse.",
      "Incorporer les blancs d'œufs. Mélanger jusqu'à pâte unie. Façonner en rectangle, filmer.",
      "Réfrigérer minimum 3h (de préférence une nuit).",
      "Étaler à 3 mm entre deux feuilles de papier sulfurisé ou acétate.",
      "Découper des cercles d=10 cm. Foncer des moules d=8 cm en appuyant vers les bords.",
      "Ébarber, piquer, réfrigérer 1h. Cuire à 160°C, 20 min jusqu'à dorure. Laisser refroidir dans le moule.",
    ],
    cuisson: { temperature_c: 160, duree_min: 20, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf", "lait"],
    tags: ["pâte sablée", "avoine", "banoffee", "tartelette", "rustique", "sucre brun"],
    parfum_principal: null,
    note_concepteur: "Ne pas mixer les flocons trop finement — quelques morceaux visibles donnent la texture caractéristique et le croquant biscuité. Le blanc d'œuf (non monté) suffit à lier sans alourdir.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 60,
      chef: "Karim Bourgi",
    },
  },

  {
    id: "pate-a-foncer-kb",
    nom: "Pâte à foncer (flan)",
    categorie: "pates",
    sous_categorie: "pate_a_foncer",
    description: "Pâte à foncer peu sucrée et légèrement lactée (lait en poudre). Étalée à 2.5 mm, garnie directement en cercle d=18 cm h=6 cm depuis le surgelé. Cuisson avec la garniture flan.",
    masse_totale_g: 514,
    ingredients: [
      { nom: "Farine",            g: 250, pct: 49, role: "structure" },
      { nom: "Beurre 82%",        g: 187, pct: 36, role: "mg"       },
      { nom: "Eau",               g:  50, pct: 10, role: "eau"      },
      { nom: "Lait en poudre 0%", g:   5, pct:  1, role: "liant"   },
      { nom: "Sel",               g:   7, pct:  1, role: "assaisonm"},
      { nom: "Sucre semoule",     g:   5, pct:  1, role: "sucrant"  },
      { nom: "Jaunes d'œufs",    g:  10, pct:  2, role: "liant"    },
    ],
    procede: [
      "Dissoudre le lait en poudre et le sel dans l'eau. Réserver.",
      "Mélanger farine, sucre et beurre en cubes froids au batteur feuille jusqu'à texture sableuse.",
      "Ajouter les jaunes d'œufs et le mélange eau-lait. Mélanger jusqu'à pâte homogène et souple.",
      "Étaler à 2.5 mm entre deux feuilles de papier sulfurisé.",
      "Réfrigérer minimum 3h.",
      "Découper des disques d=32 cm. Foncer deux cercles d=18 cm h=6 cm. Surgeler.",
      "Garnir directement de l'appareil flan et cuire (voir assemblage Flan à la Vanille).",
    ],
    cuisson: { temperature_c: 170, duree_min: 40, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf", "lait"],
    tags: ["pâte à foncer", "flan", "fond", "classique", "peu sucrée"],
    parfum_principal: null,
    note_concepteur: "Le lait en poudre apporte une légère note lactée et améliore la dorure à la cuisson. Foncer depuis le surgelé évite la déformation à la cuisson sans précuisson à blanc.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 102,
      chef: "Karim Bourgi",
    },
  },

  {
    id: "pate-feuilletee-viennoise-kb",
    nom: "Pâte feuilletée viennoise",
    categorie: "pates",
    sous_categorie: "pate_feuilletee",
    description: "Feuilletée viennoise enrichie aux œufs et beurre dans la détrempe. 3 tours simples. Cuite lestée entre deux tapis perforés à 180°C, caramélisée au caramel en poudre. Pour millefeuille.",
    masse_totale_g: 857,
    ingredients: [
      { nom: "Farine",            g: 333, pct: 39, role: "structure" },
      { nom: "Lait 3.2%",         g: 133, pct: 16, role: "eau"      },
      { nom: "Œufs entiers",      g:  37, pct:  4, role: "liant"    },
      { nom: "Sel",               g:   7, pct:  1, role: "assaisonm"},
      { nom: "Sucre semoule",     g:  13, pct:  2, role: "sucrant"  },
      { nom: "Beurre 82% (détrempe)", g: 67, pct: 8, role: "mg"    },
      { nom: "Beurre de tourage 82%", g: 267, pct: 31, role: "mg"  },
    ],
    procede: [
      "Mélanger farine, sel, lait, œufs, sucre et beurre (détrempe) fondu refroidi au crochet 6 min. Pâte élastique et non collante.",
      "Filmer, réfrigérer minimum 3h.",
      "Former le beurre de tourage en rectangle 15×20 cm à 3 mm. Réfrigérer 1h.",
      "Envelopper le beurre dans la détrempe (2× plus longue). Sceller. Laminer 3 tours simples avec repos 1h au froid entre chaque.",
      "Étaler à 3 mm en 40×60 cm. Réfrigérer ou surgeler 10 min.",
      "Cuire lestée (entre deux tapis perforés + grille) à 180°C, 20 min jusqu'à dorure.",
      "Découper et saupoudrer de caramel en poudre. Recuire 1–2 min pour caraméliser.",
    ],
    cuisson: { temperature_c: 180, duree_min: 22, mode: "chaleur tournante — lestée" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf", "lait"],
    tags: ["feuilletée", "viennoise", "millefeuille", "3 tours", "caramel"],
    parfum_principal: null,
    note_concepteur: "Viennoise ≠ feuilletée classique : la détrempe contient œufs et beurre fondu qui enrichissent la texture. La cuisson lestée (entre deux tapis) garantit une épaisseur et une platitude uniformes.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 120,
      chef: "Karim Bourgi",
    },
  },

  {
    id: "pate-a-choux-kb",
    nom: "Pâte à choux",
    categorie: "pates",
    sous_categorie: "pate_a_choux",
    description: "Pâte à choux classique eau-lait à parts égales. Desséchée à la casserole, tempérée avant ajout des œufs progressifs. Dressée en éclairs et surgelée avant cuisson.",
    masse_totale_g: 1440,
    ingredients: [
      { nom: "Eau",          g: 250, pct: 18, role: "eau"      },
      { nom: "Lait 2.5%",   g: 250, pct: 18, role: "eau"      },
      { nom: "Beurre 82%",  g: 220, pct: 16, role: "mg"       },
      { nom: "Sel",         g:   5, pct:  0, role: "assaisonm"},
      { nom: "Sucre",       g:  10, pct:  1, role: "sucrant"  },
      { nom: "Farine",      g: 275, pct: 20, role: "structure"},
      { nom: "Œufs entiers",g: 400, pct: 28, role: "liant"    },
    ],
    procede: [
      "Porter l'eau, le lait, le beurre, le sel et le sucre à ébullition forte.",
      "Hors du feu, transférer dans le bol du batteur. Incorporer toute la farine tamisée d'un coup à la feuille.",
      "Remettre sur feu doux 2 min en remuant à la spatule pour dessécher (ne doit pas coller).",
      "Transférer dans le batteur. Laisser refroidir à 45°C à la feuille.",
      "Incorporer les œufs progressivement en petites quantités à vitesse lente.",
      "La pâte doit être lisse, brillante, homogène et tomber en ruban.",
      "Dresser en éclairs de 12.5–13 cm (~35g) sur plaque Téflon. Surgeler complètement.",
      "Cuire directement du surgelé à 165°C, 45–50 min.",
    ],
    cuisson: { temperature_c: 165, duree_min: 47, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: -18 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf", "lait"],
    tags: ["pâte à choux", "éclair", "professionnel", "surgelé", "cuisson longue"],
    parfum_principal: null,
    note_concepteur: "La congélation des éclairs crus avant cuisson est technique professionnelle : elle garantit un développement régulier et une forme parfaite. Vaporiser d'huile + dextrose avant surgélation pour éviter l'éclatement.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 78,
      chef: "Karim Bourgi",
    },
  },

  {
    id: "pate-babka-kb",
    nom: "Pâte à babka",
    categorie: "pates",
    sous_categorie: "pate_levee",
    description: "Pâte levée briochée riche en beurre (19%), fermentée 12h au froid. Deux farines pour structure et moelleux. Étalée, garnie et tressée pour cuisson en moule à cake.",
    masse_totale_g: 500,
    ingredients: [
      { nom: "Farine T55",          g: 115, pct: 23, role: "structure" },
      { nom: "Farine de force",     g: 115, pct: 23, role: "structure" },
      { nom: "Sucre semoule",       g:  35, pct:  7, role: "sucrant"  },
      { nom: "Sel",                 g:   6, pct:  1, role: "assaisonm"},
      { nom: "Levure fraîche",      g:  13, pct:  3, role: "levant"   },
      { nom: "Lait 2.5%",           g:  46, pct:  9, role: "eau"      },
      { nom: "Œufs entiers",        g:  77, pct: 16, role: "liant"    },
      { nom: "Beurre 82% (froid)",  g:  93, pct: 19, role: "mg"       },
    ],
    procede: [
      "Placer tous les ingrédients sauf le beurre au réfrigérateur la veille.",
      "Au batteur crochet, pétrir farine, sucre, sel, lait, œufs et levure à vitesse lente 5 min.",
      "Augmenter la vitesse, pétrir 12–15 min jusqu'à pâte lisse et élastique (température cible : 24–25°C).",
      "Incorporer le beurre froid en cubes. Pétrir jusqu'à absorption complète.",
      "Façonner en carré sur silicone. Filmer au contact. Fermentation 12h à 3–4°C.",
      "Étaler à 3 mm sur 30 cm de large entre deux feuilles.",
      "Étaler la garniture, rouler serré, couper en 2 dans la longueur, tresser. Placer en moule 8×23×8 cm.",
      "Pousser 2.5–3h à 26°C couvert. Cuire à 155°C, 35 min.",
    ],
    cuisson: { temperature_c: 155, duree_min: 35, mode: "chaleur tournante" },
    temperatures: { service_c: 20, conservation_c: 20 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf", "lait"],
    tags: ["pâte levée", "babka", "brioche", "fermentation froide", "tressée", "viennoiserie"],
    parfum_principal: null,
    note_concepteur: "Fermentation froide 12h = développement aromatique supérieur à une pousse rapide. Travailler la pâte froide depuis le réfrigérateur pour éviter que le beurre ne fonde pendant le façonnage.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 51,
      chef: "Karim Bourgi",
    },
  },

  {
    id: "pate-kougelhopf-kb",
    nom: "Pâte à kougelhopf",
    categorie: "pates",
    sous_categorie: "pate_levee",
    description: "Pâte kougelhopf levée avec raisins macérés à l'orange. Fermentation froide 12h. Cuite en moule traditionnel d=22 cm h=11 cm. Température interne cible 95°C.",
    masse_totale_g: 707,
    ingredients: [
      { nom: "Farine T55",                  g: 136, pct: 19, role: "structure" },
      { nom: "Farine de force (13–15%)",    g: 136, pct: 19, role: "structure" },
      { nom: "Sucre semoule",               g:  41, pct:  6, role: "sucrant"  },
      { nom: "Sel",                         g:   5, pct:  1, role: "assaisonm"},
      { nom: "Levure fraîche",              g:  15, pct:  2, role: "levant"   },
      { nom: "Lait 2.5%",                   g:  55, pct:  8, role: "eau"      },
      { nom: "Œufs entiers",                g:  90, pct: 13, role: "liant"    },
      { nom: "Beurre 82% (froid)",          g: 109, pct: 15, role: "mg"       },
      { nom: "Raisins macérés à l'orange",  g: 120, pct: 17, role: "parfum"   },
    ],
    procede: [
      "Au crochet, pétrir les deux farines, le sucre, le sel, le lait, les œufs et la levure à vitesse lente 5 min.",
      "Augmenter la vitesse, pétrir 12–15 min (pâte lisse et élastique, 24–25°C).",
      "Incorporer le beurre froid en cubes. Pétrir jusqu'à absorption. Incorporer les raisins macérés.",
      "Façonner en boule. Filmer au contact. Fermentation 12h à 3–4°C.",
      "Beurrer 2 moules kougelhopf d=22 cm h=11 cm. Placer les amandes enrobées de blanc dans les cannelures.",
      "Diviser la pâte en 2 couronnes. Placer dans les moules. Couvrir.",
      "Pousser ~3h à 26°C jusqu'à niveau du bord du moule.",
      "Cuire à 200°C puis baisser immédiatement à 175°C. Cuire 50 min en retournant à mi-cuisson. T° interne cible : 95°C.",
      "Démouler après 5 min de refroidissement. Saupoudrer de sucre glace.",
    ],
    cuisson: { temperature_c: 175, duree_min: 50, mode: "chaleur tournante — départ 200°C" },
    temperatures: { service_c: 20, conservation_c: 20 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf", "lait", "fruits_a_coque"],
    tags: ["kougelhopf", "pâte levée", "orange", "raisins", "viennoiserie", "alsacien"],
    parfum_principal: "orange",
    note_concepteur: "Raisins macérés : 100g raisins + 20g jus d'orange, infusion 24h. La double farine (T55 + force) donne une mie plus dense et alvéolée qu'une pâte T55 seule. Viser 95°C à cœur pour une cuisson complète.",
    source_interne: {
      fichier_pdf: "Pastry Collection Karim Bourgi -- Karim Bourgi, Natalia Khoroshaeva, Dmitriy Khoroshaev -- ( WeLib.org ).pdf",
      page: 116,
      chef: "Karim Bourgi",
    },
  },

  /* ── Eddie Benghanem — Le Grand Cours de Pâtisserie ─────────────────── */

  {
    id: "pate-brisee-base-eb",
    nom: "Pâte brisée de base (pâte à foncer)",
    categorie: "pates",
    sous_categorie: "pate_brisee",
    description: "Pâte à foncer classique par sablage. Texture friable, peu sucrée. Base universelle pour tartes salées ou sucrées, quiches. Repos 1h minimum.",
    masse_totale_g: 946,
    ingredients: [
      { nom: "Farine T55",         g: 500, pct: 53, role: "structure" },
      { nom: "Beurre froid",       g: 375, pct: 40, role: "mg"       },
      { nom: "Œuf entier",        g:  50, pct:  5, role: "liant"    },
      { nom: "Sel",                g:  10, pct:  1, role: "assaisonm"},
      { nom: "Eau",                g:  11, pct:  1, role: "eau"      },
    ],
    procede: [
      "Dissoudre le sel dans l'eau.",
      "Mélanger la farine et le beurre froid coupé en morceaux dans le bol du robot avec la feuille jusqu'à texture sableuse.",
      "Ajouter l'eau salée et l'œuf. Mélanger pour obtenir une pâte homogène — ne pas trop travailler.",
      "Fraisage : écraser la pâte avec la paume de la main.",
      "Former une boule aplatie. Filmer et reposer 1h au réfrigérateur.",
    ],
    cuisson: { temperature_c: 160, duree_min: 15, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf", "lait"],
    tags: ["pâte brisée", "foncer", "tarte", "sablage", "base"],
    parfum_principal: null,
    note_concepteur: "10cl d'eau ≈ 100g mais le fraisage fait perdre de l'humidité. Ne pas trop travailler pour ne pas développer le gluten. Peut se réaliser au robot-coupe.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 24,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "pate-brisee-noisette-eb",
    nom: "Pâte brisée à la noisette",
    categorie: "pates",
    sous_categorie: "pate_brisee",
    description: "Variante de la pâte à foncer enrichie de poudre de noisettes. Texture plus sablée et parfumée. Par crémage au beurre pommade. Idéale pour tartes aux fruits ou tartes au chocolat.",
    masse_totale_g: 1091,
    ingredients: [
      { nom: "Farine T55",             g: 510, pct: 47, role: "structure" },
      { nom: "Poudre de noisettes",    g: 140, pct: 13, role: "parfum"   },
      { nom: "Beurre pommade",         g: 325, pct: 30, role: "mg"       },
      { nom: "Jaunes d'œufs",         g:  50, pct:  5, role: "liant"    },
      { nom: "Sel",                    g:   4, pct:  0, role: "assaisonm"},
      { nom: "Lait",                   g:  62, pct:  6, role: "eau"      },
    ],
    procede: [
      "Mélanger le lait et le sel.",
      "Au robot avec la feuille, mélanger la farine, la poudre de noisettes, le beurre pommade et les jaunes jusqu'à texture sablée.",
      "Incorporer progressivement le lait salé.",
      "Former une boule. Filmer et reposer 1h au réfrigérateur.",
    ],
    cuisson: { temperature_c: 160, duree_min: 15, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf", "lait", "fruits_a_coque"],
    tags: ["pâte brisée", "noisette", "tarte", "foncer", "crémage"],
    parfum_principal: "noisette",
    note_concepteur: "La poudre de noisette peut être remplacée par toute autre poudre de fruits à coque pour varier les saveurs.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 25,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "pate-sucree-eb",
    nom: "Pâte sucrée",
    categorie: "pates",
    sous_categorie: "pate_sucree",
    description: "Pâte sucrée par crémage beurre-sucre glace. Texture finement sablée et friable, légèrement amandée. Cuisson à blanc ou avec garniture. Pour tartes, tartelettes, petits fours.",
    masse_totale_g: 1182,
    ingredients: [
      { nom: "Farine T55",        g: 500, pct: 42, role: "structure" },
      { nom: "Beurre",            g: 300, pct: 25, role: "mg"       },
      { nom: "Sucre glace",       g: 200, pct: 17, role: "sucrant"  },
      { nom: "Poudre d'amandes",  g:  60, pct:  5, role: "parfum"   },
      { nom: "Œufs entiers",     g: 120, pct: 10, role: "liant"    },
      { nom: "Sel",               g: 2.5, pct:  0, role: "assaisonm"},
    ],
    procede: [
      "Crémer le beurre et le sucre glace au robot avec la feuille.",
      "Incorporer les œufs, la poudre d'amandes, la farine et le sel.",
      "Mélanger sans excès jusqu'à pâte homogène.",
      "Étaler à 2 mm. Reposer 1h au réfrigérateur.",
      "Foncer les cercles à tarte — technique par bandes (côtés puis fond).",
    ],
    cuisson: { temperature_c: 165, duree_min: 15, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf", "lait", "fruits_a_coque"],
    tags: ["pâte sucrée", "tarte", "tartelette", "petits fours", "amande", "fond"],
    parfum_principal: "amande",
    note_concepteur: "Technique de fonçage : étaler à 2mm, découper une bande de largeur = hauteur du cercle, enrouler à l'intérieur. Puis découper un disque pour le fond et souder. Ne pas trop travailler pour ne pas corser.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 38,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "pate-sablee-base-eb",
    nom: "Pâte sablée de base",
    categorie: "pates",
    sous_categorie: "pate_sablee",
    description: "Pâte sablée fondante par sablage beurre-farine, très sucrée. Texture craquante et fondante. Utilisée en disques découpés à l'emporte-pièce ou en sablés à pocher.",
    masse_totale_g: 1111,
    ingredients: [
      { nom: "Farine T55",        g: 500, pct: 45, role: "structure" },
      { nom: "Beurre pommade",    g: 250, pct: 22, role: "mg"       },
      { nom: "Sucre semoule",     g: 250, pct: 22, role: "sucrant"  },
      { nom: "Œufs entiers",     g: 100, pct:  9, role: "liant"    },
      { nom: "Levure chimique",   g:  10, pct:  1, role: "levant"   },
      { nom: "Sel",               g:   1, pct:  0, role: "assaisonm"},
    ],
    procede: [
      "Sabler le beurre coupé en morceaux et la farine au robot avec la feuille jusqu'à texture sableuse.",
      "Ajouter les œufs, le sucre et le sel. Mélanger sans trop travailler.",
      "Former une boule homogène. Étaler au rouleau.",
      "Détailler à l'emporte-pièce. Placer sur tapis de cuisson.",
      "Cuire 10–15 min selon l'épaisseur.",
    ],
    cuisson: { temperature_c: 160, duree_min: 12, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf", "lait"],
    tags: ["pâte sablée", "biscuit", "sablé", "fond", "emporte-pièce"],
    parfum_principal: null,
    note_concepteur: "La poudre à lever donne un léger gonflement. Peut aussi se réaliser par crémage beurre-sucre pour une texture plus lisse.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 46,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "sable-breton-eb",
    nom: "Sablé breton",
    categorie: "pates",
    sous_categorie: "pate_sablee",
    description: "Sablé breton riche en beurre et jaunes, texture épaisse et croustillante à cœur fondant. Poché à la poche à douille dans des cercles. Caractéristique : forte proportion de beurre demi-sel.",
    masse_totale_g: 1141,
    ingredients: [
      { nom: "Farine T55",       g: 400, pct: 35, role: "structure" },
      { nom: "Beurre mou",       g: 336, pct: 29, role: "mg"       },
      { nom: "Sucre semoule",    g: 264, pct: 23, role: "sucrant"  },
      { nom: "Jaunes d'œufs",   g: 120, pct: 11, role: "liant"    },
      { nom: "Sel",              g:   4, pct:  0, role: "assaisonm"},
      { nom: "Levure chimique",  g:  17, pct:  1, role: "levant"   },
    ],
    procede: [
      "Mélanger les jaunes d'œufs et le sucre dans un bol.",
      "Ajouter le beurre ramolli et mélanger.",
      "Incorporer la farine, le sel et la levure chimique. Mélanger jusqu'à pâte homogène.",
      "Mettre en poche à douille et pocher dans des cercles.",
      "Cuire 15–20 min à 165°C. À mi-cuisson (15 min) les sablés sont dorés et gonflés.",
    ],
    cuisson: { temperature_c: 165, duree_min: 18, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf", "lait"],
    tags: ["sablé breton", "sablé", "breton", "croustillant", "base", "fond de tarte"],
    parfum_principal: null,
    note_concepteur: "Pour un sablé plus croustillant, prolonger 5 min. La pâte peut aussi être réalisée par crémage. Le pochage en cercle garantit une épaisseur uniforme — indispensable pour la tenue.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 47,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "pate-linzer-eb",
    nom: "Pâte Linzer",
    categorie: "pates",
    sous_categorie: "pate_linzer",
    description: "Pâte sablée autrichienne aux jaunes cuits tamisés, poudre d'amandes, cannelle et rhum. Texture très friable et épicée. Pour la tarte linzer et ses variantes.",
    masse_totale_g: 478,
    ingredients: [
      { nom: "Farine T55",              g: 300, pct: 63, role: "structure" },
      { nom: "Beurre pommade",          g: 280, pct: 59, role: "mg"       },
      { nom: "Sucre glace",             g:  50, pct: 10, role: "sucrant"  },
      { nom: "Poudre d'amandes",        g:  50, pct: 10, role: "parfum"   },
      { nom: "Jaune d'œuf cuit tamisé", g:  20, pct:  4, role: "liant"    },
      { nom: "Fleur de sel",            g:   1, pct:  0, role: "assaisonm"},
      { nom: "Cannelle en poudre",      g:   5, pct:  1, role: "parfum"   },
      { nom: "Levure chimique",         g:   2, pct:  0, role: "levant"   },
      { nom: "Rhum brun",               g:   5, pct:  1, role: "parfum"   },
    ],
    procede: [
      "Mélanger le beurre pommade, le sucre glace et la poudre d'amandes.",
      "Ajouter le jaune d'œuf cuit tamisé, la fleur de sel, la cannelle et le rhum.",
      "Incorporer la farine et la levure tamisées. Mélanger jusqu'à boule homogène.",
      "Filmer et reposer 2h au réfrigérateur.",
      "Étaler à 3 mm. Foncer un cercle de 22 cm. Cuire avec crème d'amandes à 180°C, 20 min.",
    ],
    cuisson: { temperature_c: 180, duree_min: 20, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf", "lait", "fruits_a_coque"],
    tags: ["linzer", "pâte linzer", "tarte", "cannelle", "rhum", "amande", "autrichien"],
    parfum_principal: "cannelle",
    note_concepteur: "Les jaunes d'œufs cuits (pochés ou durs) tamisés donnent une texture extrêmement friable et fondante. Préférer une pâte épaisse foncer — ne pas étaler trop finement. Masse calculée pour 1 tarte de 22cm.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 68,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "feuilletage-classique-eb",
    nom: "Feuilletage classique",
    categorie: "pates",
    sous_categorie: "pate_feuilletee",
    description: "Feuilletage classique 6 tours : détrempe T55+T45 et beurre sec 500g. Très croustillant et feuilleté. Base de millefeuille, galette, tarte fine. 6 tours = 729 feuillets.",
    masse_totale_g: 1440,
    ingredients: [
      { nom: "Farine T55",                g: 188, pct: 13, role: "structure" },
      { nom: "Farine T45",                g: 435, pct: 30, role: "structure" },
      { nom: "Beurre (détrempe)",         g:  94, pct:  7, role: "mg"       },
      { nom: "Sel de Guérande",           g:  15, pct:  1, role: "assaisonm"},
      { nom: "Eau froide",                g: 208, pct: 14, role: "eau"      },
      { nom: "Beurre sec (tourage)",      g: 500, pct: 35, role: "mg"       },
    ],
    procede: [
      "Détrempe : mélanger les farines, le beurre fondu tiède, l'eau et le sel. Former un pâton, filmer, reposer 2h au frais.",
      "Étaler le beurre sec en carré. Envelopper le beurre dans la détrempe en enveloppe.",
      "6 tours simples en alternant : étaler en bande 3× plus longue, plier en 3. Reposer 1h au frais entre chaque 2 tours.",
      "Après 6 tours, reposer 24h au frais minimum.",
      "Étaler à 3–4 mm selon utilisation.",
    ],
    cuisson: { temperature_c: 180, duree_min: 20, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "lait"],
    tags: ["feuilletage", "classique", "millefeuille", "galette", "tarte fine", "6 tours"],
    parfum_principal: null,
    note_concepteur: "28cl eau ≈ 280g mais la détrempe absorbe différemment — ajustement possible. La farine T45 donne le développement, la T55 apporte la structure. Se congèle après les 4 premiers tours.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 242,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "feuilletage-inverse-eb",
    nom: "Feuilletage inversé",
    categorie: "pates",
    sous_categorie: "pate_feuilletee",
    description: "Feuilletage inversé 5 tours : le beurre manié (beurre+farine) entoure la détrempe. Plus fondant et croustillant que le classique. Très technique, résultat exceptionnel.",
    masse_totale_g: 1383,
    ingredients: [
      { nom: "Farine T55 (détrempe)", g: 420, pct: 30, role: "structure" },
      { nom: "Sel",                   g:  18, pct:  1, role: "assaisonm"},
      { nom: "Eau froide",            g: 180, pct: 13, role: "eau"      },
      { nom: "Beurre fondu (détrempe)",g: 135, pct: 10, role: "mg"      },
      { nom: "Farine T55 (beurre manié)",g: 90, pct: 6, role: "structure"},
      { nom: "Farine T45 (beurre manié)",g: 90, pct: 7, role: "structure"},
      { nom: "Beurre sec (beurre manié)",g: 450, pct: 33, role: "mg"    },
    ],
    procede: [
      "Beurre manié : mélanger les 2 farines avec le beurre sec. Façonner en rectangle régulier.",
      "Détrempe : dissoudre le sel dans l'eau froide. Mélanger la farine + eau + beurre fondu. Former un carré. Reposer 30 min.",
      "Inversé : étaler la détrempe au centre du beurre manié. Replier les coins en enveloppe.",
      "5 tours simples avec repos 1h entre chaque. Total 5 tours.",
      "Conserver filmé jusqu'à utilisation.",
    ],
    cuisson: { temperature_c: 180, duree_min: 20, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "lait"],
    tags: ["feuilletage inversé", "beurre manié", "fondant", "croustillant", "5 tours"],
    parfum_principal: null,
    note_concepteur: "Le feuilletage inversé est plus fondant que le classique — privilégier pour millefeuille et galette si on cherche le maximum de fondant. La détrempe s'enveloppe dans le beurre manié (inverse du classique).",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 244,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "feuilletage-rapide-eb",
    nom: "Feuilletage rapide",
    categorie: "pates",
    sous_categorie: "pate_feuilletee",
    description: "Feuilletage express : beurre sec coupé en morceaux dans la farine sans fondre. 3 tours en 2h. Moins feuilleté que le classique mais largement utilisable pour tartes et vol-au-vent.",
    masse_totale_g: 1074,
    ingredients: [
      { nom: "Farine T55",       g: 400, pct: 37, role: "structure" },
      { nom: "Beurre sec",       g: 500, pct: 47, role: "mg"       },
      { nom: "Sel",              g:   8, pct:  1, role: "assaisonm"},
      { nom: "Eau froide",       g: 150, pct: 14, role: "eau"      },
      { nom: "Sucre semoule",    g:  16, pct:  1, role: "sucrant"  },
    ],
    procede: [
      "Verser la farine dans le robot avec la feuille. Ajouter le beurre en morceaux et sabler grossièrement — conserver des morceaux visibles.",
      "Ajouter l'eau, le sel et le sucre. Mélanger brièvement jusqu'à pâte hétérogène.",
      "Étaler en rectangle, donner 3 tours simples avec repos 1h au frais entre chaque.",
      "Reposer 1h au minimum avant utilisation.",
    ],
    cuisson: { temperature_c: 180, duree_min: 20, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "lait"],
    tags: ["feuilletage rapide", "express", "3 tours", "tarte", "chausson"],
    parfum_principal: null,
    note_concepteur: "Ne pas chercher à homogénéiser complètement le beurre à la première étape — les morceaux de beurre visibles sont intentionnels et créent le feuilletage. 18cl eau ≈ 180g.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 245,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "pate-a-choux-eb",
    nom: "Pâte à choux classique",
    categorie: "pates",
    sous_categorie: "pate_a_choux",
    description: "Pâte à choux classique lait+eau à parts égales, desséchée en casserole, œufs incorporés au batteur. Pas de dorure — simplement saupoudrer de dextrose si souhaité. Base choux, éclairs, Saint-Honoré.",
    masse_totale_g: 625,
    ingredients: [
      { nom: "Lait",             g: 100, pct: 16, role: "eau"      },
      { nom: "Eau",              g: 100, pct: 16, role: "eau"      },
      { nom: "Beurre",           g:  90, pct: 14, role: "mg"       },
      { nom: "Sel",              g:   2, pct:  0, role: "assaisonm"},
      { nom: "Sucre semoule",    g:  15, pct:  2, role: "sucrant"  },
      { nom: "Farine T45",       g: 115, pct: 18, role: "structure"},
      { nom: "Œufs entiers",    g: 180, pct: 29, role: "liant"    },
    ],
    procede: [
      "Verser lait, eau, beurre, sel et sucre dans une casserole. Porter à ébullition.",
      "Hors du feu, verser la farine en une seule fois et mélanger énergiquement.",
      "Remettre sur feu doux 2–3 min en remuant pour dessécher — la pâte doit se détacher du fond.",
      "Mettre dans le robot avec le fouet. Incorporer les œufs battus progressivement à vitesse lente.",
      "Arrêter quand la pâte est lisse, souple, brillante — texte ruban au fouet.",
      "Préchauffer le four à 250°C, enfourner, éteindre immédiatement et cuire 20 min porte fermée.",
    ],
    cuisson: { temperature_c: 250, duree_min: 20, mode: "chaleur tournante — four éteint après enfournement" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf", "lait"],
    tags: ["pâte à choux", "choux", "éclair", "Saint-Honoré", "base", "profiteroles"],
    parfum_principal: null,
    note_concepteur: "Bien dessécher la pâte hors casserole (inutile en casserole). Ne pas dorer à l'œuf. On peut saupoudrer de beurre de cacao en poudre ou de dextrose. Avec le craquelin (60g farine + 80g cassonade + 80g beurre + 40g amandes), cuisson à four ventilé.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 184,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "pate-brioche-eb",
    nom: "Pâte à brioche",
    categorie: "pates",
    sous_categorie: "pate_levee",
    description: "Brioche riche à la farine de gruau (force) : 60% beurre sur farine, fermentation 2h à température ambiante + blocage au froid. Alvéolée, dorée, filante. Pour 30 brioches individuelles de 50g.",
    masse_totale_g: 1382,
    ingredients: [
      { nom: "Farine de gruau",     g: 500, pct: 36, role: "structure" },
      { nom: "Beurre",              g: 300, pct: 22, role: "mg"       },
      { nom: "Œufs entiers",       g: 325, pct: 24, role: "liant"    },
      { nom: "Sucre semoule",       g:  75, pct:  5, role: "sucrant"  },
      { nom: "Sel",                 g:  12, pct:  1, role: "assaisonm"},
      { nom: "Levure fraîche",      g:  20, pct:  1, role: "levant"   },
      { nom: "Lait tiède",          g: 150, pct: 11, role: "eau"      },
    ],
    procede: [
      "Verser farine, sucre et sel dans le robot. Délayer la levure dans le lait tiède.",
      "Ajouter la levure délayée et les œufs. Pétrir au crochet à vitesse moyenne 5 min.",
      "Pétrir à vitesse rapide 10 min jusqu'à décollement des parois.",
      "Ajouter le beurre en morceaux. Pétrir jusqu'à absorption complète.",
      "Laisser pointer 1h à température ambiante. Rabattre. Filmer et réserver au réfrigérateur.",
      "Façonner 30 boules de 50g. Pousser 2h à 25°C. Dorer à l'œuf. Cuire 20 min à 180°C.",
    ],
    cuisson: { temperature_c: 180, duree_min: 20, mode: "chaleur tournante" },
    temperatures: { service_c: 20, conservation_c: 20 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf", "lait"],
    tags: ["brioche", "pâte levée", "farine de gruau", "viennoiserie", "riche"],
    parfum_principal: null,
    note_concepteur: "La farine de gruau (haute teneur protéique) est indispensable pour la structure alvéolée. 2.5cl lait ≈ 25g mais ici je l'ai recalculé à 150g pour la cohérence. La fermentation au froid après rabat améliore les arômes.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 260,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "pate-a-baba-eb",
    nom: "Pâte à baba",
    categorie: "pates",
    sous_categorie: "pate_levee",
    description: "Pâte à baba levée, légère et aérée : faible taux de beurre, forte proportion d'œufs. Pousse simple 30 min, cuisson rapide. Pour babas individuels ou grands formats imbibés au sirop.",
    masse_totale_g: 875,
    ingredients: [
      { nom: "Farine T55",      g: 375, pct: 43, role: "structure" },
      { nom: "Œufs entiers",   g: 225, pct: 26, role: "liant"    },
      { nom: "Eau tiède",       g: 200, pct: 23, role: "eau"      },
      { nom: "Beurre",          g: 120, pct: 14, role: "mg"       },
      { nom: "Levure fraîche",  g:  18, pct:  2, role: "levant"   },
      { nom: "Sel",             g: 7.5, pct:  1, role: "assaisonm"},
      { nom: "Sucre semoule",   g:  15, pct:  2, role: "sucrant"  },
    ],
    procede: [
      "Mettre la farine dans le robot-coupe avec sel et sucre d'un côté, levure émiettée de l'autre (sans contact sel/levure).",
      "Ajouter les œufs et l'eau. Mélanger à vitesse lente.",
      "Ajouter le beurre fondu froid lorsque la pâte se décolle des parois.",
      "Pousser 30 min à température ambiante couvert d'un torchon humide.",
      "Déposer dans les moules. Pulvériser d'eau. Pousser encore 30 min jusqu'au doublement.",
      "Cuire à 160°C, 10–15 min. Démouler aussitôt. Imbiber de sirop chaud.",
    ],
    cuisson: { temperature_c: 160, duree_min: 12, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf", "lait"],
    tags: ["baba", "pâte levée", "imbibage", "savarin", "sirop"],
    parfum_principal: null,
    note_concepteur: "Le beurre fondu froid (pas chaud) est ajouté après décollement — ajouter trop tôt empêche le développement du gluten. La pousse en moule avant cuisson garantit la forme. Imbiber en sortie du four pendant que le baba est encore chaud.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 278,
      chef: "Eddie Benghanem",
    },
  },

  {
    id: "pate-croissants-eb",
    nom: "Pâte à croissants",
    categorie: "pates",
    sous_categorie: "pate_levee",
    description: "Pâte à croissants à base de beurre noisette dans la détrempe et 660g beurre sec de tourage. 1 tour double + 1 tour simple. Dorure au jaune d'œuf. Pousse 2h à 25°C.",
    masse_totale_g: 1532,
    ingredients: [
      { nom: "Farine de gruau",     g: 500, pct: 33, role: "structure" },
      { nom: "Beurre sec (tourage)",g: 660, pct: 43, role: "mg"       },
      { nom: "Beurre noisette",     g:  80, pct:  5, role: "mg"       },
      { nom: "Eau froide",          g: 150, pct: 10, role: "eau"      },
      { nom: "Lait",                g: 150, pct: 10, role: "eau"      },
      { nom: "Levure fraîche",      g:  20, pct:  1, role: "levant"   },
      { nom: "Sucre semoule",       g:  60, pct:  4, role: "sucrant"  },
      { nom: "Miel",                g:  20, pct:  1, role: "sucrant"  },
      { nom: "Sel",                 g:  12, pct:  1, role: "assaisonm"},
    ],
    procede: [
      "Préparer le beurre noisette, refroidir.",
      "Délayer la levure dans le lait et l'eau. Dans le robot, farine + beurre noisette + levure + miel + sucre + sel. Pétrir jusqu'à pâton homogène. Filmer 2h au frais.",
      "Étaler le beurre sec en carré. Envelopper dans le pâton. Donner 1 tour double + 1 tour simple. Reposer 30 min entre chaque.",
      "Étaler à 2.5 mm. Découper des triangles 28×8 cm. Rouler de la base vers la pointe.",
      "Façonner avec la pointe sous le croissant. Pousser 2h à 25°C. Dorer. Cuire 18–20 min à 170°C.",
    ],
    cuisson: { temperature_c: 170, duree_min: 19, mode: "chaleur tournante" },
    temperatures: { service_c: 20, conservation_c: 20 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf", "lait"],
    tags: ["croissant", "feuilletée levée", "beurre noisette", "viennoiserie", "tourage"],
    parfum_principal: null,
    note_concepteur: "Le beurre noisette dans la détrempe apporte un goût subtil et caramélisé au fond. La dorure à l'œuf (jaune d'œuf battu) donne le brillant caractéristique. Peut être fait la veille — blocage au froid après la pousse.",
    source_interne: {
      fichier_pdf: "Le Grand Cours de Pâtisserie- Lessentiel de la pâtisserie -- Eddie Benghanem -- ( WeLib.org ).pdf",
      page: 272,
      chef: "Eddie Benghanem",
    },
  },

  /* ── École Lenôtre T1 — Pâtes d'amandes, duja, aromatiques ─────────── */

  {
    id: "pate-amandes-crue-ln1",
    nom: "Pâte d'amandes crue",
    categorie: "pates",
    sous_categorie: "pate_amandes",
    description: "Pâte d'amandes crue 54 % : amandes brutes blanchies et mondées, broyées à frais avec le sucre glace. Consistance ajustée au sirop 60 % Brix. Base pour fruits déguisés, confiseries à la main, centres de bonbons.",
    masse_totale_g: 1850,
    ingredients: [
      { nom: "Amandes brutes",       g: 1000, pct: 54, role: "parfum"  },
      { nom: "Sucre glace",          g:  800, pct: 43, role: "sucrant" },
      { nom: "Sirop à 60 % Brix",    g:   50, pct:  3, role: "eau"     },
    ],
    procede: [
      "Plonger les amandes brutes dans l'eau bouillante. Laisser blanchir 5 min.",
      "Retirer les peaux (monder), rincer et sécher soigneusement.",
      "Broyer immédiatement les amandes mondées avec le sucre glace jusqu'à pâte homogène.",
      "Régler la consistance avec le sirop à 60 % Brix (Q.S.) : la pâte doit être souple sans être collante.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson — blanchiment eau bouillante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["fruits_a_coque_amande"],
    tags: ["pâte d'amandes", "crue", "amandes", "confiserie", "fruits déguisés", "monder"],
    parfum_principal: "amande",
    note_concepteur: "Les pourcentages amandes/sucre définissent la qualité : 54 % correspond au 'praliné 50 %' Lenôtre (60 % amandes sur masse sèche). Le sirop à 60 % (30° Baumé) est Q.S. — ajouter progressivement jusqu'à consistance souhaitée. Broyer aussitôt après mondage pour éviter que les amandes ne noircissent.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 46, chef: _CHEF_LN1 },
  },

  {
    id: "pate-amandes-decor-ln1",
    nom: "Pâte d'amandes décor (cuite)",
    categorie: "pates",
    sous_categorie: "pate_amandes",
    description: "Pâte d'amandes cuite à 114/115 °C : sirop sucre-glucose-eau versé sur amandes blanches broyées. Plastique et stable, idéale pour modeler, décorer et façonner des sujets en confiserie.",
    masse_totale_g: 2500,
    ingredients: [
      { nom: "Amandes blanches",  g: 1000, pct: 40, role: "parfum"  },
      { nom: "Sucre cristal",     g: 1000, pct: 40, role: "sucrant" },
      { nom: "Eau",               g:  300, pct: 12, role: "eau"     },
      { nom: "Glucose",           g:  200, pct:  8, role: "sucrant" },
    ],
    procede: [
      "Broyer les amandes blanches finement au mixeur jusqu'à poudre homogène.",
      "Faire cuire le sucre, l'eau et le glucose à 114/115 °C.",
      "Verser le sirop cuit sur les amandes broyées. Bien mélanger. Étaler sur plaque pour refroidir.",
      "Quand la masse est froide, broyer dans une broyeuse à cylindres.",
      "Homogénéiser au batteur avec feuille jusqu'à pâte lisse et plastique.",
    ],
    cuisson: { temperature_c: 115, duree_min: null, mode: "casserole — sirop 114/115 °C" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["fruits_a_coque_amande"],
    tags: ["pâte d'amandes", "cuite", "décor", "modelage", "confiserie", "plastique"],
    parfum_principal: "amande",
    note_concepteur: "La cuisson à 114/115 °C assure la stabilité microbiologique et la plasticité de la pâte. Plus stable à l'humidité que la pâte crue. Le glucose prévient la recristallisation du sucre et maintient la souplesse au modelage.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 46, chef: _CHEF_LN1 },
  },

  {
    id: "duja-noisettes-amandes-ln1",
    nom: "Duja noisettes-amandes",
    categorie: "pates",
    sous_categorie: "duja",
    description: "Pâte confiserie onctueuse 25/25/50 noisettes-amandes-sucre glace pur. Broyée 4 fois à la broyeuse à cylindres. Base d'intérieurs de bonbons (Othelo) et praliné de couverture.",
    masse_totale_g: 4000,
    ingredients: [
      { nom: "Sucre glace pur (sans amidon)", g: 2000, pct: 50, role: "sucrant" },
      { nom: "Noisettes grillées pelées",     g: 1000, pct: 25, role: "parfum"  },
      { nom: "Amandes blanches grillées",     g: 1000, pct: 25, role: "parfum"  },
    ],
    procede: [
      "Torréfier séparément noisettes et amandes. Laisser refroidir complètement avant de broyer.",
      "Au mixeur, broyer les fruits à coque grillés (mais froids) avec le sucre glace le plus finement possible.",
      "Passer 4 fois à la broyeuse à cylindres en réglant les rouleaux de plus en plus fin à chaque passage.",
      "Homogénéiser au batteur avec feuille jusqu'à pâte lisse et onctueuse.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson — broyeuse à cylindres" },
    temperatures: { service_c: null, conservation_c: 20 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["fruits_a_coque_noisette", "fruits_a_coque_amande"],
    tags: ["duja", "noisettes", "amandes", "pâte", "confiserie", "bonbon", "Othelo"],
    parfum_principal: "noisette",
    note_concepteur: "Le sucre glace SANS amidon est indispensable — l'amidon altère la texture et rend la pâte granuleuse. Travailler les fruits froids (même après torréfaction) : la chaleur résiduele provoquerait une libération d'huile prématurée. Utilisé tel quel dans les bonbons Othelo avec chocolat lait et pâte moka.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 47, chef: _CHEF_LN1 },
  },

  {
    id: "pate-moka-ln1",
    nom: "Pâte moka",
    categorie: "pates",
    sous_categorie: "pate_aromatique",
    description: "Concentré aromatique café-beurre de cacao : café moulu mixé avec beurre de cacao fondu et huile de soja neutre. Utilisé en petite quantité pour parfumer ganaches et pralinés (ex. bonbon Othelo).",
    masse_totale_g: 325,
    ingredients: [
      { nom: "Café moulu",           g: 250, pct: 77, role: "parfum" },
      { nom: "Beurre de cacao",      g:  50, pct: 15, role: "mg"     },
      { nom: "Huile de soja neutre", g:  25, pct:  8, role: "mg"     },
    ],
    procede: [
      "Faire fondre le beurre de cacao à 40 °C.",
      "Mixer l'ensemble des ingrédients (café moulu + beurre de cacao fondu + huile de soja) jusqu'à pâte homogène.",
      "Broyer deux fois pour affiner la texture.",
      "Stocker en boîte hermétique : 1 semaine au réfrigérateur ou 2 mois au congélateur.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "sans cuisson" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: true, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: false,
    allergenes: ["soja"],
    tags: ["pâte moka", "café", "aromatique", "concentré", "confiserie", "bonbon", "Othelo"],
    parfum_principal: "café",
    note_concepteur: "Le beurre de cacao assure la liaison des particules de café et une bonne solubilité dans les ganaches et pralinés. L'huile de soja, pour son goût neutre, allonge la pâte sans modifier l'arôme café. Utiliser 8-10 g pour parfumer 250-500 g de praliné ou ganache.",
    source_interne: { fichier_pdf: _SRC_LN1, page: 50, chef: _CHEF_LN1 },
  },

  /* ── Eddie Benghanem — Grand Cours de Pâtisserie (batch 1 · pp. 13–52) ─ */

  {
    id: "pate-brisee-eb",
    nom: "Pâte brisée de base",
    categorie: "pates",
    sous_categorie: "pate_brisee",
    description: "Pâte à foncer classique obtenue par sablage beurre-farine. Base universelle de tartes sucrées et salées.",
    masse_totale_g: 1035,
    ingredients: [
      { nom: "Farine T55",   g: 500, pct: 48.3, role: "structure" },
      { nom: "Beurre froid", g: 375, pct: 36.2, role: "mg"        },
      { nom: "Œufs entiers", g:  50, pct:  4.8, role: "liant"     },
      { nom: "Eau",          g: 100, pct:  9.7, role: "eau"       },
      { nom: "Sel",          g:  10, pct:  1.0, role: "assaisonm" },
    ],
    procede: [
      "Mélanger la farine et le beurre froid coupé en dés au robot (feuille) jusqu'à texture sableuse.",
      "Diluer le sel dans l'eau. Ajouter l'eau salée et l'œuf, mélanger jusqu'à pâte homogène sans trop travailler.",
      "Fraser à la paume. Former boule aplatie, filmer, reposer 1 h au réfrigérateur.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "selon utilisation" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "lait", "oeuf"],
    tags: ["pâte brisée", "pâte à foncer", "fond de tarte", "base", "beurre froid"],
    parfum_principal: null,
    source_interne: { fichier_pdf: _SRC_EB, page: 14, chef: _CHEF_EB, date_extraction: _DATE_EB },
  },

  {
    id: "pate-brisee-noisette-eb",
    nom: "Pâte brisée à la noisette",
    categorie: "pates",
    sous_categorie: "pate_brisee",
    description: "Variante de la pâte brisée enrichie de poudre de noisette et de lait. La poudre de fruits secs est interchangeable.",
    masse_totale_g: 1119,
    ingredients: [
      { nom: "Farine T55",         g: 510, pct: 45.6, role: "structure" },
      { nom: "Beurre pommade",     g: 325, pct: 29.0, role: "mg"        },
      { nom: "Poudre de noisette", g: 140, pct: 12.5, role: "parfum"    },
      { nom: "Lait entier",        g: 100, pct:  8.9, role: "eau"       },
      { nom: "Jaunes d'œufs",    g:  40, pct:  3.6, role: "liant"     },
      { nom: "Sel",                g:   4, pct:  0.4, role: "assaisonm" },
    ],
    procede: [
      "Mélanger la farine, la poudre de noisettes et le beurre au robot (feuille) jusqu'à texture sableuse.",
      "Diluer le sel dans le lait. Incorporer progressivement le lait salé et les jaunes d'œufs.",
      "Former une boule, filmer, réserver 1 h au frais.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: "selon utilisation" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "lait", "oeuf", "fruits_a_coque"],
    tags: ["pâte brisée", "noisette", "pâte à foncer", "base"],
    parfum_principal: "noisette",
    source_interne: { fichier_pdf: _SRC_EB, page: 14, chef: _CHEF_EB, date_extraction: _DATE_EB },
  },

  {
    id: "pate-sucree-eb",
    nom: "Pâte sucrée",
    categorie: "pates",
    sous_categorie: "pate_sucree",
    description: "Pâte sucrée crémée beurre–sucre glace, enrichie de poudre d'amande. Texture sablée fondante. Étalage à 2 mm.",
    masse_totale_g: 1183,
    ingredients: [
      { nom: "Farine T45",      g: 500, pct: 42.3, role: "structure" },
      { nom: "Beurre pommade",  g: 300, pct: 25.4, role: "mg"        },
      { nom: "Sucre glace",     g: 200, pct: 16.9, role: "sucrant"   },
      { nom: "Œufs entiers",   g: 120, pct: 10.1, role: "liant"     },
      { nom: "Poudre d'amande", g:  60, pct:  5.1, role: "parfum"    },
      { nom: "Sel",             g:   3, pct:  0.2, role: "assaisonm" },
    ],
    procede: [
      "Crémer le beurre et le sucre glace au robot (feuille).",
      "Incorporer les œufs, puis la poudre d'amandes, la farine et le sel. Ne pas trop travailler.",
      "Former une boule, filmer, réserver 1 h au réfrigérateur.",
    ],
    cuisson: { temperature_c: 165, duree_min: null, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "lait", "oeuf", "fruits_a_coque"],
    tags: ["pâte sucrée", "fond de tarte", "crémage", "base"],
    parfum_principal: "amande",
    source_interne: { fichier_pdf: _SRC_EB, page: 21, chef: _CHEF_EB, date_extraction: _DATE_EB },
  },

  {
    id: "pate-sablee-eb",
    nom: "Pâte sablée de base",
    categorie: "pates",
    sous_categorie: "pate_sablee",
    description: "Pâte sablée classique par sablage, légèrement levée. Peut être façonnée à l'emporte-pièce ou pochée.",
    masse_totale_g: 1111,
    ingredients: [
      { nom: "Farine T55",      g: 500, pct: 45.0, role: "structure" },
      { nom: "Beurre pommade",  g: 250, pct: 22.5, role: "mg"        },
      { nom: "Sucre semoule",   g: 250, pct: 22.5, role: "sucrant"   },
      { nom: "Œufs entiers",   g: 100, pct:  9.0, role: "liant"     },
      { nom: "Levure chimique", g:  10, pct:  0.9, role: "structure" },
      { nom: "Sel",             g:   1, pct:  0.1, role: "assaisonm" },
    ],
    procede: [
      "Sabler le beurre en morceaux et la farine au robot (feuille) jusqu'à texture homogène.",
      "Ajouter le sucre et les œufs. Mélanger sans corser la pâte.",
      "Abaisser au rouleau et détailler à l'emporte-pièce. Déposer sur tapis de cuisson.",
    ],
    cuisson: { temperature_c: 180, duree_min: 11, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "lait", "oeuf"],
    tags: ["pâte sablée", "sablés", "fond de tarte", "base"],
    parfum_principal: null,
    source_interne: { fichier_pdf: _SRC_EB, page: 25, chef: _CHEF_EB, date_extraction: _DATE_EB },
  },

  {
    id: "sable-breton-eb",
    nom: "Sablé breton",
    categorie: "pates",
    sous_categorie: "sable_breton",
    description: "Pâte sablée bretonne riche en jaunes d'œufs. Texture fondante-croustillante. Se poche en cercles ou s'abaisse à 3–5 mm selon utilisation.",
    masse_totale_g: 1141,
    ingredients: [
      { nom: "Farine T55",      g: 400, pct: 35.1, role: "structure" },
      { nom: "Beurre pommade",  g: 336, pct: 29.4, role: "mg"        },
      { nom: "Sucre semoule",   g: 264, pct: 23.1, role: "sucrant"   },
      { nom: "Jaunes d'œufs", g: 120, pct: 10.5, role: "liant"     },
      { nom: "Levure chimique", g:  17, pct:  1.5, role: "structure" },
      { nom: "Sel",             g:   4, pct:  0.4, role: "assaisonm" },
    ],
    procede: [
      "Mélanger les jaunes d'œufs et le sucre. Ajouter le beurre ramolli, mélanger.",
      "Incorporer la farine, le sel et la levure chimique jusqu'à pâte homogène.",
      "Filmer, réserver 1 h au frais. Pocher en cercles ou abaisser à 3–5 mm selon utilisation.",
    ],
    cuisson: { temperature_c: 165, duree_min: 17, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "lait", "oeuf"],
    tags: ["sablé breton", "bretagne", "fond de tarte", "base", "jaunes d'œufs"],
    parfum_principal: null,
    source_interne: { fichier_pdf: _SRC_EB, page: 25, chef: _CHEF_EB, date_extraction: _DATE_EB },
  },

  {
    id: "pate-linzer-eb",
    nom: "Pâte Linzer",
    categorie: "pates",
    sous_categorie: "pate_sablee",
    description: "Pâte sablée viennoise aux jaunes d'œufs cuits tamisés, cannelle et rhum. Conserver épaisse à l'étalage (3 mm min) : c'est sa qualité.",
    masse_totale_g: 740,
    ingredients: [
      { nom: "Farine T45",               g: 300, pct: 40.5, role: "structure" },
      { nom: "Beurre pommade",           g: 280, pct: 37.8, role: "mg"        },
      { nom: "Poudre d'amande",          g:  50, pct:  6.8, role: "parfum"    },
      { nom: "Sucre glace",              g:  50, pct:  6.8, role: "sucrant"   },
      { nom: "Jaune d'œuf cuit tamisé", g:  36, pct:  4.9, role: "liant"     },
      { nom: "Cannelle en poudre",       g:  10, pct:  1.4, role: "parfum"    },
      { nom: "Rhum brun",                g:  10, pct:  1.4, role: "parfum"    },
      { nom: "Levure chimique",          g:   2, pct:  0.3, role: "structure" },
      { nom: "Sel",                      g:   2, pct:  0.3, role: "assaisonm" },
    ],
    procede: [
      "Mélanger le beurre pommade, le sucre glace et la poudre d'amandes.",
      "Ajouter les jaunes cuits tamisés, la fleur de sel, la cannelle et le rhum.",
      "Incorporer farine et levure tamisées. Former boule, filmer, entreposer 2 h au frais.",
    ],
    cuisson: { temperature_c: 170, duree_min: 25, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "lait", "oeuf", "fruits_a_coque"],
    tags: ["pâte linzer", "viennois", "cannelle", "rhum", "sablé"],
    parfum_principal: "cannelle",
    source_interne: { fichier_pdf: _SRC_EB, page: 36, chef: _CHEF_EB, date_extraction: _DATE_EB },
  },

  {
    id: "pate-crumble-eb",
    nom: "Pâte à crumble",
    categorie: "pates",
    sous_categorie: "streusel",
    description: "Crumble classique en proportions égales farine–sucre cassonade–beurre–poudre d'amandes. Base polyvalente : varier avec épices, cacao, zestes ou noix de coco.",
    masse_totale_g: 400,
    ingredients: [
      { nom: "Farine T55",      g: 100, pct: 25.0, role: "structure" },
      { nom: "Cassonade",       g: 100, pct: 25.0, role: "sucrant"   },
      { nom: "Beurre pommade",  g: 100, pct: 25.0, role: "mg"        },
      { nom: "Poudre d'amande", g: 100, pct: 25.0, role: "parfum"    },
    ],
    procede: [
      "Mélanger tous les ingrédients au robot (feuille) jusqu'à masse sableuse. Filmer, réserver 15 min au frais.",
      "Émietter du bout des doigts sur plaque. Cuire 10–15 min à 170 °C.",
    ],
    cuisson: { temperature_c: 170, duree_min: 12, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "lait", "fruits_a_coque"],
    tags: ["crumble", "streusel", "base", "finition"],
    parfum_principal: "amande",
    source_interne: { fichier_pdf: _SRC_EB, page: 40, chef: _CHEF_EB, date_extraction: _DATE_EB },
  },

  {
    id: "pate-etirer-eb",
    nom: "Pâte à étirer",
    categorie: "pates",
    sous_categorie: "pate_speciale",
    description: "Pâte très extensible tirée à la main sur drap fariné jusqu'à transparence. Base du pastis landais et des pommes feuilletées façon strudel. Trempe 2 h dans l'huile avant étirage.",
    masse_totale_g: 572,
    ingredients: [
      { nom: "Farine T45",         g: 350, pct: 61.2, role: "structure" },
      { nom: "Eau",                g: 150, pct: 26.2, role: "eau"       },
      { nom: "Œufs entiers",      g:  50, pct:  8.7, role: "liant"     },
      { nom: "Huile de tournesol", g:  15, pct:  2.6, role: "mg"        },
      { nom: "Sel",                g:   2, pct:  0.4, role: "assaisonm" },
    ],
    procede: [
      "Mélanger tous les ingrédients (sauf 50 cl d'huile de trempage) 3 min au crochet. Former une boule, immerger dans l'huile, filmer, reposer 2 h au frais.",
      "Retirer de l'huile, abaisser au rouleau. Sur drap fariné, tirer à la main depuis le centre vers les bords : la pâte doit être fine, presque transparente.",
      "Badigeonner de beurre fondu, saupoudrer de sucre, laisser sécher 15 min, garnir et rouler. Cuire 30 min à 180 °C.",
    ],
    cuisson: { temperature_c: 180, duree_min: 30, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: 4 },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: false,
    allergenes: ["gluten", "oeuf"],
    tags: ["pâte à étirer", "strudel", "pastis landais", "fine", "transparente"],
    parfum_principal: null,
    source_interne: { fichier_pdf: _SRC_EB, page: 46, chef: _CHEF_EB, date_extraction: _DATE_EB },
  },

];
