export const RECETTES_SIROPS = [
  // === Import extraction-2026-08-12 (23 recettes) ===
  {
    id: "sirop-neutre",
    nom: "Sirop neutre",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop neutre — recette importée, à vérifier.",
    masse_totale_g: 600,
    ingredients: [
      { nom: "eau", g: 370.0, pct: 61.7, role: "eau" },
      { nom: "sucre", g: 230.0, pct: 38.3, role: "sucrant" },
    ],
    procede: [
      "Porter les ingrédients à ébullition, réserver au frais",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Bûche Monticola.docx", import: "extraction-2026-08-12" },
  },
  {
    id: "sirop-de-punchage",
    nom: "Sirop de punchage",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop de punchage — recette importée, à vérifier.",
    masse_totale_g: 150,
    ingredients: [
      { nom: "eau", g: 100.0, pct: 66.7, role: "eau" },
      { nom: "sucre", g: 40.0, pct: 26.7, role: "sucrant" },
      { nom: "rhum", g: 10.0, pct: 6.7, role: "parfum" },
    ],
    procede: [
      "Faire bouillir l’eau, le sucre, rajouter le rhum hors du feu.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Bûche prestige.docx", import: "extraction-2026-08-12" },
  },
  {
    id: "sirop-citron",
    nom: "Sirop citron",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop citron — recette importée, à vérifier.",
    masse_totale_g: 554,
    ingredients: [
      { nom: "jus de citron", g: 120.0, pct: 21.7, role: "acidite" },
      { nom: "sucre", g: 80.0, pct: 14.4, role: "sucrant" },
      { nom: "sucre", g: 100.0, pct: 18.1, role: "sucrant" },
      { nom: "jus de citron vert", g: 200.0, pct: 36.1, role: "acidite" },
      { nom: "pectine NH", g: 8.0, pct: 1.4, role: "gelifiant" },
      { nom: "huile d'olive", g: 40.0, pct: 7.2, role: "mg" },
      { nom: "basilic", g: 6.0, pct: 1.1, role: "parfum" },
    ],
    procede: [
      "Porter le tout à ébullition",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "citron"],
    parfum_principal: "citron",
    note_concepteur: "",
    source_interne: { fichier: "Bûche roulé citron.docx", import: "extraction-2026-08-12" },
  },
  {
    id: "sirop-cafe",
    nom: "Sirop café",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop café — recette importée, à vérifier.",
    masse_totale_g: 500,
    ingredients: [
      { nom: "expresso", g: 440.0, pct: 88.0, role: "parfum" },
      { nom: "sucre semoule", g: 60.0, pct: 12.0, role: "sucrant" },
    ],
    procede: [
      "Réaliser un sirop et réserver.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "café"],
    parfum_principal: "café",
    note_concepteur: "",
    source_interne: { fichier: "Bûche tiramisu.docx", import: "extraction-2026-08-12" },
  },
  {
    id: "imbibage-raisins",
    nom: "Imbibage raisins",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Imbibage raisins — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Raisin", g: 476.2, pct: 47.6, role: "parfum" },
      { nom: "Eau", g: 476.2, pct: 47.6, role: "eau" },
      { nom: "Rhum", g: 47.6, pct: 4.8, role: "parfum" },
    ],
    procede: [
      "Mélanger l'eau et le rhum.",
      "Tremper les raisins dans le mélange au moins 24h avant utilisation.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "Kougloff"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Imbibage raisins.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "imbibage-cacao",
    nom: "Imbibage cacao",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Imbibage cacao — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Cacao poudre", g: 86.8, pct: 8.7, role: "parfum" },
      { nom: "Eau", g: 288.8, pct: 28.9, role: "eau" },
      { nom: "Sirop à 30°", g: 579.3, pct: 57.9, role: "sucrant" },
      { nom: "Gélatine poudre", g: 1.7, pct: 0.2, role: "gelifiant" },
      { nom: "Eau", g: 43.4, pct: 4.3, role: "eau" },
    ],
    procede: [
      "Mélanger la petite quantité d'eau avec la gélatine poudre.Laisser gonfler.",
      "Faire chauffer l'eau, le sirop puis ajouter le cacao poudre.",
      "Ajouter la gélatine dans le mélange chaud, mélanger.",
      "Bûche carrémenchoc :",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "Carrémenchoc", "Bûche carrémenchoc", "Carrémenchoc dessert à l'assiette 1"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Imbibage cacao..xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "imbibage-rhum",
    nom: "Imbibage rhum",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Imbibage rhum — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Rhum blanc", g: 349.0, pct: 34.9, role: "parfum" },
      { nom: "Sirop à 30°", g: 651.0, pct: 65.1, role: "sucrant" },
    ],
    procede: [
      "Mélanger les deux ingrédients.",
      "Mix all a ingredients",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "La pink"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Imbibage rhum .xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "imbibation-whisky",
    nom: "Imbibation whisky",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Imbibation whisky — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Whisky", g: 301.5, pct: 30.2, role: "parfum" },
      { nom: "Gélatine poudre", g: 15.7, pct: 1.6, role: "gelifiant" },
      { nom: "Eau", g: 78.5, pct: 7.8, role: "eau" },
      { nom: "Sirop à 30°", g: 604.3, pct: 60.4, role: "sucrant" },
    ],
    procede: [
      "Melanger l'eau et la gélatine a froid",
      "Laisser gonfler ce mélange pendant 30 min",
      "Mettre le sirop et le whisky à chauffer",
      "Incorporer la gelatine au sirop",
      "Chauffer à 50°C",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "Bûche marron myrtille"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Imbibation Whisky.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "punch-abricot-romarin",
    nom: "Punch abricot romarin",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Punch abricot romarin — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Purée d'abricot romarin", g: 446.8, pct: 44.7, role: "assaisonnement" },
      { nom: "Sirop à 30°", g: 212.8, pct: 21.3, role: "sucrant" },
      { nom: "Eau 1", g: 202.1, pct: 20.2, role: "eau" },
      { nom: "Jus de citron", g: 26.6, pct: 2.7, role: "acidite" },
      { nom: "Eau 2", g: 95.7, pct: 9.6, role: "eau" },
      { nom: "Gélatine poudre", g: 16.0, pct: 1.6, role: "gelifiant" },
    ],
    procede: [
      "Mélanger l'eau 2 froide avec la gélatine poudre, laisser gonfler 20mn.",
      "Mélanger l'eau 1, le sirop, la purée et le jus.",
      "Prélever une petite partie, chauffer et ajouter le mélange gélatine.",
      "Ajouter ensuite tous les ingrédients.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "citron", "1000 fruits abricot romarin"],
    parfum_principal: "citron",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Punch abricot romarin.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "punch-fraise-1",
    nom: "Punch fraise 1",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Punch fraise 1 — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Purée de fraise", g: 514.3, pct: 51.4, role: "eau" },
      { nom: "Sirop à 30°", g: 228.6, pct: 22.9, role: "sucrant" },
      { nom: "Eau", g: 217.1, pct: 21.7, role: "eau" },
      { nom: "Gélatine feuille", g: 17.1, pct: 1.7, role: "gelifiant" },
      { nom: "Gourmandise fraise", g: 22.9, pct: 2.3, role: "parfum" },
    ],
    procede: [
      "Mettre la gélatine à fondre dans l'eau froide pendant au moins 20 minutes.",
      "Mélanger l'eau, le sirop à 30°, faire bouillir.",
      "Ajouter la gélatine.",
      "Verser le tout sur la purée de fraise fondue.",
      "Finir par la gourmandise fraise.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "fraise", "Le White", "Tiramisu fraise verre/verrine"],
    parfum_principal: "fraise",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Punch fraise 1.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "punch-fraise-des-bois",
    nom: "Punch fraise des Bois",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Punch fraise des Bois — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Purée de fraise des Bois", g: 386.1, pct: 38.6, role: "eau" },
      { nom: "Sirop à 30°", g: 257.1, pct: 25.7, role: "sucrant" },
      { nom: "Eau 1", g: 192.5, pct: 19.3, role: "eau" },
      { nom: "Jus de citron", g: 30.2, pct: 3.0, role: "acidite" },
      { nom: "Eau 2", g: 87.7, pct: 8.8, role: "eau" },
      { nom: "Gélatine poudre", g: 17.1, pct: 1.7, role: "gelifiant" },
      { nom: "Gourmandise fraise", g: 29.2, pct: 2.9, role: "parfum" },
    ],
    procede: [
      "Mélanger l'eau 2 froide avec la gélatine poudre, laisser gonfler 20mn.",
      "Mélanger l'eau 1, le sirop, le jus de citron, la gourmandise.",
      "Prélever une petite partie de la purée de fraise des bois et ajouter le mélange gélatine.",
      "Ajouter ensuite tous les ingrédients.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "citron", "Côté Jardin", "Tiramisu fraise"],
    parfum_principal: "citron",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Punch fraise des bois.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "punch-fraise",
    nom: "Punch fraise",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Punch fraise — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Purée de fraise", g: 386.1, pct: 38.6, role: "eau" },
      { nom: "Sirop à 30°", g: 257.1, pct: 25.7, role: "sucrant" },
      { nom: "Eau 1", g: 192.5, pct: 19.3, role: "eau" },
      { nom: "Jus de citron", g: 30.2, pct: 3.0, role: "acidite" },
      { nom: "Eau 2", g: 87.7, pct: 8.8, role: "eau" },
      { nom: "Gélatine poudre", g: 17.1, pct: 1.7, role: "gelifiant" },
      { nom: "Gourmandise fraise", g: 29.2, pct: 2.9, role: "parfum" },
    ],
    procede: [
      "Mélanger l'eau 2 froide avec la gélatine poudre, laisser gonfler 20mn.",
      "Mélanger l'eau 1, le sirop, le jus de citron, la gourmandise.",
      "Prélever une petite partie de la purée de fraise et ajouter le mélange gélatine.",
      "Ajouter ensuite tous les ingrédients.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "citron", "Carré de fruits fraise coquelicot"],
    parfum_principal: "citron",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Punch fraise.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "punch-framboise-groseilles",
    nom: "Punch framboise groseilles",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Punch framboise groseilles — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Purée de framboise", g: 324.2, pct: 32.4, role: "eau" },
      { nom: "Sirop à 30°", g: 253.3, pct: 25.3, role: "sucrant" },
      { nom: "Eau 1", g: 192.5, pct: 19.2, role: "eau" },
      { nom: "Purée de groseilles", g: 101.3, pct: 10.1, role: "eau" },
      { nom: "Eau 2", g: 88.1, pct: 8.8, role: "eau" },
      { nom: "Gélatine poudre", g: 15.2, pct: 1.5, role: "gelifiant" },
      { nom: "Gourmandise framboise", g: 25.3, pct: 2.5, role: "parfum" },
    ],
    procede: [
      "Mélanger l'eau 2 froide avec la gélatine poudre, laisser gonfler 20mn.",
      "Mélanger l'eau 1, le sirop, les purées, la gourmandise.",
      "Prélever une petite partie et ajouter le mélange gélatine.",
      "Ajouter ensuite tous les ingrédients.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "framboise", "1000 fruits framboise groseilles"],
    parfum_principal: "framboise",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Punch framboise groseilles.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "sirop-bostock-citron",
    nom: "Sirop bostock citron",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop bostock citron — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Sucre semoule", g: 513.8, pct: 51.4, role: "sucrant" },
      { nom: "Huile essentiel citron", g: 18.3, pct: 1.8, role: "mg" },
      { nom: "Eau", g: 367.0, pct: 36.7, role: "eau" },
      { nom: "Sucre glace", g: 50.4, pct: 5.0, role: "sucrant" },
      { nom: "Poudre d'amande", g: 50.4, pct: 5.0, role: "structure" },
    ],
    procede: [
      "Faire un sirop avec l'eau et les sucres;a froid rajouter la poudre d'amande et l'huile essentiel",
      "reserver au frigo",
      "Make a sirup with the water and sugar.",
      "When it's cold, add a almond powder and oil lemon flavour.",
      "To cool in the fridge.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["fruits_a_coque"],
    tags: ["sirop", "amande", "Mini bostock citron"],
    parfum_principal: "amande",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Sirop bostock citron.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "sirop-bostock-framboise",
    nom: "Sirop bostock framboise",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop bostock framboise — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Sucre semoule", g: 504.5, pct: 50.5, role: "sucrant" },
      { nom: "Sucre glace", g: 49.5, pct: 5.0, role: "sucrant" },
      { nom: "Eau", g: 360.4, pct: 36.0, role: "eau" },
      { nom: "Poudre d amande", g: 49.5, pct: 5.0, role: "structure" },
      { nom: "Arome framboise", g: 36.0, pct: 3.6, role: "parfum" },
    ],
    procede: [
      "Faire un sirop avec l'eau et les sucres",
      "A froid rajouter la poudre d'amande et l'arôme famboise",
      "Réserver au frigo",
      "Make a sirup with water ans sugar",
      "When it's cold, add a almond powder ans raspberry flavour.",
      "To cool in the fridge",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["fruits_a_coque"],
    tags: ["sirop", "amande", "Mini bostock framboise"],
    parfum_principal: "amande",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Sirop bostock framboise.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "sirop-bostock-grand-marnier",
    nom: "Sirop bostock grand marnier",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop bostock grand marnier — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Sucre semoule", g: 504.5, pct: 50.5, role: "sucrant" },
      { nom: "Sucre glace", g: 49.5, pct: 5.0, role: "sucrant" },
      { nom: "Eau", g: 360.4, pct: 36.0, role: "eau" },
      { nom: "Poudre d amande", g: 49.5, pct: 5.0, role: "structure" },
      { nom: "Grand marnier", g: 36.0, pct: 3.6, role: "parfum" },
    ],
    procede: [
      "Faire un sirop avec l'eau et les sucres",
      "A froid rajouter la poudre d'amande et le grand marnier",
      "Réserver au frigo",
      "Make a sirup with water and sugar.",
      "When it's cold, add a almond powder with the grand marnier.",
      "To cool in the fridge.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["fruits_a_coque"],
    tags: ["sirop", "amande", "Mini bostock chocolat"],
    parfum_principal: "amande",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Sirop bostock grand marnier.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "sirop-de-basilic-frais",
    nom: "Sirop de basilic frais",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop de basilic frais — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Sirop à 30°C", g: 980.4, pct: 98.0, role: "sucrant" },
      { nom: "Basilic frais", g: 19.6, pct: 2.0, role: "parfum" },
    ],
    procede: [
      "Bouillir le sirop à 30°C.",
      "Mélanger le sirop à 30°C avec les feuilles de basilic frais.",
      "Mixer à chaud.",
      "Stocker.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "Carpaccio d'ananas (Dessert Assiette)"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Sirop de basilic frais.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "sirop-jasmin",
    nom: "Sirop Jasmin",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop Jasmin — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Eau", g: 714.0, pct: 71.4, role: "eau" },
      { nom: "Sucre", g: 285.6, pct: 28.6, role: "sucrant" },
      { nom: "Arôme jasmin", g: 0.4, pct: 0.0, role: "parfum" },
    ],
    procede: [
      "Faire bouillir l'eau et le sucre",
      "Ajouter l'arôme jasmin à froid",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "Carré fruits orange jasmin"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Sirop de jasmin.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "sirop-exotique-verveine",
    nom: "Sirop exotique Verveine",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop exotique Verveine — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Sucre semoule", g: 86.8, pct: 8.7, role: "sucrant" },
      { nom: "Vanille gousse séchée", g: 4.3, pct: 0.4, role: "parfum" },
      { nom: "Verveine fraiche", g: 8.7, pct: 0.9, role: "parfum" },
      { nom: "Eau", g: 882.9, pct: 88.3, role: "eau" },
      { nom: "Zetes de citron jaune", g: 8.7, pct: 0.9, role: "liant" },
      { nom: "Zeste d'orange", g: 8.7, pct: 0.9, role: "parfum" },
    ],
    procede: [
      "Mélanger tous les ingrédients sauf la verveine.",
      "Faire bouillir. Ajouter la verveine.",
      "Filmer et infuser.",
      "Chinoiser et débarasser.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["oeuf"],
    tags: ["sirop", "vanille", "Verres plateaux repas"],
    parfum_principal: "vanille",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Sirop exotique verveine.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "sirop-exotique",
    nom: "Sirop exotique",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop exotique — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Sucre semoule", g: 87.0, pct: 8.7, role: "sucrant" },
      { nom: "Vanille gousse séchée", g: 4.3, pct: 0.4, role: "parfum" },
      { nom: "Menthe fraiche", g: 6.5, pct: 0.7, role: "parfum" },
      { nom: "Eau", g: 884.8, pct: 88.5, role: "eau" },
      { nom: "Zeste de citron jaune", g: 8.7, pct: 0.9, role: "liant" },
      { nom: "Zeste d'orange", g: 8.7, pct: 0.9, role: "parfum" },
    ],
    procede: [
      "Mélanger tous les ingrédients sauf la menthe.",
      "Faire bouillir. Ajouter la menthe.",
      "Filmer et infuser.",
      "Chinoiser et débarasser.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["oeuf"],
    tags: ["sirop", "vanille", "Verres salade de fruits", "Salade de fruit frais (dessert Assiette)"],
    parfum_principal: "vanille",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Sirop exotique.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "sirop-vanille",
    nom: "Sirop vanille",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop vanille — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Eau", g: 709.2, pct: 70.9, role: "eau" },
      { nom: "Sucre", g: 283.7, pct: 28.4, role: "sucrant" },
      { nom: "Gousse vanille", g: 7.1, pct: 0.7, role: "parfum" },
    ],
    procede: [
      "Bouillir l'eau, le sucre et la vanille.",
      "Infuser 10 minutes",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "vanille", "Carré fruits passion pistache", "Cœur de Rocker"],
    parfum_principal: "vanille",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Sirop vanille.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "sirop-a-la-fleur-d-oranger",
    nom: "Sirop à la fleur d’oranger",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop à la fleur d’oranger — recette importée, à vérifier.",
    masse_totale_g: 220,
    ingredients: [
      { nom: "sucre en poudre", g: 100.0, pct: 45.5, role: "sucrant" },
      { nom: "eau", g: 100.0, pct: 45.5, role: "eau" },
      { nom: "fleur d'oranger", g: 20.0, pct: 9.1, role: "parfum" },
    ],
    procede: [
      "Faire bouillir l’eau et le sucre puis ajouter la fleur d’oranger, réserver.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "tarte fraise et fleur d'oranger.docx", import: "extraction-2026-08-12" },
  },
  {
    id: "le-sirop-d-imbibage",
    nom: "Le sirop d’imbibage",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Le sirop d’imbibage — recette importée, à vérifier.",
    masse_totale_g: 335,
    ingredients: [
      { nom: "eau", g: 75.0, pct: 22.4, role: "eau" },
      { nom: "sucre", g: 180.0, pct: 53.7, role: "sucrant" },
      { nom: "fleur d'oranger", g: 80.0, pct: 23.9, role: "parfum" },
    ],
    procede: [
      "La veille, mélanger au crochet la farine, le sucre, le sel et la levure, pétrir à petite vitesse, puis ajouter les œufs doucement.",
      "Passer en deuxième et pétrir comme une brioche, incorporer le beurre froid coupée en dés et pétrir jusqu’à obtention d’une pâte homogène.",
      "Incorporer les raisins et les écorces d’orange en cube, 1h de pointage, dégazer, bouler, filmer et réserver au frais 24h.",
      "Tailler la pâte en 5 pâtons, beurrer les moules et parsemer les d’amandes effilées, mouler les kouglofs et mettre en pousse pendant 2h.",
      "Préchauffer le four à 180°C",
      "Enfourner et cuire pendant 15 minutes, démouler sur grille.",
      "imbiber les kouglofs généreusement avec le sirop à 60°C à plusieurs reprise.",
      "Rouler les kouglofs dans le sucre",
    ],
    cuisson: { temperature_c: 180, duree_min: 15, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Kouglofs fleur d'oranger.docx", import: "extraction-2026-08-12" },
  },
];
