export const RECETTES_SIROPS = [
  // === Import extraction-2026-08-12 (23 recettes) ===
  {
    id: "sirop-neutre",
    nom: "Sirop neutre",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop neutre — recette importée, à vérifier.",
    masse_totale_g: 600,
    ingredients: [
      { nom: "eau", g: 370.0, pct: 61.7, role: "eau" },
      { nom: "sucre", g: 230.0, pct: 38.3, role: "sucrant" },
    ],
    procede: [
      "Porter les ingrédients à ébullition, réserver au frais",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Bûche Monticola.docx", import: "extraction-2026-08-12" },
  },
  {
    id: "sirop-de-punchage",
    nom: "Sirop de punchage",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop de punchage — recette importée, à vérifier.",
    masse_totale_g: 150,
    ingredients: [
      { nom: "eau", g: 100.0, pct: 66.7, role: "eau" },
      { nom: "sucre", g: 40.0, pct: 26.7, role: "sucrant" },
      { nom: "rhum", g: 10.0, pct: 6.7, role: "parfum" },
    ],
    procede: [
      "Faire bouillir l’eau, le sucre, rajouter le rhum hors du feu.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Bûche prestige.docx", import: "extraction-2026-08-12" },
  },
  {
    id: "sirop-citron",
    nom: "Sirop citron",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop citron — recette importée, à vérifier.",
    masse_totale_g: 554,
    ingredients: [
      { nom: "jus de citron", g: 120.0, pct: 21.7, role: "acidite" },
      { nom: "sucre", g: 80.0, pct: 14.4, role: "sucrant" },
      { nom: "sucre", g: 100.0, pct: 18.1, role: "sucrant" },
      { nom: "jus de citron vert", g: 200.0, pct: 36.1, role: "acidite" },
      { nom: "pectine NH", g: 8.0, pct: 1.4, role: "gelifiant" },
      { nom: "huile d'olive", g: 40.0, pct: 7.2, role: "mg" },
      { nom: "basilic", g: 6.0, pct: 1.1, role: "parfum" },
    ],
    procede: [
      "Porter le tout à ébullition",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "citron"],
    parfum_principal: "citron",
    note_concepteur: "",
    source_interne: { fichier: "Bûche roulé citron.docx", import: "extraction-2026-08-12" },
  },
  {
    id: "sirop-cafe",
    nom: "Sirop café",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop café — recette importée, à vérifier.",
    masse_totale_g: 500,
    ingredients: [
      { nom: "expresso", g: 440.0, pct: 88.0, role: "parfum" },
      { nom: "sucre semoule", g: 60.0, pct: 12.0, role: "sucrant" },
    ],
    procede: [
      "Réaliser un sirop et réserver.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "café"],
    parfum_principal: "café",
    note_concepteur: "",
    source_interne: { fichier: "Bûche tiramisu.docx", import: "extraction-2026-08-12" },
  },
  {
    id: "imbibage-raisins",
    nom: "Imbibage raisins",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Imbibage raisins — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Raisin", g: 476.2, pct: 47.6, role: "parfum" },
      { nom: "Eau", g: 476.2, pct: 47.6, role: "eau" },
      { nom: "Rhum", g: 47.6, pct: 4.8, role: "parfum" },
    ],
    procede: [
      "Mélanger l'eau et le rhum.",
      "Tremper les raisins dans le mélange au moins 24h avant utilisation.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "Kougloff"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Imbibage raisins.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "imbibage-cacao",
    nom: "Imbibage cacao",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Imbibage cacao — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Cacao poudre", g: 86.8, pct: 8.7, role: "parfum" },
      { nom: "Eau", g: 288.8, pct: 28.9, role: "eau" },
      { nom: "Sirop à 30°", g: 579.3, pct: 57.9, role: "sucrant" },
      { nom: "Gélatine poudre", g: 1.7, pct: 0.2, role: "gelifiant" },
      { nom: "Eau", g: 43.4, pct: 4.3, role: "eau" },
    ],
    procede: [
      "Mélanger la petite quantité d'eau avec la gélatine poudre.Laisser gonfler.",
      "Faire chauffer l'eau, le sirop puis ajouter le cacao poudre.",
      "Ajouter la gélatine dans le mélange chaud, mélanger.",
      "Bûche carrémenchoc :",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "Carrémenchoc", "Bûche carrémenchoc", "Carrémenchoc dessert à l'assiette 1"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Imbibage cacao..xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "imbibage-rhum",
    nom: "Imbibage rhum",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Imbibage rhum — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Rhum blanc", g: 349.0, pct: 34.9, role: "parfum" },
      { nom: "Sirop à 30°", g: 651.0, pct: 65.1, role: "sucrant" },
    ],
    procede: [
      "Mélanger les deux ingrédients.",
      "Mix all a ingredients",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "La pink"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Imbibage rhum .xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "imbibation-whisky",
    nom: "Imbibation whisky",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Imbibation whisky — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Whisky", g: 301.5, pct: 30.2, role: "parfum" },
      { nom: "Gélatine poudre", g: 15.7, pct: 1.6, role: "gelifiant" },
      { nom: "Eau", g: 78.5, pct: 7.8, role: "eau" },
      { nom: "Sirop à 30°", g: 604.3, pct: 60.4, role: "sucrant" },
    ],
    procede: [
      "Melanger l'eau et la gélatine a froid",
      "Laisser gonfler ce mélange pendant 30 min",
      "Mettre le sirop et le whisky à chauffer",
      "Incorporer la gelatine au sirop",
      "Chauffer à 50°C",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "Bûche marron myrtille"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Imbibation Whisky.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "punch-abricot-romarin",
    nom: "Punch abricot romarin",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Punch abricot romarin — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Purée d'abricot romarin", g: 446.8, pct: 44.7, role: "assaisonnement" },
      { nom: "Sirop à 30°", g: 212.8, pct: 21.3, role: "sucrant" },
      { nom: "Eau 1", g: 202.1, pct: 20.2, role: "eau" },
      { nom: "Jus de citron", g: 26.6, pct: 2.7, role: "acidite" },
      { nom: "Eau 2", g: 95.7, pct: 9.6, role: "eau" },
      { nom: "Gélatine poudre", g: 16.0, pct: 1.6, role: "gelifiant" },
    ],
    procede: [
      "Mélanger l'eau 2 froide avec la gélatine poudre, laisser gonfler 20mn.",
      "Mélanger l'eau 1, le sirop, la purée et le jus.",
      "Prélever une petite partie, chauffer et ajouter le mélange gélatine.",
      "Ajouter ensuite tous les ingrédients.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "citron", "1000 fruits abricot romarin"],
    parfum_principal: "citron",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Punch abricot romarin.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "punch-fraise-1",
    nom: "Punch fraise 1",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Punch fraise 1 — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Purée de fraise", g: 514.3, pct: 51.4, role: "eau" },
      { nom: "Sirop à 30°", g: 228.6, pct: 22.9, role: "sucrant" },
      { nom: "Eau", g: 217.1, pct: 21.7, role: "eau" },
      { nom: "Gélatine feuille", g: 17.1, pct: 1.7, role: "gelifiant" },
      { nom: "Gourmandise fraise", g: 22.9, pct: 2.3, role: "parfum" },
    ],
    procede: [
      "Mettre la gélatine à fondre dans l'eau froide pendant au moins 20 minutes.",
      "Mélanger l'eau, le sirop à 30°, faire bouillir.",
      "Ajouter la gélatine.",
      "Verser le tout sur la purée de fraise fondue.",
      "Finir par la gourmandise fraise.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "fraise", "Le White", "Tiramisu fraise verre/verrine"],
    parfum_principal: "fraise",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Punch fraise 1.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "punch-fraise-des-bois",
    nom: "Punch fraise des Bois",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Punch fraise des Bois — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Purée de fraise des Bois", g: 386.1, pct: 38.6, role: "eau" },
      { nom: "Sirop à 30°", g: 257.1, pct: 25.7, role: "sucrant" },
      { nom: "Eau 1", g: 192.5, pct: 19.3, role: "eau" },
      { nom: "Jus de citron", g: 30.2, pct: 3.0, role: "acidite" },
      { nom: "Eau 2", g: 87.7, pct: 8.8, role: "eau" },
      { nom: "Gélatine poudre", g: 17.1, pct: 1.7, role: "gelifiant" },
      { nom: "Gourmandise fraise", g: 29.2, pct: 2.9, role: "parfum" },
    ],
    procede: [
      "Mélanger l'eau 2 froide avec la gélatine poudre, laisser gonfler 20mn.",
      "Mélanger l'eau 1, le sirop, le jus de citron, la gourmandise.",
      "Prélever une petite partie de la purée de fraise des bois et ajouter le mélange gélatine.",
      "Ajouter ensuite tous les ingrédients.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "citron", "Côté Jardin", "Tiramisu fraise"],
    parfum_principal: "citron",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Punch fraise des bois.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "punch-fraise",
    nom: "Punch fraise",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Punch fraise — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Purée de fraise", g: 386.1, pct: 38.6, role: "eau" },
      { nom: "Sirop à 30°", g: 257.1, pct: 25.7, role: "sucrant" },
      { nom: "Eau 1", g: 192.5, pct: 19.3, role: "eau" },
      { nom: "Jus de citron", g: 30.2, pct: 3.0, role: "acidite" },
      { nom: "Eau 2", g: 87.7, pct: 8.8, role: "eau" },
      { nom: "Gélatine poudre", g: 17.1, pct: 1.7, role: "gelifiant" },
      { nom: "Gourmandise fraise", g: 29.2, pct: 2.9, role: "parfum" },
    ],
    procede: [
      "Mélanger l'eau 2 froide avec la gélatine poudre, laisser gonfler 20mn.",
      "Mélanger l'eau 1, le sirop, le jus de citron, la gourmandise.",
      "Prélever une petite partie de la purée de fraise et ajouter le mélange gélatine.",
      "Ajouter ensuite tous les ingrédients.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "citron", "Carré de fruits fraise coquelicot"],
    parfum_principal: "citron",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Punch fraise.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "punch-framboise-groseilles",
    nom: "Punch framboise groseilles",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Punch framboise groseilles — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Purée de framboise", g: 324.2, pct: 32.4, role: "eau" },
      { nom: "Sirop à 30°", g: 253.3, pct: 25.3, role: "sucrant" },
      { nom: "Eau 1", g: 192.5, pct: 19.2, role: "eau" },
      { nom: "Purée de groseilles", g: 101.3, pct: 10.1, role: "eau" },
      { nom: "Eau 2", g: 88.1, pct: 8.8, role: "eau" },
      { nom: "Gélatine poudre", g: 15.2, pct: 1.5, role: "gelifiant" },
      { nom: "Gourmandise framboise", g: 25.3, pct: 2.5, role: "parfum" },
    ],
    procede: [
      "Mélanger l'eau 2 froide avec la gélatine poudre, laisser gonfler 20mn.",
      "Mélanger l'eau 1, le sirop, les purées, la gourmandise.",
      "Prélever une petite partie et ajouter le mélange gélatine.",
      "Ajouter ensuite tous les ingrédients.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "framboise", "1000 fruits framboise groseilles"],
    parfum_principal: "framboise",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Punch framboise groseilles.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "sirop-bostock-citron",
    nom: "Sirop bostock citron",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop bostock citron — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Sucre semoule", g: 513.8, pct: 51.4, role: "sucrant" },
      { nom: "Huile essentiel citron", g: 18.3, pct: 1.8, role: "mg" },
      { nom: "Eau", g: 367.0, pct: 36.7, role: "eau" },
      { nom: "Sucre glace", g: 50.4, pct: 5.0, role: "sucrant" },
      { nom: "Poudre d'amande", g: 50.4, pct: 5.0, role: "structure" },
    ],
    procede: [
      "Faire un sirop avec l'eau et les sucres;a froid rajouter la poudre d'amande et l'huile essentiel",
      "reserver au frigo",
      "Make a sirup with the water and sugar.",
      "When it's cold, add a almond powder and oil lemon flavour.",
      "To cool in the fridge.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["fruits_a_coque"],
    tags: ["sirop", "amande", "Mini bostock citron"],
    parfum_principal: "amande",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Sirop bostock citron.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "sirop-bostock-framboise",
    nom: "Sirop bostock framboise",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop bostock framboise — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Sucre semoule", g: 504.5, pct: 50.5, role: "sucrant" },
      { nom: "Sucre glace", g: 49.5, pct: 5.0, role: "sucrant" },
      { nom: "Eau", g: 360.4, pct: 36.0, role: "eau" },
      { nom: "Poudre d amande", g: 49.5, pct: 5.0, role: "structure" },
      { nom: "Arome framboise", g: 36.0, pct: 3.6, role: "parfum" },
    ],
    procede: [
      "Faire un sirop avec l'eau et les sucres",
      "A froid rajouter la poudre d'amande et l'arôme famboise",
      "Réserver au frigo",
      "Make a sirup with water ans sugar",
      "When it's cold, add a almond powder ans raspberry flavour.",
      "To cool in the fridge",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["fruits_a_coque"],
    tags: ["sirop", "amande", "Mini bostock framboise"],
    parfum_principal: "amande",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Sirop bostock framboise.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "sirop-bostock-grand-marnier",
    nom: "Sirop bostock grand marnier",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop bostock grand marnier — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Sucre semoule", g: 504.5, pct: 50.5, role: "sucrant" },
      { nom: "Sucre glace", g: 49.5, pct: 5.0, role: "sucrant" },
      { nom: "Eau", g: 360.4, pct: 36.0, role: "eau" },
      { nom: "Poudre d amande", g: 49.5, pct: 5.0, role: "structure" },
      { nom: "Grand marnier", g: 36.0, pct: 3.6, role: "parfum" },
    ],
    procede: [
      "Faire un sirop avec l'eau et les sucres",
      "A froid rajouter la poudre d'amande et le grand marnier",
      "Réserver au frigo",
      "Make a sirup with water and sugar.",
      "When it's cold, add a almond powder with the grand marnier.",
      "To cool in the fridge.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["fruits_a_coque"],
    tags: ["sirop", "amande", "Mini bostock chocolat"],
    parfum_principal: "amande",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Sirop bostock grand marnier.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "sirop-de-basilic-frais",
    nom: "Sirop de basilic frais",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop de basilic frais — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Sirop à 30°C", g: 980.4, pct: 98.0, role: "sucrant" },
      { nom: "Basilic frais", g: 19.6, pct: 2.0, role: "parfum" },
    ],
    procede: [
      "Bouillir le sirop à 30°C.",
      "Mélanger le sirop à 30°C avec les feuilles de basilic frais.",
      "Mixer à chaud.",
      "Stocker.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "Carpaccio d'ananas (Dessert Assiette)"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Sirop de basilic frais.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "sirop-jasmin",
    nom: "Sirop Jasmin",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop Jasmin — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Eau", g: 714.0, pct: 71.4, role: "eau" },
      { nom: "Sucre", g: 285.6, pct: 28.6, role: "sucrant" },
      { nom: "Arôme jasmin", g: 0.4, pct: 0.0, role: "parfum" },
    ],
    procede: [
      "Faire bouillir l'eau et le sucre",
      "Ajouter l'arôme jasmin à froid",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "Carré fruits orange jasmin"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Sirop de jasmin.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "sirop-exotique-verveine",
    nom: "Sirop exotique Verveine",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop exotique Verveine — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Sucre semoule", g: 86.8, pct: 8.7, role: "sucrant" },
      { nom: "Vanille gousse séchée", g: 4.3, pct: 0.4, role: "parfum" },
      { nom: "Verveine fraiche", g: 8.7, pct: 0.9, role: "parfum" },
      { nom: "Eau", g: 882.9, pct: 88.3, role: "eau" },
      { nom: "Zetes de citron jaune", g: 8.7, pct: 0.9, role: "liant" },
      { nom: "Zeste d'orange", g: 8.7, pct: 0.9, role: "parfum" },
    ],
    procede: [
      "Mélanger tous les ingrédients sauf la verveine.",
      "Faire bouillir. Ajouter la verveine.",
      "Filmer et infuser.",
      "Chinoiser et débarasser.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["oeuf"],
    tags: ["sirop", "vanille", "Verres plateaux repas"],
    parfum_principal: "vanille",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Sirop exotique verveine.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "sirop-exotique",
    nom: "Sirop exotique",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop exotique — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Sucre semoule", g: 87.0, pct: 8.7, role: "sucrant" },
      { nom: "Vanille gousse séchée", g: 4.3, pct: 0.4, role: "parfum" },
      { nom: "Menthe fraiche", g: 6.5, pct: 0.7, role: "parfum" },
      { nom: "Eau", g: 884.8, pct: 88.5, role: "eau" },
      { nom: "Zeste de citron jaune", g: 8.7, pct: 0.9, role: "liant" },
      { nom: "Zeste d'orange", g: 8.7, pct: 0.9, role: "parfum" },
    ],
    procede: [
      "Mélanger tous les ingrédients sauf la menthe.",
      "Faire bouillir. Ajouter la menthe.",
      "Filmer et infuser.",
      "Chinoiser et débarasser.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["oeuf"],
    tags: ["sirop", "vanille", "Verres salade de fruits", "Salade de fruit frais (dessert Assiette)"],
    parfum_principal: "vanille",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Sirop exotique.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "sirop-vanille",
    nom: "Sirop vanille",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop vanille — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Eau", g: 709.2, pct: 70.9, role: "eau" },
      { nom: "Sucre", g: 283.7, pct: 28.4, role: "sucrant" },
      { nom: "Gousse vanille", g: 7.1, pct: 0.7, role: "parfum" },
    ],
    procede: [
      "Bouillir l'eau, le sucre et la vanille.",
      "Infuser 10 minutes",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "vanille", "Carré fruits passion pistache", "Cœur de Rocker"],
    parfum_principal: "vanille",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Sirop vanille.xlsx", import: "extraction-2026-08-12" },
  },
  {
    id: "sirop-a-la-fleur-d-oranger",
    nom: "Sirop à la fleur d’oranger",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop à la fleur d’oranger — recette importée, à vérifier.",
    masse_totale_g: 220,
    ingredients: [
      { nom: "sucre en poudre", g: 100.0, pct: 45.5, role: "sucrant" },
      { nom: "eau", g: 100.0, pct: 45.5, role: "eau" },
      { nom: "fleur d'oranger", g: 20.0, pct: 9.1, role: "parfum" },
    ],
    procede: [
      "Faire bouillir l’eau et le sucre puis ajouter la fleur d’oranger, réserver.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "tarte fraise et fleur d'oranger.docx", import: "extraction-2026-08-12" },
  },
  {
    id: "le-sirop-d-imbibage",
    nom: "Le sirop d’imbibage",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Le sirop d’imbibage — recette importée, à vérifier.",
    masse_totale_g: 335,
    ingredients: [
      { nom: "eau", g: 75.0, pct: 22.4, role: "eau" },
      { nom: "sucre", g: 180.0, pct: 53.7, role: "sucrant" },
      { nom: "fleur d'oranger", g: 80.0, pct: 23.9, role: "parfum" },
    ],
    procede: [
      "La veille, mélanger au crochet la farine, le sucre, le sel et la levure, pétrir à petite vitesse, puis ajouter les œufs doucement.",
      "Passer en deuxième et pétrir comme une brioche, incorporer le beurre froid coupée en dés et pétrir jusqu’à obtention d’une pâte homogène.",
      "Incorporer les raisins et les écorces d’orange en cube, 1h de pointage, dégazer, bouler, filmer et réserver au frais 24h.",
      "Tailler la pâte en 5 pâtons, beurrer les moules et parsemer les d’amandes effilées, mouler les kouglofs et mettre en pousse pendant 2h.",
      "Préchauffer le four à 180°C",
      "Enfourner et cuire pendant 15 minutes, démouler sur grille.",
      "imbiber les kouglofs généreusement avec le sirop à 60°C à plusieurs reprise.",
      "Rouler les kouglofs dans le sucre",
    ],
    cuisson: { temperature_c: 180, duree_min: 15, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Kouglofs fleur d'oranger.docx", import: "extraction-2026-08-12" },
  },

  // === Import extraction-2026-08-25 (46 recettes) ===
  {
    id: "liqueurs-chartreuse-70",
    nom: "Liqueurs chartreuse (70%)",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Liqueurs chartreuse (70%) — recette importée, à vérifier.",
    masse_totale_g: 1180,
    ingredients: [
      { nom: "chartreuse", g: 150.0, pct: 12.7, role: "parfum" },
      { nom: "eau", g: 30.0, pct: 2.5, role: "eau" },
      { nom: "sucre", g: 750.0, pct: 63.6, role: "sucrant" },
      { nom: "eau", g: 250.0, pct: 21.2, role: "eau" },
    ],
    procede: [
      "Cuisson du sucre à 111°c /112°c.",
    ],
    cuisson: { temperature_c: 111, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Liqueurs en croute de sucre.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "cointreau-rhum-kirsch-etc",
    nom: "Cointreau rhum kirsch etc...",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Cointreau rhum kirsch etc... — recette importée, à vérifier.",
    masse_totale_g: 865,
    ingredients: [
      { nom: "alcool à 50%", g: 165.0, pct: 19.1, role: "parfum" },
      { nom: "eau", g: 200.0, pct: 23.1, role: "eau" },
      { nom: "sucre semoule", g: 500.0, pct: 57.8, role: "sucrant" },
    ],
    procede: [
      "Cuisson du sucre à 114°c.",
    ],
    cuisson: { temperature_c: 114, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Liqueurs en croute de sucre.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "sirop-a-30-b",
    nom: "Sirop à 30 °B",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop à 30 °B — recette importée, à vérifier.",
    masse_totale_g: 950,
    ingredients: [
      { nom: "sucre semoule", g: 500.0, pct: 52.6, role: "sucrant" },
      { nom: "eau", g: 450.0, pct: 47.4, role: "eau" },
    ],
    procede: [
      "Dans une casserole, portez le tout à ébullition ; laissez refroidir et stockez au frais.",
      "Café glacé",
      "Double expresso",
      "1 Cuillère à café de sucre semoule",
      "3 cuillères à soupe de pleine de glace pilée",
      "Préparez un double expresso, versez-le dans un shaker avec la glace pilée, agitez, versez dans le tumbler et servez aussitôt.",
      "NB : le sucre permet d’obtenir un café glacé mousseux en surface, ce que je recherche. Si vous avez un gros débit de cette boisson, je vous propose d’en faire un peu d’avance et de la conserver au réfrigérateur.",
      "Arts de la table",
      "Verre tumbler 28 cl, un petit verre à saké, un carré carton marron.",
      "Service",
      "Servez dans l’ordre",
      "Le café dans un tumbler sur l’assiette carrée",
      "A part, le sirop à 30 °B",
      "Conservation",
      "2 jours pour la préparation de base.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Cafe glace 01.02.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "sirop-leger-pour-les-tranches-de-poire-craquantes",
    nom: "Sirop léger pour les tranches de poire craquantes",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop léger pour les tranches de poire craquantes — recette importée, à vérifier.",
    masse_totale_g: 500,
    ingredients: [
      { nom: "eau minérale", g: 200.0, pct: 40.0, role: "eau" },
      { nom: "sucre semoule", g: 250.0, pct: 50.0, role: "sucrant" },
      { nom: "jus de citron jaune", g: 50.0, pct: 10.0, role: "liant" },
    ],
    procede: [
      "Faites bouillir ensemble l’eau minérale et le sucre semoule et ajoutez le jus de citron. Réservez.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["oeuf"],
    tags: ["sirop", "citron"],
    parfum_principal: "citron",
    note_concepteur: "",
    source_interne: { fichier: "Creme brulee au foie gras 08.06.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "sirop-a-15b",
    nom: "Sirop à 15°B",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop à 15°B — recette importée, à vérifier.",
    masse_totale_g: 1350,
    ingredients: [
      { nom: "sucre semoule", g: 350.0, pct: 25.9, role: "sucrant" },
      { nom: "eau minérale", g: 1000.0, pct: 74.1, role: "eau" },
    ],
    procede: [
      "Portez à ébullition, écumez les impuretés et utilisez aussitôt.",
      "Fines tranches de citron vert et jaune croquantes",
      "QS de citron vert et de citron jaune",
      "QS de sirop à 15°B",
      "A la trancheuse à jambon, à 1 ½, couper les citrons en fines tranches. Disposez les tranches dans un candissoir avec le sirop chaud. Laissez reposer pendant 12 heures recouvert d’un film alimentaire. Le lendemain, posez les tranches sur une plaque de cuisson recouverte d’un tapis Silpat. Laissez sécher entre deux tapis Silpat à 50°C pendant 24 heures. Coupez les tranches en deux, laissez refroidir et stockez en boite hermétique avec des pastilles air-sec.",
    ],
    cuisson: { temperature_c: 50, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Dessert Azur 10.02.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "sirop-a-1260-dit-sirop-a-30b",
    nom: "Sirop à 1260, dit sirop à 30°B",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop à 1260, dit sirop à 30°B — recette importée, à vérifier.",
    masse_totale_g: 950,
    ingredients: [
      { nom: "sucre semoule", g: 500, pct: 52.6, role: "sucrant" },
      { nom: "eau minérale", g: 450, pct: 47.4, role: "eau" },
    ],
    procede: [
      "Portez à ébullition, écumez les impuretés, laissez refroidir et stockez en boîte hermétique au réfrigérateur.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Dessert Plenitude 08.06.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "sirop-a-1260-dit-a-30b",
    nom: "Sirop à 1260 dit à 30°B",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop à 1260 dit à 30°B — recette importée, à vérifier.",
    masse_totale_g: 950,
    ingredients: [
      { nom: "sucre semoule", g: 500.0, pct: 52.6, role: "sucrant" },
      { nom: "eau minérale", g: 450.0, pct: 47.4, role: "eau" },
    ],
    procede: [
      "Portez à ébullition, écumez les impuretés, laissez refroidir et stockez en boite hermétique au réfrigérateur.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Etuvee de pommes de dix heures RM 10.04.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "sirop-leger",
    nom: "Sirop léger",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop léger — recette importée, à vérifier.",
    masse_totale_g: 500,
    ingredients: [
      { nom: "eau minérale", g: 200.0, pct: 40.0, role: "eau" },
      { nom: "sucre semoule", g: 250.0, pct: 50.0, role: "sucrant" },
      { nom: "jus de citron jaune", g: 50.0, pct: 10.0, role: "liant" },
    ],
    procede: [
      "Faites bouillir ensemble l’eau minérale et le sucre semoule et ajoutez le jus de citron. Réservez.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["oeuf"],
    tags: ["sirop", "citron"],
    parfum_principal: "citron",
    note_concepteur: "",
    source_interne: { fichier: "Etuvee de pommes de dix heures RM 10.04.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "amande-au-sirop",
    nom: "Amande au sirop",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Amande au sirop — recette importée, à vérifier.",
    masse_totale_g: 240,
    ingredients: [
      { nom: "amande effilées", g: 200.0, pct: 83.3, role: "parfum" },
      { nom: "sirop à 30", g: 20.0, pct: 8.3, role: "sucrant" },
      { nom: "sucre semoule", g: 20.0, pct: 8.3, role: "sucrant" },
    ],
    procede: [
      "Mélanger délicatement les amandes avec le sirop à 30, ajouter le sucre semoule et mettre à torréfier au four a 160 °C. Les garder blondes claires.",
      "DRESSAGE  ET  PRESENTATION :",
      "Disposer une belle rosace de quartiers de pêche pochée sur le sablé, disposer ce montage sur la crème brûlée, au milieu garnir de marmelade de pêche et de groseille bille, réserver au frais.",
      "Au moment de l’envoie décorer la coupe de 5 petits quartiers de pêches fraîches, faire une quenelle de sorbet pêche, champagne au centre et décorer d’une chips de pêche séchée. Tiédir le clafoutis décorer de sucre glace et servir le jus de groseille bien froid.",
    ],
    cuisson: { temperature_c: 160, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["fruits_a_coque"],
    tags: ["sirop", "amande"],
    parfum_principal: "amande",
    note_concepteur: "",
    source_interne: { fichier: "Pêche groseille verveine.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "sirop-menthe",
    nom: "Sirop menthe",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop menthe — recette importée, à vérifier.",
    masse_totale_g: 1230,
    ingredients: [
      { nom: "eau minérale", g: 1000.0, pct: 81.3, role: "eau" },
      { nom: "sucre semoule", g: 200.0, pct: 16.3, role: "sucrant" },
      { nom: "menthe fraiche hachée", g: 20.0, pct: 1.6, role: "parfum" },
      { nom: "Pippermint jet", g: 10.0, pct: 0.8, role: "parfum" },
    ],
    procede: [
      "Dans une casserole, faites bouillir l’eau et le sucre. A ébullition, incorporez la menthe fraiche hachée. Laissez infuser pendant 15 minutes (lors de l’infusion, ne pas oublier de filmer la casserole).Puis à froid, ajoutez le pippermint jet et stoker le sirop en boite hermétique au réfrigérateur",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Salade de fraises à la menthe RM 10.06.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "sirop-a-la-menthe-vanillee",
    nom: "Sirop à la menthe vanillée",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop à la menthe vanillée — recette importée, à vérifier.",
    masse_totale_g: 1230,
    ingredients: [
      { nom: "eau minérale", g: 1000.0, pct: 81.3, role: "eau" },
      { nom: "sucre semoule", g: 200.0, pct: 16.3, role: "sucrant" },
      { nom: "zestes de citron", g: 10.0, pct: 0.8, role: "acidite" },
      { nom: "zestes d'orange", g: 5.0, pct: 0.4, role: "parfum" },
      { nom: "gousses de vanille usées", g: 10.0, pct: 0.8, role: "parfum" },
      { nom: "feuilles de menthe", g: 5.0, pct: 0.4, role: "parfum" },
    ],
    procede: [
      "A l’aide d’un économe, prélevez le zeste de l’orange et du citron. Mettez-les dans une casserole avec la vanille, le sucre et l’eau. Portez à ébullition, puis retirez du feu. Ajoutez les feuilles de menthe grossièrement hachées. Laissez infuser pendant 30 minutes Filtrez ce sirop. Laissez-le refroidir. Réservez-le au réfrigérateur.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "vanille"],
    parfum_principal: "vanille",
    note_concepteur: "",
    source_interne: { fichier: "Salade de fruits RM 10.05.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "sirop-exotique-vanille",
    nom: "Sirop exotique vanillé",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop exotique vanillé — recette importée, à vérifier.",
    masse_totale_g: 1225,
    ingredients: [
      { nom: "eau minérale", g: 1000.0, pct: 81.6, role: "eau" },
      { nom: "sucre semoule", g: 200.0, pct: 16.3, role: "sucrant" },
      { nom: "zestes de citron jaune", g: 10.0, pct: 0.8, role: "liant" },
      { nom: "zestes d'orange", g: 5.0, pct: 0.4, role: "parfum" },
      { nom: "gousses de vanille usées", g: 10.0, pct: 0.8, role: "parfum" },
    ],
    procede: [
      "A l’aide d’un économe, prélevez le zeste de l’orange et du citron. Mettez-les dans une casserole avec la vanille, le sucre et l’eau. Portez à ébullition, puis retirez du feu. Ajoutez les feuilles de menthe grossièrement hachées. Laissez infuser pendant 30 minutes Filtrez ce sirop. Laissez-le refroidir. Réservez-le au réfrigérateur.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["oeuf"],
    tags: ["sirop", "vanille"],
    parfum_principal: "vanille",
    note_concepteur: "",
    source_interne: { fichier: "Salade de fruits ananas, citron vert & coriandre RM 10.05.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "sirop-imbibage",
    nom: "Sirop imbibage",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop imbibage — recette importée, à vérifier.",
    masse_totale_g: 2400,
    ingredients: [
      { nom: "sirop à 30°B", g: 2000.0, pct: 83.3, role: "sucrant" },
      { nom: "eau", g: 400.0, pct: 16.7, role: "eau" },
    ],
    procede: [
      "Mélangez le sirop à 30°B et l’eau. Faites tiédir le sirop avant imbibage.",
      "Imbibage",
      "Cake Aztec",
      "Sirop imbibage",
      "Déposez les cakes tiédis sur grille, elle-même posée sur un candissoire, imbibez-les avec le sirop à deux reprises. Laissez bien égoutter avant de procéder à la finition.",
      "Finition",
      "Appareil gomme arabique",
      "Aiguillettes d’oranges confites",
      "Faites fondre l’appareil gomme arabique et nappez le haut du cake Aztec. Disposez les aiguillettes et nappez-les de gomme arabique. Stockez au réfrigérateur.",
      "Emballage",
      "Emballez les cakes dans les boites PVC pliable ; appliquez l’autocollant  rectangulaire et noir, siglé PH centré au dessus puis en dessous l’adhésif indiquant la date limite de vente et la composition.",
      "Dimensions des boites à cake : hauteur unique pour les deux modèles ; pour le petit cake 16 x 9 cm et pour le grand : 19 x 9 cm.",
      "Boissons conseillées",
      "Thés, café, chocolat.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Cake Aztec 04.09.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "sirop-d-imbibage-azur",
    nom: "Sirop d’imbibage Azur",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop d’imbibage Azur — recette importée, à vérifier.",
    masse_totale_g: 450,
    ingredients: [
      { nom: "sirop à 1260 dit à 30°B", g: 210.0, pct: 46.7, role: "sucrant" },
      { nom: "jus de yuzu nature (Issé et Cie Workshop)", g: 120.0, pct: 26.7, role: "eau" },
      { nom: "eau minérale", g: 120.0, pct: 26.7, role: "eau" },
    ],
    procede: [
      "Mélangez le sirop à 30°B, le jus de yuzu et l’eau. Faites tiédir le sirop avant imbibage.",
      "Imbibage des cakes Azur",
      "Cake Azur",
      "Sirop d’imbibage Azur",
      "Sur une grille, elle-même posée sur un candissoir, déposez les cakes tièdes et imbibez-les avec le sirop à deux reprises. Laissez bien égoutter et réservez au réfrigérateur sur une plaque filmée.",
      "Rectangle de chocolat noir au cacao",
      "Couverture Mexique 64% (Valrhona)",
      "Tempérez le chocolat et étalez 320 g de sur une feuille de plastique de 40 x 60 cm. Dès qu’il commence à cristalliser, coupez des rectangles de 12 x 6 cm pour les petits modèles et de 17 x 6 cm pour les grands modèles. Posez une feuille de papier siliconé et un poids dessus pour éviter que le chocolat ne se déforme en cristallisant. Laissez cristalliser à 16°C pendant 24 heures minimum",
      "Finition",
      "Rectangle de chocolat noir au cacao",
      "Ecorces de yuzu confit (Issé et Cie Workshop)",
      "Q.S de poudre Candurin Gold Lustre (Merck)",
      "Recouvrez les écorces avec la poudre candurin, passez-les sur un tamis pour retirer l’excédent. Posez les cakes sur carton or, posez le rectangle de chocolat noir au cacao bien centré sur le dessus en le collant avec une pointe de glucose. Sur un côté du cake, posez 3/4 écorces de yuzu confit or.",
      "Emballage",
      "Emballez-les en boîte PVC transparente et posez l’indication de la Date Limite de Vente (DLV).",
      "Conservation",
      "15 jours.",
      "Conseils de consommation",
      "A garder hors du réfrigérateur avant consommation.",
      "Boissons conseillées",
      "Eau minérale, PX Pedro Ximenez, thé Azur.",
      "Tableau récapitulatif de poids",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Cake Azur 10.04.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "sirop-d-imbibage-c-bon",
    nom: "Sirop d’imbibage C’Bon",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop d’imbibage C’Bon — recette importée, à vérifier.",
    masse_totale_g: 1455,
    ingredients: [
      { nom: "caramel liquide", g: 1000.0, pct: 68.7, role: "parfum" },
      { nom: "eau minérale", g: 300.0, pct: 20.6, role: "eau" },
      { nom: "jus de citron", g: 150.0, pct: 10.3, role: "acidite" },
      { nom: "arôme Toffee (Sosa)", g: 5.0, pct: 0.3, role: "parfum" },
    ],
    procede: [
      "Mélangez tous les ingrédients ensemble. Utilisez aussitôt ou conserver au réfrigérateur.",
      "Imbibage des cakes C’Bon",
      "Cakes C’Bon",
      "Sirop d’imbibage C’Bon",
      "Sur une grille, elle-même posée sur un candissoir, déposez les cakes tièdes et imbibez-les avec le sirop à deux reprises. Laissez bien égoutter et réservez au réfrigérateur sur une plaque filmée.",
      "Finition",
      "Nappage neutre à chaud (Unipatis)",
      "Abricots moelleux entiers (HR Confiseur)",
      "Feuille d’or jaune",
      "Faites fondre le nappage neutre et nappez le dessus du cake C’bon. Déposez un abricot moelleux au centre, nappez-le et rehaussez-le de feuille d’or ainsi qu’aux deux coins du cake suivant la même diagonale.",
      "Emballage",
      "Emballez-les en boîte PVC transparente et posez l’indication de la Date Limite de Vente (DLV).",
      "Conservation",
      "15 jours.",
      "Conseils de consommation",
      "A garder hors du réfrigérateur avant consommation.",
      "Boissons conseillées",
      "Thé, café, chocolat chaud.",
      "Tableau récapitulatif de poids",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "citron"],
    parfum_principal: "citron",
    note_concepteur: "",
    source_interne: { fichier: "Cake C'Bon 10.09.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "sirop-d-imbibage",
    nom: "Sirop d’imbibage",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop d’imbibage — recette importée, à vérifier.",
    masse_totale_g: 450,
    ingredients: [
      { nom: "sirop à 1260 dit à 30°B", g: 400.0, pct: 88.9, role: "sucrant" },
      { nom: "eau minérale", g: 50.0, pct: 11.1, role: "eau" },
    ],
    procede: [
      "Mélangez le sirop à 30°B et l’eau. Faites tiédir le sirop avant imbibage.",
      "Imbibage",
      "Cake Carrément Chocolat",
      "Sirop d’imbibage",
      "Sur une grille, elle-même posée sur un candissoir, déposez les cakes tièdes et imbibez-les avec le sirop à deux reprises. Laissez bien égoutter et réservez au réfrigérateur.",
      "Rectangle de chocolat noir",
      "Couverture Mexique 64% (Valrhona)",
      "Tempérez le chocolat et étalez 320 g de sur une feuille de plastique de 40 x 60 cm. Dès qu’il commence à cristalliser, coupez des rectangles de 12 x 6 cm pour les petits modèles et de 17 x 6 cm pour les grands modèles. Posez une feuille de papier siliconé et un poids dessus pour éviter que le chocolat ne se déforme en cristallisant. Laissez cristalliser à 16°C pendant 24 heures minimum",
      "Carré Or",
      "Feuilles imprimés OR (PCB réf : FC07)",
      "Chocolat extra bitter 61% (Valrhona)",
      "Tempérez le chocolat, pesez 250 g sur une feuille imprimée or et égalisez à l’aide d’une palette coudée. Laissez cristalliser légèrement et détaillez des carrés de 4 cm à l’aide du rouleau découpoir ou d’une bicyclette. Posez une feuille de papier siliconé et un poids dessus pour éviter que le chocolat ne se déforme en cristallisant. Laissez cristalliser à 16°C pendant 24 heures minimum.",
      "Finition et emballage",
      "Posez les cakes sur carton or, posez le rectangle de chocolat noir bien centré sur le dessus en le collant avec une pointe de glucose, et un carré or en bas à droite. Emballez-les en boîte PVC transparente et posez l’indication de la Date Limite de Vente (DLV).",
      "Boissons conseillées",
      "Thés, café, chocolat.",
      "Conservation",
      "15 jours.",
      "Notes, conseils et astuces",
      "Tableau récapitulatif de poids",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Cake Carrement chocolat 08.05.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "sirop-d-imbibage-caramel",
    nom: "Sirop d’imbibage caramel",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop d’imbibage caramel — recette importée, à vérifier.",
    masse_totale_g: 1468,
    ingredients: [
      { nom: "caramel liquide", g: 1000.0, pct: 68.1, role: "parfum" },
      { nom: "eau minérale", g: 450.0, pct: 30.7, role: "eau" },
      { nom: "fleur de sel de Guérande", g: 12.5, pct: 0.9, role: "assaisonnement" },
      { nom: "arôme Toffee (Sosa)", g: 5.0, pct: 0.3, role: "parfum" },
    ],
    procede: [
      "Mélangez tous les ingrédients ensemble. Utilisez aussitôt ou conserver au réfrigérateur.",
      "Imbibage des cakes Infiniment caramel",
      "Cakes Infiniment caramel",
      "Sirop d’imbibage caramel",
      "Sur une grille, elle-même posée sur un candissoir, déposez les cakes tièdes et imbibez-les avec le sirop à deux reprises. Laissez bien égoutter et réservez au réfrigérateur sur une plaque filmée.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "caramel"],
    parfum_principal: "caramel",
    note_concepteur: "",
    source_interne: { fichier: "Cake Infiniment Caramel 10.05.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "imbibage-cafe-fort",
    nom: "Imbibage Café fort",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Imbibage Café fort — recette importée, à vérifier.",
    masse_totale_g: 1100,
    ingredients: [
      { nom: "café fort", g: 500.0, pct: 45.5, role: "parfum" },
      { nom: "sirop à 1260", g: 600.0, pct: 54.5, role: "sucrant" },
    ],
    procede: [
      "Mélangez ensemble.",
      "Imbibage",
      "Cake Infiniment café",
      "Sirop d’imbibage café fort",
      "Sur une grille, elle-même posée sur un candissoir, déposez les cakes tièdes et imbibez-les avec le sirop à deux reprises. Laissez bien égoutter et réservez au réfrigérateur.",
      "N.B : Il est indispensable que la cake soit imbibé jusqu’au poids indiqué dans le tableau récapitulatif des poids, sinon vous risquez d’avoir un cake sec, et pas moelleux a souhait.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "café"],
    parfum_principal: "café",
    note_concepteur: "",
    source_interne: { fichier: "Cake Inifiniment Café 10.03.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "sirop-a-30b",
    nom: "Sirop à 30°B",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop à 30°B — recette importée, à vérifier.",
    masse_totale_g: 1900,
    ingredients: [
      { nom: "sucre semoule", g: 1000.0, pct: 52.6, role: "sucrant" },
      { nom: "eau minérale", g: 900.0, pct: 47.4, role: "eau" },
    ],
    procede: [
      "Faites bouillir l’eau et le sucre",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Cake Mogador 07.12.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "sirop-imbibage-au-fruit-de-la-passion",
    nom: "Sirop imbibage au fruit de la passion",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop imbibage au fruit de la passion — recette importée, à vérifier.",
    masse_totale_g: 3000,
    ingredients: [
      { nom: "sirop à 30°B", g: 2000.0, pct: 66.7, role: "sucrant" },
      { nom: "purée de fruit de la passion (Boiron)", g: 600.0, pct: 20.0, role: "eau" },
      { nom: "eau minérale", g: 400.0, pct: 13.3, role: "eau" },
    ],
    procede: [
      "Mélangez le sirop à 30°B, la purée de fruit de la passion et l’eau minérale. Utilisez aussitôt ou stockez au réfrigérateur.",
      "Imbibage",
      "Cake Mogador tiède",
      "Sirop d’imbibage au fruit de la passion",
      "Déposez les cakes tièdes sur grille, elle-même posée sur un candissoir, imbibez-les avec le sirop d’imbibage au fruit de la passion à trois reprises. Laissez bien égoutter et refroidir. Stocker au réfrigérateur ou au congélateur",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Cake Mogador 07.12.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "sirop-imbibage-au-citron-et-bergamote",
    nom: "Sirop imbibage au citron et bergamote",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop imbibage au citron et bergamote — recette importée, à vérifier.",
    masse_totale_g: 3001,
    ingredients: [
      { nom: "sirop à 1260", g: 2000.0, pct: 66.6, role: "sucrant" },
      { nom: "jus de citron", g: 600.0, pct: 20.0, role: "acidite" },
      { nom: "essence de bergamote (Sévarôme)", g: 1.0, pct: 0.0, role: "parfum" },
      { nom: "eau minérale", g: 400.0, pct: 13.3, role: "eau" },
    ],
    procede: [
      "Mélangez le sirop à 1260, le jus de citron et l’eau minérale. Faites bouillir le sirop et ajoutez l’essence de bergamote.",
      "Imbibage",
      "Cake au citron tiède",
      "Sirop imbibage au citron et bergamote",
      "Déposez les cakes sur grille, elle-même posée sur un candissoire, imbibez-les avec le sirop au citron et bergamote à trois reprises. Laissez bien égoutter avant de procéder à la finition et à l’emballage.",
      "Finition",
      "Nappage neutre à chaud (Patisfrance)",
      "Ecorces de citron confit (Confiserie St Sylvestre)",
      "Faites chauffez le nappage neutre et à l’aide d’un pinceau, nappez le dessus du cake citron. Posez 5 écorces de citron confit et nappez-les de nappage neutre. Stockez au réfrigérateur en vue de l’emballage.",
      "Emballage",
      "Emballez les cakes dans les boites PVC pliable ; appliquez l’autocollant  rectangulaire et noir, siglé PH centré au dessus puis en dessous l’adhésif indiquant la date limite de vente et la composition.",
      "Dimensions des boites à cake : hauteur unique pour les deux modèles ; pour le petit cake 16 x 9 cm et pour le grand : 19 x 9 cm.",
      "Boissons conseillées",
      "Thés, café, chocolat.",
      "Tableau récapitulatif de poids",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "citron"],
    parfum_principal: "citron",
    note_concepteur: "",
    source_interne: { fichier: "Cake au citron 10.09.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "sirop-d-imbibage-au-yuzu",
    nom: "Sirop d’imbibage au yuzu",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop d’imbibage au yuzu — recette importée, à vérifier.",
    masse_totale_g: 3000,
    ingredients: [
      { nom: "sucre semoule", g: 1050.0, pct: 35.0, role: "sucrant" },
      { nom: "jus de yuzu sucré", g: 600.0, pct: 20.0, role: "sucrant" },
      { nom: "eau minérale", g: 1350.0, pct: 45.0, role: "eau" },
    ],
    procede: [
      "Faites bouillir ensemble et utilisez aussitôt.",
      "Imbibage",
      "Sur une grille, elle-même posée sur un candissoir inox, déposez les cakes tièdes et imbibez-les avec le sirop à trois reprises. Laissez bien égoutter et réservez au réfrigérateur.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Cake the vert Matcha yuzu 09.05.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "sirop-d-imbibage-a-baba",
    nom: "Sirop d’imbibage à baba",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop d’imbibage à baba — recette importée, à vérifier.",
    masse_totale_g: 846,
    ingredients: [
      { nom: "eau minérale", g: 500.0, pct: 59.1, role: "eau" },
      { nom: "sucre semoule", g: 250.0, pct: 29.6, role: "sucrant" },
      { nom: "(1 pièce) de gousse de vanille de Madagascar", g: 4.0, pct: 0.5, role: "parfum" },
      { nom: "zeste de citron jaune", g: 5.0, pct: 0.6, role: "liant" },
      { nom: "zeste d'orange", g: 12.0, pct: 1.4, role: "parfum" },
      { nom: "purée d'ananas (Boiron)", g: 25.0, pct: 3.0, role: "eau" },
      { nom: "rhum brun agricole (Clément)", g: 50.0, pct: 5.9, role: "parfum" },
    ],
    procede: [
      "A l’aide d’un économe, prélevez les zestes et mettez-les dans l’eau avec le sucre et la gousse de vanille fendue et grattée. Faites bouillir. Ajoutez la purée d’ananas et le rhum brun. Utilisez à 50°C ou stockez au réfrigérateur.",
      "N.B. : vous pouvez laissez les zestes et la gousse de vanille dans le sirop.",
      "Imbibage des babas",
      "Q.S de babas cuits",
      "Q.S de sirop d’imbibage à baba",
      "Q.S de rhum brun",
      "Dans une grande casserole, faites chauffer le sirop d’imbibage à baba à 50°C. Mettez les babas dans la casserole pendant 5 minutes en prenant soin de les tourner et de les arroser régulièrement. Une fois imbibés, à l’aide d’une écumoire, sortez les babas et posez-les sur une grille. Arrosez-les généreusement de rhum brun. Servez aussitôt ou réservez sur une plaque.",
      "Tableau récapitulatif de poids",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["oeuf"],
    tags: ["sirop", "vanille"],
    parfum_principal: "vanille",
    note_concepteur: "",
    source_interne: { fichier: "Baba au rhum 10.02.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "sirop-candi",
    nom: "Sirop candi",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop candi — recette importée, à vérifier.",
    masse_totale_g: 2800,
    ingredients: [
      { nom: "sucre semoule", g: 2000.0, pct: 71.4, role: "sucrant" },
      { nom: "eau minérale", g: 800.0, pct: 28.6, role: "eau" },
    ],
    procede: [
      "Faites bouillir en prenant soin d’enlever les impuretés avec une écumoire et nettoyez les bords avec un pinceau mouillé. Mesurez la densité à 1300 sur le pèse-sirop. Versez dans un récipent et laissez refroidir sans couvrir et couvrez ensuite.",
      "Sucre cristallisé",
      "Sirop à candi",
      "QS de sucre semoule",
      "Versez le sirop candi froid dans un candissoir ; parsemez légèrement de sucre semoule. Laissez cristalliser 72 heures. Retirez le couvercle cristallisé et posez les morceaux sur grilles pour égoutter. Stockez en boîtes hermétiques à l’abri de l’humidité. Saupoudrez le restant de sucre semoule et recommencez le processus.",
      "Embouts doré",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Buche Nuage 06.07.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "sirop-au-rhum",
    nom: "Sirop au rhum",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop au rhum — recette importée, à vérifier.",
    masse_totale_g: 220,
    ingredients: [
      { nom: "eau", g: 70.0, pct: 31.8, role: "eau" },
      { nom: "sucre semoule", g: 75.0, pct: 34.1, role: "sucrant" },
      { nom: "vieux rhum brun agricole", g: 75.0, pct: 34.1, role: "parfum" },
    ],
    procede: [
      "Dans une casserole faites bouillir ensemble l'eau et le sucre, remuer avec une cuillère en bois. Laissez refroidir le sirop et ajoutez le vieux rhum lorsque le liquide est parfaitement froid. Réservez au frais.",
      "Deux heures avant :",
      "Egouttez dans une passoire 150 g de cassis en grains, au sirop, en conserve ou en bocaux.",
      "Pâte à biscuit à la cuillère",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Buche aux marrons rhum et grains de cassis 95.08.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "imbibage-vieux-rhum-brun-agricole",
    nom: "Imbibage vieux rhum brun agricole",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Imbibage vieux rhum brun agricole — recette importée, à vérifier.",
    masse_totale_g: 440,
    ingredients: [
      { nom: "eau minérale", g: 140.0, pct: 31.8, role: "eau" },
      { nom: "sucre semoule", g: 150.0, pct: 34.1, role: "sucrant" },
      { nom: "vieux rhum brun agricole", g: 150.0, pct: 34.1, role: "parfum" },
    ],
    procede: [
      "Dans une casserole, faites bouillir l’eau et le sucre et ajoutez le rhum. Utilisez aussitôt ou stockez en boite hermétique au réfrigérateur.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Buche marron Isetan Japon 2009 09.06.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "imbibage-a-la-vanille",
    nom: "Imbibage à la vanille",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Imbibage à la vanille — recette importée, à vérifier.",
    masse_totale_g: 1582,
    ingredients: [
      { nom: "eau minérale", g: 1000.0, pct: 63.2, role: "eau" },
      { nom: "(1 pièce) de gousse de vanille Mexique fendue, grattée", g: 4.0, pct: 0.3, role: "parfum" },
      { nom: "(1 pièce) de gousse de vanille Madagascar fendue, grattée", g: 4.0, pct: 0.3, role: "parfum" },
      { nom: "(1 pièce) de gousse de vanille Tahiti fendue, grattée", g: 4.0, pct: 0.3, role: "parfum" },
      { nom: "extrait de vanille liquide sans alcool", g: 20.0, pct: 1.3, role: "parfum" },
      { nom: "sucre semoule", g: 500.0, pct: 31.6, role: "sucrant" },
      { nom: "vieux rhum brun agricole (Clément)", g: 50.0, pct: 3.2, role: "parfum" },
    ],
    procede: [
      "Fendez et grattez les gousses de vanille, mettez-les dans l’eau et le sucre, portez à ébullition et laissez infuser pendant 30 minutes au moins. Ajoutez l’extrait de vanille liquide et le rhum. Réservez en boîte hermétique au réfrigérateur.",
      "NB : les gousses de vanille peuvent rester dans le sirop.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "vanille"],
    parfum_principal: "vanille",
    note_concepteur: "",
    source_interne: { fichier: "Bûche Infiniment Vanille Japon 2009 09.05.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "sirop-d-imbibage-a-la-vanille",
    nom: "Sirop d’imbibage à la vanille",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop d’imbibage à la vanille — recette importée, à vérifier.",
    masse_totale_g: 1582,
    ingredients: [
      { nom: "eau minérale", g: 1000.0, pct: 63.2, role: "eau" },
      { nom: "(1 pièce) de gousse de vanille Mexique fendue, grattée", g: 4.0, pct: 0.3, role: "parfum" },
      { nom: "(1 pièce) de gousse de vanille Madagascar fendue, grattée", g: 4.0, pct: 0.3, role: "parfum" },
      { nom: "(1 pièce) de gousse de vanille Tahiti fendue, grattée", g: 4.0, pct: 0.3, role: "parfum" },
      { nom: "extrait de vanille liquide sans alcool", g: 20.0, pct: 1.3, role: "parfum" },
      { nom: "sucre semoule", g: 500.0, pct: 31.6, role: "sucrant" },
      { nom: "vieux rhum brun agricole (Clément)", g: 50.0, pct: 3.2, role: "parfum" },
    ],
    procede: [
      "Fendez et grattez les gousses de vanille, mettez-les dans l’eau et le sucre, portez à ébullition et laissez infuser pendant 30 minutes au moins. Ajoutez l’extrait de vanille liquide et le rhum. Réservez en boîte hermétique au réfrigérateur.",
      "NB : les gousses de vanille peuvent rester dans le sirop.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "vanille"],
    parfum_principal: "vanille",
    note_concepteur: "",
    source_interne: { fichier: "Coeur Infiniment Vanille 10.02.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "sirop-a-candi",
    nom: "Sirop à candi",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop à candi — recette importée, à vérifier.",
    masse_totale_g: 700,
    ingredients: [
      { nom: "sucre semoule", g: 500.0, pct: 71.4, role: "sucrant" },
      { nom: "eau minérale", g: 200.0, pct: 28.6, role: "eau" },
    ],
    procede: [
      "Faites bouillir en prenant soin d’enlever les impuretés avec une écumoire et nettoyez les bords avec un pinceau mouillé. Mesurez la densité à 1300 sur le pèse-sirop. Laissez refroidir sans couvrir et couvrez ensuite.",
      "Disque de sucre cristallisé",
      "Sirop à candi",
      "QS de sucre semoule",
      "Versez le sirop à candi froid à mi-hauteur dans les dômes flexipans 7 cm Ø; parsemez légèrement de sucre semoule. Laissez cristalliser 48 heures. Retirez le couvercle cristallisé et posez-les sur grilles pour égoutter.",
      "Saupoudrez à nouveau de sucre semoule et recommencez le processus.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Emotion Cristal 05.07.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "sirop-d-imbibage-aux-agrumes",
    nom: "Sirop d’imbibage aux agrumes",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop d’imbibage aux agrumes — recette importée, à vérifier.",
    masse_totale_g: 1662,
    ingredients: [
      { nom: "eau minérale", g: 950.0, pct: 57.1, role: "eau" },
      { nom: "sucre semoule", g: 500.0, pct: 30.1, role: "sucrant" },
      { nom: "jus de citron", g: 150.0, pct: 9.0, role: "acidite" },
      { nom: "zestes de citron jaune", g: 12.0, pct: 0.7, role: "liant" },
      { nom: "arôme de fleur d'oranger (60% Robertet réf : 818322)", g: 50.0, pct: 3.0, role: "parfum" },
      { nom: "huile essentielle de bergamote (Sevarome)", g: 0.5, pct: 0.0, role: "mg" },
    ],
    procede: [
      "Faites bouillir l’eau, le sucre, le jus et les zestes de citron. Ajoutez l’eau de fleur d’oranger et l’huile essentielle de bergamote. Réservez en boîte hermétique au réfrigérateur.",
      "Imbibage des babas",
      "Q.S de babas cuits",
      "Q.S de sirop d’imbibage aux agrumes",
      "Dans une grande casserole, faites chauffer le sirop d’imbibage aux agrumes à 50°C. Mettez les babas dans la casserole pendant 5 minutes en prenant soin de les tourner et de les arroser régulièrement. Une fois imbibés, à l’aide d’une écumoire, sortez les babas et posez-les sur une grille afin qu’ils s’égouttent. Réservez sur une plaque.",
      "Segments de citrons jaunes et d’oranges à vif",
      "Q.S de citrons jaunes",
      "Q.S d’oranges",
      "Coupez les deux extrémités des fruits. A l’aide d’un couteau, détachez-en le zeste, de haut, en bas en larges copeaux. Prélevez les segments. Stockez au réfrigérateur. Egouttez les segments avant utilisation.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["oeuf"],
    tags: ["sirop", "citron"],
    parfum_principal: "citron",
    note_concepteur: "",
    source_interne: { fichier: "Emotion Eau de Rochas 10.06.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "imbibage-au-cafe",
    nom: "Imbibage au café",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Imbibage au café — recette importée, à vérifier.",
    masse_totale_g: 1110,
    ingredients: [
      { nom: "café fort", g: 500.0, pct: 45.0, role: "parfum" },
      { nom: "sirop à 1260", g: 600.0, pct: 54.1, role: "sucrant" },
      { nom: "nescafé Alta Rica", g: 10.0, pct: 0.9, role: "parfum" },
    ],
    procede: [
      "Mélangez les ingrédients ensemble. Utilisez aussitôt ou stockez en boîte hermétique au réfrigérateur.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "café"],
    parfum_principal: "café",
    note_concepteur: "",
    source_interne: { fichier: "Emotion Veloute 10.01.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "imbibage-fraisier",
    nom: "Imbibage Fraisier",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Imbibage Fraisier — recette importée, à vérifier.",
    masse_totale_g: 1500,
    ingredients: [
      { nom: "sirop à 1260", g: 1000.0, pct: 66.7, role: "sucrant" },
      { nom: "liqueur de framboise", g: 250.0, pct: 16.7, role: "parfum" },
      { nom: "Kirsch pur", g: 250.0, pct: 16.7, role: "parfum" },
    ],
    procede: [
      "Mélangez tous les ingrédients, utilisez aussitôt ou stockez en boite hermétique au réfrigérateur.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "framboise"],
    parfum_principal: "framboise",
    note_concepteur: "",
    source_interne: { fichier: "Fraisier 09.02.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "sirop-leger-pour-les-tranches-de-citron-vert",
    nom: "Sirop léger pour les tranches de citron vert",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop léger pour les tranches de citron vert — recette importée, à vérifier.",
    masse_totale_g: 3000,
    ingredients: [
      { nom: "eau minérale", g: 2000.0, pct: 66.7, role: "eau" },
      { nom: "sucre semoule", g: 1000.0, pct: 33.3, role: "sucrant" },
    ],
    procede: [
      "Faites bouillir ensemble l’eau minérale et le sucre semoule. Réservez.",
      "Fines tranches de citron vert croquantes",
      "QS de citron vert",
      "Tranchez les extrémités des citrons verts et placez-les au congélateur ; sortez-les une dizaine de minutes avant de les couper en fines tranches à 1,5 à la machine à jambon ; plongez ces tranches dans le sirop léger tiède, laissez macérer pendant 24 heures. Le lendemain coupez les tranchez en deux à l’aide d’une pair de ciseaux et déposez sur une plaque noire recouverte d’un tapis Silpat, glissez directement dans un four ventilé à 70 °C, pendant 8 heures au moins. Laissez refroidir et stockez à l’abri de l’humidité avec des pastilles déshydratantes.",
      "Pâte de citron vert maison",
      "Citrons verts non traités",
      "Dans une cocotte minute faites bouillir l’eau; plongez-y les citrons verts, fermez la cocotte et faites chauffer à feu vif, réglé le chronomètre intégré à 8 minutes, il se déclenchera automatiquement lorsque la pression exercée par la vapeur sera suffisante.  Le temps écoulé, refroidissez la cocotte sous l’eau froide et retirez les citrons verts avant de les faire égoutter. Laissez bien refroidir et mixez finement au robot-coupe. Stockez au congélateur.",
      "Pâte de citron maison",
      "Citrons non traités",
      "Dans une cocotte minute faites bouillir l’eau; plongez-y les citrons, fermez la cocotte et faites chauffer à feu vif, réglé le chronomètre intégré à 7 minutes, il se déclenchera automatiquement lorsque la pression exercée par la vapeur sera suffisante.  Le temps écoulé, refroidissez la cocotte sous l’eau froide et retirez les citrons avant de les faire égoutter. Laissez bien refroidir et mixez finement au robot-coupe. Stockez au congélateur.",
    ],
    cuisson: { temperature_c: 70, duree_min: null, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "citron"],
    parfum_principal: "citron",
    note_concepteur: "",
    source_interne: { fichier: "Herme carre Mandarine Pommes Baies roses 05.08.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "sirop-de-menthe-fraiche",
    nom: "Sirop de menthe fraîche",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop de menthe fraîche — recette importée, à vérifier.",
    masse_totale_g: 3500,
    ingredients: [
      { nom: "sucre semoule", g: 1000.0, pct: 28.6, role: "sucrant" },
      { nom: "eau", g: 400.0, pct: 11.4, role: "eau" },
      { nom: "feuilles de menthe fraîche", g: 200.0, pct: 5.7, role: "parfum" },
      { nom: "sucre", g: 1000.0, pct: 28.6, role: "sucrant" },
      { nom: "eau", g: 900.0, pct: 25.7, role: "eau" },
    ],
    procede: [
      "Hachez la menthe grossièrement. Faites bouillir l'eau et le sucre, retirez du feu et ajoutez la menthe fraîche ; laissez infuser ½ heure, non couvert, avant de passer au blender. Vous pouvez stocker ce sirop au congélateur en bacs hermétiques.",
      "Sirop à 30°B",
      "Portez à ébullition et mesurer à 28° B chaud ce qui donne 30° B froid. Laissez refroidir.",
      "Imbibage menthe fraîche",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Millefeuille aux fruits rouges et menthe fraiche 00.12.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "sirop-au-cafe",
    nom: "Sirop au café",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop au café — recette importée, à vérifier.",
    masse_totale_g: 545,
    ingredients: [
      { nom: "eau de source", g: 300.0, pct: 55.0, role: "eau" },
      { nom: "café Colombie moulu", g: 100.0, pct: 18.3, role: "parfum" },
      { nom: "eau de source", g: 75.0, pct: 13.8, role: "eau" },
      { nom: "sucre semoule", g: 70.0, pct: 12.8, role: "sucrant" },
    ],
    procede: [
      "Dans une casserole en inox, faites bouillir l'eau (70 g) et le sucre. Dans une seconde casserole, faites bouillir l'eau (300 g), versez le café et filtrez aussitôt dans une passoire moyenne puis dans une passoire fine de manière à éliminer au maximum le marc. Mélangez les deux préparations et réservez au frais. Tranchez la génoise en trois parties égales dans l'épaisseur, à l'aide d'un couteau scie. Taillez un carton épais de 22 cm de diamètre, sur lequel vous posez le premier disque de génoise ; au pinceau, imbibez-le très légèrement ; étalez la moitié de la crème légère moka, recouvrez d'un second disque de génoise, généreusement imbibé ; étalez le restant de crème d'une dernière couche de génoise. Appuyez-le avec la paume de la main ; imbibez à nouveau. Avec une petite palette, lissez le tour de l'entremets pour égaliser les coulures de crème qui pourraient subsister, réservez au froid pour 3 heures.",
      "Masquez et lissez le pourtour du moka avec la crème au beurre café en deux opérations consécutives. Tapissez le bord inférieur du moka, d'amandes hachées ou effilées, grillées ; décorez la partie supérieure avec une poche à douille munie d'une douille cannelée garnie de crème au beurre café et de quelques grains de café au chocolat.",
      "Pour consommer le moka, il est préférable de laisser 48 heures au réfrigérateur, il se produit pendant ce laps de temps une osmose entre les différents composants du gâteau, qui en développe et affine le goût et la texture.",
      "Sortez du réfrigérateur une heure avant consommation.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop", "café"],
    parfum_principal: "café",
    note_concepteur: "",
    source_interne: { fichier: "Moka.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "imbibage-caramel",
    nom: "Imbibage caramel",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Imbibage caramel — recette importée, à vérifier.",
    masse_totale_g: 1600,
    ingredients: [
      { nom: "sucre semoule", g: 500.0, pct: 31.2, role: "sucrant" },
      { nom: "beurre demi-sel", g: 100.0, pct: 6.2, role: "mg" },
      { nom: "eau", g: 1000.0, pct: 62.5, role: "eau" },
    ],
    procede: [
      "Faites caraméliser le sucre, décuisez avec le beurre puis l’eau.",
      "Montage :",
      "En cadre 39 x 59 cm. Mettez une couche de biscuit dans le fond; imbibez de sirop caramel (300 g); recouvrez avec 2,5 kg de ganache. Renouvelez l’opération et recouvrez d’une troisième couche de biscuit que vous imbibez avec 250 g de sirop caramel. Gardez au réfrigérateur 12 heures au moins.",
      "Finition :",
      "Coupez en 7 bandes dans la longueur. Masquez à la ganache. Nappez au miroir chocolat. Décorez le tour avec des demis macarons chocolat. Le dessus est décoré de bâtonnets de caramel.",
      "Conseils de consommation :",
      "Sortir du réfrigérateur 2 heures avant consommation.",
      "Boissons conseillées :",
      "Eau minérale, Maury Mas Amiel vintage.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["lait"],
    tags: ["sirop", "caramel"],
    parfum_principal: "caramel",
    note_concepteur: "",
    source_interne: { fichier: "Pave du Faubourg 97.02.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "imbibage-noisette",
    nom: "Imbibage noisette",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Imbibage noisette — recette importée, à vérifier.",
    masse_totale_g: 1650,
    ingredients: [
      { nom: "sirop ˆ 30¡B", g: 1000.0, pct: 60.6, role: "sucrant" },
      { nom: "eau", g: 500.0, pct: 30.3, role: "eau" },
      { nom: "p‰te de noisette du Pimont", g: 150.0, pct: 9.1, role: "parfum" },
    ],
    procede: [
      "Mlanger dans l'ordre",
      "Biscuit amande :",
      "Tamiser",
      "Monter",
      "Monter les blancs avec le sucre semoule puis ˆ la main incorporer le mlange sucre glace, amandes et farine. Utiliser un chablon de 1,5 cm d'paisseur, 2 cm plus petit que le cercle ou dresser ˆ la poche avec une douille n¡ 9, sur tapis silicone. Cuire ˆ 170¡C, bu ouverte. Ce biscuit doit rester trs moelleux tel un macaron.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["fruits_a_coque"],
    tags: ["sirop", "noisette"],
    parfum_principal: "noisette",
    note_concepteur: "",
    source_interne: { fichier: "Royal 96.08.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "punch-passion-trinitario",
    nom: "Punch passion trinitario",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Punch passion trinitario — recette importée, à vérifier.",
    masse_totale_g: 1350,
    ingredients: [
      { nom: "sirop à 22°", g: 1000.0, pct: 74.1, role: "sucrant" },
      { nom: "pulpe passion", g: 250.0, pct: 18.5, role: "parfum" },
      { nom: "pulpe d'abricot", g: 50.0, pct: 3.7, role: "fruit" },
      { nom: "abricotine Morand (eau de vie)", g: 50.0, pct: 3.7, role: "eau" },
    ],
    procede: [
      "Montage et finition:",
      "Passer au grand froid la mousse passion dans des petits moules, puis démouler.",
      "Faire le montage dans des cercles à petits gâteaux de forme exagonale, les chemiser de chocolat, puis enfoncer au centre la mousse passion congelée. Terminer par une couche de génoise punchée au sirop passion. Passer au grand froid.",
      "Décercler, retourner les gâteaux, pulvériser au pistolet chocolat, décorer le tour de plaquettes chocolat de 3 couleurs.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Trinitario 99.05.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "frangipane-chartreuse",
    nom: "FRANGIPANE CHARTREUSE",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "FRANGIPANE CHARTREUSE — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "CREME AMANDE", g: 634.9, pct: 63.5, role: "parfum" },
      { nom: "CREME PATISSIERE", g: 317.5, pct: 31.7, role: "eau" },
      { nom: "CHARTREUSE", g: 47.6, pct: 4.8, role: "parfum" },
    ],
    procede: [
      "0.0",
      "0.0",
      "0.0",
      "0.0",
      "0.0",
      "0.0",
      "0.0",
      "0.0",
      "0.0",
      "0.0",
      "0.0",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["fruits_a_coque", "lait"],
    tags: ["sirop", "amande"],
    parfum_principal: "amande",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "FRANGIPANE CHARTREUSE.xls", import: "extraction-2026-08-25" },
  },
  {
    id: "pruneaux-d-agen-au-sirop",
    nom: "Pruneaux d'Agen au sirop",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Pruneaux d'Agen au sirop — recette importée, à vérifier.",
    masse_totale_g: 20000,
    ingredients: [
      { nom: "Eau", g: 8000.0, pct: 40.0, role: "eau" },
      { nom: "Sucre", g: 2000.0, pct: 10.0, role: "sucrant" },
      { nom: "Pruneaux", g: 10000.0, pct: 50.0, role: "eau" },
    ],
    procede: [
      "Faire bouillir tous les ingrédients dans une casserole, puis verser sur les pruneaux au vin. Laisser macérer une nuit avant de déguster.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Pruneaux d'Agen au sirop.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "sirop-au-kirsh",
    nom: "Sirop au kirsh",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop au kirsh — recette importée, à vérifier.",
    masse_totale_g: 135,
    ingredients: [
      { nom: "eau", g: 100.0, pct: 74.1, role: "eau" },
      { nom: "sucre", g: 20.0, pct: 14.8, role: "sucrant" },
      { nom: "kirsh", g: 15.0, pct: 11.1, role: "parfum" },
    ],
    procede: [
      "Porter à ébullition l’eau et le sucre semoule, débarrasser dans un bol et laisser refroidir avant d’incorporer le kirsh.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Griotte amande et dragée.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "sirop",
    nom: "Sirop",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop — recette importée, à vérifier.",
    masse_totale_g: 450,
    ingredients: [
      { nom: "sirop à 30°c", g: 300.0, pct: 66.7, role: "sucrant" },
      { nom: "purée de mandarine", g: 150.0, pct: 33.3, role: "eau" },
    ],
    procede: [
      "Mélanger le sirop et la purée de mandarine ensemble et réserver.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Millecake au thé vert.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "punch-au-whisky",
    nom: "Punch au whisky",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Punch au whisky — recette importée, à vérifier.",
    masse_totale_g: 140,
    ingredients: [
      { nom: "eau", g: 80.0, pct: 57.1, role: "eau" },
      { nom: "sucre semoule", g: 40.0, pct: 28.6, role: "sucrant" },
      { nom: "whisky tourbé", g: 20.0, pct: 14.3, role: "parfum" },
    ],
    procede: [
      "incorporer une partie de ce mélange au beurre fondu froid, et mélanger délicatement les deux masses ensemble.",
      "Ajouter les blanc d’œufs monté mousseux et le cacao en poudre.",
      "Etaler sur une plaque de 40x30 et cuire 5 à 6 minutes.",
    ],
    cuisson: { temperature_c: null, duree_min: 6, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Sidéral.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "sirop-au-the-jasmin",
    nom: "Sirop au thé jasmin",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop au thé jasmin — recette importée, à vérifier.",
    masse_totale_g: 700,
    ingredients: [
      { nom: "eau", g: 500.0, pct: 71.4, role: "eau" },
      { nom: "sucre semoule", g: 200.0, pct: 28.6, role: "sucrant" },
    ],
    procede: [
      "Ajouter les sachets de thé jasmin, laisser infuser.",
      "Réhydrater les poires tapées dans le sirop.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Souvenir d'enfance.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "sirop-framboise-badiane",
    nom: "Sirop framboise-badiane",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop framboise-badiane — recette importée, à vérifier.",
    masse_totale_g: 1200,
    ingredients: [
      { nom: "jus de framboise", g: 420.0, pct: 35.0, role: "eau" },
      { nom: "jus de citron jaune frais", g: 80.0, pct: 6.7, role: "liant" },
      { nom: "eau", g: 500.0, pct: 41.7, role: "eau" },
      { nom: "sucre semoule", g: 200.0, pct: 16.7, role: "sucrant" },
    ],
    procede: [
      "Mettre au bain-marie et laisser cuire environ 2 heures, jusqu’à obtenir une quantité de jus importante.",
      "Passer au chinois étamine.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["oeuf"],
    tags: ["sirop", "citron"],
    parfum_principal: "citron",
    note_concepteur: "",
    source_interne: { fichier: "Baba-cool.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "sirop-de-pochage",
    nom: "Sirop de pochage",
    categorie: "sirops",
    sous_categorie: "sirop",
    description: "Sirop de pochage — recette importée, à vérifier.",
    masse_totale_g: 690,
    ingredients: [
      { nom: "figues", g: 375.0, pct: 54.3, role: "parfum" },
      { nom: "eau", g: 225.0, pct: 32.6, role: "eau" },
      { nom: "sucre", g: 75.0, pct: 10.9, role: "sucrant" },
      { nom: "xérès", g: 15.0, pct: 2.2, role: "parfum" },
    ],
    procede: [
      "Faire bouillir l’eau, le sucre, le vinaigre et les figues coupées en quatre.",
      "Laisser mijoter 10 minutes puis laisser macérer 12 h.",
      "Faire ensuite rôtir les figues a four dans leur jus.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sirop"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Eclair au figues et noix.docx", import: "extraction-2026-08-25" },
  },
];
