export const RECETTES_TRAITEUR = [

  // === Import extraction-2026-08-25 (19 recettes) ===
  {
    id: "avocado-toast",
    nom: "Avocado toast",
    categorie: "traiteur",
    sous_categorie: "snacking",
    description: "Avocado toast — recette importée, à vérifier.",
    masse_totale_g: 4463,
    ingredients: [
      { nom: "Farine tradition", g: 2000.0, pct: 44.8, role: "structure" },
      { nom: "Sel", g: 40.0, pct: 0.9, role: "assaisonnement" },
      { nom: "Levure", g: 10.0, pct: 0.2, role: "levant" },
      { nom: "Levain liquide", g: 500.0, pct: 11.2, role: "levant" },
      { nom: "Eau coulage", g: 1320.0, pct: 29.6, role: "eau" },
      { nom: "Eau de bassinage", g: 60.0, pct: 1.3, role: "eau" },
      { nom: "Graine", g: 533.0, pct: 11.9, role: "parfum" },
    ],
    procede: [
      "*Autolyse = (T° du labo + T° de la farine) - TB 56° C = T° eau de coulage",
      "Pétrissage pétrin spirale. Faire une autolyse :  Pétrir 3 minutes en 1ère vitesse, puis laisser 30 minutes à 2 heures. Ajouter le sel et la levure. Pétrir 4 minutes environ en 1ère vitesse et ajouter le levain liquide et l’eau de bassinage puis pétrir jusqu’à décollement en 1ère vitesse. Température de pâte 22°C à 24°C. Pointage 1 heure avec rabat à 30 minutes puis 12h/18h à 2°C. Pesage 700g. Détente 10 à 30 minutes. Façonnage Cadre. Apprêt 45 minutes à 1 heure. Cuisson 250°C/260°C temps de cuisson en fonction des pièces.",
      "Guacamole :",
      "Avocat				5 Pce",
      "Jus de citron			25g",
      "Huile d’olive			25g",
      "Sel 				PM",
      "Poivre				PM",
      "Piment d’Espelette 		PM",
      "Eplucher les avocats et mixer tous les ingrédients, puis mettre en poche.",
      "Montage :",
      "Pain Céréale tranche 		180g",
      "Guacamole			50g",
      "Tranche d’avocat couper	50g",
      "Œuf de caille au plats 		3 Pce",
      "Salade vert",
      "Graine de chia",
      "Huile d’olive",
    ],
    cuisson: { temperature_c: null, duree_min: 3, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten"],
    tags: ["snacking"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Avocado toast.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "egg-toast",
    nom: "Egg Toast",
    categorie: "traiteur",
    sous_categorie: "snacking",
    description: "Egg Toast — recette importée, à vérifier.",
    masse_totale_g: 6700,
    ingredients: [
      { nom: "Lait", g: 1200.0, pct: 17.9, role: "eau" },
      { nom: "Levure", g: 150.0, pct: 2.2, role: "levant" },
      { nom: "Farine T45", g: 3300.0, pct: 49.3, role: "structure" },
      { nom: "Œufs entiers", g: 600.0, pct: 9.0, role: "liant" },
      { nom: "Sel fin", g: 50.0, pct: 0.7, role: "assaisonnement" },
      { nom: "Sucre semoule", g: 200.0, pct: 3.0, role: "sucrant" },
      { nom: "Beurre pommade", g: 300.0, pct: 4.5, role: "mg" },
      { nom: "Beurre de tourage", g: 900.0, pct: 13.4, role: "mg" },
    ],
    procede: [
      "Faire tourner en 1ière vitesse pour un simple mélange puis en 2ième vitesse jusqu’à ce que la pâte qui se décolle des parois. Incorporer le beurre pommade. Pétrir jusqu’à l’obtention d’une pâte homogène (T 24-25 °C)",
      "Pointage à température ambiante pendant 1 heure avec un torchon humide. Dégazer puis beurrer. Un tour double, un tour simple.",
      "Etaler le pâton dans la largeur du beurre et mettre au congel 45 minutes puis remettre au frigo. Faire le pâton avec le beurre sec avec l’ouverture mise en perpendiculaire par rapport au laminoir. Faire un tour double étalé à 7 mm d’épaisseur reposer 10 minutes au frigo. Faire un tour simple étalé à 10 mm puis directement étaler à 4 mm",
      "Houmous de mais :",
      "Mais frais 			200g",
      "Sel				5g",
      "Poivre				2g",
      "Mixé le tous au termomix",
      "Montage :",
      "Brioche feuilleter toaster",
      "Cheddar",
      "Bacon",
      "Houmous de mais",
      "Crispi Bacon",
      "Œuf au plats",
      "Sel",
      "Poivre",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten", "lait", "oeuf"],
    tags: ["snacking"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Egg Toast.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "condiment-moutarde",
    nom: "Condiment moutarde",
    categorie: "traiteur",
    sous_categorie: "sauce_salee",
    description: "Condiment moutarde — recette importée, à vérifier.",
    masse_totale_g: 120,
    ingredients: [
      { nom: "cornichons", g: 25.0, pct: 20.8, role: "parfum" },
      { nom: "oignons confits", g: 38.0, pct: 31.7, role: "parfum" },
      { nom: "moutarde", g: 38.0, pct: 31.7, role: "parfum" },
      { nom: "moutarde à l'ancienne", g: 19.0, pct: 15.8, role: "parfum" },
    ],
    procede: [
      "Le jour même, couper les cornichons en brunoise, puis les mélanger intimement avec les oignons confits, la moutarde douce et la moutarde à l’ancienne.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["moutarde"],
    tags: ["sauce salee"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Hot dog.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "jambon-beurre",
    nom: "Jambon Beurre",
    categorie: "traiteur",
    sous_categorie: "sale_proteine",
    description: "Jambon Beurre — recette importée, à vérifier.",
    masse_totale_g: 3930,
    ingredients: [
      { nom: "Farine de tradition", g: 1700.0, pct: 43.3, role: "structure" },
      { nom: "Farine Seigle", g: 300.0, pct: 7.6, role: "structure" },
      { nom: "Sel", g: 40.0, pct: 1.0, role: "assaisonnement" },
      { nom: "Levure", g: 10.0, pct: 0.3, role: "levant" },
      { nom: "Levain liquide", g: 500.0, pct: 12.7, role: "levant" },
      { nom: "Eau de coulage", g: 1320.0, pct: 33.6, role: "eau" },
      { nom: "Eau bassinage", g: 60.0, pct: 1.5, role: "eau" },
    ],
    procede: [
      "*Autolyse = (T° du labo + T° de la farine) - TB 56° C = T° eau de coulage",
      "Pétrissage pétrin spirale. Faire une autolyse :  Pétrir 3 minutes en 1ère vitesse, puis laisser 30 minutes à 2 heures. Ajouter le sel et la levure. Pétrir 4 minutes environ en 1ère vitesse et ajouter le levain liquide et l’eau de bassinage puis pétrir jusqu’à décollement en 1ère vitesse. Température de pâte 22°C à 24°C. Pointage 1 heure avec rabat à 30 minutes puis 12h/18h à 2°C. Pesage 180g. Détente 10 à 30 minutes. Façonnage baguette. Apprêt 45 minutes à 1 heure. Cuisson 250°C/260°C temps de cuisson en fonction des pièces.",
      "Beurre noisette :",
      "Beurre		 		200g",
      "Réaliser un beurre noisette, un fois froid le monter au batteur avec un fouet.",
      "Monage :",
      "Baguette 			180g",
      "Beurre noisette 		20g",
      "Conté 				30g",
      "Jambon 			70g",
      "Cornichon 			20g",
    ],
    cuisson: { temperature_c: null, duree_min: 3, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten"],
    tags: ["sale proteine"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Jambon Beurre .docx", import: "extraction-2026-08-25" },
  },
  {
    id: "poulet-miel",
    nom: "Poulet miel",
    categorie: "traiteur",
    sous_categorie: "sale_proteine",
    description: "Poulet miel — recette importée, à vérifier.",
    masse_totale_g: 3930,
    ingredients: [
      { nom: "Farine de tradition", g: 1700.0, pct: 43.3, role: "structure" },
      { nom: "Farine de mais", g: 300.0, pct: 7.6, role: "structure" },
      { nom: "Sel", g: 40.0, pct: 1.0, role: "assaisonnement" },
      { nom: "Levure", g: 10.0, pct: 0.3, role: "levant" },
      { nom: "Levain liquide", g: 500.0, pct: 12.7, role: "levant" },
      { nom: "Eau de coulage", g: 1320.0, pct: 33.6, role: "eau" },
      { nom: "Eau bassinage", g: 60.0, pct: 1.5, role: "eau" },
    ],
    procede: [
      "*Autolyse = (T° du labo + T° de la farine) - TB 56° C = T° eau de coulage",
      "Pétrissage pétrin spirale. Faire une autolyse :  Pétrir 3 minutes en 1ère vitesse, puis laisser 30 minutes à 2 heures. Ajouter le sel et la levure. Pétrir 4 minutes environ en 1ère vitesse et ajouter le levain liquide et l’eau de bassinage puis pétrir jusqu’à décollement en 1ère vitesse. Température de pâte 22°C à 24°C. Pointage 1 heure avec rabat à 30 minutes puis 12h/18h à 2°C. Pesage 180g. Détente 10 à 30 minutes. Façonnage baguette. Apprêt 45 minutes à 1 heure. Cuisson 250°C/260°C temps de cuisson en fonction des pièces.",
      "Houmous de mais :",
      "Mais frais 			200g",
      "Sel				5g",
      "Poivre				2g",
      "Mixé le tous au termomix",
      "Jus de bœuf réduit :",
      "Poudre Chef Bœuf",
      "Eau",
      "Mélanger tous les ingrédient et laisser réduire à feu doux",
      "Poulet rôtie :",
      "Blanc de poulet			4 Pce",
      "Sel 				PM",
      "Poivre 				PM",
      "Beurre 				20g",
      "Huile de tournesol		20g",
      "Cuire le poulet au four à 180°C, achée la moitié du poulet et la mélanger au houmous. Couper grossièrement l’autre moitié et la mélanger au jus de bœuf réduit",
      "Quinoas soufflé :",
      "Quinoas			100g",
      "Huile pépin raisin 		200g",
      "Faire frire le Quinoas, égoutter sur papier stoker en étuve",
      "Montage :",
      "Pain mais							180g",
      "Moutarde Miel 							50g",
      "Rillette Poulet (mélange de houmous et poulet achée)		50g",
      "Mais frais							30g",
      "Poulet								50g",
      "Jus de bœuf 							10g",
      "Quinoa soufflé rouge 						2g",
    ],
    cuisson: { temperature_c: 180, duree_min: 3, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten"],
    tags: ["sale proteine"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Poulet miel.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "pesto-d-estragon",
    nom: "Pesto d’estragon",
    categorie: "traiteur",
    sous_categorie: "sauce_salee",
    description: "Pesto d’estragon — recette importée, à vérifier.",
    masse_totale_g: 252,
    ingredients: [
      { nom: "huile d'olive", g: 250.0, pct: 99.2, role: "mg" },
      { nom: "sel", g: 1.0, pct: 0.4, role: "assaisonnement" },
      { nom: "poivre", g: 1.0, pct: 0.4, role: "assaisonnement" },
    ],
    procede: [
      "Réunir tous les ingrédients dans un blender et mixer.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sauce salee"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Sandwich Poulet.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "mayonnaise-aux-capres",
    nom: "Mayonnaise aux câpres",
    categorie: "traiteur",
    sous_categorie: "sauce_salee",
    description: "Mayonnaise aux câpres — recette importée, à vérifier.",
    masse_totale_g: 57,
    ingredients: [
      { nom: "huile d'arachide", g: 50.0, pct: 87.7, role: "mg" },
      { nom: "câpres", g: 5.0, pct: 8.8, role: "parfum" },
      { nom: "sel", g: 1.0, pct: 1.8, role: "assaisonnement" },
      { nom: "poivre", g: 1.0, pct: 1.8, role: "assaisonnement" },
    ],
    procede: [
      "Dans un blender, mettre le jaune d’œuf, la moutarde, le sel et le poivre puis faire monter à l’huile.",
      "Serrer la mayonnaise avec le vinaigre de Xeres, et ajouter les câpres et l’estragon, filmer et réserver.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["arachide"],
    tags: ["sauce salee"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Sandwich Poulet.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "poulet-roti",
    nom: "Poulet rôti",
    categorie: "traiteur",
    sous_categorie: "sale_proteine",
    description: "Poulet rôti — recette importée, à vérifier.",
    masse_totale_g: 99,
    ingredients: [
      { nom: "thym", g: 20.0, pct: 20.2, role: "parfum" },
      { nom: "beurre", g: 30.0, pct: 30.3, role: "mg" },
      { nom: "moutarde", g: 15.0, pct: 15.2, role: "parfum" },
      { nom: "sel", g: 2.0, pct: 2.0, role: "assaisonnement" },
      { nom: "poivre", g: 2.0, pct: 2.0, role: "assaisonnement" },
      { nom: "huile d'arachide", g: 30.0, pct: 30.3, role: "mg" },
    ],
    procede: [
      "Fouetter le beurre dans un cul de poule jusqu’à obtention d’une pommade, et le mélanger avec la moutarde, le sel et le poivre.",
      "Insérer le mélange sous la peau du poulet, déposer le poulet dans un plat à rôtir, puis à l’aide d’un pinceau, le badigeonner d’huile d’arachide.",
      "Enfourner et faire cuire pendant 1 heure, en arrosant régulièrement à partir de la mi-cuisson.",
      "Après cuisson, décortiquer le poulet, retirer la peau et tailler grossièrement la chair.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["arachide", "lait", "moutarde"],
    tags: ["sale proteine"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Sandwich Poulet.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "pesto-rouge",
    nom: "Pesto rouge",
    categorie: "traiteur",
    sous_categorie: "sauce_salee",
    description: "Pesto rouge — recette importée, à vérifier.",
    masse_totale_g: 528,
    ingredients: [
      { nom: "tomates", g: 100.0, pct: 18.9, role: "parfum" },
      { nom: "tomate cerises", g: 50.0, pct: 9.5, role: "parfum" },
      { nom: "piment d'Espelette", g: 6.0, pct: 1.1, role: "parfum" },
      { nom: "oignons rouge", g: 65.0, pct: 12.3, role: "parfum" },
      { nom: "huile d'olive", g: 10.0, pct: 1.9, role: "mg" },
      { nom: "cerneaux de noix", g: 15.0, pct: 2.8, role: "eau" },
      { nom: "poivron rouge", g: 65.0, pct: 12.3, role: "parfum" },
      { nom: "tomate confites", g: 30.0, pct: 5.7, role: "parfum" },
      { nom: "olive noire dénoyauté", g: 10.0, pct: 1.9, role: "parfum" },
      { nom: "sel", g: 2.0, pct: 0.4, role: "assaisonnement" },
      { nom: "poivre", g: 1.0, pct: 0.2, role: "assaisonnement" },
      { nom: "vinaigre", g: 4.0, pct: 0.8, role: "acidite" },
      { nom: "poudre de noisettes", g: 50.0, pct: 9.5, role: "structure" },
      { nom: "sucre", g: 100.0, pct: 18.9, role: "sucrant" },
      { nom: "farine", g: 20.0, pct: 3.8, role: "structure" },
    ],
    procede: [
      "Faire revenir le piment, les oignons et l’ail dans une poêle avec l’huile d’olive.",
      "Les mettre dans le bol d’un blender avec les autres ingrédients et mixer jusqu’à obtention d’une pâte.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["fruits_a_coque", "gluten"],
    tags: ["sauce salee", "noisette"],
    parfum_principal: "noisette",
    note_concepteur: "",
    source_interne: { fichier: "Sandwich Végétarien.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "le-pesto-basilic",
    nom: "Le pesto basilic",
    categorie: "traiteur",
    sous_categorie: "sauce_salee",
    description: "Le pesto basilic — recette importée, à vérifier.",
    masse_totale_g: 160,
    ingredients: [
      { nom: "amandes", g: 20.0, pct: 12.5, role: "parfum" },
      { nom: "pignons de pin", g: 10.0, pct: 6.2, role: "parfum" },
      { nom: "feuilles de basilic", g: 30.0, pct: 18.8, role: "parfum" },
      { nom: "parmesan", g: 30.0, pct: 18.8, role: "parfum" },
      { nom: "huile d'olives", g: 70.0, pct: 43.8, role: "mg" },
    ],
    procede: [
      "Déposer les mandes et les pignons sur une plaque, enfourner et faire torréfier pendant 10 minutes.",
      "Laisser refroidir, mixer avec le basilic, le parmesan et l’huile d’olive, jusqu’à obtention d’une pâte onctueuse.",
    ],
    cuisson: { temperature_c: null, duree_min: 10, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["fruits_a_coque"],
    tags: ["sauce salee", "amande"],
    parfum_principal: "amande",
    note_concepteur: "",
    source_interne: { fichier: "Sandwich méditerranéens.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "saumon-avocat",
    nom: "Saumon Avocat",
    categorie: "traiteur",
    sous_categorie: "sale_proteine",
    description: "Saumon Avocat — recette importée, à vérifier.",
    masse_totale_g: 4463,
    ingredients: [
      { nom: "Farine tradition", g: 2000.0, pct: 44.8, role: "structure" },
      { nom: "Sel", g: 40.0, pct: 0.9, role: "assaisonnement" },
      { nom: "Levure", g: 10.0, pct: 0.2, role: "levant" },
      { nom: "Levain liquide", g: 500.0, pct: 11.2, role: "levant" },
      { nom: "Eau coulage", g: 1320.0, pct: 29.6, role: "eau" },
      { nom: "Eau de bassinage", g: 60.0, pct: 1.3, role: "eau" },
      { nom: "Graine", g: 533.0, pct: 11.9, role: "parfum" },
    ],
    procede: [
      "*Autolyse = (T° du labo + T° de la farine) - TB 56° C = T° eau de coulage",
      "Pétrissage pétrin spirale. Faire une autolyse :  Pétrir 3 minutes en 1ère vitesse, puis laisser 30 minutes à 2 heures. Ajouter le sel et la levure. Pétrir 4 minutes environ en 1ère vitesse et ajouter le levain liquide et l’eau de bassinage puis pétrir jusqu’à décollement en 1ère vitesse. Température de pâte 22°C à 24°C. Pointage 1 heure avec rabat à 30 minutes puis 12h/18h à 2°C. Pesage 180g. Détente 10 à 30 minutes. Façonnage baguette. Apprêt 45 minutes à 1 heure. Cuisson 250°C/260°C temps de cuisson en fonction des pièces.",
      "Gravelax de saumon :",
      "Saumon 		1 filet",
      "Sel			500g",
      "Sucre			500g",
      "Aneth 			200g",
      "Zeste citron vert	10 pièces",
      "Lever et préparer les filets de saumon. Mélanger le sucre, le sel et l’aneth hachée ensemble puis disposer le filet de saumon dans un bac gastro et recouvrir de ce mélange, laisser mariner 24H au frigo. Rincer les filets à l’eau froide puis les mettre sous vide.",
      "Guacamole :",
      "Avocat			5 Pce",
      "Jus de citron vert	25g",
      "Huile d’olive		25g",
      "Sel 			PM",
      "Poivre			PM",
      "Piment d’Espelette 	PM",
      "Eplucher les avocats et mixer tous les ingrédients, puis mettre en poche.",
      "Gel gingembre :",
      "Jus gingembre			   		380g",
      "Eau			                		127 g",
      "Sucre			                   		25 g",
      "Agar agar			    		10 g",
      "Chauffer le jus de gingembre avec l’eau, puis ajouter le mélange sucre et agar agar. Bouillir 2 minutes. Refroidir, puis mixer.",
      "Montage :",
      "Pain céréale 			180g",
      "Guacamole			30g",
      "Tranche d’avocat 		20g",
      "Tranche de saumon 		70g",
      "Gel Gingembre			10g",
      "Œuf dur râpé			20g",
    ],
    cuisson: { temperature_c: null, duree_min: 3, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten"],
    tags: ["sale proteine"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Saumon Avocat.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "thon",
    nom: "Thon",
    categorie: "traiteur",
    sous_categorie: "sale_proteine",
    description: "Thon — recette importée, à vérifier.",
    masse_totale_g: 4430,
    ingredients: [
      { nom: "Farine de tradition", g: 2000.0, pct: 45.1, role: "structure" },
      { nom: "Sel", g: 40.0, pct: 0.9, role: "assaisonnement" },
      { nom: "Levure", g: 10.0, pct: 0.2, role: "levant" },
      { nom: "Levain liquide", g: 500.0, pct: 11.3, role: "levant" },
      { nom: "Eau de coulage", g: 1320.0, pct: 29.8, role: "eau" },
      { nom: "Eau bassinage", g: 60.0, pct: 1.4, role: "eau" },
      { nom: "Olives", g: 500.0, pct: 11.3, role: "parfum" },
    ],
    procede: [
      "*Autolyse = (T° du labo + T° de la farine) - TB 56° C = T° eau de coulage",
      "Pétrissage pétrin spirale. Faire une autolyse :  Pétrir 3 minutes en 1ère vitesse, puis laisser 30 minutes à 2 heures. Ajouter le sel et la levure. Pétrir 4 minutes environ en 1ère vitesse et ajouter le levain liquide et l’eau de bassinage puis pétrir jusqu’à décollement en 1ère vitesse. Température de pâte 22°C à 24°C. Pointage 1 heure avec rabat à 30 minutes puis 12h/18h à 2°C. Pesage 180g. Détente 10 à 30 minutes. Façonnage baguette. Apprêt 45 minutes à 1 heure. Cuisson 250°C/260°C temps de cuisson en fonction des pièces.",
      "Montage :",
      "Pain olive 		180g",
      "Tapenade 		35g",
      "Thon 			70g",
      "Oignon rouge 		13g",
      "Olive achée		10g",
      "Tomate 		50g",
      "Sauge 			2g",
      "Huile d’olive 		2g",
    ],
    cuisson: { temperature_c: null, duree_min: 3, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten"],
    tags: ["sale proteine"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Thon.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "tomate-pastramie",
    nom: "Tomate Pastramie",
    categorie: "traiteur",
    sous_categorie: "sale_proteine",
    description: "Tomate Pastramie — recette importée, à vérifier.",
    masse_totale_g: 4930,
    ingredients: [
      { nom: "Farine de tradition", g: 2000.0, pct: 40.6, role: "structure" },
      { nom: "Sel", g: 40.0, pct: 0.8, role: "assaisonnement" },
      { nom: "Levure", g: 10.0, pct: 0.2, role: "levant" },
      { nom: "Levain liquide", g: 500.0, pct: 10.1, role: "levant" },
      { nom: "Eau de coulage", g: 1320.0, pct: 26.8, role: "eau" },
      { nom: "Eau bassinage", g: 60.0, pct: 1.2, role: "eau" },
      { nom: "Tomate séchée", g: 500.0, pct: 10.1, role: "parfum" },
      { nom: "Concentré de tomate", g: 500.0, pct: 10.1, role: "parfum" },
    ],
    procede: [
      "*Autolyse = (T° du labo + T° de la farine) - TB 56° C = T° eau de coulage",
      "Pétrissage pétrin spirale. Faire une autolyse :  Pétrir 3 minutes en 1ère vitesse, puis laisser 30 minutes à 2 heures. Ajouter le sel et la levure. Pétrir 4 minutes environ en 1ère vitesse et ajouter le levain liquide et l’eau de bassinage puis pétrir jusqu’à décollement en 1ère vitesse. Température de pâte 22°C à 24°C. Pointage 1 heure avec rabat à 30 minutes puis 12h/18h à 2°C. Pesage 180g. Détente 10 à 30 minutes. Façonnage baguette. Apprêt 45 minutes à 1 heure. Cuisson 250°C/260°C temps de cuisson en fonction des pièces.",
      "Sauce tomate fumé :",
      "Tomate			20 pce",
      "Oignon			2 pce",
      "Thym 			PM",
      "Sel			PM",
      "Couper les tomates et les oignons puis disposer dans un bac gastro et mettre à cuire au four à 180°C pendant environ 30 minutes, mixer le tout au thermomix et fumer  environ 30min.",
      "Montage :",
      "Pain Tomate 		180g",
      "Sauce tomate		40g",
      "Tomate fraiche 		40g",
      "Pastramie 		70g",
      "Vieille mimolette	20g",
    ],
    cuisson: { temperature_c: 180, duree_min: 3, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten"],
    tags: ["sale proteine"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Tomate Pastramie.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "salade-d-herbes",
    nom: "Salade d’herbes",
    categorie: "traiteur",
    sous_categorie: "garniture_salee",
    description: "Salade d’herbes — recette importée, à vérifier.",
    masse_totale_g: 50,
    ingredients: [
      { nom: "coriandre", g: 15.0, pct: 30.0, role: "parfum" },
      { nom: "menthe fraîche", g: 15.0, pct: 30.0, role: "parfum" },
      { nom: "huile d'olive", g: 5.0, pct: 10.0, role: "mg" },
      { nom: "sucre semoule", g: 10.0, pct: 20.0, role: "sucrant" },
      { nom: "jus de citron jaune", g: 5.0, pct: 10.0, role: "liant" },
    ],
    procede: [
      "3 tours de moulin de poivre noir de Sarawak",
      "Effeuillez la botte de menthe fraîche et de coriandre puis ajoutez au dernier moment l’huile d’olive, le jus de citron jaune, le sucre et le poivre noir de Sarawak",
      "Préparation de l’assiette",
      "QS de framboises fraîches",
      "Dans une grande assiette plate, garnissez de tartare de tomate un cercle de 8 cm Ø et de 1,5 cm de hauteur. Autour du cercle, aspergez harmonieusement de fromage blanc, parsemez de 3 framboises fraîches, disposez la salade d’herbes et une peau de tomate séchée. Posez une quenelle de sorbet framboise et poivron rouge et terminez avec une tranche de pain de campagne sucrée et grillée.",
      "Servez sans attendre.",
      "Boissons conseillées",
      "Pineau des Charentes rouge.",
      "Tableau récapitulatif de poids",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["oeuf"],
    tags: ["garniture salee", "citron"],
    parfum_principal: "citron",
    note_concepteur: "",
    source_interne: { fichier: "tomates et fraise en tartare, sorbet framboise RM 10.04.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "croque-noisette",
    nom: "CROQUE-NOISETTE",
    categorie: "traiteur",
    sous_categorie: "snacking",
    description: "CROQUE-NOISETTE — recette importée, à vérifier.",
    masse_totale_g: 4150,
    ingredients: [
      { nom: "blancs d'œufs vieux", g: 480.0, pct: 11.6, role: "aeration" },
      { nom: "sucre glace", g: 1800.0, pct: 43.4, role: "sucrant" },
      { nom: "noisettes entières", g: 1800.0, pct: 43.4, role: "parfum" },
      { nom: "essence naturelle de café (Trabblit)", g: 70.0, pct: 1.7, role: "parfum" },
    ],
    procede: [
      "Faites griller les noisettes à 160 °C pendant 20 minutes puis passez-les au tamis pour en retirer.",
      "Mélangez le sucre glace avec les blancs, l’essence de café  et les noisettes entières encore tièdes et faites chauffer au bain-marie à 60 °C. Mixez légèrement l’appareil à croque-noisette et abaissez aussitôt en cadre 36 x 56 cm. Laissez refroidir puis stockez au congélateur.",
      "La recette ci-dessus est équivalente à un cadre 36 x 56 cm soit 4,150 kg.",
      "Découpe",
      "abaisse d’appareil croque-noisette",
      "Coupez l’abaisse en deux dans la longueur ; à l’aide du cadre de la guitare marquez la surface. A l’aide d’un grand couteau découpez des cubes de 2 cm de côté puis réservez au congélateur bien filmé.",
      "Cuisson",
      "cubes de croques-noisettes",
      "Déposez sur plaque recouverte de papier silicone les cubes de croques-noisettes légèrement espacés, cuisez à 170°C au four ventilé pendant 10 minutes. Laissez bien refroidir avant de passer à l’emballage.",
      "Emballage",
      "Emballez … g de croque noisettes dans les tubos imprimés PH, puis appliquez en dessous l’adhésif indiquant la date limite de vente et la composition.",
      "Boissons conseillées",
      "Thés, café, chocolat.",
    ],
    cuisson: { temperature_c: 170, duree_min: 10, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["fruits_a_coque", "oeuf"],
    tags: ["snacking", "noisette"],
    parfum_principal: "noisette",
    note_concepteur: "",
    source_interne: { fichier: "Croque-noisette 03.07.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "agneau-pascal-paques",
    nom: "AGNEAU PASCAL Pâques",
    categorie: "traiteur",
    sous_categorie: "sale_proteine",
    description: "AGNEAU PASCAL Pâques — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "PATE D'AMANDE CONFISEUR 33%", g: 400.2, pct: 40.0, role: "parfum" },
      { nom: "ŒUFS", g: 391.1, pct: 39.1, role: "liant" },
      { nom: "BEURRE", g: 121.9, pct: 12.2, role: "mg" },
      { nom: "FARINE T55", g: 73.6, pct: 7.4, role: "structure" },
      { nom: "LEVURE CHIMIOQUE", g: 7.3, pct: 0.7, role: "levant" },
      { nom: "RHUM", g: 5.5, pct: 0.5, role: "parfum" },
      { nom: "ORANGE ZESTE PIECE", g: 0.6, pct: 0.1, role: "parfum" },
    ],
    procede: [
      "0.0",
      "DANS UN BATTEUR DETENDRE LA PATE D'AMANDE AVEC LES ŒUFS PETIT A PETIT A LA FEUILLE",
      "0.0",
      "TAMISER LES POUDRES ENSEMBLE",
      "0.0",
      "MELANGER LE BEURRE FONDU AVEC UN PEU DE MIX PATE D'AMANDE LES ZESTES ET LE RHUM",
      "0.0",
      "AJOUTER LES POUDRES DELICATEMENT",
      "0.0",
      "450GR PAR MOULE",
      "CUIRE A 185°C DANS UN FOUR POLLIN",
    ],
    cuisson: { temperature_c: 185, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["fruits_a_coque", "gluten", "lait", "oeuf"],
    tags: ["sale proteine", "amande"],
    parfum_principal: "amande",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "AGNEAU PASCAL PAQUES NEW.xls", import: "extraction-2026-08-25" },
  },
  {
    id: "agneau-de-paques",
    nom: "AGNEAU DE Pâques",
    categorie: "traiteur",
    sous_categorie: "sale_proteine",
    description: "AGNEAU DE Pâques — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Pate d'amande LUBEKA", g: 85.6, pct: 8.6, role: "parfum" },
      { nom: "Œufs", g: 427.8, pct: 42.8, role: "liant" },
      { nom: "Sucre cristal", g: 144.4, pct: 14.4, role: "sucrant" },
      { nom: "Emulsifiant HF", g: 10.7, pct: 1.1, role: "emulsifiant" },
      { nom: "Trimoline", g: 12.8, pct: 1.3, role: "sucrant" },
      { nom: "Vanille liquide", g: 3.2, pct: 0.3, role: "parfum" },
      { nom: "Maizena", g: 50.3, pct: 5.0, role: "structure" },
      { nom: "Farine T55", g: 187.2, pct: 18.7, role: "structure" },
      { nom: "Beurre fondu tempéré", g: 74.9, pct: 7.5, role: "mg" },
      { nom: "Zeste de citron jaune en \"g\"", g: 2.1, pct: 0.2, role: "liant" },
      { nom: "Sel", g: 1.1, pct: 0.1, role: "assaisonnement" },
    ],
    procede: [
      "La veille mélanger les zestes auvec le sucre.",
      "Faire fondre le beurre et le laisser se tempérer.",
      "Mélanger la pate d'amande avec le sucre cristal et les zestes, puis ajouter la vanille liquide,",
      "trimoline, émulsifiant et sel.",
      "Ajouter les œufs petit à petit et bien faire monter, texture ruban.",
      "Incorporer la farine et la maizena préalablement tamisées.",
      "Detendre le beurre avec de la masse et incorporer délicatement.",
      "Beurrer et fariner les moules.",
      "Remplir les moules jusqu'au 4cm du haut du moule.",
      "Recettes rouge pour 35 moules (environ 400g/moules)",
      "Au Polin : 175°C pdt 18min buée fermée et 15min buée ouverte",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["fruits_a_coque", "gluten", "lait", "oeuf"],
    tags: ["sale proteine", "amande"],
    parfum_principal: "amande",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Agneau de Paques.xls", import: "extraction-2026-08-25" },
  },
  {
    id: "croque-cafe-noix",
    nom: "CROQUE CAFE NOIX",
    categorie: "traiteur",
    sous_categorie: "snacking",
    description: "CROQUE CAFE NOIX — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "BEURRE", g: 351.9, pct: 35.2, role: "mg" },
      { nom: "CAFE SOLUBLE", g: 19.2, pct: 1.9, role: "parfum" },
      { nom: "JAUNE CUIT", g: 25.6, pct: 2.6, role: "liant" },
      { nom: "SEL", g: 1.9, pct: 0.2, role: "assaisonnement" },
      { nom: "SUCRE GLACE", g: 115.2, pct: 11.5, role: "sucrant" },
      { nom: "BLANC", g: 38.4, pct: 3.8, role: "parfum" },
      { nom: "FARINE", g: 319.9, pct: 32.0, role: "structure" },
      { nom: "FECULE", g: 64.0, pct: 6.4, role: "structure" },
      { nom: "FEUILLANTINE", g: 64.0, pct: 6.4, role: "parfum" },
    ],
    procede: [
      "0.0",
      "MELANGER BEURRE CAFE JAUNE CUIT SEL ET SUCRE GLACE",
      "AJOUTER BLANC. TAMISER FARINE ET FECULE ET Y AJOUTER LA FEUILLANTINE",
      "ETALER A 5MM.",
      "PULVERISER DE L'EAU PUIS PARSEMER DE NOIX HACHEES FINEMENT",
      "COUPER EN CARRE DE 3,5CM",
      "0.0",
      "0.0",
      "0.0",
      "0.0",
      "CUIRE A 155° PENDANT 15MIN",
    ],
    cuisson: { temperature_c: 155, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten", "lait", "oeuf"],
    tags: ["snacking", "café"],
    parfum_principal: "café",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "CRAQUE CAFE NOIX.xls", import: "extraction-2026-08-25" },
  },
  {
    id: "sable-chorizo",
    nom: "SABLE CHORIZO",
    categorie: "traiteur",
    sous_categorie: "sale_proteine",
    description: "SABLE CHORIZO — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "BEURRE", g: 308.1, pct: 30.8, role: "mg" },
      { nom: "SUCRE GLACE", g: 88.0, pct: 8.8, role: "sucrant" },
      { nom: "SEL", g: 4.4, pct: 0.4, role: "assaisonnement" },
      { nom: "JAUNE CUIT", g: 44.0, pct: 4.4, role: "liant" },
      { nom: "BLANC", g: 88.0, pct: 8.8, role: "parfum" },
      { nom: "FARINE", g: 220.1, pct: 22.0, role: "structure" },
      { nom: "FECULE", g: 88.0, pct: 8.8, role: "structure" },
      { nom: "PAG", g: 70.4, pct: 7.0, role: "parfum" },
      { nom: "BICARBONATE", g: 0.9, pct: 0.1, role: "levant" },
      { nom: "CHORIZO", g: 88.0, pct: 8.8, role: "parfum" },
    ],
    procede: [
      "0.0",
      "MELANGER A LA FEUILLE (BEURRE, SUCRE GLACE, SEL ET JAUNE CUIT TAMISE)",
      "INCORPORER LES BLANCS.",
      "TAMISER FARINE FECULE ET BICARBONATE Y AJOUTER AU MELANGE",
      "AJOUTER POUDRE D'AMANDE GRISE ET CHORIZO",
      "ETALER A 5 PUIS RAYER",
      "0.0",
      "0.0",
      "0.0",
      "0.0",
      "TAILLE : 3,5 CM                       CUISSON : 18 MIN A 160°C",
    ],
    cuisson: { temperature_c: 160, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten", "lait", "oeuf"],
    tags: ["sale proteine"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "SABLE CHORIZO.xls", import: "extraction-2026-08-25" },
  },
];
