export const RECETTES_TRAITEUR = [

  // === Import extraction-2026-08-25 (19 recettes) ===
  {
    id: "avocado-toast",
    type: "assemblage",
    nom: "Avocado toast",
    categorie: "traiteur",
    sous_categorie: "snacking",
    description: "Avocado toast — recette importée, à vérifier.",
    masse_totale_g: 4743,
    composants: [
      {
        nom: "Préparation 1",
        masse_g: 4463,
        ingredients: [
          { nom: "Farine tradition", g: 2000, pct: 44.8, role: "structure" },
          { nom: "Sel", g: 40, pct: 0.9, role: "assaisonnement" },
          { nom: "Levure", g: 10, pct: 0.2, role: "levant" },
          { nom: "Levain liquide", g: 500, pct: 11.2, role: "levant" },
          { nom: "Eau coulage", g: 1320, pct: 29.6, role: "eau" },
          { nom: "Eau de bassinage", g: 60, pct: 1.3, role: "eau" },
          { nom: "Graine", g: 533, pct: 11.9, role: "parfum" },
        ],
        procede: [
          "*Autolyse = (T° du labo + T° de la farine) - TB 56° C = T° eau de coulage",
          "Pétrissage pétrin spirale. Faire une autolyse : Pétrir 3 minutes en 1ère vitesse, puis laisser 30 minutes à 2 heures. Ajouter le sel et la levure. Pétrir 4 minutes environ en 1ère vitesse et ajouter le levain liquide et l’eau de bassinage puis pétrir jusqu’à décollement en 1ère vitesse. Température de pâte 22°C à 24°C. Pointage 1 heure avec rabat à 30 minutes puis 12h/18h à 2°C. Pesage 700g. Détente 10 à 30 minutes. Façonnage Cadre. Apprêt 45 minutes à 1 heure. Cuisson 250°C/260°C temps de cuisson en fonction des pièces.",
          "Guacamole",
          "Avocat 5 Pce",
          "Sel PM",
          "Poivre PM",
          "Piment d’Espelette PM",
          "Eplucher les avocats et mixer tous les ingrédients, puis mettre en poche.",
        ],
      },
      {
        nom: "Montage",
        masse_g: 280,
        ingredients: [
          { nom: "Pain Céréale tranche", g: 180, pct: 64.3, role: "" },
          { nom: "Guacamole", g: 50, pct: 17.9, role: "" },
          { nom: "Tranche d’avocat couper", g: 50, pct: 17.8, role: "" },
        ],
        procede: [
          "Œuf de caille au plats 3 Pce",
          "Salade vert",
          "Graine de chia",
          "Huile d’olive",
        ],
      },
    ],
    cuisson: {"temperature_c":null,"duree_min":3,"mode":null},
    temperatures: {"service_c":null,"conservation_c":null},
    contraintes: {"vegan":false,"sans_lactose":true,"sans_gluten":false,"ig_bas":false},
    a_verifier: true,
    allergenes: ["gluten"],
    tags: ["snacking"],
    note_concepteur: "",
    source_interne: {"fichier":"Avocado toast.docx","import":"extraction-2026-08-25"},
  },
  {
    id: "egg-toast",
    type: "assemblage",
    nom: "Egg Toast",
    categorie: "traiteur",
    sous_categorie: "snacking",
    description: "Egg Toast — recette importée, à vérifier.",
    masse_totale_g: 6907,
    composants: [
      {
        nom: "Préparation 1",
        masse_g: 6700,
        ingredients: [
          { nom: "Lait", g: 1200, pct: 17.9, role: "eau" },
          { nom: "Levure", g: 150, pct: 2.2, role: "levant" },
          { nom: "Farine T45", g: 3300, pct: 49.3, role: "structure" },
          { nom: "Œufs entiers", g: 600, pct: 9, role: "liant" },
          { nom: "Sel fin", g: 50, pct: 0.7, role: "assaisonnement" },
          { nom: "Sucre semoule", g: 200, pct: 3, role: "sucrant" },
          { nom: "Beurre pommade", g: 300, pct: 4.5, role: "mg" },
          { nom: "Beurre de tourage", g: 900, pct: 13.4, role: "mg" },
        ],
        procede: [
          "Faire tourner en 1ière vitesse pour un simple mélange puis en 2ième vitesse jusqu’à ce que la pâte qui se décolle des parois. Incorporer le beurre pommade. Pétrir jusqu’à l’obtention d’une pâte homogène (T 24-25 °C)",
          "Pointage à température ambiante pendant 1 heure avec un torchon humide. Dégazer puis beurrer. Un tour double, un tour simple.",
          "Etaler le pâton dans la largeur du beurre et mettre au congel 45 minutes puis remettre au frigo. Faire le pâton avec le beurre sec avec l’ouverture mise en perpendiculaire par rapport au laminoir. Faire un tour double étalé à 7 mm d’épaisseur reposer 10 minutes au frigo. Faire un tour simple étalé à 10 mm puis directement étaler à 4 mm",
        ],
      },
      {
        nom: "Houmous de mais",
        masse_g: 207,
        ingredients: [
          { nom: "Mais frais", g: 200, pct: 96.6, role: "" },
          { nom: "Sel", g: 5, pct: 2.4, role: "assaisonnement" },
          { nom: "Poivre", g: 2, pct: 1, role: "assaisonnement" },
        ],
        procede: [
          "Mixé le tous au termomix",
        ],
      },
    ],
    montage: [
      "Brioche feuilleter toaster",
      "Cheddar",
      "Bacon",
      "Houmous de mais",
      "Crispi Bacon",
      "Œuf au plats",
      "Sel",
      "Poivre",
    ],
    cuisson: {"temperature_c":null,"duree_min":null,"mode":null},
    temperatures: {"service_c":null,"conservation_c":null},
    contraintes: {"vegan":false,"sans_lactose":false,"sans_gluten":false,"ig_bas":false},
    a_verifier: true,
    allergenes: ["gluten","lait","oeuf"],
    tags: ["snacking"],
    note_concepteur: "",
    source_interne: {"fichier":"Egg Toast.docx","import":"extraction-2026-08-25"},
  },
  {
    id: "condiment-moutarde",
    nom: "Condiment moutarde",
    categorie: "traiteur",
    sous_categorie: "sauce_salee",
    description: "Condiment moutarde — recette importée, à vérifier.",
    masse_totale_g: 120,
    ingredients: [
      { nom: "cornichons", g: 25.0, pct: 20.8, role: "parfum" },
      { nom: "oignons confits", g: 38.0, pct: 31.7, role: "parfum" },
      { nom: "moutarde", g: 38.0, pct: 31.7, role: "parfum" },
      { nom: "moutarde à l'ancienne", g: 19.0, pct: 15.8, role: "parfum" },
    ],
    procede: [
      "Le jour même, couper les cornichons en brunoise, puis les mélanger intimement avec les oignons confits, la moutarde douce et la moutarde à l’ancienne.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["moutarde"],
    tags: ["sauce salee"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Hot dog.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "jambon-beurre",
    type: "assemblage",
    nom: "Jambon Beurre",
    categorie: "traiteur",
    sous_categorie: "sale_proteine",
    description: "Jambon Beurre — recette importée, à vérifier.",
    masse_totale_g: 4250,
    composants: [
      {
        nom: "Préparation 1",
        masse_g: 3930,
        ingredients: [
          { nom: "Farine de tradition", g: 1700, pct: 43.3, role: "structure" },
          { nom: "Farine Seigle", g: 300, pct: 7.6, role: "structure" },
          { nom: "Sel", g: 40, pct: 1, role: "assaisonnement" },
          { nom: "Levure", g: 10, pct: 0.3, role: "levant" },
          { nom: "Levain liquide", g: 500, pct: 12.7, role: "levant" },
          { nom: "Eau de coulage", g: 1320, pct: 33.6, role: "eau" },
          { nom: "Eau bassinage", g: 60, pct: 1.5, role: "eau" },
        ],
        procede: [
          "*Autolyse = (T° du labo + T° de la farine) - TB 56° C = T° eau de coulage",
          "Pétrissage pétrin spirale. Faire une autolyse : Pétrir 3 minutes en 1ère vitesse, puis laisser 30 minutes à 2 heures. Ajouter le sel et la levure. Pétrir 4 minutes environ en 1ère vitesse et ajouter le levain liquide et l’eau de bassinage puis pétrir jusqu’à décollement en 1ère vitesse. Température de pâte 22°C à 24°C. Pointage 1 heure avec rabat à 30 minutes puis 12h/18h à 2°C. Pesage 180g. Détente 10 à 30 minutes. Façonnage baguette. Apprêt 45 minutes à 1 heure. Cuisson 250°C/260°C temps de cuisson en fonction des pièces.",
          "Beurre noisette",
          "Réaliser un beurre noisette, un fois froid le monter au batteur avec un fouet.",
        ],
      },
      {
        nom: "Monage",
        masse_g: 320,
        ingredients: [
          { nom: "Baguette", g: 180, pct: 56.3, role: "" },
          { nom: "Beurre noisette", g: 20, pct: 6.2, role: "mg" },
          { nom: "Conté", g: 30, pct: 9.4, role: "" },
          { nom: "Jambon", g: 70, pct: 21.9, role: "" },
          { nom: "Cornichon", g: 20, pct: 6.2, role: "" },
        ],
        procede: [
        ],
      },
    ],
    cuisson: {"temperature_c":null,"duree_min":3,"mode":null},
    temperatures: {"service_c":null,"conservation_c":null},
    contraintes: {"vegan":false,"sans_lactose":true,"sans_gluten":false,"ig_bas":false},
    a_verifier: true,
    allergenes: ["fruits_a_coque", "gluten", "lait"],
    tags: ["sale proteine"],
    note_concepteur: "",
    source_interne: {"fichier":"Jambon Beurre .docx","import":"extraction-2026-08-25"},
  },
  {
    id: "poulet-miel",
    type: "assemblage",
    nom: "Poulet miel",
    categorie: "traiteur",
    sous_categorie: "sale_proteine",
    description: "Poulet miel — recette importée, à vérifier.",
    masse_totale_g: 4849,
    composants: [
      {
        nom: "Préparation 1",
        masse_g: 3930,
        ingredients: [
          { nom: "Farine de tradition", g: 1700, pct: 43.3, role: "structure" },
          { nom: "Farine de mais", g: 300, pct: 7.6, role: "structure" },
          { nom: "Sel", g: 40, pct: 1, role: "assaisonnement" },
          { nom: "Levure", g: 10, pct: 0.3, role: "levant" },
          { nom: "Levain liquide", g: 500, pct: 12.7, role: "levant" },
          { nom: "Eau de coulage", g: 1320, pct: 33.6, role: "eau" },
          { nom: "Eau bassinage", g: 60, pct: 1.5, role: "eau" },
        ],
        procede: [
          "*Autolyse = (T° du labo + T° de la farine) - TB 56° C = T° eau de coulage",
          "Pétrissage pétrin spirale. Faire une autolyse : Pétrir 3 minutes en 1ère vitesse, puis laisser 30 minutes à 2 heures. Ajouter le sel et la levure. Pétrir 4 minutes environ en 1ère vitesse et ajouter le levain liquide et l’eau de bassinage puis pétrir jusqu’à décollement en 1ère vitesse. Température de pâte 22°C à 24°C. Pointage 1 heure avec rabat à 30 minutes puis 12h/18h à 2°C. Pesage 180g. Détente 10 à 30 minutes. Façonnage baguette. Apprêt 45 minutes à 1 heure. Cuisson 250°C/260°C temps de cuisson en fonction des pièces.",
        ],
      },
      {
        nom: "Houmous de mais",
        masse_g: 207,
        ingredients: [
          { nom: "Mais frais", g: 200, pct: 96.6, role: "" },
          { nom: "Sel", g: 5, pct: 2.4, role: "assaisonnement" },
          { nom: "Poivre", g: 2, pct: 1, role: "assaisonnement" },
        ],
        procede: [
          "Mixé le tous au termomix",
          "Jus de bœuf réduit",
          "Poudre Chef Bœuf",
          "Eau",
          "Mélanger tous les ingrédient et laisser réduire à feu doux",
          "Poulet rôtie",
          "Blanc de poulet 4 Pce",
          "Sel PM",
        ],
      },
      {
        nom: "Poivre PM",
        masse_g: 40,
        ingredients: [
          { nom: "Beurre", g: 20, pct: 50, role: "mg" },
          { nom: "Huile de tournesol", g: 20, pct: 50, role: "mg" },
        ],
        procede: [
          "Cuire le poulet au four à 180°C, achée la moitié du poulet et la mélanger au houmous. Couper grossièrement l’autre moitié et la mélanger au jus de bœuf réduit",
        ],
      },
      {
        nom: "Quinoas soufflé",
        masse_g: 300,
        ingredients: [
          { nom: "Quinoas", g: 100, pct: 33.3, role: "" },
          { nom: "Huile pépin raisin", g: 200, pct: 66.7, role: "" },
        ],
        procede: [
          "Faire frire le Quinoas, égoutter sur papier stoker en étuve",
        ],
      },
      {
        nom: "Montage",
        masse_g: 372,
        ingredients: [
          { nom: "Pain mais", g: 180, pct: 48.4, role: "" },
          { nom: "Moutarde Miel", g: 50, pct: 13.5, role: "" },
          { nom: "Rillette Poulet (mélange de houmous et poulet achée)", g: 50, pct: 13.4, role: "" },
          { nom: "Mais frais", g: 30, pct: 8.1, role: "" },
          { nom: "Poulet", g: 50, pct: 13.4, role: "" },
          { nom: "Jus de bœuf", g: 10, pct: 2.7, role: "" },
          { nom: "Quinoa soufflé rouge", g: 2, pct: 0.5, role: "" },
        ],
        procede: [
        ],
      },
    ],
    cuisson: {"temperature_c":180,"duree_min":3,"mode":null},
    temperatures: {"service_c":null,"conservation_c":null},
    contraintes: {"vegan":false,"sans_lactose":true,"sans_gluten":false,"ig_bas":false},
    a_verifier: true,
    allergenes: ["gluten", "lait", "moutarde"],
    tags: ["sale proteine"],
    note_concepteur: "",
    source_interne: {"fichier":"Poulet miel.docx","import":"extraction-2026-08-25"},
  },
  {
    id: "pesto-d-estragon",
    nom: "Pesto d’estragon",
    categorie: "traiteur",
    sous_categorie: "sauce_salee",
    description: "Pesto d’estragon — recette importée, à vérifier.",
    masse_totale_g: 252,
    ingredients: [
      { nom: "huile d'olive", g: 250.0, pct: 99.2, role: "mg" },
      { nom: "sel", g: 1.0, pct: 0.4, role: "assaisonnement" },
      { nom: "poivre", g: 1.0, pct: 0.4, role: "assaisonnement" },
    ],
    procede: [
      "Réunir tous les ingrédients dans un blender et mixer.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: [],
    tags: ["sauce salee"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Sandwich Poulet.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "mayonnaise-aux-capres",
    nom: "Mayonnaise aux câpres",
    categorie: "traiteur",
    sous_categorie: "sauce_salee",
    description: "Mayonnaise aux câpres — recette importée, à vérifier.",
    masse_totale_g: 57,
    ingredients: [
      { nom: "huile d'arachide", g: 50.0, pct: 87.7, role: "mg" },
      { nom: "câpres", g: 5.0, pct: 8.8, role: "parfum" },
      { nom: "sel", g: 1.0, pct: 1.8, role: "assaisonnement" },
      { nom: "poivre", g: 1.0, pct: 1.8, role: "assaisonnement" },
    ],
    procede: [
      "Dans un blender, mettre le jaune d’œuf, la moutarde, le sel et le poivre puis faire monter à l’huile.",
      "Serrer la mayonnaise avec le vinaigre de Xeres, et ajouter les câpres et l’estragon, filmer et réserver.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["arachide"],
    tags: ["sauce salee"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Sandwich Poulet.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "poulet-roti",
    nom: "Poulet rôti",
    categorie: "traiteur",
    sous_categorie: "sale_proteine",
    description: "Poulet rôti — recette importée, à vérifier.",
    masse_totale_g: 99,
    ingredients: [
      { nom: "thym", g: 20.0, pct: 20.2, role: "parfum" },
      { nom: "beurre", g: 30.0, pct: 30.3, role: "mg" },
      { nom: "moutarde", g: 15.0, pct: 15.2, role: "parfum" },
      { nom: "sel", g: 2.0, pct: 2.0, role: "assaisonnement" },
      { nom: "poivre", g: 2.0, pct: 2.0, role: "assaisonnement" },
      { nom: "huile d'arachide", g: 30.0, pct: 30.3, role: "mg" },
    ],
    procede: [
      "Fouetter le beurre dans un cul de poule jusqu’à obtention d’une pommade, et le mélanger avec la moutarde, le sel et le poivre.",
      "Insérer le mélange sous la peau du poulet, déposer le poulet dans un plat à rôtir, puis à l’aide d’un pinceau, le badigeonner d’huile d’arachide.",
      "Enfourner et faire cuire pendant 1 heure, en arrosant régulièrement à partir de la mi-cuisson.",
      "Après cuisson, décortiquer le poulet, retirer la peau et tailler grossièrement la chair.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["arachide", "lait", "moutarde"],
    tags: ["sale proteine"],
    parfum_principal: null,
    note_concepteur: "",
    source_interne: { fichier: "Sandwich Poulet.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "pesto-rouge",
    nom: "Pesto rouge",
    categorie: "traiteur",
    sous_categorie: "sauce_salee",
    description: "Pesto rouge — recette importée, à vérifier.",
    masse_totale_g: 528,
    ingredients: [
      { nom: "tomates", g: 100.0, pct: 18.9, role: "parfum" },
      { nom: "tomate cerises", g: 50.0, pct: 9.5, role: "parfum" },
      { nom: "piment d'Espelette", g: 6.0, pct: 1.1, role: "parfum" },
      { nom: "oignons rouge", g: 65.0, pct: 12.3, role: "parfum" },
      { nom: "huile d'olive", g: 10.0, pct: 1.9, role: "mg" },
      { nom: "cerneaux de noix", g: 15.0, pct: 2.8, role: "eau" },
      { nom: "poivron rouge", g: 65.0, pct: 12.3, role: "parfum" },
      { nom: "tomate confites", g: 30.0, pct: 5.7, role: "parfum" },
      { nom: "olive noire dénoyauté", g: 10.0, pct: 1.9, role: "parfum" },
      { nom: "sel", g: 2.0, pct: 0.4, role: "assaisonnement" },
      { nom: "poivre", g: 1.0, pct: 0.2, role: "assaisonnement" },
      { nom: "vinaigre", g: 4.0, pct: 0.8, role: "acidite" },
      { nom: "poudre de noisettes", g: 50.0, pct: 9.5, role: "structure" },
      { nom: "sucre", g: 100.0, pct: 18.9, role: "sucrant" },
      { nom: "farine", g: 20.0, pct: 3.8, role: "structure" },
    ],
    procede: [
      "Faire revenir le piment, les oignons et l’ail dans une poêle avec l’huile d’olive.",
      "Les mettre dans le bol d’un blender avec les autres ingrédients et mixer jusqu’à obtention d’une pâte.",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["fruits_a_coque", "gluten"],
    tags: ["sauce salee", "noisette"],
    parfum_principal: "noisette",
    note_concepteur: "",
    source_interne: { fichier: "Sandwich Végétarien.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "le-pesto-basilic",
    nom: "Le pesto basilic",
    categorie: "traiteur",
    sous_categorie: "sauce_salee",
    description: "Le pesto basilic — recette importée, à vérifier.",
    masse_totale_g: 160,
    ingredients: [
      { nom: "amandes", g: 20.0, pct: 12.5, role: "parfum" },
      { nom: "pignons de pin", g: 10.0, pct: 6.2, role: "parfum" },
      { nom: "feuilles de basilic", g: 30.0, pct: 18.8, role: "parfum" },
      { nom: "parmesan", g: 30.0, pct: 18.8, role: "parfum" },
      { nom: "huile d'olives", g: 70.0, pct: 43.8, role: "mg" },
    ],
    procede: [
      "Déposer les mandes et les pignons sur une plaque, enfourner et faire torréfier pendant 10 minutes.",
      "Laisser refroidir, mixer avec le basilic, le parmesan et l’huile d’olive, jusqu’à obtention d’une pâte onctueuse.",
    ],
    cuisson: { temperature_c: null, duree_min: 10, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["fruits_a_coque"],
    tags: ["sauce salee", "amande"],
    parfum_principal: "amande",
    note_concepteur: "",
    source_interne: { fichier: "Sandwich méditerranéens.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "saumon-avocat",
    type: "assemblage",
    nom: "Saumon Avocat",
    categorie: "traiteur",
    sous_categorie: "sale_proteine",
    description: "Saumon Avocat — recette importée, à vérifier.",
    masse_totale_g: 5335,
    composants: [
      {
        nom: "Préparation 1",
        masse_g: 4463,
        ingredients: [
          { nom: "Farine tradition", g: 2000, pct: 44.8, role: "structure" },
          { nom: "Sel", g: 40, pct: 0.9, role: "assaisonnement" },
          { nom: "Levure", g: 10, pct: 0.2, role: "levant" },
          { nom: "Levain liquide", g: 500, pct: 11.2, role: "levant" },
          { nom: "Eau coulage", g: 1320, pct: 29.6, role: "eau" },
          { nom: "Eau de bassinage", g: 60, pct: 1.3, role: "eau" },
          { nom: "Graine", g: 533, pct: 11.9, role: "parfum" },
        ],
        procede: [
          "*Autolyse = (T° du labo + T° de la farine) - TB 56° C = T° eau de coulage",
          "Pétrissage pétrin spirale. Faire une autolyse : Pétrir 3 minutes en 1ère vitesse, puis laisser 30 minutes à 2 heures. Ajouter le sel et la levure. Pétrir 4 minutes environ en 1ère vitesse et ajouter le levain liquide et l’eau de bassinage puis pétrir jusqu’à décollement en 1ère vitesse. Température de pâte 22°C à 24°C. Pointage 1 heure avec rabat à 30 minutes puis 12h/18h à 2°C. Pesage 180g. Détente 10 à 30 minutes. Façonnage baguette. Apprêt 45 minutes à 1 heure. Cuisson 250°C/260°C temps de cuisson en fonction des pièces.",
          "Gravelax de saumon",
          "Saumon 1 filet",
          "Lever et préparer les filets de saumon. Mélanger le sucre, le sel et l’aneth hachée ensemble puis disposer le filet de saumon dans un bac gastro et recouvrir de ce mélange, laisser mariner 24H au frigo. Rincer les filets à l’eau froide puis les mettre sous vide.",
          "Guacamole",
          "Avocat 5 Pce",
          "Sel PM",
          "Poivre PM",
          "Piment d’Espelette PM",
          "Eplucher les avocats et mixer tous les ingrédients, puis mettre en poche.",
        ],
      },
      {
        nom: "Gel gingembre",
        masse_g: 542,
        ingredients: [
          { nom: "Jus gingembre", g: 380, pct: 70.1, role: "assaisonnement" },
          { nom: "Eau", g: 127, pct: 23.4, role: "eau" },
          { nom: "Sucre", g: 25, pct: 4.6, role: "sucrant" },
          { nom: "Agar agar", g: 10, pct: 1.9, role: "gelifiant" },
        ],
        procede: [
          "Chauffer le jus de gingembre avec l’eau, puis ajouter le mélange sucre et agar agar. Bouillir 2 minutes. Refroidir, puis mixer.",
        ],
      },
      {
        nom: "Montage",
        masse_g: 330,
        ingredients: [
          { nom: "Pain céréale", g: 180, pct: 54.5, role: "" },
          { nom: "Guacamole", g: 30, pct: 9.1, role: "" },
          { nom: "Tranche d’avocat", g: 20, pct: 6.1, role: "" },
          { nom: "Tranche de saumon", g: 70, pct: 21.2, role: "" },
          { nom: "Gel Gingembre", g: 10, pct: 3, role: "" },
          { nom: "Œuf dur râpé", g: 20, pct: 6.1, role: "" },
        ],
        procede: [
        ],
      },
    ],
    cuisson: {"temperature_c":null,"duree_min":3,"mode":null},
    temperatures: {"service_c":null,"conservation_c":null},
    contraintes: {"vegan":false,"sans_lactose":true,"sans_gluten":false,"ig_bas":false},
    a_verifier: true,
    allergenes: ["gluten", "oeuf", "poisson"],
    tags: ["sale proteine"],
    note_concepteur: "",
    source_interne: {"fichier":"Saumon Avocat.docx","import":"extraction-2026-08-25"},
  },
  {
    id: "thon",
    type: "assemblage",
    nom: "Thon",
    categorie: "traiteur",
    sous_categorie: "sale_proteine",
    description: "Thon — recette importée, à vérifier.",
    masse_totale_g: 4792,
    composants: [
      {
        nom: "Préparation 1",
        masse_g: 4430,
        ingredients: [
          { nom: "Farine de tradition", g: 2000, pct: 45.1, role: "structure" },
          { nom: "Sel", g: 40, pct: 0.9, role: "assaisonnement" },
          { nom: "Levure", g: 10, pct: 0.2, role: "levant" },
          { nom: "Levain liquide", g: 500, pct: 11.3, role: "levant" },
          { nom: "Eau de coulage", g: 1320, pct: 29.8, role: "eau" },
          { nom: "Eau bassinage", g: 60, pct: 1.4, role: "eau" },
          { nom: "Olives", g: 500, pct: 11.3, role: "parfum" },
        ],
        procede: [
          "*Autolyse = (T° du labo + T° de la farine) - TB 56° C = T° eau de coulage",
          "Pétrissage pétrin spirale. Faire une autolyse : Pétrir 3 minutes en 1ère vitesse, puis laisser 30 minutes à 2 heures. Ajouter le sel et la levure. Pétrir 4 minutes environ en 1ère vitesse et ajouter le levain liquide et l’eau de bassinage puis pétrir jusqu’à décollement en 1ère vitesse. Température de pâte 22°C à 24°C. Pointage 1 heure avec rabat à 30 minutes puis 12h/18h à 2°C. Pesage 180g. Détente 10 à 30 minutes. Façonnage baguette. Apprêt 45 minutes à 1 heure. Cuisson 250°C/260°C temps de cuisson en fonction des pièces.",
        ],
      },
      {
        nom: "Montage",
        masse_g: 362,
        ingredients: [
          { nom: "Pain olive", g: 180, pct: 49.7, role: "" },
          { nom: "Tapenade", g: 35, pct: 9.7, role: "" },
          { nom: "Thon", g: 70, pct: 19.3, role: "" },
          { nom: "Oignon rouge", g: 13, pct: 3.6, role: "" },
          { nom: "Olive achée", g: 10, pct: 2.8, role: "" },
          { nom: "Tomate", g: 50, pct: 13.8, role: "" },
          { nom: "Sauge", g: 2, pct: 0.6, role: "parfum" },
          { nom: "Huile d’olive", g: 2, pct: 0.5, role: "" },
        ],
        procede: [
        ],
      },
    ],
    cuisson: {"temperature_c":null,"duree_min":3,"mode":null},
    temperatures: {"service_c":null,"conservation_c":null},
    contraintes: {"vegan":false,"sans_lactose":true,"sans_gluten":false,"ig_bas":false},
    a_verifier: true,
    allergenes: ["gluten", "poisson"],
    tags: ["sale proteine"],
    note_concepteur: "",
    source_interne: {"fichier":"Thon.docx","import":"extraction-2026-08-25"},
  },
  {
    id: "tomate-pastramie",
    type: "assemblage",
    nom: "Tomate Pastramie",
    categorie: "traiteur",
    sous_categorie: "sale_proteine",
    description: "Tomate Pastramie — recette importée, à vérifier.",
    masse_totale_g: 5280,
    composants: [
      {
        nom: "Préparation 1",
        masse_g: 4930,
        ingredients: [
          { nom: "Farine de tradition", g: 2000, pct: 40.6, role: "structure" },
          { nom: "Sel", g: 40, pct: 0.8, role: "assaisonnement" },
          { nom: "Levure", g: 10, pct: 0.2, role: "levant" },
          { nom: "Levain liquide", g: 500, pct: 10.1, role: "levant" },
          { nom: "Eau de coulage", g: 1320, pct: 26.8, role: "eau" },
          { nom: "Eau bassinage", g: 60, pct: 1.2, role: "eau" },
          { nom: "Tomate séchée", g: 500, pct: 10.1, role: "parfum" },
          { nom: "Concentré de tomate", g: 500, pct: 10.1, role: "parfum" },
        ],
        procede: [
          "*Autolyse = (T° du labo + T° de la farine) - TB 56° C = T° eau de coulage",
          "Pétrissage pétrin spirale. Faire une autolyse : Pétrir 3 minutes en 1ère vitesse, puis laisser 30 minutes à 2 heures. Ajouter le sel et la levure. Pétrir 4 minutes environ en 1ère vitesse et ajouter le levain liquide et l’eau de bassinage puis pétrir jusqu’à décollement en 1ère vitesse. Température de pâte 22°C à 24°C. Pointage 1 heure avec rabat à 30 minutes puis 12h/18h à 2°C. Pesage 180g. Détente 10 à 30 minutes. Façonnage baguette. Apprêt 45 minutes à 1 heure. Cuisson 250°C/260°C temps de cuisson en fonction des pièces.",
          "Sauce tomate fumé",
          "Tomate 20 pce",
          "Oignon 2 pce",
          "Thym PM",
          "Sel PM",
          "Couper les tomates et les oignons puis disposer dans un bac gastro et mettre à cuire au four à 180°C pendant environ 30 minutes, mixer le tout au thermomix et fumer environ 30min.",
        ],
      },
      {
        nom: "Montage",
        masse_g: 350,
        ingredients: [
          { nom: "Pain Tomate", g: 180, pct: 51.4, role: "" },
          { nom: "Sauce tomate", g: 40, pct: 11.5, role: "" },
          { nom: "Tomate fraiche", g: 40, pct: 11.4, role: "" },
          { nom: "Pastramie", g: 70, pct: 20, role: "" },
          { nom: "Vieille mimolette", g: 20, pct: 5.7, role: "" },
        ],
        procede: [
        ],
      },
    ],
    cuisson: {"temperature_c":180,"duree_min":3,"mode":null},
    temperatures: {"service_c":null,"conservation_c":null},
    contraintes: {"vegan":false,"sans_lactose":true,"sans_gluten":false,"ig_bas":false},
    a_verifier: true,
    allergenes: ["gluten"],
    tags: ["sale proteine"],
    note_concepteur: "",
    source_interne: {"fichier":"Tomate Pastramie.docx","import":"extraction-2026-08-25"},
  },
  {
    id: "salade-d-herbes",
    nom: "Salade d’herbes",
    categorie: "traiteur",
    sous_categorie: "garniture_salee",
    description: "Salade d’herbes — recette importée, à vérifier.",
    masse_totale_g: 50,
    ingredients: [
      { nom: "coriandre", g: 15.0, pct: 30.0, role: "parfum" },
      { nom: "menthe fraîche", g: 15.0, pct: 30.0, role: "parfum" },
      { nom: "huile d'olive", g: 5.0, pct: 10.0, role: "mg" },
      { nom: "sucre semoule", g: 10.0, pct: 20.0, role: "sucrant" },
      { nom: "jus de citron jaune", g: 5.0, pct: 10.0, role: "liant" },
    ],
    procede: [
      "3 tours de moulin de poivre noir de Sarawak",
      "Effeuillez la botte de menthe fraîche et de coriandre puis ajoutez au dernier moment l’huile d’olive, le jus de citron jaune, le sucre et le poivre noir de Sarawak",
      "Préparation de l’assiette",
      "QS de framboises fraîches",
      "Dans une grande assiette plate, garnissez de tartare de tomate un cercle de 8 cm Ø et de 1,5 cm de hauteur. Autour du cercle, aspergez harmonieusement de fromage blanc, parsemez de 3 framboises fraîches, disposez la salade d’herbes et une peau de tomate séchée. Posez une quenelle de sorbet framboise et poivron rouge et terminez avec une tranche de pain de campagne sucrée et grillée.",
      "Servez sans attendre.",
      "Boissons conseillées",
      "Pineau des Charentes rouge.",
      "Tableau récapitulatif de poids",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["oeuf"],
    tags: ["garniture salee", "citron"],
    parfum_principal: "citron",
    note_concepteur: "",
    source_interne: { fichier: "tomates et fraise en tartare, sorbet framboise RM 10.04.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "croque-noisette",
    nom: "CROQUE-NOISETTE",
    categorie: "traiteur",
    sous_categorie: "snacking",
    description: "CROQUE-NOISETTE — recette importée, à vérifier.",
    masse_totale_g: 4150,
    ingredients: [
      { nom: "blancs d'œufs vieux", g: 480.0, pct: 11.6, role: "aeration" },
      { nom: "sucre glace", g: 1800.0, pct: 43.4, role: "sucrant" },
      { nom: "noisettes entières", g: 1800.0, pct: 43.4, role: "parfum" },
      { nom: "essence naturelle de café (Trabblit)", g: 70.0, pct: 1.7, role: "parfum" },
    ],
    procede: [
      "Faites griller les noisettes à 160 °C pendant 20 minutes puis passez-les au tamis pour en retirer.",
      "Mélangez le sucre glace avec les blancs, l’essence de café  et les noisettes entières encore tièdes et faites chauffer au bain-marie à 60 °C. Mixez légèrement l’appareil à croque-noisette et abaissez aussitôt en cadre 36 x 56 cm. Laissez refroidir puis stockez au congélateur.",
      "La recette ci-dessus est équivalente à un cadre 36 x 56 cm soit 4,150 kg.",
      "Découpe",
      "abaisse d’appareil croque-noisette",
      "Coupez l’abaisse en deux dans la longueur ; à l’aide du cadre de la guitare marquez la surface. A l’aide d’un grand couteau découpez des cubes de 2 cm de côté puis réservez au congélateur bien filmé.",
      "Cuisson",
      "cubes de croques-noisettes",
      "Déposez sur plaque recouverte de papier silicone les cubes de croques-noisettes légèrement espacés, cuisez à 170°C au four ventilé pendant 10 minutes. Laissez bien refroidir avant de passer à l’emballage.",
      "Emballage",
      "Emballez … g de croque noisettes dans les tubos imprimés PH, puis appliquez en dessous l’adhésif indiquant la date limite de vente et la composition.",
      "Boissons conseillées",
      "Thés, café, chocolat.",
    ],
    cuisson: { temperature_c: 170, duree_min: 10, mode: "chaleur tournante" },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: true, sans_gluten: true, ig_bas: false },
    a_verifier: true,
    allergenes: ["fruits_a_coque", "oeuf"],
    tags: ["snacking", "noisette"],
    parfum_principal: "noisette",
    note_concepteur: "",
    source_interne: { fichier: "Croque-noisette 03.07.docx", import: "extraction-2026-08-25" },
  },
  {
    id: "agneau-pascal-paques",
    nom: "AGNEAU PASCAL Pâques",
    categorie: "traiteur",
    sous_categorie: "sale_proteine",
    description: "AGNEAU PASCAL Pâques — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "PATE D'AMANDE CONFISEUR 33%", g: 400.2, pct: 40.0, role: "parfum" },
      { nom: "ŒUFS", g: 391.1, pct: 39.1, role: "liant" },
      { nom: "BEURRE", g: 121.9, pct: 12.2, role: "mg" },
      { nom: "FARINE T55", g: 73.6, pct: 7.4, role: "structure" },
      { nom: "LEVURE CHIMIOQUE", g: 7.3, pct: 0.7, role: "levant" },
      { nom: "RHUM", g: 5.5, pct: 0.5, role: "parfum" },
      { nom: "ORANGE ZESTE PIECE", g: 0.6, pct: 0.1, role: "parfum" },
    ],
    procede: [
      "0.0",
      "DANS UN BATTEUR DETENDRE LA PATE D'AMANDE AVEC LES ŒUFS PETIT A PETIT A LA FEUILLE",
      "0.0",
      "TAMISER LES POUDRES ENSEMBLE",
      "0.0",
      "MELANGER LE BEURRE FONDU AVEC UN PEU DE MIX PATE D'AMANDE LES ZESTES ET LE RHUM",
      "0.0",
      "AJOUTER LES POUDRES DELICATEMENT",
      "0.0",
      "450GR PAR MOULE",
      "CUIRE A 185°C DANS UN FOUR POLLIN",
    ],
    cuisson: { temperature_c: 185, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["fruits_a_coque", "gluten", "lait", "oeuf"],
    tags: ["sale proteine", "amande"],
    parfum_principal: "amande",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "AGNEAU PASCAL PAQUES NEW.xls", import: "extraction-2026-08-25" },
  },
  {
    id: "agneau-de-paques",
    nom: "AGNEAU DE Pâques",
    categorie: "traiteur",
    sous_categorie: "sale_proteine",
    description: "AGNEAU DE Pâques — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "Pate d'amande LUBEKA", g: 85.6, pct: 8.6, role: "parfum" },
      { nom: "Œufs", g: 427.8, pct: 42.8, role: "liant" },
      { nom: "Sucre cristal", g: 144.4, pct: 14.4, role: "sucrant" },
      { nom: "Emulsifiant HF", g: 10.7, pct: 1.1, role: "emulsifiant" },
      { nom: "Trimoline", g: 12.8, pct: 1.3, role: "sucrant" },
      { nom: "Vanille liquide", g: 3.2, pct: 0.3, role: "parfum" },
      { nom: "Maizena", g: 50.3, pct: 5.0, role: "structure" },
      { nom: "Farine T55", g: 187.2, pct: 18.7, role: "structure" },
      { nom: "Beurre fondu tempéré", g: 74.9, pct: 7.5, role: "mg" },
      { nom: "Zeste de citron jaune en \"g\"", g: 2.1, pct: 0.2, role: "liant" },
      { nom: "Sel", g: 1.1, pct: 0.1, role: "assaisonnement" },
    ],
    procede: [
      "La veille mélanger les zestes auvec le sucre.",
      "Faire fondre le beurre et le laisser se tempérer.",
      "Mélanger la pate d'amande avec le sucre cristal et les zestes, puis ajouter la vanille liquide,",
      "trimoline, émulsifiant et sel.",
      "Ajouter les œufs petit à petit et bien faire monter, texture ruban.",
      "Incorporer la farine et la maizena préalablement tamisées.",
      "Detendre le beurre avec de la masse et incorporer délicatement.",
      "Beurrer et fariner les moules.",
      "Remplir les moules jusqu'au 4cm du haut du moule.",
      "Recettes rouge pour 35 moules (environ 400g/moules)",
      "Au Polin : 175°C pdt 18min buée fermée et 15min buée ouverte",
    ],
    cuisson: { temperature_c: null, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["fruits_a_coque", "gluten", "lait", "oeuf"],
    tags: ["sale proteine", "amande"],
    parfum_principal: "amande",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "Agneau de Paques.xls", import: "extraction-2026-08-25" },
  },
  {
    id: "croque-cafe-noix",
    nom: "CROQUE CAFE NOIX",
    categorie: "traiteur",
    sous_categorie: "snacking",
    description: "CROQUE CAFE NOIX — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "BEURRE", g: 351.9, pct: 35.2, role: "mg" },
      { nom: "CAFE SOLUBLE", g: 19.2, pct: 1.9, role: "parfum" },
      { nom: "JAUNE CUIT", g: 25.6, pct: 2.6, role: "liant" },
      { nom: "SEL", g: 1.9, pct: 0.2, role: "assaisonnement" },
      { nom: "SUCRE GLACE", g: 115.2, pct: 11.5, role: "sucrant" },
      { nom: "BLANC", g: 38.4, pct: 3.8, role: "parfum" },
      { nom: "FARINE", g: 319.9, pct: 32.0, role: "structure" },
      { nom: "FECULE", g: 64.0, pct: 6.4, role: "structure" },
      { nom: "FEUILLANTINE", g: 64.0, pct: 6.4, role: "parfum" },
    ],
    procede: [
      "0.0",
      "MELANGER BEURRE CAFE JAUNE CUIT SEL ET SUCRE GLACE",
      "AJOUTER BLANC. TAMISER FARINE ET FECULE ET Y AJOUTER LA FEUILLANTINE",
      "ETALER A 5MM.",
      "PULVERISER DE L'EAU PUIS PARSEMER DE NOIX HACHEES FINEMENT",
      "COUPER EN CARRE DE 3,5CM",
      "0.0",
      "0.0",
      "0.0",
      "0.0",
      "CUIRE A 155° PENDANT 15MIN",
    ],
    cuisson: { temperature_c: 155, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten", "lait", "oeuf"],
    tags: ["snacking", "café"],
    parfum_principal: "café",
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "CRAQUE CAFE NOIX.xls", import: "extraction-2026-08-25" },
  },
  {
    id: "sable-chorizo",
    nom: "SABLE CHORIZO",
    categorie: "traiteur",
    sous_categorie: "sale_proteine",
    description: "SABLE CHORIZO — recette importée, ratios pour 1000 g, à vérifier.",
    masse_totale_g: 1000,
    ingredients: [
      { nom: "BEURRE", g: 308.1, pct: 30.8, role: "mg" },
      { nom: "SUCRE GLACE", g: 88.0, pct: 8.8, role: "sucrant" },
      { nom: "SEL", g: 4.4, pct: 0.4, role: "assaisonnement" },
      { nom: "JAUNE CUIT", g: 44.0, pct: 4.4, role: "liant" },
      { nom: "BLANC", g: 88.0, pct: 8.8, role: "parfum" },
      { nom: "FARINE", g: 220.1, pct: 22.0, role: "structure" },
      { nom: "FECULE", g: 88.0, pct: 8.8, role: "structure" },
      { nom: "PAG", g: 70.4, pct: 7.0, role: "parfum" },
      { nom: "BICARBONATE", g: 0.9, pct: 0.1, role: "levant" },
      { nom: "CHORIZO", g: 88.0, pct: 8.8, role: "parfum" },
    ],
    procede: [
      "0.0",
      "MELANGER A LA FEUILLE (BEURRE, SUCRE GLACE, SEL ET JAUNE CUIT TAMISE)",
      "INCORPORER LES BLANCS.",
      "TAMISER FARINE FECULE ET BICARBONATE Y AJOUTER AU MELANGE",
      "AJOUTER POUDRE D'AMANDE GRISE ET CHORIZO",
      "ETALER A 5 PUIS RAYER",
      "0.0",
      "0.0",
      "0.0",
      "0.0",
      "TAILLE : 3,5 CM                       CUISSON : 18 MIN A 160°C",
    ],
    cuisson: { temperature_c: 160, duree_min: null, mode: null },
    temperatures: { service_c: null, conservation_c: null },
    contraintes: { vegan: false, sans_lactose: false, sans_gluten: false, ig_bas: false },
    a_verifier: true,
    allergenes: ["gluten", "lait", "oeuf"],
    tags: ["sale proteine"],
    parfum_principal: null,
    note_concepteur: "",
    masse_de_reference: true,
    source_interne: { fichier: "SABLE CHORIZO.xls", import: "extraction-2026-08-25" },
  },
];
