// Données métier par ingrédient : prix, allergènes INCO, conservation
// Clé = nom exact tel qu'utilisé dans lib/ingredients-nutrition.js et les templates
//
// prix_eur_par_g  : en € / g HT — valeurs indicatives Metro Pro / Capfruit / Valrhona 2025-01
// allergenes_inco : parmi les 21 identifiants INCO définis (règlement UE 1169/2011)
//   gluten · crustaces · oeufs · poissons · arachides · soja · lait
//   fruits_a_coque_amande · fruits_a_coque_noisette · fruits_a_coque_noix
//   fruits_a_coque_cajou · fruits_a_coque_pecan · fruits_a_coque_pistache
//   fruits_a_coque_macadamia · fruits_a_coque_bresil
//   celeri · moutarde · sesame · sulfites · lupin · mollusques
// conservation_j_* : jours de conservation de l'ingrédient seul (pas de la recette)
// apres_ouverture : durée après ouverture du conditionnement

export const INGREDIENTS_METIER = {

  // ── Produits laitiers ────────────────────────────────────────────────────────
  'Crème liquide 35%': {
    prix_eur_par_g: 0.0025, prix_unitaire_eur: 2.50, unite_prix: 'L',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: ['lait'], traces_possibles: [], nom_inco: 'LAIT',
    conservation_j_froid: 21, conservation_j_ambiant: null, conservation_j_surgele: null,
    instructions_conservation: 'Réfrigérer à +4 °C maximum',
    apres_ouverture: '3 j',
  },
  'Crème liquide 35% (base)': {
    prix_eur_par_g: 0.0025, prix_unitaire_eur: 2.50, unite_prix: 'L',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: ['lait'], traces_possibles: [], nom_inco: 'LAIT',
    conservation_j_froid: 21, conservation_j_ambiant: null, conservation_j_surgele: null,
    instructions_conservation: 'Réfrigérer à +4 °C maximum',
    apres_ouverture: '3 j',
  },
  'Crème UHT 35 %': {
    prix_eur_par_g: 0.0028, prix_unitaire_eur: 2.80, unite_prix: 'L',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: ['lait'], traces_possibles: [], nom_inco: 'LAIT',
    conservation_j_froid: 21, conservation_j_ambiant: 180, conservation_j_surgele: null,
    instructions_conservation: 'UHT : conserver à température ambiante avant ouverture, réfrigérer après',
    apres_ouverture: '3 j',
  },
  'Lait entier': {
    prix_eur_par_g: 0.0012, prix_unitaire_eur: 1.20, unite_prix: 'L',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: ['lait'], traces_possibles: [], nom_inco: 'LAIT',
    conservation_j_froid: 5, conservation_j_ambiant: null, conservation_j_surgele: null,
    instructions_conservation: 'Réfrigérer à +4 °C maximum',
    apres_ouverture: '3 j',
  },
  'Lait UHT entier': {
    prix_eur_par_g: 0.0012, prix_unitaire_eur: 1.20, unite_prix: 'L',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: ['lait'], traces_possibles: [], nom_inco: 'LAIT',
    conservation_j_froid: 5, conservation_j_ambiant: 180, conservation_j_surgele: null,
    instructions_conservation: 'UHT : conserver à température ambiante avant ouverture',
    apres_ouverture: '3 j',
  },
  'Lait concentré sucré': {
    prix_eur_par_g: 0.0035, prix_unitaire_eur: 3.50, unite_prix: 'kg',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: ['lait'], traces_possibles: [], nom_inco: 'LAIT',
    conservation_j_froid: 7, conservation_j_ambiant: 365, conservation_j_surgele: null,
    instructions_conservation: 'Conserver à température ambiante avant ouverture',
    apres_ouverture: '7 j au réfrigérateur',
  },

  // ── Beurres et matières grasses laitières ────────────────────────────────────
  'Beurre doux': {
    prix_eur_par_g: 0.0085, prix_unitaire_eur: 8.50, unite_prix: 'kg',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: ['lait'], traces_possibles: [], nom_inco: 'LAIT',
    conservation_j_froid: 60, conservation_j_ambiant: null, conservation_j_surgele: 90,
    instructions_conservation: 'Réfrigérer, emballer hermétiquement',
    apres_ouverture: '14 j',
  },
  'Beurre fondu': {
    prix_eur_par_g: 0.0085, prix_unitaire_eur: 8.50, unite_prix: 'kg',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: ['lait'], traces_possibles: [], nom_inco: 'LAIT',
    conservation_j_froid: 60, conservation_j_ambiant: null, conservation_j_surgele: 90,
    instructions_conservation: 'Réfrigérer, emballer hermétiquement',
    apres_ouverture: '14 j',
  },
  'Beurre noisette': {
    prix_eur_par_g: 0.0085, prix_unitaire_eur: 8.50, unite_prix: 'kg',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: ['lait'], traces_possibles: [], nom_inco: 'LAIT',
    conservation_j_froid: 60, conservation_j_ambiant: null, conservation_j_surgele: 90,
    instructions_conservation: 'Réfrigérer, emballer hermétiquement',
    apres_ouverture: '14 j',
  },
  'Beurre': {
    prix_eur_par_g: 0.0085, prix_unitaire_eur: 8.50, unite_prix: 'kg',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: ['lait'], traces_possibles: [], nom_inco: 'LAIT',
    conservation_j_froid: 60, conservation_j_ambiant: null, conservation_j_surgele: 90,
    instructions_conservation: 'Réfrigérer, emballer hermétiquement',
    apres_ouverture: '14 j',
  },
  'Beurre de cacao': {
    prix_eur_par_g: 0.0280, prix_unitaire_eur: 28.00, unite_prix: 'kg',
    fournisseur: 'Valrhona', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: [], traces_possibles: ['lait'], nom_inco: null,
    conservation_j_froid: null, conservation_j_ambiant: 365, conservation_j_surgele: null,
    instructions_conservation: 'Conserver au frais et au sec, à l\'abri de la lumière',
    apres_ouverture: null,
  },

  // ── Œufs ─────────────────────────────────────────────────────────────────────
  'Œufs entiers': {
    prix_eur_par_g: 0.0051, prix_unitaire_eur: 0.28, unite_prix: 'piece',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: ['oeufs'], traces_possibles: [], nom_inco: 'ŒUFS',
    conservation_j_froid: 28, conservation_j_ambiant: 21, conservation_j_surgele: null,
    instructions_conservation: 'Conserver coquille intacte, réfrigérer après achat',
    apres_ouverture: null,
  },
  'Œuf entier': {
    prix_eur_par_g: 0.0051, prix_unitaire_eur: 0.28, unite_prix: 'piece',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: ['oeufs'], traces_possibles: [], nom_inco: 'ŒUFS',
    conservation_j_froid: 28, conservation_j_ambiant: 21, conservation_j_surgele: null,
    instructions_conservation: 'Conserver coquille intacte, réfrigérer après achat',
    apres_ouverture: null,
  },
  "Jaunes d'œufs": {
    prix_eur_par_g: 0.0139, prix_unitaire_eur: 0.25, unite_prix: 'piece',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: ['oeufs'], traces_possibles: [], nom_inco: 'ŒUFS',
    conservation_j_froid: 2, conservation_j_ambiant: null, conservation_j_surgele: 365,
    instructions_conservation: 'Filmer au contact, réfrigérer immédiatement',
    apres_ouverture: '2 j max',
  },
  "Jaune d'œuf": {
    prix_eur_par_g: 0.0139, prix_unitaire_eur: 0.25, unite_prix: 'piece',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: ['oeufs'], traces_possibles: [], nom_inco: 'ŒUFS',
    conservation_j_froid: 2, conservation_j_ambiant: null, conservation_j_surgele: 365,
    instructions_conservation: 'Filmer au contact, réfrigérer immédiatement',
    apres_ouverture: '2 j max',
  },
  "Blancs d'œufs": {
    prix_eur_par_g: 0.0033, prix_unitaire_eur: 0.10, unite_prix: 'piece',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: ['oeufs'], traces_possibles: [], nom_inco: 'ŒUFS',
    conservation_j_froid: 3, conservation_j_ambiant: null, conservation_j_surgele: 365,
    instructions_conservation: 'Conserver dans un récipient hermétique au réfrigérateur',
    apres_ouverture: '3 j max',
  },
  "Blanc d'œuf": {
    prix_eur_par_g: 0.0033, prix_unitaire_eur: 0.10, unite_prix: 'piece',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: ['oeufs'], traces_possibles: [], nom_inco: 'ŒUFS',
    conservation_j_froid: 3, conservation_j_ambiant: null, conservation_j_surgele: 365,
    instructions_conservation: 'Conserver dans un récipient hermétique au réfrigérateur',
    apres_ouverture: '3 j max',
  },

  // ── Sucrants ─────────────────────────────────────────────────────────────────
  'Sucre semoule': {
    prix_eur_par_g: 0.0011, prix_unitaire_eur: 1.10, unite_prix: 'kg',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: [], traces_possibles: [], nom_inco: null,
    conservation_j_froid: null, conservation_j_ambiant: 730, conservation_j_surgele: null,
    instructions_conservation: 'Conserver au sec, à l\'abri de l\'humidité',
    apres_ouverture: null,
  },
  'Sucre glace': {
    prix_eur_par_g: 0.0013, prix_unitaire_eur: 1.30, unite_prix: 'kg',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: [], traces_possibles: [], nom_inco: null,
    conservation_j_froid: null, conservation_j_ambiant: 365, conservation_j_surgele: null,
    instructions_conservation: 'Conserver dans un récipient hermétique, craint l\'humidité',
    apres_ouverture: null,
  },
  'Cassonade': {
    prix_eur_par_g: 0.0014, prix_unitaire_eur: 1.40, unite_prix: 'kg',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: [], traces_possibles: [], nom_inco: null,
    conservation_j_froid: null, conservation_j_ambiant: 730, conservation_j_surgele: null,
    instructions_conservation: 'Conserver dans un récipient hermétique',
    apres_ouverture: null,
  },
  'Sucre de coco': {
    prix_eur_par_g: 0.0065, prix_unitaire_eur: 6.50, unite_prix: 'kg',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: [], traces_possibles: [], nom_inco: null,
    conservation_j_froid: null, conservation_j_ambiant: 730, conservation_j_surgele: null,
    instructions_conservation: 'Conserver dans un récipient hermétique au sec',
    apres_ouverture: null,
  },
  'Sucre de coco (mixé finement)': {
    prix_eur_par_g: 0.0065, prix_unitaire_eur: 6.50, unite_prix: 'kg',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: [], traces_possibles: [], nom_inco: null,
    conservation_j_froid: null, conservation_j_ambiant: 730, conservation_j_surgele: null,
    instructions_conservation: 'Conserver dans un récipient hermétique au sec',
    apres_ouverture: null,
  },
  'Glucose': {
    prix_eur_par_g: 0.0038, prix_unitaire_eur: 3.80, unite_prix: 'kg',
    fournisseur: 'Louis François', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: [], traces_possibles: [], nom_inco: null,
    conservation_j_froid: null, conservation_j_ambiant: 365, conservation_j_surgele: null,
    instructions_conservation: 'Conserver en récipient fermé, à l\'abri de la chaleur',
    apres_ouverture: null,
  },
  "Sirop d'érable": {
    prix_eur_par_g: 0.0120, prix_unitaire_eur: 12.00, unite_prix: 'kg',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: [], traces_possibles: [], nom_inco: null,
    conservation_j_froid: 365, conservation_j_ambiant: 730, conservation_j_surgele: null,
    instructions_conservation: 'Réfrigérer après ouverture',
    apres_ouverture: '365 j au réfrigérateur',
  },
  'Miel d\'acacia': {
    prix_eur_par_g: 0.0080, prix_unitaire_eur: 8.00, unite_prix: 'kg',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: [], traces_possibles: [], nom_inco: null,
    conservation_j_froid: null, conservation_j_ambiant: 1825, conservation_j_surgele: null,
    instructions_conservation: 'Conserver à température ambiante, à l\'abri de la lumière',
    apres_ouverture: null,
  },

  // ── Chocolats et couvertures ─────────────────────────────────────────────────
  'Chocolat noir 70%': {
    prix_eur_par_g: 0.0140, prix_unitaire_eur: 14.00, unite_prix: 'kg',
    fournisseur: 'Valrhona', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: ['soja'], traces_possibles: ['lait'], nom_inco: 'SOJA',
    conservation_j_froid: null, conservation_j_ambiant: 365, conservation_j_surgele: null,
    instructions_conservation: 'Conserver entre 16 et 18 °C, à l\'abri de la lumière et de l\'humidité',
    apres_ouverture: null,
  },
  'Couverture noir 64%': {
    prix_eur_par_g: 0.0130, prix_unitaire_eur: 13.00, unite_prix: 'kg',
    fournisseur: 'Valrhona', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: ['soja'], traces_possibles: ['lait'], nom_inco: 'SOJA',
    conservation_j_froid: null, conservation_j_ambiant: 365, conservation_j_surgele: null,
    instructions_conservation: 'Conserver entre 16 et 18 °C, à l\'abri de la lumière',
    apres_ouverture: null,
  },
  'Couverture lait': {
    prix_eur_par_g: 0.0115, prix_unitaire_eur: 11.50, unite_prix: 'kg',
    fournisseur: 'Valrhona', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: ['lait', 'soja'], traces_possibles: [], nom_inco: 'LAIT · SOJA',
    conservation_j_froid: null, conservation_j_ambiant: 365, conservation_j_surgele: null,
    instructions_conservation: 'Conserver entre 16 et 18 °C, à l\'abri de la lumière',
    apres_ouverture: null,
  },
  'Couverture blanc': {
    prix_eur_par_g: 0.0105, prix_unitaire_eur: 10.50, unite_prix: 'kg',
    fournisseur: 'Valrhona', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: ['lait', 'soja'], traces_possibles: [], nom_inco: 'LAIT · SOJA',
    conservation_j_froid: null, conservation_j_ambiant: 270, conservation_j_surgele: null,
    instructions_conservation: 'Conserver entre 16 et 18 °C — le blanc est plus fragile à la chaleur',
    apres_ouverture: null,
  },
  'Couverture blond': {
    prix_eur_par_g: 0.0180, prix_unitaire_eur: 18.00, unite_prix: 'kg',
    fournisseur: 'Valrhona', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: ['lait', 'soja'], traces_possibles: [], nom_inco: 'LAIT · SOJA',
    conservation_j_froid: null, conservation_j_ambiant: 270, conservation_j_surgele: null,
    instructions_conservation: 'Conserver entre 16 et 18 °C',
    apres_ouverture: null,
  },
  'Gianduja fondu': {
    prix_eur_par_g: 0.0220, prix_unitaire_eur: 22.00, unite_prix: 'kg',
    fournisseur: 'Valrhona', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: ['lait', 'fruits_a_coque_noisette'], traces_possibles: ['fruits_a_coque_amande'],
    nom_inco: 'LAIT · NOISETTES',
    conservation_j_froid: null, conservation_j_ambiant: 90, conservation_j_surgele: null,
    instructions_conservation: 'Conserver entre 14 et 18 °C, à l\'abri de la lumière',
    apres_ouverture: null,
  },

  // ── Purées de fruits ─────────────────────────────────────────────────────────
  'Purée de framboise': {
    prix_eur_par_g: 0.0120, prix_unitaire_eur: 12.00, unite_prix: 'kg',
    fournisseur: 'Capfruit', date_maj_prix: '2025-01-01', prix_variable_saison: true,
    allergenes_inco: [], traces_possibles: [], nom_inco: null,
    conservation_j_froid: 4, conservation_j_ambiant: null, conservation_j_surgele: 365,
    instructions_conservation: 'Réfrigérer après ouverture, consommer rapidement',
    apres_ouverture: '4 j au réfrigérateur',
  },
  'Purée de fraise': {
    prix_eur_par_g: 0.0095, prix_unitaire_eur: 9.50, unite_prix: 'kg',
    fournisseur: 'Capfruit', date_maj_prix: '2025-01-01', prix_variable_saison: true,
    allergenes_inco: [], traces_possibles: [], nom_inco: null,
    conservation_j_froid: 4, conservation_j_ambiant: null, conservation_j_surgele: 365,
    instructions_conservation: 'Réfrigérer après ouverture',
    apres_ouverture: '4 j',
  },
  'Purée de mangue': {
    prix_eur_par_g: 0.0100, prix_unitaire_eur: 10.00, unite_prix: 'kg',
    fournisseur: 'Capfruit', date_maj_prix: '2025-01-01', prix_variable_saison: true,
    allergenes_inco: [], traces_possibles: [], nom_inco: null,
    conservation_j_froid: 4, conservation_j_ambiant: null, conservation_j_surgele: 365,
    instructions_conservation: 'Réfrigérer après ouverture',
    apres_ouverture: '4 j',
  },
  'Purée de fruit de la passion': {
    prix_eur_par_g: 0.0145, prix_unitaire_eur: 14.50, unite_prix: 'kg',
    fournisseur: 'Capfruit', date_maj_prix: '2025-01-01', prix_variable_saison: true,
    allergenes_inco: [], traces_possibles: [], nom_inco: null,
    conservation_j_froid: 4, conservation_j_ambiant: null, conservation_j_surgele: 365,
    instructions_conservation: 'Réfrigérer après ouverture',
    apres_ouverture: '4 j',
  },
  "Purée d'abricot": {
    prix_eur_par_g: 0.0080, prix_unitaire_eur: 8.00, unite_prix: 'kg',
    fournisseur: 'Capfruit', date_maj_prix: '2025-01-01', prix_variable_saison: true,
    allergenes_inco: [], traces_possibles: [], nom_inco: null,
    conservation_j_froid: 4, conservation_j_ambiant: null, conservation_j_surgele: 365,
    instructions_conservation: 'Réfrigérer après ouverture',
    apres_ouverture: '4 j',
  },

  // ── Gélatine / texturants ─────────────────────────────────────────────────────
  'Gélatine 200 bloom': {
    prix_eur_par_g: 0.0280, prix_unitaire_eur: 28.00, unite_prix: 'kg',
    fournisseur: 'Louis François', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: [], traces_possibles: [], nom_inco: null,
    conservation_j_froid: null, conservation_j_ambiant: 365, conservation_j_surgele: null,
    instructions_conservation: 'Conserver au sec, entre 15 et 20 °C',
    apres_ouverture: null,
  },
  'Gélatine en feuilles': {
    prix_eur_par_g: 0.0280, prix_unitaire_eur: 28.00, unite_prix: 'kg',
    fournisseur: 'Louis François', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: [], traces_possibles: [], nom_inco: null,
    conservation_j_froid: null, conservation_j_ambiant: 365, conservation_j_surgele: null,
    instructions_conservation: 'Conserver au sec',
    apres_ouverture: null,
  },
  'Agar-agar': {
    prix_eur_par_g: 0.0350, prix_unitaire_eur: 35.00, unite_prix: 'kg',
    fournisseur: 'Louis François', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: [], traces_possibles: [], nom_inco: null,
    conservation_j_froid: null, conservation_j_ambiant: 730, conservation_j_surgele: null,
    instructions_conservation: 'Conserver dans un récipient hermétique, au sec',
    apres_ouverture: null,
  },
  'Pectine NH': {
    prix_eur_par_g: 0.0450, prix_unitaire_eur: 45.00, unite_prix: 'kg',
    fournisseur: 'Louis François', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: [], traces_possibles: [], nom_inco: null,
    conservation_j_froid: null, conservation_j_ambiant: 730, conservation_j_surgele: null,
    instructions_conservation: 'Conserver dans un récipient hermétique, au sec',
    apres_ouverture: null,
  },

  // ── Farines et amidons ────────────────────────────────────────────────────────
  'Farine T45': {
    prix_eur_par_g: 0.0014, prix_unitaire_eur: 1.40, unite_prix: 'kg',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: ['gluten'], traces_possibles: [], nom_inco: 'GLUTEN',
    conservation_j_froid: null, conservation_j_ambiant: 365, conservation_j_surgele: null,
    instructions_conservation: 'Conserver dans un récipient hermétique, au sec',
    apres_ouverture: null,
  },
  'Farine T55': {
    prix_eur_par_g: 0.0012, prix_unitaire_eur: 1.20, unite_prix: 'kg',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: ['gluten'], traces_possibles: [], nom_inco: 'GLUTEN',
    conservation_j_froid: null, conservation_j_ambiant: 365, conservation_j_surgele: null,
    instructions_conservation: 'Conserver dans un récipient hermétique, au sec',
    apres_ouverture: null,
  },
  'Farine': {
    prix_eur_par_g: 0.0012, prix_unitaire_eur: 1.20, unite_prix: 'kg',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: ['gluten'], traces_possibles: [], nom_inco: 'GLUTEN',
    conservation_j_froid: null, conservation_j_ambiant: 365, conservation_j_surgele: null,
    instructions_conservation: 'Conserver dans un récipient hermétique, au sec',
    apres_ouverture: null,
  },
  'Fécule de maïs': {
    prix_eur_par_g: 0.0022, prix_unitaire_eur: 2.20, unite_prix: 'kg',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: [], traces_possibles: [], nom_inco: null,
    conservation_j_froid: null, conservation_j_ambiant: 365, conservation_j_surgele: null,
    instructions_conservation: 'Conserver au sec, dans un récipient hermétique',
    apres_ouverture: null,
  },
  'Levure chimique': {
    prix_eur_par_g: 0.0045, prix_unitaire_eur: 4.50, unite_prix: 'kg',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: [], traces_possibles: ['gluten'], nom_inco: null,
    conservation_j_froid: null, conservation_j_ambiant: 365, conservation_j_surgele: null,
    instructions_conservation: 'Conserver dans un récipient hermétique, à l\'abri de l\'humidité',
    apres_ouverture: null,
  },

  // ── Oléagineux / pralinés ────────────────────────────────────────────────────
  "Poudre d'amande": {
    prix_eur_par_g: 0.0090, prix_unitaire_eur: 9.00, unite_prix: 'kg',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: ['fruits_a_coque_amande'], traces_possibles: ['fruits_a_coque_noisette'],
    nom_inco: 'AMANDES',
    conservation_j_froid: 90, conservation_j_ambiant: 30, conservation_j_surgele: 180,
    instructions_conservation: 'Réfrigérer après ouverture — les huiles s\'oxydent à température ambiante',
    apres_ouverture: '30 j hermétique au frais',
  },
  "Purée d'amande": {
    prix_eur_par_g: 0.0140, prix_unitaire_eur: 14.00, unite_prix: 'kg',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: ['fruits_a_coque_amande'], traces_possibles: [], nom_inco: 'AMANDES',
    conservation_j_froid: 90, conservation_j_ambiant: 30, conservation_j_surgele: 180,
    instructions_conservation: 'Réfrigérer après ouverture, remuer avant emploi',
    apres_ouverture: '30 j au réfrigérateur',
  },
  'Pâte de noisette': {
    prix_eur_par_g: 0.0180, prix_unitaire_eur: 18.00, unite_prix: 'kg',
    fournisseur: 'Valrhona', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: ['fruits_a_coque_noisette'], traces_possibles: ['fruits_a_coque_amande'],
    nom_inco: 'NOISETTES',
    conservation_j_froid: 90, conservation_j_ambiant: 30, conservation_j_surgele: 180,
    instructions_conservation: 'Réfrigérer après ouverture',
    apres_ouverture: '30 j au réfrigérateur',
  },
  'Praliné noisette': {
    prix_eur_par_g: 0.0160, prix_unitaire_eur: 16.00, unite_prix: 'kg',
    fournisseur: 'Valrhona', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: ['fruits_a_coque_noisette'], traces_possibles: ['fruits_a_coque_amande', 'lait'],
    nom_inco: 'NOISETTES',
    conservation_j_froid: null, conservation_j_ambiant: 60, conservation_j_surgele: null,
    instructions_conservation: 'Conserver dans un récipient hermétique entre 16 et 18 °C',
    apres_ouverture: '60 j',
  },
  'Pâte de pistache': {
    prix_eur_par_g: 0.0550, prix_unitaire_eur: 55.00, unite_prix: 'kg',
    fournisseur: 'Sevarome', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: ['fruits_a_coque_pistache'], traces_possibles: ['fruits_a_coque_amande', 'fruits_a_coque_noisette'],
    nom_inco: 'PISTACHES',
    conservation_j_froid: 90, conservation_j_ambiant: 30, conservation_j_surgele: 180,
    instructions_conservation: 'Réfrigérer après ouverture, conserver à l\'abri de la lumière',
    apres_ouverture: '30 j au réfrigérateur',
  },
  'Feuilletine (paillettes)': {
    prix_eur_par_g: 0.0085, prix_unitaire_eur: 8.50, unite_prix: 'kg',
    fournisseur: 'Louis François', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: ['gluten', 'lait'], traces_possibles: ['oeufs', 'soja'], nom_inco: 'GLUTEN · LAIT',
    conservation_j_froid: null, conservation_j_ambiant: 60, conservation_j_surgele: null,
    instructions_conservation: 'Conserver dans un récipient hermétique, à l\'abri de l\'humidité',
    apres_ouverture: '30 j hermétique',
  },
  'Brisures de feuilletine': {
    prix_eur_par_g: 0.0085, prix_unitaire_eur: 8.50, unite_prix: 'kg',
    fournisseur: 'Louis François', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: ['gluten', 'lait'], traces_possibles: ['oeufs', 'soja'], nom_inco: 'GLUTEN · LAIT',
    conservation_j_froid: null, conservation_j_ambiant: 60, conservation_j_surgele: null,
    instructions_conservation: 'Conserver dans un récipient hermétique',
    apres_ouverture: '30 j hermétique',
  },

  // ── Alternatives végétales ───────────────────────────────────────────────────
  'Lait de coco': {
    prix_eur_par_g: 0.0032, prix_unitaire_eur: 3.20, unite_prix: 'L',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: [], traces_possibles: [], nom_inco: null,
    conservation_j_froid: 5, conservation_j_ambiant: 730, conservation_j_surgele: null,
    instructions_conservation: 'Conserver à température ambiante avant ouverture, réfrigérer après',
    apres_ouverture: '5 j au réfrigérateur',
  },
  'Crème de coco': {
    prix_eur_par_g: 0.0040, prix_unitaire_eur: 4.00, unite_prix: 'L',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: [], traces_possibles: [], nom_inco: null,
    conservation_j_froid: 5, conservation_j_ambiant: 730, conservation_j_surgele: null,
    instructions_conservation: 'Conserver à température ambiante avant ouverture, réfrigérer après',
    apres_ouverture: '5 j au réfrigérateur',
  },
  'Aquafaba (eau de pois chiche)': {
    prix_eur_par_g: 0.0008, prix_unitaire_eur: 0.80, unite_prix: 'L',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: [], traces_possibles: [], nom_inco: null,
    conservation_j_froid: 4, conservation_j_ambiant: null, conservation_j_surgele: null,
    instructions_conservation: 'Réfrigérer immédiatement après préparation ou ouverture de boîte',
    apres_ouverture: '4 j',
  },

  // ── Divers ───────────────────────────────────────────────────────────────────
  'Eau': {
    prix_eur_par_g: 0.0000, prix_unitaire_eur: 0.00, unite_prix: 'L',
    fournisseur: null, date_maj_prix: null, prix_variable_saison: false,
    allergenes_inco: [], traces_possibles: [], nom_inco: null,
    conservation_j_froid: null, conservation_j_ambiant: null, conservation_j_surgele: null,
    instructions_conservation: null,
    apres_ouverture: null,
  },
  'Sel': {
    prix_eur_par_g: 0.0005, prix_unitaire_eur: 0.50, unite_prix: 'kg',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: [], traces_possibles: [], nom_inco: null,
    conservation_j_froid: null, conservation_j_ambiant: 3650, conservation_j_surgele: null,
    instructions_conservation: 'Conserver au sec',
    apres_ouverture: null,
  },
  'Fleur de sel': {
    prix_eur_par_g: 0.0080, prix_unitaire_eur: 8.00, unite_prix: 'kg',
    fournisseur: 'Metro', date_maj_prix: '2025-01-01', prix_variable_saison: false,
    allergenes_inco: [], traces_possibles: [], nom_inco: null,
    conservation_j_froid: null, conservation_j_ambiant: 3650, conservation_j_surgele: null,
    instructions_conservation: 'Conserver dans un récipient hermétique',
    apres_ouverture: null,
  },
};
